# Nettoyage & enrichissement des boxscores (minutes, DNP, totaux, ratios)

In [1]:
import pandas as pd
import numpy as np
import os
from datetime import datetime
from src.config import *
from src.utils import *
from src.feature_builder import *
from src.feature_aggregation import *

#display full columns
pd.set_option('display.max_column', None)
# pd.set_option('display.max_rows', None)
# pd.set_option('display.max_seq_items', None)
# pd.set_option('display.max_colwidth', 500)
# pd.set_option('expand_frame_repr', True)

In [2]:
#store start time of notebook
start_time = datetime.now()
print("Start time: ", start_time)

Start time:  2025-06-05 15:46:53.652941

# 🔁 Chargement des fichiers

In [3]:
boxscores_file = get_latest_file(DATA_LAST_BOXSCORES_BATCHES_MERGED_DIR)
games_file = get_latest_file(DATA_LAST_GAMES_MERGED_DIR)
df_boxscores = pd.read_csv(boxscores_file, dtype={'gameId': str})
df_games = pd.read_csv(games_file, dtype={'GAME_ID': str})

In [4]:
df_boxscores

,gameId,teamId,teamCity,teamName,teamTricode,teamSlug,personId,firstName,familyName,nameI,playerSlug,position,comment,jerseyNum,minutes,offensiveRating_advanced,defensiveRating_advanced,estimatedNetRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,oppPointsOffTurnovers_misc,oppPointsSecondChance_misc,oppPointsFastBreak_misc,oppPointsPaint_misc,blocksAgainst_misc,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,threePointersPercentage_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,freeThrowsPercentage_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,points_traditional,plusMinusPoints_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage
0,0021100005,1610612746,Los Angeles,Clippers,LAC,clippers,2406,Caron,Butler,C. Butler,caron-butler,F,NaN,NaN,36:01,112.9,87.3,22.9,25.5,0.174,0.00,26.7,0.000,0.238,0.125,0.0,0.450,0.486,0.133,93.37,93.96,70.0,0.208,0.508,0.559,0.099,0.377,0.231,0.172,0.368,2,0,0,2,5,15,11,32,1,2,0.700,0.300,0.545,0.364,0.273,0.000,0.182,0.182,0.182,1.000,0.000,1.0,0.0,1.000,0.000,4,10,1,3,0.333,2,3,0.667,0,10,10,4,3,0,0,0,11,17.0,0.148,0.169,0.167,0.188,0.105,0.091,0.000,0.417,0.294,0.235,0.000,0.375,0.000,0.167,0.000,0.077,0.139
1,0021100005,1610612746,Los Angeles,Clippers,LAC,clippers,201933,Blake,Griffin,B. Griffin,blake-griffin,F,NaN,NaN,34:44,112.3,86.2,24.0,26.2,0.056,0.33,3.8,0.135,0.049,0.090,11.5,0.500,0.511,0.321,89.11,89.83,65.0,0.096,0.484,0.344,0.092,0.355,0.210,0.188,0.421,5,5,4,16,4,17,9,30,1,9,1.000,0.000,0.818,0.091,0.000,0.182,0.182,0.227,0.727,0.778,0.222,0.0,0.0,0.778,0.222,9,18,0,0,0.000,4,8,0.500,5,2,7,1,2,0,3,4,22,17.0,0.333,0.295,0.000,0.000,0.286,0.381,0.455,0.091,0.212,0.063,0.500,0.250,0.000,0.125,0.333,0.409,0.301
2,0021100005,1610612746,Los Angeles,Clippers,LAC,clippers,201599,DeAndre,Jordan,D. Jordan,deandre-jordan,C,NaN,NaN,30:31,111.9,86.4,20.3,25.4,0.000,0.00,0.0,0.088,0.054,0.070,20.0,0.500,0.412,0.139,93.18,92.80,59.0,0.006,0.500,0.569,0.115,0.357,0.232,0.173,0.424,0,1,2,2,5,15,9,26,1,6,1.000,0.000,0.333,0.000,0.000,0.333,0.667,0.000,0.333,1.000,0.000,0.0,0.0,1.000,0.000,1,2,0,0,0.000,4,12,0.333,3,2,5,0,0,8,2,2,6,15.0,0.043,0.039,0.000,0.000,0.267,0.414,0.300,0.105,0.172,0.000,0.286,0.000,1.000,0.167,0.182,0.261,0.091
3,0021100005,1610612746,Los Angeles,Clippers,LAC,clippers,1497,Chauncey,Billups,C. Billups,chauncey-billups,G,NaN,NaN,38:19,112.5,87.5,21.1,25.0,0.167,4.00,14.8,0.000,0.119,0.060,3.7,0.395,0.485,0.267,90.44,90.22,72.0,0.133,0.478,0.353,0.082,0.383,0.313,0.184,0.385,3,2,2,4,5,16,11,36,3,6,0.474,0.526,0.286,0.095,0.429,0.095,0.286,0.143,0.190,0.000,1.000,1.0,0.0,0.500,0.500,6,19,3,10,0.300,6,6,1.000,0,5,5,4,0,0,1,2,21,18.0,0.200,0.279,0.600,0.526,0.375,0.250,0.000,0.208,0.143,0.250,0.167,0.000,0.000,0.429,0.154,0.250,0.259
4,0021100005,1610612746,Los Angeles,Clippers,LAC,clippers,101108,Chris,Paul,C. Paul,chris-paul,G,NaN,NaN,36:39,115.1,90.3,20.5,24.8,0.409,4.50,34.6,0.025,0.024,0.024,7.7,0.625,0.683,0.195,94.93,94.93,73.0,0.195,0.516,0.524,0.094,0.386,0.258,0.156,0.368,5,0,1,4,5,15,11,34,2,4,0.750,0.250,0.600,0.400,0.150,0.050,0.250,0.250,0.200,0.000,1.000,1.0,0.0,0.143,0.857,7,12,1,3,0.333,5,6,0.833,1,1,2,9,2,0,2,4,20,19.0,0.241,0.190,0.143,0.167,0.263,0.182,0.100,0.042,0.059,0.500,0.286,0.250,0.000,0.286,0.267,0.160,0.238
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256718,0021600744,1610612759,San Antonio,Spurs,SAS,spurs,201202,Joel,Anthony,J. Anthony,joel-anthony,NaN,NaN,NaN,12:34,74.1,86.2,-19.4,-12.1,0.000,0.00,0.0,0.143,0.118,0.129,0.0,0.667,0.667,0.100,98.41,106.96,27.0,0.160,0.381,0.190,0.233,0.480,0.160,0.116,0.235,0,2,0,4,6,5,6,12,0,1,1.000,0.000,1.000,0.000,0.000,0.000,0.000,0.000,1.000,1.000,0.000,0.0,0.0,1.000,0.000,2,3,0,0,0.000,0,0,0.000,2,2,4,0,1,1,0,1,4,-5.0,0.286,0.143,0.000,0.000,0.000,0.000,0.667,0.154,0.250,0.000,0.000,1.000,0.333,0.000,0.333,0.250,0.200
256719,0021600744,1610612759,San Antonio,Spurs,SAS,spurs,203937,Kyle,Anderson,K. Anderson,kyle-anderson,NaN,NaN,NaN,24:15,98.2,71.4,31.6,26.8,0.143,1.00,30.0,0.000,0.147,0.091,30.0,0.333,0.515,0.113,107.99,110.84,56.0,0.114,0.560,0.286,0.206,0.348,0.239,0.197,0.182,0,0,0,2,12,7,7,16,1,1,1.000,0.000,0.500,0.000,0.000,0.000,0.500,0.000,0.500,1.000,0.000,0.0,0.0,1.000,0.000,1,3,0,0,0.000,2,2,1.000,0,5,5,3,3,1,3,1,4,15.0,0.045,0.071,0.000,0.000,0.250,0.167,0.000,0.185,0.156,0.200,0.273,0.500,0.200,0.250,0.143,0.100,0.073
256720,0021600744,1610612759,San Antonio,Spurs,SAS,spurs,203613,Jonathon,Simmons,J. Simmons,jonathon-simmons,NaN,NaN,NaN,19:12,109.3,83.7,32.9,25.6,0.000,0.00,0.0,0.000,0.136,0.081,0.0,0.375,0.517,0.239,106.15,107.50,43.0,0.082,0.591,0.273,0.171,0.412,0.265,0.273,0.316,2,0,1,6,7,9,6,14,1,4,0.875,0.125,0.545,0.000,0.000,0.091,0.455,0.182,0.545,1.000,0.000,0.0,0.0,1.000,0.000,3,8,0,1,0.000,5,6,0.833,0,3,3,0,0,1,0,2,11,11.0,0.158,0.242,0.000,0.200,0.625,0.667,0.000,0.231,0.188,0.000,0.000,0.000,0.200,0.500,0.333,0.571,0.234
256721,0021600744,1610612759,San Antonio,Spurs,SAS,spurs,1627749,Dejounte,Murray,D. Murray,dejounte-murray,NaN,NaN,NaN,5:02,42.9,71.4,-40.6,-28.6,0.500,0.50,20.0,0.000,0.000,0.000,40.0,0.000,0.000,0.267,122.26,133.51,14.0,-0.471,0.222,0.444,0.291,0.500,0.222,0.253,0.167,0,0,0,0,2,2,4,6,0,0,0.500,0.500,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0,2,0,1,0.000,0,0,0.000,0,0,0,1,0,0,2,1,0,-4.0,0.000,0.222,0.000,0.500,0.000,0.000,0.000,0.000,0.000,0.500,0.500,0.000,0.000,0.000,0.500,0.000,0.000
256722,0021600744,1610612759,San Antonio,Spurs,SAS,spurs,1627854,Bryn,Forbes,B. Forbes,bryn-forbes,NaN,NaN,NaN,3:18,50.0,57.1,1.0,-7.1,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.125,100.95,109.09,8.0,-0.167,0.250,0.500,0.291,0.286,0.000,0.143,0.200,0,0,0,0,2,0,2,2,1,0,1.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0,1,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,0.0,0.000,0.250,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,1.000,0.000,0.000,0.000

In [5]:
df_games

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS,SEASON
0,22011,1610612746,LAC,Los Angeles Clippers,0021100005,2011-12-25,LAC @ GSW,W,240,105,37,81,0.457,8,23,0.348,23,38,0.605,13,30,43,22,9,8,10,19,19.0,2011-12
1,22011,1610612753,ORL,Orlando Magic,0021100004,2011-12-25,ORL @ OKC,L,240,89,30,81,0.370,8,28,0.286,21,26,0.808,14,31,45,18,7,4,18,25,-8.0,2011-12
2,22011,1610612747,LAL,Los Angeles Lakers,0021100003,2011-12-25,LAL vs. CHI,L,240,87,36,76,0.474,4,16,0.250,11,20,0.550,12,30,42,22,6,8,17,20,-1.0,2011-12
3,22011,1610612738,BOS,Boston Celtics,0021100001,2011-12-25,BOS @ NYK,L,240,104,39,76,0.513,2,5,0.400,24,31,0.774,13,28,41,28,7,5,18,28,-2.0,2011-12
4,22011,1610612744,GSW,Golden State Warriors,0021100005,2011-12-25,GSW vs. LAC,L,238,86,32,82,0.390,5,21,0.238,17,24,0.708,17,31,48,17,4,8,16,32,-19.0,2011-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35705,42024,1610612760,OKC,Oklahoma City Thunder,0042400315,2025-05-28,OKC vs. MIN,W,238,124,46,88,0.523,14,35,0.400,18,21,0.857,7,39,46,26,14,8,14,20,30.0,2024-25
35706,42024,1610612754,IND,Indiana Pacers,0042400305,2025-05-29,IND @ NYK,L,240,94,30,74,0.405,10,30,0.333,24,29,0.828,8,32,40,20,10,7,20,22,-17.0,2024-25
35707,42024,1610612752,NYK,New York Knicks,0042400305,2025-05-29,NYK vs. IND,W,241,111,44,89,0.494,8,29,0.276,15,22,0.682,11,34,45,22,11,3,15,22,17.0,2024-25
35708,42024,1610612752,NYK,New York Knicks,0042400306,2025-05-31,NYK @ IND,L,240,108,41,86,0.477,9,32,0.281,17,26,0.654,13,28,41,23,10,6,17,16,-17.0,2024-25
35709,42024,1610612754,IND,Indiana Pacers,0042400306,2025-05-31,IND vs. NYK,W,241,125,46,85,0.541,17,33,0.515,16,19,0.842,6,30,36,30,10,9,12,23,17.0,2024-25

# 🧼 Nettoyage des minutes jouées

In [6]:
def convert_minutes(val):
    if pd.isna(val) or val in ['DNP', '']:
        return 0.0
    try:
        parts = str(val).split(':')
        return int(parts[0]) + int(parts[1]) / 60 if len(parts) == 2 else float(val)
    except:
        return 0.0

df_boxscores['MINUTES_PLAYED'] = df_boxscores['minutes'].apply(convert_minutes)

# Rename gameId and teamId in boxscores

In [7]:
rename_columns = {
    'gameId': 'GAME_ID',
    'teamId': 'TEAM_ID',
}

df_boxscores.rename(columns=rename_columns, inplace=True)

# 🔄 Cast dynamique des colonnes numériques

In [8]:
numeric_cols = df_boxscores.select_dtypes(include=[np.number]).columns.tolist()
for col in numeric_cols:
    df_boxscores[col] = pd.to_numeric(df_boxscores[col], errors='coerce').fillna(0)

In [9]:
df_boxscores

,GAME_ID,TEAM_ID,teamCity,teamName,teamTricode,teamSlug,personId,firstName,familyName,nameI,playerSlug,position,comment,jerseyNum,minutes,offensiveRating_advanced,defensiveRating_advanced,estimatedNetRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,oppPointsOffTurnovers_misc,oppPointsSecondChance_misc,oppPointsFastBreak_misc,oppPointsPaint_misc,blocksAgainst_misc,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,threePointersPercentage_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,freeThrowsPercentage_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,points_traditional,plusMinusPoints_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage,MINUTES_PLAYED
0,0021100005,1610612746,Los Angeles,Clippers,LAC,clippers,2406,Caron,Butler,C. Butler,caron-butler,F,NaN,0.0,36:01,112.9,87.3,22.9,25.5,0.174,0.00,26.7,0.000,0.238,0.125,0.0,0.450,0.486,0.133,93.37,93.96,70.0,0.208,0.508,0.559,0.099,0.377,0.231,0.172,0.368,2,0,0,2,5,15,11,32,1,2,0.700,0.300,0.545,0.364,0.273,0.000,0.182,0.182,0.182,1.000,0.000,1.0,0.0,1.000,0.000,4,10,1,3,0.333,2,3,0.667,0,10,10,4,3,0,0,0,11,17.0,0.148,0.169,0.167,0.188,0.105,0.091,0.000,0.417,0.294,0.235,0.000,0.375,0.000,0.167,0.000,0.077,0.139,36.016667
1,0021100005,1610612746,Los Angeles,Clippers,LAC,clippers,201933,Blake,Griffin,B. Griffin,blake-griffin,F,NaN,0.0,34:44,112.3,86.2,24.0,26.2,0.056,0.33,3.8,0.135,0.049,0.090,11.5,0.500,0.511,0.321,89.11,89.83,65.0,0.096,0.484,0.344,0.092,0.355,0.210,0.188,0.421,5,5,4,16,4,17,9,30,1,9,1.000,0.000,0.818,0.091,0.000,0.182,0.182,0.227,0.727,0.778,0.222,0.0,0.0,0.778,0.222,9,18,0,0,0.000,4,8,0.500,5,2,7,1,2,0,3,4,22,17.0,0.333,0.295,0.000,0.000,0.286,0.381,0.455,0.091,0.212,0.063,0.500,0.250,0.000,0.125,0.333,0.409,0.301,34.733333
2,0021100005,1610612746,Los Angeles,Clippers,LAC,clippers,201599,DeAndre,Jordan,D. Jordan,deandre-jordan,C,NaN,0.0,30:31,111.9,86.4,20.3,25.4,0.000,0.00,0.0,0.088,0.054,0.070,20.0,0.500,0.412,0.139,93.18,92.80,59.0,0.006,0.500,0.569,0.115,0.357,0.232,0.173,0.424,0,1,2,2,5,15,9,26,1,6,1.000,0.000,0.333,0.000,0.000,0.333,0.667,0.000,0.333,1.000,0.000,0.0,0.0,1.000,0.000,1,2,0,0,0.000,4,12,0.333,3,2,5,0,0,8,2,2,6,15.0,0.043,0.039,0.000,0.000,0.267,0.414,0.300,0.105,0.172,0.000,0.286,0.000,1.000,0.167,0.182,0.261,0.091,30.516667
3,0021100005,1610612746,Los Angeles,Clippers,LAC,clippers,1497,Chauncey,Billups,C. Billups,chauncey-billups,G,NaN,0.0,38:19,112.5,87.5,21.1,25.0,0.167,4.00,14.8,0.000,0.119,0.060,3.7,0.395,0.485,0.267,90.44,90.22,72.0,0.133,0.478,0.353,0.082,0.383,0.313,0.184,0.385,3,2,2,4,5,16,11,36,3,6,0.474,0.526,0.286,0.095,0.429,0.095,0.286,0.143,0.190,0.000,1.000,1.0,0.0,0.500,0.500,6,19,3,10,0.300,6,6,1.000,0,5,5,4,0,0,1,2,21,18.0,0.200,0.279,0.600,0.526,0.375,0.250,0.000,0.208,0.143,0.250,0.167,0.000,0.000,0.429,0.154,0.250,0.259,38.316667
4,0021100005,1610612746,Los Angeles,Clippers,LAC,clippers,101108,Chris,Paul,C. Paul,chris-paul,G,NaN,0.0,36:39,115.1,90.3,20.5,24.8,0.409,4.50,34.6,0.025,0.024,0.024,7.7,0.625,0.683,0.195,94.93,94.93,73.0,0.195,0.516,0.524,0.094,0.386,0.258,0.156,0.368,5,0,1,4,5,15,11,34,2,4,0.750,0.250,0.600,0.400,0.150,0.050,0.250,0.250,0.200,0.000,1.000,1.0,0.0,0.143,0.857,7,12,1,3,0.333,5,6,0.833,1,1,2,9,2,0,2,4,20,19.0,0.241,0.190,0.143,0.167,0.263,0.182,0.100,0.042,0.059,0.500,0.286,0.250,0.000,0.286,0.267,0.160,0.238,36.650000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256718,0021600744,1610612759,San Antonio,Spurs,SAS,spurs,201202,Joel,Anthony,J. Anthony,joel-anthony,NaN,NaN,0.0,12:34,74.1,86.2,-19.4,-12.1,0.000,0.00,0.0,0.143,0.118,0.129,0.0,0.667,0.667,0.100,98.41,106.96,27.0,0.160,0.381,0.190,0.233,0.480,0.160,0.116,0.235,0,2,0,4,6,5,6,12,0,1,1.000,0.000,1.000,0.000,0.000,0.000,0.000,0.000,1.000,1.000,0.000,0.0,0.0,1.000,0.000,2,3,0,0,0.000,0,0,0.000,2,2,4,0,1,1,0,1,4,-5.0,0.286,0.143,0.000,0.000,0.000,0.000,0.667,0.154,0.250,0.000,0.000,1.000,0.333,0.000,0.333,0.250,0.200,12.566667
256719,0021600744,1610612759,San Antonio,Spurs,SAS,spurs,203937,Kyle,Anderson,K. Anderson,kyle-anderson,NaN,NaN,0.0,24:15,98.2,71.4,31.6,26.8,0.143,1.00,30.0,0.000,0.147,0.091,30.0,0.333,0.515,0.113,107.99,110.84,56.0,0.114,0.560,0.286,0.206,0.348,0.239,0.197,0.182,0,0,0,2,12,7,7,16,1,1,1.000,0.000,0.500,0.000,0.000,0.000,0.500,0.000,0.500,1.000,0.000,0.0,0.0,1.000,0.000,1,3,0,0,0.000,2,2,1.000,0,5,5,3,3,1,3,1,4,15.0,0.045,0.071,0.000,0.000,0.250,0.167,0.000,0.185,0.156,0.200,0.273,0.500,0.200,0.250,0.143,0.100,0.073,24.250000
256720,0021600744,1610612759,San Antonio,Spurs,SAS,spurs,203613,Jonathon,Simmons,J. Simmons,jonathon-simmons,NaN,NaN,0.0,19:12,109.3,83.7,32.9,25.6,0.000,0.00,0.0,0.000,0.136,0.081,0.0,0.375,0.517,0.239,106.15,107.50,43.0,0.082,0.591,0.273,0.171,0.412,0.265,0.273,0.316,2,0,1,6,7,9,6,14,1,4,0.875,0.125,0.545,0.000,0.000,0.091,0.455,0.182,0.545,1.000,0.000,0.0,0.0,1.000,0.000,3,8,0,1,0.000,5,6,0.833,0,3,3,0,0,1,0,2,11,11.0,0.158,0.242,0.000,0.200,0.625,0.667,0.000,0.231,0.188,0.000,0.000,0.000,0.200,0.500,0.333,0.571,0.234,19.200000
256721,0021600744,1610612759,San Antonio,Spurs,SAS,spurs,1627749,Dejounte,Murray,D. Murray,dejounte-murray,NaN,NaN,0.0,5:02,42.9,71.4,-40.6,-28.6,0.500,0.50,20.0,0.000,0.000,0.000,40.0,0.000,0.000,0.267,122.26,133.51,14.0,-0.471,0.222,0.444,0.291,0.500,0.222,0.253,0.167,0,0,0,0,2,2,4,6,0,0,0.500,0.500,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0,2,0,1,0.000,0,0,0.000,0,0,0,1,0,0,2,1,0,-4.0,0.000,0.222,0.000,0.500,0.000,0.000,0.000,0.000,0.000,0.500,0.500,0.000,0.000,0.000,0.500,0.000,0.000,5.033333
256722,0021600744,1610612759,San Antonio,Spurs,SAS,spurs,1627854,Bryn,Forbes,B. Forbes,bryn-forbes,NaN,NaN,0.0,3:18,50.0,57.1,1.0,-7.1,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.125,100.95,109.09,8.0,-0.167,0.250,0.500,0.291,0.286,0.000,0.143,0.200,0,0,0,0,2,0,2,2,1,0,1.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0,1,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,0.0,0.000,0.250,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,1.000,0.000,0.000,0.000,3.300000

# ⚙️ Aggrégation par équipe et match

## Définir les colonnes à sommer et à moyenner pondérées

In [10]:

cols_to_sum = [
    'fieldGoalsMade_traditional', 'fieldGoalsAttempted_traditional',
    'threePointersMade_traditional', 'threePointersAttempted_traditional',
    'freeThrowsMade_traditional', 'freeThrowsAttempted_traditional',
    'reboundsOffensive_traditional', 'reboundsDefensive_traditional',
    'reboundsTotal_traditional', 'assists_traditional', 'steals_traditional',
    'blocks_traditional', 'turnovers_traditional', 'foulsPersonal_traditional',
    'points_traditional', 'MINUTES_PLAYED',
    'pointsOffTurnovers_misc', 'pointsSecondChance_misc', 'pointsFastBreak_misc',
    'pointsPaint_misc', 'blocksAgainst_misc'
]

cols_to_weighted_avg = [
    'offensiveRating_advanced', 'defensiveRating_advanced', 'netRating_advanced',
    'assistPercentage_advanced', 'assistToTurnover_advanced', 'assistRatio_advanced',
    'offensiveReboundPercentage_advanced', 'defensiveReboundPercentage_advanced',
    'reboundPercentage_advanced', 'turnoverRatio_advanced', 'effectiveFieldGoalPercentage_advanced',
    'trueShootingPercentage_advanced', 'usagePercentage_advanced', 'estimatedPace_advanced',
    'pace_advanced', 'possessions_advanced', 'PIE_advanced',
    'effectiveFieldGoalPercentage_fourfactors', 'freeThrowAttemptRate_fourfactors',
    'teamTurnoverPercentage_fourfactors', 'oppEffectiveFieldGoalPercentage_fourfactors',
    'oppFreeThrowAttemptRate_fourfactors', 'oppTeamTurnoverPercentage_fourfactors',
    'oppOffensiveReboundPercentage_fourfactors', 'foulsDrawn_misc',
    'percentageFieldGoalsAttempted2pt_scoring', 'percentageFieldGoalsAttempted3pt_scoring',
    'percentagePoints2pt_scoring', 'percentagePointsMidrange2pt_scoring',
    'percentagePoints3pt_scoring', 'percentagePointsFastBreak_scoring',
    'percentagePointsFreeThrow_scoring', 'percentagePointsOffTurnovers_scoring',
    'percentagePointsPaint_scoring', 'percentageAssisted2pt_scoring',
    'percentageUnassisted2pt_scoring', 'percentageAssisted3pt_scoring',
    'percentageUnassisted3pt_scoring', 'percentageAssistedFGM_scoring',
    'percentageUnassistedFGM_scoring', 'threePointersPercentage_traditional',
    'freeThrowsPercentage_traditional', 'percentageFieldGoalsMade_usage',
    'percentageFieldGoalsAttempted_usage', 'percentageThreePointersMade_usage',
    'percentageThreePointersAttempted_usage', 'percentageFreeThrowsMade_usage',
    'percentageFreeThrowsAttempted_usage', 'percentageReboundsOffensive_usage',
    'percentageReboundsDefensive_usage', 'percentageReboundsTotal_usage',
    'percentageAssists_usage', 'percentageTurnovers_usage', 'percentageSteals_usage',
    'percentageBlocks_usage', 'percentageBlocksAllowed_usage', 'percentagePersonalFouls_usage',
    'percentagePersonalFoulsDrawn_usage', 'percentagePoints_usage','plusMinusPoints_traditional'
]

## 📊 Agrégation des données par équipe et match

In [11]:

# 1. Agrégation par somme
group_keys = ['GAME_ID', 'TEAM_ID']
sum_agg = df_boxscores[group_keys + cols_to_sum].copy()
sum_agg = sum_agg.groupby(group_keys).sum().reset_index()

# 2. Agrégation pondérée par les minutes jouées
weighted_agg = compute_weighted_mean_features(df_boxscores, group_keys, cols_to_weighted_avg, weight_col='MINUTES_PLAYED')

# 3. Fusion des deux agrégats
team_match_stats = pd.merge(sum_agg, weighted_agg, on=group_keys, how='left')

# 4. Identifier l'équipe adverse
teams_in_game = df_boxscores.groupby('GAME_ID')['TEAM_ID'].unique().to_dict()
team_match_stats['OPP_TEAM_ID'] = team_match_stats.apply(
    lambda row: [tid for tid in teams_in_game[row['GAME_ID']] if tid != row['TEAM_ID']][0], axis=1
)

# Ajout GAME_DATE

In [12]:
df_games['GAME_DATE'] = pd.to_datetime(df_games['GAME_DATE'])
team_match_stats = team_match_stats.merge(
    df_games[['GAME_ID', 'TEAM_ID', 'GAME_DATE']],
    on=['GAME_ID', 'TEAM_ID'],
    how='left'
)

In [13]:

team_match_stats

,GAME_ID,TEAM_ID,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,points_traditional,MINUTES_PLAYED,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,blocksAgainst_misc,offensiveRating_advanced,defensiveRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,threePointersPercentage_traditional,freeThrowsPercentage_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage,plusMinusPoints_traditional,OPP_TEAM_ID,GAME_DATE
0,0021100001,1610612738,78,152,4,10,48,62,26,56,82,56,14,10,36,56,208,480.066667,46,28,32,96,22,108.222233,111.932634,-3.694161,0.181532,0.790279,22.503020,0.061573,0.134002,0.097899,12.900889,0.453896,0.519213,0.191597,96.309683,95.611487,58.667477,0.105580,0.527782,0.418177,0.197031,0.535076,0.465478,0.165281,0.219223,3.478475,0.872849,0.063896,0.657995,0.198006,0.047118,0.093738,0.194901,0.231660,0.459988,0.644765,0.207825,0.157062,0.000000,0.662670,0.189920,0.104760,0.573335,0.193987,0.196816,0.157062,0.168254,0.215569,0.209100,0.174194,0.209209,0.198993,0.198954,0.194672,0.192078,0.164272,0.199008,0.197277,0.190504,0.198690,-0.024024,1610612752,2011-12-25
1,0021100001,1610612752,70,148,18,40,54,68,16,46,62,34,18,22,32,50,212,480.000000,36,30,16,60,10,111.690535,109.301778,2.391958,0.126097,0.960625,16.776063,0.036982,0.110483,0.073473,14.148785,0.504104,0.548899,0.195513,96.300708,95.199224,58.210000,0.093249,0.532830,0.466765,0.163975,0.523165,0.416090,0.198781,0.364813,3.618611,0.703230,0.259062,0.478796,0.197675,0.193396,0.055705,0.228786,0.154347,0.281354,0.426875,0.474098,0.536753,0.034983,0.528409,0.372563,0.320129,0.490452,0.193849,0.199039,0.163932,0.188751,0.187076,0.185633,0.201746,0.190901,0.189602,0.193623,0.204452,0.185782,0.199473,0.217573,0.210196,0.199814,0.195756,0.530694,1610612738,2011-12-25
2,0021100002,1610612742,62,164,18,56,46,60,16,46,62,46,20,0,34,58,188,480.000000,58,16,20,56,12,93.242326,103.892722,-10.645875,0.188613,0.796389,16.193778,0.030597,0.109217,0.064217,14.164944,0.391964,0.461304,0.197981,103.019453,100.899090,46.477153,0.117762,0.434031,0.369116,0.161587,0.505683,0.459455,0.227592,0.393651,2.579861,0.629453,0.370547,0.391193,0.121015,0.262616,0.061630,0.209038,0.240364,0.270300,0.328070,0.305263,0.478194,0.000000,0.617390,0.185249,0.184064,0.483051,0.198304,0.197585,0.187880,0.189499,0.214503,0.226300,0.227590,0.208331,0.209382,0.200089,0.199635,0.185659,0.000000,0.181193,0.187694,0.207550,0.203267,-9.322639,1610612748,2011-12-25
3,0021100002,1610612748,76,156,8,14,50,72,30,72,102,36,18,12,44,56,210,480.000000,50,20,62,88,0,105.091562,92.652757,12.443250,0.123284,0.772721,12.838507,0.066478,0.135241,0.105986,17.983465,0.548017,0.573978,0.193178,103.019219,101.200267,55.740139,0.072708,0.511090,0.458427,0.225250,0.430919,0.370513,0.164162,0.173621,3.905417,0.882384,0.093172,0.629823,0.131434,0.119080,0.257134,0.197556,0.148850,0.498103,0.335987,0.533666,0.175347,0.000000,0.445607,0.500851,0.144625,0.468889,0.202118,0.202054,0.175347,0.118316,0.169824,0.176898,0.183416,0.194325,0.196766,0.170766,0.187428,0.176683,0.189969,0.000000,0.197006,0.180527,0.195534,8.956736,1610612742,2011-12-25
4,0021100003,1610612741,72,178,14,30,18,28,32,50,82,42,28,8,28,42,176,480.000000,34,24,24,84,16,98.512514,97.707549,0.800771,0.153143,0.610694,15.807715,0.059251,0.116565,0.084043,11.089632,0.436749,0.453350,0.196549,91.481810,89.301101,51.621736,0.096233,0.442985,0.157266,0.149571,0.504284,0.265141,0.187859,0.324516,2.305347,0.844803,0.155197,0.700210,0.256993,0.155816,0.111500,0.103209,0.164463,0.443353,0.568812,0.337577,0.259236,0.100000,0.622291,0.336945,0.173209,0.306806,0.192869,0.200243,0.197162,0.200000,0.198159,0.193702,0.198053,0.203510,0.200116,0.198273,0.194801,0.203793,0.176597,0.193993,0.206829,0.192603,0.194224,2.834097,1610612747,2011-12-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15281,0041600403,1610612744,40,83,16,33,22,24,8,36,44,29,8,4,18,28,118,240.000000,20,16,24,38,3,117.980799,111.665500,6.310889,0.173779,2.263830,21.133632,0.036072,0.134347,0.090214,13.509750,0.502234,0.573268,0.195801,103.278042,100.600913,64.662361,0.119599,0.577433,0.290488,0.173693,0.511252,0.280507,0.116964,0.215773,3.422361,0.575468,0.355018,0.385675,0.062151,0.315288,0.163209,0.206661,0.124450,0.323694,0.485312,0.372812,0.476646,0.150854,0.608594,0.249531,0.322034,0.820182,0.205225,0.198118,0.186505,0.189137,0.195056,0.193311,0.197842,0.194358,0.196588,0.199610,0.205726,0.209342,0.162535,0.173448,0.196886,0.208574,0.204704,4.875486,1610612739,2017-06-07
15282,0041600404,1610612739,46,87,24,45,21,31,11,30,41,27,6,3,11,24,137,240.000000,18,21,8,36,6,143.924910,119.523819,24.386257,0.149844,1.804391,18.908194,0.046927,0.114640,0.086014,9.386729,0.689620,0.679870,0.199086,99.739830,96.300538,59.229375,0.114793,0.673553,0.375250,0.110169,0.512060,0.423046,0.120607,0.345281,3.343958,0.477771,0.503340,0.351049,0.036364,0.463307,0.055852,0.166755,0.120214,0.314855,0.393108,0.359878,0.530494,0.201242,0.610991,0.360676,0.421328,0.521120,0.196054,0.197244,0.194162,0.199496,0.182723,0.184374,0.177800,0.193797,0.195700,0.196336,0.198007,0.173863,0.177222,0.230764,0.206584,0.188966,0.198006,12.064236,1610612744,2017-06-09
15283,0041600404,1610612744,39,87,11,39,27,36,16,24,40,26,5,6,12,27,116,240.016667,10,15,9,40,3,120.743719,143.609847,-22.860322,0.164756,1.827392,17.123998,0.058239,0.116001,0.083350,7.918735,0.529264,0.550556,0.198723,99.742829,95.901633,57.778488,0.081546,0.511071,0.416414,0.120787,0.670647,0.389597,0.110226,0.307564,3.248247,0.573239,0.404957,0.483369,0.137821,0.303444,0.053873,0.191704,0.070989,0.345548,0.444746,0.358115,0.439657,0.242448,0.644541,0.333655,0.179176,0.532532,0.198969,0.200153,0.215102,0.212193,0.183401,0.190034,0.182420,0.205007,0.202139,0.212347,0.209803,0.198060,0.141515,0.235296,0.210750,0.188151,0.201036,-11.987501,1610612739,2017-06-09
15284,0041600405,1610612739,47,88,11,24,15,23,12,28,40,22,6,5,14,22,120,240.000000,25,20,25,62,2,121.789722,127.352653,-5.543674,0.128000,1.207535,14.285500,0.051772,0.120648,0.085652,11.077937,0.582644,0.607025,0.198684,101.720536,100.101136,68.871528,0.088589,0.596013,0.264821,0.147290,0.590410,0.319451,0.126091,0.312421,3.637778,0.640640,0.359360,0.512974,0.059288,0.265161,0.178492,0.154206,0.201363,0.454052,0.395738,0.462804,0.562263,0.048640,0.458412,0.474297,0.349970,0.438142,0.194622,0.199423,0.178921,0.192735,0.288973,0.269110,0.216840,0.200830,0.202585,0.196317,0.183021,0.191947,0.196169,0.186875,0.186402,0.206406,0.197266,-5.704444,1610612744,2017-06-12
15285,0041600405,1610612744,46,90,14,38,23,28,13,29,42,27,8,2,13,24,129,240.000000,21,15,18,52,5,128.643153,122.172042,6.487667,0.150365,1.179740,18.494819,0.053119,0.120246,0.089912,8.272854,0.547206,0.580721,0.196525,101.718108,99.399156,71.476250,0.107421,0.588877,0.312834,0.126243,0.594327,0.261859,0.147807,0.297210,3.339028,0.585860,0.409695,0.440319,0.090306,0.367593,0.126848,0.146631,0.146715,0.350013,0.540470,0.413905,0.536320,0.284374,0.604034,0.350341,0.321765,0.484646,0.199070,0.200313,0.193364,0.201004,0.192431,0.190246,0.184667,0.191379,0.202238,0.199951,0.185956,0.205464,0.185833,0.212326,0.195920,0.196442,0.198527,8.909583,1610612739,2017-06-12

# 🔁 Merge avec l’adversaire

In [14]:
team_cols = [col for col in team_match_stats.columns if col not in ['GAME_ID', 'TEAM_ID', 'OPP_TEAM_ID']]
opp_cols = [f"OPP_{col}" for col in team_cols]
df_opp = team_match_stats.rename(columns={col: f"OPP_{col}" for col in team_cols}).rename(
    columns={'TEAM_ID': 'OPP_TEAM_ID', 'OPP_TEAM_ID': 'TEAM_ID'})
match_dataset = pd.merge(
    team_match_stats,
    df_opp[['GAME_ID', 'TEAM_ID'] + opp_cols],
    on=['GAME_ID', 'TEAM_ID'],
    how='left'
)

In [15]:
match_dataset.columns

Index(['GAME_ID', 'TEAM_ID', 'fieldGoalsMade_traditional',
       'fieldGoalsAttempted_traditional', 'threePointersMade_traditional',
       'threePointersAttempted_traditional', 'freeThrowsMade_traditional',
       'freeThrowsAttempted_traditional', 'reboundsOffensive_traditional',
       'reboundsDefensive_traditional',
       ...
       'OPP_percentageAssists_usage', 'OPP_percentageTurnovers_usage',
       'OPP_percentageSteals_usage', 'OPP_percentageBlocks_usage',
       'OPP_percentageBlocksAllowed_usage',
       'OPP_percentagePersonalFouls_usage',
       'OPP_percentagePersonalFoulsDrawn_usage', 'OPP_percentagePoints_usage',
       'OPP_plusMinusPoints_traditional', 'OPP_GAME_DATE'],
      dtype='object', length=167)

In [16]:
match_dataset

,GAME_ID,TEAM_ID,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,points_traditional,MINUTES_PLAYED,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,blocksAgainst_misc,offensiveRating_advanced,defensiveRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,threePointersPercentage_traditional,freeThrowsPercentage_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage,plusMinusPoints_traditional,OPP_TEAM_ID,GAME_DATE,OPP_fieldGoalsMade_traditional,OPP_fieldGoalsAttempted_traditional,OPP_threePointersMade_traditional,OPP_threePointersAttempted_traditional,OPP_freeThrowsMade_traditional,OPP_freeThrowsAttempted_traditional,OPP_reboundsOffensive_traditional,OPP_reboundsDefensive_traditional,OPP_reboundsTotal_traditional,OPP_assists_traditional,OPP_steals_traditional,OPP_blocks_traditional,OPP_turnovers_traditional,OPP_foulsPersonal_traditional,OPP_points_traditional,OPP_MINUTES_PLAYED,OPP_pointsOffTurnovers_misc,OPP_pointsSecondChance_misc,OPP_pointsFastBreak_misc,OPP_pointsPaint_misc,OPP_blocksAgainst_misc,OPP_offensiveRating_advanced,OPP_defensiveRating_advanced,OPP_netRating_advanced,OPP_assistPercentage_advanced,OPP_assistToTurnover_advanced,OPP_assistRatio_advanced,OPP_offensiveReboundPercentage_advanced,OPP_defensiveReboundPercentage_advanced,OPP_reboundPercentage_advanced,OPP_turnoverRatio_advanced,OPP_effectiveFieldGoalPercentage_advanced,OPP_trueShootingPercentage_advanced,OPP_usagePercentage_advanced,OPP_estimatedPace_advanced,OPP_pace_advanced,OPP_possessions_advanced,OPP_PIE_advanced,OPP_effectiveFieldGoalPercentage_fourfactors,OPP_freeThrowAttemptRate_fourfactors,OPP_teamTurnoverPercentage_fourfactors,OPP_oppEffectiveFieldGoalPercentage_fourfactors,OPP_oppFreeThrowAttemptRate_fourfactors,OPP_oppTeamTurnoverPercentage_fourfactors,OPP_oppOffensiveReboundPercentage_fourfactors,OPP_foulsDrawn_misc,OPP_percentageFieldGoalsAttempted2pt_scoring,OPP_percentageFieldGoalsAttempted3pt_scoring,OPP_percentagePoints2pt_scoring,OPP_percentagePointsMidrange2pt_scoring,OPP_percentagePoints3pt_scoring,OPP_percentagePointsFastBreak_scoring,OPP_percentagePointsFreeThrow_scoring,OPP_percentagePointsOffTurnovers_scoring,OPP_percentagePointsPaint_scoring,OPP_percentageAssisted2pt_scoring,OPP_percentageUnassisted2pt_scoring,OPP_percentageAssisted3pt_scoring,OPP_percentageUnassisted3pt_scoring,OPP_percentageAssistedFGM_scoring,OPP_percentageUnassistedFGM_scoring,OPP_threePointersPercentage_traditional,OPP_freeThrowsPercentage_traditional,OPP_percentageFieldGoalsMade_usage,OPP_percentageFieldGoalsAttempted_usage,OPP_percentageThreePointersMade_usage,OPP_percentageThreePointersAttempted_usage,OPP_percentageFreeThrowsMade_usage,OPP_percentageFreeThrowsAttempted_usage,OPP_percentageReboundsOffensive_usage,OPP_percentageReboundsDefensive_usage,OPP_percentageReboundsTotal_usage,OPP_percentageAssists_usage,OPP_percentageTurnovers_usage,OPP_percentageSteals_usage,OPP_percentageBlocks_usage,OPP_percentageBlocksAllowed_usage,OPP_percentagePersonalFouls_usage,OPP_percentagePersonalFoulsDrawn_usage,OPP_percentagePoints_usage,OPP_plusMinusPoints_traditional,OPP_GAME_DATE
0,0021100001,1610612738,78,152,4,10,48,62,26,56,82,56,14,10,36,56,208,480.066667,46,28,32,96,22,108.222233,111.932634,-3.694161,0.181532,0.790279,22.503020,0.061573,0.134002,0.097899,12.900889,0.453896,0.519213,0.191597,96.309683,95.611487,58.667477,0.105580,0.527782,0.418177,0.197031,0.535076,0.465478,0.165281,0.219223,3.478475,0.872849,0.063896,0.657995,0.198006,0.047118,0.093738,0.194901,0.231660,0.459988,0.644765,0.207825,0.157062,0.000000,0.662670,0.189920,0.104760,0.573335,0.193987,0.196816,0.157062,0.168254,0.215569,0.209100,0.174194,0.209209,0.198993,0.198954,0.194672,0.192078,0.164272,0.199008,0.197277,0.190504,0.198690,-0.024024,1610612752,2011-12-25,70,148,18,40,54,68,16,46,62,34,18,22,32,50,212,480.000000,36,30,16,60,10,111.690535,109.301778,2.391958,0.126097,0.960625,16.776063,0.036982,0.110483,0.073473,14.148785,0.504104,0.548899,0.195513,96.300708,95.199224,58.210000,0.093249,0.532830,0.466765,0.163975,0.523165,0.416090,0.198781,0.364813,3.618611,0.703230,0.259062,0.478796,0.197675,0.193396,0.055705,0.228786,0.154347,0.281354,0.426875,0.474098,0.536753,0.034983,0.528409,0.372563,0.320129,0.490452,0.193849,0.199039,0.163932,0.188751,0.187076,0.185633,0.201746,0.190901,0.189602,0.193623,0.204452,0.185782,0.199473,0.217573,0.210196,0.199814,0.195756,0.530694,2011-12-25
1,0021100001,1610612752,70,148,18,40,54,68,16,46,62,34,18,22,32,50,212,480.000000,36,30,16,60,10,111.690535,109.301778,2.391958,0.126097,0.960625,16.776063,0.036982,0.110483,0.073473,14.148785,0.504104,0.548899,0.195513,96.300708,95.199224,58.210000,0.093249,0.532830,0.466765,0.163975,0.523165,0.416090,0.198781,0.364813,3.618611,0.703230,0.259062,0.478796,0.197675,0.193396,0.055705,0.228786,0.154347,0.281354,0.426875,0.474098,0.536753,0.034983,0.528409,0.372563,0.320129,0.490452,0.193849,0.199039,0.163932,0.188751,0.187076,0.185633,0.201746,0.190901,0.189602,0.193623,0.204452,0.185782,0.199473,0.217573,0.210196,0.199814,0.195756,0.530694,1610612738,2011-12-25,78,152,4,10,48,62,26,56,82,56,14,10,36,56,208,480.066667,46,28,32,96,22,108.222233,111.932634,-3.694161,0.181532,0.790279,22.503020,0.061573,0.134002,0.097899,12.900889,0.453896,0.519213,0.191597,96.309683,95.611487,58.667477,0.105580,0.527782,0.418177,0.197031,0.535076,0.465478,0.165281,0.219223,3.478475,0.872849,0.063896,0.657995,0.198006,0.047118,0.093738,0.194901,0.231660,0.459988,0.644765,0.207825,0.157062,0.000000,0.662670,0.189920,0.104760,0.573335,0.193987,0.196816,0.157062,0.168254,0.215569,0.209100,0.174194,0.209209,0.198993,0.198954,0.194672,0.192078,0.164272,0.199008,0.197277,0.190504,0.198690,-0.024024,2011-12-25
2,0021100002,1610612742,62,164,18,56,46,60,16,46,62,46,20,0,34,58,188,480.000000,58,16,20,56,12,93.242326,103.892722,-10.645875,0.188613,0.796389,16.193778,0.030597,0.109217,0.064217,14.164944,0.391964,0.461304,0.197981,103.019453,100.899090,46.477153,0.117762,0.434031,0.369116,0.161587,0.505683,0.459455,0.227592,0.393651,2.579861,0.629453,0.370547,0.391193,0.121015,0.262616,0.061630,0.209038,0.240364,0.270300,0.328070,0.305263,0.478194,0.000000,0.617390,0.185249,0.184064,0.483051,0.198304,0.197585,0.187880,0.189499,0.214503,0.226300,0.227590,0.208331,0.209382,0.200089,0.199635,0.185659,0.000000,0.181193,0.187694,0.207550,0.203267,-9.322639,1610612748,2011-12-25,76,156,8,14,50,72,30,72,102,36,18,12,44,56,210,480.000000,50,20,62,88,0,105.091562,92.652757,12.443250,0.123284,0.772721,12.838507,0.066478,0.135241,0.105986,17.983465,0.548017,0.573978,0.193178,103.019219,101.200267,55.740139,0.072708,0.511090,0.458427,0.225250,0.430919,0.370513,0.164162,0.173621,3.905417,0.882384,0.093172,0.629823,0.131434,0.119080,0.257134,0.197556,0.148850,0.498103,0.335987,0.533666,0.175347,0.000000,0.445607,0.500851,0.144625,0.468889,0.202118,0.202054,0.175347,0.118316,0.169824,0.176898,0.183416,0.194325,0.196766,0.170766,0.187428,0.176683,0.189969,0.000000,0.197006,0.180527,0.195534,8.956736,2011-12-25
3,0021100002,1610612748,76,156,8,14,50,72,30,72,102,36,18,12,44,56,210,480.000000,50,20,62,88,0,105.091562,92.652757,12.443250,0.123284,0.772721,12.838507,0.066478,0.135241,0.105986,17.983465,0.548017,0.573978,0.193178,103.019219,101.200267,55.740139,0.072708,0.511090,0.458427,0.225250,0.430919,0.370513,0.164162,0.173621,3.905417,0.882384,0.093172,0.629823,0.131434,0.119080,0.257134,0.197556,0.148850,0.498103,0.335987,0.533666,0.175347,0.000000,0.445607,0.500851,0.144625,0.468889,0.202118,0.202054,0.175347,0.118316,0.169824,0.176898,0.183416,0.194325,0.196766,0.170766,0.187428,0.176683,0.189969,0.000000,0.197006,0.180527,0.195534,8.956736,1610612742,2011-12-25,62,164,18,56,46,60,16,46,62,46,20,0,34,58,188,480.000000,58,16,20,56,12,93.242326,103.892722,-10.645875,0.188613,0.796389,16.193778,0.030597,0.109217,0.064217,14.164944,0.391964,0.461304,0.197981,103.019453,100.899090,46.477153,0.117762,0.434031,0.369116,0.161587,0.505683,0.459455,0.227592,0.393651,2.579861,0.629453,0.370547,0.391193,0.121015,0.262616,0.061630,0.209038,0.240364,0.270300,0.328070,0.305263,0.478194,0.000000,0.617390,0.185249,0.184064,0.483051,0.198304,0.197585,0.187880,0.189499,0.214503,0.226300,0.227590,0.208331,0.209382,0.200089,0.199635,0.185659,0.000000,0.181193,0.187694,0.207550,0.203267,-9.322639,2011-12-25
4,0021100003,1610612741,72,178,14,30,18,28,32,50,82,42,28,8,28,42,176,480.000000,34,24,24,84,16,98.512514,97.707549,0.800771,0.153143,0.610694,15.807715,0.059251,0.116565,0.084043,11.089632,0.436749,0.453350,0.196549,91.481810,89.301101,51.621736,0.096233,0.442985,0.157266,0.149571,0.504284,0.265141,0.187859,0.324516,2.305347,0.844803,0.155197,0.700210,0.256993,0.155816,0.111500,0.103209,0.164463,0.443353,0.568812,0.337577,0.259236,0.100000,0.622291,0.336945,0.173209,0.306806,0.192869,0.200243,0.197162,0.200000,0.198159,0.193702,0.198053,0.203510,0.200116,0.198273,0.194801,0.203793,0.176597,0.193993,0.206829,0.192603,0.194224,2.834097,1610612747,2011-12-25,72,152,8,32,22,40,24,60,84,44,12,16,34,40,174,480.000000,26,32,20,84,8,96.614681,99.695653,-3.095722,0.165185,1.128056,18.783563,0.051151,0.111076,0.085848,12.337771,0.509613,0.509765,0.197092,91.480246,88.900503,54.142847,0.112230,0.501000,0.263993,0.188597,0.445803,0.156010,0.149584,0.337517,2.869931,0.774221,0.225779,0.810646,0.203246,0.104479,0.165068,0.084875,0.189339,0.607400,0.640330,0.307170,0.104479,0.051979,0.666841,0.333159,0.069636,0.295267,0.205067,0.201467,0.086997,0.196560,0.240011,0.200699,0.185879,0.200551,0.200724,0.208811,0.194689,0.211188,0.204903,0.155219,0.217577,0.207932,0.206196,-1.166111,2011-12-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15281,0041600403,1610612744,40,83,16,33,22,24,8,36,44,29,8,4,18,28,118,240.000000,20,16,24,38,3,117.980799,111.665500,6.310889,0.173779,2.263830,21.133632,0.036072,0.134347,0.090214,13.509750,0.502234,0.573268,0.195801,103.278042,100.600913,64.662361,0.119599,0.577433,0.290488,0.173693,0.511252,0.280507,0.116964,0.215773,3.422361,0.575468,0.355018,0.385675,0.062151,0.315288,0.163209,0.206661,0.124450,0.323694,0.485312,0.372812,0.476646,0.150854,0.608594,0.249531,0.322034,0.820182,0.205225,0.198118,0.186505,0.189137,0.195056,0.193311,0.197842,0.194358,0.196588,0.199610,0.205726,0.209342,0.162535,0.173448,0.196886,0.208574,0.204704,4.875486,1610612739,2017-06-07,40,90,12,44,21,25,10,27,37,17,9,3,12,25,113,240.000000,22,4,13,46,4,112.192750,116.927354,-4.720549,0.119173,0.954868,13.653986,0.037721,0.125605,0.076939,10.204431,0.412466,0.480836,0.199898,103.280690,100.701731,70.813333,0.085712,0.512051,0.285126,0.116228,0.578830,0.288668,0.173060,0.238663,4.067431,0.436193,0.563807,0.288050,0.048796,0.319852,0.123806,0.280992,0.171715,0.239443,0.198677,0.276878,0.446406,0.142552,0.495870,0.278019,0.211608,0.630047,0.199595,0.200094,0.183834,0.201238,0.203199,0.204868,0.198250,0.215159,0.208537,0.191954,0.202722,0.195085,0.159474,0.203849,0.205012,0.195641,0.201695,-3.728264,2017-06-07
15282,0041600404,1610612739,46,87,24,45,21,31,11,30,41,27,6,3,11,24,137,240.000000,18,21,8,36,6,143.924910,119.523819,24.386257,0.149844,1.804391,18.908194,0.046927,0.114640,0.086014,9.386729,0.689620,0.679870,0.199086,99.739830,96.300538,59.229375,0.114793,0.673553,0.375250,0.110169,0.512060,0.423046,0.120607,0.345281,3.343958,0.477771,0.503340,0.351049,0.036364,0.463307,0.055852,0.166755,0.120214,0.314855,0.393108,0.359878,0.530494,0.201242,0.610991,0.360676,0.421328,0.521120,0.196054,0.197244,0.194162,0.199496,0.182723,0.184374,0.177800,0.193797,0.195700,0.196336,0.198007,0.173863,0.177222,0.230764,0.206584,0.188966,0.198006,12.064236,1610612744,2017-06-09,39,87,11,39,27,36,16,24,40,26,5,6,12,27,116,240.016667,10,15,9,40,3,120.743719,143.609847,-22.860322,0.164756,1.827392,17.123998,0.058239,0.116001,0.083350,7.918735,0.529264,0.550556,0.198723,99.742829,95.901633,57.778488,0.081546,0.511071,0.416414,0.120787,0.670647,0.389597,0.110226,0.307564,3.248247,0.573239,0.404957,0.483369,0.137821,0.303444,0.053873,0.191704,0.070989,0.345548,0.444746,0.358115,0.439657,0.242448,0.644541,0.333655,0.179176,0.532532,0.198969,0.200153,0.215102,0.212193,0.183401,0.190034,0.182420,0.205007,0.202139,0.212347,0.209803,0.198060,0.141515,0.235296,0.210750,0.188151,0.201036,-11.987501,2017-06-09
15283,0041600404,1610612744,39,87,11,39,27,36,16,24,40,26,5,6,12,27,116,240.016667,10,15,9,40,3,120.743719,143.609847,-22.860322,0.164756,1.827392,17.123998,0.058239,0.116001,0.083350,7.918735,0.529264,0.550556,0.198723,99.742829,95.901633,57.778488,0.081546,0.511071,0.416414,0.120787,0.670647,0.389597,0.110226,0.307564,3.248247,0.573239,0.404957,0.483369,0.137821,0.303444,0.053873,0.191704,0.070989,0.345548,0.444746,0.358115,0.439657,0.242448,0.644541,0.333655,0.179176,0.532532,0.198969,0.200153,0.215102,0.212193,0.183401,0.190034,0.182420,0.205007,0.202139,0.212347,0.209803,0.198060,0.141515,0.235296,0.210750,0.188151,0.201036,-11.987501,1610612739,2017-06-09,46,87,24,45,21,31,11,30,41,27,6,3,11,24,137,240.000000,18,21,8,36,6,143.924910,119.523819,24.386257,0.149844,1.804391,18.908194,0.046927,0.114640,0.086014,9.386729,0.689620,0.679870,0.199086,99.739830,96.300538,59.229375,0.114793,0.673553,0.375250,0.110169,0.512060,0.423046,0.120607,0.345281,3.343958,0.477771,0.503340,0.351049,0.036364,0.463307,0.055852,0.166755,0.120214,0.314855,0.393108,0.359878,0.530494,0.201242,0.610991,0.360676,0.421328,0.521120,0.196054,0.197244,0.194162,0.199496,0.182723,0.184374,0.177800,0.193797,0.195700,0.196336,0.198007,0.173863,0.177222,0.230764,0.206584,0.188966,0.198006,12.064236,2017-06-09
15284,0041600405,1610612739,47,88,11,24,15,23,12,28,40,22,6,5,14,22,120,240.000000,25,20,25,62,2,121.789722,127.352653,-5.543674,0.128000,1.207535,14.285500,0.051772,0.120648,0.085652,11.077937,0.582644,0.607025,0.198684,101.720536,100.101136,68.871528,0.088589,0.596013,0.264821,0.147290,0.590410,0.319451,0.126091,0.312421,3.637778,0.640640,0.359360,0.512974,0.059288,0.265161,0.178492,0.154206,0.201363,0.454052,0.395738,0.462804,0.562263,0.048640,0.458412,0.474297,0.349970,0.438142,0.194622,0.199423,0.178921,0.192735,0.288973,0.269110,0.216840,0.200830,0.202585,0.196317,0.183021,0.191947,0.196169,0.186875,0.186402,0.206406,0.197266,-5.704444,1610612744,2017-06-12,46,90,14,38,23,28,13,29,42,27,8,2,13,24,129,240.000000,21,15,18,52,5,128.643153,122.172042,6.487667,0.150365,1.179740,18.494819,0.053119,0.120246,0.089912,8.272854,0.547206,0.580721,0.196525,101.718108,99.399156,71.476250,0.107421,0.588877,0.312834,0.126243,0.594327,0.261859,0.147807,0.297210,3.339028,0.585860,0.409695,0.440319,0.090306,0.367593,0.126848,0.146631,0.146715,0.350013,0.540470,0.413905,0.536320,0.284374,0.604034,0.350341,0.321765,0.484646,0.199070,0.200313,0.193364,0.201004,0.192431,0.190246,0.184667,0.191379,0.202238,0.199951,0.185956,0.205464,0.185833,0.212326,0.195920,0.196442,0.198527,8.909583,2017-06-12
15285,0041600405,1610612744,46,90,14,38,23,28,13,29,42,27,8,2,13,24,129,240.000000,21,15,18,52,5,128.643153,122.172042,6.487667,0.150365,1.179740,18.494819,0.053119,0.120246,0.089912,8.272854,0.547206,0.580721,0.196525,101.718108,99.399156,71.476250,0.107421,0.588877,0.312834,0.126243,0.594327,0.261859,0.147807,0.297210,3.339028,0.585860,0.409695,0.440319,0.090306,0.367593,0.126848,0.146631,0.146715,0.350013,0.540470,0.413905,0.536320,0.284374,0.604034,0.350341,0.321765,0.484646,0.199070,0.200313,0.193364,0.201004,0.192431,0.190246,0.184667,0.191379,0.202238,0.199951,0.185956,0.205464,0.185833,0.212326,0.195920,0.196442,0.198527,8.909583,1610612739,2017-06-12,47,88,11,24,15,23,12,28,40,22,6,5,14,22,120,240.000000,25,20,25,62,2,121.789722,127.352653,-5.543674,0.128000,1.207535,14.285500,0.051772,0.120648,0.085652,11.077937,0.582644,0.607025,0.198684,101.720536,100.101136,68.871528,0.088589,0.596013,0.264821,0.147290,0.590410,0.319451,0.126091,0.312421,3.637778,0.640640,0.359360,0.512974,0.059288,0.265161,0.178492,0.154206,0.201363,0.454052,0.395738,0.462804,0.562263,0.048640,0.458412,0.474297,0.349970,0.438142,0.194622,0.199423,0.178921,0.192735,0.288973,0.269110,0.216840,0.200830,0.202585,0.196317,0.183021,0.191947,0.196169,0.186875,0.186402,0.206406,0.197266,-5.704444,2017-06-12

# 🏠 Ajout IS_HOME et IS_WIN

In [17]:
# Assurer le format datetime pour GAME_DATE
df_games['GAME_DATE'] = pd.to_datetime(df_games['GAME_DATE'])

# Merge avec les infos de match (MATCHUP, SEASON)
match_dataset = match_dataset.merge(
    df_games[['GAME_ID', 'TEAM_ID', 'MATCHUP', 'SEASON']],
    on=['GAME_ID', 'TEAM_ID'],
    how='left'
)

print("match_dataset after merge")
display(match_dataset)

# Définir si l'équipe joue à domicile
match_dataset['IS_HOME'] = match_dataset['MATCHUP'].str.contains('vs').astype(int)

# Calcul du résultat (win) et écart de points
match_dataset['IS_WIN'] = (match_dataset['points_traditional'] > match_dataset['OPP_points_traditional']).astype(int)
match_dataset['POINT_DIFF'] = match_dataset['points_traditional'] - match_dataset['OPP_points_traditional']

# Conversion GAME_DATE et tri
match_dataset['GAME_DATE'] = pd.to_datetime(match_dataset['GAME_DATE'])
match_dataset = match_dataset.sort_values(['GAME_DATE', 'GAME_ID']).reset_index(drop=True)

match_dataset after merge

,GAME_ID,TEAM_ID,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,points_traditional,MINUTES_PLAYED,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,blocksAgainst_misc,offensiveRating_advanced,defensiveRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,threePointersPercentage_traditional,freeThrowsPercentage_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage,plusMinusPoints_traditional,OPP_TEAM_ID,GAME_DATE,OPP_fieldGoalsMade_traditional,OPP_fieldGoalsAttempted_traditional,OPP_threePointersMade_traditional,OPP_threePointersAttempted_traditional,OPP_freeThrowsMade_traditional,OPP_freeThrowsAttempted_traditional,OPP_reboundsOffensive_traditional,OPP_reboundsDefensive_traditional,OPP_reboundsTotal_traditional,OPP_assists_traditional,OPP_steals_traditional,OPP_blocks_traditional,OPP_turnovers_traditional,OPP_foulsPersonal_traditional,OPP_points_traditional,OPP_MINUTES_PLAYED,OPP_pointsOffTurnovers_misc,OPP_pointsSecondChance_misc,OPP_pointsFastBreak_misc,OPP_pointsPaint_misc,OPP_blocksAgainst_misc,OPP_offensiveRating_advanced,OPP_defensiveRating_advanced,OPP_netRating_advanced,OPP_assistPercentage_advanced,OPP_assistToTurnover_advanced,OPP_assistRatio_advanced,OPP_offensiveReboundPercentage_advanced,OPP_defensiveReboundPercentage_advanced,OPP_reboundPercentage_advanced,OPP_turnoverRatio_advanced,OPP_effectiveFieldGoalPercentage_advanced,OPP_trueShootingPercentage_advanced,OPP_usagePercentage_advanced,OPP_estimatedPace_advanced,OPP_pace_advanced,OPP_possessions_advanced,OPP_PIE_advanced,OPP_effectiveFieldGoalPercentage_fourfactors,OPP_freeThrowAttemptRate_fourfactors,OPP_teamTurnoverPercentage_fourfactors,OPP_oppEffectiveFieldGoalPercentage_fourfactors,OPP_oppFreeThrowAttemptRate_fourfactors,OPP_oppTeamTurnoverPercentage_fourfactors,OPP_oppOffensiveReboundPercentage_fourfactors,OPP_foulsDrawn_misc,OPP_percentageFieldGoalsAttempted2pt_scoring,OPP_percentageFieldGoalsAttempted3pt_scoring,OPP_percentagePoints2pt_scoring,OPP_percentagePointsMidrange2pt_scoring,OPP_percentagePoints3pt_scoring,OPP_percentagePointsFastBreak_scoring,OPP_percentagePointsFreeThrow_scoring,OPP_percentagePointsOffTurnovers_scoring,OPP_percentagePointsPaint_scoring,OPP_percentageAssisted2pt_scoring,OPP_percentageUnassisted2pt_scoring,OPP_percentageAssisted3pt_scoring,OPP_percentageUnassisted3pt_scoring,OPP_percentageAssistedFGM_scoring,OPP_percentageUnassistedFGM_scoring,OPP_threePointersPercentage_traditional,OPP_freeThrowsPercentage_traditional,OPP_percentageFieldGoalsMade_usage,OPP_percentageFieldGoalsAttempted_usage,OPP_percentageThreePointersMade_usage,OPP_percentageThreePointersAttempted_usage,OPP_percentageFreeThrowsMade_usage,OPP_percentageFreeThrowsAttempted_usage,OPP_percentageReboundsOffensive_usage,OPP_percentageReboundsDefensive_usage,OPP_percentageReboundsTotal_usage,OPP_percentageAssists_usage,OPP_percentageTurnovers_usage,OPP_percentageSteals_usage,OPP_percentageBlocks_usage,OPP_percentageBlocksAllowed_usage,OPP_percentagePersonalFouls_usage,OPP_percentagePersonalFoulsDrawn_usage,OPP_percentagePoints_usage,OPP_plusMinusPoints_traditional,OPP_GAME_DATE,MATCHUP,SEASON
0,0021100001,1610612738,78,152,4,10,48,62,26,56,82,56,14,10,36,56,208,480.066667,46,28,32,96,22,108.222233,111.932634,-3.694161,0.181532,0.790279,22.503020,0.061573,0.134002,0.097899,12.900889,0.453896,0.519213,0.191597,96.309683,95.611487,58.667477,0.105580,0.527782,0.418177,0.197031,0.535076,0.465478,0.165281,0.219223,3.478475,0.872849,0.063896,0.657995,0.198006,0.047118,0.093738,0.194901,0.231660,0.459988,0.644765,0.207825,0.157062,0.000000,0.662670,0.189920,0.104760,0.573335,0.193987,0.196816,0.157062,0.168254,0.215569,0.209100,0.174194,0.209209,0.198993,0.198954,0.194672,0.192078,0.164272,0.199008,0.197277,0.190504,0.198690,-0.024024,1610612752,2011-12-25,70,148,18,40,54,68,16,46,62,34,18,22,32,50,212,480.000000,36,30,16,60,10,111.690535,109.301778,2.391958,0.126097,0.960625,16.776063,0.036982,0.110483,0.073473,14.148785,0.504104,0.548899,0.195513,96.300708,95.199224,58.210000,0.093249,0.532830,0.466765,0.163975,0.523165,0.416090,0.198781,0.364813,3.618611,0.703230,0.259062,0.478796,0.197675,0.193396,0.055705,0.228786,0.154347,0.281354,0.426875,0.474098,0.536753,0.034983,0.528409,0.372563,0.320129,0.490452,0.193849,0.199039,0.163932,0.188751,0.187076,0.185633,0.201746,0.190901,0.189602,0.193623,0.204452,0.185782,0.199473,0.217573,0.210196,0.199814,0.195756,0.530694,2011-12-25,BOS @ NYK,2011-12
1,0021100001,1610612752,70,148,18,40,54,68,16,46,62,34,18,22,32,50,212,480.000000,36,30,16,60,10,111.690535,109.301778,2.391958,0.126097,0.960625,16.776063,0.036982,0.110483,0.073473,14.148785,0.504104,0.548899,0.195513,96.300708,95.199224,58.210000,0.093249,0.532830,0.466765,0.163975,0.523165,0.416090,0.198781,0.364813,3.618611,0.703230,0.259062,0.478796,0.197675,0.193396,0.055705,0.228786,0.154347,0.281354,0.426875,0.474098,0.536753,0.034983,0.528409,0.372563,0.320129,0.490452,0.193849,0.199039,0.163932,0.188751,0.187076,0.185633,0.201746,0.190901,0.189602,0.193623,0.204452,0.185782,0.199473,0.217573,0.210196,0.199814,0.195756,0.530694,1610612738,2011-12-25,78,152,4,10,48,62,26,56,82,56,14,10,36,56,208,480.066667,46,28,32,96,22,108.222233,111.932634,-3.694161,0.181532,0.790279,22.503020,0.061573,0.134002,0.097899,12.900889,0.453896,0.519213,0.191597,96.309683,95.611487,58.667477,0.105580,0.527782,0.418177,0.197031,0.535076,0.465478,0.165281,0.219223,3.478475,0.872849,0.063896,0.657995,0.198006,0.047118,0.093738,0.194901,0.231660,0.459988,0.644765,0.207825,0.157062,0.000000,0.662670,0.189920,0.104760,0.573335,0.193987,0.196816,0.157062,0.168254,0.215569,0.209100,0.174194,0.209209,0.198993,0.198954,0.194672,0.192078,0.164272,0.199008,0.197277,0.190504,0.198690,-0.024024,2011-12-25,NYK vs. BOS,2011-12
2,0021100002,1610612742,62,164,18,56,46,60,16,46,62,46,20,0,34,58,188,480.000000,58,16,20,56,12,93.242326,103.892722,-10.645875,0.188613,0.796389,16.193778,0.030597,0.109217,0.064217,14.164944,0.391964,0.461304,0.197981,103.019453,100.899090,46.477153,0.117762,0.434031,0.369116,0.161587,0.505683,0.459455,0.227592,0.393651,2.579861,0.629453,0.370547,0.391193,0.121015,0.262616,0.061630,0.209038,0.240364,0.270300,0.328070,0.305263,0.478194,0.000000,0.617390,0.185249,0.184064,0.483051,0.198304,0.197585,0.187880,0.189499,0.214503,0.226300,0.227590,0.208331,0.209382,0.200089,0.199635,0.185659,0.000000,0.181193,0.187694,0.207550,0.203267,-9.322639,1610612748,2011-12-25,76,156,8,14,50,72,30,72,102,36,18,12,44,56,210,480.000000,50,20,62,88,0,105.091562,92.652757,12.443250,0.123284,0.772721,12.838507,0.066478,0.135241,0.105986,17.983465,0.548017,0.573978,0.193178,103.019219,101.200267,55.740139,0.072708,0.511090,0.458427,0.225250,0.430919,0.370513,0.164162,0.173621,3.905417,0.882384,0.093172,0.629823,0.131434,0.119080,0.257134,0.197556,0.148850,0.498103,0.335987,0.533666,0.175347,0.000000,0.445607,0.500851,0.144625,0.468889,0.202118,0.202054,0.175347,0.118316,0.169824,0.176898,0.183416,0.194325,0.196766,0.170766,0.187428,0.176683,0.189969,0.000000,0.197006,0.180527,0.195534,8.956736,2011-12-25,DAL vs. MIA,2011-12
3,0021100002,1610612748,76,156,8,14,50,72,30,72,102,36,18,12,44,56,210,480.000000,50,20,62,88,0,105.091562,92.652757,12.443250,0.123284,0.772721,12.838507,0.066478,0.135241,0.105986,17.983465,0.548017,0.573978,0.193178,103.019219,101.200267,55.740139,0.072708,0.511090,0.458427,0.225250,0.430919,0.370513,0.164162,0.173621,3.905417,0.882384,0.093172,0.629823,0.131434,0.119080,0.257134,0.197556,0.148850,0.498103,0.335987,0.533666,0.175347,0.000000,0.445607,0.500851,0.144625,0.468889,0.202118,0.202054,0.175347,0.118316,0.169824,0.176898,0.183416,0.194325,0.196766,0.170766,0.187428,0.176683,0.189969,0.000000,0.197006,0.180527,0.195534,8.956736,1610612742,2011-12-25,62,164,18,56,46,60,16,46,62,46,20,0,34,58,188,480.000000,58,16,20,56,12,93.242326,103.892722,-10.645875,0.188613,0.796389,16.193778,0.030597,0.109217,0.064217,14.164944,0.391964,0.461304,0.197981,103.019453,100.899090,46.477153,0.117762,0.434031,0.369116,0.161587,0.505683,0.459455,0.227592,0.393651,2.579861,0.629453,0.370547,0.391193,0.121015,0.262616,0.061630,0.209038,0.240364,0.270300,0.328070,0.305263,0.478194,0.000000,0.617390,0.185249,0.184064,0.483051,0.198304,0.197585,0.187880,0.189499,0.214503,0.226300,0.227590,0.208331,0.209382,0.200089,0.199635,0.185659,0.000000,0.181193,0.187694,0.207550,0.203267,-9.322639,2011-12-25,MIA @ DAL,2011-12
4,0021100003,1610612741,72,178,14,30,18,28,32,50,82,42,28,8,28,42,176,480.000000,34,24,24,84,16,98.512514,97.707549,0.800771,0.153143,0.610694,15.807715,0.059251,0.116565,0.084043,11.089632,0.436749,0.453350,0.196549,91.481810,89.301101,51.621736,0.096233,0.442985,0.157266,0.149571,0.504284,0.265141,0.187859,0.324516,2.305347,0.844803,0.155197,0.700210,0.256993,0.155816,0.111500,0.103209,0.164463,0.443353,0.568812,0.337577,0.259236,0.100000,0.622291,0.336945,0.173209,0.306806,0.192869,0.200243,0.197162,0.200000,0.198159,0.193702,0.198053,0.203510,0.200116,0.198273,0.194801,0.203793,0.176597,0.193993,0.206829,0.192603,0.194224,2.834097,1610612747,2011-12-25,72,152,8,32,22,40,24,60,84,44,12,16,34,40,174,480.000000,26,32,20,84,8,96.614681,99.695653,-3.095722,0.165185,1.128056,18.783563,0.051151,0.111076,0.085848,12.337771,0.509613,0.509765,0.197092,91.480246,88.900503,54.142847,0.112230,0.501000,0.263993,0.188597,0.445803,0.156010,0.149584,0.337517,2.869931,0.774221,0.225779,0.810646,0.203246,0.104479,0.165068,0.084875,0.189339,0.607400,0.640330,0.307170,0.104479,0.051979,0.666841,0.333159,0.069636,0.295267,0.205067,0.201467,0.086997,0.196560,0.240011,0.200699,0.185879,0.200551,0.200724,0.208811,0.194689,0.211188,0.204903,0.155219,0.217577,0.207932,0.206196,-1.166111,2011-12-25,CHI @ LAL,2011-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15281,0041600403,1610612744,40,83,16,33,22,24,8,36,44,29,8,4,18,28,118,240.000000,20,16,24,38,3,117.980799,111.665500,6.310889,0.173779,2.263830,21.133632,0.036072,0.134347,0.090214,13.509750,0.502234,0.573268,0.195801,103.278042,100.600913,64.662361,0.119599,0.577433,0.290488,0.173693,0.511252,0.280507,0.116964,0.215773,3.422361,0.575468,0.355018,0.385675,0.062151,0.315288,0.163209,0.206661,0.124450,0.323694,0.485312,0.372812,0.476646,0.150854,0.608594,0.249531,0.322034,0.820182,0.205225,0.198118,0.186505,0.189137,0.195056,0.193311,0.197842,0.194358,0.196588,0.199610,0.205726,0.209342,0.162535,0.173448,0.196886,0.208574,0.204704,4.875486,1610612739,2017-06-07,40,90,12,44,21,25,10,27,37,17,9,3,12,25,113,240.000000,22,4,13,46,4,112.192750,116.927354,-4.720549,0.119173,0.954868,13.653986,0.037721,0.125605,0.076939,10.204431,0.412466,0.480836,0.199898,103.280690,100.701731,70.813333,0.085712,0.512051,0.285126,0.116228,0.578830,0.288668,0.173060,0.238663,4.067431,0.436193,0.563807,0.288050,0.048796,0.319852,0.123806,0.280992,0.171715,0.239443,0.198677,0.276878,0.446406,0.142552,0.495870,0.278019,0.211608,0.630047,0.199595,0.200094,0.183834,0.201238,0.203199,0.204868,0.198250,0.215159,0.208537,0.191954,0.202722,0.195085,0.159474,0.203849,0.205012,0.195641,0.201695,-3.728264,2017-06-07,GSW @ CLE,2016-17
15282,0041600404,1610612739,46,87,24,45,21,31,11,30,41,27,6,3,11,24,137,240.000000,18,21,8,36,6,143.924910,119.523819,24.386257,0.149844,1.804391,18.908194,0.046927,0.114640,0.086014,9.386729,0.689620,0.679870,0.199086,99.739830,96.300538,59.229375,0.114793,0.673553,0.375250,0.110169,0.512060,0.423046,0.120607,0.345281,3.343958,0.477771,0.503340,0.351049,0.036364,0.463307,0.055852,0.166755,0.120214,0.314855,0.393108,0.359878,0.530494,0.201242,0.610991,0.360676,0.421328,0.521120,0.196054,0.197244,0.194162,0.199496,0.182723,0.184374,0.177800,0.193797,0.195700,0.196336,0.198007,0.173863,0.177222,0.230764,0.206584,0.188966,0.198006,12.064236,1610612744,2017-06-09,39,87,11,39,27,36,16,24,40,26,5,6,12,27,116,240.016667,10,15,9,40,3,120.743719,143.609847,-22.860322,0.164756,1.827392,17.123998,0.058239,0.116001,0.083350,7.918735,0.529264,0.550556,0.198723,99.742829,95.901633,57.778488,0.081546,0.511071,0.416414,0.120787,0.670647,0.389597,0.110226,0.307564,3.248247,0.573239,0.404957,0.483369,0.137821,0.303444,0.053873,0.191704,0.070989,0.345548,0.444746,0.358115,0.439657,0.242448,0.644541,0.333655,0.179176,0.532532,0.198969,0.200153,0.215102,0.212193,0.183401,0.190034,0.182420,0.205007,0.202139,0.212347,0.209803,0.198060,0.141515,0.235296,0.210750,0.188151,0.201036,-11.987501,2017-06-09,CLE vs. GSW,2016-17
15283,0041600404,1610612744,39,87,11,39,27,36,16,24,40,26,5,6,12,27,116,240.016667,10,15,9,40,3,120.743719,143.609847,-22.860322,0.164756,1.827392,17.123998,0.058239,0.116001,0.083350,7.918735,0.529264,0.550556,0.198723,99.742829,95.901633,57.778488,0.081546,0.511071,0.416414,0.120787,0.670647,0.389597,0.110226,0.307564,3.248247,0.573239,0.404957,0.483369,0.137821,0.303444,0.053873,0.191704,0.070989,0.345548,0.444746,0.358115,0.439657,0.242448,0.644541,0.333655,0.179176,0.532532,0.198969,0.200153,0.215102,0.212193,0.183401,0.190034,0.182420,0.205007,0.202139,0.212347,0.209803,0.198060,0.141515,0.235296,0.210750,0.188151,0.201036,-11.987501,1610612739,2017-06-09,46,87,24,45,21,31,11,30,41,27,6,3,11,24,137,240.000000,18,21,8,36,6,143.924910,119.523819,24.386257,0.149844,1.804391,18.908194,0.046927,0.114640,0.086014,9.386729,0.689620,0.679870,0.199086,99.739830,96.300538,59.229375,0.114793,0.673553,0.375250,0.110169,0.512060,0.423046,0.120607,0.345281,3.343958,0.477771,0.503340,0.351049,0.036364,0.463307,0.055852,0.166755,0.120214,0.314855,0.393108,0.359878,0.530494,0.201242,0.610991,0.360676,0.421328,0.521120,0.196054,0.197244,0.194162,0.199496,0.182723,0.184374,0.177800,0.193797,0.195700,0.196336,0.198007,0.173863,0.177222,0.230764,0.206584,0.188966,0.198006,12.064236,2017-06-09,GSW @ CLE,2016-17
15284,0041600405,1610612739,47,88,11,24,15,23,12,28,40,22,6,5,14,22,120,240.000000,25,20,25,62,2,121.789722,127.352653,-5.543674,0.128000,1.207535,14.285500,0.051772,0.120648,0.085652,11.077937,0.582644,0.607025,0.198684,101.720536,100.101136,68.871528,0.088589,0.596013,0.264821,0.147290,0.590410,0.319451,0.126091,0.312421,3.637778,0.640640,0.359360,0.512974,0.059288,0.265161,0.178492,0.154206,0.201363,0.454052,0.395738,0.462804,0.562263,0.048640,0.458412,0.474297,0.349970,0.438142,0.194622,0.199423,0.178921,0.192735,0.288973,0.269110,0.216840,0.200830,0.202585,0.196317,0.183021,0.191947,0.196169,0.186875,0.186402,0.206406,0.197266,-5.704444,1610612744,2017-06-12,46,90,14,38,23,28,13,29,42,27,8,2,13,24,129,240.000000,21,15,18,52,5,128.643153,122.172042,6.487667,0.150365,1.179740,18.494819,0.053119,0.120246,0.089912,8.272854,0.547206,0.580721,0.196525,101.718108,99.399156,71.476250,0.107421,0.588877,0.312834,0.126243,0.594327,0.261859,0.147807,0.297210,3.339028,0.585860,0.409695,0.440319,0.090306,0.367593,0.126848,0.146631,0.146715,0.350013,0.540470,0.413905,0.536320,0.284374,0.604034,0.350341,0.321765,0.484646,0.199070,0.200313,0.193364,0.201004,0.192431,0.190246,0.184667,0.191379,0.202238,0.199951,0.185956,0.205464,0.185833,0.212326,0.195920,0.196442,0.198527,8.909583,2017-06-12,CLE @ GSW,2016-17
15285,0041600405,1610612744,46,90,14,38,23,28,13,29,42,27,8,2,13,24,129,240.000000,21,15,18,52,5,128.643153,122.172042,6.487667,0.150365,1.179740,18.494819,0.053119,0.120246,0.089912,8.272854,0.547206,0.580721,0.196525,101.718108,99.399156,71.476250,0.107421,0.588877,0.312834,0.126243,0.594327,0.261859,0.147807,0.297210,3.339028,0.585860,0.409695,0.440319,0.090306,0.367593,0.126848,0.146631,0.146715,0.350013,0.540470,0.413905,0.536320,0.284374,0.604034,0.350341,0.321765,0.484646,0.199070,0.200313,0.193364,0.201004,0.192431,0.190246,0.184667,0.191379,0.202238,0.199951,0.185956,0.205464,0.185833,0.212326,0.195920,0.196442,0.198527,8.909583,1610612739,2017-06-12,47,88,11,24,15,23,12,28,40,22,6,5,14,22,120,240.000000,25,20,25,62,2,121.789722,127.352653,-5.543674,0.128000,1.207535,14.285500,0.051772,0.120648,0.085652,11.077937,0.582644,0.607025,0.198684,101.720536,100.101136,68.871528,0.088589,0.596013,0.264821,0.147290,0.590410,0.319451,0.126091,0.312421,3.637778,0.640640,0.359360,0.512974,0.059288,0.265161,0.178492,0.154206,0.201363,0.454052,0.395738,0.462804,0.562263,0.048640,0.458412,0.474297,0.349970,0.438142,0.194622,0.199423,0.178921,0.192735,0.288973,0.269110,0.216840,0.200830,0.202585,0.196317,0.183021,0.191947,0.196169,0.186875,0.186402,0.206406,0.197266,-5.704444,2017-06-12,GSW vs. CLE,2016-17

In [18]:
match_dataset

,GAME_ID,TEAM_ID,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,points_traditional,MINUTES_PLAYED,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,blocksAgainst_misc,offensiveRating_advanced,defensiveRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,threePointersPercentage_traditional,freeThrowsPercentage_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage,plusMinusPoints_traditional,OPP_TEAM_ID,GAME_DATE,OPP_fieldGoalsMade_traditional,OPP_fieldGoalsAttempted_traditional,OPP_threePointersMade_traditional,OPP_threePointersAttempted_traditional,OPP_freeThrowsMade_traditional,OPP_freeThrowsAttempted_traditional,OPP_reboundsOffensive_traditional,OPP_reboundsDefensive_traditional,OPP_reboundsTotal_traditional,OPP_assists_traditional,OPP_steals_traditional,OPP_blocks_traditional,OPP_turnovers_traditional,OPP_foulsPersonal_traditional,OPP_points_traditional,OPP_MINUTES_PLAYED,OPP_pointsOffTurnovers_misc,OPP_pointsSecondChance_misc,OPP_pointsFastBreak_misc,OPP_pointsPaint_misc,OPP_blocksAgainst_misc,OPP_offensiveRating_advanced,OPP_defensiveRating_advanced,OPP_netRating_advanced,OPP_assistPercentage_advanced,OPP_assistToTurnover_advanced,OPP_assistRatio_advanced,OPP_offensiveReboundPercentage_advanced,OPP_defensiveReboundPercentage_advanced,OPP_reboundPercentage_advanced,OPP_turnoverRatio_advanced,OPP_effectiveFieldGoalPercentage_advanced,OPP_trueShootingPercentage_advanced,OPP_usagePercentage_advanced,OPP_estimatedPace_advanced,OPP_pace_advanced,OPP_possessions_advanced,OPP_PIE_advanced,OPP_effectiveFieldGoalPercentage_fourfactors,OPP_freeThrowAttemptRate_fourfactors,OPP_teamTurnoverPercentage_fourfactors,OPP_oppEffectiveFieldGoalPercentage_fourfactors,OPP_oppFreeThrowAttemptRate_fourfactors,OPP_oppTeamTurnoverPercentage_fourfactors,OPP_oppOffensiveReboundPercentage_fourfactors,OPP_foulsDrawn_misc,OPP_percentageFieldGoalsAttempted2pt_scoring,OPP_percentageFieldGoalsAttempted3pt_scoring,OPP_percentagePoints2pt_scoring,OPP_percentagePointsMidrange2pt_scoring,OPP_percentagePoints3pt_scoring,OPP_percentagePointsFastBreak_scoring,OPP_percentagePointsFreeThrow_scoring,OPP_percentagePointsOffTurnovers_scoring,OPP_percentagePointsPaint_scoring,OPP_percentageAssisted2pt_scoring,OPP_percentageUnassisted2pt_scoring,OPP_percentageAssisted3pt_scoring,OPP_percentageUnassisted3pt_scoring,OPP_percentageAssistedFGM_scoring,OPP_percentageUnassistedFGM_scoring,OPP_threePointersPercentage_traditional,OPP_freeThrowsPercentage_traditional,OPP_percentageFieldGoalsMade_usage,OPP_percentageFieldGoalsAttempted_usage,OPP_percentageThreePointersMade_usage,OPP_percentageThreePointersAttempted_usage,OPP_percentageFreeThrowsMade_usage,OPP_percentageFreeThrowsAttempted_usage,OPP_percentageReboundsOffensive_usage,OPP_percentageReboundsDefensive_usage,OPP_percentageReboundsTotal_usage,OPP_percentageAssists_usage,OPP_percentageTurnovers_usage,OPP_percentageSteals_usage,OPP_percentageBlocks_usage,OPP_percentageBlocksAllowed_usage,OPP_percentagePersonalFouls_usage,OPP_percentagePersonalFoulsDrawn_usage,OPP_percentagePoints_usage,OPP_plusMinusPoints_traditional,OPP_GAME_DATE,MATCHUP,SEASON,IS_HOME,IS_WIN,POINT_DIFF
0,0021100001,1610612738,78,152,4,10,48,62,26,56,82,56,14,10,36,56,208,480.066667,46,28,32,96,22,108.222233,111.932634,-3.694161,0.181532,0.790279,22.503020,0.061573,0.134002,0.097899,12.900889,0.453896,0.519213,0.191597,96.309683,95.611487,58.667477,0.105580,0.527782,0.418177,0.197031,0.535076,0.465478,0.165281,0.219223,3.478475,0.872849,0.063896,0.657995,0.198006,0.047118,0.093738,0.194901,0.231660,0.459988,0.644765,0.207825,0.157062,0.000000,0.662670,0.189920,0.104760,0.573335,0.193987,0.196816,0.157062,0.168254,0.215569,0.209100,0.174194,0.209209,0.198993,0.198954,0.194672,0.192078,0.164272,0.199008,0.197277,0.190504,0.198690,-0.024024,1610612752,2011-12-25,70,148,18,40,54,68,16,46,62,34,18,22,32,50,212,480.000000,36,30,16,60,10,111.690535,109.301778,2.391958,0.126097,0.960625,16.776063,0.036982,0.110483,0.073473,14.148785,0.504104,0.548899,0.195513,96.300708,95.199224,58.210000,0.093249,0.532830,0.466765,0.163975,0.523165,0.416090,0.198781,0.364813,3.618611,0.703230,0.259062,0.478796,0.197675,0.193396,0.055705,0.228786,0.154347,0.281354,0.426875,0.474098,0.536753,0.034983,0.528409,0.372563,0.320129,0.490452,0.193849,0.199039,0.163932,0.188751,0.187076,0.185633,0.201746,0.190901,0.189602,0.193623,0.204452,0.185782,0.199473,0.217573,0.210196,0.199814,0.195756,0.530694,2011-12-25,BOS @ NYK,2011-12,0,0,-4
1,0021100001,1610612752,70,148,18,40,54,68,16,46,62,34,18,22,32,50,212,480.000000,36,30,16,60,10,111.690535,109.301778,2.391958,0.126097,0.960625,16.776063,0.036982,0.110483,0.073473,14.148785,0.504104,0.548899,0.195513,96.300708,95.199224,58.210000,0.093249,0.532830,0.466765,0.163975,0.523165,0.416090,0.198781,0.364813,3.618611,0.703230,0.259062,0.478796,0.197675,0.193396,0.055705,0.228786,0.154347,0.281354,0.426875,0.474098,0.536753,0.034983,0.528409,0.372563,0.320129,0.490452,0.193849,0.199039,0.163932,0.188751,0.187076,0.185633,0.201746,0.190901,0.189602,0.193623,0.204452,0.185782,0.199473,0.217573,0.210196,0.199814,0.195756,0.530694,1610612738,2011-12-25,78,152,4,10,48,62,26,56,82,56,14,10,36,56,208,480.066667,46,28,32,96,22,108.222233,111.932634,-3.694161,0.181532,0.790279,22.503020,0.061573,0.134002,0.097899,12.900889,0.453896,0.519213,0.191597,96.309683,95.611487,58.667477,0.105580,0.527782,0.418177,0.197031,0.535076,0.465478,0.165281,0.219223,3.478475,0.872849,0.063896,0.657995,0.198006,0.047118,0.093738,0.194901,0.231660,0.459988,0.644765,0.207825,0.157062,0.000000,0.662670,0.189920,0.104760,0.573335,0.193987,0.196816,0.157062,0.168254,0.215569,0.209100,0.174194,0.209209,0.198993,0.198954,0.194672,0.192078,0.164272,0.199008,0.197277,0.190504,0.198690,-0.024024,2011-12-25,NYK vs. BOS,2011-12,1,1,4
2,0021100002,1610612742,62,164,18,56,46,60,16,46,62,46,20,0,34,58,188,480.000000,58,16,20,56,12,93.242326,103.892722,-10.645875,0.188613,0.796389,16.193778,0.030597,0.109217,0.064217,14.164944,0.391964,0.461304,0.197981,103.019453,100.899090,46.477153,0.117762,0.434031,0.369116,0.161587,0.505683,0.459455,0.227592,0.393651,2.579861,0.629453,0.370547,0.391193,0.121015,0.262616,0.061630,0.209038,0.240364,0.270300,0.328070,0.305263,0.478194,0.000000,0.617390,0.185249,0.184064,0.483051,0.198304,0.197585,0.187880,0.189499,0.214503,0.226300,0.227590,0.208331,0.209382,0.200089,0.199635,0.185659,0.000000,0.181193,0.187694,0.207550,0.203267,-9.322639,1610612748,2011-12-25,76,156,8,14,50,72,30,72,102,36,18,12,44,56,210,480.000000,50,20,62,88,0,105.091562,92.652757,12.443250,0.123284,0.772721,12.838507,0.066478,0.135241,0.105986,17.983465,0.548017,0.573978,0.193178,103.019219,101.200267,55.740139,0.072708,0.511090,0.458427,0.225250,0.430919,0.370513,0.164162,0.173621,3.905417,0.882384,0.093172,0.629823,0.131434,0.119080,0.257134,0.197556,0.148850,0.498103,0.335987,0.533666,0.175347,0.000000,0.445607,0.500851,0.144625,0.468889,0.202118,0.202054,0.175347,0.118316,0.169824,0.176898,0.183416,0.194325,0.196766,0.170766,0.187428,0.176683,0.189969,0.000000,0.197006,0.180527,0.195534,8.956736,2011-12-25,DAL vs. MIA,2011-12,1,0,-22
3,0021100002,1610612748,76,156,8,14,50,72,30,72,102,36,18,12,44,56,210,480.000000,50,20,62,88,0,105.091562,92.652757,12.443250,0.123284,0.772721,12.838507,0.066478,0.135241,0.105986,17.983465,0.548017,0.573978,0.193178,103.019219,101.200267,55.740139,0.072708,0.511090,0.458427,0.225250,0.430919,0.370513,0.164162,0.173621,3.905417,0.882384,0.093172,0.629823,0.131434,0.119080,0.257134,0.197556,0.148850,0.498103,0.335987,0.533666,0.175347,0.000000,0.445607,0.500851,0.144625,0.468889,0.202118,0.202054,0.175347,0.118316,0.169824,0.176898,0.183416,0.194325,0.196766,0.170766,0.187428,0.176683,0.189969,0.000000,0.197006,0.180527,0.195534,8.956736,1610612742,2011-12-25,62,164,18,56,46,60,16,46,62,46,20,0,34,58,188,480.000000,58,16,20,56,12,93.242326,103.892722,-10.645875,0.188613,0.796389,16.193778,0.030597,0.109217,0.064217,14.164944,0.391964,0.461304,0.197981,103.019453,100.899090,46.477153,0.117762,0.434031,0.369116,0.161587,0.505683,0.459455,0.227592,0.393651,2.579861,0.629453,0.370547,0.391193,0.121015,0.262616,0.061630,0.209038,0.240364,0.270300,0.328070,0.305263,0.478194,0.000000,0.617390,0.185249,0.184064,0.483051,0.198304,0.197585,0.187880,0.189499,0.214503,0.226300,0.227590,0.208331,0.209382,0.200089,0.199635,0.185659,0.000000,0.181193,0.187694,0.207550,0.203267,-9.322639,2011-12-25,MIA @ DAL,2011-12,0,1,22
4,0021100003,1610612741,72,178,14,30,18,28,32,50,82,42,28,8,28,42,176,480.000000,34,24,24,84,16,98.512514,97.707549,0.800771,0.153143,0.610694,15.807715,0.059251,0.116565,0.084043,11.089632,0.436749,0.453350,0.196549,91.481810,89.301101,51.621736,0.096233,0.442985,0.157266,0.149571,0.504284,0.265141,0.187859,0.324516,2.305347,0.844803,0.155197,0.700210,0.256993,0.155816,0.111500,0.103209,0.164463,0.443353,0.568812,0.337577,0.259236,0.100000,0.622291,0.336945,0.173209,0.306806,0.192869,0.200243,0.197162,0.200000,0.198159,0.193702,0.198053,0.203510,0.200116,0.198273,0.194801,0.203793,0.176597,0.193993,0.206829,0.192603,0.194224,2.834097,1610612747,2011-12-25,72,152,8,32,22,40,24,60,84,44,12,16,34,40,174,480.000000,26,32,20,84,8,96.614681,99.695653,-3.095722,0.165185,1.128056,18.783563,0.051151,0.111076,0.085848,12.337771,0.509613,0.509765,0.197092,91.480246,88.900503,54.142847,0.112230,0.501000,0.263993,0.188597,0.445803,0.156010,0.149584,0.337517,2.869931,0.774221,0.225779,0.810646,0.203246,0.104479,0.165068,0.084875,0.189339,0.607400,0.640330,0.307170,0.104479,0.051979,0.666841,0.333159,0.069636,0.295267,0.205067,0.201467,0.086997,0.196560,0.240011,0.200699,0.185879,0.200551,0.200724,0.208811,0.194689,0.211188,0.204903,0.155219,0.217577,0.207932,0.206196,-1.166111,2011-12-25,CHI @ LAL,2011-12,0,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15281,0041600403,1610612744,40,83,16,33,22,24,8,36,44,29,8,4,18,28,118,240.000000,20,16,24,38,3,117.980799,111.665500,6.310889,0.173779,2.263830,21.133632,0.036072,0.134347,0.090214,13.509750,0.502234,0.573268,0.195801,103.278042,100.600913,64.662361,0.119599,0.577433,0.290488,0.173693,0.511252,0.280507,0.116964,0.215773,3.422361,0.575468,0.355018,0.385675,0.062151,0.315288,0.163209,0.206661,0.124450,0.323694,0.485312,0.372812,0.476646,0.150854,0.608594,0.249531,0.322034,0.820182,0.205225,0.198118,0.186505,0.189137,0.195056,0.193311,0.197842,0.194358,0.196588,0.199610,0.205726,0.209342,0.162535,0.173448,0.196886,0.208574,0.204704,4.875486,1610612739,2017-06-07,40,90,12,44,21,25,10,27,37,17,9,3,12,25,113,240.000000,22,4,13,46,4,112.192750,116.927354,-4.720549,0.119173,0.954868,13.653986,0.037721,0.125605,0.076939,10.204431,0.412466,0.480836,0.199898,103.280690,100.701731,70.813333,0.085712,0.512051,0.285126,0.116228,0.578830,0.288668,0.173060,0.238663,4.067431,0.436193,0.563807,0.288050,0.048796,0.319852,0.123806,0.280992,0.171715,0.239443,0.198677,0.276878,0.446406,0.142552,0.495870,0.278019,0.211608,0.630047,0.199595,0.200094,0.183834,0.201238,0.203199,0.204868,0.198250,0.215159,0.208537,0.191954,0.202722,0.195085,0.159474,0.203849,0.205012,0.195641,0.201695,-3.728264,2017-06-07,GSW @ CLE,2016-17,0,1,5
15282,0041600404,1610612739,46,87,24,45,21,31,11,30,41,27,6,3,11,24,137,240.000000,18,21,8,36,6,143.924910,119.523819,24.386257,0.149844,1.804391,18.908194,0.046927,0.114640,0.086014,9.386729,0.689620,0.679870,0.199086,99.739830,96.300538,59.229375,0.114793,0.673553,0.375250,0.110169,0.512060,0.423046,0.120607,0.345281,3.343958,0.477771,0.503340,0.351049,0.036364,0.463307,0.055852,0.166755,0.120214,0.314855,0.393108,0.359878,0.530494,0.201242,0.610991,0.360676,0.421328,0.521120,0.196054,0.197244,0.194162,0.199496,0.182723,0.184374,0.177800,0.193797,0.195700,0.196336,0.198007,0.173863,0.177222,0.230764,0.206584,0.188966,0.198006,12.064236,1610612744,2017-06-09,39,87,11,39,27,36,16,24,40,26,5,6,12,27,116,240.016667,10,15,9,40,3,120.743719,143.609847,-22.860322,0.164756,1.827392,17.123998,0.058239,0.116001,0.083350,7.918735,0.529264,0.550556,0.198723,99.742829,95.901633,57.778488,0.081546,0.511071,0.416414,0.120787,0.670647,0.389597,0.110226,0.307564,3.248247,0.573239,0.404957,0.483369,0.137821,0.303444,0.053873,0.191704,0.070989,0.345548,0.444746,0.358115,0.439657,0.242448,0.644541,0.333655,0.179176,0.532532,0.198969,0.200153,0.215102,0.212193,0.183401,0.190034,0.182420,0.205007,0.202139,0.212347,0.209803,0.198060,0.141515,0.235296,0.210750,0.188151,0.201036,-11.987501,2017-06-09,CLE vs. GSW,2016-17,1,1,21
15283,0041600404,1610612744,39,87,11,39,27,36,16,24,40,26,5,6,12,27,116,240.016667,10,15,9,40,3,120.743719,143.609847,-22.860322,0.164756,1.827392,17.123998,0.058239,0.116001,0.083350,7.918735,0.529264,0.550556,0.198723,99.742829,95.901633,57.778488,0.081546,0.511071,0.416414,0.120787,0.670647,0.389597,0.110226,0.307564,3.248247,0.573239,0.404957,0.483369,0.137821,0.303444,0.053873,0.191704,0.070989,0.345548,0.444746,0.358115,0.439657,0.242448,0.644541,0.333655,0.179176,0.532532,0.198969,0.200153,0.215102,0.212193,0.183401,0.190034,0.182420,0.205007,0.202139,0.212347,0.209803,0.198060,0.141515,0.235296,0.210750,0.188151,0.201036,-11.987501,1610612739,2017-06-09,46,87,24,45,21,31,11,30,41,27,6,3,11,24,137,240.000000,18,21,8,36,6,143.924910,119.523819,24.386257,0.149844,1.804391,18.908194,0.046927,0.114640,0.086014,9.386729,0.689620,0.679870,0.199086,99.739830,96.300538,59.229375,0.114793,0.673553,0.375250,0.110169,0.512060,0.423046,0.120607,0.345281,3.343958,0.477771,0.503340,0.351049,0.036364,0.463307,0.055852,0.166755,0.120214,0.314855,0.393108,0.359878,0.530494,0.201242,0.610991,0.360676,0.421328,0.521120,0.196054,0.197244,0.194162,0.199496,0.182723,0.184374,0.177800,0.193797,0.195700,0.196336,0.198007,0.173863,0.177222,0.230764,0.206584,0.188966,0.198006,12.064236,2017-06-09,GSW @ CLE,2016-17,0,0,-21
15284,0041600405,1610612739,47,88,11,24,15,23,12,28,40,22,6,5,14,22,120,240.000000,25,20,25,62,2,121.789722,127.352653,-5.543674,0.128000,1.207535,14.285500,0.051772,0.120648,0.085652,11.077937,0.582644,0.607025,0.198684,101.720536,100.101136,68.871528,0.088589,0.596013,0.264821,0.147290,0.590410,0.319451,0.126091,0.312421,3.637778,0.640640,0.359360,0.512974,0.059288,0.265161,0.178492,0.154206,0.201363,0.454052,0.395738,0.462804,0.562263,0.048640,0.458412,0.474297,0.349970,0.438142,0.194622,0.199423,0.178921,0.192735,0.288973,0.269110,0.216840,0.200830,0.202585,0.196317,0.183021,0.191947,0.196169,0.186875,0.186402,0.206406,0.197266,-5.704444,1610612744,2017-06-12,46,90,14,38,23,28,13,29,42,27,8,2,13,24,129,240.000000,21,15,18,52,5,128.643153,122.172042,6.487667,0.150365,1.179740,18.494819,0.053119,0.120246,0.089912,8.272854,0.547206,0.580721,0.196525,101.718108,99.399156,71.476250,0.107421,0.588877,0.312834,0.126243,0.594327,0.261859,0.147807,0.297210,3.339028,0.585860,0.409695,0.440319,0.090306,0.367593,0.126848,0.146631,0.146715,0.350013,0.540470,0.413905,0.536320,0.284374,0.604034,0.350341,0.321765,0.484646,0.199070,0.200313,0.193364,0.201004,0.192431,0.190246,0.184667,0.191379,0.202238,0.199951,0.185956,0.205464,0.185833,0.212326,0.195920,0.196442,0.198527,8.909583,2017-06-12,CLE @ GSW,2016-17,0,0,-9
15285,0041600405,1610612744,46,90,14,38,23,28,13,29,42,27,8,2,13,24,129,240.000000,21,15,18,52,5,128.643153,122.172042,6.487667,0.150365,1.179740,18.494819,0.053119,0.120246,0.089912,8.272854,0.547206,0.580721,0.196525,101.718108,99.399156,71.476250,0.107421,0.588877,0.312834,0.126243,0.594327,0.261859,0.147807,0.297210,3.339028,0.585860,0.409695,0.440319,0.090306,0.367593,0.126848,0.146631,0.146715,0.350013,0.540470,0.413905,0.536320,0.284374,0.604034,0.350341,0.321765,0.484646,0.199070,0.200313,0.193364,0.201004,0.192431,0.190246,0.184667,0.191379,0.202238,0.199951,0.185956,0.205464,0.185833,0.212326,0.195920,0.196442,0.198527,8.909583,1610612739,2017-06-12,47,88,11,24,15,23,12,28,40,22,6,5,14,22,120,240.000000,25,20,25,62,2,121.789722,127.352653,-5.543674,0.128000,1.207535,14.285500,0.051772,0.120648,0.085652,11.077937,0.582644,0.607025,0.198684,101.720536,100.101136,68.871528,0.088589,0.596013,0.264821,0.147290,0.590410,0.319451,0.126091,0.312421,3.637778,0.640640,0.359360,0.512974,0.059288,0.265161,0.178492,0.154206,0.201363,0.454052,0.395738,0.462804,0.562263,0.048640,0.458412,0.474297,0.349970,0.438142,0.194622,0.199423,0.178921,0.192735,0.288973,0.269110,0.216840,0.200830,0.202585,0.196317,0.183021,0.191947,0.196169,0.186875,0.186402,0.206406,0.197266,-5.704444,2017-06-12,GSW vs. CLE,2016-17,1,1,9

# SPECIAL FOR ODDS : Keep only season past 2010-11

In [19]:
# # get first line with season 2010-11 and cut all lines before
# first_season = match_dataset[match_dataset['SEASON'] == '2010-11'].index[0]
# match_dataset = match_dataset.iloc[first_season:].reset_index(drop=True)
# match_dataset

# Merge Odds with dataset

In [20]:
all_odds_df = merge_odds_csv_files(DATA_ODDS_HISTORY_DIR)

match_dataset = match_odds_with_dataset(all_odds_df, match_dataset)

------------------ Nombre de lignes supprimées pour cotes manquantes: 14 ------------------

In [21]:
match_dataset

,GAME_ID,TEAM_ID,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,points_traditional,MINUTES_PLAYED,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,blocksAgainst_misc,offensiveRating_advanced,defensiveRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,threePointersPercentage_traditional,freeThrowsPercentage_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage,plusMinusPoints_traditional,OPP_TEAM_ID,GAME_DATE,OPP_fieldGoalsMade_traditional,OPP_fieldGoalsAttempted_traditional,OPP_threePointersMade_traditional,OPP_threePointersAttempted_traditional,OPP_freeThrowsMade_traditional,OPP_freeThrowsAttempted_traditional,OPP_reboundsOffensive_traditional,OPP_reboundsDefensive_traditional,OPP_reboundsTotal_traditional,OPP_assists_traditional,OPP_steals_traditional,OPP_blocks_traditional,OPP_turnovers_traditional,OPP_foulsPersonal_traditional,OPP_points_traditional,OPP_MINUTES_PLAYED,OPP_pointsOffTurnovers_misc,OPP_pointsSecondChance_misc,OPP_pointsFastBreak_misc,OPP_pointsPaint_misc,OPP_blocksAgainst_misc,OPP_offensiveRating_advanced,OPP_defensiveRating_advanced,OPP_netRating_advanced,OPP_assistPercentage_advanced,OPP_assistToTurnover_advanced,OPP_assistRatio_advanced,OPP_offensiveReboundPercentage_advanced,OPP_defensiveReboundPercentage_advanced,OPP_reboundPercentage_advanced,OPP_turnoverRatio_advanced,OPP_effectiveFieldGoalPercentage_advanced,OPP_trueShootingPercentage_advanced,OPP_usagePercentage_advanced,OPP_estimatedPace_advanced,OPP_pace_advanced,OPP_possessions_advanced,OPP_PIE_advanced,OPP_effectiveFieldGoalPercentage_fourfactors,OPP_freeThrowAttemptRate_fourfactors,OPP_teamTurnoverPercentage_fourfactors,OPP_oppEffectiveFieldGoalPercentage_fourfactors,OPP_oppFreeThrowAttemptRate_fourfactors,OPP_oppTeamTurnoverPercentage_fourfactors,OPP_oppOffensiveReboundPercentage_fourfactors,OPP_foulsDrawn_misc,OPP_percentageFieldGoalsAttempted2pt_scoring,OPP_percentageFieldGoalsAttempted3pt_scoring,OPP_percentagePoints2pt_scoring,OPP_percentagePointsMidrange2pt_scoring,OPP_percentagePoints3pt_scoring,OPP_percentagePointsFastBreak_scoring,OPP_percentagePointsFreeThrow_scoring,OPP_percentagePointsOffTurnovers_scoring,OPP_percentagePointsPaint_scoring,OPP_percentageAssisted2pt_scoring,OPP_percentageUnassisted2pt_scoring,OPP_percentageAssisted3pt_scoring,OPP_percentageUnassisted3pt_scoring,OPP_percentageAssistedFGM_scoring,OPP_percentageUnassistedFGM_scoring,OPP_threePointersPercentage_traditional,OPP_freeThrowsPercentage_traditional,OPP_percentageFieldGoalsMade_usage,OPP_percentageFieldGoalsAttempted_usage,OPP_percentageThreePointersMade_usage,OPP_percentageThreePointersAttempted_usage,OPP_percentageFreeThrowsMade_usage,OPP_percentageFreeThrowsAttempted_usage,OPP_percentageReboundsOffensive_usage,OPP_percentageReboundsDefensive_usage,OPP_percentageReboundsTotal_usage,OPP_percentageAssists_usage,OPP_percentageTurnovers_usage,OPP_percentageSteals_usage,OPP_percentageBlocks_usage,OPP_percentageBlocksAllowed_usage,OPP_percentagePersonalFouls_usage,OPP_percentagePersonalFoulsDrawn_usage,OPP_percentagePoints_usage,OPP_plusMinusPoints_traditional,OPP_GAME_DATE,MATCHUP,SEASON,IS_HOME,IS_WIN,POINT_DIFF,TEAM_NAME,OPPONENT_NAME,ODDS,OPP_ODDS
0,0041100405,1610612748,80.0,154.0,28.0,52.0,54.0,66.0,16.0,66.0,82.0,50.0,16.0,14.0,26.0,42.0,242.0,480.000000,58.0,26.0,30.0,92.0,6.0,126.004229,108.644847,17.373819,0.142980,1.199537,16.307299,0.040713,0.124535,0.089900,8.778069,0.563849,0.628182,0.195189,99.479931,97.000046,60.508889,0.125629,0.593201,0.466620,0.143813,0.476427,0.304036,0.128481,0.232916,3.816736,0.612336,0.362525,0.374102,0.040791,0.358406,0.107215,0.223117,0.249705,0.333167,0.230541,0.502237,0.499931,0.070694,0.537576,0.361452,0.384826,0.672922,0.186663,0.198747,0.176693,0.190151,0.188101,0.187200,0.186777,0.195408,0.198461,0.184242,0.202927,0.184594,0.162332,0.177785,0.188845,0.198039,0.197702,15.774722,1610612760,2012-06-21,72.0,174.0,22.0,56.0,46.0,52.0,20.0,56.0,76.0,38.0,14.0,6.0,26.0,58.0,212.0,480.000000,30.0,28.0,26.0,80.0,14.0,108.516882,125.870271,-17.354410,0.138415,0.866533,14.117389,0.037329,0.145047,0.084540,8.336139,0.465233,0.525484,0.197786,99.478407,96.898178,61.837361,0.075981,0.470087,0.306408,0.128621,0.601521,0.457418,0.144059,0.219195,3.348681,0.667002,0.332998,0.525438,0.075454,0.231829,0.109402,0.204062,0.244113,0.450163,0.437892,0.510719,0.351938,0.109520,0.525230,0.435951,0.218437,0.561977,0.202106,0.201233,0.175863,0.190037,0.185059,0.182312,0.187035,0.204015,0.203011,0.185635,0.183078,0.180010,0.131689,0.206325,0.208649,0.196010,0.202598,-14.305556,2012-06-21,MIA vs. OKC,2011-12,1.0,1.0,30.0,miami heat,oklahoma city thunder,1.50,2.07
1,0041100405,1610612760,72.0,174.0,22.0,56.0,46.0,52.0,20.0,56.0,76.0,38.0,14.0,6.0,26.0,58.0,212.0,480.000000,30.0,28.0,26.0,80.0,14.0,108.516882,125.870271,-17.354410,0.138415,0.866533,14.117389,0.037329,0.145047,0.084540,8.336139,0.465233,0.525484,0.197786,99.478407,96.898178,61.837361,0.075981,0.470087,0.306408,0.128621,0.601521,0.457418,0.144059,0.219195,3.348681,0.667002,0.332998,0.525438,0.075454,0.231829,0.109402,0.204062,0.244113,0.450163,0.437892,0.510719,0.351938,0.109520,0.525230,0.435951,0.218437,0.561977,0.202106,0.201233,0.175863,0.190037,0.185059,0.182312,0.187035,0.204015,0.203011,0.185635,0.183078,0.180010,0.131689,0.206325,0.208649,0.196010,0.202598,-14.305556,1610612748,2012-06-21,80.0,154.0,28.0,52.0,54.0,66.0,16.0,66.0,82.0,50.0,16.0,14.0,26.0,42.0,242.0,480.000000,58.0,26.0,30.0,92.0,6.0,126.004229,108.644847,17.373819,0.142980,1.199537,16.307299,0.040713,0.124535,0.089900,8.778069,0.563849,0.628182,0.195189,99.479931,97.000046,60.508889,0.125629,0.593201,0.466620,0.143813,0.476427,0.304036,0.128481,0.232916,3.816736,0.612336,0.362525,0.374102,0.040791,0.358406,0.107215,0.223117,0.249705,0.333167,0.230541,0.502237,0.499931,0.070694,0.537576,0.361452,0.384826,0.672922,0.186663,0.198747,0.176693,0.190151,0.188101,0.187200,0.186777,0.195408,0.198461,0.184242,0.202927,0.184594,0.162332,0.177785,0.188845,0.198039,0.197702,15.774722,2012-06-21,OKC @ MIA,2011-12,0.0,0.0,-30.0,oklahoma city thunder,miami heat,2.07,1.50
2,0041100404,1610612748,76.0,158.0,20.0,52.0,36.0,50.0,18.0,62.0,80.0,38.0,16.0,4.0,18.0,36.0,208.0,480.033333,32.0,30.0,18.0,92.0,4.0,111.775030,108.489869,3.267461,0.138692,1.470419,11.950955,0.041160,0.145299,0.091995,9.742011,0.503598,0.534114,0.191322,91.519899,91.598767,67.795431,0.110933,0.543179,0.318223,0.109271,0.504589,0.195091,0.119525,0.205522,3.176446,0.522204,0.430091,0.430541,0.077213,0.347774,0.063242,0.160116,0.115395,0.353327,0.295757,0.391904,0.424901,0.358308,0.579584,0.359032,0.314803,0.601795,0.199755,0.198582,0.186186,0.196445,0.194075,0.197446,0.202304,0.205279,0.199276,0.187058,0.189589,0.213750,0.173530,0.173530,0.192206,0.200225,0.199973,2.496840,1610612760,2012-06-19,80.0,164.0,6.0,32.0,30.0,32.0,16.0,54.0,70.0,26.0,12.0,4.0,22.0,40.0,196.0,480.000000,22.0,18.0,34.0,80.0,4.0,108.575333,113.059111,-4.467132,0.099957,0.810921,10.660590,0.035203,0.124871,0.080836,8.384618,0.433593,0.472360,0.197361,91.519248,91.198559,63.762569,0.092315,0.507022,0.194929,0.119121,0.545026,0.316991,0.110349,0.248921,2.961736,0.806151,0.193849,0.628893,0.316470,0.146244,0.188379,0.132587,0.147634,0.312805,0.488758,0.419158,0.459375,0.000000,0.504724,0.403192,0.106967,0.496962,0.197698,0.200221,0.274334,0.208500,0.184014,0.182300,0.177653,0.202558,0.202393,0.207299,0.193414,0.202357,0.184722,0.166458,0.204230,0.195866,0.197871,-3.609306,2012-06-19,MIA vs. OKC,2011-12,1.0,1.0,12.0,miami heat,oklahoma city thunder,1.47,2.16
3,0041100404,1610612760,80.0,164.0,6.0,32.0,30.0,32.0,16.0,54.0,70.0,26.0,12.0,4.0,22.0,40.0,196.0,480.000000,22.0,18.0,34.0,80.0,4.0,108.575333,113.059111,-4.467132,0.099957,0.810921,10.660590,0.035203,0.124871,0.080836,8.384618,0.433593,0.472360,0.197361,91.519248,91.198559,63.762569,0.092315,0.507022,0.194929,0.119121,0.545026,0.316991,0.110349,0.248921,2.961736,0.806151,0.193849,0.628893,0.316470,0.146244,0.188379,0.132587,0.147634,0.312805,0.488758,0.419158,0.459375,0.000000,0.504724,0.403192,0.106967,0.496962,0.197698,0.200221,0.274334,0.208500,0.184014,0.182300,0.177653,0.202558,0.202393,0.207299,0.193414,0.202357,0.184722,0.166458,0.204230,0.195866,0.197871,-3.609306,1610612748,2012-06-19,76.0,158.0,20.0,52.0,36.0,50.0,18.0,62.0,80.0,38.0,16.0,4.0,18.0,36.0,208.0,480.033333,32.0,30.0,18.0,92.0,4.0,111.775030,108.489869,3.267461,0.138692,1.470419,11.950955,0.041160,0.145299,0.091995,9.742011,0.503598,0.534114,0.191322,91.519899,91.598767,67.795431,0.110933,0.543179,0.318223,0.109271,0.504589,0.195091,0.119525,0.205522,3.176446,0.522204,0.430091,0.430541,0.077213,0.347774,0.063242,0.160116,0.115395,0.353327,0.295757,0.391904,0.424901,0.358308,0.579584,0.359032,0.314803,0.601795,0.199755,0.198582,0.186186,0.196445,0.194075,0.197446,0.202304,0.205279,0.199276,0.187058,0.189589,0.213750,0.173530,0.173530,0.192206,0.200225,0.199973,2.496840,2012-06-19,OKC @ MIA,2011-12,0.0,0.0,-12.0,oklahoma city thunder,miami heat,2.16,1.47
4,0041100403,1610612748,56.0,148.0,8.0,26.0,62.0,70.0,28.0,62.0,90.0,26.0,12.0,10.0,24.0,38.0,182.0,480.000000,32.0,22.0,38.0,92.0,16.0,101.904174,94.829590,7.068444,0.133996,0.896493,9.251458,0.061608,0.131960,0.095753,8.582056,0.549756,0.592009,0.192270,90.483008,89.600293,66.627708,0.120503,0.407040,0.478514,0.165867,0.454944,0.315444,0.154438,0.259428,3.907639,0.682283,0.317717,0.537869,0.012602,0.141893,0.132756,0.294613,0.113761,0.525267,0.320877,0.456207,0.379931,0.000000,0.531501,0.442874,0.217465,0.728820,0.198627,0.199318,0.217465,0.202331,0.191072,0.195062,0.196719,0.206829,0.202548,0.184336,0.153440,0.190721,0.201649,0.183316,0.182922,0.202630,0.198154,3.100625,1610612760,2012-06-17,66.0,154.0,8.0,36.0,30.0,48.0,22.0,54.0,76.0,22.0,18.0,16.0,22.0,50.0,170.0,480.000000,34.0,18.0,24.0,84.0,10.0,95.300840,101.279708,-6.004354,0.082626,0.806979,7.689049,0.047671,0.114070,0.079816,7.843806,0.445420,0.480164,0.194426,90.479059,89.699849,58.660694,0.087323,0.455548,0.313589,0.155275,0.414446,0.490590,0.166118,0.350517,2.590347,0.788366,0.211634,0.667006,0.144521,0.123635,0.155385,0.197483,0.180513,0.522485,0.305290,0.682835,0.117708,0.324861,0.376484,0.611641,0.159727,0.603568,0.194994,0.201428,0.167033,0.190556,0.211953,0.228078,0.206531,0.205878,0.204334,0.194692,0.149790,0.182590,0.166836,0.212995,0.199219,0.210855,0.197977,-2.518264,2012-06-17,MIA vs. OKC,2011-12,1.0,1.0,12.0,miami heat,oklahoma city thunder,1.39,2.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15231,0021600026,1610612755,28.0,80.0,5.0,18.0,11.0,15.0,4.0,35.0,39.0,16.0,9.0,5.0,20.0,20.0,72.0,240.000000,8.0,9.0,7.0,36.0,7.0,71.091583,100.971292,-29.875007,0.160397,0.642949,12.208868,0.014925,0.139575,0.076537,15.588125,0.341817,0.365731,0.196586,101.859514,102.300862,46.121528,0.055463,0.380178,0.193137,0.194862,0.522224,0.281280,0.118156,0.152943,1.088542,0.727503,0.272497,0.421314,0.070209,0.284097,0.066336,0.098830,0.062099,0.351169,0.369343,0.230657,0.204306,0.174444,0.508982,0.295324,0.265351,0.205119,0.202060,0.201955,0.264028,0.189523,0.139235,0.145620,0.172500,0.198429,0.197669,0.212242,0.194393,0.171508,0.158204,0.209933,0.192256,0.187989,0.202708,-14.372639,1610612737,2016-10-29,42.0,85.0,5.0,20.0,15.0,23.0,6.0,41.0,47.0,31.0,11.0,7.0,12.0,14.0,104.0,240.000000,22.0,8.0,19.0,50.0,5.0,101.561875,70.518500,31.054875,0.184172,1.203683,20.858319,0.025936,0.160620,0.092390,8.641674,0.550163,0.563637,0.192354,101.859732,102.200686,46.441181,0.153587,0.520717,0.280693,0.117978,0.380491,0.188785,0.195056,0.087838,1.785139,0.794189,0.205811,0.732716,0.208090,0.126796,0.188391,0.140488,0.232850,0.524626,0.681432,0.318568,0.265764,0.000000,0.722958,0.277042,0.174419,0.354436,0.199172,0.200586,0.183681,0.199592,0.211839,0.204513,0.180999,0.199249,0.199508,0.201146,0.152266,0.202900,0.232970,0.191680,0.197736,0.211736,0.200441,13.465903,2016-10-29,PHI vs. ATL,2016-17,1.0,0.0,-32.0,philadelphia 76ers,atlanta hawks,3.50,1.25
15232,0041600144,1610612744,46.0,86.0,17.0,29.0,19.0,27.0,6.0,39.0,45.0,27.0,7.0,9.0,10.0,15.0,128.0,240.033333,14.0,4.0,14.0,38.0,3.0,124.959651,101.338634,23.627788,0.159116,0.671833,19.085578,0.021503,0.144437,0.091251,6.107187,0.574273,0.591628,0.197779,101.820948,101.899357,49.736912,0.125485,0.638266,0.309432,0.098037,0.467547,0.339688,0.108453,0.152001,2.018609,0.696467,0.303533,0.483538,0.161477,0.283940,0.072509,0.151561,0.089193,0.322061,0.475786,0.443392,0.361629,0.112888,0.527949,0.391229,0.326586,0.555776,0.197415,0.201708,0.149023,0.178059,0.220644,0.203437,0.120788,0.203820,0.199202,0.192156,0.155522,0.188083,0.159018,0.167407,0.190030,0.201668,0.194639,15.950840,1610612757,2017-04-24,33.0,85.0,13.0,39.0,24.0,29.0,7.0,32.0,39.0,14.0,7.0,3.0,11.0,20.0,103.0,240.000000,5.0,12.0,4.0,28.0,9.0,101.844146,125.220750,-23.395333,0.127247,0.459810,7.659931,0.026963,0.149890,0.079387,7.898889,0.445574,0.497418,0.197088,101.821058,101.799083,58.903472,0.072797,0.464278,0.342151,0.107807,0.638345,0.314603,0.097185,0.141563,2.000625,0.569321,0.430679,0.416382,0.113276,0.266090,0.021082,0.265775,0.045946,0.303253,0.232639,0.629861,0.465324,0.134190,0.356060,0.529634,0.246725,0.660928,0.196420,0.199501,0.202839,0.198949,0.188219,0.189613,0.218232,0.200356,0.196915,0.202024,0.185506,0.179140,0.179408,0.188289,0.199278,0.189102,0.195214,-15.393889,2017-04-24,GSW @ POR,2016-17,0.0,1.0,25.0,golden state warriors,portland trail blazers,1.39,2.53
15233,0041600144,1610612757,33.0,85.0,13.0,39.0,24.0,29.0,7.0,32.0,39.0,14.0,7.0,3.0,11.0,20.0,103.0,240.000000,5.0,12.0,4.0,28.0,9.0,101.844146,125.220750,-23.395333,0.127247,0.459810,7.659931,0.026963,0.149890,0.079387,7.898889,0.445574,0.497418,0.197088,101.821058,101.799083,58.903472,0.072797,0.464278,0.342151,0.107807,0.638345,0.314603,0.097185,0.141563,2.000625,0.569321,0.430679,0.416382,0.113276,0.266090,0.021082,0.265775,0.045946,0.303253,0.232639,0.629861,0.465324,0.134190,0.356060,0.529634,0.246725,0.660928,0.196420,0.199501,0.202839,0.198949,0.188219,0.189613,0.218232,0.200356,0.196915,0.202024,0.185506,0.179140,0.179408,0.188289,0.199278,0.189102,0.195214,-15.393889,1610612744,2017-04-24,46.0,86.0,17.0,29.0,19.0,27.0,6.0,39.0,45.0,27.0,7.0,9.0,10.0,15.0,128.0,240.033333,14.0,4.0,14.0,38.0,3.0,124.959651,101.338634,23.627788,0.159116,0.671833,19.085578,0.021503,0.144437,0.091251,6.107187,0.574273,0.591628,0.197779,101.820948,101.899357,49.736912,0.125485,0.638266,0.309432,0.098037,0.467547,0.339688,0.108453,0.152001,2.018609,0.696467,0.303533,0.483538,0.161477,0.283940,0.072509,0.151561,0.089193,0.322061,0.475786,0.443392,0.361629,0.112888,0.527949,0.391229,0.326586,0.555776,0.197415,0.201708,0.149023,0.178059,0.220644,0.203437,0.120788,0.203820,0.199202,0.192156,0.155522,0.188083,0.159018,0.167407,0.190030,0.201668,0.194639,15.950840,2017-04-24,POR vs. GSW,2016-17,1.0,0.0,-25.0,portland trail blazers,golden state warriors,2.53,1.39
15234,0041600174,1610612746,33.0,75.0,11.0,32.0,21.0,29.0,6.0,25.0,31.0,17.0,8.0,0.0,9.0,18.0,98.0,240.000000,4.0,9.0,1.0,36.0,3.0,105.526958,114.612326,-9.062743,0.158487,1.224792,9.869785,0.027667,0.136051,0.075938,7.550153,0.470915,0.523953,0.196106,90.000755,92.499403,61.731944,0.079637,0.515302,0.389761,0.099057,0.611337,0.299591,0.144572,0.216650,2.398264,0.545538,0.438420,0.411841,0.112741,0.283564,0.016042,0.254109,0.033678,0.299100,0.523208,0.410264,0.613097,0.026208,0.657032,0.276440,0.276600,0.678282,0.195867,0.199402,0.179647,0.197842,0.197776,0.196380,0.161846,0.189472,0.188428,0.187360,0.217585,0.167650,0.000000,0.219571,0.201685,0.204162,0.196494,-5.767708,1610612762,2017-04-23,40.0,74.0,10.0,22.0,15.0,21.0,7.0,35.0,42.0,24.0,7.0,3.0,12.0,17.0,105.0,240.016667,17.0,13.0,7.0,58.0,0.0,114.779251,105.963287,8.798521,0.146641,1.804977,21.007916,0.038889,0.152663,0.101374,10.618881,0.616318,0.632372,0.192232,90.000485,92.499108,56.007083,0.121128,0.610731,0.285767,0.144788,0.512997,0.387243,0.098771,0.149382,2.278314,0.606645,0.342811,0.432184,0.010235,0.349148,0.080264,0.124603,0.194886,0.421949,0.357923,0.460700,0.584751,0.121033,0.571900,0.334009,0.381367,0.514805,0.202307,0.197492,0.217908,0.192665,0.212821,0.209094,0.197643,0.195777,0.198899,0.191070,0.175250,0.172667,0.224207,0.000000,0.192367,0.195124,0.202119,5.759461,2017-04-23,LAC @ UTA,2016-17,0.0,0.0,-7.0,los angeles clippers,utah jazz,1.70,1.93

# Reorder columns for visualisation

In [22]:
cols_first = ['GAME_ID', 'GAME_DATE', 'TEAM_ID', 'OPP_TEAM_ID', 'IS_HOME', 'IS_WIN','POINT_DIFF', 'points_traditional','ODDS','OPP_ODDS']
other_cols = [col for col in match_dataset.columns if col not in cols_first]
match_dataset = match_dataset[cols_first + other_cols]
match_dataset

,GAME_ID,GAME_DATE,TEAM_ID,OPP_TEAM_ID,IS_HOME,IS_WIN,POINT_DIFF,points_traditional,ODDS,OPP_ODDS,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,MINUTES_PLAYED,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,blocksAgainst_misc,offensiveRating_advanced,defensiveRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,threePointersPercentage_traditional,freeThrowsPercentage_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage,plusMinusPoints_traditional,OPP_fieldGoalsMade_traditional,OPP_fieldGoalsAttempted_traditional,OPP_threePointersMade_traditional,OPP_threePointersAttempted_traditional,OPP_freeThrowsMade_traditional,OPP_freeThrowsAttempted_traditional,OPP_reboundsOffensive_traditional,OPP_reboundsDefensive_traditional,OPP_reboundsTotal_traditional,OPP_assists_traditional,OPP_steals_traditional,OPP_blocks_traditional,OPP_turnovers_traditional,OPP_foulsPersonal_traditional,OPP_points_traditional,OPP_MINUTES_PLAYED,OPP_pointsOffTurnovers_misc,OPP_pointsSecondChance_misc,OPP_pointsFastBreak_misc,OPP_pointsPaint_misc,OPP_blocksAgainst_misc,OPP_offensiveRating_advanced,OPP_defensiveRating_advanced,OPP_netRating_advanced,OPP_assistPercentage_advanced,OPP_assistToTurnover_advanced,OPP_assistRatio_advanced,OPP_offensiveReboundPercentage_advanced,OPP_defensiveReboundPercentage_advanced,OPP_reboundPercentage_advanced,OPP_turnoverRatio_advanced,OPP_effectiveFieldGoalPercentage_advanced,OPP_trueShootingPercentage_advanced,OPP_usagePercentage_advanced,OPP_estimatedPace_advanced,OPP_pace_advanced,OPP_possessions_advanced,OPP_PIE_advanced,OPP_effectiveFieldGoalPercentage_fourfactors,OPP_freeThrowAttemptRate_fourfactors,OPP_teamTurnoverPercentage_fourfactors,OPP_oppEffectiveFieldGoalPercentage_fourfactors,OPP_oppFreeThrowAttemptRate_fourfactors,OPP_oppTeamTurnoverPercentage_fourfactors,OPP_oppOffensiveReboundPercentage_fourfactors,OPP_foulsDrawn_misc,OPP_percentageFieldGoalsAttempted2pt_scoring,OPP_percentageFieldGoalsAttempted3pt_scoring,OPP_percentagePoints2pt_scoring,OPP_percentagePointsMidrange2pt_scoring,OPP_percentagePoints3pt_scoring,OPP_percentagePointsFastBreak_scoring,OPP_percentagePointsFreeThrow_scoring,OPP_percentagePointsOffTurnovers_scoring,OPP_percentagePointsPaint_scoring,OPP_percentageAssisted2pt_scoring,OPP_percentageUnassisted2pt_scoring,OPP_percentageAssisted3pt_scoring,OPP_percentageUnassisted3pt_scoring,OPP_percentageAssistedFGM_scoring,OPP_percentageUnassistedFGM_scoring,OPP_threePointersPercentage_traditional,OPP_freeThrowsPercentage_traditional,OPP_percentageFieldGoalsMade_usage,OPP_percentageFieldGoalsAttempted_usage,OPP_percentageThreePointersMade_usage,OPP_percentageThreePointersAttempted_usage,OPP_percentageFreeThrowsMade_usage,OPP_percentageFreeThrowsAttempted_usage,OPP_percentageReboundsOffensive_usage,OPP_percentageReboundsDefensive_usage,OPP_percentageReboundsTotal_usage,OPP_percentageAssists_usage,OPP_percentageTurnovers_usage,OPP_percentageSteals_usage,OPP_percentageBlocks_usage,OPP_percentageBlocksAllowed_usage,OPP_percentagePersonalFouls_usage,OPP_percentagePersonalFoulsDrawn_usage,OPP_percentagePoints_usage,OPP_plusMinusPoints_traditional,OPP_GAME_DATE,MATCHUP,SEASON,TEAM_NAME,OPPONENT_NAME
0,0041100405,2012-06-21,1610612748,1610612760,1.0,1.0,30.0,242.0,1.50,2.07,80.0,154.0,28.0,52.0,54.0,66.0,16.0,66.0,82.0,50.0,16.0,14.0,26.0,42.0,480.000000,58.0,26.0,30.0,92.0,6.0,126.004229,108.644847,17.373819,0.142980,1.199537,16.307299,0.040713,0.124535,0.089900,8.778069,0.563849,0.628182,0.195189,99.479931,97.000046,60.508889,0.125629,0.593201,0.466620,0.143813,0.476427,0.304036,0.128481,0.232916,3.816736,0.612336,0.362525,0.374102,0.040791,0.358406,0.107215,0.223117,0.249705,0.333167,0.230541,0.502237,0.499931,0.070694,0.537576,0.361452,0.384826,0.672922,0.186663,0.198747,0.176693,0.190151,0.188101,0.187200,0.186777,0.195408,0.198461,0.184242,0.202927,0.184594,0.162332,0.177785,0.188845,0.198039,0.197702,15.774722,72.0,174.0,22.0,56.0,46.0,52.0,20.0,56.0,76.0,38.0,14.0,6.0,26.0,58.0,212.0,480.000000,30.0,28.0,26.0,80.0,14.0,108.516882,125.870271,-17.354410,0.138415,0.866533,14.117389,0.037329,0.145047,0.084540,8.336139,0.465233,0.525484,0.197786,99.478407,96.898178,61.837361,0.075981,0.470087,0.306408,0.128621,0.601521,0.457418,0.144059,0.219195,3.348681,0.667002,0.332998,0.525438,0.075454,0.231829,0.109402,0.204062,0.244113,0.450163,0.437892,0.510719,0.351938,0.109520,0.525230,0.435951,0.218437,0.561977,0.202106,0.201233,0.175863,0.190037,0.185059,0.182312,0.187035,0.204015,0.203011,0.185635,0.183078,0.180010,0.131689,0.206325,0.208649,0.196010,0.202598,-14.305556,2012-06-21,MIA vs. OKC,2011-12,miami heat,oklahoma city thunder
1,0041100405,2012-06-21,1610612760,1610612748,0.0,0.0,-30.0,212.0,2.07,1.50,72.0,174.0,22.0,56.0,46.0,52.0,20.0,56.0,76.0,38.0,14.0,6.0,26.0,58.0,480.000000,30.0,28.0,26.0,80.0,14.0,108.516882,125.870271,-17.354410,0.138415,0.866533,14.117389,0.037329,0.145047,0.084540,8.336139,0.465233,0.525484,0.197786,99.478407,96.898178,61.837361,0.075981,0.470087,0.306408,0.128621,0.601521,0.457418,0.144059,0.219195,3.348681,0.667002,0.332998,0.525438,0.075454,0.231829,0.109402,0.204062,0.244113,0.450163,0.437892,0.510719,0.351938,0.109520,0.525230,0.435951,0.218437,0.561977,0.202106,0.201233,0.175863,0.190037,0.185059,0.182312,0.187035,0.204015,0.203011,0.185635,0.183078,0.180010,0.131689,0.206325,0.208649,0.196010,0.202598,-14.305556,80.0,154.0,28.0,52.0,54.0,66.0,16.0,66.0,82.0,50.0,16.0,14.0,26.0,42.0,242.0,480.000000,58.0,26.0,30.0,92.0,6.0,126.004229,108.644847,17.373819,0.142980,1.199537,16.307299,0.040713,0.124535,0.089900,8.778069,0.563849,0.628182,0.195189,99.479931,97.000046,60.508889,0.125629,0.593201,0.466620,0.143813,0.476427,0.304036,0.128481,0.232916,3.816736,0.612336,0.362525,0.374102,0.040791,0.358406,0.107215,0.223117,0.249705,0.333167,0.230541,0.502237,0.499931,0.070694,0.537576,0.361452,0.384826,0.672922,0.186663,0.198747,0.176693,0.190151,0.188101,0.187200,0.186777,0.195408,0.198461,0.184242,0.202927,0.184594,0.162332,0.177785,0.188845,0.198039,0.197702,15.774722,2012-06-21,OKC @ MIA,2011-12,oklahoma city thunder,miami heat
2,0041100404,2012-06-19,1610612748,1610612760,1.0,1.0,12.0,208.0,1.47,2.16,76.0,158.0,20.0,52.0,36.0,50.0,18.0,62.0,80.0,38.0,16.0,4.0,18.0,36.0,480.033333,32.0,30.0,18.0,92.0,4.0,111.775030,108.489869,3.267461,0.138692,1.470419,11.950955,0.041160,0.145299,0.091995,9.742011,0.503598,0.534114,0.191322,91.519899,91.598767,67.795431,0.110933,0.543179,0.318223,0.109271,0.504589,0.195091,0.119525,0.205522,3.176446,0.522204,0.430091,0.430541,0.077213,0.347774,0.063242,0.160116,0.115395,0.353327,0.295757,0.391904,0.424901,0.358308,0.579584,0.359032,0.314803,0.601795,0.199755,0.198582,0.186186,0.196445,0.194075,0.197446,0.202304,0.205279,0.199276,0.187058,0.189589,0.213750,0.173530,0.173530,0.192206,0.200225,0.199973,2.496840,80.0,164.0,6.0,32.0,30.0,32.0,16.0,54.0,70.0,26.0,12.0,4.0,22.0,40.0,196.0,480.000000,22.0,18.0,34.0,80.0,4.0,108.575333,113.059111,-4.467132,0.099957,0.810921,10.660590,0.035203,0.124871,0.080836,8.384618,0.433593,0.472360,0.197361,91.519248,91.198559,63.762569,0.092315,0.507022,0.194929,0.119121,0.545026,0.316991,0.110349,0.248921,2.961736,0.806151,0.193849,0.628893,0.316470,0.146244,0.188379,0.132587,0.147634,0.312805,0.488758,0.419158,0.459375,0.000000,0.504724,0.403192,0.106967,0.496962,0.197698,0.200221,0.274334,0.208500,0.184014,0.182300,0.177653,0.202558,0.202393,0.207299,0.193414,0.202357,0.184722,0.166458,0.204230,0.195866,0.197871,-3.609306,2012-06-19,MIA vs. OKC,2011-12,miami heat,oklahoma city thunder
3,0041100404,2012-06-19,1610612760,1610612748,0.0,0.0,-12.0,196.0,2.16,1.47,80.0,164.0,6.0,32.0,30.0,32.0,16.0,54.0,70.0,26.0,12.0,4.0,22.0,40.0,480.000000,22.0,18.0,34.0,80.0,4.0,108.575333,113.059111,-4.467132,0.099957,0.810921,10.660590,0.035203,0.124871,0.080836,8.384618,0.433593,0.472360,0.197361,91.519248,91.198559,63.762569,0.092315,0.507022,0.194929,0.119121,0.545026,0.316991,0.110349,0.248921,2.961736,0.806151,0.193849,0.628893,0.316470,0.146244,0.188379,0.132587,0.147634,0.312805,0.488758,0.419158,0.459375,0.000000,0.504724,0.403192,0.106967,0.496962,0.197698,0.200221,0.274334,0.208500,0.184014,0.182300,0.177653,0.202558,0.202393,0.207299,0.193414,0.202357,0.184722,0.166458,0.204230,0.195866,0.197871,-3.609306,76.0,158.0,20.0,52.0,36.0,50.0,18.0,62.0,80.0,38.0,16.0,4.0,18.0,36.0,208.0,480.033333,32.0,30.0,18.0,92.0,4.0,111.775030,108.489869,3.267461,0.138692,1.470419,11.950955,0.041160,0.145299,0.091995,9.742011,0.503598,0.534114,0.191322,91.519899,91.598767,67.795431,0.110933,0.543179,0.318223,0.109271,0.504589,0.195091,0.119525,0.205522,3.176446,0.522204,0.430091,0.430541,0.077213,0.347774,0.063242,0.160116,0.115395,0.353327,0.295757,0.391904,0.424901,0.358308,0.579584,0.359032,0.314803,0.601795,0.199755,0.198582,0.186186,0.196445,0.194075,0.197446,0.202304,0.205279,0.199276,0.187058,0.189589,0.213750,0.173530,0.173530,0.192206,0.200225,0.199973,2.496840,2012-06-19,OKC @ MIA,2011-12,oklahoma city thunder,miami heat
4,0041100403,2012-06-17,1610612748,1610612760,1.0,1.0,12.0,182.0,1.39,2.36,56.0,148.0,8.0,26.0,62.0,70.0,28.0,62.0,90.0,26.0,12.0,10.0,24.0,38.0,480.000000,32.0,22.0,38.0,92.0,16.0,101.904174,94.829590,7.068444,0.133996,0.896493,9.251458,0.061608,0.131960,0.095753,8.582056,0.549756,0.592009,0.192270,90.483008,89.600293,66.627708,0.120503,0.407040,0.478514,0.165867,0.454944,0.315444,0.154438,0.259428,3.907639,0.682283,0.317717,0.537869,0.012602,0.141893,0.132756,0.294613,0.113761,0.525267,0.320877,0.456207,0.379931,0.000000,0.531501,0.442874,0.217465,0.728820,0.198627,0.199318,0.217465,0.202331,0.191072,0.195062,0.196719,0.206829,0.202548,0.184336,0.153440,0.190721,0.201649,0.183316,0.182922,0.202630,0.198154,3.100625,66.0,154.0,8.0,36.0,30.0,48.0,22.0,54.0,76.0,22.0,18.0,16.0,22.0,50.0,170.0,480.000000,34.0,18.0,24.0,84.0,10.0,95.300840,101.279708,-6.004354,0.082626,0.806979,7.689049,0.047671,0.114070,0.079816,7.843806,0.445420,0.480164,0.194426,90.479059,89.699849,58.660694,0.087323,0.455548,0.313589,0.155275,0.414446,0.490590,0.166118,0.350517,2.590347,0.788366,0.211634,0.667006,0.144521,0.123635,0.155385,0.197483,0.180513,0.522485,0.305290,0.682835,0.117708,0.324861,0.376484,0.611641,0.159727,0.603568,0.194994,0.201428,0.167033,0.190556,0.211953,0.228078,0.206531,0.205878,0.204334,0.194692,0.149790,0.182590,0.166836,0.212995,0.199219,0.210855,0.197977,-2.518264,2012-06-17,MIA vs. OKC,2011-12,miami heat,oklahoma city thunder
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15231,0021600026,2016-10-29,1610612755,1610612737,1.0,0.0,-32.0,72.0,3.50,1.25,28.0,80.0,5.0,18.0,11.0,15.0,4.0,35.0,39.0,16.0,9.0,5.0,20.0,20.0,240.000000,8.0,9.0,7.0,36.0,7.0,71.091583,100.971292,-29.875007,0.160397,0.642949,12.208868,0.014925,0.139575,0.076537,15.588125,0.341817,0.365731,0.196586,101.859514,102.300862,46.121528,0.055463,0.380178,0.193137,0.194862,0.522224,0.281280,0.118156,0.152943,1.088542,0.727503,0.272497,0.421314,0.070209,0.284097,0.066336,0.098830,0.062099,0.351169,0.369343,0.230657,0.204306,0.174444,0.508982,0.295324,0.265351,0.205119,0.202060,0.201955,0.264028,0.189523,0.139235,0.145620,0.172500,0.198429,0.197669,0.212242,0.194393,0.171508,0.158204,0.209933,0.192256,0.187989,0.202708,-14.372639,42.0,85.0,5.0,20.0,15.0,23.0,6.0,41.0,47.0,31.0,11.0,7.0,12.0,14.0,104.0,240.000000,22.0,8.0,19.0,50.0,5.0,101.561875,70.518500,31.054875,0.184172,1.203683,20.858319,0.025936,0.160620,0.092390,8.641674,0.550163,0.563637,0.192354,101.859732,102.200686,46.441181,0.153587,0.520717,0.280693,0.117978,0.380491,0.188785,0.195056,0.087838,1.785139,0.794189,0.205811,0.732716,0.208090,0.126796,0.188391,0.140488,0.232850,0.524626,0.681432,0.318568,0.265764,0.000000,0.722958,0.277042,0.174419,0.354436,0.199172,0.200586,0.183681,0.199592,0.211839,0.204513,0.180999,0.199249,0.199508,0.201146,0.152266,0.202900,0.232970,0.191680,0.197736,0.211736,0.200441,13.465903,2016-10-29,PHI vs. ATL,2016-17,philadelphia 76ers,atlanta hawks
15232,0041600144,2017-04-24,1610612744,1610612757,0.0,1.0,25.0,128.0,1.39,2.53,46.0,86.0,17.0,29.0,19.0,27.0,6.0,39.0,45.0,27.0,7.0,9.0,10.0,15.0,240.033333,14.0,4.0,14.0,38.0,3.0,124.959651,101.338634,23.627788,0.159116,0.671833,19.085578,0.021503,0.144437,0.091251,6.107187,0.574273,0.591628,0.197779,101.820948,101.899357,49.736912,0.125485,0.638266,0.309432,0.098037,0.467547,0.339688,0.108453,0.152001,2.018609,0.696467,0.303533,0.483538,0.161477,0.283940,0.072509,0.151561,0.089193,0.322061,0.475786,0.443392,0.361629,0.112888,0.527949,0.391229,0.326586,0.555776,0.197415,0.201708,0.149023,0.178059,0.220644,0.203437,0.120788,0.203820,0.199202,0.192156,0.155522,0.188083,0.159018,0.167407,0.190030,0.201668,0.194639,15.950840,33.0,85.0,13.0,39.0,24.0,29.0,7.0,32.0,39.0,14.0,7.0,3.0,11.0,20.0,103.0,240.000000,5.0,12.0,4.0,28.0,9.0,101.844146,125.220750,-23.395333,0.127247,0.459810,7.659931,0.026963,0.149890,0.079387,7.898889,0.445574,0.497418,0.197088,101.821058,101.799083,58.903472,0.072797,0.464278,0.342151,0.107807,0.638345,0.314603,0.097185,0.141563,2.000625,0.569321,0.430679,0.416382,0.113276,0.266090,0.021082,0.265775,0.045946,0.303253,0.232639,0.629861,0.465324,0.134190,0.356060,0.529634,0.246725,0.660928,0.196420,0.199501,0.202839,0.198949,0.188219,0.189613,0.218232,0.200356,0.196915,0.202024,0.185506,0.179140,0.179408,0.188289,0.199278,0.189102,0.195214,-15.393889,2017-04-24,GSW @ POR,2016-17,golden state warriors,portland trail blazers
15233,0041600144,2017-04-24,1610612757,1610612744,1.0,0.0,-25.0,103.0,2.53,1.39,33.0,85.0,13.0,39.0,24.0,29.0,7.0,32.0,39.0,14.0,7.0,3.0,11.0,20.0,240.000000,5.0,12.0,4.0,28.0,9.0,101.844146,125.220750,-23.395333,0.127247,0.459810,7.659931,0.026963,0.149890,0.079387,7.898889,0.445574,0.497418,0.197088,101.821058,101.799083,58.903472,0.072797,0.464278,0.342151,0.107807,0.638345,0.314603,0.097185,0.141563,2.000625,0.569321,0.430679,0.416382,0.113276,0.266090,0.021082,0.265775,0.045946,0.303253,0.232639,0.629861,0.465324,0.134190,0.356060,0.529634,0.246725,0.660928,0.196420,0.199501,0.202839,0.198949,0.188219,0.189613,0.218232,0.200356,0.196915,0.202024,0.185506,0.179140,0.179408,0.188289,0.199278,0.189102,0.195214,-15.393889,46.0,86.0,17.0,29.0,19.0,27.0,6.0,39.0,45.0,27.0,7.0,9.0,10.0,15.0,128.0,240.033333,14.0,4.0,14.0,38.0,3.0,124.959651,101.338634,23.627788,0.159116,0.671833,19.085578,0.021503,0.144437,0.091251,6.107187,0.574273,0.591628,0.197779,101.820948,101.899357,49.736912,0.125485,0.638266,0.309432,0.098037,0.467547,0.339688,0.108453,0.152001,2.018609,0.696467,0.303533,0.483538,0.161477,0.283940,0.072509,0.151561,0.089193,0.322061,0.475786,0.443392,0.361629,0.112888,0.527949,0.391229,0.326586,0.555776,0.197415,0.201708,0.149023,0.178059,0.220644,0.203437,0.120788,0.203820,0.199202,0.192156,0.155522,0.188083,0.159018,0.167407,0.190030,0.201668,0.194639,15.950840,2017-04-24,POR vs. GSW,2016-17,portland trail blazers,golden state warriors
15234,0041600174,2017-04-23,1610612746,1610612762,0.0,0.0,-7.0,98.0,1.70,1.93,33.0,75.0,11.0,32.0,21.0,29.0,6.0,25.0,31.0,17.0,8.0,0.0,9.0,18.0,240.000000,4.0,9.0,1.0,36.0,3.0,105.526958,114.612326,-9.062743,0.158487,1.224792,9.869785,0.027667,0.136051,0.075938,7.550153,0.470915,0.523953,0.196106,90.000755,92.499403,61.731944,0.079637,0.515302,0.389761,0.099057,0.611337,0.299591,0.144572,0.216650,2.398264,0.545538,0.438420,0.411841,0.112741,0.283564,0.016042,0.254109,0.033678,0.299100,0.523208,0.410264,0.613097,0.026208,0.657032,0.276440,0.276600,0.678282,0.195867,0.199402,0.179647,0.197842,0.197776,0.196380,0.161846,0.189472,0.188428,0.187360,0.217585,0.167650,0.000000,0.219571,0.201685,0.204162,0.196494,-5.767708,40.0,74.0,10.0,22.0,15.0,21.0,7.0,35.0,42.0,24.0,7.0,3.0,12.0,17.0,105.0,240.016667,17.0,13.0,7.0,58.0,0.0,114.779251,105.963287,8.798521,0.146641,1.804977,21.007916,0.038889,0.152663,0.101374,10.618881,0.616318,0.632372,0.192232,90.000485,92.499108,56.007083,0.121128,0.610731,0.285767,0.144788,0.512997,0.387243,0.098771,0.149382,2.278314,0.606645,0.342811,0.432184,0.010235,0.349148,0.080264,0.124603,0.194886,0.421949,0.357923,0.460700,0.584751,0.121033,0.571900,0.334009,0.381367,0.514805,0.202307,0.197492,0.217908,0.192665,0.212821,0.209094,0.197643,0.195777,0.198899,0.191070,0.175250,0.172667,0.224207,0.000000,0.192367,0.195124,0.202119,5.759461,2017-04-23,LAC @ UTA,2016-17,los angeles clippers,utah jazz

# 🚀 Features avancées

In [28]:

# Ajouter les features avancées aux stats de match
#match_dataset = add_advanced_boxscore_features(match_dataset)

# MOVED TO CONFIG
# features_to_roll = cols_to_sum + cols_to_weighted_avg
# features_to_roll += [f"OPP_{col}" for col in cols_to_sum + cols_to_weighted_avg]

# Calcul des features glissantes shiftées
match_dataset = compute_rolling_features(match_dataset, "TEAM_ID", ["TEAM_ID", "GAME_DATE"], features_to_roll, N_LIST, method="ewm")


match_dataset = compute_winrates(match_dataset, "TEAM_ID", "IS_WIN", "IS_HOME", N_LIST)
match_dataset = compute_win_ratio(match_dataset, "TEAM_ID", "IS_WIN", N_LIST)

match_dataset["IS_WIN_SHIFTED"] = match_dataset.groupby("TEAM_ID")["IS_WIN"].shift(1).fillna(0).astype(int)
match_dataset["WIN_STREAK"] = match_dataset.groupby("TEAM_ID").apply(
    lambda x: compute_win_streak(x, "TEAM_ID", "IS_WIN_SHIFTED")).reset_index(level=0, drop=True)
match_dataset = compute_side_win_streak(match_dataset, win_shifted_col="IS_WIN_SHIFTED")


# Calcul des jours de repos pour l'équipe et l'adversaire
match_dataset["DAYS_SINCE_LAST_GAME"] = compute_rest_days(match_dataset, "GAME_DATE", "TEAM_ID")
match_dataset["OPP_DAYS_SINCE_LAST_GAME"] = compute_rest_days(match_dataset, "GAME_DATE", "OPP_TEAM_ID")

# Avantage de repos
match_dataset["REST_ADVANTAGE"] = (
    match_dataset["DAYS_SINCE_LAST_GAME"] - match_dataset["OPP_DAYS_SINCE_LAST_GAME"]
)


match_dataset = compute_rolling_rest_advantage(
    match_dataset, "TEAM_ID", "IS_HOME", "REST_ADVANTAGE", N_LIST
)

match_dataset = compute_home_away_pts(
    match_dataset, "TEAM_ID", "IS_HOME", "points_traditional", "OPP_points_traditional", N_LIST
)

# match_dataset = rename_pts_against_columns(match_dataset)

match_dataset = compute_h2h(match_dataset, N_LIST)
# match_dataset = compute_h2h_pts_margin(match_dataset, N_LIST)
match_dataset = compute_h2h_season(match_dataset)
match_dataset = compute_h2h_streak(match_dataset)

match_dataset = compute_elo(match_dataset)
match_dataset = compute_elo_season(match_dataset)

KeyboardInterrupt:

In [24]:
pd.options.display.max_columns = None
display(match_dataset)

          GAME_ID  GAME_DATE     TEAM_ID OPP_TEAM_ID  IS_HOME  IS_WIN  \
0      0021100001 2011-12-25  1610612738  1610612752      0.0     0.0
1      0021100001 2011-12-25  1610612752  1610612738      1.0     1.0
2      0021100002 2011-12-25  1610612742  1610612748      1.0     0.0
3      0021100002 2011-12-25  1610612748  1610612742      0.0     1.0
4      0021100003 2011-12-25  1610612741  1610612747      0.0     1.0
...           ...        ...         ...         ...      ...     ...
15231  0041600403 2017-06-07  1610612744  1610612739      0.0     1.0
15232  0041600404 2017-06-09  1610612739  1610612744      1.0     1.0
15233  0041600404 2017-06-09  1610612744  1610612739      0.0     0.0
15234  0041600405 2017-06-12  1610612739  1610612744      0.0     0.0
15235  0041600405 2017-06-12  1610612744  1610612739      1.0     1.0

       POINT_DIFF  points_traditional  ODDS  OPP_ODDS  \
0            -4.0               208.0  2.45      1.37
1             4.0               212.0  1.37      2.45
2           -22.0               188.0  2.43      1.37
3            22.0               210.0  1.37      2.43
4             2.0               176.0  1.38      2.43
...           ...                 ...   ...       ...
15231         5.0               118.0  1.53      2.16
15232        21.0               137.0  2.43      1.42
15233       -21.0               116.0  1.42      2.43
15234        -9.0               120.0  3.43      1.22
15235         9.0               129.0  1.22      3.43

       fieldGoalsMade_traditional  fieldGoalsAttempted_traditional  \
0                            78.0                            152.0
1                            70.0                            148.0
2                            62.0                            164.0
3                            76.0                            156.0
4                            72.0                            178.0
...                           ...                              ...
15231                        40.0                             83.0
15232                        46.0                             87.0
15233                        39.0                             87.0
15234                        47.0                             88.0
15235                        46.0                             90.0

       threePointersMade_traditional  threePointersAttempted_traditional  \
0                                4.0                                10.0
1                               18.0                                40.0
2                               18.0                                56.0
3                                8.0                                14.0
4                               14.0                                30.0
...                              ...                                 ...
15231                           16.0                                33.0
15232                           24.0                                45.0
15233                           11.0                                39.0
15234                           11.0                                24.0
15235                           14.0                                38.0

       freeThrowsMade_traditional  freeThrowsAttempted_traditional  \
0                            48.0                             62.0
1                            54.0                             68.0
2                            46.0                             60.0
3                            50.0                             72.0
4                            18.0                             28.0
...                           ...                              ...
15231                        22.0                             24.0
15232                        21.0                             31.0
15233                        27.0                             36.0
15234                        15.0                             23.0
15235                        23.0                             28.0

       reboundsOffensive_traditional  reboundsDefensive_traditional  \
0                               26.0                           56.0
1                               16.0                           46.0
2                               16.0                           46.0
3                               30.0                           72.0
4                               32.0                           50.0
...                              ...                            ...
15231                            8.0                           36.0
15232                           11.0                           30.0
15233                           16.0                           24.0
15234                           12.0                           28.0
15235                           13.0                           29.0

       reboundsTotal_traditional  assists_traditional  steals_traditional  \
0                           82.0                 56.0                14.0
1                           62.0                 34.0                18.0
2                           62.0                 46.0                20.0
3                          102.0                 36.0                18.0
4                           82.0                 42.0                28.0
...                          ...                  ...                 ...
15231                       44.0                 29.0                 8.0
15232                       41.0                 27.0                 6.0
15233                       40.0                 26.0                 5.0
15234                       40.0                 22.0                 6.0
15235                       42.0                 27.0                 8.0

       blocks_traditional  turnovers_traditional  foulsPersonal_traditional  \
0                    10.0                   36.0                       56.0
1                    22.0                   32.0                       50.0
2                     0.0                   34.0                       58.0
3                    12.0                   44.0                       56.0
4                     8.0                   28.0                       42.0
...                   ...                    ...                        ...
15231                 4.0                   18.0                       28.0
15232                 3.0                   11.0                       24.0
15233                 6.0                   12.0                       27.0
15234                 5.0                   14.0                       22.0
15235                 2.0                   13.0                       24.0

       MINUTES_PLAYED  pointsOffTurnovers_misc  pointsSecondChance_misc  \
0          480.066667                     46.0                     28.0
1          480.000000                     36.0                     30.0
2          480.000000                     58.0                     16.0
3          480.000000                     50.0                     20.0
4          480.000000                     34.0                     24.0
...               ...                      ...                      ...
15231      240.000000                     20.0                     16.0
15232      240.000000                     18.0                     21.0
15233      240.016667                     10.0                     15.0
15234      240.000000                     25.0                     20.0
15235      240.000000                     21.0                     15.0

       pointsFastBreak_misc  pointsPaint_misc  blocksAgainst_misc  \
0                      32.0              96.0                22.0
1                      16.0              60.0                10.0
2                      20.0              56.0                12.0
3                      62.0              88.0                 0.0
4                      24.0              84.0                16.0
...                     ...               ...                 ...
15231                  24.0              38.0                 3.0
15232                   8.0              36.0                 6.0
15233                   9.0              40.0                 3.0
15234                  25.0              62.0                 2.0
15235                  18.0              52.0                 5.0

       offensiveRating_advanced  defensiveRating_advanced  netRating_advanced  \
0                    108.222233                111.932634           -3.694161
1                    111.690535                109.301778            2.391958
2                     93.242326                103.892722          -10.645875
3                    105.091562                 92.652757           12.443250
4                     98.512514                 97.707549            0.800771
...                         ...                       ...                 ...
15231                117.980799                111.665500            6.310889
15232                143.924910                119.523819           24.386257
15233                120.743719                143.609847          -22.860322
15234                121.789722                127.352653           -5.543674
15235                128.643153                122.172042            6.487667

       assistPercentage_advanced  assistToTurnover_advanced  \
0                       0.181532                   0.790279
1                       0.126097                   0.960625
2                       0.188613                   0.796389
3                       0.123284                   0.772721
4                       0.153143                   0.610694
...                          ...                        ...
15231                   0.173779                   2.263830
15232                   0.149844                   1.804391
15233                   0.164756                   1.827392
15234                   0.128000                   1.207535
15235                   0.150365                   1.179740

       assistRatio_advanced  offensiveReboundPercentage_advanced  \
0                 22.503020                             0.061573
1                 16.776063                             0.036982
2                 16.193778                             0.030597
3                 12.838507                             0.066478
4                 15.807715                             0.059251
...                     ...                                  ...
15231             21.133632                             0.036072
15232             18.908194                             0.046927
15233             17.123998                             0.058239
15234             14.285500                             0.051772
15235             18.494819                             0.053119

       defensiveReboundPercentage_advanced  reboundPercentage_advanced  \
0                                 0.134002                    0.097899
1                                 0.110483                    0.073473
2                                 0.109217                    0.064217
3                                 0.135241                    0.105986
4                                 0.116565                    0.084043
...                                    ...                         ...
15231                             0.134347                    0.090214
15232                             0.114640                    0.086014
15233                             0.116001                    0.083350
15234                             0.120648                    0.085652
15235                             0.120246                    0.089912

       turnoverRatio_advanced  effectiveFieldGoalPercentage_advanced  \
0                   12.900889                               0.453896
1                   14.148785                               0.504104
2                   14.164944                               0.391964
3                   17.983465                               0.548017
4                   11.089632                               0.436749
...                       ...                                    ...
15231               13.509750                               0.502234
15232                9.386729                               0.689620
15233                7.918735                               0.529264
15234               11.077937                               0.582644
15235                8.272854                               0.547206

       trueShootingPercentage_advanced  usagePercentage_advanced  \
0                             0.519213                  0.191597
1                             0.548899                  0.195513
2                             0.461304                  0.197981
3                             0.573978                  0.193178
4                             0.453350                  0.196549
...                                ...                       ...
15231                         0.573268                  0.195801
15232                         0.679870                  0.199086
15233                         0.550556                  0.198723
15234                         0.607025                  0.198684
15235                         0.580721                  0.196525

       estimatedPace_advanced  pace_advanced  possessions_advanced  \
0                   96.309683      95.611487             58.667477
1                   96.300708      95.199224             58.210000
2                  103.019453     100.899090             46.477153
3                  103.019219     101.200267             55.740139
4                   91.481810      89.301101             51.621736
...                       ...            ...                   ...
15231              103.278042     100.600913             64.662361
15232               99.739830      96.300538             59.229375
15233               99.742829      95.901633             57.778488
15234              101.720536     100.101136             68.871528
15235              101.718108      99.399156             71.476250

       PIE_advanced  effectiveFieldGoalPercentage_fourfactors  \
0          0.105580                                  0.527782
1          0.093249                                  0.532830
2          0.117762                                  0.434031
3          0.072708                                  0.511090
4          0.096233                                  0.442985
...             ...                                       ...
15231      0.119599                                  0.577433
15232      0.114793                                  0.673553
15233      0.081546                                  0.511071
15234      0.088589                                  0.596013
15235      0.107421                                  0.588877

       freeThrowAttemptRate_fourfactors  teamTurnoverPercentage_fourfactors  \
0                              0.418177                            0.197031
1                              0.466765                            0.163975
2                              0.369116                            0.161587
3                              0.458427                            0.225250
4                              0.157266                            0.149571
...                                 ...                                 ...
15231                          0.290488                            0.173693
15232                          0.375250                            0.110169
15233                          0.416414                            0.120787
15234                          0.264821                            0.147290
15235                          0.312834                            0.126243

       oppEffectiveFieldGoalPercentage_fourfactors  \
0                                         0.535076
1                                         0.523165
2                                         0.505683
3                                         0.430919
4                                         0.504284
...                                            ...
15231                                     0.511252
15232                                     0.512060
15233                                     0.670647
15234                                     0.590410
15235                                     0.594327

       oppFreeThrowAttemptRate_fourfactors  \
0                                 0.465478
1                                 0.416090
2                                 0.459455
3                                 0.370513
4                                 0.265141
...                                    ...
15231                             0.280507
15232                             0.423046
15233                             0.389597
15234                             0.319451
15235                             0.261859

       oppTeamTurnoverPercentage_fourfactors  \
0                                   0.165281
1                                   0.198781
2                                   0.227592
3                                   0.164162
4                                   0.187859
...                                      ...
15231                               0.116964
15232                               0.120607
15233                               0.110226
15234                               0.126091
15235                               0.147807

       oppOffensiveReboundPercentage_fourfactors  foulsDrawn_misc  \
0                                       0.219223         3.478475
1                                       0.364813         3.618611
2                                       0.393651         2.579861
3                                       0.173621         3.905417
4                                       0.324516         2.305347
...                                          ...              ...
15231                                   0.215773         3.422361
15232                                   0.345281         3.343958
15233                                   0.307564         3.248247
15234                                   0.312421         3.637778
15235                                   0.297210         3.339028

       percentageFieldGoalsAttempted2pt_scoring  \
0                                      0.872849
1                                      0.703230
2                                      0.629453
3                                      0.882384
4                                      0.844803
...                                         ...
15231                                  0.575468
15232                                  0.477771
15233                                  0.573239
15234                                  0.640640
15235                                  0.585860

       percentageFieldGoalsAttempted3pt_scoring  percentagePoints2pt_scoring  \
0                                      0.063896                     0.657995
1                                      0.259062                     0.478796
2                                      0.370547                     0.391193
3                                      0.093172                     0.629823
4                                      0.155197                     0.700210
...                                         ...                          ...
15231                                  0.355018                     0.385675
15232                                  0.503340                     0.351049
15233                                  0.404957                     0.483369
15234                                  0.359360                     0.512974
15235                                  0.409695                     0.440319

       percentagePointsMidrange2pt_scoring  percentagePoints3pt_scoring  \
0                                 0.198006                     0.047118
1                                 0.197675                     0.193396
2                                 0.121015                     0.262616

# 🧽 Nettoyage et sauvegarde

In [25]:


final_date = datetime.now().strftime('%Y-%m-%d_%H-%M-%S')
raw_save_path = os.path.join(DATA_FINAL_DATASET_DIR, f'nba_features_final_{final_date}.csv')
clean_save_path = os.path.join(DATA_FINAL_CLEANED_DATASET_DIR, f'nba_features_cleaned_final_{final_date}.csv')

os.makedirs(DATA_FINAL_DATASET_DIR, exist_ok=True)
os.makedirs(DATA_FINAL_CLEANED_DATASET_DIR, exist_ok=True)

match_dataset.to_csv(raw_save_path, index=False)

final_cleaned = match_dataset.drop(columns=features_to_roll+COLS_MATCH_REAL, errors='ignore')
final_cleaned.to_csv(clean_save_path, index=False)

print(f"✅ Fichier brut : {raw_save_path}")
print(f"✅ Fichier clean : {clean_save_path}")

final_cleaned

✅ Fichier brut : data\final_dataset\nba_features_final_2025-06-05_15-47-52.csv
✅ Fichier clean : data\final_cleaned_dataset\nba_features_cleaned_final_2025-06-05_15-47-52.csv

,GAME_ID,GAME_DATE,TEAM_ID,OPP_TEAM_ID,IS_HOME,IS_WIN,POINT_DIFF,ODDS,OPP_ODDS,SEASON,ROLL_fieldGoalsMade_traditional_3,ROLL_fieldGoalsMade_traditional_5,ROLL_fieldGoalsMade_traditional_10,ROLL_fieldGoalsMade_traditional_25,ROLL_fieldGoalsMade_traditional_50,ROLL_fieldGoalsMade_traditional_100,ROLL_fieldGoalsMade_traditional_200,ROLL_fieldGoalsAttempted_traditional_3,ROLL_fieldGoalsAttempted_traditional_5,ROLL_fieldGoalsAttempted_traditional_10,ROLL_fieldGoalsAttempted_traditional_25,ROLL_fieldGoalsAttempted_traditional_50,ROLL_fieldGoalsAttempted_traditional_100,ROLL_fieldGoalsAttempted_traditional_200,ROLL_threePointersMade_traditional_3,ROLL_threePointersMade_traditional_5,ROLL_threePointersMade_traditional_10,ROLL_threePointersMade_traditional_25,ROLL_threePointersMade_traditional_50,ROLL_threePointersMade_traditional_100,ROLL_threePointersMade_traditional_200,ROLL_threePointersAttempted_traditional_3,ROLL_threePointersAttempted_traditional_5,ROLL_threePointersAttempted_traditional_10,ROLL_threePointersAttempted_traditional_25,ROLL_threePointersAttempted_traditional_50,ROLL_threePointersAttempted_traditional_100,ROLL_threePointersAttempted_traditional_200,ROLL_freeThrowsMade_traditional_3,ROLL_freeThrowsMade_traditional_5,ROLL_freeThrowsMade_traditional_10,ROLL_freeThrowsMade_traditional_25,ROLL_freeThrowsMade_traditional_50,ROLL_freeThrowsMade_traditional_100,ROLL_freeThrowsMade_traditional_200,ROLL_freeThrowsAttempted_traditional_3,ROLL_freeThrowsAttempted_traditional_5,ROLL_freeThrowsAttempted_traditional_10,ROLL_freeThrowsAttempted_traditional_25,ROLL_freeThrowsAttempted_traditional_50,ROLL_freeThrowsAttempted_traditional_100,ROLL_freeThrowsAttempted_traditional_200,ROLL_reboundsOffensive_traditional_3,ROLL_reboundsOffensive_traditional_5,ROLL_reboundsOffensive_traditional_10,ROLL_reboundsOffensive_traditional_25,ROLL_reboundsOffensive_traditional_50,ROLL_reboundsOffensive_traditional_100,ROLL_reboundsOffensive_traditional_200,ROLL_reboundsDefensive_traditional_3,ROLL_reboundsDefensive_traditional_5,ROLL_reboundsDefensive_traditional_10,ROLL_reboundsDefensive_traditional_25,ROLL_reboundsDefensive_traditional_50,ROLL_reboundsDefensive_traditional_100,ROLL_reboundsDefensive_traditional_200,ROLL_reboundsTotal_traditional_3,ROLL_reboundsTotal_traditional_5,ROLL_reboundsTotal_traditional_10,ROLL_reboundsTotal_traditional_25,ROLL_reboundsTotal_traditional_50,ROLL_reboundsTotal_traditional_100,ROLL_reboundsTotal_traditional_200,ROLL_assists_traditional_3,ROLL_assists_traditional_5,ROLL_assists_traditional_10,ROLL_assists_traditional_25,ROLL_assists_traditional_50,ROLL_assists_traditional_100,ROLL_assists_traditional_200,ROLL_steals_traditional_3,ROLL_steals_traditional_5,ROLL_steals_traditional_10,ROLL_steals_traditional_25,ROLL_steals_traditional_50,ROLL_steals_traditional_100,ROLL_steals_traditional_200,ROLL_blocks_traditional_3,ROLL_blocks_traditional_5,ROLL_blocks_traditional_10,ROLL_blocks_traditional_25,ROLL_blocks_traditional_50,ROLL_blocks_traditional_100,ROLL_blocks_traditional_200,ROLL_turnovers_traditional_3,ROLL_turnovers_traditional_5,ROLL_turnovers_traditional_10,ROLL_turnovers_traditional_25,ROLL_turnovers_traditional_50,ROLL_turnovers_traditional_100,ROLL_turnovers_traditional_200,ROLL_foulsPersonal_traditional_3,ROLL_foulsPersonal_traditional_5,ROLL_foulsPersonal_traditional_10,ROLL_foulsPersonal_traditional_25,ROLL_foulsPersonal_traditional_50,ROLL_foulsPersonal_traditional_100,ROLL_foulsPersonal_traditional_200,ROLL_points_traditional_3,ROLL_points_traditional_5,ROLL_points_traditional_10,ROLL_points_traditional_25,ROLL_points_traditional_50,ROLL_points_traditional_100,ROLL_points_traditional_200,ROLL_MINUTES_PLAYED_3,ROLL_MINUTES_PLAYED_5,ROLL_MINUTES_PLAYED_10,ROLL_MINUTES_PLAYED_25,ROLL_MINUTES_PLAYED_50,ROLL_MINUTES_PLAYED_100,ROLL_MINUTES_PLAYED_200,ROLL_pointsOffTurnovers_misc_3,ROLL_pointsOffTurnovers_misc_5,ROLL_pointsOffTurnovers_misc_10,ROLL_pointsOffTurnovers_misc_25,ROLL_pointsOffTurnovers_misc_50,ROLL_pointsOffTurnovers_misc_100,ROLL_pointsOffTurnovers_misc_200,ROLL_pointsSecondChance_misc_3,ROLL_pointsSecondChance_misc_5,ROLL_pointsSecondChance_misc_10,ROLL_pointsSecondChance_misc_25,ROLL_pointsSecondChance_misc_50,ROLL_pointsSecondChance_misc_100,ROLL_pointsSecondChance_misc_200,ROLL_pointsFastBreak_misc_3,ROLL_pointsFastBreak_misc_5,ROLL_pointsFastBreak_misc_10,ROLL_pointsFastBreak_misc_25,ROLL_pointsFastBreak_misc_50,ROLL_pointsFastBreak_misc_100,ROLL_pointsFastBreak_misc_200,ROLL_pointsPaint_misc_3,ROLL_pointsPaint_misc_5,ROLL_pointsPaint_misc_10,ROLL_pointsPaint_misc_25,ROLL_pointsPaint_misc_50,ROLL_pointsPaint_misc_100,ROLL_pointsPaint_misc_200,ROLL_blocksAgainst_misc_3,ROLL_blocksAgainst_misc_5,ROLL_blocksAgainst_misc_10,ROLL_blocksAgainst_misc_25,ROLL_blocksAgainst_misc_50,ROLL_blocksAgainst_misc_100,ROLL_blocksAgainst_misc_200,ROLL_offensiveRating_advanced_3,ROLL_offensiveRating_advanced_5,ROLL_offensiveRating_advanced_10,ROLL_offensiveRating_advanced_25,ROLL_offensiveRating_advanced_50,ROLL_offensiveRating_advanced_100,ROLL_offensiveRating_advanced_200,ROLL_defensiveRating_advanced_3,ROLL_defensiveRating_advanced_5,ROLL_defensiveRating_advanced_10,ROLL_defensiveRating_advanced_25,ROLL_defensiveRating_advanced_50,ROLL_defensiveRating_advanced_100,ROLL_defensiveRating_advanced_200,ROLL_netRating_advanced_3,ROLL_netRating_advanced_5,ROLL_netRating_advanced_10,ROLL_netRating_advanced_25,ROLL_netRating_advanced_50,ROLL_netRating_advanced_100,ROLL_netRating_advanced_200,ROLL_assistPercentage_advanced_3,ROLL_assistPercentage_advanced_5,ROLL_assistPercentage_advanced_10,ROLL_assistPercentage_advanced_25,ROLL_assistPercentage_advanced_50,ROLL_assistPercentage_advanced_100,ROLL_assistPercentage_advanced_200,ROLL_assistToTurnover_advanced_3,ROLL_assistToTurnover_advanced_5,ROLL_assistToTurnover_advanced_10,ROLL_assistToTurnover_advanced_25,ROLL_assistToTurnover_advanced_50,ROLL_assistToTurnover_advanced_100,ROLL_assistToTurnover_advanced_200,ROLL_assistRatio_advanced_3,ROLL_assistRatio_advanced_5,ROLL_assistRatio_advanced_10,ROLL_assistRatio_advanced_25,ROLL_assistRatio_advanced_50,ROLL_assistRatio_advanced_100,ROLL_assistRatio_advanced_200,ROLL_offensiveReboundPercentage_advanced_3,ROLL_offensiveReboundPercentage_advanced_5,ROLL_offensiveReboundPercentage_advanced_10,ROLL_offensiveReboundPercentage_advanced_25,ROLL_offensiveReboundPercentage_advanced_50,ROLL_offensiveReboundPercentage_advanced_100,ROLL_offensiveReboundPercentage_advanced_200,ROLL_defensiveReboundPercentage_advanced_3,ROLL_defensiveReboundPercentage_advanced_5,ROLL_defensiveReboundPercentage_advanced_10,ROLL_defensiveReboundPercentage_advanced_25,ROLL_defensiveReboundPercentage_advanced_50,ROLL_defensiveReboundPercentage_advanced_100,ROLL_defensiveReboundPercentage_advanced_200,ROLL_reboundPercentage_advanced_3,ROLL_reboundPercentage_advanced_5,ROLL_reboundPercentage_advanced_10,ROLL_reboundPercentage_advanced_25,ROLL_reboundPercentage_advanced_50,ROLL_reboundPercentage_advanced_100,ROLL_reboundPercentage_advanced_200,ROLL_turnoverRatio_advanced_3,ROLL_turnoverRatio_advanced_5,ROLL_turnoverRatio_advanced_10,ROLL_turnoverRatio_advanced_25,ROLL_turnoverRatio_advanced_50,ROLL_turnoverRatio_advanced_100,ROLL_turnoverRatio_advanced_200,ROLL_effectiveFieldGoalPercentage_advanced_3,ROLL_effectiveFieldGoalPercentage_advanced_5,ROLL_effectiveFieldGoalPercentage_advanced_10,ROLL_effectiveFieldGoalPercentage_advanced_25,ROLL_effectiveFieldGoalPercentage_advanced_50,ROLL_effectiveFieldGoalPercentage_advanced_100,ROLL_effectiveFieldGoalPercentage_advanced_200,ROLL_trueShootingPercentage_advanced_3,ROLL_trueShootingPercentage_advanced_5,ROLL_trueShootingPercentage_advanced_10,ROLL_trueShootingPercentage_advanced_25,ROLL_trueShootingPercentage_advanced_50,ROLL_trueShootingPercentage_advanced_100,ROLL_trueShootingPercentage_advanced_200,ROLL_usagePercentage_advanced_3,ROLL_usagePercentage_advanced_5,ROLL_usagePercentage_advanced_10,ROLL_usagePercentage_advanced_25,ROLL_usagePercentage_advanced_50,ROLL_usagePercentage_advanced_100,ROLL_usagePercentage_advanced_200,ROLL_estimatedPace_advanced_3,ROLL_estimatedPace_advanced_5,ROLL_estimatedPace_advanced_10,ROLL_estimatedPace_advanced_25,ROLL_estimatedPace_advanced_50,ROLL_estimatedPace_advanced_100,ROLL_estimatedPace_advanced_200,ROLL_pace_advanced_3,ROLL_pace_advanced_5,ROLL_pace_advanced_10,ROLL_pace_advanced_25,ROLL_pace_advanced_50,ROLL_pace_advanced_100,ROLL_pace_advanced_200,ROLL_possessions_advanced_3,ROLL_possessions_advanced_5,ROLL_possessions_advanced_10,ROLL_possessions_advanced_25,ROLL_possessions_advanced_50,ROLL_possessions_advanced_100,ROLL_possessions_advanced_200,ROLL_PIE_advanced_3,ROLL_PIE_advanced_5,ROLL_PIE_advanced_10,ROLL_PIE_advanced_25,ROLL_PIE_advanced_50,ROLL_PIE_advanced_100,ROLL_PIE_advanced_200,ROLL_effectiveFieldGoalPercentage_fourfactors_3,ROLL_effectiveFieldGoalPercentage_fourfactors_5,ROLL_effectiveFieldGoalPercentage_fourfactors_10,ROLL_effectiveFieldGoalPercentage_fourfactors_25,ROLL_effectiveFieldGoalPercentage_fourfactors_50,ROLL_effectiveFieldGoalPercentage_fourfactors_100,ROLL_effectiveFieldGoalPercentage_fourfactors_200,ROLL_freeThrowAttemptRate_fourfactors_3,ROLL_freeThrowAttemptRate_fourfactors_5,ROLL_freeThrowAttemptRate_fourfactors_10,ROLL_freeThrowAttemptRate_fourfactors_25,ROLL_freeThrowAttemptRate_fourfactors_50,ROLL_freeThrowAttemptRate_fourfactors_100,ROLL_freeThrowAttemptRate_fourfactors_200,ROLL_teamTurnoverPercentage_fourfactors_3,ROLL_teamTurnoverPercentage_fourfactors_5,ROLL_teamTurnoverPercentage_fourfactors_10,ROLL_teamTurnoverPercentage_fourfactors_25,ROLL_teamTurnoverPercentage_fourfactors_50,ROLL_teamTurnoverPercentage_fourfactors_100,ROLL_teamTurnoverPercentage_fourfactors_200,ROLL_oppEffectiveFieldGoalPercentage_fourfactors_3,ROLL_oppEffectiveFieldGoalPercentage_fourfactors_5,ROLL_oppEffectiveFieldGoalPercentage_fourfactors_10,ROLL_oppEffectiveFieldGoalPercentage_fourfactors_25,ROLL_oppEffectiveFieldGoalPercentage_fourfactors_50,ROLL_oppEffectiveFieldGoalPercentage_fourfactors_100,ROLL_oppEffectiveFieldGoalPercentage_fourfactors_200,ROLL_oppFreeThrowAttemptRate_fourfactors_3,ROLL_oppFreeThrowAttemptRate_fourfactors_5,ROLL_oppFreeThrowAttemptRate_fourfactors_10,ROLL_oppFreeThrowAttemptRate_fourfactors_25,ROLL_oppFreeThrowAttemptRate_fourfactors_50,ROLL_oppFreeThrowAttemptRate_fourfactors_100,ROLL_oppFreeThrowAttemptRate_fourfactors_200,ROLL_oppTeamTurnoverPercentage_fourfactors_3,ROLL_oppTeamTurnoverPercentage_fourfactors_5,ROLL_oppTeamTurnoverPercentage_fourfactors_10,ROLL_oppTeamTurnoverPercentage_fourfactors_25,ROLL_oppTeamTurnoverPercentage_fourfactors_50,ROLL_oppTeamTurnoverPercentage_fourfactors_100,ROLL_oppTeamTurnoverPercentage_fourfactors_200,ROLL_oppOffensiveReboundPercentage_fourfactors_3,ROLL_oppOffensiveReboundPercentage_fourfactors_5,ROLL_oppOffensiveReboundPercentage_fourfactors_10,ROLL_oppOffensiveReboundPercentage_fourfactors_25,ROLL_oppOffensiveReboundPercentage_fourfactors_50,ROLL_oppOffensiveReboundPercentage_fourfactors_100,ROLL_oppOffensiveReboundPercentage_fourfactors_200,ROLL_foulsDrawn_misc_3,ROLL_foulsDrawn_misc_5,ROLL_foulsDrawn_misc_10,ROLL_foulsDrawn_misc_25,ROLL_foulsDrawn_misc_50,ROLL_foulsDrawn_misc_100,ROLL_foulsDrawn_misc_200,ROLL_percentageFieldGoalsAttempted2pt_scoring_3,ROLL_percentageFieldGoalsAttempted2pt_scoring_5,ROLL_percentageFieldGoalsAttempted2pt_scoring_10,ROLL_percentageFieldGoalsAttempted2pt_scoring_25,ROLL_percentageFieldGoalsAttempted2pt_scoring_50,ROLL_percentageFieldGoalsAttempted2pt_scoring_100,ROLL_percentageFieldGoalsAttempted2pt_scoring_200,ROLL_percentageFieldGoalsAttempted3pt_scoring_3,ROLL_percentageFieldGoalsAttempted3pt_scoring_5,ROLL_percentageFieldGoalsAttempted3pt_scoring_10,ROLL_percentageFieldGoalsAttempted3pt_scoring_25,ROLL_percentageFieldGoalsAttempted3pt_scoring_50,ROLL_percentageFieldGoalsAttempted3pt_scoring_100,ROLL_percentageFieldGoalsAttempted3pt_scoring_200,ROLL_percentagePoints2pt_scoring_3,ROLL_percentagePoints2pt_scoring_5,ROLL_percentagePoints2pt_scoring_10,ROLL_percentagePoints2pt_scoring_25,ROLL_percentagePoints2pt_scoring_50,ROLL_percentagePoints2pt_scoring_100,ROLL_percentagePoints2pt_scoring_200,ROLL_percentagePointsMidrange2pt_scoring_3,ROLL_percentagePointsMidrange2pt_scoring_5,ROLL_percentagePointsMidrange2pt_scoring_10,ROLL_percentagePointsMidrange2pt_scoring_25,ROLL_percentagePointsMidrange2pt_scoring_50,ROLL_percentagePointsMidrange2pt_scoring_100,ROLL_percentagePointsMidrange2pt_scoring_200,ROLL_percentagePoints3pt_scoring_3,ROLL_percentagePoints3pt_scoring_5,ROLL_percentagePoints3pt_scoring_10,ROLL_percentagePoints3pt_scoring_25,ROLL_percentagePoints3pt_scoring_50,ROLL_percentagePoints3pt_scoring_100,ROLL_percentagePoints3pt_scoring_200,ROLL_percentagePointsFastBreak_scoring_3,ROLL_percentagePointsFastBreak_scoring_5,ROLL_percentagePointsFastBreak_scoring_10,ROLL_percentagePointsFastBreak_scoring_25,ROLL_percentagePointsFastBreak_scoring_50,ROLL_percentagePointsFastBreak_scoring_100,ROLL_percentagePointsFastBreak_scoring_200,ROLL_percentagePointsFreeThrow_scoring_3,ROLL_percentagePointsFreeThrow_scoring_5,ROLL_percentagePointsFreeThrow_scoring_10,ROLL_percentagePointsFreeThrow_scoring_25,ROLL_percentagePointsFreeThrow_scoring_50,ROLL_percentagePointsFreeThrow_scoring_100,ROLL_percentagePointsFreeThrow_scoring_200,ROLL_percentagePointsOffTurnovers_scoring_3,ROLL_percentagePointsOffTurnovers_scoring_5,ROLL_percentagePointsOffTurnovers_scoring_10,ROLL_percentagePointsOffTurnovers_scoring_25,ROLL_percentagePointsOffTurnovers_scoring_50,ROLL_percentagePointsOffTurnovers_scoring_100,ROLL_percentagePointsOffTurnovers_scoring_200,ROLL_percentagePointsPaint_scoring_3,ROLL_percentagePointsPaint_scoring_5,ROLL_percentagePointsPaint_scoring_10,ROLL_percentagePointsPaint_scoring_25,ROLL_percentagePointsPaint_scoring_50,ROLL_percentagePointsPaint_scoring_100,ROLL_percentagePointsPaint_scoring_200,ROLL_percentageAssisted2pt_scoring_3,ROLL_percentageAssisted2pt_scoring_5,ROLL_percentageAssisted2pt_scoring_10,ROLL_percentageAssisted2pt_scoring_25,ROLL_percentageAssisted2pt_scoring_50,ROLL_percentageAssisted2pt_scoring_100,ROLL_percentageAssisted2pt_scoring_200,ROLL_percentageUnassisted2pt_scoring_3,ROLL_percentageUnassisted2pt_scoring_5,ROLL_percentageUnassisted2pt_scoring_10,ROLL_percentageUnassisted2pt_scoring_25,ROLL_percentageUnassisted2pt_scoring_50,ROLL_percentageUnassisted2pt_scoring_100,ROLL_percentageUnassisted2pt_scoring_200,ROLL_percentageAssisted3pt_scoring_3,ROLL_percentageAssisted3pt_scoring_5,ROLL_percentageAssisted3pt_scoring_10,ROLL_percentageAssisted3pt_scoring_25,ROLL_percentageAssisted3pt_scoring_50,ROLL_percentageAssisted3pt_scoring_100,ROLL_percentageAssisted3pt_scoring_200,ROLL_percentageUnassisted3pt_scoring_3,ROLL_percentageUnassisted3pt_scoring_5,ROLL_percentageUnassisted3pt_scoring_10,ROLL_percentageUnassisted3pt_scoring_25,ROLL_percentageUnassisted3pt_scoring_50,ROLL_percentageUnassisted3pt_scoring_100,ROLL_percentageUnassisted3pt_scoring_200,ROLL_percentageAssistedFGM_scoring_3,ROLL_percentageAssistedFGM_scoring_5,ROLL_percentageAssistedFGM_scoring_10,ROLL_percentageAssistedFGM_scoring_25,ROLL_percentageAssistedFGM_scoring_50,ROLL_percentageAssistedFGM_scoring_100,ROLL_percentageAssistedFGM_scoring_200,ROLL_percentageUnassistedFGM_scoring_3,ROLL_percentageUnassistedFGM_scoring_5,ROLL_percentageUnassistedFGM_scoring_10,ROLL_percentageUnassistedFGM_scoring_25,ROLL_percentageUnassistedFGM_scoring_50,ROLL_percentageUnassistedFGM_scoring_100,ROLL_percentageUnassistedFGM_scoring_200,ROLL_threePointersPercentage_traditional_3,ROLL_threePointersPercentage_traditional_5,ROLL_threePointersPercentage_traditional_10,ROLL_threePointersPercentage_traditional_25,ROLL_threePointersPercentage_traditional_50,ROLL_threePointersPercentage_traditional_100,ROLL_threePointersPercentage_traditional_200,ROLL_freeThrowsPercentage_traditional_3,ROLL_freeThrowsPercentage_traditional_5,ROLL_freeThrowsPercentage_traditional_10,ROLL_freeThrowsPercentage_traditional_25,ROLL_freeThrowsPercentage_traditional_50,ROLL_freeThrowsPercentage_traditional_100,ROLL_freeThrowsPercentage_traditional_200,ROLL_percentageFieldGoalsMade_usage_3,ROLL_percentageFieldGoalsMade_usage_5,ROLL_percentageFieldGoalsMade_usage_10,ROLL_percentageFieldGoalsMade_usage_25,ROLL_percentageFieldGoalsMade_usage_50,ROLL_percentageFieldGoalsMade_usage_100,ROLL_percentageFieldGoalsMade_usage_200,ROLL_percentageFieldGoalsAttempted_usage_3,ROLL_percentageFieldGoalsAttempted_usage_5,ROLL_percentageFieldGoalsAttempted_usage_10,ROLL_percentageFieldGoalsAttempted_usage_25,ROLL_percentageFieldGoalsAttempted_usage_50,ROLL_percentageFieldGoalsAttempted_usage_100,ROLL_percentageFieldGoalsAttempted_usage_200,ROLL_percentageThreePointersMade_usage_3,ROLL_percentageThreePointersMade_usage_5,ROLL_percentageThreePointersMade_usage_10,ROLL_percentageThreePointersMade_usage_25,ROLL_percentageThreePointersMade_usage_50,ROLL_percentageThreePointersMade_usage_100,ROLL_percentageThreePointersMade_usage_200,ROLL_percentageThreePointersAttempted_usage_3,ROLL_percentageThreePointersAttempted_usage_5,ROLL_percentageThreePointersAttempted_usage_10,ROLL_percentageThreePointersAttempted_usage_25,ROLL_percentageThreePointersAttempted_usage_50,ROLL_percentageThreePointersAttempted_usage_100,ROLL_percentageThreePointersAttempted_usage_200,ROLL_percentageFreeThrowsMade_usage_3,ROLL_percentageFreeThrowsMade_usage_5,ROLL_percentageFreeThrowsMade_usage_10,ROLL_percentageFreeThrowsMade_usage_25,ROLL_percentageFreeThrowsMade_usage_50,ROLL_percentageFreeThrowsMade_usage_100,ROLL_percentageFreeThrowsMade_usage_200,ROLL_percentageFreeThrowsAttempted_usage_3,ROLL_percentageFreeThrowsAttempted_usage_5,ROLL_percentageFreeThrowsAttempted_usage_10,ROLL_percentageFreeThrowsAttempted_usage_25,ROLL_percentageFreeThrowsAttempted_usage_50,ROLL_percentageFreeThrowsAttempted_usage_100,ROLL_percentageFreeThrowsAttempted_usage_200,ROLL_percentageReboundsOffensive_usage_3,ROLL_percentageReboundsOffensive_usage_5,ROLL_percentageReboundsOffensive_usage_10,ROLL_percentageReboundsOffensive_usage_25,ROLL_percentageReboundsOffensive_usage_50,ROLL_percentageReboundsOffensive_usage_100,ROLL_percentageReboundsOffensive_usage_200,ROLL_percentageReboundsDefensive_usage_3,ROLL_percentageReboundsDefensive_usage_5,ROLL_percentageReboundsDefensive_usage_10,ROLL_percentageReboundsDefensive_usage_25,ROLL_percentageReboundsDefensive_usage_50,ROLL_percentageReboundsDefensive_usage_100,ROLL_percentageReboundsDefensive_usage_200,ROLL_percentageReboundsTotal_usage_3,ROLL_percentageReboundsTotal_usage_5,ROLL_percentageReboundsTotal_usage_10,ROLL_percentageReboundsTotal_usage_25,ROLL_percentageReboundsTotal_usage_50,ROLL_percentageReboundsTotal_usage_100,ROLL_percentageReboundsTotal_usage_200,ROLL_percentageAssists_usage_3,ROLL_percentageAssists_usage_5,ROLL_percentageAssists_usage_10,ROLL_percentageAssists_usage_25,ROLL_percentageAssists_usage_50,ROLL_percentageAssists_usage_100,ROLL_percentageAssists_usage_200,ROLL_percentageTurnovers_usage_3,ROLL_percentageTurnovers_usage_5,ROLL_percentageTurnovers_usage_10,ROLL_percentageTurnovers_usage_25,ROLL_percentageTurnovers_usage_50,ROLL_percentageTurnovers_usage_100,ROLL_percentageTurnovers_usage_200,ROLL_percentageSteals_usage_3,ROLL_percentageSteals_usage_5,ROLL_percentageSteals_usage_10,ROLL_percentageSteals_usage_25,ROLL_percentageSteals_usage_50,ROLL_percentageSteals_usage_100,ROLL_percentageSteals_usage_200,ROLL_percentageBlocks_usage_3,ROLL_percentageBlocks_usage_5,ROLL_percentageBlocks_usage_10,ROLL_percentageBlocks_usage_25,ROLL_percentageBlocks_usage_50,ROLL_percentageBlocks_usage_100,ROLL_percentageBlocks_usage_200,ROLL_percentageBlocksAllowed_usage_3,ROLL_percentageBlocksAllowed_usage_5,ROLL_percentageBlocksAllowed_usage_10,ROLL_percentageBlocksAllowed_usage_25,ROLL_percentageBlocksAllowed_usage_50,ROLL_percentageBlocksAllowed_usage_100,ROLL_percentageBlocksAllowed_usage_200,ROLL_percentagePersonalFouls_usage

In [26]:
final_cleaned.columns

Index(['GAME_ID', 'GAME_DATE', 'TEAM_ID', 'OPP_TEAM_ID', 'IS_HOME', 'IS_WIN',
       'POINT_DIFF', 'ODDS', 'OPP_ODDS', 'SEASON',
       ...
       'H2H_LAST_200_WINRATE', 'H2H_LAST_200_COUNT', 'H2H_SEASON_WINS',
       'H2H_SEASON_MATCHES', 'H2H_SEASON_WINRATE', 'H2H_WIN_STREAK', 'ELO_PRE',
       'OPP_ELO_PRE', 'ELO_PRE_SEASON', 'OPP_ELO_PRE_SEASON'],
      dtype='object', length=1242)

In [27]:
#store end time of notebook
end_time = datetime.now()
print("End time: ", end_time)
print("Total time: ", end_time - start_time)

End time:  2025-06-05 15:48:48.432251
Total time:  0:01:54.779310