# Nettoyage & enrichissement des boxscores (minutes, DNP, totaux, ratios)

In [1]:
import pandas as pd
import numpy as np
import os
import datetime
from src.config import *
from src.utils import *
from src.feature_builder import *

In [2]:
#store start time of notebook
start_time = datetime.datetime.now()
print("Start time: ", start_time)

Start time:  2025-05-25 16:21:09.143782

# 🔁 Chargement des fichiers

In [3]:
boxscores_file = get_latest_file(DATA_LAST_BOXSCORES_BATCHES_MERGED_DIR)
games_file = get_latest_file(DATA_LAST_GAMES_MERGED_DIR)
df_boxscores = pd.read_csv(boxscores_file, dtype={'GAME_ID': str})
df_games = pd.read_csv(games_file, dtype={'GAME_ID': str})

# 🧼 Nettoyage des minutes jouées

In [4]:
def convert_minutes(val):
    if pd.isna(val) or val in ['DNP', '']:
        return 0.0
    try:
        parts = str(val).split(':')
        return int(parts[0]) + int(parts[1]) / 60 if len(parts) == 2 else float(val)
    except:
        return 0.0

df_boxscores['MINUTES_PLAYED'] = df_boxscores['MIN'].apply(convert_minutes)

# 🔄 Cast des colonnes numériques

In [5]:
cols_to_float = ['PTS', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'FGM', 'FGA', 'FG3M', 'FG3A',
                 'FTM', 'FTA', 'OREB', 'DREB', 'PLUS_MINUS']
for col in cols_to_float:
    if col in df_boxscores.columns:
        df_boxscores[col] = pd.to_numeric(df_boxscores[col], errors='coerce').fillna(0)

# ⚙️ Aggrégation par équipe et match

In [6]:
# 3. Merge pour ajouter GAME_DATE à chaque ligne de boxscore
if 'GAME_DATE' not in df_boxscores.columns:
    # Pour éviter les doublons ou les merges en cascade si tu relances le code
    if 'GAME_DATE' in df_games.columns:
        df_boxscores = df_boxscores.merge(
            df_games[['GAME_ID', 'GAME_DATE']],
            on='GAME_ID',
            how='left'
        )
        # Conversion en datetime
        df_boxscores['GAME_DATE'] = pd.to_datetime(df_boxscores['GAME_DATE'])
    else:
        print("No GAME_DATE column found in games_df. Please check your merge operation.")

In [7]:

agg_cols = ['FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT',
            'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TO', 'PF', 'PTS', 'PLUS_MINUS', 'MINUTES_PLAYED']
team_match_stats = df_boxscores.groupby(['GAME_ID', 'TEAM_ID', 'GAME_DATE'])[agg_cols].sum().reset_index()
teams_in_game = df_boxscores.groupby('GAME_ID')['TEAM_ID'].unique().to_dict()
team_match_stats['OPP_TEAM_ID'] = team_match_stats.apply(
    lambda row: [tid for tid in teams_in_game[row['GAME_ID']] if tid != row['TEAM_ID']][0], axis=1)

# 🔁 Merge avec l’adversaire

In [8]:
team_cols = [col for col in team_match_stats.columns if col not in ['GAME_ID', 'TEAM_ID', 'OPP_TEAM_ID']]
opp_cols = [f"OPP_{col}" for col in team_cols]
df_opp = team_match_stats.rename(columns={col: f"OPP_{col}" for col in team_cols}).rename(
    columns={'TEAM_ID': 'OPP_TEAM_ID', 'OPP_TEAM_ID': 'TEAM_ID'})
match_dataset = pd.merge(
    team_match_stats,
    df_opp[['GAME_ID', 'TEAM_ID'] + opp_cols],
    on=['GAME_ID', 'TEAM_ID'],
    how='left'
)

In [9]:
match_dataset.columns

Index(['GAME_ID', 'TEAM_ID', 'GAME_DATE', 'FGM', 'FGA', 'FG_PCT', 'FG3M',
       'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST',
       'STL', 'BLK', 'TO', 'PF', 'PTS', 'PLUS_MINUS', 'MINUTES_PLAYED',
       'OPP_TEAM_ID', 'OPP_GAME_DATE', 'OPP_FGM', 'OPP_FGA', 'OPP_FG_PCT',
       'OPP_FG3M', 'OPP_FG3A', 'OPP_FG3_PCT', 'OPP_FTM', 'OPP_FTA',
       'OPP_FT_PCT', 'OPP_OREB', 'OPP_DREB', 'OPP_REB', 'OPP_AST', 'OPP_STL',
       'OPP_BLK', 'OPP_TO', 'OPP_PF', 'OPP_PTS', 'OPP_PLUS_MINUS',
       'OPP_MINUTES_PLAYED'],
      dtype='object')

In [10]:
match_dataset

,GAME_ID,TEAM_ID,GAME_DATE,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,...,OPP_DREB,OPP_REB,OPP_AST,OPP_STL,OPP_BLK,OPP_TO,OPP_PF,OPP_PTS,OPP_PLUS_MINUS,OPP_MINUTES_PLAYED
0,0020000001,1610612752,2000-10-31,50.0,140.0,8.906,6.0,22.0,2.666,38.0,...,58.0,74.0,54.0,20.0,10.0,26.0,48.0,202.0,290.0,480.000000
1,0020000001,1610612755,2000-10-31,76.0,132.0,10.382,6.0,16.0,3.000,44.0,...,46.0,74.0,28.0,12.0,8.0,44.0,60.0,144.0,-290.0,480.000000
2,0020000002,1610612739,2000-10-31,64.0,156.0,6.796,4.0,14.0,3.000,40.0,...,70.0,94.0,48.0,18.0,16.0,24.0,62.0,164.0,-40.0,480.000000
3,0020000002,1610612751,2000-10-31,62.0,170.0,6.524,6.0,20.0,2.334,34.0,...,82.0,104.0,32.0,10.0,16.0,38.0,54.0,172.0,40.0,480.000000
4,0020000003,1610612753,2000-10-31,68.0,158.0,7.900,12.0,32.0,2.750,46.0,...,70.0,88.0,40.0,12.0,2.0,52.0,56.0,172.0,-110.0,480.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64141,0052300131,1610612758,2024-04-16,86.0,196.0,8.150,36.0,78.0,5.796,28.0,...,68.0,84.0,38.0,10.0,6.0,32.0,34.0,188.0,-240.0,480.000000
64142,0052300201,1610612741,2024-04-19,70.0,184.0,8.816,26.0,86.0,4.130,16.0,...,76.0,94.0,52.0,12.0,12.0,30.0,22.0,224.0,210.0,480.000000
64143,0052300201,1610612748,2024-04-19,76.0,164.0,9.182,28.0,66.0,7.888,44.0,...,62.0,76.0,54.0,24.0,12.0,24.0,38.0,182.0,-210.0,480.000000
64144,0052300211,1610612740,2024-04-19,88.0,170.0,8.708,14.0,38.0,6.072,20.0,...,52.0,80.0,42.0,18.0,8.0,30.0,34.0,196.0,-70.0,480.000000
64145,0052300211,1610612758,2024-04-19,72.0,176.0,5.026,22.0,82.0,2.938,30.0,...,68.0,90.0,58.0,18.0,16.0,30.0,38.0,210.0,70.0,480.066667

# 🏠 Ajout IS_HOME et IS_WIN

In [11]:


df_games['GAME_DATE'] = pd.to_datetime(df_games['GAME_DATE'])
match_dataset = match_dataset.merge(df_games[['GAME_ID', 'TEAM_ID', 'MATCHUP', 'SEASON']], on=['GAME_ID', 'TEAM_ID'], how='left')
match_dataset['IS_HOME'] = match_dataset['MATCHUP'].str.contains('vs').astype(int)
match_dataset['IS_WIN'] = (match_dataset['PTS'] > match_dataset['OPP_PTS']).astype(int)
match_dataset['POINT_DIFF'] = match_dataset['PTS'] - match_dataset['OPP_PTS']
match_dataset['GAME_DATE'] = pd.to_datetime(match_dataset['GAME_DATE'])
match_dataset = match_dataset.sort_values(['GAME_DATE', 'GAME_ID']).reset_index(drop=True)

In [12]:
match_dataset

,GAME_ID,TEAM_ID,GAME_DATE,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,...,OPP_TO,OPP_PF,OPP_PTS,OPP_PLUS_MINUS,OPP_MINUTES_PLAYED,MATCHUP,SEASON,IS_HOME,IS_WIN,POINT_DIFF
0,0020000001,1610612752,2000-10-31,50.0,140.0,8.906,6.0,22.0,2.666,38.0,...,26.0,48.0,202.0,290.0,480.0,NYK vs. PHI,2000-01,1,0,-58.0
1,0020000001,1610612755,2000-10-31,76.0,132.0,10.382,6.0,16.0,3.000,44.0,...,44.0,60.0,144.0,-290.0,480.0,PHI @ NYK,2000-01,0,1,58.0
2,0020000002,1610612739,2000-10-31,64.0,156.0,6.796,4.0,14.0,3.000,40.0,...,24.0,62.0,164.0,-40.0,480.0,CLE @ NJN,2000-01,0,1,8.0
3,0020000002,1610612751,2000-10-31,62.0,170.0,6.524,6.0,20.0,2.334,34.0,...,38.0,54.0,172.0,40.0,480.0,NJN vs. CLE,2000-01,1,0,-8.0
4,0020000003,1610612753,2000-10-31,68.0,158.0,7.900,12.0,32.0,2.750,46.0,...,52.0,56.0,172.0,-110.0,480.0,ORL vs. WAS,2000-01,1,1,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64141,0042400312,1610612760,2025-05-22,180.0,360.0,14.300,36.0,132.0,7.808,76.0,...,56.0,80.0,412.0,-300.0,0.0,OKC vs. MIN,2024-25,1,1,60.0
64142,0042400302,1610612752,2025-05-23,160.0,336.0,14.756,44.0,128.0,6.932,72.0,...,40.0,92.0,456.0,100.0,0.0,NYK vs. IND,2024-25,1,0,-20.0
64143,0042400302,1610612754,2025-05-23,172.0,332.0,17.144,52.0,120.0,13.936,60.0,...,48.0,76.0,436.0,-100.0,0.0,IND @ NYK,2024-25,0,1,20.0
64144,0042400313,1610612750,2025-05-24,220.0,384.0,32.280,80.0,160.0,25.432,52.0,...,56.0,80.0,404.0,-840.0,0.0,MIN vs. OKC,2024-25,1,1,168.0
64145,0042400313,1610612760,2025-05-24,140.0,344.0,23.300,56.0,176.0,17.864,68.0,...,40.0,72.0,572.0,840.0,0.0,OKC @ MIN,2024-25,0,0,-168.0

# 🚀 Features avancées

In [13]:
N_LIST = [3, 5, 10, 25, 50, 100, 200]

match_dataset = compute_rolling_features(match_dataset, "TEAM_ID", ["TEAM_ID", "GAME_DATE"],
                                         ['PTS', 'REB', 'AST', 'FGM', 'FGA', 'FG_PCT', 'PLUS_MINUS'], N_LIST)
match_dataset = compute_winrates(match_dataset, "TEAM_ID", "IS_WIN", "IS_HOME", N_LIST)
match_dataset = compute_win_ratio(match_dataset, "TEAM_ID", "IS_WIN", N_LIST)

match_dataset["IS_WIN_SHIFTED"] = match_dataset.groupby("TEAM_ID")["IS_WIN"].shift(1).fillna(0).astype(int)
match_dataset["WIN_STREAK"] = match_dataset.groupby("TEAM_ID").apply(
    lambda x: compute_win_streak(x, "TEAM_ID", "IS_WIN_SHIFTED")).reset_index(level=0, drop=True)
match_dataset = compute_side_win_streak(match_dataset)

match_dataset["DAYS_SINCE_LAST_GAME"] = compute_rest_days(match_dataset, "GAME_DATE", "TEAM_ID")
match_dataset["OPP_DAYS_SINCE_LAST_GAME"] = compute_rest_days(match_dataset, "GAME_DATE", "OPP_TEAM_ID")
match_dataset["REST_ADVANTAGE"] = match_dataset["DAYS_SINCE_LAST_GAME"] - match_dataset["OPP_DAYS_SINCE_LAST_GAME"]

match_dataset = compute_rolling_rest_advantage(match_dataset, "TEAM_ID", "IS_HOME", "REST_ADVANTAGE", N_LIST)
match_dataset = compute_home_away_pts(match_dataset, "TEAM_ID", "IS_HOME", "PTS", "OPP_PTS", N_LIST)
match_dataset = rename_pts_against_columns(match_dataset)

match_dataset = compute_h2h(match_dataset, N_LIST)
match_dataset = compute_h2h_pts_margin(match_dataset, N_LIST)
match_dataset = compute_h2h_season(match_dataset)
match_dataset = compute_h2h_streak(match_dataset)

match_dataset = compute_elo(match_dataset)
match_dataset = compute_elo_season(match_dataset)

In [14]:
pd.options.display.max_columns = None
display(match_dataset)

,GAME_ID,TEAM_ID,GAME_DATE,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS,MINUTES_PLAYED,OPP_TEAM_ID,OPP_GAME_DATE,OPP_FGM,OPP_FGA,OPP_FG_PCT,OPP_FG3M,OPP_FG3A,OPP_FG3_PCT,OPP_FTM,OPP_FTA,OPP_FT_PCT,OPP_OREB,OPP_DREB,OPP_REB,OPP_AST,OPP_STL,OPP_BLK,OPP_TO,OPP_PF,OPP_PTS,OPP_PLUS_MINUS,OPP_MINUTES_PLAYED,MATCHUP,SEASON,IS_HOME,IS_WIN,POINT_DIFF,ROLL_PTS_3,ROLL_PTS_5,ROLL_PTS_10,ROLL_PTS_25,ROLL_PTS_50,ROLL_PTS_100,ROLL_PTS_200,ROLL_REB_3,ROLL_REB_5,ROLL_REB_10,ROLL_REB_25,ROLL_REB_50,ROLL_REB_100,ROLL_REB_200,ROLL_AST_3,ROLL_AST_5,ROLL_AST_10,ROLL_AST_25,ROLL_AST_50,ROLL_AST_100,ROLL_AST_200,ROLL_FGM_3,ROLL_FGM_5,ROLL_FGM_10,ROLL_FGM_25,ROLL_FGM_50,ROLL_FGM_100,ROLL_FGM_200,ROLL_FGA_3,ROLL_FGA_5,ROLL_FGA_10,ROLL_FGA_25,ROLL_FGA_50,ROLL_FGA_100,ROLL_FGA_200,ROLL_FG_PCT_3,ROLL_FG_PCT_5,ROLL_FG_PCT_10,ROLL_FG_PCT_25,ROLL_FG_PCT_50,ROLL_FG_PCT_100,ROLL_FG_PCT_200,ROLL_PLUS_MINUS_3,ROLL_PLUS_MINUS_5,ROLL_PLUS_MINUS_10,ROLL_PLUS_MINUS_25,ROLL_PLUS_MINUS_50,ROLL_PLUS_MINUS_100,ROLL_PLUS_MINUS_200,ROLL_HOME_WINRATE_3,ROLL_AWAY_WINRATE_3,ROLL_HOME_WINRATE_5,ROLL_AWAY_WINRATE_5,ROLL_HOME_WINRATE_10,ROLL_AWAY_WINRATE_10,ROLL_HOME_WINRATE_25,ROLL_AWAY_WINRATE_25,ROLL_HOME_WINRATE_50,ROLL_AWAY_WINRATE_50,ROLL_HOME_WINRATE_100,ROLL_AWAY_WINRATE_100,ROLL_HOME_WINRATE_200,ROLL_AWAY_WINRATE_200,ROLL_WIN_RATIO_3,ROLL_WIN_RATIO_5,ROLL_WIN_RATIO_10,ROLL_WIN_RATIO_25,ROLL_WIN_RATIO_50,ROLL_WIN_RATIO_100,ROLL_WIN_RATIO_200,WIN_STREAK,HOME_WIN_STREAK,AWAY_WIN_STREAK,DAYS_SINCE_LAST_GAME,OPP_DAYS_SINCE_LAST_GAME,REST_ADVANTAGE,ROLL_HOME_REST_ADV_3,ROLL_AWAY_REST_ADV_3,ROLL_HOME_REST_ADV_5,ROLL_AWAY_REST_ADV_5,ROLL_HOME_REST_ADV_10,ROLL_AWAY_REST_ADV_10,ROLL_HOME_REST_ADV_25,ROLL_AWAY_REST_ADV_25,ROLL_HOME_REST_ADV_50,ROLL_AWAY_REST_ADV_50,ROLL_HOME_REST_ADV_100,ROLL_AWAY_REST_ADV_100,ROLL_HOME_REST_ADV_200,ROLL_AWAY_REST_ADV_200,ROLL_HOME_PTS_FOR_3,ROLL_HOME_OPP_PTS_AGAINST_3,ROLL_AWAY_PTS_FOR_3,ROLL_AWAY_OPP_PTS_AGAINST_3,ROLL_HOME_PTS_FOR_5,ROLL_HOME_OPP_PTS_AGAINST_5,ROLL_AWAY_PTS_FOR_5,ROLL_AWAY_OPP_PTS_AGAINST_5,ROLL_HOME_PTS_FOR_10,ROLL_HOME_OPP_PTS_AGAINST_10,ROLL_AWAY_PTS_FOR_10,ROLL_AWAY_OPP_PTS_AGAINST_10,ROLL_HOME_PTS_FOR_25,ROLL_HOME_OPP_PTS_AGAINST_25,ROLL_AWAY_PTS_FOR_25,ROLL_AWAY_OPP_PTS_AGAINST_25,ROLL_HOME_PTS_FOR_50,ROLL_HOME_OPP_PTS_AGAINST_50,ROLL_AWAY_PTS_FOR_50,ROLL_AWAY_OPP_PTS_AGAINST_50,ROLL_HOME_PTS_FOR_100,ROLL_HOME_OPP_PTS_AGAINST_100,ROLL_AWAY_PTS_FOR_100,ROLL_AWAY_OPP_PTS_AGAINST_100,ROLL_HOME_PTS_FOR_200,ROLL_HOME_OPP_PTS_AGAINST_200,ROLL_AWAY_PTS_FOR_200,ROLL_AWAY_OPP_PTS_AGAINST_200,ROLL_HOME_PTS_AGAINST_3,ROLL_AWAY_PTS_AGAINST_3,ROLL_HOME_PTS_AGAINST_5,ROLL_AWAY_PTS_AGAINST_5,ROLL_HOME_PTS_AGAINST_10,ROLL_AWAY_PTS_AGAINST_10,ROLL_HOME_PTS_AGAINST_25,ROLL_AWAY_PTS_AGAINST_25,ROLL_HOME_PTS_AGAINST_50,ROLL_AWAY_PTS_AGAINST_50,ROLL_HOME_PTS_AGAINST_100,ROLL_AWAY_PTS_AGAINST_100,ROLL_HOME_PTS_AGAINST_200,ROLL_AWAY_PTS_AGAINST_200,H2H_LAST_3_DIFF,H2H_LAST_3_WINRATE,H2H_LAST_3_COUNT,H2H_LAST_5_DIFF,H2H_LAST_5_WINRATE,H2H_LAST_5_COUNT,H2H_LAST_10_DIFF,H2H_LAST_10_WINRATE,H2H_LAST_10_COUNT,H2H_LAST_25_DIFF,H2H_LAST_25_WINRATE,H2H_LAST_25_COUNT,H2H_LAST_50_DIFF,H2H_LAST_50_WINRATE,H2H_LAST_50_COUNT,H2H_LAST_100_DIFF,H2H_LAST_100_WINRATE,H2H_LAST_100_COUNT,H2H_LAST_200_DIFF,H2H_LAST_200_WINRATE,H2H_LAST_200_COUNT,H2H_LAST_3_PTS_FOR,H2H_LAST_3_PTS_AGAINST,H2H_LAST_3_MARGIN,H2H_LAST_5_PTS_FOR,H2H_LAST_5_PTS_AGAINST,H2H_LAST_5_MARGIN,H2H_LAST_10_PTS_FOR,H2H_LAST_10_PTS_AGAINST,H2H_LAST_10_MARGIN,H2H_LAST_25_PTS_FOR,H2H_LAST_25_PTS_AGAINST,H2H_LAST_25_MARGIN,H2H_LAST_50_PTS_FOR,H2H_LAST_50_PTS_AGAINST,H2H_LAST_50_MARGIN,H2H_LAST_100_PTS_FOR,H2H_LAST_100_PTS_AGAINST,H2H_LAST_100_MARGIN,H2H_LAST_200_PTS_FOR,H2H_LAST_200_PTS_AGAINST,H2H_LAST_200_MARGIN,H2H_SEASON_WINS,H2H_SEASON_MATCHES,H2H_SEASON_WINRATE,H2H_WIN_STREAK,ELO_PRE,OPP_ELO_PRE,ELO_PRE_SEASON,OPP_ELO_PRE_SEASON
0,0020000001,1610612752,2000-10-31,50.0,140.0,8.906,6.0,22.0,2.666,38.0,48.0,8.214,28.0,46.0,74.0,28.0,12.0,8.0,44.0,60.0,144.0,-290.0,480.0,1610612755,2000-10-31,76.0,132.0,10.382,6.0,16.0,3.000,44.0,60.0,8.358,16.0,58.0,74.0,54.0,20.0,10.0,26.0,48.0,202.0,290.0,480.0,NYK vs. PHI,2000-01,1,0,-58.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,7.0,-8880.0,8887.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.500000,0,0,0.5,0,0,0.5,0,0,0.50,0,0,0.50,0,0,0.500000,0,0,0.500000,0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0.000000,0,1500.000000,1500.000000,1500.000000,1500.000000
1,0020000001,1610612755,2000-10-31,76.0,132.0,10.382,6.0,16.0,3.000,44.0,60.0,8.358,16.0,58.0,74.0,54.0,20.0,10.0,26.0,48.0,202.0,290.0,480.0,1610612752,2000-10-31,50.0,140.0,8.906,6.0,22.0,2.666,38.0,48.0,8.214,28.0,46.0,74.0,28.0,12.0,8.0,44.0,60.0,144.0,-290.0,480.0,PHI @ NYK,2000-01,0,1,58.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,7.0,-8970.0,8977.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.500000,0,0,0.5,0,0,0.5,0,0,0.50,0,0,0.50,0,0,0.500000,0,0,0.500000,0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0.000000,0,1500.000000,1500.000000,1500.000000,1500.000000
2,0020000002,1610612739,2000-10-31,64.0,156.0,6.796,4.0,14.0,3.000,40.0,64.0,9.500,22.0,82.0,104.0,32.0,10.0,16.0,38.0,54.0,172.0,40.0,480.0,1610612751,2000-10-31,62.0,170.0,6.524,6.0,20.0,2.334,34.0,52.0,12.500,24.0,70.0,94.0,48.0,18.0,16.0,24.0,62.0,164.0,-40.0,480.0,CLE @ NJN,2000-01,0,1,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,7.0,-8904.0,8911.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.500000,0,0,0.5,0,0,0.5,0,0,0.50,0,0,0.50,0,0,0.500000,0,0,0.500000,0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0.000000,0,1500.000000,1500.000000,1500.000000,1500.000000
3,0020000002,1610612751,2000-10-31,62.0,170.0,6.524,6.0,20.0,2.334,34.0,52.0,12.500,24.0,70.0,94.0,48.0,18.0,16.0,24.0,62.0,164.0,-40.0,480.0,1610612739,2000-10-31,64.0,156.0,6.796,4.0,14.0,3.000,40.0,64.0,9.500,22.0,82.0,104.0,32.0,10.0,16.0,38.0,54.0,172.0,40.0,480.0,NJN vs. CLE,2000-01,1,0,-8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,7.0,-8868.0,8875.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.500000,0,0,0.5,0,0,0.5,0,0,0.50,0,0,0.50,0,0,0.500000,0,0,0.500000,0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0.000000,0,1500.000000,1500.000000,1500.000000,1500.000000
4,0020000003,1610612753,2000-10-31,68.0,158.0,7.900,12.0,32.0,2.750,46.0,66.0,13.988,16.0,58.0,74.0,40.0,20.0,18.0,30.0,48.0,194.0,110.0,480.0,1610612764,2000-10-31,66.0,144.0,13.270,8.0,14.0,5.000,32.0,48.0,10.642,18.0,70.0,88.0,40.0,12.0,2.0,52.0,56.0,172.0,-110.0,480.0,ORL vs. WAS,2000-01,1,1,22.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,7.0,-8908.0,8915.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.500000,0,0,0.5,0,0,0.5,0,0,0.50,0,0,0.50,0,0,0.500000,0,0,0.500000,0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0.000000,0,1500.000000,1500.000000,1500.000000,1500.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64141,0042400312,1610612760,2025-05-22,180.0,360.0,14.300,36.0,132.0,7.808,76.0,96.0,8.800,36.0,132.0,168.0,120.0,36.0,12.0,24.0,88.0,472.0,300.0,0.0,1610612750,2025-05-22,144.0,348.0,12.476,44.0,156.0,7.776,80.0,104.0,19.468,52.0,112.0,164.0,80.0,8.0,28.0,56.0,80.0,412.0,-300.0,0.0,OKC vs. MIN,2024-25,1,1,60.0,306.666667,265.6,253.4,250.16,249.88,239.52,255.69,117.333333,109.6,98.2,94.32,93.40,90.10,92.98,71.333333,60.0,55.6,56.00,55.16,53.30,56.52,114.666667,97.6,91.2,91.44,91.52,88.50,94.26,234.666667,208.4,198.8,191.28,189.76,185.88,194.73,16.009333,12.8056,11.2432,10.49520,10.02396,9.72074,10.73602,240.000000,168.0,124.0,148.0,132.4,122.9,98.62,1.0,0.0,1.0,0.5,0.800000,0.600000,0.866667,0.700000,0.821429,0.772727,0.823529,0.755102,0.810000,0.650000,0.666667,0.8,0.7,0.80,0.80,0.79,0.730,2,2,1,2.0,2.0,0.0,-41.500000,0.0,-27.666667,0.000000,-26.000000,0.000000,-46.133333,-26.000000,-57.071429,-56.909091,-112.745098,-94.959184,-120.760000,-98.280000,353.000000,269.000000,214.0,238.0,310.0,249.333333,199.0,206.000000,293.2,240.4,213.6,216.800000,268.266667,222.266667,223.000000,218.000000,261.285714,222.785714,235.363636,224.181818,248.509804,216.117647,230.163265,213.714286,266.140000,236.520000,245.240000,235.340000,269.000000,238.0,249.333333,206.000000,240.4,216.800000,222.266667,218.000000,222.785714,224.181818,216.117647,213.714286,236.520000,235.340000,1,0.666667,3,1,0.6,5,0,0.5,10,-1,0.48,25,4,0.54,50,17,0.585859,99,17,0.585859,99,324.000000,286.666667,37.333333,280.0,260.4,19.6,266.6,258.6,8.0,242.08,244.40,-2.32,229.52,226.88,2.64,216.323232,214.141414,2.181818,216.323232,214.141414,2.181818,3,5,0.600000,1,1776.018986,1655.066745,1755.342687,1640.305738
64142,0042400302,1610612752,2025-05-23,160.0,336.0,14.756,44.0,128.0,6.932,72.0,84.0,20.000,40.0,112.0,152.0,72.0,24.0,16.0,48.0,76.0,436.0,-100.0,0.0,1610612754,2025-05-23,172.0,332.0,17.144,52.0,120.0,13.936,60.0,84.0,13.856,28.0,100.0,128.0,104.0,24.0,12.0,40.0,92.0,456.0,100.0,0.0,NYK vs. IND,2024-25,1,0,-20.0,327.333333,282.0,243.4,232.32,231.72,232.44,242.98,124.666667,109.2,99.6,89.20,86.96,86.56,94.97,60.000000,52.4,45.0,50.88,52.72,52.94,53.16,111.333333,99.6,87.4,85.84,86.84,86.42,89.40,240.000000,212.8,194.4,183.12,184.12,179.62,190.40,10.725333,10.0276,7.9334,8.27248,8.46376,8.43140,8.93332,23.333333,-14.0,-2.0,17.2,15.2,32.3,38.95,0.5,0.0,0.5,0.0,0.400000,0.800000,0.571429,0.636364,0.629630,0.608696,0.647059,0.591837,0.653465,0.555556,0.333333,0.4,0.6,0.60,0.62,0.62,0.605,0,0,3,2.0,2.0,0.0,-47.000000,0.0,-23.500000,0.000000,-18.800000,-4.600000,-44.142857,-33.636364,-89.185185,-74.608696,-95.784314,-110.979592,-92.742574,-117.636364,389.000000,357.000000,204.0,254.0,301.5,292.500000,204.0,254.000000,282.4,276.4,204.4,211.200000,247.142857,235.142857,213.454545,220.909091,243.407407,234.074074,218.000000,222.347826,240.039216,227.294118,224.530612,224.612245,246.435644,233.009901,239.454545,237.414141,357.000000,254.0,292.500000,254.000000,276.4,211.200000,235.142857,220.909091,234.074074,222.347826,227.294118,224.612245,233.009901,237.414141,-1,0.333333,3,-1,0.4,5,-2,0.4,10,1,0.52,25,-12,0.38,50,-22,0.390000,100,-21,0.398058,103,346.000000,348.666667,-2.666667,300.4,300.4,0.0,260.0,262.2,-2.2,239.04,242.24,-3.20,216.80,225.40,-8.60,205.900000,213.000000,-7.100000,204.757282,211.553398,-6.796117,2,4,0.500000,0,1626.543025,1676.707924,1619.085403,1672.606577
64143,0042400302,1610612754,2025-05-23,172.0,332.0,17.144,52.0,120.0,13.936,60.0,84.0,13.856,28.0,100.0,128.0,104.0,24.0,12.0,40.0,92.0,456.0,100.0,0.0,1610612752,2025-05-23,160.0,336.0,14.756,44.0,128.0,6.932,72.0,84.0,20.000,40.0,112.0,152.0,72.0,24.0,16.0,48.0,76.0,436.0,-100.0,0.0,IND @ NYK,2024-25,0,1,20.0,346.000000,297.2,267.2,243.44,239.84,234.84,257.36,108.000000,97.2,90.0,85.92,82.52,82.92,88.34,76.666667,67.6,64.2,59.36,60.28,58.60,63.91,128.000000,108.4,98.2,88.64,88.32,87.68,96.89,250.000000,216.0,195.8,177.68,178.92,177.30,193.86,13.010667,11.8580,10.6116,10.10912,9.82364,9.87584,10.87769,116.666667,28.0,42.0,72.0,49.2,26.2,22.00,1.0,1.0,0.5,1.0,0.750000,0.833333,0.800000,0.800000,0.807692,0.583333,0.714286,0.509804,0.663265,0.490196,1.000000,0.8,0.8,0.80,0.70,0.61,0.575,3,0,5,2.0,2.0,0.0,0.000000,-45.5,0.000000,-30.333333,0.000000,-18.333333,-42.800000,-65.500000,-71.307692,-97.041667,-73.775510,-128.294118,-95.826531,-116.245098,258.000000,218.000000,390.0,375.0,233.0,235.000000,340.0,329.333333,237.5,234.0,287.0,275.333333,220.266667,206.133333,278.200000,263.400000,229.769231,214.615385,250.750000,246.666667,231.306122,219.632653,238.235294,239.176471,266.142857,253.530612,248.921569,252.411765,218.000000,375.0,235.000000,329.333333,234.0,275.333333,206.133333,263.400000,214.615385,246.666667,219.632653,239.176471,253.530612,252.411765,1,0.666667,3,1,0.6,5,2,0.6,10,-1,0.48,25,12,0.62,50,22,0.610000,100,21,0.601942,103,348.666667,346.000000,2.666667,300.4,300.4,0.0,262.2,260.0,2.2,242.24,239.04,3.20,225.40,216.80,8.60,213.000000,205.900000,7.100000,211.553398,204.757282,6.796117,2,4,0.500000,1,1676.707924,1626.543025,1672.606577,1619.085403
64144,0042400313,1610612750,2025-05-24,220.0,384.0,32.280,80.0,160.0,25.432,52.0,68.0,18.000,44.0,156.0,200.0,120.0,24.0,12.0,40.0,72.0,572.0,840.0,0.0,1610612760,2025-05-24,140.0,344.0,23.300,56.0,176.0,17.864,68.0,76.0,23.332,20.0,104.0,124.0,76.0,20.0,12.0,56.0,80.0,404.0,-840.0,0.0,MIN vs. OKC,2024-25,1,1,168.0,335.333333,288.8,252.4,241.28,238.24,228.14,243.91,136.666667,114.8,101.6,94.48,91.32,89.10,94.54,74.666667,64.8,56.4,55.04,54.88,51.96,56.21,119.333333,101.6,90.0,87.36,85.56,81.86,88.16,278.666667,231.6,204.4,187.92,184.24,177.08,185.86,12.565333,10.5160,8.8000,9.47016,9.07856,8.80796,9.97337,-236.666667,-118.0,-24.0,43.6,50.6,34.7,52.35,1.0,0.0,1.0,0.5,0.800000,0.600000,0.750000,0.615385,0.680000,0.600000,0.571429,0.568627,0.642857,0.598039,0.333333,0.6,0.7,0.68,0.64,0.57,0.620,0,0,0,2.0,2.0,0.0,0.000000,-39.5,0.000000,-19.750000,-21.000000,-15.800000,-60.750000,-51.384615,-94.040000,-59.320000,-109.510204,-95.333333,-105.806122,-103.872549,242.000000,220.000000,382.0,464.0,242.0,220.000000,300.5,335.500000,223.2,207.6,281.6,306.800000,238.333333,214.833333,244.000000,248.923077,237.760000,217.600000,238.720000,238.640000,228.938776,216.489796,227.372549,225.725490,244.755102,228.979592,243.098039,237.725490,220.000000,464.0,220.000000,335.500000,207.6,306.800000,214.833333,248.923077,217.600000,238.640000,216.489796,225.725490,228.979592,237.725490,-1,0.333333,3,-1,0.4,5,-2,0.4,10,1,0.52,25,-4,0.46,50,-18,0.410000,100,-18,0.410000,100,342.000000,394.666667,-52.666667,300.8,329.2,-28.4,275.8,294.8,-19.0,250.80,250.40,0.40,230.68,233.88,-3.20,216.120000,218.880000,-2.760000,216.120000,218.880000,-2.760000,2,6,0.333333,0,1647.083323,1783.759474,1632.139876,1763.257237
64145,0042400313,1610612760,2025-05-24,140.0,344.0,23.300,56.0,176.0,17.864,68.0,76.0,23.332,20.0,104.0,124.0,76.0,20.0,12.0,56.0,80.0,404.0,-840.0,0.0,1610612750,2025-05-24,220.0,384.0,32.280,80.0,160.0,25.432,52.0,68.0,18.000,44.0,156.0,200.0,120.0,24.0,12.0,40.0,72.0,572.0,840.0,0.0,OKC @ MIN,2024-25,0,0,-168.0,392.666667,323.2,277.8,259.36,254.40,242.12,256.84,146.666667,121.2,106.4,97.04,95.20,90.84,93.31,94.666667,76.0,62.8,58.40,56.76,53.96,56.90,146.000000,121.2,101.4,94.96,93.36,89.50,94.71,293.333333,245.6,217.6,198.56,193.16,187.82,195.54,17.523333,14.2240,11.9028,10.67360,10.15880,9.76830,10.76621,380.000000,218.0,148.0,153.6,136.6,123.8,99.42,1.0,NaN,1.0,0.0,0.833333,0.500000,0.875000,0.666667,0.821429,0.772727,0.826923,0.750000,0.810000,0.650000,1.000000,0.8,0.7,0.80,0.80,0.79,0.730,3,2,2,2.0,2.0,0.0,-27.666667,NaN,-20.750000,0.000000,-21.666667,0.000000,-43.250000,-24.444444,-55.392857,-56.909091,-110.576923,-96.937500,-120.200000,-98.280000,392.666667,316.666667,NaN,NaN,350.5,290.000000,214.0,238.000000,323.0,269.0,210.0,217.000000,281.000000,234.125000,220.888889,218.888889,269.357143,229.357143,235.363636,224.181818,252.807692,219.884615,230.541667,214.625000,268.440000,238.500000,245.240000,235.340000,316.666667,NaN,290.000000,238.000000,269.0,217.000000,234.125000,218.888889,229.357143,224.181818,219.884615,214.625000,238.500000,235.340000,1,0.666667,3,1,0.6,5,2,0.6,10,-1,0.48,25,4,0.54,50,18,0.590000,100,18,0.590000,100,394.666667,342.000000,52.666667,329.2,300.8,28.4,294.8,275.8,19.0,250.40,250.80,-0.40,233.88,230.68,3.20,218.880000,216.120000,2.760000,218.880000,216.120000,2.760000,4,6,0.666667,2,1783.759474,1647.083323,1763.257237,1632.139876

# 🧽 Nettoyage et sauvegarde

In [15]:


final_date = datetime.datetime.now().strftime('%Y-%m-%d_%H-%M-%S')
raw_save_path = os.path.join(DATA_FINAL_DATASET_DIR, f'nba_features_final_{final_date}.csv')
clean_save_path = os.path.join(DATA_FINAL_CLEANED_DATASET_DIR, f'nba_features_cleaned_final_{final_date}.csv')

match_dataset.to_csv(raw_save_path, index=False)


# Liste des colonnes à dropper (toutes les stats brutes et colonnes de match, identifiants inutiles, etc.)
drop_cols = [
    # Identifiants et logs
    "GAME_ID", "OPP_GAME_DATE", "MATCHUP", #"OPP_TEAM_ID", "GAME_DATE",

    "IS_WIN_SHIFTED", 

    # Stats brutes de match (pour les deux équipes)
    "FGM", "FGA", "FG_PCT", "FG3M", "FG3A", "FG3_PCT", "FTM", "FTA", "FT_PCT",
    "OREB", "DREB", "REB", "AST", "STL", "BLK", "TO", "PF", "PTS", "PLUS_MINUS", "MINUTES_PLAYED",

    "OPP_FGM", "OPP_FGA", "OPP_FG_PCT", "OPP_FG3M", "OPP_FG3A", "OPP_FG3_PCT", "OPP_FTM", "OPP_FTA", "OPP_FT_PCT",
    "OPP_OREB", "OPP_DREB", "OPP_REB", "OPP_AST", "OPP_STL", "OPP_BLK", "OPP_TO", "OPP_PF", "OPP_PTS",
    "OPP_PLUS_MINUS", "OPP_MINUTES_PLAYED",
    "POINT_DIFF"
]

# Droppage effectif
final_dataset = match_dataset.drop(columns=[col for col in drop_cols if col in match_dataset.columns])


final_cleaned = match_dataset.drop(columns=drop_cols, errors='ignore')
final_cleaned.to_csv(clean_save_path, index=False)

print(f"✅ Fichier brut : {raw_save_path}")
print(f"✅ Fichier clean : {clean_save_path}")

✅ Fichier brut : data/final_dataset/nba_features_final_2025-05-25_16-22-56.csv
✅ Fichier clean : data/final_cleaned_dataset/nba_features_cleaned_final_2025-05-25_16-22-56.csv

In [16]:
final_cleaned

,TEAM_ID,GAME_DATE,OPP_TEAM_ID,SEASON,IS_HOME,IS_WIN,ROLL_PTS_3,ROLL_PTS_5,ROLL_PTS_10,ROLL_PTS_25,ROLL_PTS_50,ROLL_PTS_100,ROLL_PTS_200,ROLL_REB_3,ROLL_REB_5,ROLL_REB_10,ROLL_REB_25,ROLL_REB_50,ROLL_REB_100,ROLL_REB_200,ROLL_AST_3,ROLL_AST_5,ROLL_AST_10,ROLL_AST_25,ROLL_AST_50,ROLL_AST_100,ROLL_AST_200,ROLL_FGM_3,ROLL_FGM_5,ROLL_FGM_10,ROLL_FGM_25,ROLL_FGM_50,ROLL_FGM_100,ROLL_FGM_200,ROLL_FGA_3,ROLL_FGA_5,ROLL_FGA_10,ROLL_FGA_25,ROLL_FGA_50,ROLL_FGA_100,ROLL_FGA_200,ROLL_FG_PCT_3,ROLL_FG_PCT_5,ROLL_FG_PCT_10,ROLL_FG_PCT_25,ROLL_FG_PCT_50,ROLL_FG_PCT_100,ROLL_FG_PCT_200,ROLL_PLUS_MINUS_3,ROLL_PLUS_MINUS_5,ROLL_PLUS_MINUS_10,ROLL_PLUS_MINUS_25,ROLL_PLUS_MINUS_50,ROLL_PLUS_MINUS_100,ROLL_PLUS_MINUS_200,ROLL_HOME_WINRATE_3,ROLL_AWAY_WINRATE_3,ROLL_HOME_WINRATE_5,ROLL_AWAY_WINRATE_5,ROLL_HOME_WINRATE_10,ROLL_AWAY_WINRATE_10,ROLL_HOME_WINRATE_25,ROLL_AWAY_WINRATE_25,ROLL_HOME_WINRATE_50,ROLL_AWAY_WINRATE_50,ROLL_HOME_WINRATE_100,ROLL_AWAY_WINRATE_100,ROLL_HOME_WINRATE_200,ROLL_AWAY_WINRATE_200,ROLL_WIN_RATIO_3,ROLL_WIN_RATIO_5,ROLL_WIN_RATIO_10,ROLL_WIN_RATIO_25,ROLL_WIN_RATIO_50,ROLL_WIN_RATIO_100,ROLL_WIN_RATIO_200,WIN_STREAK,HOME_WIN_STREAK,AWAY_WIN_STREAK,DAYS_SINCE_LAST_GAME,OPP_DAYS_SINCE_LAST_GAME,REST_ADVANTAGE,ROLL_HOME_REST_ADV_3,ROLL_AWAY_REST_ADV_3,ROLL_HOME_REST_ADV_5,ROLL_AWAY_REST_ADV_5,ROLL_HOME_REST_ADV_10,ROLL_AWAY_REST_ADV_10,ROLL_HOME_REST_ADV_25,ROLL_AWAY_REST_ADV_25,ROLL_HOME_REST_ADV_50,ROLL_AWAY_REST_ADV_50,ROLL_HOME_REST_ADV_100,ROLL_AWAY_REST_ADV_100,ROLL_HOME_REST_ADV_200,ROLL_AWAY_REST_ADV_200,ROLL_HOME_PTS_FOR_3,ROLL_HOME_OPP_PTS_AGAINST_3,ROLL_AWAY_PTS_FOR_3,ROLL_AWAY_OPP_PTS_AGAINST_3,ROLL_HOME_PTS_FOR_5,ROLL_HOME_OPP_PTS_AGAINST_5,ROLL_AWAY_PTS_FOR_5,ROLL_AWAY_OPP_PTS_AGAINST_5,ROLL_HOME_PTS_FOR_10,ROLL_HOME_OPP_PTS_AGAINST_10,ROLL_AWAY_PTS_FOR_10,ROLL_AWAY_OPP_PTS_AGAINST_10,ROLL_HOME_PTS_FOR_25,ROLL_HOME_OPP_PTS_AGAINST_25,ROLL_AWAY_PTS_FOR_25,ROLL_AWAY_OPP_PTS_AGAINST_25,ROLL_HOME_PTS_FOR_50,ROLL_HOME_OPP_PTS_AGAINST_50,ROLL_AWAY_PTS_FOR_50,ROLL_AWAY_OPP_PTS_AGAINST_50,ROLL_HOME_PTS_FOR_100,ROLL_HOME_OPP_PTS_AGAINST_100,ROLL_AWAY_PTS_FOR_100,ROLL_AWAY_OPP_PTS_AGAINST_100,ROLL_HOME_PTS_FOR_200,ROLL_HOME_OPP_PTS_AGAINST_200,ROLL_AWAY_PTS_FOR_200,ROLL_AWAY_OPP_PTS_AGAINST_200,ROLL_HOME_PTS_AGAINST_3,ROLL_AWAY_PTS_AGAINST_3,ROLL_HOME_PTS_AGAINST_5,ROLL_AWAY_PTS_AGAINST_5,ROLL_HOME_PTS_AGAINST_10,ROLL_AWAY_PTS_AGAINST_10,ROLL_HOME_PTS_AGAINST_25,ROLL_AWAY_PTS_AGAINST_25,ROLL_HOME_PTS_AGAINST_50,ROLL_AWAY_PTS_AGAINST_50,ROLL_HOME_PTS_AGAINST_100,ROLL_AWAY_PTS_AGAINST_100,ROLL_HOME_PTS_AGAINST_200,ROLL_AWAY_PTS_AGAINST_200,H2H_LAST_3_DIFF,H2H_LAST_3_WINRATE,H2H_LAST_3_COUNT,H2H_LAST_5_DIFF,H2H_LAST_5_WINRATE,H2H_LAST_5_COUNT,H2H_LAST_10_DIFF,H2H_LAST_10_WINRATE,H2H_LAST_10_COUNT,H2H_LAST_25_DIFF,H2H_LAST_25_WINRATE,H2H_LAST_25_COUNT,H2H_LAST_50_DIFF,H2H_LAST_50_WINRATE,H2H_LAST_50_COUNT,H2H_LAST_100_DIFF,H2H_LAST_100_WINRATE,H2H_LAST_100_COUNT,H2H_LAST_200_DIFF,H2H_LAST_200_WINRATE,H2H_LAST_200_COUNT,H2H_LAST_3_PTS_FOR,H2H_LAST_3_PTS_AGAINST,H2H_LAST_3_MARGIN,H2H_LAST_5_PTS_FOR,H2H_LAST_5_PTS_AGAINST,H2H_LAST_5_MARGIN,H2H_LAST_10_PTS_FOR,H2H_LAST_10_PTS_AGAINST,H2H_LAST_10_MARGIN,H2H_LAST_25_PTS_FOR,H2H_LAST_25_PTS_AGAINST,H2H_LAST_25_MARGIN,H2H_LAST_50_PTS_FOR,H2H_LAST_50_PTS_AGAINST,H2H_LAST_50_MARGIN,H2H_LAST_100_PTS_FOR,H2H_LAST_100_PTS_AGAINST,H2H_LAST_100_MARGIN,H2H_LAST_200_PTS_FOR,H2H_LAST_200_PTS_AGAINST,H2H_LAST_200_MARGIN,H2H_SEASON_WINS,H2H_SEASON_MATCHES,H2H_SEASON_WINRATE,H2H_WIN_STREAK,ELO_PRE,OPP_ELO_PRE,ELO_PRE_SEASON,OPP_ELO_PRE_SEASON
0,1610612752,2000-10-31,1610612755,2000-01,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,7.0,-8880.0,8887.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.500000,0,0,0.5,0,0,0.5,0,0,0.50,0,0,0.50,0,0,0.500000,0,0,0.500000,0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0.000000,0,1500.000000,1500.000000,1500.000000,1500.000000
1,1610612755,2000-10-31,1610612752,2000-01,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,7.0,-8970.0,8977.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.500000,0,0,0.5,0,0,0.5,0,0,0.50,0,0,0.50,0,0,0.500000,0,0,0.500000,0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0.000000,0,1500.000000,1500.000000,1500.000000,1500.000000
2,1610612739,2000-10-31,1610612751,2000-01,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,7.0,-8904.0,8911.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.500000,0,0,0.5,0,0,0.5,0,0,0.50,0,0,0.50,0,0,0.500000,0,0,0.500000,0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0.000000,0,1500.000000,1500.000000,1500.000000,1500.000000
3,1610612751,2000-10-31,1610612739,2000-01,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,7.0,-8868.0,8875.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.500000,0,0,0.5,0,0,0.5,0,0,0.50,0,0,0.50,0,0,0.500000,0,0,0.500000,0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0.000000,0,1500.000000,1500.000000,1500.000000,1500.000000
4,1610612753,2000-10-31,1610612764,2000-01,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,7.0,-8908.0,8915.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.500000,0,0,0.5,0,0,0.5,0,0,0.50,0,0,0.50,0,0,0.500000,0,0,0.500000,0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0.000000,0,1500.000000,1500.000000,1500.000000,1500.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64141,1610612760,2025-05-22,1610612750,2024-25,1,1,306.666667,265.6,253.4,250.16,249.88,239.52,255.69,117.333333,109.6,98.2,94.32,93.40,90.10,92.98,71.333333,60.0,55.6,56.00,55.16,53.30,56.52,114.666667,97.6,91.2,91.44,91.52,88.50,94.26,234.666667,208.4,198.8,191.28,189.76,185.88,194.73,16.009333,12.8056,11.2432,10.49520,10.02396,9.72074,10.73602,240.000000,168.0,124.0,148.0,132.4,122.9,98.62,1.0,0.0,1.0,0.5,0.800000,0.600000,0.866667,0.700000,0.821429,0.772727,0.823529,0.755102,0.810000,0.650000,0.666667,0.8,0.7,0.80,0.80,0.79,0.730,2,2,1,2.0,2.0,0.0,-41.500000,0.0,-27.666667,0.000000,-26.000000,0.000000,-46.133333,-26.000000,-57.071429,-56.909091,-112.745098,-94.959184,-120.760000,-98.280000,353.000000,269.000000,214.0,238.0,310.0,249.333333,199.0,206.000000,293.2,240.4,213.6,216.800000,268.266667,222.266667,223.000000,218.000000,261.285714,222.785714,235.363636,224.181818,248.509804,216.117647,230.163265,213.714286,266.140000,236.520000,245.240000,235.340000,269.000000,238.0,249.333333,206.000000,240.4,216.800000,222.266667,218.000000,222.785714,224.181818,216.117647,213.714286,236.520000,235.340000,1,0.666667,3,1,0.6,5,0,0.5,10,-1,0.48,25,4,0.54,50,17,0.585859,99,17,0.585859,99,324.000000,286.666667,37.333333,280.0,260.4,19.6,266.6,258.6,8.0,242.08,244.40,-2.32,229.52,226.88,2.64,216.323232,214.141414,2.181818,216.323232,214.141414,2.181818,3,5,0.600000,1,1776.018986,1655.066745,1755.342687,1640.305738
64142,1610612752,2025-05-23,1610612754,2024-25,1,0,327.333333,282.0,243.4,232.32,231.72,232.44,242.98,124.666667,109.2,99.6,89.20,86.96,86.56,94.97,60.000000,52.4,45.0,50.88,52.72,52.94,53.16,111.333333,99.6,87.4,85.84,86.84,86.42,89.40,240.000000,212.8,194.4,183.12,184.12,179.62,190.40,10.725333,10.0276,7.9334,8.27248,8.46376,8.43140,8.93332,23.333333,-14.0,-2.0,17.2,15.2,32.3,38.95,0.5,0.0,0.5,0.0,0.400000,0.800000,0.571429,0.636364,0.629630,0.608696,0.647059,0.591837,0.653465,0.555556,0.333333,0.4,0.6,0.60,0.62,0.62,0.605,0,0,3,2.0,2.0,0.0,-47.000000,0.0,-23.500000,0.000000,-18.800000,-4.600000,-44.142857,-33.636364,-89.185185,-74.608696,-95.784314,-110.979592,-92.742574,-117.636364,389.000000,357.000000,204.0,254.0,301.5,292.500000,204.0,254.000000,282.4,276.4,204.4,211.200000,247.142857,235.142857,213.454545,220.909091,243.407407,234.074074,218.000000,222.347826,240.039216,227.294118,224.530612,224.612245,246.435644,233.009901,239.454545,237.414141,357.000000,254.0,292.500000,254.000000,276.4,211.200000,235.142857,220.909091,234.074074,222.347826,227.294118,224.612245,233.009901,237.414141,-1,0.333333,3,-1,0.4,5,-2,0.4,10,1,0.52,25,-12,0.38,50,-22,0.390000,100,-21,0.398058,103,346.000000,348.666667,-2.666667,300.4,300.4,0.0,260.0,262.2,-2.2,239.04,242.24,-3.20,216.80,225.40,-8.60,205.900000,213.000000,-7.100000,204.757282,211.553398,-6.796117,2,4,0.500000,0,1626.543025,1676.707924,1619.085403,1672.606577
64143,1610612754,2025-05-23,1610612752,2024-25,0,1,346.000000,297.2,267.2,243.44,239.84,234.84,257.36,108.000000,97.2,90.0,85.92,82.52,82.92,88.34,76.666667,67.6,64.2,59.36,60.28,58.60,63.91,128.000000,108.4,98.2,88.64,88.32,87.68,96.89,250.000000,216.0,195.8,177.68,178.92,177.30,193.86,13.010667,11.8580,10.6116,10.10912,9.82364,9.87584,10.87769,116.666667,28.0,42.0,72.0,49.2,26.2,22.00,1.0,1.0,0.5,1.0,0.750000,0.833333,0.800000,0.800000,0.807692,0.583333,0.714286,0.509804,0.663265,0.490196,1.000000,0.8,0.8,0.80,0.70,0.61,0.575,3,0,5,2.0,2.0,0.0,0.000000,-45.5,0.000000,-30.333333,0.000000,-18.333333,-42.800000,-65.500000,-71.307692,-97.041667,-73.775510,-128.294118,-95.826531,-116.245098,258.000000,218.000000,390.0,375.0,233.0,235.000000,340.0,329.333333,237.5,234.0,287.0,275.333333,220.266667,206.133333,278.200000,263.400000,229.769231,214.615385,250.750000,246.666667,231.306122,219.632653,238.235294,239.176471,266.142857,253.530612,248.921569,252.411765,218.000000,375.0,235.000000,329.333333,234.0,275.333333,206.133333,263.400000,214.615385,246.666667,219.632653,239.176471,253.530612,252.411765,1,0.666667,3,1,0.6,5,2,0.6,10,-1,0.48,25,12,0.62,50,22,0.610000,100,21,0.601942,103,348.666667,346.000000,2.666667,300.4,300.4,0.0,262.2,260.0,2.2,242.24,239.04,3.20,225.40,216.80,8.60,213.000000,205.900000,7.100000,211.553398,204.757282,6.796117,2,4,0.500000,1,1676.707924,1626.543025,1672.606577,1619.085403
64144,1610612750,2025-05-24,1610612760,2024-25,1,1,335.333333,288.8,252.4,241.28,238.24,228.14,243.91,136.666667,114.8,101.6,94.48,91.32,89.10,94.54,74.666667,64.8,56.4,55.04,54.88,51.96,56.21,119.333333,101.6,90.0,87.36,85.56,81.86,88.16,278.666667,231.6,204.4,187.92,184.24,177.08,185.86,12.565333,10.5160,8.8000,9.47016,9.07856,8.80796,9.97337,-236.666667,-118.0,-24.0,43.6,50.6,34.7,52.35,1.0,0.0,1.0,0.5,0.800000,0.600000,0.750000,0.615385,0.680000,0.600000,0.571429,0.568627,0.642857,0.598039,0.333333,0.6,0.7,0.68,0.64,0.57,0.620,0,0,0,2.0,2.0,0.0,0.000000,-39.5,0.000000,-19.750000,-21.000000,-15.800000,-60.750000,-51.384615,-94.040000,-59.320000,-109.510204,-95.333333,-105.806122,-103.872549,242.000000,220.000000,382.0,464.0,242.0,220.000000,300.5,335.500000,223.2,207.6,281.6,306.800000,238.333333,214.833333,244.000000,248.923077,237.760000,217.600000,238.720000,238.640000,228.938776,216.489796,227.372549,225.725490,244.755102,228.979592,243.098039,237.725490,220.000000,464.0,220.000000,335.500000,207.6,306.800000,214.833333,248.923077,217.600000,238.640000,216.489796,225.725490,228.979592,237.725490,-1,0.333333,3,-1,0.4,5,-2,0.4,10,1,0.52,25,-4,0.46,50,-18,0.410000,100,-18,0.410000,100,342.000000,394.666667,-52.666667,300.8,329.2,-28.4,275.8,294.8,-19.0,250.80,250.40,0.40,230.68,233.88,-3.20,216.120000,218.880000,-2.760000,216.120000,218.880000,-2.760000,2,6,0.333333,0,1647.083323,1783.759474,1632.139876,1763.257237
64145,1610612760,2025-05-24,1610612750,2024-25,0,0,392.666667,323.2,277.8,259.36,254.40,242.12,256.84,146.666667,121.2,106.4,97.04,95.20,90.84,93.31,94.666667,76.0,62.8,58.40,56.76,53.96,56.90,146.000000,121.2,101.4,94.96,93.36,89.50,94.71,293.333333,245.6,217.6,198.56,193.16,187.82,195.54,17.523333,14.2240,11.9028,10.67360,10.15880,9.76830,10.76621,380.000000,218.0,148.0,153.6,136.6,123.8,99.42,1.0,NaN,1.0,0.0,0.833333,0.500000,0.875000,0.666667,0.821429,0.772727,0.826923,0.750000,0.810000,0.650000,1.000000,0.8,0.7,0.80,0.80,0.79,0.730,3,2,2,2.0,2.0,0.0,-27.666667,NaN,-20.750000,0.000000,-21.666667,0.000000,-43.250000,-24.444444,-55.392857,-56.909091,-110.576923,-96.937500,-120.200000,-98.280000,392.666667,316.666667,NaN,NaN,350.5,290.000000,214.0,238.000000,323.0,269.0,210.0,217.000000,281.000000,234.125000,220.888889,218.888889,269.357143,229.357143,235.363636,224.181818,252.807692,219.884615,230.541667,214.625000,268.440000,238.500000,245.240000,235.340000,316.666667,NaN,290.000000,238.000000,269.0,217.000000,234.125000,218.888889,229.357143,224.181818,219.884615,214.625000,238.500000,235.340000,1,0.666667,3,1,0.6,5,2,0.6,10,-1,0.48,25,4,0.54,50,18,0.590000,100,18,0.590000,100,394.666667,342.000000,52.666667,329.2,300.8,28.4,294.8,275.8,19.0,250.40,250.80,-0.40,233.88,230.68,3.20,218.880000,216.120000,2.760000,218.880000,216.120000,2.760000,4,6,0.666667,2,1783.759474,1647.083323,1763.257237,1632.139876

In [17]:
#display full columns
pd.set_option('display.max_column', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_seq_items', None)
pd.set_option('display.max_colwidth', 500)
pd.set_option('expand_frame_repr', True)
# Display the final cleaned dataset
print("Final cleaned dataset:")
toto = final_cleaned.columns
print(toto)

Final cleaned dataset:
Index(['TEAM_ID', 'GAME_DATE', 'OPP_TEAM_ID', 'SEASON', 'IS_HOME', 'IS_WIN',
       'ROLL_PTS_3', 'ROLL_PTS_5', 'ROLL_PTS_10', 'ROLL_PTS_25', 'ROLL_PTS_50',
       'ROLL_PTS_100', 'ROLL_PTS_200', 'ROLL_REB_3', 'ROLL_REB_5',
       'ROLL_REB_10', 'ROLL_REB_25', 'ROLL_REB_50', 'ROLL_REB_100',
       'ROLL_REB_200', 'ROLL_AST_3', 'ROLL_AST_5', 'ROLL_AST_10',
       'ROLL_AST_25', 'ROLL_AST_50', 'ROLL_AST_100', 'ROLL_AST_200',
       'ROLL_FGM_3', 'ROLL_FGM_5', 'ROLL_FGM_10', 'ROLL_FGM_25', 'ROLL_FGM_50',
       'ROLL_FGM_100', 'ROLL_FGM_200', 'ROLL_FGA_3', 'ROLL_FGA_5',
       'ROLL_FGA_10', 'ROLL_FGA_25', 'ROLL_FGA_50', 'ROLL_FGA_100',
       'ROLL_FGA_200', 'ROLL_FG_PCT_3', 'ROLL_FG_PCT_5', 'ROLL_FG_PCT_10',
       'ROLL_FG_PCT_25', 'ROLL_FG_PCT_50', 'ROLL_FG_PCT_100',
       'ROLL_FG_PCT_200', 'ROLL_PLUS_MINUS_3', 'ROLL_PLUS_MINUS_5',
       'ROLL_PLUS_MINUS_10', 'ROLL_PLUS_MINUS_25', 'ROLL_PLUS_MINUS_50',
       'ROLL_PLUS_MINUS_100', 'ROLL_PLUS_MINUS_200', 'ROLL_HOME_WINRATE_3',
       'ROLL_AWAY_WINRATE_3', 'ROLL_HOME_WINRATE_5', 'ROLL_AWAY_WINRATE_5',
       'ROLL_HOME_WINRATE_10', 'ROLL_AWAY_WINRATE_10', 'ROLL_HOME_WINRATE_25',
       'ROLL_AWAY_WINRATE_25', 'ROLL_HOME_WINRATE_50', 'ROLL_AWAY_WINRATE_50',
       'ROLL_HOME_WINRATE_100', 'ROLL_AWAY_WINRATE_100',
       'ROLL_HOME_WINRATE_200', 'ROLL_AWAY_WINRATE_200', 'ROLL_WIN_RATIO_3',
       'ROLL_WIN_RATIO_5', 'ROLL_WIN_RATIO_10', 'ROLL_WIN_RATIO_25',
       'ROLL_WIN_RATIO_50', 'ROLL_WIN_RATIO_100', 'ROLL_WIN_RATIO_200',
       'WIN_STREAK', 'HOME_WIN_STREAK', 'AWAY_WIN_STREAK',
       'DAYS_SINCE_LAST_GAME', 'OPP_DAYS_SINCE_LAST_GAME', 'REST_ADVANTAGE',
       'ROLL_HOME_REST_ADV_3', 'ROLL_AWAY_REST_ADV_3', 'ROLL_HOME_REST_ADV_5',
       'ROLL_AWAY_REST_ADV_5', 'ROLL_HOME_REST_ADV_10',
       'ROLL_AWAY_REST_ADV_10', 'ROLL_HOME_REST_ADV_25',
       'ROLL_AWAY_REST_ADV_25', 'ROLL_HOME_REST_ADV_50',
       'ROLL_AWAY_REST_ADV_50', 'ROLL_HOME_REST_ADV_100',
       'ROLL_AWAY_REST_ADV_100', 'ROLL_HOME_REST_ADV_200',
       'ROLL_AWAY_REST_ADV_200', 'ROLL_HOME_PTS_FOR_3',
       'ROLL_HOME_OPP_PTS_AGAINST_3', 'ROLL_AWAY_PTS_FOR_3',
       'ROLL_AWAY_OPP_PTS_AGAINST_3', 'ROLL_HOME_PTS_FOR_5',
       'ROLL_HOME_OPP_PTS_AGAINST_5', 'ROLL_AWAY_PTS_FOR_5',
       'ROLL_AWAY_OPP_PTS_AGAINST_5', 'ROLL_HOME_PTS_FOR_10',
       'ROLL_HOME_OPP_PTS_AGAINST_10', 'ROLL_AWAY_PTS_FOR_10',
       'ROLL_AWAY_OPP_PTS_AGAINST_10', 'ROLL_HOME_PTS_FOR_25',
       'ROLL_HOME_OPP_PTS_AGAINST_25', 'ROLL_AWAY_PTS_FOR_25',
       'ROLL_AWAY_OPP_PTS_AGAINST_25', 'ROLL_HOME_PTS_FOR_50',
       'ROLL_HOME_OPP_PTS_AGAINST_50', 'ROLL_AWAY_PTS_FOR_50',
       'ROLL_AWAY_OPP_PTS_AGAINST_50', 'ROLL_HOME_PTS_FOR_100',
       'ROLL_HOME_OPP_PTS_AGAINST_100', 'ROLL_AWAY_PTS_FOR_100',
       'ROLL_AWAY_OPP_PTS_AGAINST_100', 'ROLL_HOME_PTS_FOR_200',
       'ROLL_HOME_OPP_PTS_AGAINST_200', 'ROLL_AWAY_PTS_FOR_200',
       'ROLL_AWAY_OPP_PTS_AGAINST_200', 'ROLL_HOME_PTS_AGAINST_3',
       'ROLL_AWAY_PTS_AGAINST_3', 'ROLL_HOME_PTS_AGAINST_5',
       'ROLL_AWAY_PTS_AGAINST_5', 'ROLL_HOME_PTS_AGAINST_10',
       'ROLL_AWAY_PTS_AGAINST_10', 'ROLL_HOME_PTS_AGAINST_25',
       'ROLL_AWAY_PTS_AGAINST_25', 'ROLL_HOME_PTS_AGAINST_50',
       'ROLL_AWAY_PTS_AGAINST_50', 'ROLL_HOME_PTS_AGAINST_100',
       'ROLL_AWAY_PTS_AGAINST_100', 'ROLL_HOME_PTS_AGAINST_200',
       'ROLL_AWAY_PTS_AGAINST_200', 'H2H_LAST_3_DIFF', 'H2H_LAST_3_WINRATE',
       'H2H_LAST_3_COUNT', 'H2H_LAST_5_DIFF', 'H2H_LAST_5_WINRATE',
       'H2H_LAST_5_COUNT', 'H2H_LAST_10_DIFF', 'H2H_LAST_10_WINRATE',
       'H2H_LAST_10_COUNT', 'H2H_LAST_25_DIFF', 'H2H_LAST_25_WINRATE',
       'H2H_LAST_25_COUNT', 'H2H_LAST_50_DIFF', 'H2H_LAST_50_WINRATE',
       'H2H_LAST_50_COUNT', 'H2H_LAST_100_DIFF', 'H2H_LAST_100_WINRATE',
       'H2H_LAST_100_COUNT', 'H2H_LAST_200_DIFF', 'H2H_LAST_200_WINRATE',
       'H2H_LAST_200_COUNT', 'H2H_LAST_3_PTS_FOR', 'H2H_LAST_3_PTS_AGAINST',
       'H2H_LAST_3_MARGIN', 'H2H_LAST_5_PTS_FOR', 'H2H_LAST_5_PTS_AGAINST',
       'H2H_LAST_5_MARGIN', 'H2H_LAST_10_PTS_FOR', 'H2H_LAST_10_PTS_AGAINST',
       'H2H_LAST_10_MARGIN', 'H2H_LAST_25_PTS_FOR', 'H2H_LAST_25_PTS_AGAINST',
       'H2H_LAST_25_MARGIN', 'H2H_LAST_50_PTS_FOR', 'H2H_LAST_50_PTS_AGAINST',
       'H2H_LAST_50_MARGIN', 'H2H_LAST_100_PTS_FOR',
       'H2H_LAST_100_PTS_AGAINST', 'H2H_LAST_100_MARGIN',
       'H2H_LAST_200_PTS_FOR', 'H2H_LAST_200_PTS_AGAINST',
       'H2H_LAST_200_MARGIN', 'H2H_SEASON_WINS', 'H2H_SEASON_MATCHES',
       'H2H_SEASON_WINRATE', 'H2H_WIN_STREAK', 'ELO_PRE', 'OPP_ELO_PRE',
       'ELO_PRE_SEASON', 'OPP_ELO_PRE_SEASON'],
      dtype='object')

In [18]:
#store end time of notebook
end_time = datetime.datetime.now()
print("End time: ", end_time)
print("Total time: ", end_time - start_time)

End time:  2025-05-25 16:23:21.368346
Total time:  0:02:12.224564