# Nettoyage & enrichissement des boxscores (minutes, DNP, totaux, ratios)

In [16]:
import pandas as pd
import numpy as np
import os
from datetime import datetime
from nba_api.stats.static import players

from src.config import *
from src.utils import *
from src.feature_builder import *
from src.feature_aggregation import *

#display full columns
pd.set_option('display.max_column', None)
# pd.set_option('display.max_rows', None)
# pd.set_option('display.max_seq_items', None)
# pd.set_option('display.max_colwidth', 500)
# pd.set_option('expand_frame_repr', True)

In [17]:
#store start time of notebook
start_time = datetime.now()
print("Start time: ", start_time)

Start time:  2025-06-13 00:11:46.520878

# 🔁 Chargement des fichiers

In [18]:
boxscores_file = get_latest_file(DATA_LAST_BOXSCORES_BATCHES_MERGED_DIR)
games_file = get_latest_file(DATA_LAST_GAMES_MERGED_DIR)
df_boxscores = pd.read_csv(boxscores_file, dtype={'gameId': str})
df_games = pd.read_csv(games_file, dtype={'GAME_ID': str})

In [19]:
games_file

'data\\raw_last\\games_merged\\games_merged_all_seasons_2025-06-13_00-03-39.csv'

In [20]:
df_boxscores

,gameId,teamId,teamCity,teamName,teamTricode,teamSlug,personId,firstName,familyName,nameI,playerSlug,position,comment,jerseyNum,minutes,offensiveRating_advanced,defensiveRating_advanced,estimatedNetRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,oppPointsOffTurnovers_misc,oppPointsSecondChance_misc,oppPointsFastBreak_misc,oppPointsPaint_misc,blocksAgainst_misc,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,threePointersPercentage_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,freeThrowsPercentage_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,points_traditional,plusMinusPoints_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage
0,0029900011,1610612747,Los Angeles,Lakers,LAL,lakers,779,Glen,Rice,G. Rice,glen-rice,F,NaN,NaN,40:11,102.6,88.2,15.5,14.5,0.150,0.75,13.0,0.026,0.143,0.081,17.4,0.808,0.871,0.225,89.63,90.80,76.0,0.224,0.500,0.349,0.201,0.440,0.328,0.226,0.258,2,5,10,0,14,14,9,28,1,1,0.538,0.462,0.214,0.214,0.536,0.357,0.250,0.071,0.000,1.000,0.000,1.0,0.0,1.000,0.000,8,13,5,6,0.833,7,7,1.000,1,5,6,3,2,0,4,5,28,11.0,0.286,0.206,0.714,0.545,0.467,0.318,0.077,0.217,0.167,0.143,0.267,0.222,0.00,0.200,0.263,0.045,0.359
1,0029900011,1610612747,Los Angeles,Lakers,LAL,lakers,920,A.C.,Green,A. Green,ac-green,F,NaN,NaN,32:55,111.5,96.7,18.1,14.8,0.087,0.00,28.6,0.100,0.130,0.113,0.0,0.200,0.200,0.068,87.15,88.96,61.0,0.027,0.519,0.346,0.187,0.558,0.349,0.264,0.238,0,0,0,0,13,8,7,24,0,1,1.000,0.000,1.000,1.000,0.000,0.000,0.000,0.000,0.000,1.000,0.000,0.0,0.0,1.000,0.000,1,5,0,0,0.000,0,0,0.000,3,3,6,2,1,0,0,3,2,9.0,0.042,0.096,0.000,0.000,0.000,0.000,0.250,0.188,0.214,0.133,0.000,0.143,0.00,0.000,0.176,0.048,0.029
2,0029900011,1610612747,Los Angeles,Lakers,LAL,lakers,406,Shaquille,O'Neal,S. O'Neal,shaquille-oneal,C,NaN,NaN,34:26,120.3,96.8,26.0,23.5,0.050,0.50,3.6,0.147,0.258,0.200,7.1,0.450,0.463,0.355,89.58,88.52,64.0,0.118,0.559,0.305,0.141,0.462,0.283,0.186,0.269,3,4,0,16,8,14,9,24,2,0,1.000,0.000,0.783,0.087,0.000,0.000,0.217,0.130,0.696,0.556,0.444,0.0,0.0,0.556,0.444,9,20,0,0,0.000,5,11,0.455,5,8,13,1,1,2,2,4,23,16.0,0.310,0.339,0.000,0.000,0.455,0.611,0.417,0.421,0.419,0.050,0.222,0.167,0.40,0.500,0.235,0.000,0.299
3,0029900011,1610612747,Los Angeles,Lakers,LAL,lakers,965,Derek,Fisher,D. Fisher,derek-fisher,G,NaN,NaN,39:32,106.8,89.0,19.1,17.8,0.304,3.50,35.0,0.000,0.094,0.043,10.0,0.545,0.545,0.151,87.52,88.63,73.0,0.094,0.508,0.355,0.181,0.464,0.309,0.235,0.250,6,0,2,2,12,12,9,28,1,2,0.636,0.364,0.500,0.333,0.500,0.167,0.000,0.500,0.167,0.667,0.333,1.0,0.0,0.800,0.200,5,11,2,4,0.500,0,0,0.000,0,3,3,7,1,0,2,5,12,13.0,0.179,0.177,0.286,0.400,0.000,0.000,0.000,0.143,0.088,0.350,0.154,0.125,0.00,0.200,0.263,0.087,0.154
4,0029900011,1610612747,Los Angeles,Lakers,LAL,lakers,166,Ron,Harper,R. Harper,ron-harper,G,NaN,NaN,37:48,105.8,88.7,16.6,17.1,0.167,1.33,20.0,0.114,0.094,0.104,15.0,0.273,0.353,0.195,86.68,88.89,69.0,0.061,0.517,0.250,0.207,0.462,0.346,0.218,0.200,3,0,0,4,12,10,9,24,1,0,1.000,0.000,0.667,0.222,0.000,0.000,0.333,0.333,0.444,0.333,0.667,0.0,0.0,0.333,0.667,3,11,0,0,0.000,3,4,0.750,4,3,7,4,2,1,3,2,9,10.0,0.111,0.183,0.000,0.000,0.273,0.267,0.308,0.125,0.189,0.222,0.214,0.286,0.25,0.167,0.111,0.000,0.123
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2512865,0042400403,1610612754,Indiana,Pacers,IND,pacers,1628396,Tony,Bradley,T. Bradley,tony-bradley,NaN,DNP - Coach's Decision,NaN,NaN,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.00,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0,0,0,0,0,0,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0,0,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,0.000
2512866,0042400403,1610612754,Indiana,Pacers,IND,pacers,1642277,Johnny,Furphy,J. Furphy,johnny-furphy,NaN,DNP - Coach's Decision,NaN,NaN,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.00,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0,0,0,0,0,0,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0,0,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,0.000
2512867,0042400403,1610612754,Indiana,Pacers,IND,pacers,1630543,Isaiah,Jackson,I. Jackson,isaiah-jackson,NaN,DND - Injury/Illness,NaN,NaN,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.00,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0,0,0,0,0,0,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0,0,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,0.000
2512868,0042400403,1610612754,Indiana,Pacers,IND,pacers,201949,James,Johnson,J. Johnson,james-johnson,NaN,DNP - Coach's Decision,NaN,NaN,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.00,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0,0,0,0,0,0,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0,0,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,0.000
2512869,0042400403,1610612754,Indiana,Pacers,IND,pacers,1641716,Jarace,Walker,J. Walker,jarace-walker,NaN,DND - Injury/Illness,NaN,NaN,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.00,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0,0,0,0,0,0,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0,0,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,0.000

In [21]:
df_games

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS,SEASON
0,21995,1610612742,DAL,Dallas Mavericks,0029500011,1995-11-03,DAL @ SAN,W,240,103,42,89,0.472,4,12,0.333,15,23,0.652,15,34,49,16,7,7,17,30,NaN,1995-96
1,21995,1610612737,ATL,Atlanta Hawks,0029500002,1995-11-03,ATL vs. IND,L,240,106,35,73,0.479,6,14,0.429,30,47,0.638,14,13,27,21,12,4,12,32,NaN,1995-96
2,21995,1610612758,SAC,Sacramento Kings,0029500009,1995-11-03,SAC vs. MIN,W,240,95,33,67,0.493,7,13,0.538,22,33,0.667,6,31,37,21,12,6,21,26,NaN,1995-96
3,21995,1610612739,CLE,Cleveland Cavaliers,0029500010,1995-11-03,CLE @ ORL,L,240,88,30,63,0.476,9,16,0.563,19,33,0.576,6,25,31,20,9,4,10,21,NaN,1995-96
4,21995,1610612757,POR,Portland Trail Blazers,0029500007,1995-11-03,POR vs. VAN,L,240,80,29,81,0.358,5,22,0.227,17,30,0.567,23,28,51,20,11,3,26,25,NaN,1995-96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86077,42024,1610612754,IND,Indiana Pacers,0042400401,2025-06-05,IND @ OKC,W,240,111,39,82,0.476,18,39,0.462,15,21,0.714,13,43,56,24,1,7,24,22,1.0,2024-25
86078,42024,1610612760,OKC,Oklahoma City Thunder,0042400402,2025-06-08,OKC vs. IND,W,240,123,40,82,0.488,14,36,0.389,29,33,0.879,11,32,43,25,10,4,13,20,16.0,2024-25
86079,42024,1610612754,IND,Indiana Pacers,0042400402,2025-06-08,IND @ OKC,L,241,107,37,82,0.451,14,40,0.350,19,26,0.731,7,28,35,27,9,6,15,25,-16.0,2024-25
86080,42024,1610612760,OKC,Oklahoma City Thunder,0042400403,2025-06-11,OKC @ IND,L,239,107,37,79,0.468,10,22,0.455,23,30,0.767,9,33,42,16,6,4,17,20,-9.0,2024-25
86081,42024,1610612754,IND,Indiana Pacers,0042400403,2025-06-11,IND vs. OKC,W,239,116,44,85,0.518,9,27,0.333,19,22,0.864,7,29,36,24,13,11,13,24,9.0,2024-25

# 🧼 Nettoyage des minutes jouées

In [22]:
def convert_minutes(val):
    if pd.isna(val) or val in ['DNP', '']:
        return 0.0
    try:
        parts = str(val).split(':')
        return int(parts[0]) + int(parts[1]) / 60 if len(parts) == 2 else float(val)
    except:
        return 0.0

df_boxscores['MINUTES_PLAYED'] = df_boxscores['minutes'].apply(convert_minutes)

# Rename gameId and teamId in boxscores

In [23]:
rename_columns = {
    'gameId': 'GAME_ID',
    'teamId': 'TEAM_ID',
}

df_boxscores.rename(columns=rename_columns, inplace=True)

In [24]:
# cast 'GAME_ID', 'TEAM_ID' to string
df_games['GAME_ID'] = df_games['GAME_ID'].astype(str)
df_games['TEAM_ID'] = df_games['TEAM_ID'].astype(str)

df_boxscores['GAME_ID'] = df_boxscores['GAME_ID'].astype(str)
df_boxscores['TEAM_ID'] = df_boxscores['TEAM_ID'].astype(str)

In [25]:
print(df_games.dtypes)

SEASON_ID              int64
TEAM_ID               object
TEAM_ABBREVIATION     object
TEAM_NAME             object
GAME_ID               object
GAME_DATE             object
MATCHUP               object
WL                    object
MIN                    int64
PTS                    int64
FGM                    int64
FGA                    int64
FG_PCT               float64
FG3M                   int64
FG3A                   int64
FG3_PCT              float64
FTM                    int64
FTA                    int64
FT_PCT               float64
OREB                   int64
DREB                   int64
REB                    int64
AST                    int64
STL                    int64
BLK                    int64
TOV                    int64
PF                     int64
PLUS_MINUS           float64
SEASON                object
dtype: object

In [26]:
print(df_boxscores.dtypes)

GAME_ID                                object
TEAM_ID                                object
teamCity                               object
teamName                               object
teamTricode                            object
                                       ...
percentageBlocksAllowed_usage         float64
percentagePersonalFouls_usage         float64
percentagePersonalFoulsDrawn_usage    float64
percentagePoints_usage                float64
MINUTES_PLAYED                        float64
Length: 101, dtype: object

# Merge GAME_DATE dans les boxscores et remove les duplicates créés

In [28]:
df_games['GAME_DATE'] = pd.to_datetime(df_games['GAME_DATE'])
df_boxscores = df_boxscores.merge(
    df_games[['GAME_ID', 'TEAM_ID', 'GAME_DATE']],
    on=['GAME_ID', 'TEAM_ID'],
    how='left'
)

df_boxscores = df_boxscores.drop_duplicates(subset=['GAME_ID', 'TEAM_ID', 'playerSlug'])

In [29]:
# display nat GAME_DATE in df_boxscores
# check for NaT values in GAME_DATE
nat_dates = df_boxscores[df_boxscores['GAME_DATE'].isna()]
nat_dates

Empty DataFrame
Columns: [GAME_ID, TEAM_ID, teamCity, teamName, teamTricode, teamSlug, personId, firstName, familyName, nameI, playerSlug, position, comment, jerseyNum, minutes, offensiveRating_advanced, defensiveRating_advanced, estimatedNetRating_advanced, netRating_advanced, assistPercentage_advanced, assistToTurnover_advanced, assistRatio_advanced, offensiveReboundPercentage_advanced, defensiveReboundPercentage_advanced, reboundPercentage_advanced, turnoverRatio_advanced, effectiveFieldGoalPercentage_advanced, trueShootingPercentage_advanced, usagePercentage_advanced, estimatedPace_advanced, pace_advanced, possessions_advanced, PIE_advanced, effectiveFieldGoalPercentage_fourfactors, freeThrowAttemptRate_fourfactors, teamTurnoverPercentage_fourfactors, oppEffectiveFieldGoalPercentage_fourfactors, oppFreeThrowAttemptRate_fourfactors, oppTeamTurnoverPercentage_fourfactors, oppOffensiveReboundPercentage_fourfactors, pointsOffTurnovers_misc, pointsSecondChance_misc, pointsFastBreak_misc, pointsPaint_misc, oppPointsOffTurnovers_misc, oppPointsSecondChance_misc, oppPointsFastBreak_misc, oppPointsPaint_misc, blocksAgainst_misc, foulsDrawn_misc, percentageFieldGoalsAttempted2pt_scoring, percentageFieldGoalsAttempted3pt_scoring, percentagePoints2pt_scoring, percentagePointsMidrange2pt_scoring, percentagePoints3pt_scoring, percentagePointsFastBreak_scoring, percentagePointsFreeThrow_scoring, percentagePointsOffTurnovers_scoring, percentagePointsPaint_scoring, percentageAssisted2pt_scoring, percentageUnassisted2pt_scoring, percentageAssisted3pt_scoring, percentageUnassisted3pt_scoring, percentageAssistedFGM_scoring, percentageUnassistedFGM_scoring, fieldGoalsMade_traditional, fieldGoalsAttempted_traditional, threePointersMade_traditional, threePointersAttempted_traditional, threePointersPercentage_traditional, freeThrowsMade_traditional, freeThrowsAttempted_traditional, freeThrowsPercentage_traditional, reboundsOffensive_traditional, reboundsDefensive_traditional, reboundsTotal_traditional, assists_traditional, steals_traditional, blocks_traditional, turnovers_traditional, foulsPersonal_traditional, points_traditional, plusMinusPoints_traditional, percentageFieldGoalsMade_usage, percentageFieldGoalsAttempted_usage, percentageThreePointersMade_usage, percentageThreePointersAttempted_usage, percentageFreeThrowsMade_usage, percentageFreeThrowsAttempted_usage, percentageReboundsOffensive_usage, percentageReboundsDefensive_usage, percentageReboundsTotal_usage, percentageAssists_usage, percentageTurnovers_usage, percentageSteals_usage, percentageBlocks_usage, percentageBlocksAllowed_usage, percentagePersonalFouls_usage, percentagePersonalFoulsDrawn_usage, percentagePoints_usage, ...]
Index: []

In [30]:
missing = df_boxscores[df_boxscores['GAME_DATE'].isna()][['GAME_ID', 'TEAM_ID']].drop_duplicates()

print(f"Exemples de lignes avec GAME_DATE NaT:")
print(missing.head(10))

# On regarde s’ils existent dans df_games
merged_check = missing.merge(df_games[['GAME_ID', 'TEAM_ID']], on=['GAME_ID', 'TEAM_ID'], how='left', indicator=True)
print(merged_check['_merge'].value_counts())

Exemples de lignes avec GAME_DATE NaT:
Empty DataFrame
Columns: [GAME_ID, TEAM_ID]
Index: []
_merge
left_only     0
right_only    0
both          0
Name: count, dtype: int64

In [31]:
print("Exemples d’ID manquants dans df_games")
print(missing[~missing.set_index(['GAME_ID', 'TEAM_ID']).index.isin(df_games.set_index(['GAME_ID', 'TEAM_ID']).index)])

Exemples d’ID manquants dans df_games
Empty DataFrame
Columns: [GAME_ID, TEAM_ID]
Index: []

# 🔄 Cast dynamique des colonnes numériques

In [32]:
numeric_cols = df_boxscores.select_dtypes(include=[np.number]).columns.tolist()
for col in numeric_cols:
    df_boxscores[col] = pd.to_numeric(df_boxscores[col], errors='coerce').fillna(0)

In [33]:
df_boxscores

,GAME_ID,TEAM_ID,teamCity,teamName,teamTricode,teamSlug,personId,firstName,familyName,nameI,playerSlug,position,comment,jerseyNum,minutes,offensiveRating_advanced,defensiveRating_advanced,estimatedNetRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,oppPointsOffTurnovers_misc,oppPointsSecondChance_misc,oppPointsFastBreak_misc,oppPointsPaint_misc,blocksAgainst_misc,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,threePointersPercentage_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,freeThrowsPercentage_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,points_traditional,plusMinusPoints_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage,MINUTES_PLAYED,GAME_DATE
0,0029900011,1610612747,Los Angeles,Lakers,LAL,lakers,779,Glen,Rice,G. Rice,glen-rice,F,NaN,0.0,40:11,102.6,88.2,15.5,14.5,0.150,0.75,13.0,0.026,0.143,0.081,17.4,0.808,0.871,0.225,89.63,90.80,76.0,0.224,0.500,0.349,0.201,0.440,0.328,0.226,0.258,2,5,10,0,14,14,9,28,1,1,0.538,0.462,0.214,0.214,0.536,0.357,0.250,0.071,0.000,1.000,0.000,1.0,0.0,1.000,0.000,8,13,5,6,0.833,7,7,1.000,1,5,6,3,2,0,4,5,28,11.0,0.286,0.206,0.714,0.545,0.467,0.318,0.077,0.217,0.167,0.143,0.267,0.222,0.00,0.200,0.263,0.045,0.359,40.183333,1999-11-02
1,0029900011,1610612747,Los Angeles,Lakers,LAL,lakers,920,A.C.,Green,A. Green,ac-green,F,NaN,0.0,32:55,111.5,96.7,18.1,14.8,0.087,0.00,28.6,0.100,0.130,0.113,0.0,0.200,0.200,0.068,87.15,88.96,61.0,0.027,0.519,0.346,0.187,0.558,0.349,0.264,0.238,0,0,0,0,13,8,7,24,0,1,1.000,0.000,1.000,1.000,0.000,0.000,0.000,0.000,0.000,1.000,0.000,0.0,0.0,1.000,0.000,1,5,0,0,0.000,0,0,0.000,3,3,6,2,1,0,0,3,2,9.0,0.042,0.096,0.000,0.000,0.000,0.000,0.250,0.188,0.214,0.133,0.000,0.143,0.00,0.000,0.176,0.048,0.029,32.916667,1999-11-02
2,0029900011,1610612747,Los Angeles,Lakers,LAL,lakers,406,Shaquille,O'Neal,S. O'Neal,shaquille-oneal,C,NaN,0.0,34:26,120.3,96.8,26.0,23.5,0.050,0.50,3.6,0.147,0.258,0.200,7.1,0.450,0.463,0.355,89.58,88.52,64.0,0.118,0.559,0.305,0.141,0.462,0.283,0.186,0.269,3,4,0,16,8,14,9,24,2,0,1.000,0.000,0.783,0.087,0.000,0.000,0.217,0.130,0.696,0.556,0.444,0.0,0.0,0.556,0.444,9,20,0,0,0.000,5,11,0.455,5,8,13,1,1,2,2,4,23,16.0,0.310,0.339,0.000,0.000,0.455,0.611,0.417,0.421,0.419,0.050,0.222,0.167,0.40,0.500,0.235,0.000,0.299,34.433333,1999-11-02
3,0029900011,1610612747,Los Angeles,Lakers,LAL,lakers,965,Derek,Fisher,D. Fisher,derek-fisher,G,NaN,0.0,39:32,106.8,89.0,19.1,17.8,0.304,3.50,35.0,0.000,0.094,0.043,10.0,0.545,0.545,0.151,87.52,88.63,73.0,0.094,0.508,0.355,0.181,0.464,0.309,0.235,0.250,6,0,2,2,12,12,9,28,1,2,0.636,0.364,0.500,0.333,0.500,0.167,0.000,0.500,0.167,0.667,0.333,1.0,0.0,0.800,0.200,5,11,2,4,0.500,0,0,0.000,0,3,3,7,1,0,2,5,12,13.0,0.179,0.177,0.286,0.400,0.000,0.000,0.000,0.143,0.088,0.350,0.154,0.125,0.00,0.200,0.263,0.087,0.154,39.533333,1999-11-02
4,0029900011,1610612747,Los Angeles,Lakers,LAL,lakers,166,Ron,Harper,R. Harper,ron-harper,G,NaN,0.0,37:48,105.8,88.7,16.6,17.1,0.167,1.33,20.0,0.114,0.094,0.104,15.0,0.273,0.353,0.195,86.68,88.89,69.0,0.061,0.517,0.250,0.207,0.462,0.346,0.218,0.200,3,0,0,4,12,10,9,24,1,0,1.000,0.000,0.667,0.222,0.000,0.000,0.333,0.333,0.444,0.333,0.667,0.0,0.0,0.333,0.667,3,11,0,0,0.000,3,4,0.750,4,3,7,4,2,1,3,2,9,10.0,0.111,0.183,0.000,0.000,0.273,0.267,0.308,0.125,0.189,0.222,0.214,0.286,0.25,0.167,0.111,0.000,0.123,37.800000,1999-11-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3035625,0042400403,1610612754,Indiana,Pacers,IND,pacers,1628396,Tony,Bradley,T. Bradley,tony-bradley,NaN,DNP - Coach's Decision,0.0,NaN,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.00,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0,0,0,0,0,0,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0,0,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000000,2025-06-11
3035626,0042400403,1610612754,Indiana,Pacers,IND,pacers,1642277,Johnny,Furphy,J. Furphy,johnny-furphy,NaN,DNP - Coach's Decision,0.0,NaN,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.00,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0,0,0,0,0,0,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0,0,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000000,2025-06-11
3035627,0042400403,1610612754,Indiana,Pacers,IND,pacers,1630543,Isaiah,Jackson,I. Jackson,isaiah-jackson,NaN,DND - Injury/Illness,0.0,NaN,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.00,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0,0,0,0,0,0,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0,0,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000000,2025-06-11
3035628,0042400403,1610612754,Indiana,Pacers,IND,pacers,201949,James,Johnson,J. Johnson,james-johnson,NaN,DNP - Coach's Decision,0.0,NaN,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.00,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0,0,0,0,0,0,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0,0,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000000,2025-06-11
3035629,0042400403,1610612754,Indiana,Pacers,IND,pacers,1641716,Jarace,Walker,J. Walker,jarace-walker,NaN,DND - Injury/Illness,0.0,NaN,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.00,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0,0,0,0,0,0,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0,0,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000000,2025-06-11

# Build player features (players and top players absence for each game)

In [34]:
player_features_df = build_player_status_features(df_boxscores)

today = datetime.now().strftime('%Y-%m-%d_%H-%M-%S')


os.makedirs(DATA_PLAYERS_DIR, exist_ok=True)
player_features_output = os.path.join(DATA_PLAYERS_DIR, f'player_features_{today}.csv')

# to csv
#player_features_df.to_csv(player_features_output, index=False)

In [35]:
player_features_df

,GAME_ID,TEAM_ID,GAME_DATE,personId,is_present,is_absent,is_injured,is_resting,is_suspended,is_personal,is_absent_other,player_perf_score,player_defense_score,player_offense_score,player_impact_score,comment
0,0029900011,1610612747,1999-11-02,779,1,0,0,0,0,0,0,37.7,-2.0,34.1,0.224,
1,0029900011,1610612747,1999-11-02,920,1,0,0,0,0,0,0,13.2,-1.5,5.4,0.027,
2,0029900011,1610612747,1999-11-02,406,1,0,0,0,0,0,0,41.1,0.5,27.1,0.118,
3,0029900011,1610612747,1999-11-02,965,1,0,0,0,0,0,0,25.1,-3.5,22.9,0.094,
4,0029900011,1610612747,1999-11-02,166,1,0,0,0,0,0,0,23.4,2.5,13.8,0.061,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3035625,0042400403,1610612754,2025-06-11,1628396,0,1,0,0,0,0,1,0.0,0.0,0.0,0.000,dnp - coach's decision
3035626,0042400403,1610612754,2025-06-11,1642277,0,1,0,0,0,0,1,0.0,0.0,0.0,0.000,dnp - coach's decision
3035627,0042400403,1610612754,2025-06-11,1630543,0,1,1,0,0,0,0,0.0,0.0,0.0,0.000,dnd - injury/illness
3035628,0042400403,1610612754,2025-06-11,201949,0,1,0,0,0,0,1,0.0,0.0,0.0,0.000,dnp - coach's decision
3035629,0042400403,1610612754,2025-06-11,1641716,0,1,1,0,0,0,0,0.0,0.0,0.0,0.000,dnd - injury/illness

In [36]:
#print duplicates on 'GAME_ID' and 'TEAM_ID', personId
duplicates = player_features_df[player_features_df.duplicated(subset=['GAME_ID', 'TEAM_ID', 'personId'], keep=False)]
if not duplicates.empty:
    print("Duplicates found:")
    display(duplicates)

In [37]:
#player_features_df[player_features_df['is_absent'] == 1].sort_values(by='GAME_ID').head(50)

#same but filter with comment "DNP - Coach's Decision"

filtered = player_features_df[
    (player_features_df['is_absent'] == 1) &
    (~player_features_df['comment'].str.contains("coach's decision", na=False))
]
display(filtered.sort_values(by=['GAME_ID', 'TEAM_ID']).tail(50))

filtered = player_features_df[
    (player_features_df['is_personal'] == 1) &
    (~player_features_df['comment'].str.contains("personal", na=False)) &
    (~player_features_df['comment'].str.contains("not with team", na=False)) 
]
display(filtered.sort_values(by=['GAME_ID', 'TEAM_ID']).tail(50))




# display(player_features_df[
#     player_features_df['is_personal'] == 1 &
#     (~player_features_df['comment'].str.contains("nwt", na=False))
#     ].head(50))

,GAME_ID,TEAM_ID,GAME_DATE,personId,is_present,is_absent,is_injured,is_resting,is_suspended,is_personal,is_absent_other,player_perf_score,player_defense_score,player_offense_score,player_impact_score,comment
28901,0049900028,1610612758,2000-05-02,895,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd - sprained left ankle
28878,0049900030,1610612759,2000-05-02,1495,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,"dnd - lateral meniscus tear, left knee"
28879,0049900030,1610612759,2000-05-02,760,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd - mid-right foot dislocation
28924,0049900032,1610612760,2000-05-03,1023,0,1,0,0,0,0,1,0.0,0.0,0.0,0.0,dnd - damaged facial nerve
28912,0049900032,1610612762,2000-05-03,228,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd- right hamstring
28949,0049900040,1610612760,2000-05-05,1023,0,1,0,0,0,0,1,0.0,0.0,0.0,0.0,dnd-did not dress - injured
28957,0049900040,1610612762,2000-05-05,228,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd - did not dress - strained r. ham.
29021,0049900041,1610612748,2000-05-07,1934,0,1,0,0,0,0,1,0.0,0.0,0.0,0.0,nwt -
29104,0049900042,1610612748,2000-05-09,1934,0,1,0,0,0,0,1,0.0,0.0,0.0,0.0,nwt -
29206,0049900043,1610612748,2000-05-12,1934,0,1,0,0,0,0,1,0.0,0.0,0.0,0.0,nwt
29246,0049900044,1610612748,2000-05-14,1934,0,1,0,0,0,0,1,0.0,0.0,0.0,0.0,nwt
29375,0049900045,1610612748,2000-05-17,1934,0,1,0,0,0,0,1,0.0,0.0,0.0,0.0,nwt
29385,0049900046,1610612748,2000-05-19,1934,0,1,0,0,0,0,1,0.0,0.0,0.0,0.0,nwt
29455,0049900047,1610612748,2000-05-21,1934,0,1,0,0,0,0,1,0.0,0.0,0.0,0.0,nwt
29148,0049900050,1610612755,2000-05-10,727,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd -chip fracture right ankle
29237,0049900051,1610612755,2000-05-13,727,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd - chip fracture right ankle
29322,0049900052,1610612754,2000-05-15,397,0,1,0,0,1,0,0,0.0,0.0,0.0,0.0,dnd - suspended
29310,0049900052,1610612755,2000-05-15,761,0,1,0,0,1,0,0,0.0,0.0,0.0,0.0,dnd - suspended
29311,0049900052,1610612755,2000-05-15,727,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd - fractured rt ankle
29420,0049900053,1610612755,2000-05-19,761,0,1,0,0,1,0,0,0.0,0.0,0.0,0.0,dnd - suspended
29159,0049900056,1610612747,2000-05-10,965,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,nwt - flu
29055,0049900062,1610612762,2000-05-07,228,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd - sore right hamstring
29118,0049900063,1610612762,2000-05-09,228,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd - strained right hamstring
29180,0049900064,1610612762,2000-05-11,228,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,"dnd - injury, right hamstring"
29275,0049900065,1610612762,2000-05-14,228,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,"dnd - injured, strained r. hamstring."
29353,0049900066,1610612762,2000-05-16,228,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd - strained right hamstring
29523,0049900071,1610612747,2000-05-26,1904,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,nwt - bad left ankle
29561,0049900072,1610612747,2000-05-28,1904,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd - sprained left ankle
29562,0049900072,1610612747,2000-05-28,216,0,1,0,0,1,0,0,0.0,0.0,0.0,0.0,nwt - league suspension
29659,0049900074,1610612747,2000-06-02,1904,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd - sprained left ankle
29683,0049900075,1610612747,2000-06-04,1904,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd - sprained left ankle.
29552,0049900078,1610612752,2000-05-27,121,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,"dnd - acute tendinitis, right foot"
29590,0049900079,1610612752,2000-05-29,121,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,"dnd - acute tendinitis, right foot"
29702,0049900083,1610612747,2000-06-07,1904,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd - sprained left ankle.
29735,0049900085,1610612747,2000-06-11,977,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd - sprained left ankle
2544883,0052300101,1610612748,2024-04-17,1626196,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - not with team
2544889,0052300101,1610612748,2024-04-17,1626179,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - not with team
2544961,0052300111,1610612741,2024-04-17,1641763,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd - injury/illness
2544963,0052300111,1610612741,2024-04-17,1630172,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd - injury/illness
2544775,0052300121,1610612747,2024-04-16,1629629,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnp - injury/illness
2545039,0052300201,1610612741,2024-04-19,1641763,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd - injury/illness
2545041,0052300201,1610612741,2024-04-19,1630172,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd - injury/illness
2545067,0052300201,1610612748,2024-04-19,202710,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd - injury/illness
2545069,0052300201,1610612748,2024-04-19,1626196,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd - injury/illness
2545071,0052300201,1610612748,2024-04-19,1626179,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd - injury/illness
2822793,0052400101,1610612737,2025-04-15,1630552,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnp - injury/illness
2822901,0052400111,1610612748,2025-04-16,1631107,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd - injury/illness
2822905,0052400111,1610612748,2025-04-16,201567,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd-return to competition reconditioning
2823035,0052400201,1610612737,2025-04-18,1630552,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd - injury/illness
2823011,0052400201,1610612748,2025-04-18,201567,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - personal

,GAME_ID,TEAM_ID,GAME_DATE,personId,is_present,is_absent,is_injured,is_resting,is_suspended,is_personal,is_absent_other,player_perf_score,player_defense_score,player_offense_score,player_impact_score,comment
243112,0020300765,1610612749,2004-02-17,1496,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family matters
243139,0020300777,1610612749,2004-02-18,1496,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family matters
244754,0020301147,1610612760,2004-04-10,2501,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - death in family
255836,0020400071,1610612765,2004-11-11,1112,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family matters
255965,0020400088,1610612765,2004-11-13,1112,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,"dnp - nwt, family matters"
262217,0020401200,1610612757,2005-04-17,1507,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family concerns
283337,0020500508,1610612760,2006-01-11,2501,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - excused absence attending funeral
346504,0020600508,1610612755,2007-01-09,2212,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - birth of child
397485,0020700039,1610612737,2007-11-04,1533,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family matters
414191,0020700731,1610612757,2008-02-08,200750,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family matter
414357,0020700737,1610612757,2008-02-09,200750,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family matter
415226,0020700778,1610612741,2008-02-14,1112,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - death in family
477147,0020800737,1610612763,2009-02-06,201589,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family reasons
488252,0020801206,1610612749,2009-04-13,2557,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt- family reasons
528092,0020900251,1610612763,2009-11-30,200752,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,dnp - nwt - family reasons
528963,0020900289,1610612744,2009-12-05,201627,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - death in family
601185,0021000686,1610612765,2011-01-28,1112,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family matter
601712,0021000705,1610612765,2011-01-30,1112,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family matter
605794,0021000874,1610612765,2011-02-26,1112,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family matter
606475,0021000906,1610612750,2011-03-02,2545,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family matter
611530,0021001107,1610612765,2011-03-30,101198,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family matter
700798,0021100099,1610612765,2012-01-06,2732,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family matters
705466,0021100181,1610612765,2012-01-15,2863,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family matter
680892,0021100260,1610612765,2012-01-25,2419,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,dnd - family matter
680970,0021100274,1610612765,2012-01-27,2419,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family matter
694090,0021100741,1610612757,2012-03-27,101109,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family
694846,0021100771,1610612737,2012-03-31,711,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family emergency
695204,0021100784,1610612744,2012-04-01,202148,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family matters
695512,0021100796,1610612744,2012-04-03,202148,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family matters
699512,0021100947,1610612757,2012-04-21,101109,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family matter
820786,0021200144,1610612738,2012-11-18,2545,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family reasons
800396,0021200607,1610612745,2013-01-21,202962,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family reasons
816109,0021201169,1610612756,2013-04-10,201563,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family reasons
816378,0021201182,1610612739,2013-04-12,203079,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family matters
1064649,0021400441,1610612757,2014-12-26,2549,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family
1076841,0021400871,1610612737,2015-02-28,201143,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family reasons
35,0029900003,1610612737,1999-11-02,375,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - death in family
130,0029900006,1610612738,1999-11-02,344,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - death in family
430,0029900014,1610612738,1999-11-03,344,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - death in family
2994,0029900127,1610612746,1999-11-19,1838,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - wife gave birth
5405,0029900224,1610612748,1999-12-03,190,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - birth in family
12162,0029900508,1610612764,2000-01-14,1888,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,dna - death in family
12313,0029900517,1610612764,2000-01-15,1888,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family matter
13054,0029900546,1610612764,2000-01-19,1888,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt-death in family
22612,0029900953,1610612756,2000-03-19,932,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family emergency
26067,0029901091,1610612737,2000-04-08,1728,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family emergency
146325,0040100154,1610612759,2002-05-01,1495,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - death in family
263201,0040400311,1610612759,2005-05-22,299,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family business
263215,0040400312,1610612759,2005-05-24,299,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family business
263252,0040400313,1610612759,2005-05-28,299,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family business

In [38]:

# Analyse des statuts des joueurs
total_rows = len(player_features_df)

# Comptage des cas
n_present = player_features_df['is_present'].sum()
n_absent = player_features_df['is_absent'].sum()
n_injured = player_features_df['is_injured'].sum()

# is_resting
# is_suspended
# is_personal

n_resting = player_features_df['is_resting'].sum()
n_suspended = player_features_df['is_suspended'].sum()
n_personal = player_features_df['is_personal'].sum()

# Lignes incohérentes : aucune des colonnes n'est True

mask_no_status = (
    (player_features_df['is_present'] == 0) &
    (player_features_df['is_absent'] == 0) &
    (player_features_df['is_injured'] == 0) &
    (player_features_df['is_resting'] == 0) &
    (player_features_df['is_suspended'] == 0) &
    (player_features_df['is_personal'] == 0)
)


n_inconsistent = mask_no_status.sum()

# Lignes avec plusieurs statuts à la fois (logiquement impossible)
mask_multiple_status = (
    player_features_df[['is_present', 'is_absent', 'is_injured']].sum(axis=1) > 1
)
n_multiple = mask_multiple_status.sum()

print(f"✅ Analyse des statuts des joueurs sur {total_rows} lignes")
print(f" - Joueurs présents : {n_present}")
print(f" - Joueurs absents : {n_absent}")
print(f" - Joueurs blessés : {n_injured}")
print(f" - Joueurs en repos : {n_resting}")
print(f" - Joueurs suspendus : {n_suspended}")
print(f" - Joueurs pour raisons personnelles : {n_personal}")
print(f"❌ Lignes sans statut défini : {n_inconsistent}")
print(f"⚠️ Lignes avec plusieurs statuts actifs : {n_multiple}")

display(player_features_df[mask_no_status].head(10))

✅ Analyse des statuts des joueurs sur 782356 lignes
 - Joueurs présents : 642800
 - Joueurs absents : 139556
 - Joueurs blessés : 22195
 - Joueurs en repos : 393
 - Joueurs suspendus : 1063
 - Joueurs pour raisons personnelles : 1056
❌ Lignes sans statut défini : 0
⚠️ Lignes avec plusieurs statuts actifs : 22195

Empty DataFrame
Columns: [GAME_ID, TEAM_ID, GAME_DATE, personId, is_present, is_absent, is_injured, is_resting, is_suspended, is_personal, is_absent_other, player_perf_score, player_defense_score, player_offense_score, player_impact_score, comment]
Index: []

# ⚙️ Aggrégation des data Player par équipe et match

In [42]:
# df_team_players = aggregate_team_player_features(player_features_df, top_n=10)

# display(df_team_players.head(10))
# display(df_team_players.tail(10))

# #display some lines with absent players
# absent_players = df_team_players[df_team_players['num_injured'] >= 1]
# absent_players 

# Identification des top joueurs sur l'ensemble du dataset
df_top_players = identify_historical_top_players(player_features_df)
print(f"✅ {df_top_players['is_historical_top'].sum()} top joueurs identifiés sur {len(df_top_players)} joueurs.")


df_agg_actual = aggregate_actual_team_features(player_features_df)
print(f"✅ {df_agg_actual.shape[0]} lignes générées dans l'aggregation actuelle par équipe.")

df_agg_top_abs = flag_top_players_absences(player_features_df, df_top_players)
print(f"✅ {df_agg_top_abs['top_player_absent'].sum()} absences de top joueurs détectées.")

df_team_features_final = df_agg_actual.merge(df_agg_top_abs, on=["GAME_ID", "TEAM_ID"], how="left")
df_team_features_final.fillna(0, inplace=True)

#add flags has_top_absent flag to use it as input and not roll it to see in analyse how much it helps to scrap this data before match
df_team_features_final['has_top_absent'] = df_team_features_final['top_player_absent'].apply(lambda x: 1 if x > 0 else 0)
df_team_features_final['has_absent'] = df_team_features_final['num_absent'].apply(lambda x: 1 if x > 0 else 0)


#sort by GAME_ID, TEAM_ID and GAME_DATE
df_team_features_final.sort_values(by=['GAME_ID', 'TEAM_ID', 'GAME_DATE'], inplace=True)


print(f"✅ Fusion réussie. Shape finale : {df_team_features_final.shape}")

✅ 319691 top joueurs identifiés sur 319691 joueurs.
✅ 66201 lignes générées dans l'aggregation actuelle par équipe.
✅ 19709 absences de top joueurs détectées.
✅ Fusion réussie. Shape finale : (66201, 27)

In [44]:
# display(df_team_features_final.head(10))
# display(df_team_features_final.tail(10))

# top_player_absence_rate
# top_player_injury_rate
# top_player_resting_rate
# top_player_suspension_rate
# top_player_personal_rate

# display(df_team_features_final[df_team_features_final['top_player_absent_rate'] > 0])
# display(df_team_features_final[df_team_features_final['top_player_injury_rate'] > 0])
# display(df_team_features_final[df_team_features_final['top_player_resting_rate'] > 0])
# display(df_team_features_final[df_team_features_final['top_player_suspension_rate'] > 0])
# display(df_team_features_final[df_team_features_final['top_player_personal_rate'] > 0])
display(df_team_features_final)

,GAME_ID,TEAM_ID,GAME_DATE,player_perf_score_mean,player_perf_score_sum,num_present,num_absent,num_injured,num_suspended,num_resting,num_personal,num_absent_other,top_player_count,top_player_absent,top_player_injured,top_player_resting,top_player_suspended,top_player_personal,top_player_absent_other,top_player_absent_rate,top_player_injury_rate,top_player_resting_rate,top_player_suspension_rate,top_player_personal_rate,top_player_absent_other_rate,has_top_absent,has_absent
0,0020000001,1610612752,2000-10-31,10.450000,125.4,12,0,0,0,0,0,0,5,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
1,0020000001,1610612755,2000-10-31,15.658333,187.9,12,0,0,0,0,0,0,5,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
2,0020000002,1610612739,2000-10-31,13.866667,166.4,11,1,0,0,0,0,1,5,1,0,0,0,0,1,0.2,0.0,0.0,0.0,0.0,0.2,1,1
3,0020000002,1610612751,2000-10-31,14.950000,179.4,10,2,0,0,0,0,2,5,1,0,0,0,0,1,0.2,0.0,0.0,0.0,0.0,0.2,1,1
4,0020000003,1610612753,2000-10-31,14.616667,175.4,10,2,0,0,0,0,2,5,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66196,0052400131,1610612758,2025-04-16,14.253846,185.3,12,1,0,0,0,0,1,5,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1
66197,0052400201,1610612737,2025-04-18,18.150000,217.8,9,3,1,0,0,0,2,5,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1
66198,0052400201,1610612748,2025-04-18,15.686667,235.3,9,6,0,0,0,1,5,5,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1
66199,0052400211,1610612742,2025-04-18,14.438462,187.7,11,2,0,0,0,0,2,5,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1
66200,0052400211,1610612763,2025-04-18,17.461538,227.0,12,1,0,0,0,0,1,5,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1

# ⚙️ Aggrégation des data Boxscore purs par équipe et match

## 📊 Agrégation des données par équipe et match

In [49]:

# 1. Agrégation par somme
group_keys = ['GAME_ID', 'TEAM_ID']
sum_agg = df_boxscores[group_keys + cols_to_sum].copy()
sum_agg = sum_agg.groupby(group_keys).sum().reset_index()

# 2. Agrégation pondérée par les minutes jouées
weighted_agg = compute_weighted_mean_features(df_boxscores, group_keys, cols_to_weighted_avg, weight_col='MINUTES_PLAYED')

# 3. Fusion des deux agrégats
team_match_stats = pd.merge(sum_agg, weighted_agg, on=group_keys, how='left')

# 4. Identifier l'équipe adverse
teams_in_game = df_boxscores.groupby('GAME_ID')['TEAM_ID'].unique().to_dict()
def get_opponent(row):
    teams = teams_in_game.get(row['GAME_ID'], [])
    opps = [tid for tid in teams if tid != row['TEAM_ID']]
    return opps[0] if opps else None

team_match_stats['OPP_TEAM_ID'] = team_match_stats.apply(get_opponent, axis=1)

In [ ]:
count = 0

for game_id, teams in teams_in_game.items():
    if len(teams) < 2:
        #print(f"Attention : GAME_ID {game_id} a moins de 2 équipes : {teams}")
        count += 1
        
print(f"Nombre de GAME_ID avec moins de 2 équipes : {count}")

Attention : GAME_ID 0020300003 a moins de 2 équipes : ['1610612747']
Attention : GAME_ID 0020300017 a moins de 2 équipes : ['1610612745']
Attention : GAME_ID 0020300021 a moins de 2 équipes : ['1610612749']
Attention : GAME_ID 0020300032 a moins de 2 équipes : ['1610612749']
Attention : GAME_ID 0020300035 a moins de 2 équipes : ['1610612759']
Attention : GAME_ID 0020300053 a moins de 2 équipes : ['1610612764']
Attention : GAME_ID 0020300069 a moins de 2 équipes : ['1610612753']
Attention : GAME_ID 0020300089 a moins de 2 équipes : ['1610612760']
Attention : GAME_ID 0020300118 a moins de 2 équipes : ['1610612760']
Attention : GAME_ID 0020300122 a moins de 2 équipes : ['1610612761']
Attention : GAME_ID 0020300138 a moins de 2 équipes : ['1610612747']
Attention : GAME_ID 0020300144 a moins de 2 équipes : ['1610612739']
Attention : GAME_ID 0020300291 a moins de 2 équipes : ['1610612760']
Attention : GAME_ID 0020300292 a moins de 2 équipes : ['1610612748']
Attention : GAME_ID 0020300303 a moins de 2 équipes : ['1610612759']
Attention : GAME_ID 0020300306 a moins de 2 équipes : ['1610612739']
Attention : GAME_ID 0020300313 a moins de 2 équipes : ['1610612737']
Attention : GAME_ID 0020300315 a moins de 2 équipes : ['1610612760']
Attention : GAME_ID 0020300344 a moins de 2 équipes : ['1610612743']
Attention : GAME_ID 0020300350 a moins de 2 équipes : ['1610612762']
Attention : GAME_ID 0020300355 a moins de 2 équipes : ['1610612743']
Attention : GAME_ID 0020300356 a moins de 2 équipes : ['1610612746']
Attention : GAME_ID 0020300367 a moins de 2 équipes : ['1610612748']
Attention : GAME_ID 0020300368 a moins de 2 équipes : ['1610612745']
Attention : GAME_ID 0020300370 a moins de 2 équipes : ['1610612759']
Attention : GAME_ID 0020300384 a moins de 2 équipes : ['1610612757']
Attention : GAME_ID 0020300406 a moins de 2 équipes : ['1610612740']
Attention : GAME_ID 0020300435 a moins de 2 équipes : ['1610612745']
Attention : GAME_ID 0020300443 a moins de 2 équipes : ['1610612763']
Attention : GAME_ID 0020300458 a moins de 2 équipes : ['1610612750']
Attention : GAME_ID 0020300462 a moins de 2 équipes : ['1610612760']
Attention : GAME_ID 0020300466 a moins de 2 équipes : ['1610612754']
Attention : GAME_ID 0020300484 a moins de 2 équipes : ['1610612757']
Attention : GAME_ID 0020300489 a moins de 2 équipes : ['1610612764']
Attention : GAME_ID 0020300496 a moins de 2 équipes : ['1610612765']
Attention : GAME_ID 0020300500 a moins de 2 équipes : ['1610612747']
Attention : GAME_ID 0020300502 a moins de 2 équipes : ['1610612760']
Attention : GAME_ID 0020300515 a moins de 2 équipes : ['1610612747']
Attention : GAME_ID 0020300517 a moins de 2 équipes : ['1610612755']
Attention : GAME_ID 0020300522 a moins de 2 équipes : ['1610612762']
Attention : GAME_ID 0020300539 a moins de 2 équipes : ['1610612756']
Attention : GAME_ID 0020300550 a moins de 2 équipes : ['1610612747']
Attention : GAME_ID 0020300553 a moins de 2 équipes : ['1610612763']
Attention : GAME_ID 0020300559 a moins de 2 équipes : ['1610612752']
Attention : GAME_ID 0020300560 a moins de 2 équipes : ['1610612764']
Attention : GAME_ID 0020300573 a moins de 2 équipes : ['1610612762']
Attention : GAME_ID 0020300576 a moins de 2 équipes : ['1610612738']
Attention : GAME_ID 0020300590 a moins de 2 équipes : ['1610612760']
Attention : GAME_ID 0020300594 a moins de 2 équipes : ['1610612762']
Attention : GAME_ID 0020300597 a moins de 2 équipes : ['1610612737']
Attention : GAME_ID 0020300605 a moins de 2 équipes : ['1610612758']
Attention : GAME_ID 0020300607 a moins de 2 équipes : ['1610612760']
Attention : GAME_ID 0020300615 a moins de 2 équipes : ['1610612758']
Attention : GAME_ID 0020300620 a moins de 2 équipes : ['1610612744']
Attention : GAME_ID 0020300621 a moins de 2 équipes : ['1610612754']
Attention : GAME_ID 0020300627 a moins de 2 équipes : ['1610612738']
Attention : GAME_ID 0020300631 a moins de 2 équipes : ['1610612745']
Attention : GAME_ID 0020300636 a moins de 2 équipes : ['1610612748']
Attention : GAME_ID 0020300640 a moins de 2 équipes : ['1610612755']
Attention : GAME_ID 0020300644 a moins de 2 équipes : ['1610612746']
Attention : GAME_ID 0020300648 a moins de 2 équipes : ['1610612756']
Attention : GAME_ID 0020300651 a moins de 2 équipes : ['1610612763']
Attention : GAME_ID 0020300653 a moins de 2 équipes : ['1610612743']
Attention : GAME_ID 0020300686 a moins de 2 équipes : ['1610612740']
Attention : GAME_ID 0020300691 a moins de 2 équipes : ['1610612741']
Attention : GAME_ID 0020300695 a moins de 2 équipes : ['1610612750']
Attention : GAME_ID 0020300708 a moins de 2 équipes : ['1610612747']
Attention : GAME_ID 0020300713 a moins de 2 équipes : ['1610612753']
Attention : GAME_ID 0020300722 a moins de 2 équipes : ['1610612748']
Attention : GAME_ID 0020300723 a moins de 2 équipes : ['1610612738']
Attention : GAME_ID 0020300756 a moins de 2 équipes : ['1610612745']
Attention : GAME_ID 0020300765 a moins de 2 équipes : ['1610612749']
Attention : GAME_ID 0020300774 a moins de 2 équipes : ['1610612761']
Attention : GAME_ID 0020300781 a moins de 2 équipes : ['1610612758']
Attention : GAME_ID 0020300782 a moins de 2 équipes : ['1610612755']
Attention : GAME_ID 0020300783 a moins de 2 équipes : ['1610612746']
Attention : GAME_ID 0020300786 a moins de 2 équipes : ['1610612762']
Attention : GAME_ID 0020300790 a moins de 2 équipes : ['1610612765']
Attention : GAME_ID 0020300796 a moins de 2 équipes : ['1610612748']
Attention : GAME_ID 0020300801 a moins de 2 équipes : ['1610612744']
Attention : GAME_ID 0020300805 a moins de 2 équipes : ['1610612759']
Attention : GAME_ID 0020300806 a moins de 2 équipes : ['1610612764']
Attention : GAME_ID 0020300808 a moins de 2 équipes : ['1610612756']
Attention : GAME_ID 0020300817 a moins de 2 équipes : ['1610612761']
Attention : GAME_ID 0020300821 a moins de 2 équipes : ['1610612759']
Attention : GAME_ID 0020300831 a moins de 2 équipes : ['1610612743']
Attention : GAME_ID 0020300839 a moins de 2 équipes : ['1610612740']
Attention : GAME_ID 0020300840 a moins de 2 équipes : ['1610612737']
Attention : GAME_ID 0020300848 a moins de 2 équipes : ['1610612764']
Attention : GAME_ID 0020300861 a moins de 2 équipes : ['1610612758']
Attention : GAME_ID 0020300866 a moins de 2 équipes : ['1610612763']
Attention : GAME_ID 0020300874 a moins de 2 équipes : ['1610612764']
Attention : GAME_ID 0020300876 a moins de 2 équipes : ['1610612739']
Attention : GAME_ID 0020300880 a moins de 2 équipes : ['1610612760']
Attention : GAME_ID 0020300883 a moins de 2 équipes : ['1610612746']
Attention : GAME_ID 0020300892 a moins de 2 équipes : ['1610612759']
Attention : GAME_ID 0020300911 a moins de 2 équipes : ['1610612757']
Attention : GAME_ID 0020300916 a moins de 2 équipes : ['1610612747']
Attention : GAME_ID 0020300917 a moins de 2 équipes : ['1610612764']
Attention : GAME_ID 0020300928 a moins de 2 équipes : ['1610612739']
Attention : GAME_ID 0020300933 a moins de 2 équipes : ['1610612746']
Attention : GAME_ID 0020300937 a moins de 2 équipes : ['1610612758']
Attention : GAME_ID 0020300940 a moins de 2 équipes : ['1610612741']
Attention : GAME_ID 0020300943 a moins de 2 équipes : ['1610612750']
Attention : GAME_ID 0020300962 a moins de 2 équipes : ['1610612762']
Attention : GAME_ID 0020300967 a moins de 2 équipes : ['1610612741']
Attention : GAME_ID 0020300969 a moins de 2 équipes : ['1610612758']
Attention : GAME_ID 0020300982 a moins de 2 équipes : ['1610612744']
Attention : GAME_ID 0020300993 a moins de 2 équipes : ['1610612738']
Attention : GAME_ID 0020301001 a moins de 2 équipes : ['1610612738']
Attention : GAME_ID 0020301011 a moins de 2 équipes : ['1610612753']
Attention : GAME_ID 0020301014 a moins de 2 équipes : ['1610612754']
Attention : GAME_ID 0020301016 a moins de 2 équipes : ['1610612746']
Attention : GAME_ID 0020301019 a moins de 2 équipes : ['1610612765']
Attention : GAME_ID 0020301023 a moins de 2 équipes : ['1610612764']
Attention : GAME_ID 0020301027 a moins de 2 équipes : ['1610612752']
Attention : GAME_ID 0020301032 a moins de 2 équipes : ['1610612760']
Attention : GAME_ID 0020301033 a moins de 2 équipes : ['1610612758']
Attention : GAME_ID 0020301046 a moins de 2 équipes : ['1610612750']
Attention : GAME_ID 0020301048 a moins de 2 équipes : ['1610612760']
Attention : GAME_ID 0020301060 a moins de 2 équipes : ['1610612755']
Attention : GAME_ID 0020301063 a moins de 2 équipes : ['1610612762']
Attention : GAME_ID 0020301073 a moins de 2 équipes : ['1610612742']
Attention : GAME_ID 0020301077 a moins de 2 équipes : ['1610612764']
Attention : GAME_ID 0020301078 a moins de 2 équipes : ['1610612741']
Attention : GAME_ID 0020301091 a moins de 2 équipes : ['1610612754']
Attention : GAME_ID 0020301092 a moins de 2 équipes : ['1610612751']
Attention : GAME_ID 0020301094 a moins de 2 équipes : ['1610612764']
Attention : GAME_ID 0020301095 a moins de 2 équipes : ['1610612756']
Attention : GAME_ID 0020301099 a moins de 2 équipes : ['1610612759']
Attention : GAME_ID 0020301100 a moins de 2 équipes : ['1610612760']
Attention : GAME_ID 0020301111 a moins de 2 équipes : ['1610612754']
Attention : GAME_ID 0020301118 a moins de 2 équipes : ['1610612753']
Attention : GAME_ID 0020301119 a moins de 2 équipes : ['1610612752']
Attention : GAME_ID 0020301120 a moins de 2 équipes : ['1610612742']
Attention : GAME_ID 0020301124 a moins de 2 équipes : ['1610612741']
Attention : GAME_ID 0020301129 a moins de 2 équipes : ['1610612760']
Attention : GAME_ID 0020301132 a moins de 2 équipes : ['1610612746']
Attention : GAME_ID 0020301133 a moins de 2 équipes : ['1610612753']
Attention : GAME_ID 0020301134 a moins de 2 équipes : ['1610612742']
Attention : GAME_ID 0020301140 a moins de 2 équipes : ['1610612759']
Attention : GAME_ID 0020301155 a moins de 2 équipes : ['1610612755']
Attention : GAME_ID 0020301164 a moins de 2 équipes : ['1610612737']
Attention : GAME_ID 0020301170 a moins de 2 équipes : ['1610612759']
Attention : GAME_ID 0020301185 a moins de 2 équipes : ['1610612756']
Attention : GAME_ID 0020301187 a moins de 2 équipes : ['1610612747']
Attention : GAME_ID 0020400008 a moins de 2 équipes : ['1610612748']
Attention : GAME_ID 0020400010 a moins de 2 équipes : ['1610612742']
Attention : GAME_ID 0020400012 a moins de 2 équipes : ['1610612758']
Attention : GAME_ID 0020400013 a moins de 2 équipes : ['1610612756']
Attention : GAME_ID 0020400014 a moins de 2 équipes : ['1610612762']
Attention : GAME_ID 0020400017 a moins de 2 équipes : ['1610612764']
Attention : GAME_ID 0020400029 a moins de 2 équipes : ['1610612737']
Attention : GAME_ID 0020400032 a moins de 2 équipes : ['1610612752']
Attention : GAME_ID 0020400034 a moins de 2 équipes : ['1610612756']
Attention : GAME_ID 0020400040 a moins de 2 équipes : ['1610612743']
Attention : GAME_ID 0020400043 a moins de 2 équipes : ['1610612759']
Attention : GAME_ID 0020400044 a moins de 2 équipes : ['1610612737']
Attention : GAME_ID 0020400048 a moins de 2 équipes : ['1610612742']
Attention : GAME_ID 0020400052 a moins de 2 équipes : ['1610612748']
Attention : GAME_ID 0020400057 a moins de 2 équipes : ['1610612743']
Attention : GAME_ID 0020400062 a moins de 2 équipes : ['1610612754']
Attention : GAME_ID 0020400066 a moins de 2 équipes : ['1610612759']
Attention : GAME_ID 0020400067 a moins de 2 équipes : ['1610612761']
Attention : GAME_ID 0020400074 a moins de 2 équipes : ['1610612766']
Attention : GAME_ID 0020400075 a moins de 2 équipes : ['1610612746']
Attention : GAME_ID 0020400080 a moins de 2 équipes : ['1610612742']
Attention : GAME_ID 0020400081 a moins de 2 équipes : ['1610612739']
Attention : GAME_ID 0020400083 a moins de 2 équipes : ['1610612737']
Attention : GAME_ID 0020400084 a moins de 2 équipes : ['1610612754']
Attention : GAME_ID 0020400095 a moins de 2 équipes : ['1610612743']
Attention : GAME_ID 0020400097 a moins de 2 équipes : ['1610612745']
Attention : GAME_ID 0020400101 a moins de 2 équipes : ['1610612748']
Attention : GAME_ID 0020400105 a moins de 2 équipes : ['1610612746']
Attention : GAME_ID 0020400106 a moins de 2 équipes : ['1610612764']
Attention : GAME_ID 0020400116 a moins de 2 équipes : ['1610612744']
Attention : GAME_ID 0020400118 a moins de 2 équipes : ['1610612766']
Attention : GAME_ID 0020400135 a moins de 2 équipes : ['1610612763']
Attention : GAME_ID 0020400138 a moins de 2 équipes : ['1610612738']
Attention : GAME_ID 0020400147 a moins de 2 équipes : ['1610612742']
Attention : GAME_ID 0020400152 a moins de 2 équipes : ['1610612754']
Attention : GAME_ID 0020400161 a moins de 2 équipes : ['1610612755']
Attention : GAME_ID 0020400163 a moins de 2 équipes : ['1610612739']
Attention : GAME_ID 0020400166 a moins de 2 équipes : ['1610612742']
Attention : GAME_ID 0020400170 a moins de 2 équipes : ['1610612746']
Attention : GAME_ID 0020400179 a moins de 2 équipes : ['1610612762']
Attention : GAME_ID 0020400186 a moins de 2 équipes : ['1610612753']
Attention : GAME_ID 0020400190 a moins de 2 équipes : ['1610612762']
Attention : GAME_ID 0020400195 a moins de 2 équipes : ['1610612751']
Attention : GAME_ID 0020400197 a moins de 2 équipes : ['1610612760']
Attention : GAME_ID 0020400215 a moins de 2 équipes : ['1610612740']
Attention : GAME_ID 0020400218 a moins de 2 équipes : ['1610612756']
Attention : GAME_ID 0020400222 a moins de 2 équipes : ['1610612742']
Attention : GAME_ID 0020400226 a moins de 2 équipes : ['1610612764']
Attention : GAME_ID 0020400229 a moins de 2 équipes : ['1610612748']
Attention : GAME_ID 0020400232 a moins de 2 équipes : ['1610612754']
Attention : GAME_ID 0020400236 a moins de 2 équipes : ['1610612739']
Attention : GAME_ID 0020400239 a moins de 2 équipes : ['1610612749']
Attention : GAME_ID 0020400243 a moins de 2 équipes : ['1610612746']
Attention : GAME_ID 0020400244 a moins de 2 équipes : ['1610612744']
Attention : GAME_ID 0020400246 a moins de 2 équipes : ['1610612738']
Attention : GAME_ID 0020400247 a moins de 2 équipes : ['1610612756']
Attention : GAME_ID 0020400269 a moins de 2 équipes : ['1610612741']
Attention : GAME_ID 0020400291 a moins de 2 équipes : ['1610612745']
Attention : GAME_ID 0020400297 a moins de 2 équipes : ['1610612740']
Attention : GAME_ID 0020400305 a moins de 2 équipes : ['1610612756']
Attention : GAME_ID 0020400319 a moins de 2 équipes : ['1610612757']
Attention : GAME_ID 0020400328 a moins de 2 équipes : ['1610612747']
Attention : GAME_ID 0020400329 a moins de 2 équipes : ['1610612752']
Attention : GAME_ID 0020400336 a moins de 2 équipes : ['1610612746']
Attention : GAME_ID 0020400341 a moins de 2 équipes : ['1610612743']
Attention : GAME_ID 0020400360 a moins de 2 équipes : ['1610612751']
Attention : GAME_ID 0020400361 a moins de 2 équipes : ['1610612739']
Attention : GAME_ID 0020400362 a moins de 2 équipes : ['1610612742']
Attention : GAME_ID 0020400386 a moins de 2 équipes : ['1610612759']
Attention : GAME_ID 0020400394 a moins de 2 équipes : ['1610612740']
Attention : GAME_ID 0020400397 a moins de 2 équipes : ['1610612746']
Attention : GAME_ID 0020400398 a moins de 2 équipes : ['1610612760']
Attention : GAME_ID 0020400402 a moins de 2 équipes : ['1610612745']
Attention : GAME_ID 0020400404 a moins de 2 équipes : ['1610612742']
Attention : GAME_ID 0020400418 a moins de 2 équipes : ['1610612751']
Attention : GAME_ID 0020400424 a moins de 2 équipes : ['1610612758']
Attention : GAME_ID 0020400434 a moins de 2 équipes : ['1610612765']
Attention : GAME_ID 0020400436 a moins de 2 équipes : ['1610612745']
Attention : GAME_ID 0020400442 a moins de 2 équipes : ['1610612766']
Attention : GAME_ID 0020400449 a moins de 2 équipes : ['1610612754']
Attention : GAME_ID 0020400452 a moins de 2 équipes : ['1610612747']
Attention : GAME_ID 0020400467 a moins de 2 équipes : ['1610612759']
Attention : GAME_ID 0020400469 a moins de 2 équipes : ['1610612753']
Attention : GAME_ID 0020400474 a moins de 2 équipes : ['1610612755']
Attention : GAME_ID 0020400476 a moins de 2 équipes : ['1610612748']
Attention : GAME_ID 0020400488 a moins de 2 équipes : ['1610612752']
Attention : GAME_ID 0020400497 a moins de 2 équipes : ['1610612739']
Attention : GAME_ID 0020400509 a moins de 2 équipes : ['1610612755']
Attention : GAME_ID 0020400521 a moins de 2 équipes : ['1610612756']
Attention : GAME_ID 0020400522 a moins de 2 équipes : ['1610612738']
Attention : GAME_ID 0020400530 a moins de 2 équipes : ['1610612752']
Attention : GAME_ID 0020400532 a moins de 2 équipes : ['1610612766']
Attention : GAME_ID 0020400542 a moins de 2 équipes : ['1610612740']
Attention : GAME_ID 0020400545 a moins de 2 équipes : ['1610612749']
Attention : GAME_ID 0020400560 a moins de 2 équipes : ['1610612741']
Attention : GAME_ID 0020400562 a moins de 2 équipes : ['1610612755']
Attention : GAME_ID 0020400571 a moins de 2 équipes : ['1610612753']
Attention : GAME_ID 0020400572 a moins de 2 équipes : ['1610612739']
Attention : GAME_ID 0020400575 a moins de 2 équipes : ['1610612751']
Attention : GAME_ID 0020400584 a moins de 2 équipes : ['1610612737']
Attention : GAME_ID 0020400598 a moins de 2 équipes : ['1610612760']
Attention : GAME_ID 0020400601 a moins de 2 équipes : ['1610612740']
Attention : GAME_ID 0020400604 a moins de 2 équipes : ['1610612757']
Attention : GAME_ID 0020400611 a moins de 2 équipes : ['1610612760']
Attention : GAME_ID 0020400612 a moins de 2 équipes : ['1610612754']
Attention : GAME_ID 0020400613 a moins de 2 équipes : ['1610612748']
Attention : GAME_ID 0020400615 a moins de 2 équipes : ['1610612739']
Attention : GAME_ID 0020400625 a moins de 2 équipes : ['1610612766']
Attention : GAME_ID 0020400626 a moins de 2 équipes : ['1610612758']
Attention : GAME_ID 0020400630 a moins de 2 équipes : ['1610612756']
Attention : GAME_ID 0020400633 a moins de 2 équipes : ['1610612762']
Attention : GAME_ID 0020400635 a moins de 2 équipes : ['1610612758']
Attention : GAME_ID 0020400643 a moins de 2 équipes : ['1610612738']
Attention : GAME_ID 0020400646 a moins de 2 équipes : ['1610612751']
Attention : GAME_ID 0020400649 a moins de 2 équipes : ['1610612761']
Attention : GAME_ID 0020400662 a moins de 2 équipes : ['1610612749']
Attention : GAME_ID 0020400665 a moins de 2 équipes : ['1610612743']
Attention : GAME_ID 0020400666 a moins de 2 équipes : ['1610612766']
Attention : GAME_ID 0020400669 a moins de 2 équipes : ['1610612751']
Attention : GAME_ID 0020400674 a moins de 2 équipes : ['1610612750']
Attention : GAME_ID 0020400681 a moins de 2 équipes : ['1610612737']
Attention : GAME_ID 0020400683 a moins de 2 équipes : ['1610612753']
Attention : GAME_ID 0020400685 a moins de 2 équipes : ['1610612745']
Attention : GAME_ID 0020400689 a moins de 2 équipes : ['1610612765']
Attention : GAME_ID 0020400690 a moins de 2 équipes : ['1610612764']
Attention : GAME_ID 0020400695 a moins de 2 équipes : ['1610612740']
Attention : GAME_ID 0020400698 a moins de 2 équipes : ['1610612760']
Attention : GAME_ID 0020400707 a moins de 2 équipes : ['1610612752']
Attention : GAME_ID 0020400725 a moins de 2 équipes : ['1610612745']
Attention : GAME_ID 0020400733 a moins de 2 équipes : ['1610612745']
Attention : GAME_ID 0020400734 a moins de 2 équipes : ['1610612752']
Attention : GAME_ID 0020400743 a moins de 2 équipes : ['1610612765']
Attention : GAME_ID 0020400769 a moins de 2 équipes : ['1610612763']
Attention : GAME_ID 0020400773 a moins de 2 équipes : ['1610612739']
Attention : GAME_ID 0020400794 a moins de 2 équipes : ['1610612760']
Attention : GAME_ID 0020400796 a moins de 2 équipes : ['1610612743']
Attention : GAME_ID 0020400811 a moins de 2 équipes : ['1610612747']
Attention : GAME_ID 0020400812 a moins de 2 équipes : ['1610612760']
Attention : GAME_ID 0020400838 a moins de 2 équipes : ['1610612745']
Attention : GAME_ID 0020400839 a moins de 2 équipes : ['1610612737']
Attention : GAME_ID 0020400840 a moins de 2 équipes : ['1610612765']
Attention : GAME_ID 0020400844 a moins de 2 équipes : ['1610612760']
Attention : GAME_ID 0020400847 a moins de 2 équipes : ['1610612761']

# 🔁 Ajout des colonnes OPP_ avec les data de l'adversaire

In [51]:
team_cols = [col for col in team_match_stats.columns if col not in ['GAME_ID', 'TEAM_ID', 'OPP_TEAM_ID']]
opp_cols = [f"OPP_{col}" for col in team_cols]
df_opp = team_match_stats.rename(columns={col: f"OPP_{col}" for col in team_cols}).rename(
    columns={'TEAM_ID': 'OPP_TEAM_ID', 'OPP_TEAM_ID': 'TEAM_ID'})
match_dataset = pd.merge(
    team_match_stats,
    df_opp[['GAME_ID', 'TEAM_ID'] + opp_cols],
    on=['GAME_ID', 'TEAM_ID'],
    how='left'
)

In [52]:
match_dataset.columns

Index(['GAME_ID', 'TEAM_ID', 'fieldGoalsMade_traditional',
       'fieldGoalsAttempted_traditional', 'threePointersMade_traditional',
       'threePointersAttempted_traditional', 'freeThrowsMade_traditional',
       'freeThrowsAttempted_traditional', 'reboundsOffensive_traditional',
       'reboundsDefensive_traditional',
       ...
       'OPP_percentageReboundsTotal_usage', 'OPP_percentageAssists_usage',
       'OPP_percentageTurnovers_usage', 'OPP_percentageSteals_usage',
       'OPP_percentageBlocks_usage', 'OPP_percentageBlocksAllowed_usage',
       'OPP_percentagePersonalFouls_usage',
       'OPP_percentagePersonalFoulsDrawn_usage', 'OPP_percentagePoints_usage',
       'OPP_plusMinusPoints_traditional'],
      dtype='object', length=165)

# 🏠 Ajout IS_HOME et IS_WIN

In [53]:
df_games

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS,SEASON
0,21995,1610612742,DAL,Dallas Mavericks,0029500011,1995-11-03,DAL @ SAN,W,240,103,42,89,0.472,4,12,0.333,15,23,0.652,15,34,49,16,7,7,17,30,NaN,1995-96
1,21995,1610612737,ATL,Atlanta Hawks,0029500002,1995-11-03,ATL vs. IND,L,240,106,35,73,0.479,6,14,0.429,30,47,0.638,14,13,27,21,12,4,12,32,NaN,1995-96
2,21995,1610612758,SAC,Sacramento Kings,0029500009,1995-11-03,SAC vs. MIN,W,240,95,33,67,0.493,7,13,0.538,22,33,0.667,6,31,37,21,12,6,21,26,NaN,1995-96
3,21995,1610612739,CLE,Cleveland Cavaliers,0029500010,1995-11-03,CLE @ ORL,L,240,88,30,63,0.476,9,16,0.563,19,33,0.576,6,25,31,20,9,4,10,21,NaN,1995-96
4,21995,1610612757,POR,Portland Trail Blazers,0029500007,1995-11-03,POR vs. VAN,L,240,80,29,81,0.358,5,22,0.227,17,30,0.567,23,28,51,20,11,3,26,25,NaN,1995-96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86077,42024,1610612754,IND,Indiana Pacers,0042400401,2025-06-05,IND @ OKC,W,240,111,39,82,0.476,18,39,0.462,15,21,0.714,13,43,56,24,1,7,24,22,1.0,2024-25
86078,42024,1610612760,OKC,Oklahoma City Thunder,0042400402,2025-06-08,OKC vs. IND,W,240,123,40,82,0.488,14,36,0.389,29,33,0.879,11,32,43,25,10,4,13,20,16.0,2024-25
86079,42024,1610612754,IND,Indiana Pacers,0042400402,2025-06-08,IND @ OKC,L,241,107,37,82,0.451,14,40,0.350,19,26,0.731,7,28,35,27,9,6,15,25,-16.0,2024-25
86080,42024,1610612760,OKC,Oklahoma City Thunder,0042400403,2025-06-11,OKC @ IND,L,239,107,37,79,0.468,10,22,0.455,23,30,0.767,9,33,42,16,6,4,17,20,-9.0,2024-25
86081,42024,1610612754,IND,Indiana Pacers,0042400403,2025-06-11,IND vs. OKC,W,239,116,44,85,0.518,9,27,0.333,19,22,0.864,7,29,36,24,13,11,13,24,9.0,2024-25

In [54]:
match_dataset

,GAME_ID,TEAM_ID,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,points_traditional,MINUTES_PLAYED,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,blocksAgainst_misc,offensiveRating_advanced,defensiveRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,threePointersPercentage_traditional,freeThrowsPercentage_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage,plusMinusPoints_traditional,OPP_TEAM_ID,OPP_fieldGoalsMade_traditional,OPP_fieldGoalsAttempted_traditional,OPP_threePointersMade_traditional,OPP_threePointersAttempted_traditional,OPP_freeThrowsMade_traditional,OPP_freeThrowsAttempted_traditional,OPP_reboundsOffensive_traditional,OPP_reboundsDefensive_traditional,OPP_reboundsTotal_traditional,OPP_assists_traditional,OPP_steals_traditional,OPP_blocks_traditional,OPP_turnovers_traditional,OPP_foulsPersonal_traditional,OPP_points_traditional,OPP_MINUTES_PLAYED,OPP_pointsOffTurnovers_misc,OPP_pointsSecondChance_misc,OPP_pointsFastBreak_misc,OPP_pointsPaint_misc,OPP_blocksAgainst_misc,OPP_offensiveRating_advanced,OPP_defensiveRating_advanced,OPP_netRating_advanced,OPP_assistPercentage_advanced,OPP_assistToTurnover_advanced,OPP_assistRatio_advanced,OPP_offensiveReboundPercentage_advanced,OPP_defensiveReboundPercentage_advanced,OPP_reboundPercentage_advanced,OPP_turnoverRatio_advanced,OPP_effectiveFieldGoalPercentage_advanced,OPP_trueShootingPercentage_advanced,OPP_usagePercentage_advanced,OPP_estimatedPace_advanced,OPP_pace_advanced,OPP_possessions_advanced,OPP_PIE_advanced,OPP_effectiveFieldGoalPercentage_fourfactors,OPP_freeThrowAttemptRate_fourfactors,OPP_teamTurnoverPercentage_fourfactors,OPP_oppEffectiveFieldGoalPercentage_fourfactors,OPP_oppFreeThrowAttemptRate_fourfactors,OPP_oppTeamTurnoverPercentage_fourfactors,OPP_oppOffensiveReboundPercentage_fourfactors,OPP_foulsDrawn_misc,OPP_percentageFieldGoalsAttempted2pt_scoring,OPP_percentageFieldGoalsAttempted3pt_scoring,OPP_percentagePoints2pt_scoring,OPP_percentagePointsMidrange2pt_scoring,OPP_percentagePoints3pt_scoring,OPP_percentagePointsFastBreak_scoring,OPP_percentagePointsFreeThrow_scoring,OPP_percentagePointsOffTurnovers_scoring,OPP_percentagePointsPaint_scoring,OPP_percentageAssisted2pt_scoring,OPP_percentageUnassisted2pt_scoring,OPP_percentageAssisted3pt_scoring,OPP_percentageUnassisted3pt_scoring,OPP_percentageAssistedFGM_scoring,OPP_percentageUnassistedFGM_scoring,OPP_threePointersPercentage_traditional,OPP_freeThrowsPercentage_traditional,OPP_percentageFieldGoalsMade_usage,OPP_percentageFieldGoalsAttempted_usage,OPP_percentageThreePointersMade_usage,OPP_percentageThreePointersAttempted_usage,OPP_percentageFreeThrowsMade_usage,OPP_percentageFreeThrowsAttempted_usage,OPP_percentageReboundsOffensive_usage,OPP_percentageReboundsDefensive_usage,OPP_percentageReboundsTotal_usage,OPP_percentageAssists_usage,OPP_percentageTurnovers_usage,OPP_percentageSteals_usage,OPP_percentageBlocks_usage,OPP_percentageBlocksAllowed_usage,OPP_percentagePersonalFouls_usage,OPP_percentagePersonalFoulsDrawn_usage,OPP_percentagePoints_usage,OPP_plusMinusPoints_traditional
0,0020000001,1610612752,25,70,3,11,19,24,14,23,37,14,6,4,22,30,72,240.000000,12,15,4,22,5,80.922299,114.464688,-33.537868,0.163246,0.523610,11.026556,0.056220,0.147483,0.091563,19.763500,0.372955,0.436562,0.193970,86.879031,88.699676,43.962361,0.039403,0.377483,0.365924,0.247518,0.598126,0.458272,0.160368,0.266661,0.000000,0.857836,0.142164,0.650577,0.241035,0.057733,0.039143,0.257106,0.165235,0.409507,0.518244,0.447172,0.197778,0.000000,0.559933,0.405484,0.108844,0.466333,0.213520,0.203724,0.197778,0.193515,0.199331,0.190465,0.232461,0.204200,0.204153,0.200857,0.197202,0.196856,0.199583,0.160243,0.192422,0.000000,0.201207,-14.930903,1610612755,38.0,66.0,3.0,8.0,22.0,30.0,8.0,29.0,37.0,27.0,10.0,5.0,13.0,24.0,101.0,240.000000,26.0,9.0,10.0,36.0,4.0,113.678208,80.924167,32.729556,0.182441,1.177822,20.832340,0.049657,0.117050,0.092804,12.917368,0.562437,0.596134,0.194474,86.879235,88.899378,50.502014,0.160855,0.601599,0.469504,0.161353,0.382886,0.361238,0.246772,0.319077,0.000000,0.839428,0.116266,0.644489,0.293966,0.049281,0.125861,0.169078,0.233654,0.350402,0.615402,0.247446,0.168090,0.078368,0.629851,0.232997,0.168090,0.508698,0.203276,0.200388,0.194265,0.173397,0.203479,0.208561,0.163576,0.192186,0.195743,0.196602,0.176540,0.217619,0.134035,0.178715,0.194042,0.000000,0.208010,18.242986
1,0020000001,1610612755,38,66,3,8,22,30,8,29,37,27,10,5,13,24,101,240.000000,26,9,10,36,4,113.678208,80.924167,32.729556,0.182441,1.177822,20.832340,0.049657,0.117050,0.092804,12.917368,0.562437,0.596134,0.194474,86.879235,88.899378,50.502014,0.160855,0.601599,0.469504,0.161353,0.382886,0.361238,0.246772,0.319077,0.000000,0.839428,0.116266,0.644489,0.293966,0.049281,0.125861,0.169078,0.233654,0.350402,0.615402,0.247446,0.168090,0.078368,0.629851,0.232997,0.168090,0.508698,0.203276,0.200388,0.194265,0.173397,0.203479,0.208561,0.163576,0.192186,0.195743,0.196602,0.176540,0.217619,0.134035,0.178715,0.194042,0.000000,0.208010,18.242986,1610612752,25.0,70.0,3.0,11.0,19.0,24.0,14.0,23.0,37.0,14.0,6.0,4.0,22.0,30.0,72.0,240.000000,12.0,15.0,4.0,22.0,5.0,80.922299,114.464688,-33.537868,0.163246,0.523610,11.026556,0.056220,0.147483,0.091563,19.763500,0.372955,0.436562,0.193970,86.879031,88.699676,43.962361,0.039403,0.377483,0.365924,0.247518,0.598126,0.458272,0.160368,0.266661,0.000000,0.857836,0.142164,0.650577,0.241035,0.057733,0.039143,0.257106,0.165235,0.409507,0.518244,0.447172,0.197778,0.000000,0.559933,0.405484,0.108844,0.466333,0.213520,0.203724,0.197778,0.193515,0.199331,0.190465,0.232461,0.204200,0.204153,0.200857,0.197202,0.196856,0.199583,0.160243,0.192422,0.000000,0.201207,-14.930903
2,0020000002,1610612739,32,78,2,7,20,32,11,41,52,16,5,8,19,27,86,240.000000,12,12,14,36,8,87.118465,82.284514,4.836236,0.135260,0.953071,12.727431,0.043157,0.154742,0.099091,13.891264,0.403829,0.477510,0.197340,99.760802,99.597600,55.404514,0.027378,0.423046,0.418163,0.189245,0.385467,0.306368,0.150790,0.226623,0.000000,0.905348,0.071110,0.619452,0.225391,0.042091,0.151227,0.250680,0.134511,0.394061,0.380781,0.531441,0.226319,0.000000,0.404284,0.507939,0.179271,0.558568,0.200988,0.201629,0.113160,0.180712,0.189883,0.188048,0.223730,0.215432,0.215471,0.206409,0.202678,0.200235,0.161342,0.223420,0.197098,0.000000,0.194632,4.139722,1610612751,31.0,85.0,3.0,10.0,17.0,26.0,12.0,35.0,47.0,24.0,9.0,8.0,12.0,31.0,82.0,240.000000,21.0,13.0,9.0,42.0,8.0,83.457417,86.645424,-3.170028,0.186321,1.655972,19.164549,0.044377,0.128634,0.084390,9.645229,0.334428,0.403052,0.190604,99.760810,98.798017,59.042292,0.112319,0.383964,0.309240,0.149999,0.421320,0.418921,0.191348,0.243931,0.000000,0.892640,0.107360,0.589287,0.177226,0.068950,0.074612,0.329879,0.171267,0.412061,0.623859,0.250308,0.227153,0.000000,0.623859,0.250308,0.129859,0.680444,0.195359,0.199699,0.140674,0.162797,0.207021,0.210566,0.241208,0.196126,0.197293,0.200915,0.151191,0.198521,0.187091,0.206165,0.210120,0.000000,0.192918,-2.137222
3,0020000002,1610612751,31,85,3,10,17,26,12,35,47,24,9,8,12,31,82,240.000000,21,13,9,42,8,83.457417,86.645424,-3.170028,0.186321,1.655972,19.164549,0.044377,0.128634,0.084390,9.645229,0.334428,0.403052,0.190604,99.760810,98.798017,59.042292,0.112319,0.383964,0.309240,0.149999,0.421320,0.418921,0.191348,0.243931,0.000000,0.892640,0.107360,0.589287,0.177226,0.068950,0.074612,0.329879,0.171267,0.412061,0.623859,0.250308,0.227153,0.000000,0.623859,0.250308,0.129859,0.680444,0.195359,0.199699,0.140674,0.162797,0.207021,0.210566,0.241208,0.196126,0.197293,0.200915,0.151191,0.198521,0.187091,0.206165,0.210120,0.000000,0.192918,-2.137222,1610612739,32.0,78.0,2.0,7.0,20.0,32.0,11.0,41.0,52.0,16.0,5.0,8.0,19.0,27.0,86.0,240.000000,12.0,12.0,14.0,36.0,8.0,87.118465,82.284514,4.836236,0.135260,0.953071,12.727431,0.043157,0.154742,0.099091,13.891264,0.403829,0.477510,0.197340,99.760802,99.597600,55.404514,0.027378,0.423046,0.418163,0.189245,0.385467,0.306368,0.150790,0.226623,0.000000,0.905348,0.071110,0.619452,0.225391,0.042091,0.151227,0.250680,0.134511,0.394061,0.380781,0.531441,0.226319,0.000000,0.404284,0.507939,0.179271,0.558568,0.200988,0.201629,0.113160,0.180712,0.189883,0.188048,0.223730,0.215432,0.215471,0.206409,0.202678,0.200235,0.161342,0.223420,0.197098,0.000000,0.194632,4.139722
4,0020000003,1610612753,34,79,6,16,23,33,8,29,37,20,10,9,15,24,97,240.000000,28,9,19,32,1,98.736875,86.636882,12.099993,0.142503,0.857986,12.904542,0.031709,0.133742,0.081268,11.997660,0.475912,0.520254,0.200260,100.539295,98.899090,61.198889,0.118825,0.472056,0.423020,0.148499,0.486995,0.336534,0.267238,0.238280,0.000000,0.799790,0.200210,0.571690,0.237194,0.199434,0.245441,0.229067,0.346846,0.334358,0.459721,0.398473,0.403889,0.000000,0.606531,0.371316,0.186988,0.685047,0.200331,0.201844,0.229832,0.189043,0.227233,0.227924,0.167742,0.196079,0.201831,0.197763,0.182205,0.192654,0.169992,0.065000,0.193451,0.000000,0.204198,7.283056,1610612764,33.0,72.0,4.0,7.0,16.0,24.0,9.0,35.0,44.0,20.0,6.0,1.0,26.0,28.0,86.0,240.000000,15.0,12.0,14.0,42.0,9.0,87.675576,98.295687,-10.619472,0.149045,0.627285,14.817028,0.042904,0.148099,0.098173,19.670639,0.520195,0.553401,0.194765,100.541349,98.401342,53.393403,0.101201,0.485589,0.342879,0.267129,0.470513,0.418830,0.148780,0.185661,0.000000,0.916404,0.083596,0.632414,0.206632,0.148603,0.156626,0.189113,0.165165,0.425926,0.502342,0.467588,0.432986,0.000000,0.600256,0.369674,0.276597,0.604405,0.194938,0.201348,0.157969,0.160486,0.177851,0.170195,0.210115,0.209455,0.210824,0.194940,0.196138,0.138369,0.109583,0.186508,0.215050,0.000000,0.198386,-6.894514
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66196,0052400131,1610612758,41,89,13,33,11,15,15,29,44,23,6,4,18,19,106,240.000000,15,13,15,40,8,110.123410,123.832694,-13.692986,0.144001,0.915579,16.246007,0.061248,0.139456,0.094800,13.410542,0.553654,0.568678,0.196805,96.519477,96.900852,64.197361,0.078930,0.533497,0.168455,0.181755,0.589886,0.321300,0.106123,0.242713,1.925417,0.579009,0.412449,0.498701,0.103705,0.374451,0.147024,0.093555,0.120819,0.394996,0.601385,0.356601,0.625625,0.137917,0.614244,0.352284,0.337209,0.444622,0.198443,0.199547,0.199186,0.197010,0.199987,0.198947,0.220836,0.204731,0.202397,0.198671,0.194704,0.193650,0.140420,0.176580,0.204741,0.201187,0.198282,-14.351250,1610612742,41.0,83.0,14.0,28.0,24.0,26.0,10.0,31.0,41.0,29.0,9.0,8.0,9.0,15.0,120.0,240.000000,18.0,4.0,14.0,40.0,4.0,123.867549,110.768076,13.093542,0.179320,1.234705,23.328986,0.043102,0.126057,0.088669,7.650514,0.614891,0.653447,0.190092,96.519280,96.700401,52.394028,0.120096,0.586034,0.319399,0.106316,0.531757,0.167544,0.181331,0.320657,2.229653,0.660342,0.331116,0.484243,0.140879,0.266205,0.119458,0.173500,0.127531,0.343317,0.539994,0.384173,0.710417,0.000000,0.693429,0.230738,0.371341,0.690868,0.189465,0.197248,0.188922,0.192500,0.200256,0.200080,0.177569,0.202057,0.201182,0.211608,0.180998,0.195077,0.211063,0.166207,0.202276,0.192422,0.188871,13.047708
66197,0052400201,1610612737,44,102,16,47,10,12,11,33,44,30,12,3,9,18,114,265.016667,21,14,22,56,8,108.972216,113.769398,-4.786328,0.170940,1.701450,19.786856,0.038220,0.132929,0.082033,6.828665,0.533646,0.548288,0.194796,96.088083,96.542768,70.793032,0.094415,0.515043,0.115509,0.094355,0.582867,0.189826,0.139047,0.283225,2.338658,0.528556,0.471444,0.478198,0.000000,0.421953,0.212341,0.069536,0.130952,0.478198,0.664189,0.249212,0.692064,0.218571,0.717321,0.252367,0.401740,0.302049,0.201907,0.198260,0.191661,0.199505,0.163951,0.180012,0.223868,0.200502,0.200689,0.193867,0.160034,0.206388,0.145900,0.193684,0.193772,0.193633,0.199234,-6.091126,1610612748,48.0,96.0,16.0,42.0,11.0,18.0,13.0,41.0,54.0,33.0,4.0,8.0,14.0,15.0,123.0,265.000000,18.0,17.0,14.0,48.0,3.0,114.115346,109.194151,4.941660,0.175512,1.914025,21.394906,0.052826,0.136744,0.098506,8.743547,0.602740,0.610614,0.188164,96.091468,96.271151,74.389497,0.108900,0.582882,0.188123,0.140615,0.511179,0.117131,0.094058,0.210104,2.789245,0.569122,0.430878,0.531708,0.131616,0.389409,0.104841,0.078883,0.158831,0.400093,0.679972,0.320028,0.594560,0.156132,0.689231,0.310769,0.317894,0.399580,0.200367,0.200068,0.199439,0.200160,0.203244,0.198173,0.193693,0.197318,0.198007,0.203462,0.175619,0.211259,0.195655,0.227722,0.201947,0.191826,0.199943,7.759057
66198,0052400201,1610612748,48,96,16,42,11,18,13,41,54,33,4,8,14,15,123,265.000000,18,17,14,48,3,114.115346,109.194151,4.941660,0.175512,1.914025,21.394906,0.052826,0.136744,0.098506,8.743547,0.602740,0.610614,0.188164,96.091468,96.271151,74.389497,0.108900,0.582882,0.188123,0.140615,0.511179,0.117131,0.094058,0.210104,2.789245,0.569122,0.430878,0.531708,0.131616,0.389409,0.104841,0.078883,0.158831,0.400093,0.679972,0.320028,0.594560,0.156132,0.689231,0.310769,0.317894,0.399580,0.200367,0.200068,0.199439,0.200160,0.203244,0.198173,0.193693,0.197318,0.198007,0.203462,0.175619,0.211259,0.195655,0.227722,0.201947,0.191826,0.199943,7.759057,1610612737,44.0,102.0,16.0,47.0,10.0,12.0,11.0,33.0,44.0,30.0,12.0,3.0,9.0,18.0,114.0,265.016667,21.0,14.0,22.0,56.0,8.0,108.972216,113.769398,-4.786328,0.170940,1.701450,19.786856,0.038220,0.132929,0.082033,6.828665,0.533646,0.548288,0.194796,96.088083,96.542768,70.793032,0.094415,0.515043,0.115509,0.094355,0.582867,0.189826,0.139047,0.283225,2.338658,0.528556,0.471444,0.478198,0.000000,0.421953,0.212341,0.069536,0.130952,0.478198,0.664189,0.249212,0.692064,0.218571,0.717321,0.252367,0.401740,0.302049,0.201907,0.198260,0.191661,0.199505,0.163951,0.180012,0.223868,0.200502,0.200689,0.193867,0.160034,0.206388,0.145900,0.193684,0.193772,0.193633,0.199234,-6.091126
66199,0052400211,1610612742,41,87,12,38,12,16,7,29,36,25,9,8,16,17,106,239.983333,14,15,15,44,4,103.971838,117.104361,-13.146712,0.159645,1.043291,21.438058,0.028121,0.109295,0.071448,14.196291,0.505059,0.518344,0.194360,102.820733,102.200355,55.776790,0.083048,0.540618,0.184078,0.155320,0.534614,0.150467,0.117294,0.351484,1.775957,0.589597,0.410403,0.375406,0.089519,0.288293,0.120119,0.077834,0.102521,0.286029,0.431148,0.256678,0.465397,0.199927,0.498200,0.243395,0.324056,0.404056,0.199455,0.198674,0.234511,0.197563,0.188766,0.193288,0.179929,0.199788,0.199410,0.199269,0.194797,0.201698,0.189836,0.148746,0.180069,0.178183,0.199691,-8.414820,1610612763,47.0,100.0,13.0,31.0,13.0,15.0,16.0,34.0,50.0,30.0,8.0,4.0,10.0,17.0,120.0,240.000000,24.0,15.0,19.0,60.0,8.0,118.571125,105.071556,13.509528,0.154672,0.823437,19.079396,0.059757,0.149789,0.100197,4.889924,0.566430,0.582027,0.191697,102.820601,101.299056,62.138194,0.109814,0.532094,0.153846,0.116233,0.542366,0.187143,0.155200,0.164587,2.136944,0.650762,0.334099,0.569661,0.056488,0.328575,0.226652,0.078919,0.205619,0.513310,0.620063,0.349659,0.682240,0.087343,0.648875,0.320847,0.348328,0.327988,0.197052,0.199753,0.185188,0.203577,0.155673,0.161807,0.197832,0.203155,0.201390,0.197460,0.149565,0.187630,0.217161,0.174559,0.196685,0.173665,0.201920,11.408611
66200,0052400211,1610612763,47,100,13,31,13,15,16,34,50,30,8,4,10,17,120,240.000000,24,15,19,60,8,118.571125,105.071556,13.509528,0.154672,0.823437,19.079396,0.059757,0.149789,0.100197,4.889924,0.566430,0.582027,0.191697,102.820601,101.299056,62.138194,0.109814,0.532094,0.153846,0.116233,0.542366,0.187143,0.155200,0.164587,2.136944,0.650762,0.334099,0.569661,0.056488,0.328575,0.226652,0.078919,0.205619,0.513310,0.620063,0.349659,0.682240,0.087343,0.648875,0.320847,0.348328,0.327988,0.197052,0.199753,0.185188,0.203577,0.155673,0.161807,0.197832,0.203155,0.201390,0.197460,0.149565,0.187630,0.217161,0.174559,0.196685,0.173665,0.201920,11.408611,1610612742,41.0,87.0,12.0,38.0,12.0,16.0,7.0,29.0,36.0,25.0,9.0,8.0,16.0,17.0,106.0,239.983333,14.0,15.0,15.0,44.0,4.0,103.971838,117.104361,-13.146712,0.159645,1.043291,21.438058,0.028121,0.109295,0.071448,14.196291,0.505059,0.518344,0.194360,102.820733,102.200355,55.776790,0.083048,0.540618,0.184078,0.155320,0.534614,0.150467,0.117294,0.351484,1.775957,0.589597,0.410403,0.375406,0.089519,0.288293,0.120119,0.077834,0.102521,0.286029,0.431148,0.256678,0.465397,0.199927,0.498200,0.243395,0.324056,0.404056,0.199455,0.198674,0.234511,0.197563,0.188766,0.193288,0.179929,0.199788,0.199410,0.199269,0.194797,0.201698,0.189836,0.148746,0.180069,0.178183,0.199691,-8.414820

In [55]:
# Assurer le format datetime pour GAME_DATE
df_games['GAME_DATE'] = pd.to_datetime(df_games['GAME_DATE'])



# Merge avec les infos de match (MATCHUP, SEASON)
match_dataset = match_dataset.merge(
    df_games[['GAME_ID', 'TEAM_ID', 'MATCHUP', 'SEASON','GAME_DATE']],
    on=['GAME_ID', 'TEAM_ID'],
    how='left'
)

In [56]:

print("match_dataset after merge")
display(match_dataset)

match_dataset after merge

,GAME_ID,TEAM_ID,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,points_traditional,MINUTES_PLAYED,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,blocksAgainst_misc,offensiveRating_advanced,defensiveRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,threePointersPercentage_traditional,freeThrowsPercentage_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage,plusMinusPoints_traditional,OPP_TEAM_ID,OPP_fieldGoalsMade_traditional,OPP_fieldGoalsAttempted_traditional,OPP_threePointersMade_traditional,OPP_threePointersAttempted_traditional,OPP_freeThrowsMade_traditional,OPP_freeThrowsAttempted_traditional,OPP_reboundsOffensive_traditional,OPP_reboundsDefensive_traditional,OPP_reboundsTotal_traditional,OPP_assists_traditional,OPP_steals_traditional,OPP_blocks_traditional,OPP_turnovers_traditional,OPP_foulsPersonal_traditional,OPP_points_traditional,OPP_MINUTES_PLAYED,OPP_pointsOffTurnovers_misc,OPP_pointsSecondChance_misc,OPP_pointsFastBreak_misc,OPP_pointsPaint_misc,OPP_blocksAgainst_misc,OPP_offensiveRating_advanced,OPP_defensiveRating_advanced,OPP_netRating_advanced,OPP_assistPercentage_advanced,OPP_assistToTurnover_advanced,OPP_assistRatio_advanced,OPP_offensiveReboundPercentage_advanced,OPP_defensiveReboundPercentage_advanced,OPP_reboundPercentage_advanced,OPP_turnoverRatio_advanced,OPP_effectiveFieldGoalPercentage_advanced,OPP_trueShootingPercentage_advanced,OPP_usagePercentage_advanced,OPP_estimatedPace_advanced,OPP_pace_advanced,OPP_possessions_advanced,OPP_PIE_advanced,OPP_effectiveFieldGoalPercentage_fourfactors,OPP_freeThrowAttemptRate_fourfactors,OPP_teamTurnoverPercentage_fourfactors,OPP_oppEffectiveFieldGoalPercentage_fourfactors,OPP_oppFreeThrowAttemptRate_fourfactors,OPP_oppTeamTurnoverPercentage_fourfactors,OPP_oppOffensiveReboundPercentage_fourfactors,OPP_foulsDrawn_misc,OPP_percentageFieldGoalsAttempted2pt_scoring,OPP_percentageFieldGoalsAttempted3pt_scoring,OPP_percentagePoints2pt_scoring,OPP_percentagePointsMidrange2pt_scoring,OPP_percentagePoints3pt_scoring,OPP_percentagePointsFastBreak_scoring,OPP_percentagePointsFreeThrow_scoring,OPP_percentagePointsOffTurnovers_scoring,OPP_percentagePointsPaint_scoring,OPP_percentageAssisted2pt_scoring,OPP_percentageUnassisted2pt_scoring,OPP_percentageAssisted3pt_scoring,OPP_percentageUnassisted3pt_scoring,OPP_percentageAssistedFGM_scoring,OPP_percentageUnassistedFGM_scoring,OPP_threePointersPercentage_traditional,OPP_freeThrowsPercentage_traditional,OPP_percentageFieldGoalsMade_usage,OPP_percentageFieldGoalsAttempted_usage,OPP_percentageThreePointersMade_usage,OPP_percentageThreePointersAttempted_usage,OPP_percentageFreeThrowsMade_usage,OPP_percentageFreeThrowsAttempted_usage,OPP_percentageReboundsOffensive_usage,OPP_percentageReboundsDefensive_usage,OPP_percentageReboundsTotal_usage,OPP_percentageAssists_usage,OPP_percentageTurnovers_usage,OPP_percentageSteals_usage,OPP_percentageBlocks_usage,OPP_percentageBlocksAllowed_usage,OPP_percentagePersonalFouls_usage,OPP_percentagePersonalFoulsDrawn_usage,OPP_percentagePoints_usage,OPP_plusMinusPoints_traditional,MATCHUP,SEASON,GAME_DATE
0,0020000001,1610612752,25,70,3,11,19,24,14,23,37,14,6,4,22,30,72,240.000000,12,15,4,22,5,80.922299,114.464688,-33.537868,0.163246,0.523610,11.026556,0.056220,0.147483,0.091563,19.763500,0.372955,0.436562,0.193970,86.879031,88.699676,43.962361,0.039403,0.377483,0.365924,0.247518,0.598126,0.458272,0.160368,0.266661,0.000000,0.857836,0.142164,0.650577,0.241035,0.057733,0.039143,0.257106,0.165235,0.409507,0.518244,0.447172,0.197778,0.000000,0.559933,0.405484,0.108844,0.466333,0.213520,0.203724,0.197778,0.193515,0.199331,0.190465,0.232461,0.204200,0.204153,0.200857,0.197202,0.196856,0.199583,0.160243,0.192422,0.000000,0.201207,-14.930903,1610612755,38.0,66.0,3.0,8.0,22.0,30.0,8.0,29.0,37.0,27.0,10.0,5.0,13.0,24.0,101.0,240.000000,26.0,9.0,10.0,36.0,4.0,113.678208,80.924167,32.729556,0.182441,1.177822,20.832340,0.049657,0.117050,0.092804,12.917368,0.562437,0.596134,0.194474,86.879235,88.899378,50.502014,0.160855,0.601599,0.469504,0.161353,0.382886,0.361238,0.246772,0.319077,0.000000,0.839428,0.116266,0.644489,0.293966,0.049281,0.125861,0.169078,0.233654,0.350402,0.615402,0.247446,0.168090,0.078368,0.629851,0.232997,0.168090,0.508698,0.203276,0.200388,0.194265,0.173397,0.203479,0.208561,0.163576,0.192186,0.195743,0.196602,0.176540,0.217619,0.134035,0.178715,0.194042,0.000000,0.208010,18.242986,NYK vs. PHI,2000-01,2000-10-31
1,0020000001,1610612755,38,66,3,8,22,30,8,29,37,27,10,5,13,24,101,240.000000,26,9,10,36,4,113.678208,80.924167,32.729556,0.182441,1.177822,20.832340,0.049657,0.117050,0.092804,12.917368,0.562437,0.596134,0.194474,86.879235,88.899378,50.502014,0.160855,0.601599,0.469504,0.161353,0.382886,0.361238,0.246772,0.319077,0.000000,0.839428,0.116266,0.644489,0.293966,0.049281,0.125861,0.169078,0.233654,0.350402,0.615402,0.247446,0.168090,0.078368,0.629851,0.232997,0.168090,0.508698,0.203276,0.200388,0.194265,0.173397,0.203479,0.208561,0.163576,0.192186,0.195743,0.196602,0.176540,0.217619,0.134035,0.178715,0.194042,0.000000,0.208010,18.242986,1610612752,25.0,70.0,3.0,11.0,19.0,24.0,14.0,23.0,37.0,14.0,6.0,4.0,22.0,30.0,72.0,240.000000,12.0,15.0,4.0,22.0,5.0,80.922299,114.464688,-33.537868,0.163246,0.523610,11.026556,0.056220,0.147483,0.091563,19.763500,0.372955,0.436562,0.193970,86.879031,88.699676,43.962361,0.039403,0.377483,0.365924,0.247518,0.598126,0.458272,0.160368,0.266661,0.000000,0.857836,0.142164,0.650577,0.241035,0.057733,0.039143,0.257106,0.165235,0.409507,0.518244,0.447172,0.197778,0.000000,0.559933,0.405484,0.108844,0.466333,0.213520,0.203724,0.197778,0.193515,0.199331,0.190465,0.232461,0.204200,0.204153,0.200857,0.197202,0.196856,0.199583,0.160243,0.192422,0.000000,0.201207,-14.930903,PHI @ NYK,2000-01,2000-10-31
2,0020000002,1610612739,32,78,2,7,20,32,11,41,52,16,5,8,19,27,86,240.000000,12,12,14,36,8,87.118465,82.284514,4.836236,0.135260,0.953071,12.727431,0.043157,0.154742,0.099091,13.891264,0.403829,0.477510,0.197340,99.760802,99.597600,55.404514,0.027378,0.423046,0.418163,0.189245,0.385467,0.306368,0.150790,0.226623,0.000000,0.905348,0.071110,0.619452,0.225391,0.042091,0.151227,0.250680,0.134511,0.394061,0.380781,0.531441,0.226319,0.000000,0.404284,0.507939,0.179271,0.558568,0.200988,0.201629,0.113160,0.180712,0.189883,0.188048,0.223730,0.215432,0.215471,0.206409,0.202678,0.200235,0.161342,0.223420,0.197098,0.000000,0.194632,4.139722,1610612751,31.0,85.0,3.0,10.0,17.0,26.0,12.0,35.0,47.0,24.0,9.0,8.0,12.0,31.0,82.0,240.000000,21.0,13.0,9.0,42.0,8.0,83.457417,86.645424,-3.170028,0.186321,1.655972,19.164549,0.044377,0.128634,0.084390,9.645229,0.334428,0.403052,0.190604,99.760810,98.798017,59.042292,0.112319,0.383964,0.309240,0.149999,0.421320,0.418921,0.191348,0.243931,0.000000,0.892640,0.107360,0.589287,0.177226,0.068950,0.074612,0.329879,0.171267,0.412061,0.623859,0.250308,0.227153,0.000000,0.623859,0.250308,0.129859,0.680444,0.195359,0.199699,0.140674,0.162797,0.207021,0.210566,0.241208,0.196126,0.197293,0.200915,0.151191,0.198521,0.187091,0.206165,0.210120,0.000000,0.192918,-2.137222,CLE @ NJN,2000-01,2000-10-31
3,0020000002,1610612751,31,85,3,10,17,26,12,35,47,24,9,8,12,31,82,240.000000,21,13,9,42,8,83.457417,86.645424,-3.170028,0.186321,1.655972,19.164549,0.044377,0.128634,0.084390,9.645229,0.334428,0.403052,0.190604,99.760810,98.798017,59.042292,0.112319,0.383964,0.309240,0.149999,0.421320,0.418921,0.191348,0.243931,0.000000,0.892640,0.107360,0.589287,0.177226,0.068950,0.074612,0.329879,0.171267,0.412061,0.623859,0.250308,0.227153,0.000000,0.623859,0.250308,0.129859,0.680444,0.195359,0.199699,0.140674,0.162797,0.207021,0.210566,0.241208,0.196126,0.197293,0.200915,0.151191,0.198521,0.187091,0.206165,0.210120,0.000000,0.192918,-2.137222,1610612739,32.0,78.0,2.0,7.0,20.0,32.0,11.0,41.0,52.0,16.0,5.0,8.0,19.0,27.0,86.0,240.000000,12.0,12.0,14.0,36.0,8.0,87.118465,82.284514,4.836236,0.135260,0.953071,12.727431,0.043157,0.154742,0.099091,13.891264,0.403829,0.477510,0.197340,99.760802,99.597600,55.404514,0.027378,0.423046,0.418163,0.189245,0.385467,0.306368,0.150790,0.226623,0.000000,0.905348,0.071110,0.619452,0.225391,0.042091,0.151227,0.250680,0.134511,0.394061,0.380781,0.531441,0.226319,0.000000,0.404284,0.507939,0.179271,0.558568,0.200988,0.201629,0.113160,0.180712,0.189883,0.188048,0.223730,0.215432,0.215471,0.206409,0.202678,0.200235,0.161342,0.223420,0.197098,0.000000,0.194632,4.139722,NJN vs. CLE,2000-01,2000-10-31
4,0020000003,1610612753,34,79,6,16,23,33,8,29,37,20,10,9,15,24,97,240.000000,28,9,19,32,1,98.736875,86.636882,12.099993,0.142503,0.857986,12.904542,0.031709,0.133742,0.081268,11.997660,0.475912,0.520254,0.200260,100.539295,98.899090,61.198889,0.118825,0.472056,0.423020,0.148499,0.486995,0.336534,0.267238,0.238280,0.000000,0.799790,0.200210,0.571690,0.237194,0.199434,0.245441,0.229067,0.346846,0.334358,0.459721,0.398473,0.403889,0.000000,0.606531,0.371316,0.186988,0.685047,0.200331,0.201844,0.229832,0.189043,0.227233,0.227924,0.167742,0.196079,0.201831,0.197763,0.182205,0.192654,0.169992,0.065000,0.193451,0.000000,0.204198,7.283056,1610612764,33.0,72.0,4.0,7.0,16.0,24.0,9.0,35.0,44.0,20.0,6.0,1.0,26.0,28.0,86.0,240.000000,15.0,12.0,14.0,42.0,9.0,87.675576,98.295687,-10.619472,0.149045,0.627285,14.817028,0.042904,0.148099,0.098173,19.670639,0.520195,0.553401,0.194765,100.541349,98.401342,53.393403,0.101201,0.485589,0.342879,0.267129,0.470513,0.418830,0.148780,0.185661,0.000000,0.916404,0.083596,0.632414,0.206632,0.148603,0.156626,0.189113,0.165165,0.425926,0.502342,0.467588,0.432986,0.000000,0.600256,0.369674,0.276597,0.604405,0.194938,0.201348,0.157969,0.160486,0.177851,0.170195,0.210115,0.209455,0.210824,0.194940,0.196138,0.138369,0.109583,0.186508,0.215050,0.000000,0.198386,-6.894514,ORL vs. WAS,2000-01,2000-10-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76342,0052400201,1610612748,48,96,16,42,11,18,13,41,54,33,4,8,14,15,123,265.000000,18,17,14,48,3,114.115346,109.194151,4.941660,0.175512,1.914025,21.394906,0.052826,0.136744,0.098506,8.743547,0.602740,0.610614,0.188164,96.091468,96.271151,74.389497,0.108900,0.582882,0.188123,0.140615,0.511179,0.117131,0.094058,0.210104,2.789245,0.569122,0.430878,0.531708,0.131616,0.389409,0.104841,0.078883,0.158831,0.400093,0.679972,0.320028,0.594560,0.156132,0.689231,0.310769,0.317894,0.399580,0.200367,0.200068,0.199439,0.200160,0.203244,0.198173,0.193693,0.197318,0.198007,0.203462,0.175619,0.211259,0.195655,0.227722,0.201947,0.191826,0.199943,7.759057,1610612737,44.0,102.0,16.0,47.0,10.0,12.0,11.0,33.0,44.0,30.0,12.0,3.0,9.0,18.0,114.0,265.016667,21.0,14.0,22.0,56.0,8.0,108.972216,113.769398,-4.786328,0.170940,1.701450,19.786856,0.038220,0.132929,0.082033,6.828665,0.533646,0.548288,0.194796,96.088083,96.542768,70.793032,0.094415,0.515043,0.115509,0.094355,0.582867,0.189826,0.139047,0.283225,2.338658,0.528556,0.471444,0.478198,0.000000,0.421953,0.212341,0.069536,0.130952,0.478198,0.664189,0.249212,0.692064,0.218571,0.717321,0.252367,0.401740,0.302049,0.201907,0.198260,0.191661,0.199505,0.163951,0.180012,0.223868,0.200502,0.200689,0.193867,0.160034,0.206388,0.145900,0.193684,0.193772,0.193633,0.199234,-6.091126,MIA @ ATL,2024-25,2025-04-18
76343,0052400211,1610612742,41,87,12,38,12,16,7,29,36,25,9,8,16,17,106,239.983333,14,15,15,44,4,103.971838,117.104361,-13.146712,0.159645,1.043291,21.438058,0.028121,0.109295,0.071448,14.196291,0.505059,0.518344,0.194360,102.820733,102.200355,55.776790,0.083048,0.540618,0.184078,0.155320,0.534614,0.150467,0.117294,0.351484,1.775957,0.589597,0.410403,0.375406,0.089519,0.288293,0.120119,0.077834,0.102521,0.286029,0.431148,0.256678,0.465397,0.199927,0.498200,0.243395,0.324056,0.404056,0.199455,0.198674,0.234511,0.197563,0.188766,0.193288,0.179929,0.199788,0.199410,0.199269,0.194797,0.201698,0.189836,0.148746,0.180069,0.178183,0.199691,-8.414820,1610612763,47.0,100.0,13.0,31.0,13.0,15.0,16.0,34.0,50.0,30.0,8.0,4.0,10.0,17.0,120.0,240.000000,24.0,15.0,19.0,60.0,8.0,118.571125,105.071556,13.509528,0.154672,0.823437,19.079396,0.059757,0.149789,0.100197,4.889924,0.566430,0.582027,0.191697,102.820601,101.299056,62.138194,0.109814,0.532094,0.153846,0.116233,0.542366,0.187143,0.155200,0.164587,2.136944,0.650762,0.334099,0.569661,0.056488,0.328575,0.226652,0.078919,0.205619,0.513310,0.620063,0.349659,0.682240,0.087343,0.648875,0.320847,0.348328,0.327988,0.197052,0.199753,0.185188,0.203577,0.155673,0.161807,0.197832,0.203155,0.201390,0.197460,0.149565,0.187630,0.217161,0.174559,0.196685,0.173665,0.201920,11.408611,DAL @ MEM,2024-25,2025-04-18
76344,0052400211,1610612742,41,87,12,38,12,16,7,29,36,25,9,8,16,17,106,239.983333,14,15,15,44,4,103.971838,117.104361,-13.146712,0.159645,1.043291,21.438058,0.028121,0.109295,0.071448,14.196291,0.505059,0.518344,0.194360,102.820733,102.200355,55.776790,0.083048,0.540618,0.184078,0.155320,0.534614,0.150467,0.117294,0.351484,1.775957,0.589597,0.410403,0.375406,0.089519,0.288293,0.120119,0.077834,0.102521,0.286029,0.431148,0.256678,0.465397,0.199927,0.498200,0.243395,0.324056,0.404056,0.199455,0.198674,0.234511,0.197563,0.188766,0.193288,0.179929,0.199788,0.199410,0.199269,0.194797,0.201698,0.189836,0.148746,0.180069,0.178183,0.199691,-8.414820,1610612763,47.0,100.0,13.0,31.0,13.0,15.0,16.0,34.0,50.0,30.0,8.0,4.0,10.0,17.0,120.0,240.000000,24.0,15.0,19.0,60.0,8.0,118.571125,105.071556,13.509528,0.154672,0.823437,19.079396,0.059757,0.149789,0.100197,4.889924,0.566430,0.582027,0.191697,102.820601,101.299056,62.138194,0.109814,0.532094,0.153846,0.116233,0.542366,0.187143,0.155200,0.164587,2.136944,0.650762,0.334099,0.569661,0.056488,0.328575,0.226652,0.078919,0.205619,0.513310,0.620063,0.349659,0.682240,0.087343,0.648875,0.320847,0.348328,0.327988,0.197052,0.199753,0.185188,0.203577,0.155673,0.161807,0.197832,0.203155,0.201390,0.197460,0.149565,0.187630,0.217161,0.174559,0.196685,0.173665,0.201920,11.408611,DAL @ MEM,2024-25,2025-04-18
76345,0052400211,1610612763,47,100,13,31,13,15,16,34,50,30,8,4,10,17,120,240.000000,24,15,19,60,8,118.571125,105.071556,13.509528,0.154672,0.823437,19.079396,0.059757,0.149789,0.100197,4.889924,0.566430,0.582027,0.191697,102.820601,101.299056,62.138194,0.109814,0.532094,0.153846,0.116233,0.542366,0.187143,0.155200,0.164587,2.136944,0.650762,0.334099,0.569661,0.056488,0.328575,0.226652,0.078919,0.205619,0.513310,0.620063,0.349659,0.682240,0.087343,0.648875,0.320847,0.348328,0.327988,0.197052,0.199753,0.185188,0.203577,0.155673,0.161807,0.197832,0.203155,0.201390,0.197460,0.149565,0.187630,0.217161,0.174559,0.196685,0.173665,0.201920,11.408611,1610612742,41.0,87.0,12.0,38.0,12.0,16.0,7.0,29.0,36.0,25.0,9.0,8.0,16.0,17.0,106.0,239.983333,14.0,15.0,15.0,44.0,4.0,103.971838,117.104361,-13.146712,0.159645,1.043291,21.438058,0.028121,0.109295,0.071448,14.196291,0.505059,0.518344,0.194360,102.820733,102.200355,55.776790,0.083048,0.540618,0.184078,0.155320,0.534614,0.150467,0.117294,0.351484,1.775957,0.589597,0.410403,0.375406,0.089519,0.288293,0.120119,0.077834,0.102521,0.286029,0.431148,0.256678,0.465397,0.199927,0.498200,0.243395,0.324056,0.404056,0.199455,0.198674,0.234511,0.197563,0.188766,0.193288,0.179929,0.199788,0.199410,0.199269,0.194797,0.201698,0.189836,0.148746,0.180069,0.178183,0.199691,-8.414820,MEM vs. DAL,2024-25,2025-04-18
76346,0052400211,1610612763,47,100,13,31,13,15,16,34,50,30,8,4,10,17,120,240.000000,24,15,19,60,8,118.571125,105.071556,13.509528,0.154672,0.823437,19.079396,0.059757,0.149789,0.100197,4.889924,0.566430,0.582027,0.191697,102.820601,101.299056,62.138194,0.109814,0.532094,0.153846,0.116233,0.542366,0.187143,0.155200,0.164587,2.136944,0.650762,0.334099,0.569661,0.056488,0.328575,0.226652,0.078919,0.205619,0.513310,0.620063,0.349659,0.682240,0.087343,0.648875,0.320847,0.348328,0.327988,0.197052,0.199753,0.185188,0.203577,0.155673,0.161807,0.197832,0.203155,0.201390,0.197460,0.149565,0.187630,0.217161,0.174559,0.196685,0.173665,0.201920,11.408611,1610612742,41.0,87.0,12.0,38.0,12.0,16.0,7.0,29.0,36.0,25.0,9.0,8.0,16.0,17.0,106.0,239.983333,14.0,15.0,15.0,44.0,4.0,103.971838,117.104361,-13.146712,0.159645,1.043291,21.438058,0.028121,0.109295,0.071448,14.196291,0.505059,0.518344,0.194360,102.820733,102.200355,55.776790,0.083048,0.540618,0.184078,0.155320,0.534614,0.150467,0.117294,0.351484,1.775957,0.589597,0.410403,0.375406,0.089519,0.288293,0.120119,0.077834,0.102521,0.286029,0.431148,0.256678,0.465397,0.199927,0.498200,0.243395,0.324056,0.404056,0.199455,0.198674,0.234511,0.197563,0.188766,0.193288,0.179929,0.199788,0.199410,0.199269,0.194797,0.201698,0.189836,0.148746,0.180069,0.178183,0.199691,-8.414820,MEM vs. DAL,2024-25,2025-04-18

In [57]:

#display lines with nan values on matchup
print("Lines with NaN in MATCHUP:")
display(match_dataset[match_dataset['MATCHUP'].isna()])

Lines with NaN in MATCHUP:

Empty DataFrame
Columns: [GAME_ID, TEAM_ID, fieldGoalsMade_traditional, fieldGoalsAttempted_traditional, threePointersMade_traditional, threePointersAttempted_traditional, freeThrowsMade_traditional, freeThrowsAttempted_traditional, reboundsOffensive_traditional, reboundsDefensive_traditional, reboundsTotal_traditional, assists_traditional, steals_traditional, blocks_traditional, turnovers_traditional, foulsPersonal_traditional, points_traditional, MINUTES_PLAYED, pointsOffTurnovers_misc, pointsSecondChance_misc, pointsFastBreak_misc, pointsPaint_misc, blocksAgainst_misc, offensiveRating_advanced, defensiveRating_advanced, netRating_advanced, assistPercentage_advanced, assistToTurnover_advanced, assistRatio_advanced, offensiveReboundPercentage_advanced, defensiveReboundPercentage_advanced, reboundPercentage_advanced, turnoverRatio_advanced, effectiveFieldGoalPercentage_advanced, trueShootingPercentage_advanced, usagePercentage_advanced, estimatedPace_advanced, pace_advanced, possessions_advanced, PIE_advanced, effectiveFieldGoalPercentage_fourfactors, freeThrowAttemptRate_fourfactors, teamTurnoverPercentage_fourfactors, oppEffectiveFieldGoalPercentage_fourfactors, oppFreeThrowAttemptRate_fourfactors, oppTeamTurnoverPercentage_fourfactors, oppOffensiveReboundPercentage_fourfactors, foulsDrawn_misc, percentageFieldGoalsAttempted2pt_scoring, percentageFieldGoalsAttempted3pt_scoring, percentagePoints2pt_scoring, percentagePointsMidrange2pt_scoring, percentagePoints3pt_scoring, percentagePointsFastBreak_scoring, percentagePointsFreeThrow_scoring, percentagePointsOffTurnovers_scoring, percentagePointsPaint_scoring, percentageAssisted2pt_scoring, percentageUnassisted2pt_scoring, percentageAssisted3pt_scoring, percentageUnassisted3pt_scoring, percentageAssistedFGM_scoring, percentageUnassistedFGM_scoring, threePointersPercentage_traditional, freeThrowsPercentage_traditional, percentageFieldGoalsMade_usage, percentageFieldGoalsAttempted_usage, percentageThreePointersMade_usage, percentageThreePointersAttempted_usage, percentageFreeThrowsMade_usage, percentageFreeThrowsAttempted_usage, percentageReboundsOffensive_usage, percentageReboundsDefensive_usage, percentageReboundsTotal_usage, percentageAssists_usage, percentageTurnovers_usage, percentageSteals_usage, percentageBlocks_usage, percentageBlocksAllowed_usage, percentagePersonalFouls_usage, percentagePersonalFoulsDrawn_usage, percentagePoints_usage, plusMinusPoints_traditional, OPP_TEAM_ID, OPP_fieldGoalsMade_traditional, OPP_fieldGoalsAttempted_traditional, OPP_threePointersMade_traditional, OPP_threePointersAttempted_traditional, OPP_freeThrowsMade_traditional, OPP_freeThrowsAttempted_traditional, OPP_reboundsOffensive_traditional, OPP_reboundsDefensive_traditional, OPP_reboundsTotal_traditional, OPP_assists_traditional, OPP_steals_traditional, OPP_blocks_traditional, OPP_turnovers_traditional, OPP_foulsPersonal_traditional, OPP_points_traditional, OPP_MINUTES_PLAYED, ...]
Index: []

In [58]:



# Définir si l'équipe joue à domicile
match_dataset['IS_HOME'] = match_dataset['MATCHUP'].str.contains('vs').astype(int)

# Calcul du résultat (win) et écart de points
match_dataset['IS_WIN'] = (match_dataset['points_traditional'] > match_dataset['OPP_points_traditional']).astype(int)
match_dataset['POINT_DIFF'] = match_dataset['points_traditional'] - match_dataset['OPP_points_traditional']

# Conversion GAME_DATE et tri
match_dataset['GAME_DATE'] = pd.to_datetime(match_dataset['GAME_DATE'])
match_dataset = match_dataset.sort_values(['GAME_DATE', 'GAME_ID']).reset_index(drop=True)

In [59]:
match_dataset

,GAME_ID,TEAM_ID,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,points_traditional,MINUTES_PLAYED,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,blocksAgainst_misc,offensiveRating_advanced,defensiveRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,threePointersPercentage_traditional,freeThrowsPercentage_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage,plusMinusPoints_traditional,OPP_TEAM_ID,OPP_fieldGoalsMade_traditional,OPP_fieldGoalsAttempted_traditional,OPP_threePointersMade_traditional,OPP_threePointersAttempted_traditional,OPP_freeThrowsMade_traditional,OPP_freeThrowsAttempted_traditional,OPP_reboundsOffensive_traditional,OPP_reboundsDefensive_traditional,OPP_reboundsTotal_traditional,OPP_assists_traditional,OPP_steals_traditional,OPP_blocks_traditional,OPP_turnovers_traditional,OPP_foulsPersonal_traditional,OPP_points_traditional,OPP_MINUTES_PLAYED,OPP_pointsOffTurnovers_misc,OPP_pointsSecondChance_misc,OPP_pointsFastBreak_misc,OPP_pointsPaint_misc,OPP_blocksAgainst_misc,OPP_offensiveRating_advanced,OPP_defensiveRating_advanced,OPP_netRating_advanced,OPP_assistPercentage_advanced,OPP_assistToTurnover_advanced,OPP_assistRatio_advanced,OPP_offensiveReboundPercentage_advanced,OPP_defensiveReboundPercentage_advanced,OPP_reboundPercentage_advanced,OPP_turnoverRatio_advanced,OPP_effectiveFieldGoalPercentage_advanced,OPP_trueShootingPercentage_advanced,OPP_usagePercentage_advanced,OPP_estimatedPace_advanced,OPP_pace_advanced,OPP_possessions_advanced,OPP_PIE_advanced,OPP_effectiveFieldGoalPercentage_fourfactors,OPP_freeThrowAttemptRate_fourfactors,OPP_teamTurnoverPercentage_fourfactors,OPP_oppEffectiveFieldGoalPercentage_fourfactors,OPP_oppFreeThrowAttemptRate_fourfactors,OPP_oppTeamTurnoverPercentage_fourfactors,OPP_oppOffensiveReboundPercentage_fourfactors,OPP_foulsDrawn_misc,OPP_percentageFieldGoalsAttempted2pt_scoring,OPP_percentageFieldGoalsAttempted3pt_scoring,OPP_percentagePoints2pt_scoring,OPP_percentagePointsMidrange2pt_scoring,OPP_percentagePoints3pt_scoring,OPP_percentagePointsFastBreak_scoring,OPP_percentagePointsFreeThrow_scoring,OPP_percentagePointsOffTurnovers_scoring,OPP_percentagePointsPaint_scoring,OPP_percentageAssisted2pt_scoring,OPP_percentageUnassisted2pt_scoring,OPP_percentageAssisted3pt_scoring,OPP_percentageUnassisted3pt_scoring,OPP_percentageAssistedFGM_scoring,OPP_percentageUnassistedFGM_scoring,OPP_threePointersPercentage_traditional,OPP_freeThrowsPercentage_traditional,OPP_percentageFieldGoalsMade_usage,OPP_percentageFieldGoalsAttempted_usage,OPP_percentageThreePointersMade_usage,OPP_percentageThreePointersAttempted_usage,OPP_percentageFreeThrowsMade_usage,OPP_percentageFreeThrowsAttempted_usage,OPP_percentageReboundsOffensive_usage,OPP_percentageReboundsDefensive_usage,OPP_percentageReboundsTotal_usage,OPP_percentageAssists_usage,OPP_percentageTurnovers_usage,OPP_percentageSteals_usage,OPP_percentageBlocks_usage,OPP_percentageBlocksAllowed_usage,OPP_percentagePersonalFouls_usage,OPP_percentagePersonalFoulsDrawn_usage,OPP_percentagePoints_usage,OPP_plusMinusPoints_traditional,MATCHUP,SEASON,GAME_DATE,IS_HOME,IS_WIN,POINT_DIFF
0,0029900001,1610612739,30,77,7,14,17,23,9,29,38,23,10,2,18,27,84,240.000000,16,18,5,18,10,90.733681,97.737250,-6.988278,0.192753,1.411334,19.952389,0.033153,0.128447,0.079094,14.011125,0.416957,0.469768,0.196084,96.000410,93.500258,56.054375,0.086425,0.433493,0.298513,0.196031,0.474877,0.369961,0.189484,0.242580,0.207917,0.787322,0.201011,0.503678,0.296652,0.212107,0.053691,0.196500,0.169005,0.207026,0.704014,0.147931,0.206631,0.249897,0.632994,0.218950,0.251120,0.581979,0.198319,0.200823,0.169585,0.180783,0.199848,0.203016,0.163000,0.199473,0.199854,0.206976,0.180579,0.178215,0.148264,0.229443,0.194080,0.014335,0.196578,-4.233125,1610612752,32.0,74.0,6.0,15.0,22.0,27.0,9.0,35.0,44.0,17.0,10.0,10.0,15.0,23.0,92.0,240.000000,20.0,10.0,8.0,26.0,2.0,98.132465,91.007410,7.138000,0.138091,0.660656,14.414340,0.041851,0.138519,0.093162,10.718486,0.452203,0.514103,0.189160,96.002022,92.999508,64.810208,0.118791,0.474730,0.370718,0.188443,0.435168,0.300185,0.195257,0.201355,0.111458,0.792252,0.207891,0.559252,0.275400,0.145694,0.068824,0.244220,0.273872,0.283893,0.315212,0.633954,0.327361,0.000000,0.457383,0.491784,0.196417,0.769640,0.200191,0.200648,0.163681,0.182519,0.189975,0.187079,0.165201,0.200395,0.197848,0.197485,0.156261,0.184727,0.226056,0.158403,0.199342,0.014650,0.198439,7.415139,CLE @ NYK,1999-00,1999-11-02,0,0,-8.0
1,0029900001,1610612752,32,74,6,15,22,27,9,35,44,17,10,10,15,23,92,240.000000,20,10,8,26,2,98.132465,91.007410,7.138000,0.138091,0.660656,14.414340,0.041851,0.138519,0.093162,10.718486,0.452203,0.514103,0.189160,96.002022,92.999508,64.810208,0.118791,0.474730,0.370718,0.188443,0.435168,0.300185,0.195257,0.201355,0.111458,0.792252,0.207891,0.559252,0.275400,0.145694,0.068824,0.244220,0.273872,0.283893,0.315212,0.633954,0.327361,0.000000,0.457383,0.491784,0.196417,0.769640,0.200191,0.200648,0.163681,0.182519,0.189975,0.187079,0.165201,0.200395,0.197848,0.197485,0.156261,0.184727,0.226056,0.158403,0.199342,0.014650,0.198439,7.415139,1610612739,30.0,77.0,7.0,14.0,17.0,23.0,9.0,29.0,38.0,23.0,10.0,2.0,18.0,27.0,84.0,240.000000,16.0,18.0,5.0,18.0,10.0,90.733681,97.737250,-6.988278,0.192753,1.411334,19.952389,0.033153,0.128447,0.079094,14.011125,0.416957,0.469768,0.196084,96.000410,93.500258,56.054375,0.086425,0.433493,0.298513,0.196031,0.474877,0.369961,0.189484,0.242580,0.207917,0.787322,0.201011,0.503678,0.296652,0.212107,0.053691,0.196500,0.169005,0.207026,0.704014,0.147931,0.206631,0.249897,0.632994,0.218950,0.251120,0.581979,0.198319,0.200823,0.169585,0.180783,0.199848,0.203016,0.163000,0.199473,0.199854,0.206976,0.180579,0.178215,0.148264,0.229443,0.194080,0.014335,0.196578,-4.233125,NYK vs. CLE,1999-00,1999-11-02,1,1,8.0
2,0029900002,1610612751,36,81,5,12,35,46,15,30,45,11,11,4,18,39,112,240.000000,22,20,8,40,3,103.037021,110.423160,-7.397125,0.093954,0.374306,7.795562,0.063256,0.127267,0.094153,11.500326,0.544179,0.589837,0.193948,105.281281,108.500828,67.433611,0.095616,0.475948,0.565859,0.172617,0.513612,0.687339,0.187842,0.338847,0.368264,0.838005,0.138940,0.548426,0.211650,0.108675,0.104131,0.319844,0.193684,0.336908,0.307333,0.524681,0.073889,0.264792,0.380447,0.596498,0.128292,0.702157,0.200503,0.203035,0.129688,0.171099,0.198261,0.193761,0.199947,0.203550,0.199933,0.212605,0.187613,0.189531,0.155583,0.146405,0.196895,0.014148,0.198515,-5.470972,1610612754,37.0,78.0,6.0,13.0,39.0,53.0,15.0,28.0,43.0,14.0,10.0,3.0,20.0,38.0,119.0,240.016667,19.0,25.0,12.0,42.0,4.0,111.010916,103.199708,7.811208,0.090626,0.519961,10.650885,0.066723,0.114252,0.089925,15.337539,0.537174,0.590935,0.197836,105.280436,108.000458,61.738560,0.095848,0.514629,0.691705,0.187933,0.476372,0.568241,0.171832,0.344928,0.455871,0.826516,0.173484,0.526269,0.173445,0.170067,0.083064,0.256120,0.138516,0.352695,0.269519,0.682915,0.469967,0.048191,0.365172,0.587262,0.442511,0.575040,0.197908,0.200782,0.208183,0.179729,0.185648,0.185818,0.203955,0.199004,0.197018,0.209140,0.200613,0.186442,0.192869,0.160660,0.196291,0.014945,0.198406,5.461426,NJN vs. IND,1999-00,1999-11-02,1,0,-7.0
3,0029900002,1610612754,37,78,6,13,39,53,15,28,43,14,10,3,20,38,119,240.016667,19,25,12,42,4,111.010916,103.199708,7.811208,0.090626,0.519961,10.650885,0.066723,0.114252,0.089925,15.337539,0.537174,0.590935,0.197836,105.280436,108.000458,61.738560,0.095848,0.514629,0.691705,0.187933,0.476372,0.568241,0.171832,0.344928,0.455871,0.826516,0.173484,0.526269,0.173445,0.170067,0.083064,0.256120,0.138516,0.352695,0.269519,0.682915,0.469967,0.048191,0.365172,0.587262,0.442511,0.575040,0.197908,0.200782,0.208183,0.179729,0.185648,0.185818,0.203955,0.199004,0.197018,0.209140,0.200613,0.186442,0.192869,0.160660,0.196291,0.014945,0.198406,5.461426,1610612751,36.0,81.0,5.0,12.0,35.0,46.0,15.0,30.0,45.0,11.0,11.0,4.0,18.0,39.0,112.0,240.000000,22.0,20.0,8.0,40.0,3.0,103.037021,110.423160,-7.397125,0.093954,0.374306,7.795562,0.063256,0.127267,0.094153,11.500326,0.544179,0.589837,0.193948,105.281281,108.500828,67.433611,0.095616,0.475948,0.565859,0.172617,0.513612,0.687339,0.187842,0.338847,0.368264,0.838005,0.138940,0.548426,0.211650,0.108675,0.104131,0.319844,0.193684,0.336908,0.307333,0.524681,0.073889,0.264792,0.380447,0.596498,0.128292,0.702157,0.200503,0.203035,0.129688,0.171099,0.198261,0.193761,0.199947,0.203550,0.199933,0.212605,0.187613,0.189531,0.155583,0.146405,0.196895,0.014148,0.198515,-5.470972,IND @ NJN,1999-00,1999-11-02,0,1,7.0
4,0029900003,1610612737,31,78,2,6,23,30,16,34,50,15,5,5,23,22,87,240.000000,14,10,14,32,5,89.259479,96.353313,-7.075097,0.127295,0.373726,9.903090,0.064874,0.139126,0.101001,16.693944,0.410884,0.479125,0.200495,98.118501,97.600537,61.293611,0.088329,0.414216,0.401616,0.233748,0.462236,0.185940,0.152675,0.265121,0.503056,0.929368,0.070787,0.714106,0.256272,0.048078,0.153771,0.237661,0.150749,0.457861,0.421989,0.532872,0.000000,0.199514,0.405471,0.594529,0.176944,0.572303,0.202958,0.200886,0.099757,0.222895,0.177422,0.184213,0.191125,0.212502,0.204615,0.215720,0.207392,0.174378,0.154861,0.150347,0.181666,0.028054,0.201412,-2.602917,1610612764,39.0,88.0,3.0,10.0,13.0,16.0,12.0,30.0,42.0,23.0,5.0,5.0,15.0,30.0,94.0,240.000000,21.0,13.0,6.0,40.0,5.0,95.607153,87.699611,7.902674,0.142049,0.605174,20.307479,0.046938,0.118369,0.083026,10.285243,0.505227,0.527368,0.195427,98.120797,98.500015,46.877917,0.105983,0.461744,0.185739,0.153030,0.408839,0.400769,0.234769,0.346544,0.702847,0.878051,0.090977,0.792576,0.317607,0.079125,0.079987,0.097327,0.239451,0.474969,0.487619,0.481409,0.131875,0.000000,0.564075,0.404953,0.054433,0.349670,0.204716,0.200208,0.085926,0.136903,0.190875,0.203007,0.185406,0.196825,0.197388,0.189788,0.200875,0.185517,0.172653,0.155711,0.199349,0.080037,0.204833,4.042986,ATL @ WAS,1999-00,1999-11-02,0,0,-7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76342,0042400401,1610612760,39,98,11,30,21,24,10,29,39,13,14,6,6,19,110,240.016667,11,11,11,46,7,104.859211,107.238254,-2.401319,0.089877,0.484480,9.231408,0.032102,0.126582,0.073159,4.215554,0.471415,0.518615,0.190986,104.398813,104.097747,65.037497,0.097399,0.455725,0.253861,0.066125,0.585600,0.256203,0.242994,0.305840,2.829040,0.638792,0.358499,0.523928,0.053338,0.277455,0.101775,0.178516,0.108151,0.470590,0.280170,0.548314,0.341042,0.292109,0.451021,0.528911,0.280632,0.579554,0.197089,0.199259,0.183445,0.203555,0.203944,0.205643,0.158191,0.195664,0.189841,0.191115,0.166873,0.207506,0.252223,0.156445,0.205720,0.204903,0.201040,-1.280814,1610612754,39.0,82.0,18.0,39.0,15.0,21.0,13.0,43.0,56.0,24.0,1.0,7.0,24.0,22.0,111.0,240.016667,4.0,12.0,10.0,34.0,6.0,107.199743,106.020887,1.185473,0.152824,1.487171,16.042157,0.054027,0.135550,0.102712,16.549691,0.590604,0.622814,0.194014,104.398840,103.499456,61.453580,0.105077,0.587677,0.257399,0.241239,0.456693,0.248252,0.066348,0.198115,2.300604,0.501280,0.498720,0.367759,0.077094,0.487458,0.102077,0.145064,0.030612,0.290827,0.311811,0.520492,0.785258,0.148566,0.577500,0.422500,0.453506,0.406064,0.201986,0.200134,0.195214,0.196461,0.208137,0.204329,0.181644,0.190189,0.193941,0.198113,0.190323,0.068954,0.205017,0.172056,0.188080,0.209822,0.200037,3.767655,OKC vs. IND,2024-25,2025-06-05,1,0,-1.0
76343,0042400402,1610612754,37,82,14,40,19,26,7,28,35,27,9,6,15,25,107,240.000000,17,10,9,34,4,107.749493,125.240944,-17.504944,0.192788,1.313061,17.297743,0.028622,0.128916,0.075563,10.674743,0.518804,0.563388,0.192446,100.480918,98.800358,51.636806,0.083734,0.537393,0.318106,0.147637,0.584459,0.455280,0.141166,0.278398,2.256319,0.473365,0.509969,0.365112,0.100213,0.425986,0.073556,0.192350,0.172364,0.264890,0.556698,0.242607,0.876344,0.047545,0.732554,0.202584,0.359288,0.351443,0.200187,0.200804,0.212136,0.203101,0.213007,0.211989,0.193367,0.198466,0.201860,0.192983,0.190133,0.199179,0.187639,0.111100,0.193683,0.196846,0.201050,-8.625486,1610612760,40.0,82.0,14.0,36.0,29.0,33.0,11.0,32.0,43.0,25.0,10.0,4.0,13.0,20.0,123.0,240.000000,14.0,9.0,4.0,42.0,6.0,124.927028,107.611965,17.327417,0.165791,1.589896,19.668556,0.045791,0.133632,0.092358,8.651090,0.527407,0.586091,0.195107,100.478826,99.098391,52.651944,0.117421,0.604591,0.467545,0.142374,0.534502,0.319897,0.148433,0.177770,3.164306,0.531637,0.440447,0.440503,0.056893,0.317947,0.026094,0.193078,0.072515,0.383494,0.519340,0.300729,0.709903,0.017111,0.669727,0.270551,0.261287,0.592896,0.201530,0.204388,0.214924,0.203669,0.203131,0.202932,0.187598,0.194976,0.194408,0.207842,0.195114,0.183332,0.142664,0.136569,0.179131,0.218797,0.199623,7.487847,IND @ OKC,2024-25,2025-06-08,0,0,-16.0
76344,0042400402,1610612760,40,82,14,36,29,33,11,32,43,25,10,4,13,20,123,240.000000,14,9,4,42,6,124.927028,107.611965,17.327417,0.165791,1.589896,19.668556,0.045791,0.133632,0.092358,8.651090,0.527407,0.586091,0.195107,100.478826,99.098391,52.651944,0.117421,0.604591,0.467545,0.142374,0.534502,0.319897,0.148433,0.177770,3.164306,0.531637,0.440447,0.440503,0.056893,0.317947,0.026094,0.193078,0.072515,0.383494,0.519340,0.300729,0.709903,0.017111,0.669727,0.270551,0.261287,0.592896,0.201530,0.204388,0.214924,0.203669,0.203131,0.202932,0.187598,0.194976,0.194408,0.207842,0.195114,0.183332,0.142664,0.136569,0.179131,0.218797,0.199623,7.487847,1610612754,37.0,82.0,14.0,40.0,19.0,26.0,7.0,28.0,35.0,27.0,9.0,6.0,15.0,25.0,107.0,240.000000,17.0,10.0,9.0,34.0,4.0,107.749493,125.240944,-17.504944,0.192788,1.313061,17.297743,0.028622,0.128916,0.075563,10.674743,0.518804,0.563388,0.192446,100.480918,98.800358,51.636806,0.083734,0.537393,0.318106,0.147637,0.584459,0.455280,0.141166,0.278398,2.256319,0.473365,0.509969,0.365112,0.100213,0.425986,0.073556,0.192350,0.172364,0.264890,0.556698,0.242607,0.876344,0.047545,0.732554,0.202584,0.359288,0.351443,0.200187,0.200804,0.212136,0.203101,0.213007,0.211989,0.193367,0.198466,0.201860,0.192983,0.190133,0.199179,0.187639,0.111100,0.193683,0.196846,0.201050,-8.625486,OKC vs. IND,2024-25,2025-06-08,1,1,16.0
76345,0042400403,1610612754,44,85,9,27,19,22,7,29,36,24,13,11,13,24,116,240.000000,21,13,17,50,4,114.081778,103.844535,10.243340,0.143614,0.890670,13.519639,0.032210,0.127237,0.081195,10.168583,0.564719,0.589556,0.194711,101.940403,102.401259,58.636806,0.110640,0.569751,0.258165,0.138367,0.532022,0.386116,0.185964,0.233093,2.106042,0.654474,0.332749,0.624951,0.215150,0.236199,0.131332,0.125948,0.219943,0.409799,0.499780,0.487443,0.562083,0.037847,0.581615,0.405607,0.284580,0.449041,0.196540,0.199064,0.195040,0.196882,0.174378,0.182395,0.240243,0.199543,0.201736,0.198057,0.192505,0.186220,0.177785,0.171336,0.193431,0.188285,0.193799,4.867153,1610612760,37.0,79.0,10.0,22.0,23.0,30.0,9.0,33.0,42.0,16.0,6.0,4.0,17.0,20.0,107.0,240.000000,14.0,7.0,10.0,48.0,11.0,104.041729,113.766938,-9.725208,0.109897,1.188749,12.576111,0.040029,0.148027,0.094363,13.171382,0.551383,0.595842,0.188548,101.939283,102.497244,68.000069,0.090457,0.532462,0.380398,0.185438,0.571176,0.265022,0.137716,0.176117,3.636528,0.704326,0.294285,0.459764,0.040943,0.306684,0.105949,0.183192,0.130573,0.418821,0.245000,0.403889,0.292118,0.335799,0.534992,0.414800,0.405356,0.556018,0.200116,0.200735,0.173265,0.175914,0.185293,0.185213,0.194253,0.195259,0.195451,0.197819,0.177444,0.229913,0.182049,0.190598,0.195926,0.185801,0.197910,-5.147639,IND vs. OKC,2024-25,2025-06-11,1,1,9.0
76346,0042400403,1610612760,37,79,10,22,23,30,9,33,42,16,6,4,17,20,107,240.000000,14,7,10,48,11,104.041729,113.766938,-9.725208,0.109897,1.188749,12.576111,0.040029,0.148027,0.094363,13.171382,0.551383,0.595842,0.188548,101.939283,102.497244,68.000069,0.090457,0.532462,0.380398,0.185438,0.571176,0.265022,0.137716,0.176117,3.636528,0.704326,0.294285,0.459764,0.040943,0.306684,0.105949,0.183192,0.130573,0.418821,0.245000,0.403889,0.292118,0.335799,0.534992,0.414800,0.405356,0.556018,0.200116,0.200735,0.173265,0.175914,0.185293,0.185213,0.194253,0.195259,0.195451,0.197819,0.177444,0.229913,0.182049,0.190598,0.195926,0.185801,0.197910,-5.147639,1610612754,44.0,85.0,9.0,27.0,19.0,22.0,7.0,29.0,36.0,24.0,13.0,11.0,13.0,24.0,116.0,240.000000,21.0,13.0,17.0,50.0,4.0,114.081778,103.844535,10.243340,0.143614,0.890670,13.519639,0.032210,0.127237,0.081195,10.168583,0.564719,0.589556,0.194711,101.940403,102.401259,58.636806,0.110640,0.569751,0.258165,0.138367,0.532022,0.386116,0.185964,0.233093,2.106042,0.654474,0.332749,0.624951,0.215150,0.236199,0.131332,0.125948,0.219943,0.409799,0.499780,0.487443,0.562083,0.037847,0.581615,0.405607,0.284580,0.449041,0.196540,0.199064,0.195040,0.196882,0.174378,0.182395,0.240243,0.199543,0.201736,0.198057,0.192505,0.186220,0.177785,0.171336,0.193431,0.188285,0.193799,4.867153,OKC @ IND,2024-25,2025-06-11,0,0,-9.0

# SPECIAL FOR ODDS : Keep only season past 2010-11

In [ ]:
# # get first line with season 2010-11 and cut all lines before
# first_season = match_dataset[match_dataset['SEASON'] == '2010-11'].index[0]
# match_dataset = match_dataset.iloc[first_season:].reset_index(drop=True)
# match_dataset

# Merge Odds with dataset

In [64]:

def match_odds_with_dataset_test(odds_df, nba_df):
    
    team_id_map = get_team_mapping_id()
    
    nba_df = nba_df.copy()
    odds_df = odds_df.copy()

    # Conversion explicite des ID en str
    nba_df["TEAM_ID"] = nba_df["TEAM_ID"].astype(str)
    nba_df["OPP_TEAM_ID"] = nba_df["OPP_TEAM_ID"].astype(str)
    team_id_map = {str(k): v for k, v in team_id_map.items()}

    nba_df["TEAM_NAME"] = nba_df["TEAM_ID"].map(team_id_map).apply(clean_team_name)
    nba_df["OPPONENT_NAME"] = nba_df["OPP_TEAM_ID"].map(team_id_map).apply(clean_team_name)
    nba_df["GAME_DATE"] = pd.to_datetime(nba_df["GAME_DATE"]).dt.date

    odds_df["home_team"] = odds_df["home_team"].apply(clean_team_name)
    odds_df["away_team"] = odds_df["away_team"].apply(clean_team_name)
    odds_df["date"] = pd.to_datetime(odds_df["date"]).dt.date

    nba_df["match_key"] = nba_df.apply(
        lambda row: (row["GAME_DATE"], row["TEAM_NAME"], row["OPPONENT_NAME"])
        if row["IS_HOME"] == 1
        else (row["GAME_DATE"], row["OPPONENT_NAME"], row["TEAM_NAME"]),
        axis=1,
    )

    keys_full = []
    for shift in [-1, 0, 1]:
        shifted = odds_df.copy()
        shifted["match_key"] = shifted.apply(
            lambda row: (row["date"] + timedelta(days=shift), row["home_team"], row["away_team"]),
            axis=1
        )
        keys_full.append(shifted)

    odds_full = pd.concat(keys_full, ignore_index=True)
    odds_full = odds_full.drop_duplicates(subset=["match_key"])

    # print("\nExemples de clés de match dans odds_df (tolérance date):")
    # print(odds_full["match_key"].drop_duplicates().head())
    # print("\nExemples de clés de match dans nba_df:")
    # print(nba_df["match_key"].drop_duplicates().head())


    merged = pd.merge(odds_full, nba_df, on="match_key", how="right")
    
    # Attribution claire des cotes à chaque ligne équipe
    merged["ODDS"] = merged.apply(
        lambda row: row["home_odds"] if row["IS_HOME"] == 1 else row["away_odds"], axis=1
    )
    merged["OPP_ODDS"] = merged.apply(
        lambda row: row["away_odds"] if row["IS_HOME"] == 1 else row["home_odds"], axis=1
    )
    
    # print(f"\nNombre de lignes fusionnées: {len(merged)}")
    # print(f"Nombre de correspondances réussies: {merged['TEAM_ID'].notna().sum()}")
    # print(f"Nombre de correspondances échouées: {merged['TEAM_ID'].isna().sum()}")

    # print("\nIDs manquants TEAM_ID:", nba_df[~nba_df["TEAM_ID"].isin(team_id_map.keys())]["TEAM_ID"].unique())
    # print("IDs manquants OPP_TEAM_ID:", nba_df[~nba_df["OPP_TEAM_ID"].isin(team_id_map.keys())]["OPP_TEAM_ID"].unique())

    # Nettoyage des données fusionnées
    merged = clean_merged_matches(merged)

    return merged

In [65]:
all_odds_df = merge_odds_csv_files(DATA_ODDS_HISTORY_DIR)

match_dataset = match_odds_with_dataset_test(all_odds_df, match_dataset)

In [ ]:
match_dataset

,GAME_ID,TEAM_ID,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,points_traditional,MINUTES_PLAYED,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,blocksAgainst_misc,offensiveRating_advanced,defensiveRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,threePointersPercentage_traditional,freeThrowsPercentage_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage,plusMinusPoints_traditional,OPP_TEAM_ID,OPP_fieldGoalsMade_traditional,OPP_fieldGoalsAttempted_traditional,OPP_threePointersMade_traditional,OPP_threePointersAttempted_traditional,OPP_freeThrowsMade_traditional,OPP_freeThrowsAttempted_traditional,OPP_reboundsOffensive_traditional,OPP_reboundsDefensive_traditional,OPP_reboundsTotal_traditional,OPP_assists_traditional,OPP_steals_traditional,OPP_blocks_traditional,OPP_turnovers_traditional,OPP_foulsPersonal_traditional,OPP_points_traditional,OPP_MINUTES_PLAYED,OPP_pointsOffTurnovers_misc,OPP_pointsSecondChance_misc,OPP_pointsFastBreak_misc,OPP_pointsPaint_misc,OPP_blocksAgainst_misc,OPP_offensiveRating_advanced,OPP_defensiveRating_advanced,OPP_netRating_advanced,OPP_assistPercentage_advanced,OPP_assistToTurnover_advanced,OPP_assistRatio_advanced,OPP_offensiveReboundPercentage_advanced,OPP_defensiveReboundPercentage_advanced,OPP_reboundPercentage_advanced,OPP_turnoverRatio_advanced,OPP_effectiveFieldGoalPercentage_advanced,OPP_trueShootingPercentage_advanced,OPP_usagePercentage_advanced,OPP_estimatedPace_advanced,OPP_pace_advanced,OPP_possessions_advanced,OPP_PIE_advanced,OPP_effectiveFieldGoalPercentage_fourfactors,OPP_freeThrowAttemptRate_fourfactors,OPP_teamTurnoverPercentage_fourfactors,OPP_oppEffectiveFieldGoalPercentage_fourfactors,OPP_oppFreeThrowAttemptRate_fourfactors,OPP_oppTeamTurnoverPercentage_fourfactors,OPP_oppOffensiveReboundPercentage_fourfactors,OPP_foulsDrawn_misc,OPP_percentageFieldGoalsAttempted2pt_scoring,OPP_percentageFieldGoalsAttempted3pt_scoring,OPP_percentagePoints2pt_scoring,OPP_percentagePointsMidrange2pt_scoring,OPP_percentagePoints3pt_scoring,OPP_percentagePointsFastBreak_scoring,OPP_percentagePointsFreeThrow_scoring,OPP_percentagePointsOffTurnovers_scoring,OPP_percentagePointsPaint_scoring,OPP_percentageAssisted2pt_scoring,OPP_percentageUnassisted2pt_scoring,OPP_percentageAssisted3pt_scoring,OPP_percentageUnassisted3pt_scoring,OPP_percentageAssistedFGM_scoring,OPP_percentageUnassistedFGM_scoring,OPP_threePointersPercentage_traditional,OPP_freeThrowsPercentage_traditional,OPP_percentageFieldGoalsMade_usage,OPP_percentageFieldGoalsAttempted_usage,OPP_percentageThreePointersMade_usage,OPP_percentageThreePointersAttempted_usage,OPP_percentageFreeThrowsMade_usage,OPP_percentageFreeThrowsAttempted_usage,OPP_percentageReboundsOffensive_usage,OPP_percentageReboundsDefensive_usage,OPP_percentageReboundsTotal_usage,OPP_percentageAssists_usage,OPP_percentageTurnovers_usage,OPP_percentageSteals_usage,OPP_percentageBlocks_usage,OPP_percentageBlocksAllowed_usage,OPP_percentagePersonalFouls_usage,OPP_percentagePersonalFoulsDrawn_usage,OPP_percentagePoints_usage,OPP_plusMinusPoints_traditional,MATCHUP,SEASON,GAME_DATE,IS_HOME,IS_WIN,POINT_DIFF,TEAM_NAME,OPPONENT_NAME,ODDS,OPP_ODDS
0,0021000001,1610612738,32,69,8,16,16,25,8,34,42,25,6,4,18,19,88,240.000000,17,11,11,38,6,95.258826,86.767938,8.458819,0.179324,1.418765,16.786944,0.040284,0.143548,0.097696,13.576424,0.536647,0.565526,0.192004,91.500720,92.499906,61.978819,0.121102,0.524833,0.364811,0.217790,0.420576,0.341330,0.187027,0.244226,2.633472,0.773753,0.226247,0.600667,0.136254,0.202795,0.091713,0.196539,0.204380,0.464413,0.525706,0.421030,0.332569,0.000000,0.710834,0.235902,0.228976,0.522179,0.200810,0.200914,0.180178,0.199018,0.197938,0.195703,0.190636,0.204025,0.202745,0.190902,0.178942,0.176299,0.151945,0.196471,0.197720,0.199016,0.200868,4.585556,1610612748,27.0,74.0,8.0,20.0,18.0,25.0,11.0,28.0,39.0,15.0,10.0,6.0,17.0,21.0,80.0,240.000000,22.0,5.0,11.0,24.0,4.0,86.585597,94.558222,-7.960403,0.158097,0.533849,13.530931,0.049858,0.138836,0.087374,10.813681,0.426550,0.495102,0.197047,91.499007,92.600174,59.272778,0.090339,0.418351,0.344338,0.188392,0.524045,0.364850,0.217761,0.223355,2.708681,0.712399,0.243379,0.496113,0.140206,0.278267,0.123794,0.225773,0.204365,0.355907,0.308280,0.538734,0.396736,0.152847,0.520927,0.434698,0.226023,0.579196,0.205427,0.199612,0.187020,0.186814,0.196853,0.187300,0.218039,0.202114,0.198359,0.228813,0.200531,0.173722,0.193393,0.147483,0.203271,0.192911,0.203349,-6.306528,BOS vs. MIA,2010-11,2010-10-26,1,1,8.0,boston celtics,miami heat,1.88,1.70
1,0021000001,1610612748,27,74,8,20,18,25,11,28,39,15,10,6,17,21,80,240.000000,22,5,11,24,4,86.585597,94.558222,-7.960403,0.158097,0.533849,13.530931,0.049858,0.138836,0.087374,10.813681,0.426550,0.495102,0.197047,91.499007,92.600174,59.272778,0.090339,0.418351,0.344338,0.188392,0.524045,0.364850,0.217761,0.223355,2.708681,0.712399,0.243379,0.496113,0.140206,0.278267,0.123794,0.225773,0.204365,0.355907,0.308280,0.538734,0.396736,0.152847,0.520927,0.434698,0.226023,0.579196,0.205427,0.199612,0.187020,0.186814,0.196853,0.187300,0.218039,0.202114,0.198359,0.228813,0.200531,0.173722,0.193393,0.147483,0.203271,0.192911,0.203349,-6.306528,1610612738,32.0,69.0,8.0,16.0,16.0,25.0,8.0,34.0,42.0,25.0,6.0,4.0,18.0,19.0,88.0,240.000000,17.0,11.0,11.0,38.0,6.0,95.258826,86.767938,8.458819,0.179324,1.418765,16.786944,0.040284,0.143548,0.097696,13.576424,0.536647,0.565526,0.192004,91.500720,92.499906,61.978819,0.121102,0.524833,0.364811,0.217790,0.420576,0.341330,0.187027,0.244226,2.633472,0.773753,0.226247,0.600667,0.136254,0.202795,0.091713,0.196539,0.204380,0.464413,0.525706,0.421030,0.332569,0.000000,0.710834,0.235902,0.228976,0.522179,0.200810,0.200914,0.180178,0.199018,0.197938,0.195703,0.190636,0.204025,0.202745,0.190902,0.178942,0.176299,0.151945,0.196471,0.197720,0.199016,0.200868,4.585556,MIA @ BOS,2010-11,2010-10-26,0,0,-8.0,miami heat,boston celtics,1.70,1.88
2,0021000002,1610612756,36,74,9,19,11,16,7,23,30,15,3,4,19,19,92,240.000000,17,11,6,44,2,101.425007,116.062382,-14.648243,0.113202,0.765569,12.112500,0.037518,0.088750,0.065437,15.816979,0.525870,0.535510,0.195844,94.820024,91.299769,49.458125,0.072061,0.551087,0.219725,0.204248,0.516365,0.162388,0.155634,0.433928,2.182639,0.755892,0.244108,0.571466,0.086887,0.339328,0.039907,0.089060,0.246915,0.484873,0.259333,0.521430,0.333822,0.231595,0.436625,0.563375,0.372170,0.355924,0.197446,0.201281,0.204137,0.193324,0.178646,0.176324,0.205161,0.195726,0.197705,0.204080,0.182448,0.135582,0.266250,0.217986,0.189598,0.189302,0.196874,-7.175972,1610612757,43.0,93.0,10.0,20.0,10.0,15.0,18.0,30.0,48.0,31.0,11.0,2.0,12.0,22.0,106.0,240.000000,21.0,21.0,13.0,42.0,4.0,116.705951,101.868819,14.847993,0.179627,1.619028,21.211271,0.071370,0.149384,0.105635,7.830722,0.500923,0.520792,0.191743,94.821719,91.100492,55.840069,0.059822,0.516180,0.167638,0.156635,0.550046,0.216926,0.204611,0.194777,2.417917,0.803757,0.196243,0.626211,0.218095,0.243037,0.126697,0.118044,0.228035,0.408116,0.552484,0.343836,0.495069,0.000000,0.696103,0.291188,0.261279,0.596760,0.198572,0.201131,0.215227,0.194294,0.199463,0.211358,0.207308,0.211804,0.199374,0.199567,0.145885,0.190182,0.204896,0.180178,0.195436,0.204637,0.199758,9.013194,PHX @ POR,2010-11,2010-10-26,0,0,-14.0,phoenix suns,portland trail blazers,3.30,1.22
3,0021000002,1610612757,43,93,10,20,10,15,18,30,48,31,11,2,12,22,106,240.000000,21,21,13,42,4,116.705951,101.868819,14.847993,0.179627,1.619028,21.211271,0.071370,0.149384,0.105635,7.830722,0.500923,0.520792,0.191743,94.821719,91.100492,55.840069,0.059822,0.516180,0.167638,0.156635,0.550046,0.216926,0.204611,0.194777,2.417917,0.803757,0.196243,0.626211,0.218095,0.243037,0.126697,0.118044,0.228035,0.408116,0.552484,0.343836,0.495069,0.000000,0.696103,0.291188,0.261279,0.596760,0.198572,0.201131,0.215227,0.194294,0.199463,0.211358,0.207308,0.211804,0.199374,0.199567,0.145885,0.190182,0.204896,0.180178,0.195436,0.204637,0.199758,9.013194,1610612756,36.0,74.0,9.0,19.0,11.0,16.0,7.0,23.0,30.0,15.0,3.0,4.0,19.0,19.0,92.0,240.000000,17.0,11.0,6.0,44.0,2.0,101.425007,116.062382,-14.648243,0.113202,0.765569,12.112500,0.037518,0.088750,0.065437,15.816979,0.525870,0.535510,0.195844,94.820024,91.299769,49.458125,0.072061,0.551087,0.219725,0.204248,0.516365,0.162388,0.155634,0.433928,2.182639,0.755892,0.244108,0.571466,0.086887,0.339328,0.039907,0.089060,0.246915,0.484873,0.259333,0.521430,0.333822,0.231595,0.436625,0.563375,0.372170,0.355924,0.197446,0.201281,0.204137,0.193324,0.178646,0.176324,0.205161,0.195726,0.197705,0.204080,0.182448,0.135582,0.266250,0.217986,0.189598,0.189302,0.196874,-7.175972,POR vs. PHX,2010-11,2010-10-26,1,1,14.0,portland trail blazers,phoenix suns,1.22,3.30
4,0021000003,1610612745,38,91,8,20,26,28,16,37,53,25,6,7,20,25,110,239.983333,10,16,17,42,4,106.091812,106.928071,-0.849344,0.163359,1.393743,22.918397,0.061861,0.126248,0.095825,12.957421,0.402580,0.475858,0.198410,107.319701,104.201138,61.522328,0.102728,0.462191,0.307097,0.193372,0.466376,0.295486,0.112989,0.279195,3.016946,0.693632,0.244628,0.453675,0.138961,0.260127,0.120814,0.204803,0.083422,0.314576,0.444436,0.343327,0.383863,0.043388,0.668162,0.250444,0.220759,0.663562,0.195155,0.200732,0.158192,0.197478,0.179789,0.185280,0.236348,0.191520,0.197204,0.203254,0.194367,0.177269,0.216853,0.199693,0.193461,0.186709,0.195638,1.938676,1610612747,40.0,96.0,9.0,21.0,23.0,28.0,14.0,30.0,44.0,21.0,11.0,4.0,12.0,24.0,112.0,240.000000,20.0,23.0,12.0,46.0,7.0,107.380507,106.350694,1.029812,0.131055,1.647756,16.353167,0.047063,0.113064,0.079990,8.603597,0.459826,0.499774,0.198762,107.319970,103.900553,62.920486,0.095947,0.469353,0.301715,0.112949,0.462946,0.308913,0.193897,0.342518,3.282014,0.763126,0.236874,0.525493,0.091175,0.238875,0.084063,0.155979,0.220723,0.434164,0.409895,0.420730,0.239410,0.061146,0.488379,0.431968,0.178848,0.382295,0.197003,0.201767,0.150194,0.192673,0.191074,0.183087,0.181331,0.198692,0.201060,0.205763,0.192513,0.190966,0.181838,0.153690,0.207920,0.200452,0.194698,1.128750,HOU @ LAL,2010-11,2010-10-26,0,0,-2.0,houston rockets,los angeles lakers,3.50,1.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38076,0042400315,1610612760,46,88,14,35,18,21,7,39,46,26,14,8,14,20,124,239.983333,18,9,19,54,6,116.271158,86.683714,29.598472,0.153179,1.150288,17.148017,0.028388,0.149998,0.096439,10.277860,0.516245,0.561993,0.192570,105.418048,106.997439,56.169803,0.148150,0.611803,0.236456,0.146934,0.474105,0.174840,0.200146,0.167282,2.263421,0.505107,0.447042,0.415513,0.053693,0.336386,0.170277,0.143716,0.142655,0.361811,0.271593,0.447207,0.613654,0.088201,0.505260,0.390219,0.295980,0.433318,0.198910,0.199313,0.218421,0.218920,0.201889,0.200478,0.173750,0.198343,0.198732,0.215838,0.178020,0.231836,0.154287,0.182675,0.190519,0.206314,0.205296,18.174734,1610612750,35.0,85.0,12.0,34.0,12.0,15.0,8.0,31.0,39.0,16.0,7.0,6.0,21.0,20.0,94.0,240.000000,19.0,9.0,11.0,42.0,8.0,87.171514,116.504264,-29.333417,0.116183,0.708677,13.718125,0.030622,0.140361,0.082084,18.631167,0.542748,0.561445,0.194901,105.418737,106.599077,51.231667,0.058890,0.481091,0.175172,0.203289,0.610079,0.237644,0.146667,0.177161,2.122014,0.608866,0.391134,0.427432,0.024669,0.320582,0.067912,0.079573,0.128458,0.402630,0.312224,0.394374,0.471545,0.220469,0.493226,0.334135,0.337450,0.277234,0.194955,0.201662,0.195141,0.204843,0.219928,0.203904,0.200962,0.195197,0.198470,0.204414,0.195335,0.164717,0.196726,0.170304,0.208142,0.201490,0.195605,-17.503681,OKC vs. MIN,2024-25,2025-05-28,1,1,30.0,oklahoma city thunder,minnesota timberwolves,1.25,3.91
38077,0042400305,1610612752,44,89,8,29,15,22,11,34,45,22,11,3,15,22,111,240.016667,15,13,15,60,7,111.626672,96.476189,15.129859,0.125950,1.390534,15.440879,0.043370,0.141279,0.092679,12.034067,0.558147,0.567221,0.193626,100.719560,98.500117,59.565447,0.119602,0.540469,0.246219,0.145814,0.472053,0.393109,0.202483,0.192982,2.828206,0.683842,0.316158,0.631731,0.103985,0.190954,0.127092,0.134889,0.142174,0.527886,0.399925,0.557508,0.460541,0.105253,0.491475,0.465958,0.243192,0.465728,0.197112,0.201025,0.202199,0.205898,0.244602,0.222547,0.210065,0.194339,0.198821,0.199803,0.207125,0.182632,0.101895,0.205040,0.216710,0.200750,0.201481,10.772516,1610612754,30.0,74.0,10.0,30.0,24.0,29.0,8.0,32.0,40.0,20.0,10.0,7.0,20.0,22.0,94.0,240.000000,20.0,7.0,16.0,34.0,3.0,94.468389,110.979389,-16.503681,0.163760,0.659449,15.763840,0.033514,0.127963,0.081709,16.695181,0.522219,0.580079,0.196780,100.719401,99.700689,48.830486,0.078752,0.474772,0.405602,0.202463,0.541328,0.248815,0.145482,0.266363,2.224722,0.574555,0.419334,0.426940,0.067650,0.336782,0.120847,0.209541,0.207355,0.359363,0.269045,0.469635,0.632361,0.000000,0.568223,0.382680,0.318047,0.466979,0.193672,0.201590,0.186990,0.212042,0.183350,0.184878,0.199272,0.207638,0.198974,0.215748,0.200089,0.149691,0.177951,0.097502,0.214917,0.200371,0.196788,-9.565694,NYK vs. IND,2024-25,2025-05-29,1,1,17.0,new york knicks,indiana pacers,1.54,2.46
38078,0042400305,1610612754,30,74,10,30,24,29,8,32,40,20,10,7,20,22,94,240.000000,20,7,16,34,3,94.468389,110.979389,-16.503681,0.163760,0.659449,15.763840,0.033514,0.127963,0.081709,16.695181,0.522219,0.580079,0.196780,100.719401,99.700689,48.830486,0.078752,0.474772,0.405602,0.202463,0.541328,0.248815,0.145482,0.266363,2.224722,0.574555,0.419334,0.426940,0.067650,0.336782,0.120847,0.209541,0.207355,0.359363,0.269045,0.469635,0.632361,0.000000,0.568223,0.382680,0.318047,0.466979,0.193672,0.201590,0.186990,0.212042,0.183350,0.184878,0.199272,0.207638,0.198974,0.215748,0.200089,0.149691,0.177951,0.097502,0.214917,0.200371,0.196788,-9.565694,1610612752,44.0,89.0,8.0,29.0,15.0,22.0,11.0,34.0,45.0,22.0,11.0,3.0,15.0,22.0,111.0,240.016667,15.0,13.0,15.0,60.0,7.0,111.626672,96.476189,15.129859,0.125950,1.390534,15.440879,0.043370,0.141279,0.092679,12.034067,0.558147,0.567221,0.193626,100.719560,98.500117,59.565447,0.119602,0.540469,0.246219,0.145814,0.472053,0.393109,0.202483,0.192982,2.828206,0.683842,0.316158,0.631731,0.103985,0.190954,0.127092,0.134889,0.142174,0.527886,0.399925,0.557508,0.460541,0.105253,0.491475,0.465958,0.243192,0.465728,0.197112,0.201025,0.202199,0.205898,0.244602,0.222547,0.210065,0.194339,0.198821,0.199803,0.207125,0.182632,0.101895,0.205040,0.216710,0.200750,0.201481,10.772516,IND @ NYK,2024-25,2025-05-29,0,0,-17.0,indiana pacers,new york knicks,2.46,1.54
38079,0042400306,1610612752,41,86,9,32,17,26,13,28,41,23,10,6,17,16,108,240.000000,13,15,10,54,9,108.452111,126.791896,-18.338972,0.137946,1.068833,13.428708,0.050020,0.136825,0.086799,13.136583,0.501459,0.559112,0.190430,101.400812,99.101217,59.888889,0.085635,0.531050,0.308973,0.174502,0.648678,0.225373,0.131917,0.166467,2.875208,0.620439,0.348450,0.568563,0.073972,0.177266,0.102219,0.223204,0.122027,0.494456,0.382728,0.424147,0.355764,0.143333,0.470684,0.402580,0.190597,0.561911,0.195777,0.195994,0.214569,0.203844,0.172815,0.187488,0.206232,0.194752,0.195968,0.195585,0.162782,0.198096,0.156052,0.187617,0.192666,0.197732,0.202965,-12.926389,1610612754,46.0,85.0,17.0,33.0,16.0,19.0,6.0,30.0,36.0,30.0,10.0,9.0,12.0,23.0,125.0,240.016667,34.0,12.0,25.0,50.0,6.0,127.352996,105.015909,22.340053,0.153711,2.025884,22.049573,0.031637,0.114636,0.078322,7.995493,0.594024,0.616071,0.192961,101.399425,100.497996,54.449066,0.114831,0.633074,0.227772,0.126563,0.531103,0.304584,0.174045,0.304667,2.036595,0.562603,0.430870,0.428352,0.068864,0.387280,0.189745,0.093415,0.301309,0.359492,0.451172,0.346064,0.634262,0.209499,0.559565,0.349330,0.434339,0.543444,0.203022,0.197637,0.193534,0.192665,0.192244,0.191655,0.167582,0.200059,0.202670,0.197309,0.199876,0.164402,0.206905,0.175693,0.203954,0.201069,0.201598,13.039650,NYK @ IND,2024-25,2025-05-31,0,0,-17.0,new york knicks,indiana pacers,2.38,1.58
38080,0042400306,1610612754,46,85,17,33,16,19,6,30,36,30,10,9,12,23,125,240.016667,34,12,25,50,6,127.352996,105.015909,22.340053,0.153711,2.025884,22.049573,0.031637,0.114636,0.078322,7.995493,0.594024,0.616071,0.192961,101.399425,100.497996,54.449066,0.114831,0.633074,0.227772,0.126563,0.531103,0.304584,0.174045,0.304667,2.036595,0.562603,0.430870,0.428352,0.068864,0.387280,0.189745,0.093415,0.301309,0.359492,0.451172,0.346064,0.634262,0.209499,0.559565,0.349330,0.434339,0.543444,0.203022,0.197637,0.193534,0.192665,0.192244,0.191655,0.167582,0.200059,0.202670,0.197309,0.199876,0.164402,0.206905,0.175693,0.203954,0.201069,0.201598,13.039650,1610612752,41.0,86.0,9.0,32.0,17.0,26.0,13.0,28.0,41.0,23.0,10.0,6.0,17.0,16.0,108.0,240.000000,13.0,15.0,10.0,54.0,9.0,108.452111,126.791896,-18.338972,0.137946,1.068833,13.428708,0.050020,0.136825,0.086799,13.136583,0.501459,0.559112,0.190430,101.400812,99.101217,59.888889,0.085635,0.531050,0.308973,0.174502,0.648678,0.225373,0.131917,0.166467,2.875208,0.620439,0.348450,0.568563,0.073972,0.177266,0.102219,0.223204,0.122027,0.494456,0.382728,0.424147,0.355764,0.143333,0.470684,0.402580,0.190597,0.561911,0.195777,0.195994,0.214569,0.203844,0.172815,0.187488,0.206232,0.194752,0.195968,0.195585,0.162782,0.198096,0.156052,0.187617,0.192666,0.197732,0.202965,-12.926389,IND vs. NYK,2024-25,2025-05-31,1,1,17.0,indiana pacers,new york knicks,1.58,2.38

:

# Merge match_dataset with df_team_features_final on TEAM and GAME

In [ ]:

#team id as str
match_dataset['TEAM_ID'] = match_dataset['TEAM_ID'].astype(str)
match_dataset['GAME_ID'] = match_dataset['GAME_ID'].astype(str)

#date as datetime
match_dataset['GAME_DATE'] = pd.to_datetime(match_dataset['GAME_DATE'])

df_team_features_final['TEAM_ID'] = df_team_features_final['TEAM_ID'].astype(str)
df_team_features_final['GAME_ID'] = df_team_features_final['GAME_ID'].astype(str)
df_team_features_final['GAME_DATE'] = pd.to_datetime(df_team_features_final['GAME_DATE'])



# Merge match_dataset with df_team_features_final on TEAM and GAME, keep GAME_DATE
match_dataset = match_dataset.merge(
    df_team_features_final[['GAME_ID', 'TEAM_ID', 'GAME_DATE'] + df_team_features_final.columns.difference(['GAME_ID', 'TEAM_ID', 'GAME_DATE']).tolist()],
    on=['GAME_ID', 'TEAM_ID'],
    how='left'
)



# match_dataset_ = match_dataset.merge(
#     df_team_features_final,
#     on=['GAME_ID', 'TEAM_ID'],
#     how='left'
# )
#remove duplicates
match_dataset = match_dataset.drop_duplicates(subset=['GAME_ID', 'TEAM_ID'])

In [ ]:
#sort by GAME_DATE and GAME_ID
#match_dataset = match_dataset.sort_values(['GAME_DATE', 'GAME_ID']).reset_index(drop=True)



#print GAME_DATE_x and GAME_DATE_y to check if they are the same
print("GAME_DATE_x and GAME_DATE_y are the same:", (match_dataset['GAME_DATE_x'] == match_dataset['GAME_DATE_y']).all())

#drop GAME_DATE_x and GAME_DATE_y to GAME_DATE
match_dataset['GAME_DATE'] = match_dataset['GAME_DATE_x']
match_dataset = match_dataset.drop(columns=['GAME_DATE_x', 'GAME_DATE_y'])



#display cols in common match_dataset and df_team_features_final
common_cols = set(match_dataset.columns).intersection(set(df_team_features_final.columns))
print("Common columns between match_dataset and df_team_features_final:")
display(common_cols)

GAME_DATE_x and GAME_DATE_y are the same: True
Common columns between match_dataset and df_team_features_final:

{'GAME_DATE',
 'GAME_ID',
 'TEAM_ID',
 'has_absent',
 'has_top_absent',
 'num_absent',
 'num_absent_other',
 'num_injured',
 'num_personal',
 'num_present',
 'num_resting',
 'num_suspended',
 'player_perf_score_mean',
 'player_perf_score_sum',
 'top_player_absent',
 'top_player_absent_other',
 'top_player_absent_other_rate',
 'top_player_absent_rate',
 'top_player_count',
 'top_player_injured',
 'top_player_injury_rate',
 'top_player_personal',
 'top_player_personal_rate',
 'top_player_resting',
 'top_player_resting_rate',
 'top_player_suspended',
 'top_player_suspension_rate'}

# Reorder columns for visualisation

In [ ]:
cols_first = ['GAME_ID', 'GAME_DATE', 'TEAM_ID', 'OPP_TEAM_ID', 'IS_HOME', 'IS_WIN','POINT_DIFF','has_absent','has_top_absent','num_absent','top_player_absent', 'points_traditional','ODDS','OPP_ODDS']
other_cols = [col for col in match_dataset.columns if col not in cols_first]
match_dataset = match_dataset[cols_first + other_cols]
match_dataset

,GAME_ID,GAME_DATE,TEAM_ID,OPP_TEAM_ID,IS_HOME,IS_WIN,POINT_DIFF,has_absent,has_top_absent,num_absent,top_player_absent,points_traditional,ODDS,OPP_ODDS,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,MINUTES_PLAYED,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,blocksAgainst_misc,offensiveRating_advanced,defensiveRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,threePointersPercentage_traditional,freeThrowsPercentage_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage,plusMinusPoints_traditional,OPP_fieldGoalsMade_traditional,OPP_fieldGoalsAttempted_traditional,OPP_threePointersMade_traditional,OPP_threePointersAttempted_traditional,OPP_freeThrowsMade_traditional,OPP_freeThrowsAttempted_traditional,OPP_reboundsOffensive_traditional,OPP_reboundsDefensive_traditional,OPP_reboundsTotal_traditional,OPP_assists_traditional,OPP_steals_traditional,OPP_blocks_traditional,OPP_turnovers_traditional,OPP_foulsPersonal_traditional,OPP_points_traditional,OPP_MINUTES_PLAYED,OPP_pointsOffTurnovers_misc,OPP_pointsSecondChance_misc,OPP_pointsFastBreak_misc,OPP_pointsPaint_misc,OPP_blocksAgainst_misc,OPP_offensiveRating_advanced,OPP_defensiveRating_advanced,OPP_netRating_advanced,OPP_assistPercentage_advanced,OPP_assistToTurnover_advanced,OPP_assistRatio_advanced,OPP_offensiveReboundPercentage_advanced,OPP_defensiveReboundPercentage_advanced,OPP_reboundPercentage_advanced,OPP_turnoverRatio_advanced,OPP_effectiveFieldGoalPercentage_advanced,OPP_trueShootingPercentage_advanced,OPP_usagePercentage_advanced,OPP_estimatedPace_advanced,OPP_pace_advanced,OPP_possessions_advanced,OPP_PIE_advanced,OPP_effectiveFieldGoalPercentage_fourfactors,OPP_freeThrowAttemptRate_fourfactors,OPP_teamTurnoverPercentage_fourfactors,OPP_oppEffectiveFieldGoalPercentage_fourfactors,OPP_oppFreeThrowAttemptRate_fourfactors,OPP_oppTeamTurnoverPercentage_fourfactors,OPP_oppOffensiveReboundPercentage_fourfactors,OPP_foulsDrawn_misc,OPP_percentageFieldGoalsAttempted2pt_scoring,OPP_percentageFieldGoalsAttempted3pt_scoring,OPP_percentagePoints2pt_scoring,OPP_percentagePointsMidrange2pt_scoring,OPP_percentagePoints3pt_scoring,OPP_percentagePointsFastBreak_scoring,OPP_percentagePointsFreeThrow_scoring,OPP_percentagePointsOffTurnovers_scoring,OPP_percentagePointsPaint_scoring,OPP_percentageAssisted2pt_scoring,OPP_percentageUnassisted2pt_scoring,OPP_percentageAssisted3pt_scoring,OPP_percentageUnassisted3pt_scoring,OPP_percentageAssistedFGM_scoring,OPP_percentageUnassistedFGM_scoring,OPP_threePointersPercentage_traditional,OPP_freeThrowsPercentage_traditional,OPP_percentageFieldGoalsMade_usage,OPP_percentageFieldGoalsAttempted_usage,OPP_percentageThreePointersMade_usage,OPP_percentageThreePointersAttempted_usage,OPP_percentageFreeThrowsMade_usage,OPP_percentageFreeThrowsAttempted_usage,OPP_percentageReboundsOffensive_usage,OPP_percentageReboundsDefensive_usage,OPP_percentageReboundsTotal_usage,OPP_percentageAssists_usage,OPP_percentageTurnovers_usage,OPP_percentageSteals_usage,OPP_percentageBlocks_usage,OPP_percentageBlocksAllowed_usage,OPP_percentagePersonalFouls_usage,OPP_percentagePersonalFoulsDrawn_usage,OPP_percentagePoints_usage,OPP_plusMinusPoints_traditional,MATCHUP,SEASON,TEAM_NAME,OPPONENT_NAME,num_absent_other,num_injured,num_personal,num_present,num_resting,num_suspended,player_perf_score_mean,player_perf_score_sum,top_player_absent_other,top_player_absent_other_rate,top_player_absent_rate,top_player_count,top_player_injured,top_player_injury_rate,top_player_personal,top_player_personal_rate,top_player_resting,top_player_resting_rate,top_player_suspended,top_player_suspension_rate
0,0041000405,2011-06-09,1610612742,1610612748,1.0,1.0,9.0,1,0,3,0,112.0,1.64,1.76,39.0,69.0,13.0,19.0,21.0,27.0,4.0,22.0,26.0,23.0,8.0,3.0,11.0,20.0,240.000000,21.0,7.0,14.0,34.0,4.0,124.483000,115.769097,8.688201,0.156017,1.707951,17.436076,0.023313,0.119843,0.074096,9.238958,0.721924,0.717079,0.192045,89.160360,89.400925,60.698056,0.112384,0.662704,0.404485,0.124605,0.583640,0.370735,0.199594,0.292299,3.331250,0.652529,0.347471,0.490485,0.129948,0.335592,0.154415,0.173923,0.205318,0.360644,0.445141,0.456595,0.471740,0.191593,0.662219,0.337781,0.495611,0.722107,0.201647,0.198718,0.200506,0.198868,0.198774,0.195838,0.142726,0.209231,0.212778,0.218416,0.208787,0.205196,0.216426,0.218662,0.193322,0.194688,0.200734,9.178333,37.0,70.0,8.0,20.0,21.0,26.0,9.0,27.0,36.0,25.0,5.0,4.0,16.0,26.0,103.0,240.000000,15.0,11.0,11.0,46.0,3.0,115.847194,123.534965,-7.678000,0.181847,1.192205,17.331146,0.049004,0.164362,0.104834,12.073757,0.634362,0.671524,0.194274,89.161361,90.000096,58.286111,0.087416,0.584849,0.377992,0.199160,0.661934,0.408766,0.123801,0.118958,2.993056,0.700720,0.299280,0.638474,0.146638,0.193494,0.088319,0.153588,0.102425,0.491671,0.463771,0.327410,0.194375,0.143542,0.648529,0.337027,0.209442,0.440016,0.198049,0.202923,0.175064,0.183521,0.178636,0.175533,0.202980,0.199053,0.198641,0.202974,0.174229,0.167085,0.182146,0.156903,0.199387,0.189628,0.198622,-7.056458,DAL vs. MIA,2010-11,dallas mavericks,miami heat,3,0,0,9,0,0,14.808333,177.7,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0
1,0041000405,2011-06-09,1610612748,1610612742,0.0,0.0,-9.0,1,0,2,0,103.0,1.76,1.64,37.0,70.0,8.0,20.0,21.0,26.0,9.0,27.0,36.0,25.0,5.0,4.0,16.0,26.0,240.000000,15.0,11.0,11.0,46.0,3.0,115.847194,123.534965,-7.678000,0.181847,1.192205,17.331146,0.049004,0.164362,0.104834,12.073757,0.634362,0.671524,0.194274,89.161361,90.000096,58.286111,0.087416,0.584849,0.377992,0.199160,0.661934,0.408766,0.123801,0.118958,2.993056,0.700720,0.299280,0.638474,0.146638,0.193494,0.088319,0.153588,0.102425,0.491671,0.463771,0.327410,0.194375,0.143542,0.648529,0.337027,0.209442,0.440016,0.198049,0.202923,0.175064,0.183521,0.178636,0.175533,0.202980,0.199053,0.198641,0.202974,0.174229,0.167085,0.182146,0.156903,0.199387,0.189628,0.198622,-7.056458,39.0,69.0,13.0,19.0,21.0,27.0,4.0,22.0,26.0,23.0,8.0,3.0,11.0,20.0,112.0,240.000000,21.0,7.0,14.0,34.0,4.0,124.483000,115.769097,8.688201,0.156017,1.707951,17.436076,0.023313,0.119843,0.074096,9.238958,0.721924,0.717079,0.192045,89.160360,89.400925,60.698056,0.112384,0.662704,0.404485,0.124605,0.583640,0.370735,0.199594,0.292299,3.331250,0.652529,0.347471,0.490485,0.129948,0.335592,0.154415,0.173923,0.205318,0.360644,0.445141,0.456595,0.471740,0.191593,0.662219,0.337781,0.495611,0.722107,0.201647,0.198718,0.200506,0.198868,0.198774,0.195838,0.142726,0.209231,0.212778,0.218416,0.208787,0.205196,0.216426,0.218662,0.193322,0.194688,0.200734,9.178333,MIA @ DAL,2010-11,miami heat,dallas mavericks,2,0,0,10,0,0,14.725000,176.7,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0
2,0041000404,2011-06-07,1610612742,1610612748,1.0,1.0,3.0,1,0,2,0,86.0,1.52,1.95,29.0,73.0,4.0,19.0,24.0,30.0,12.0,29.0,41.0,13.0,7.0,2.0,11.0,18.0,240.000000,18.0,15.0,6.0,38.0,5.0,100.873868,96.398639,4.442590,0.113874,0.536158,12.644361,0.056293,0.118563,0.086590,11.815931,0.378804,0.432576,0.195710,85.370765,85.688906,58.694167,0.099991,0.424794,0.406251,0.130057,0.441711,0.319575,0.175969,0.327472,3.498472,0.610423,0.376591,0.451375,0.096813,0.113327,0.048074,0.228900,0.154725,0.354562,0.249309,0.437635,0.254306,0.000000,0.375732,0.418017,0.082695,0.661237,0.197312,0.199356,0.143681,0.182896,0.205958,0.209901,0.204594,0.195762,0.199805,0.201086,0.201356,0.168984,0.134826,0.228042,0.195406,0.206492,0.198223,4.126111,32.0,75.0,2.0,14.0,17.0,24.0,15.0,29.0,44.0,19.0,8.0,5.0,13.0,23.0,83.0,240.000000,12.0,15.0,11.0,40.0,2.0,95.933215,101.875465,-5.924340,0.141166,0.970573,18.303035,0.058802,0.120893,0.092651,9.220799,0.364425,0.409425,0.191351,85.377647,85.899028,59.846458,0.098935,0.444339,0.320926,0.173622,0.423996,0.412444,0.129097,0.305750,3.006319,0.741355,0.247534,0.664792,0.230533,0.060694,0.108858,0.196067,0.228346,0.434259,0.431126,0.429568,0.060694,0.000000,0.491821,0.429568,0.024278,0.459279,0.197191,0.200027,0.060694,0.187825,0.225926,0.209875,0.179078,0.194578,0.198288,0.199801,0.178217,0.199264,0.189727,0.169931,0.199084,0.208150,0.201120,-2.981667,DAL vs. MIA,2010-11,dallas mavericks,miami heat,2,0,0,10,0,0,12.725000,152.7,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0
3,0041000404,2011-06-07,1610612748,1610612742,0.0,0.0,-3.0,1,0,3,0,83.0,1.95,1.52,32.0,75.0,2.0,14.0,17.0,24.0,15.0,29.0,44.0,19.0,8.0,5.0,13.0,23.0,240.000000,12.0,15.0,11.0,40.0,2.0,95.933215,101.875465,-5.924340,0.141166,0.970573,18.303035,0.058802,0.120893,0.092651,9.220799,0.364425,0.409425,0.191351,85.377647,85.899028,59.846458,0.098935,0.444339,0.320926,0.173622,0.423996,0.412444,0.129097,0.305750,3.006319,0.741355,0.247534,0.664792,0.230533,0.060694,0.108858,0.196067,0.228346,0.434259,0.431126,0.429568,0.060694,0.000000,0.491821,0.429568,0.024278,0.459279,0.197191,0.200027,0.060694,0.187825,0.225926,0.209875,0.179078,0.194578,0.198288,0.199801,0.178217,0.199264,0.189727,0.169931,0.199084,0.208150,0.201120,-2.981667,29.0,73.0,4.0,19.0,24.0,30.0,12.0,29.0,41.0,13.0,7.0,2.0,11.0,18.0,86.0,240.000000,18.0,15.0,6.0,38.0,5.0,100.873868,96.398639,4.442590,0.113874,0.536158,12.644361,0.056293,0.118563,0.086590,11.815931,0.378804,0.432576,0.195710,85.370765,85.688906,58.694167,0.099991,0.424794,0.406251,0.130057,0.441711,0.319575,0.175969,0.327472,3.498472,0.610423,0.376591,0.451375,0.096813,0.113327,0.048074,0.228900,0.154725,0.354562,0.249309,0.437635,0.254306,0.000000,0.375732,0.418017,0.082695,0.661237,0.197312,0.199356,0.143681,0.182896,0.205958,0.209901,0.204594,0.195762,0.199805,0.201086,0.201356,0.168984,0.134826,0.228042,0.195406,0.206492,0.198223,4.126111,MIA @ DAL,2010-11,miami heat,dallas mavericks,3,0,0,9,0,0,13.691667,164.3,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0
4,0041000403,2011-06-05,1610612742,1610612748,1.0,0.0,-2.0,1,0,2,0,86.0,1.55,1.90,28.0,70.0,8.0,21.0,22.0,27.0,12.0,30.0,42.0,18.0,3.0,8.0,14.0,14.0,240.016667,15.0,10.0,16.0,22.0,5.0,99.437171,100.956579,-1.501437,0.159033,0.716335,15.023873,0.055469,0.131777,0.093695,9.475342,0.462078,0.546024,0.194047,86.240661,87.203469,60.724464,0.107783,0.459188,0.386461,0.165660,0.487271,0.205206,0.148102,0.226107,3.787306,0.698464,0.301050,0.448428,0.178193,0.270369,0.196699,0.280892,0.112813,0.270060,0.440091,0.466929,0.594542,0.000000,0.581981,0.384202,0.283477,0.715446,0.203179,0.199818,0.197541,0.218848,0.191637,0.191682,0.201641,0.196560,0.198357,0.195042,0.182928,0.158187,0.193325,0.183023,0.180651,0.202986,0.200672,1.866676,34.0,78.0,8.0,19.0,12.0,15.0,9.0,27.0,36.0,20.0,8.0,5.0,10.0,27.0,88.0,240.000000,19.0,6.0,14.0,40.0,8.0,101.587653,97.731354,3.851229,0.149351,0.993837,17.983674,0.037043,0.122203,0.079955,9.223090,0.437792,0.478918,0.190763,86.238558,87.500490,57.617431,0.097241,0.490690,0.203339,0.146303,0.462031,0.388643,0.167176,0.306525,1.977222,0.684235,0.289028,0.560525,0.137528,0.266296,0.196057,0.122296,0.194572,0.422997,0.458541,0.264237,0.388333,0.160972,0.671875,0.250695,0.227667,0.447583,0.200026,0.197254,0.225424,0.211465,0.256346,0.267137,0.188497,0.199093,0.195778,0.198939,0.158231,0.182757,0.180563,0.195386,0.198620,0.231920,0.204162,0.124236,DAL vs. MIA,2010-11,dallas mavericks,miami heat,2,0,0,10,0,0,13.366667,160.4,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38076,0022400087,2024-10-26,1610612746,1610612743,0.0,1.0,5.0,1,0,3,0,109.0,3.31,1.25,40.0,82.0,12.0,33.0,17.0,21.0,11.0,33.0,44.0,30.0,4.0,5.0,16.0,24.0,240.000000,12.0,13.0,9.0,52.0,4.0,113.362125,106.258118,7.124118,0.176159,0.721969,23.426660,0.047712,0.124879,0.090236,9.414285,0.445455,0.526659,0.199489,97.398442,97.201100,56.666111,0.080197,0.563024,0.254146,0.174821,0.487391,0.278288,0.102450,0.230944,2.985000,0.509191,0.385670,0.406454,0.021151,0.199629,0.090298,0.192666,0.078131,0.385304,0.443182,0.265984,0.413165,0.071557,0.496141,0.213026,0.193859,0.390767,0.192688,0.201909,0.190237,0.200174,0.189189,0.203901,0.197160,0.202369,0.202316,0.199148,0.183938,0.200451,0.194223,0.230847,0.212717,0.209447,0.196583,1.675764,35.0,87.0,14.0,35.0,20.0,24.0,10.0,27.0,37.0,20.0,13.0,4.0,10.0,22.0,104.0,240.000000,23.0,13.0,9.0,34.0,5.0,106.772104,112.970514,-6.198410,0.151218,1.326062,15.111083,0.038915,0.127791,0.079419,6.563722,0.458367,0.510433,0.192078,97.401411,97.299438,63.261667,0.071764,0.485370,0.277949,0.102535,0.561151,0.256051,0.174513,0.279869,3.273889,0.633511,0.366489,0.403140,0.070555,0.275650,0.084249,0.274251,0.334755,0.332739,0.343786,0.480728,0.542070,0.124319,0.459480,0.365033,0.413705,0.785538,0.183716,0.200075,0.180334,0.200766,0.200539,0.197205,0.205557,0.206304,0.204789,0.192580,0.203496,0.194035,0.233618,0.195868,0.185764,0.189378,0.187967,0.159167,LAC @ DEN,2024-25,los angeles clippers,denver nuggets,3,0,0,10,0,0,15.369231,199.8,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0
38077,0041600144,2017-04-24,1610612744,1610612757,0.0,1.0,25.0,1,0,1,0,128.0,1.39,2.53,46.0,86.0,17.0,29.0,19.0,27.0,6.0,39.0,45.0,27.0,7.0,9.0,10.0,15.0,240.033333,14.0,4.0,14.0,38.0,3.0,124.959651,101.338634,23.627788,0.159116,0.671833,19.085578,0.021503,0.144437,0.091251,6.107187,0.574273,0.591628,0.197779,101.820948,101.899357,49.736912,0.125485,0.638266,0.309432,0.098037,0.467547,0.339688,0.108453,0.152001,2.018609,0.696467,0.303533,0.483538,0.161477,0.283940,0.072509,0.151561,0.089193,0.322061,0.475786,0.443392,0.361629,0.112888,0.527949,0.391229,0.326586,0.555776,0.197415,0.201708,0.149023,0.178059,0.220644,0.203437,0.120788,0.203820,0.199202,0.192156,0.155522,0.188083,0.159018,0.167407,0.190030,0.201668,0.194639,15.950840,33.0,85.0,13.0,39.0,24.0,29.0,7.0,32.0,39.0,14.0,7.0,3.0,11.0,20.0,103.0,240.000000,5.0,12.0,4.0,28.0,9.0,101.844146,125.220750,-23.395333,0.127247,0.459810,7.659931,0.026963,0.149890,0.079387,7.898889,0.445574,0.497418,0.197088,101.821058,101.799083,58.903472,0.072797,0.464278,0.342151,0.107807,0.638345,0.314603,0.097185,0.141563,2.000625,0.569321,0.430679,0.416382,0.113276,0.266090,0.021082,0.265775,0.045946,0.303253,0.232639,0.629861,0.465324,0.134190,0.356060,0.529634,0.246725,0.660928,0.196420,0.199501,0.202839,0.198949,0.188219,0.189613,0.218232,0.200356,0.196915,0.202024,0.185506,0.179140,0.179408,0.188289,0.199278,0.189102,0.195214,-15.393889,GSW @ POR,2016-17,golden state warriors,portland trail blazers,0,1,0,12,0,0,17.576923,228.5,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0
38078,0041600144,2017-04-24,1610612757,1610612744,1.0,0.0,-25.0,1,1,1,1,103.0,2.53,1.39,33.0,85.0,13.0,39.0,24.0,29.0,7.0,32.0,39.0,14.0,7.0,3.0,11.0,20.0,240.000000,5.0,12.0,4.0,28.0,9.0,101.844146,125.220750,-23.395333,0.127247,0.459810,7.659931,0.026963,0.149890,0.079387,7.898889,0.445574,0.497418,0.197088,101.821058,101.799083,58.903472,0.072797,0.464278,0.342151,0.107807,0.638345,0.314603,0.097185,0.141563,2.000625,0.569321,0.430679,0.416382,0.113276,0.266090,0.021082,0.265775,0.045946,0.303253,0.232639,0.629861,0.465324,0.134190,0.356060,0.529634,0.246725,0.660928,0.196420,0.199501,0.202839,0.198949,0.188219,0.189613,0.218232,0.200356,0.196915,0.202024,0.185506,0.179140,0.179408,0.188289,0.199278,0.189102,0.195214,-15.393889,46.0,86.0,17.0,29.0,19.0,27.0,6.0,39.0,45.0,27.0,7.0,9.0,10.0,15.0,128.0,240.033333,14.0,4.0,14.0,38.0,3.0,124.959651,101.338634,23.627788,0.159116,0.671833,19.085578,0.021503,0.144437,0.091251,6.107187,0.574273,0.591628,0.197779,101.820948,101.899357,49.736912,0.125485,0.638266,0.309432,0.098037,0.467547,0.339688,0.108453,0.152001,2.018609,0.696467,0.303533,0.483538,0.161477,0.283940,0.072509,0.151561,0.089193,0.322061,0.475786,0.443392,0.361629,0.112888,0.527949,0.391229,0.326586,0.555776,0.197415,0.201708,0.149023,0.178059,0.220644,0.203437,0.120788,0.203820,0.199202,0.192156,0.155522,0.188083,0.159018,0.167407,0.190030,0.201668,0.194639,15.950840,POR vs. GSW,2016-17,portland trail blazers,golden state warriors,0,1,0,12,0,0,13.061538,169.8,0,0.0,0.2,5,1,0.2,0,0.0,0,0.0,0,0.0
38079,0041600174,2017-04-23,1610612746,1610612762,0.0,0.0,-7.0,1,0,4,0,98.0,1.70,1.93,33.0,75.0,11.0,32.0,21.0,29.0,6.0,25.0,31.0,17.0,8.0,0.0,9.0,18.0,240.000000,4.0,9.0,1.0,36.0,3.0,105.526958,114.612326,-9.062743,0.158487,1.224792,9.869785,0.027667,0.136051,0.075938,7.550153,0.470915,0.523953,0.196106,90.000755,92.499403,61.731944,0.079637,0.515302,0.389761,0.099057,0.611337,0.299591,0.144572,0.216650,2.398264,0.545538,0.438420,0.411841,0.112741,0.283564,0.016042,0.254109,0.033678,0.299100,0.523208,0.410264,0.613097,0.026208,0.657032,0.276440,0.276600,0.678282,0.195867,0.199402,0.179647,0.197842,0.197776,0.196380,0.161846,0.189472,0.188428,0.187360,0.217585,0.167650,0.000000,0.219571,0.201685,0.204162,0.196494,-5.767708,40.0,74.0,10.0,22.0,15.0,21.0,7.0,35.0,42.0,24.0,7.0,3.0,12.0,17.0,105.0,240.016667,17.0,13.0,7.0,58.0,0.0,114.779251,105.963287,8.798521,0.146641,1.804977,21.007916,0.038889,0.152663,0.101374,10.618881,0.616318,0.632372,0.192232,90.000485,92.499108,56.007083,0.121128,0.610731,0.285767,0.144788,0.512997,0.387243,0.098771,0.149382,2.278314,0.606645,0.342811,0.432184,0.010235,0.349148,0.080264,0.124603,0.194886,0.421949,0.357923,0.460700,0.584751,0.121033,0.571900,0.334009,0.381367,0.514805,0.202307,0.197492,0.217908,0.192665,0.212821,0.209094,0.197643,0.195777,0.198899,0.191070,0.175250,0.172667,0.224207,0.000000,0.192367,0.195124,0.202119,5.759461,LAC @ UTA,2016-17,los angeles clippers,utah jazz,4,0,0,9,0,0,12.284615,159.7,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0

# Add OPP cols for player stats

In [ ]:
opp_cols = [f"OPP_{col}" for col in cols_player_stats]
df_opp = match_dataset.rename(columns={col: f"OPP_{col}" for col in cols_player_stats})

match_dataset = pd.merge(
    match_dataset,
    df_opp[['GAME_ID', 'TEAM_ID'] + opp_cols],
    on=['GAME_ID', 'TEAM_ID'],
    how='left'
)

In [ ]:
match_dataset

,GAME_ID,GAME_DATE,TEAM_ID,OPP_TEAM_ID,IS_HOME,IS_WIN,POINT_DIFF,has_absent,has_top_absent,num_absent,top_player_absent,points_traditional,ODDS,OPP_ODDS,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,MINUTES_PLAYED,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,blocksAgainst_misc,offensiveRating_advanced,defensiveRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,threePointersPercentage_traditional,freeThrowsPercentage_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage,plusMinusPoints_traditional,OPP_fieldGoalsMade_traditional,OPP_fieldGoalsAttempted_traditional,OPP_threePointersMade_traditional,OPP_threePointersAttempted_traditional,OPP_freeThrowsMade_traditional,OPP_freeThrowsAttempted_traditional,OPP_reboundsOffensive_traditional,OPP_reboundsDefensive_traditional,OPP_reboundsTotal_traditional,OPP_assists_traditional,OPP_steals_traditional,OPP_blocks_traditional,OPP_turnovers_traditional,OPP_foulsPersonal_traditional,OPP_points_traditional,OPP_MINUTES_PLAYED,OPP_pointsOffTurnovers_misc,OPP_pointsSecondChance_misc,OPP_pointsFastBreak_misc,OPP_pointsPaint_misc,OPP_blocksAgainst_misc,OPP_offensiveRating_advanced,OPP_defensiveRating_advanced,OPP_netRating_advanced,OPP_assistPercentage_advanced,OPP_assistToTurnover_advanced,OPP_assistRatio_advanced,OPP_offensiveReboundPercentage_advanced,OPP_defensiveReboundPercentage_advanced,OPP_reboundPercentage_advanced,OPP_turnoverRatio_advanced,OPP_effectiveFieldGoalPercentage_advanced,OPP_trueShootingPercentage_advanced,OPP_usagePercentage_advanced,OPP_estimatedPace_advanced,OPP_pace_advanced,OPP_possessions_advanced,OPP_PIE_advanced,OPP_effectiveFieldGoalPercentage_fourfactors,OPP_freeThrowAttemptRate_fourfactors,OPP_teamTurnoverPercentage_fourfactors,OPP_oppEffectiveFieldGoalPercentage_fourfactors,OPP_oppFreeThrowAttemptRate_fourfactors,OPP_oppTeamTurnoverPercentage_fourfactors,OPP_oppOffensiveReboundPercentage_fourfactors,OPP_foulsDrawn_misc,OPP_percentageFieldGoalsAttempted2pt_scoring,OPP_percentageFieldGoalsAttempted3pt_scoring,OPP_percentagePoints2pt_scoring,OPP_percentagePointsMidrange2pt_scoring,OPP_percentagePoints3pt_scoring,OPP_percentagePointsFastBreak_scoring,OPP_percentagePointsFreeThrow_scoring,OPP_percentagePointsOffTurnovers_scoring,OPP_percentagePointsPaint_scoring,OPP_percentageAssisted2pt_scoring,OPP_percentageUnassisted2pt_scoring,OPP_percentageAssisted3pt_scoring,OPP_percentageUnassisted3pt_scoring,OPP_percentageAssistedFGM_scoring,OPP_percentageUnassistedFGM_scoring,OPP_threePointersPercentage_traditional,OPP_freeThrowsPercentage_traditional,OPP_percentageFieldGoalsMade_usage,OPP_percentageFieldGoalsAttempted_usage,OPP_percentageThreePointersMade_usage,OPP_percentageThreePointersAttempted_usage,OPP_percentageFreeThrowsMade_usage,OPP_percentageFreeThrowsAttempted_usage,OPP_percentageReboundsOffensive_usage,OPP_percentageReboundsDefensive_usage,OPP_percentageReboundsTotal_usage,OPP_percentageAssists_usage,OPP_percentageTurnovers_usage,OPP_percentageSteals_usage,OPP_percentageBlocks_usage,OPP_percentageBlocksAllowed_usage,OPP_percentagePersonalFouls_usage,OPP_percentagePersonalFoulsDrawn_usage,OPP_percentagePoints_usage,OPP_plusMinusPoints_traditional,MATCHUP,SEASON,TEAM_NAME,OPPONENT_NAME,num_absent_other,num_injured,num_personal,num_present,num_resting,num_suspended,player_perf_score_mean,player_perf_score_sum,top_player_absent_other,top_player_absent_other_rate,top_player_absent_rate,top_player_count,top_player_injured,top_player_injury_rate,top_player_personal,top_player_personal_rate,top_player_resting,top_player_resting_rate,top_player_suspended,top_player_suspension_rate,OPP_num_absent,OPP_num_injured,OPP_num_personal,OPP_num_present,OPP_num_resting,OPP_num_suspended,OPP_num_absent_other,OPP_player_perf_score_mean,OPP_player_perf_score_sum,OPP_top_player_absent,OPP_top_player_absent_rate,OPP_top_player_count,OPP_top_player_injured,OPP_top_player_injury_rate,OPP_top_player_personal,OPP_top_player_personal_rate,OPP_top_player_resting,OPP_top_player_resting_rate,OPP_top_player_suspended,OPP_top_player_suspension_rate,OPP_top_player_absent_other,OPP_top_player_absent_other_rate
0,0041000405,2011-06-09,1610612742,1610612748,1.0,1.0,9.0,1,0,3,0,112.0,1.64,1.76,39.0,69.0,13.0,19.0,21.0,27.0,4.0,22.0,26.0,23.0,8.0,3.0,11.0,20.0,240.000000,21.0,7.0,14.0,34.0,4.0,124.483000,115.769097,8.688201,0.156017,1.707951,17.436076,0.023313,0.119843,0.074096,9.238958,0.721924,0.717079,0.192045,89.160360,89.400925,60.698056,0.112384,0.662704,0.404485,0.124605,0.583640,0.370735,0.199594,0.292299,3.331250,0.652529,0.347471,0.490485,0.129948,0.335592,0.154415,0.173923,0.205318,0.360644,0.445141,0.456595,0.471740,0.191593,0.662219,0.337781,0.495611,0.722107,0.201647,0.198718,0.200506,0.198868,0.198774,0.195838,0.142726,0.209231,0.212778,0.218416,0.208787,0.205196,0.216426,0.218662,0.193322,0.194688,0.200734,9.178333,37.0,70.0,8.0,20.0,21.0,26.0,9.0,27.0,36.0,25.0,5.0,4.0,16.0,26.0,103.0,240.000000,15.0,11.0,11.0,46.0,3.0,115.847194,123.534965,-7.678000,0.181847,1.192205,17.331146,0.049004,0.164362,0.104834,12.073757,0.634362,0.671524,0.194274,89.161361,90.000096,58.286111,0.087416,0.584849,0.377992,0.199160,0.661934,0.408766,0.123801,0.118958,2.993056,0.700720,0.299280,0.638474,0.146638,0.193494,0.088319,0.153588,0.102425,0.491671,0.463771,0.327410,0.194375,0.143542,0.648529,0.337027,0.209442,0.440016,0.198049,0.202923,0.175064,0.183521,0.178636,0.175533,0.202980,0.199053,0.198641,0.202974,0.174229,0.167085,0.182146,0.156903,0.199387,0.189628,0.198622,-7.056458,DAL vs. MIA,2010-11,dallas mavericks,miami heat,3,0,0,9,0,0,14.808333,177.7,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0,3,0,0,9,0,0,3,14.808333,177.7,0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
1,0041000405,2011-06-09,1610612748,1610612742,0.0,0.0,-9.0,1,0,2,0,103.0,1.76,1.64,37.0,70.0,8.0,20.0,21.0,26.0,9.0,27.0,36.0,25.0,5.0,4.0,16.0,26.0,240.000000,15.0,11.0,11.0,46.0,3.0,115.847194,123.534965,-7.678000,0.181847,1.192205,17.331146,0.049004,0.164362,0.104834,12.073757,0.634362,0.671524,0.194274,89.161361,90.000096,58.286111,0.087416,0.584849,0.377992,0.199160,0.661934,0.408766,0.123801,0.118958,2.993056,0.700720,0.299280,0.638474,0.146638,0.193494,0.088319,0.153588,0.102425,0.491671,0.463771,0.327410,0.194375,0.143542,0.648529,0.337027,0.209442,0.440016,0.198049,0.202923,0.175064,0.183521,0.178636,0.175533,0.202980,0.199053,0.198641,0.202974,0.174229,0.167085,0.182146,0.156903,0.199387,0.189628,0.198622,-7.056458,39.0,69.0,13.0,19.0,21.0,27.0,4.0,22.0,26.0,23.0,8.0,3.0,11.0,20.0,112.0,240.000000,21.0,7.0,14.0,34.0,4.0,124.483000,115.769097,8.688201,0.156017,1.707951,17.436076,0.023313,0.119843,0.074096,9.238958,0.721924,0.717079,0.192045,89.160360,89.400925,60.698056,0.112384,0.662704,0.404485,0.124605,0.583640,0.370735,0.199594,0.292299,3.331250,0.652529,0.347471,0.490485,0.129948,0.335592,0.154415,0.173923,0.205318,0.360644,0.445141,0.456595,0.471740,0.191593,0.662219,0.337781,0.495611,0.722107,0.201647,0.198718,0.200506,0.198868,0.198774,0.195838,0.142726,0.209231,0.212778,0.218416,0.208787,0.205196,0.216426,0.218662,0.193322,0.194688,0.200734,9.178333,MIA @ DAL,2010-11,miami heat,dallas mavericks,2,0,0,10,0,0,14.725000,176.7,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0,2,0,0,10,0,0,2,14.725000,176.7,0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
2,0041000404,2011-06-07,1610612742,1610612748,1.0,1.0,3.0,1,0,2,0,86.0,1.52,1.95,29.0,73.0,4.0,19.0,24.0,30.0,12.0,29.0,41.0,13.0,7.0,2.0,11.0,18.0,240.000000,18.0,15.0,6.0,38.0,5.0,100.873868,96.398639,4.442590,0.113874,0.536158,12.644361,0.056293,0.118563,0.086590,11.815931,0.378804,0.432576,0.195710,85.370765,85.688906,58.694167,0.099991,0.424794,0.406251,0.130057,0.441711,0.319575,0.175969,0.327472,3.498472,0.610423,0.376591,0.451375,0.096813,0.113327,0.048074,0.228900,0.154725,0.354562,0.249309,0.437635,0.254306,0.000000,0.375732,0.418017,0.082695,0.661237,0.197312,0.199356,0.143681,0.182896,0.205958,0.209901,0.204594,0.195762,0.199805,0.201086,0.201356,0.168984,0.134826,0.228042,0.195406,0.206492,0.198223,4.126111,32.0,75.0,2.0,14.0,17.0,24.0,15.0,29.0,44.0,19.0,8.0,5.0,13.0,23.0,83.0,240.000000,12.0,15.0,11.0,40.0,2.0,95.933215,101.875465,-5.924340,0.141166,0.970573,18.303035,0.058802,0.120893,0.092651,9.220799,0.364425,0.409425,0.191351,85.377647,85.899028,59.846458,0.098935,0.444339,0.320926,0.173622,0.423996,0.412444,0.129097,0.305750,3.006319,0.741355,0.247534,0.664792,0.230533,0.060694,0.108858,0.196067,0.228346,0.434259,0.431126,0.429568,0.060694,0.000000,0.491821,0.429568,0.024278,0.459279,0.197191,0.200027,0.060694,0.187825,0.225926,0.209875,0.179078,0.194578,0.198288,0.199801,0.178217,0.199264,0.189727,0.169931,0.199084,0.208150,0.201120,-2.981667,DAL vs. MIA,2010-11,dallas mavericks,miami heat,2,0,0,10,0,0,12.725000,152.7,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0,2,0,0,10,0,0,2,12.725000,152.7,0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
3,0041000404,2011-06-07,1610612748,1610612742,0.0,0.0,-3.0,1,0,3,0,83.0,1.95,1.52,32.0,75.0,2.0,14.0,17.0,24.0,15.0,29.0,44.0,19.0,8.0,5.0,13.0,23.0,240.000000,12.0,15.0,11.0,40.0,2.0,95.933215,101.875465,-5.924340,0.141166,0.970573,18.303035,0.058802,0.120893,0.092651,9.220799,0.364425,0.409425,0.191351,85.377647,85.899028,59.846458,0.098935,0.444339,0.320926,0.173622,0.423996,0.412444,0.129097,0.305750,3.006319,0.741355,0.247534,0.664792,0.230533,0.060694,0.108858,0.196067,0.228346,0.434259,0.431126,0.429568,0.060694,0.000000,0.491821,0.429568,0.024278,0.459279,0.197191,0.200027,0.060694,0.187825,0.225926,0.209875,0.179078,0.194578,0.198288,0.199801,0.178217,0.199264,0.189727,0.169931,0.199084,0.208150,0.201120,-2.981667,29.0,73.0,4.0,19.0,24.0,30.0,12.0,29.0,41.0,13.0,7.0,2.0,11.0,18.0,86.0,240.000000,18.0,15.0,6.0,38.0,5.0,100.873868,96.398639,4.442590,0.113874,0.536158,12.644361,0.056293,0.118563,0.086590,11.815931,0.378804,0.432576,0.195710,85.370765,85.688906,58.694167,0.099991,0.424794,0.406251,0.130057,0.441711,0.319575,0.175969,0.327472,3.498472,0.610423,0.376591,0.451375,0.096813,0.113327,0.048074,0.228900,0.154725,0.354562,0.249309,0.437635,0.254306,0.000000,0.375732,0.418017,0.082695,0.661237,0.197312,0.199356,0.143681,0.182896,0.205958,0.209901,0.204594,0.195762,0.199805,0.201086,0.201356,0.168984,0.134826,0.228042,0.195406,0.206492,0.198223,4.126111,MIA @ DAL,2010-11,miami heat,dallas mavericks,3,0,0,9,0,0,13.691667,164.3,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0,3,0,0,9,0,0,3,13.691667,164.3,0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
4,0041000403,2011-06-05,1610612742,1610612748,1.0,0.0,-2.0,1,0,2,0,86.0,1.55,1.90,28.0,70.0,8.0,21.0,22.0,27.0,12.0,30.0,42.0,18.0,3.0,8.0,14.0,14.0,240.016667,15.0,10.0,16.0,22.0,5.0,99.437171,100.956579,-1.501437,0.159033,0.716335,15.023873,0.055469,0.131777,0.093695,9.475342,0.462078,0.546024,0.194047,86.240661,87.203469,60.724464,0.107783,0.459188,0.386461,0.165660,0.487271,0.205206,0.148102,0.226107,3.787306,0.698464,0.301050,0.448428,0.178193,0.270369,0.196699,0.280892,0.112813,0.270060,0.440091,0.466929,0.594542,0.000000,0.581981,0.384202,0.283477,0.715446,0.203179,0.199818,0.197541,0.218848,0.191637,0.191682,0.201641,0.196560,0.198357,0.195042,0.182928,0.158187,0.193325,0.183023,0.180651,0.202986,0.200672,1.866676,34.0,78.0,8.0,19.0,12.0,15.0,9.0,27.0,36.0,20.0,8.0,5.0,10.0,27.0,88.0,240.000000,19.0,6.0,14.0,40.0,8.0,101.587653,97.731354,3.851229,0.149351,0.993837,17.983674,0.037043,0.122203,0.079955,9.223090,0.437792,0.478918,0.190763,86.238558,87.500490,57.617431,0.097241,0.490690,0.203339,0.146303,0.462031,0.388643,0.167176,0.306525,1.977222,0.684235,0.289028,0.560525,0.137528,0.266296,0.196057,0.122296,0.194572,0.422997,0.458541,0.264237,0.388333,0.160972,0.671875,0.250695,0.227667,0.447583,0.200026,0.197254,0.225424,0.211465,0.256346,0.267137,0.188497,0.199093,0.195778,0.198939,0.158231,0.182757,0.180563,0.195386,0.198620,0.231920,0.204162,0.124236,DAL vs. MIA,2010-11,dallas mavericks,miami heat,2,0,0,10,0,0,13.366667,160.4,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0,2,0,0,10,0,0,2,13.366667,160.4,0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38076,0022400087,2024-10-26,1610612746,1610612743,0.0,1.0,5.0,1,0,3,0,109.0,3.31,1.25,40.0,82.0,12.0,33.0,17.0,21.0,11.0,33.0,44.0,30.0,4.0,5.0,16.0,24.0,240.000000,12.0,13.0,9.0,52.0,4.0,113.362125,106.258118,7.124118,0.176159,0.721969,23.426660,0.047712,0.124879,0.090236,9.414285,0.445455,0.526659,0.199489,97.398442,97.201100,56.666111,0.080197,0.563024,0.254146,0.174821,0.487391,0.278288,0.102450,0.230944,2.985000,0.509191,0.385670,0.406454,0.021151,0.199629,0.090298,0.192666,0.078131,0.385304,0.443182,0.265984,0.413165,0.071557,0.496141,0.213026,0.193859,0.390767,0.192688,0.201909,0.190237,0.200174,0.189189,0.203901,0.197160,0.202369,0.202316,0.199148,0.183938,0.200451,0.194223,0.230847,0.212717,0.209447,0.196583,1.675764,35.0,87.0,14.0,35.0,20.0,24.0,10.0,27.0,37.0,20.0,13.0,4.0,10.0,22.0,104.0,240.000000,23.0,13.0,9.0,34.0,5.0,106.772104,112.970514,-6.198410,0.151218,1.326062,15.111083,0.038915,0.127791,0.079419,6.563722,0.458367,0.510433,0.192078,97.401411,97.299438,63.261667,0.071764,0.485370,0.277949,0.102535,0.561151,0.256051,0.174513,0.279869,3.273889,0.633511,0.366489,0.403140,0.070555,0.275650,0.084249,0.274251,0.334755,0.332739,0.343786,0.480728,0.542070,0.124319,0.459480,0.365033,0.413705,0.785538,0.183716,0.200075,0.180334,0.200766,0.200539,0.197205,0.205557,0.206304,0.204789,0.192580,0.203496,0.194035,0.233618,0.195868,0.185764,0.189378,0.187967,0.159167,LAC @ DEN,2024-25,los angeles clippers,denver nuggets,3,0,0,10,0,0,15.369231,199.8,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0,3,0,0,10,0,0,3,15.369231,199.8,0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
38077,0041600144,2017-04-24,1610612744,1610612757,0.0,1.0,25.0,1,0,1,0,128.0,1.39,2.53,46.0,86.0,17.0,29.0,19.0,27.0,6.0,39.0,45.0,27.0,7.0,9.0,10.0,15.0,240.033333,14.0,4.0,14.0,38.0,3.0,124.959651,101.338634,23.627788,0.159116,0.671833,19.085578,0.021503,0.144437,0.091251,6.107187,0.574273,0.591628,0.197779,101.820948,101.899357,49.736912,0.125485,0.638266,0.309432,0.098037,0.467547,0.339688,0.108453,0.152001,2.018609,0.696467,0.303533,0.483538,0.161477,0.283940,0.072509,0.151561,0.089193,0.322061,0.475786,0.443392,0.361629,0.112888,0.527949,0.391229,0.326586,0.555776,0.197415,0.201708,0.149023,0.178059,0.220644,0.203437,0.120788,0.203820,0.199202,0.192156,0.155522,0.188083,0.159018,0.167407,0.190030,0.201668,0.194639,15.950840,33.0,85.0,13.0,39.0,24.0,29.0,7.0,32.0,39.0,14.0,7.0,3.0,11.0,20.0,103.0,240.000000,5.0,12.0,4.0,28.0,9.0,101.844146,125.220750,-23.395333,0.127247,0.459810,7.659931,0.026963,0.149890,0.079387,7.898889,0.445574,0.497418,0.197088,101.821058,101.799083,58.903472,0.072797,0.464278,0.342151,0.107807,0.638345,0.314603,0.097185,0.141563,2.000625,0.569321,0.430679,0.416382,0.113276,0.266090,0.021082,0.265775,0.045946,0.303253,0.232639,0.629861,0.465324,0.134190,0.356060,0.529634,0.246725,0.660928,0.196420,0.199501,0.202839,0.198949,0.188219,0.189613,0.218232,0.200356,0.196915,0.202024,0.185506,0.179140,0.179408,0.188289,0.199278,0.189102,0.195214,-15.393889,GSW @ POR,2016-17,golden state warriors,portland trail blazers,0,1,0,12,0,0,17.576923,228.5,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0,1,1,0,12,0,0,0,17.576923,228.5,0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
38078,0041600144,2017-04-24,1610612757,1610612744,1.0,0.0,-25.0,1,1,1,1,103.0,2.53,1.39,33.0,85.0,13.0,39.0,24.0,29.0,7.0,32.0,39.0,14.0,7.0,3.0,11.0,20.0,240.000000,5.0,12.0,4.0,28.0,9.0,101.844146,125.220750,-23.395333,0.127247,0.459810,7.659931,0.026963,0.149890,0.079387,7.898889,0.445574,0.497418,0.197088,101.821058,101.799083,58.903472,0.072797,0.464278,0.342151,0.107807,0.638345,0.314603,0.097185,0.141563,2.000625,0.569321,0.430679,0.416382,0.113276,0.266090,0.021082,0.265775,0.045946,0.303253,0.232639,0.629861,0.465324,0.134190,0.356060,0.529634,0.246725,0.660928,0.196420,0.199501,0.202839,0.198949,0.188219,0.189613,0.218232,0.200356,0.196915,0.202024,0.185506,0.179140,0.179408,0.188289,0.199278,0.189102,0.195214,-15.393889,46.0,86.0,17.0,29.0,19.0,27.0,6.0,39.0,45.0,27.0,7.0,9.0,10.0,15.0,128.0,240.033333,14.0,4.0,14.0,38.0,3.0,124.959651,101.338634,23.627788,0.159116,0.671833,19.085578,0.021503,0.144437,0.091251,6.107187,0.574273,0.591628,0.197779,101.820948,101.899357,49.736912,0.125485,0.638266,0.309432,0.098037,0.467547,0.339688,0.108453,0.152001,2.018609,0.696467,0.303533,0.483538,0.161477,0.283940,0.072509,0.151561,0.089193,0.322061,0.475786,0.443392,0.361629,0.112888,0.527949,0.391229,0.326586,0.555776,0.197415,0.201708,0.149023,0.178059,0.220644,0.203437,0.120788,0.203820,0.199202,0.192156,0.155522,0.188083,0.159018,0.167407,0.190030,0.201668,0.194639,15.950840,POR vs. GSW,2016-17,portland trail blazers,golden state warriors,0,1,0,12,0,0,13.061538,169.8,0,0.0,0.2,5,1,0.2,0,0.0,0,0.0,0,0.0,1,1,0,12,0,0,0,13.061538,169.8,1,0.2,5,1,0.2,0,0.0,0,0.0,0,0.0,0,0.0

# 🚀 Features avancées

In [ ]:

# Ajouter les features avancées aux stats de match
#match_dataset = add_advanced_boxscore_features(match_dataset)

# MOVED TO CONFIG
# features_to_roll = cols_to_sum + cols_to_weighted_avg
# features_to_roll += [f"OPP_{col}" for col in cols_to_sum + cols_to_weighted_avg]

# Calcul des features glissantes shiftées
match_dataset = compute_rolling_features(match_dataset, "TEAM_ID", ["TEAM_ID", "GAME_DATE"], features_to_roll, N_LIST, method="ewm")

match_dataset = compute_rolling_features(match_dataset, "TEAM_ID", ["TEAM_ID", "GAME_DATE"], top_player_features_to_roll, N_LIST_TOP, method="ewm", apply_log=True)


match_dataset = compute_winrates(match_dataset, "TEAM_ID", "IS_WIN", "IS_HOME", N_LIST)
match_dataset = compute_win_ratio(match_dataset, "TEAM_ID", "IS_WIN", N_LIST)

match_dataset["IS_WIN_SHIFTED"] = match_dataset.groupby("TEAM_ID")["IS_WIN"].shift(1).fillna(0).astype(int)
match_dataset["WIN_STREAK"] = match_dataset.groupby("TEAM_ID").apply(
    lambda x: compute_win_streak(x, "TEAM_ID", "IS_WIN_SHIFTED")).reset_index(level=0, drop=True)
match_dataset = compute_side_win_streak(match_dataset, win_shifted_col="IS_WIN_SHIFTED")


# Calcul des jours de repos pour l'équipe et l'adversaire
match_dataset["DAYS_SINCE_LAST_GAME"] = compute_rest_days(match_dataset, "GAME_DATE", "TEAM_ID")
match_dataset["OPP_DAYS_SINCE_LAST_GAME"] = compute_rest_days(match_dataset, "GAME_DATE", "OPP_TEAM_ID")

# Avantage de repos
match_dataset["REST_ADVANTAGE"] = (
    match_dataset["DAYS_SINCE_LAST_GAME"] - match_dataset["OPP_DAYS_SINCE_LAST_GAME"]
)


match_dataset = compute_rolling_rest_advantage(
    match_dataset, "TEAM_ID", "IS_HOME", "REST_ADVANTAGE", N_LIST
)

match_dataset = compute_home_away_pts(
    match_dataset, "TEAM_ID", "IS_HOME", "points_traditional", "OPP_points_traditional", N_LIST
)

# match_dataset = rename_pts_against_columns(match_dataset)

match_dataset = compute_h2h(match_dataset, N_LIST)
# match_dataset = compute_h2h_pts_margin(match_dataset, N_LIST)
match_dataset = compute_h2h_season(match_dataset)
match_dataset = compute_h2h_streak(match_dataset)

match_dataset = compute_elo(match_dataset)
match_dataset = compute_elo_season(match_dataset)

match_dataset = convert_elos_to_elo_diff(match_dataset)

e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (

In [ ]:
pd.options.display.max_columns = None
display(match_dataset)

          GAME_ID  GAME_DATE     TEAM_ID OPP_TEAM_ID  IS_HOME  IS_WIN  \
0      0021000001 2010-10-26  1610612738  1610612748      1.0     1.0
1      0021000001 2010-10-26  1610612748  1610612738      0.0     0.0
2      0021000002 2010-10-26  1610612756  1610612757      0.0     0.0
3      0021000002 2010-10-26  1610612757  1610612756      1.0     1.0
4      0021000003 2010-10-26  1610612745  1610612747      0.0     0.0
...           ...        ...         ...         ...      ...     ...
38076  0042400315 2025-05-28  1610612760  1610612750      1.0     1.0
38077  0042400305 2025-05-29  1610612752  1610612754      1.0     1.0
38078  0042400305 2025-05-29  1610612754  1610612752      0.0     0.0
38079  0042400306 2025-05-31  1610612752  1610612754      0.0     0.0
38080  0042400306 2025-05-31  1610612754  1610612752      1.0     1.0

       POINT_DIFF  has_absent  has_top_absent  num_absent  top_player_absent  \
0             8.0           1               0           3                  0
1            -8.0           1               1           3                  2
2           -14.0           1               0           2                  0
3            14.0           1               0           2                  0
4            -2.0           1               1           2                  1
...           ...         ...             ...         ...                ...
38076        30.0           0               0           0                  0
38077        17.0           1               0           4                  0
38078       -17.0           1               0           2                  0
38079       -17.0           1               0           2                  0
38080        17.0           1               0           2                  0

       points_traditional  ODDS  OPP_ODDS  fieldGoalsMade_traditional  \
0                    88.0  1.88      1.70                        32.0
1                    80.0  1.70      1.88                        27.0
2                    92.0  3.30      1.22                        36.0
3                   106.0  1.22      3.30                        43.0
4                   110.0  3.50      1.20                        38.0
...                   ...   ...       ...                         ...
38076               124.0  1.25      3.91                        46.0
38077               111.0  1.54      2.46                        44.0
38078                94.0  2.46      1.54                        30.0
38079               108.0  2.38      1.58                        41.0
38080               125.0  1.58      2.38                        46.0

       fieldGoalsAttempted_traditional  threePointersMade_traditional  \
0                                 69.0                            8.0
1                                 74.0                            8.0
2                                 74.0                            9.0
3                                 93.0                           10.0
4                                 91.0                            8.0
...                                ...                            ...
38076                             88.0                           14.0
38077                             89.0                            8.0
38078                             74.0                           10.0
38079                             86.0                            9.0
38080                             85.0                           17.0

       threePointersAttempted_traditional  freeThrowsMade_traditional  \
0                                    16.0                        16.0
1                                    20.0                        18.0
2                                    19.0                        11.0
3                                    20.0                        10.0
4                                    20.0                        26.0
...                                   ...                         ...
38076                                35.0                        18.0
38077                                29.0                        15.0
38078                                30.0                        24.0
38079                                32.0                        17.0
38080                                33.0                        16.0

       freeThrowsAttempted_traditional  reboundsOffensive_traditional  \
0                                 25.0                            8.0
1                                 25.0                           11.0
2                                 16.0                            7.0
3                                 15.0                           18.0
4                                 28.0                           16.0
...                                ...                            ...
38076                             21.0                            7.0
38077                             22.0                           11.0
38078                             29.0                            8.0
38079                             26.0                           13.0
38080                             19.0                            6.0

       reboundsDefensive_traditional  reboundsTotal_traditional  \
0                               34.0                       42.0
1                               28.0                       39.0
2                               23.0                       30.0
3                               30.0                       48.0
4                               37.0                       53.0
...                              ...                        ...
38076                           39.0                       46.0
38077                           34.0                       45.0
38078                           32.0                       40.0
38079                           28.0                       41.0
38080                           30.0                       36.0

       assists_traditional  steals_traditional  blocks_traditional  \
0                     25.0                 6.0                 4.0
1                     15.0                10.0                 6.0
2                     15.0                 3.0                 4.0
3                     31.0                11.0                 2.0
4                     25.0                 6.0                 7.0
...                    ...                 ...                 ...
38076                 26.0                14.0                 8.0
38077                 22.0                11.0                 3.0
38078                 20.0                10.0                 7.0
38079                 23.0                10.0                 6.0
38080                 30.0                10.0                 9.0

       turnovers_traditional  foulsPersonal_traditional  MINUTES_PLAYED  \
0                       18.0                       19.0      240.000000
1                       17.0                       21.0      240.000000
2                       19.0                       19.0      240.000000
3                       12.0                       22.0      240.000000
4                       20.0                       25.0      239.983333
...                      ...                        ...             ...
38076                   14.0                       20.0      239.983333
38077                   15.0                       22.0      240.016667
38078                   20.0                       22.0      240.000000
38079                   17.0                       16.0      240.000000
38080                   12.0                       23.0      240.016667

       pointsOffTurnovers_misc  pointsSecondChance_misc  pointsFastBreak_misc  \
0                         17.0                     11.0                  11.0
1                         22.0                      5.0                  11.0
2                         17.0                     11.0                   6.0
3                         21.0                     21.0                  13.0
4                         10.0                     16.0                  17.0
...                        ...                      ...                   ...
38076                     18.0                      9.0                  19.0
38077                     15.0                     13.0                  15.0
38078                     20.0                      7.0                  16.0
38079                     13.0                     15.0                  10.0
38080                     34.0                     12.0                  25.0

       pointsPaint_misc  blocksAgainst_misc  offensiveRating_advanced  \
0                  38.0                 6.0                 95.258826
1                  24.0                 4.0                 86.585597
2                  44.0                 2.0                101.425007
3                  42.0                 4.0                116.705951
4                  42.0                 4.0                106.091812
...                 ...                 ...                       ...
38076              54.0                 6.0                116.271158
38077              60.0                 7.0                111.626672
38078              34.0                 3.0                 94.468389
38079              54.0                 9.0                108.452111
38080              50.0                 6.0                127.352996

       defensiveRating_advanced  netRating_advanced  \
0                     86.767938            8.458819
1                     94.558222           -7.960403
2                    116.062382          -14.648243
3                    101.868819           14.847993
4                    106.928071           -0.849344
...                         ...                 ...
38076                 86.683714           29.598472
38077                 96.476189           15.129859
38078                110.979389          -16.503681
38079                126.791896          -18.338972
38080                105.015909           22.340053

       assistPercentage_advanced  assistToTurnover_advanced  \
0                       0.179324                   1.418765
1                       0.158097                   0.533849
2                       0.113202                   0.765569
3                       0.179627                   1.619028
4                       0.163359                   1.393743
...                          ...                        ...
38076                   0.153179                   1.150288
38077                   0.125950                   1.390534
38078                   0.163760                   0.659449
38079                   0.137946                   1.068833
38080                   0.153711                   2.025884

       assistRatio_advanced  offensiveReboundPercentage_advanced  \
0                 16.786944                             0.040284
1                 13.530931                             0.049858
2                 12.112500                             0.037518
3                 21.211271                             0.071370
4                 22.918397                             0.061861
...                     ...                                  ...
38076             17.148017                             0.028388
38077             15.440879                             0.043370
38078             15.763840                             0.033514
38079             13.428708                             0.050020
38080             22.049573                             0.031637

       defensiveReboundPercentage_advanced  reboundPercentage_advanced  \
0                                 0.143548                    0.097696
1                                 0.138836                    0.087374
2                                 0.088750                    0.065437
3                                 0.149384                    0.105635
4                                 0.126248                    0.095825
...                                    ...                         ...
38076                             0.149998                    0.096439
38077                             0.141279                    0.092679
38078                             0.127963                    0.081709
38079                             0.136825                    0.086799
38080                             0.114636                    0.078322

       turnoverRatio_advanced  effectiveFieldGoalPercentage_advanced  \
0                   13.576424                               0.536647
1                   10.813681                               0.426550
2                   15.816979                               0.525870
3                    7.830722                               0.500923
4                   12.957421                               0.402580
...                       ...                                    ...
38076               10.277860                               0.516245
38077               12.034067                               0.558147
38078               16.695181                               0.522219
38079               13.136583                               0.501459
38080                7.995493                               0.594024

       trueShootingPercentage_advanced  usagePercentage_advanced  \
0                             0.565526                  0.192004
1                             0.495102                  0.197047
2                             0.535510                  0.195844
3                             0.520792                  0.191743
4                             0.475858                  0.198410
...                                ...                       ...
38076                         0.561993                  0.192570
38077                         0.567221                  0.193626
38078                         0.580079                  0.196780
38079                         0.559112                  0.190430
38080                         0.616071                  0.192961

       estimatedPace_advanced  pace_advanced  possessions_advanced  \
0                   91.500720      92.499906             61.978819
1                   91.499007      92.600174             59.272778
2                   94.820024      91.299769             49.458125
3                   94.821719      91.100492             55.840069
4                  107.319701     104.201138             61.522328
...                       ...            ...                   ...
38076              105.418048     106.997439             56.169803
38077              100.719560      98.500117             59.565447
38078              100.719401      99.700689             48.830486
38079              101.400812      99.101217             59.888889
38080              101.399425     100.497996             54.449066

       PIE_advanced  effectiveFieldGoalPercentage_fourfactors  \
0          0.121102                                  0.524833
1          0.090339                                  0.418351
2          0.072061                                  0.551087
3          0.059822                                  0.516180
4          0.102728                                  0.462191
...             ...                                       ...
38076      0.148150                                  0.611803
38077      0.119602                                  0.540469
38078      0.078752                                  0.474772
38079      0.085635                                  0.531050
38080      0.114831                                  0.633074

       freeThrowAttemptRate_fourfactors  teamTurnoverPercentage_fourfactors  \
0                              0.364811                            0.217790
1                              0.344338                            0.188392
2                              0.219725                            0.204248
3                              0.167638                            0.156635
4                              0.307097                            0.193372
...                                 ...                                 ...
38076                          0.236456                            0.146934
38077                          0.246219                            0.145814
38078                          0.405602                            0.202463
38079                          0.308973                            0.174502
38080                          0.227772                            0.126563

       oppEffectiveFieldGoalPercentage_fourfactors  \
0                                         0.420576
1                                         0.524045
2                                         0.516365
3                                         0.550046
4                                         0.466376
...                                            ...
38076                                     0.474105
38077                                     0.472053
38078                                     0.541328
38079                                     0.648678
38080                                     0.531103

       oppFreeThrowAttemptRate_fourfactors  \
0                                 0.341330
1                                 0.364850
2                                 0.162388
3                                 0.216926
4                                 0.295486
...                                    ...
38076                             0.174840
38077                             0.393109
38078                             0.248815
38079                             0.225373
38080                             0.304584

       oppTeamTurnoverPercentage_fourfactors  \
0                                   0.187027
1                                   0.217761
2                                   0.155634
3                                   0.204611
4                                   0.112989
...                                      ...
38076                               0.200146
38077                               0.202483
38078                               0.145482
38079                               0.131917
38080                               0.174045

       oppOffensiveReboundPercentage_fourfactors  foulsDrawn_misc  \
0                                       0.244226         2.633472
1                                       0.223355         2.708681
2                                       0.433928         2.182639
3                                       0.194777         2.417917
4                                       0.279195         3.016946
...                                          ...              ...
38076                                   0.167282         2.263421
38077                                   0.192982         2.828206
38078                                   0.266363         2.224722
38079                                   0.166467         2.875208
38080                                   0.304667         2.036595

       percentageFieldGoalsAttempted2pt_scoring  \
0                                      0.773753
1                                      0.712399
2                                      0.755892
3                                      0.803757
4                                      0.693632
...                                         ...
38076                                  0.505107
38077                                  0.683842
38078                                  0.574555
38079                                  0.620439
38080                                  0.562603

       percentageFieldGoalsAttempted3pt_scoring  percentagePoints2pt_scoring  \
0                                      0.226247                     0.600667
1                                      0.243379                     0.496113
2                                      0.244108                     0.571466
3                                      0.196243                     0.626211
4                                      0.244628                     0.453675

# 🧽 Nettoyage et sauvegarde

In [ ]:


final_date = datetime.now().strftime('%Y-%m-%d_%H-%M-%S')
raw_save_path = os.path.join(DATA_FINAL_DATASET_DIR, f'nba_features_final_{final_date}.csv')
clean_save_path = os.path.join(DATA_FINAL_CLEANED_DATASET_DIR, f'nba_features_cleaned_final_{final_date}.csv')

os.makedirs(DATA_FINAL_DATASET_DIR, exist_ok=True)
os.makedirs(DATA_FINAL_CLEANED_DATASET_DIR, exist_ok=True)

match_dataset.to_csv(raw_save_path, index=False)

cols_to_drop = features_to_roll+top_player_features_to_roll+COLS_MATCH_REAL
#remove num_absent and top_player_absent from cols_to_drop to see if we can use them has input
cols_to_drop = [col for col in cols_to_drop if col not in ['num_absent', 'top_player_absent']]


final_cleaned = match_dataset.drop(columns=cols_to_drop, errors='ignore')
final_cleaned.to_csv(clean_save_path, index=False)

print(f"✅ Fichier brut : {raw_save_path}")
print(f"✅ Fichier clean : {clean_save_path}")

final_cleaned

✅ Fichier brut : data\final_dataset\nba_features_final_2025-06-12_20-02-49.csv
✅ Fichier clean : data\final_cleaned_dataset\nba_features_cleaned_final_2025-06-12_20-02-49.csv

          GAME_ID  GAME_DATE     TEAM_ID OPP_TEAM_ID  IS_HOME  IS_WIN  \
0      0021000001 2010-10-26  1610612738  1610612748      1.0     1.0
1      0021000001 2010-10-26  1610612748  1610612738      0.0     0.0
2      0021000002 2010-10-26  1610612756  1610612757      0.0     0.0
3      0021000002 2010-10-26  1610612757  1610612756      1.0     1.0
4      0021000003 2010-10-26  1610612745  1610612747      0.0     0.0
...           ...        ...         ...         ...      ...     ...
38076  0042400315 2025-05-28  1610612760  1610612750      1.0     1.0
38077  0042400305 2025-05-29  1610612752  1610612754      1.0     1.0
38078  0042400305 2025-05-29  1610612754  1610612752      0.0     0.0
38079  0042400306 2025-05-31  1610612752  1610612754      0.0     0.0
38080  0042400306 2025-05-31  1610612754  1610612752      1.0     1.0

       POINT_DIFF  has_absent  has_top_absent  num_absent  top_player_absent  \
0             8.0           1               0           3                  0
1            -8.0           1               1           3                  2
2           -14.0           1               0           2                  0
3            14.0           1               0           2                  0
4            -2.0           1               1           2                  1
...           ...         ...             ...         ...                ...
38076        30.0           0               0           0                  0
38077        17.0           1               0           4                  0
38078       -17.0           1               0           2                  0
38079       -17.0           1               0           2                  0
38080        17.0           1               0           2                  0

       ODDS  OPP_ODDS   SEASON  ROLL_fieldGoalsMade_traditional_3  \
0      1.88      1.70  2010-11                                NaN
1      1.70      1.88  2010-11                                NaN
2      3.30      1.22  2010-11                                NaN
3      1.22      3.30  2010-11                                NaN
4      3.50      1.20  2010-11                                NaN
...     ...       ...      ...                                ...
38076  1.25      3.91  2024-25                          43.687438
38077  1.54      2.46  2024-25                          37.928151
38078  2.46      1.54  2024-25                          42.227196
38079  2.38      1.58  2024-25                          40.964076
38080  1.58      2.38  2024-25                          36.113598

       ROLL_fieldGoalsMade_traditional_5  ROLL_fieldGoalsMade_traditional_10  \
0                                    NaN                                 NaN
1                                    NaN                                 NaN
2                                    NaN                                 NaN
3                                    NaN                                 NaN
4                                    NaN                                 NaN
...                                  ...                                 ...
38076                          42.975442                           42.674003
38077                          38.496268                           38.913265
38078                          42.415353                           42.844523
38079                          40.330846                           39.838126
38080                          38.276902                           40.509156

       ROLL_fieldGoalsMade_traditional_25  ROLL_fieldGoalsMade_traditional_50  \
0                                     NaN                                 NaN
1                                     NaN                                 NaN
2                                     NaN                                 NaN
3                                     NaN                                 NaN
4                                     NaN                                 NaN
...                                   ...                                 ...
38076                           43.429035                           44.065909
38077                           39.769775                           40.868402
38078                           43.334909                           43.617826
38079                           40.095177                           40.991210
38080                           42.309146                           43.083794

       ROLL_fieldGoalsMade_traditional_100  \
0                                      NaN
1                                      NaN
2                                      NaN
3                                      NaN
4                                      NaN
...                                    ...
38076                            44.165172
38077                            41.615533
38078                            43.937162
38079                            41.662750
38080                            43.661179

       ROLL_fieldGoalsMade_traditional_200  \
0                                      NaN
1                                      NaN
2                                      NaN
3                                      NaN
4                                      NaN
...                                    ...
38076                            43.711170
38077                            41.602569
38078                            44.073120
38079                            41.626424
38080                            43.933088

       ROLL_fieldGoalsAttempted_traditional_3  \
0                                         NaN
1                                         NaN
2                                         NaN
3                                         NaN
4                                         NaN
...                                       ...
38076                               91.177611
38077                               82.354104
38078                               85.185403
38079                               85.677052
38080                               79.592701

       ROLL_fieldGoalsAttempted_traditional_5  \
0                                         NaN
1                                         NaN
2                                         NaN
3                                         NaN
4                                         NaN
...                                       ...
38076                               90.462160
38077                               83.590291
38078                               85.523283
38079                               85.393527
38080                               81.682189

       ROLL_fieldGoalsAttempted_traditional_10  \
0                                          NaN
1                                          NaN
2                                          NaN
3                                          NaN
4                                          NaN
...                                        ...
38076                                90.821663
38077                                85.047437
38078                                86.508843
38079                                85.766085
38080                                84.234508

       ROLL_fieldGoalsAttempted_traditional_25  \
0                                          NaN
1                                          NaN
2                                          NaN
3                                          NaN
4                                          NaN
...                                        ...
38076                                92.048646
38077                                86.670628
38078                                88.160713
38079                                86.849811
38080                                87.071427

       ROLL_fieldGoalsAttempted_traditional_50  \
0                                          NaN
1                                          NaN
2                                          NaN
3                                          NaN
4                                          NaN
...                                        ...
38076                                92.416351
38077                                87.842845
38078                                88.865706
38079                                87.888223
38080                                88.282737

       ROLL_fieldGoalsAttempted_traditional_100  \
0                                           NaN
1                                           NaN
2                                           NaN
3                                           NaN
4                                           NaN
...                                         ...
38076                                 92.071940
38077                                 88.424964
38078                                 89.257216
38079                                 88.436351
38080                                 88.955093

       ROLL_fieldGoalsAttempted_traditional_200  \
0                                           NaN
1                                           NaN
2                                           NaN
3                                           NaN
4                                           NaN
...                                         ...
38076                                 91.394191
38077                                 88.442533
38078                                 89.634989
38079                                 88.448080
38080                                 89.479416

       ROLL_threePointersMade_traditional_3  \
0                                       NaN
1                                       NaN
2                                       NaN
3                                       NaN
4                                       NaN
...                                     ...
38076                             14.037870
38077                             11.657789
38078                             11.193129
38079                              9.828894
38080                             10.596565

       ROLL_threePointersMade_traditional_5  \
0                                       NaN
1                                       NaN
2                                       NaN
3                                       NaN
4                                       NaN
...                                     ...
38076                             13.164787
38077                             11.645911
38078                             11.585449
38079                             10.430607
38080                             11.056966

       ROLL_threePointersMade_traditional_10  \
0                                        NaN
1                                        NaN
2                                        NaN
3                                        NaN
4                                        NaN
...                                      ...
38076                              12.650486
38077                              11.630687
38078                              12.354924
38079                              10.970562
38080                              11.926756

       ROLL_threePointersMade_traditional_25  \
0                                        NaN
1                                        NaN
2                                        NaN
3                                        NaN
4                                        NaN
...                                      ...
38076                              13.262874
38077                              11.727505
38078                              13.159462
38079                              11.440774
38080                              12.916426

       ROLL_threePointersMade_traditional_50  \
0                                        NaN
1                                        NaN
2                                        NaN
3                                        NaN
4                                        NaN
...                                      ...
38076                              13.852548
38077                              11.855927
38078                              13.375601
38079                              11.704714
38080                              13.243224

       ROLL_threePointersMade_traditional_100  \
0                                         NaN
1                                         NaN
2                                         NaN
3                                         NaN
4                                         NaN
...                                       ...
38076                               13.929046
38077                               12.126803
38078                               13.274237
38079                               12.045084
38080                               13.209401

       ROLL_threePointersMade_traditional_200  \
0                                         NaN
1                                         NaN
2                                         NaN
3                                         NaN
4                                         NaN
...                                       ...
38076                               13.568395
38077                               12.363818
38078                               13.096396
38079                               12.320397
38080                               13.065586

       ROLL_threePointersAttempted_traditional_3  \
0                                            NaN
1                                            NaN
2                                            NaN
3                                            NaN
4                                            NaN
...                                          ...
38076                                  37.311252
38077                                  30.488765
38078                                  30.437262
38079                                  29.744383
38080                                  30.218631

       ROLL_threePointersAttempted_traditional_5  \
0                                            NaN
1                                            NaN
2                                            NaN
3                                            NaN
4                                            NaN
...                                          ...
38076                                  36.524460
38077                                  31.556491
38078                                  31.004494
38079                                  30.704328
38080                                  30.669663

       ROLL_threePointersAttempted_traditional_10  \
0                                             NaN
1                                             NaN
2                                             NaN
3                                             NaN
4                                             NaN
...                                           ...
38076                                   36.481312
38077                                   32.259225
38078                                   32.360396
38079                                   31.666639
38080                                   31.931233

       ROLL_threePointersAttempted_traditional_25  \
0                                             NaN
1                                             NaN
2                                             NaN
3                                             NaN
4                                             NaN
...                                           ...
38076                                   37.506658
38077                                   32.610238
38078                                   34.573861
38079                                   32.332528
38080                                   34.222025

       ROLL_threePointersAttempted_traditional_50  \
0                                             NaN
1                                             NaN
2                                             NaN
3                                             NaN
4                                             NaN
...                                           ...
38076                                   38.001748
38077                                   32.875643
38078                                   35.472806
38079                                   32.723657
38080                                   35.258186

       ROLL_threePointersAttempted_traditional_100  \
0                                              NaN
1                                              NaN
2                                              NaN
3                                              NaN
4                                              NaN
...                                            ...
38076                                    37.741462
38077                                    33.399543
38078                                    35.445788
38079                                    33.312423
38080                                    35.337951

       ROLL_threePointersAttempted_traditional_200  \
0                                              NaN
1                                              NaN
2                                              NaN
3                                              NaN
4                                              NaN
...                                            ...
38076                                    36.862494
38077                                    33.971010
38078                                    35.191873
38079                                    33.921547
38080                                    35.140212

       ROLL_freeThrowsMade_traditional_3  ROLL_freeThrowsMade_traditional_5  \
0                                    NaN                                NaN
1                                    NaN                                NaN
2                                    NaN                                NaN
3                                    NaN                                NaN
4                                    NaN                                NaN
...                                  ...                                ...
38076                          16.988977                          17.449483
38077                          28.559587                          26.399211
38078                          24.556546                          22.877815
38079                          21.779794                          22.599474
38080                          24.278273                          23.251877

       ROLL_freeThrowsMade_traditional_10  ROLL_freeThrowsMade_traditional_25  \
0                                     NaN                                 NaN
1                                     NaN                                 NaN
2                                     NaN                                 NaN
3                                     NaN                                 NaN
4                                     NaN                                 NaN
...                                   ...                                 ...
38076                           18.067596                           18.296466
38077                           23.421474                           19.955104
38078                           20.949255                           19.251334
38079                           21.890297                           19.573942
38080                           21.503936                           19.616616

       ROLL_freeThrowsMade_traditional_50  \
0                                     NaN
1                                     NaN
2                                     NaN
3                                     NaN
4                                     NaN
...                                   ...
38076                           17.971087
38077                           18.342311
38078                           18.297975
38079                           18.211240
38080                           18.521584

       ROLL_freeThrowsMade_traditional_100  \
0                                      NaN
1                                      NaN

In [ ]:
final_cleaned.columns

Index(['GAME_ID', 'GAME_DATE', 'TEAM_ID', 'OPP_TEAM_ID', 'IS_HOME', 'IS_WIN',
       'POINT_DIFF', 'has_absent', 'has_top_absent', 'num_absent',
       ...
       'H2H_LAST_100_COUNT', 'H2H_LAST_200_DIFF', 'H2H_LAST_200_WINRATE',
       'H2H_LAST_200_COUNT', 'H2H_SEASON_WINS', 'H2H_SEASON_MATCHES',
       'H2H_SEASON_WINRATE', 'H2H_WIN_STREAK', 'ELO_DIFF', 'ELO_DIFF_SEASON'],
      dtype='object', length=1464)

In [ ]:
#store end time of notebook
end_time = datetime.now()
print("End time: ", end_time)
print("Total time: ", end_time - start_time)

End time:  2025-06-12 20:05:27.066582
Total time:  0:13:49.732725