# Nettoyage & enrichissement des boxscores (minutes, DNP, totaux, ratios)

In [1]:
import pandas as pd
import numpy as np
import os
from datetime import datetime
from nba_api.stats.static import players

from src.config import *
from src.utils import *
from src.feature_builder import *
from src.feature_aggregation import *

#display full columns
pd.set_option('display.max_column', None)
# pd.set_option('display.max_rows', None)
# pd.set_option('display.max_seq_items', None)
# pd.set_option('display.max_colwidth', 500)
# pd.set_option('expand_frame_repr', True)

In [2]:
#store start time of notebook
start_time = datetime.now()
print("Start time: ", start_time)

Start time:  2025-06-09 00:43:08.365194

# 🔁 Chargement des fichiers

In [3]:
boxscores_file = get_latest_file(DATA_LAST_BOXSCORES_BATCHES_MERGED_DIR)
games_file = get_latest_file(DATA_LAST_GAMES_MERGED_DIR)
df_boxscores = pd.read_csv(boxscores_file, dtype={'gameId': str})
df_games = pd.read_csv(games_file, dtype={'GAME_ID': str})

In [4]:
games_file

'data\\raw_last\\games_merged\\games_merged_all_seasons__2025-06-06_19-44-58.csv'

In [5]:
df_boxscores

,gameId,teamId,teamCity,teamName,teamTricode,teamSlug,personId,firstName,familyName,nameI,playerSlug,position,comment,jerseyNum,minutes,offensiveRating_advanced,defensiveRating_advanced,estimatedNetRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,oppPointsOffTurnovers_misc,oppPointsSecondChance_misc,oppPointsFastBreak_misc,oppPointsPaint_misc,blocksAgainst_misc,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,threePointersPercentage_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,freeThrowsPercentage_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,points_traditional,plusMinusPoints_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage
0,0021000002,1610612756,Phoenix,Suns,PHX,suns,255,Grant,Hill,G. Hill,grant-hill,F,NaN,NaN,26:05,106.3,122.9,-8.9,-16.7,0.056,0.33,12.5,0.050,0.000,0.021,37.5,0.500,0.450,0.130,89.40,88.33,48.0,-0.011,0.605,0.237,0.234,0.529,0.098,0.199,0.591,0,0,0,4,12,13,10,24,0,3,0.750,0.250,1.000,0.000,0.000,0.000,0.000,0.000,1.000,0.000,1.000,0.000,0.000,0.000,1.000,2,4,0,1,0.00,0,1,0.0,1,0,1,1,0,1,3,1,4,-8.0,0.100,0.105,0.000,0.091,0.000,0.111,0.167,0.000,0.067,0.143,0.273,0.000,1.0,0.0,0.111,0.273,0.078
1,0021000002,1610612756,Phoenix,Suns,PHX,suns,2045,Hedo,Turkoglu,H. Turkoglu,hedo-turkoglu,F,NaN,NaN,27:13,114.9,124.5,-11.6,-9.6,0.100,2.00,20.0,0.000,0.111,0.060,10.0,0.429,0.429,0.145,86.77,84.65,47.0,0.010,0.556,0.133,0.164,0.548,0.077,0.161,0.522,0,0,0,0,6,15,0,22,0,1,0.429,0.571,0.000,0.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,0.500,0.500,0.500,0.500,2,7,2,4,0.50,0,0,0.0,0,3,3,2,1,0,1,5,6,-7.0,0.091,0.156,0.333,0.267,0.000,0.000,0.000,0.273,0.167,0.286,0.125,0.333,0.0,0.0,0.556,0.125,0.111
2,0021000002,1610612756,Phoenix,Suns,PHX,suns,201577,Robin,Lopez,R. Lopez,robin-lopez,C,NaN,NaN,24:50,120.0,122.7,6.2,-2.7,0.000,0.00,0.0,0.158,0.111,0.130,16.7,0.500,0.512,0.118,91.52,86.00,45.0,0.071,0.641,0.179,0.195,0.490,0.122,0.226,0.667,1,4,0,4,10,18,10,24,0,2,1.000,0.000,0.800,0.000,0.000,0.000,0.200,0.200,0.800,0.000,1.000,0.000,0.000,0.000,1.000,2,4,0,0,0.00,1,2,0.5,3,3,6,0,0,1,1,0,5,0.0,0.091,0.103,0.000,0.000,0.250,0.286,0.600,0.429,0.500,0.000,0.111,0.000,0.5,0.0,0.000,0.182,0.093
3,0021000002,1610612756,Phoenix,Suns,PHX,suns,2202,Jason,Richardson,J. Richardson,jason-richardson,G,NaN,NaN,35:05,106.0,116.4,-8.3,-10.4,0.053,1.00,6.3,0.080,0.100,0.092,6.3,0.808,0.793,0.205,93.50,91.67,67.0,0.184,0.630,0.260,0.266,0.500,0.127,0.145,0.457,9,5,6,10,18,13,10,32,0,2,0.692,0.308,0.545,0.091,0.409,0.273,0.045,0.409,0.455,0.667,0.333,0.667,0.333,0.667,0.333,9,13,3,4,0.75,1,2,0.5,2,4,6,1,1,0,1,0,22,-7.0,0.321,0.260,0.429,0.333,0.125,0.154,0.333,0.211,0.240,0.091,0.056,0.333,0.0,0.0,0.000,0.143,0.310
4,0021000002,1610612756,Phoenix,Suns,PHX,suns,959,Steve,Nash,S. Nash,steve-nash,G,NaN,NaN,35:25,104.4,114.7,-12.4,-10.3,0.333,0.67,17.1,0.000,0.077,0.046,25.7,0.579,0.613,0.392,92.23,92.15,68.0,0.127,0.618,0.255,0.262,0.507,0.143,0.134,0.457,0,0,0,12,18,13,10,32,1,4,0.789,0.211,0.615,0.154,0.231,0.000,0.154,0.000,0.462,0.000,1.000,0.500,0.500,0.100,0.900,10,19,2,4,0.50,4,5,0.8,0,3,3,6,1,0,9,1,26,-7.0,0.357,0.373,0.286,0.333,0.500,0.385,0.000,0.158,0.120,0.545,0.500,0.333,0.0,1.0,0.083,0.286,0.366
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
948298,0042400401,1610612760,Oklahoma City,Thunder,OKC,thunder,1629026,Kenrich,Williams,K. Williams,kenrich-williams,NaN,NaN,NaN,0:39,50.0,150.0,-96.8,-100.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,142.90,147.31,2.0,0.000,0.000,2.000,0.000,1.500,0.000,0.500,0.000,0,0,0,0,0,0,0,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0,0,0,0.00,0,0,0.0,0,0,0,0,0,0,0,0,0,-2.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000
948299,0042400401,1610612760,Oklahoma City,Thunder,OKC,thunder,1642349,Ajay,Mitchell,A. Mitchell,ajay-mitchell,NaN,NaN,NaN,4:10,100.0,130.0,-17.5,-30.0,0.000,0.00,0.0,0.429,0.000,0.250,0.0,0.000,0.000,0.231,105.98,115.20,10.0,-0.083,0.222,0.667,0.000,0.563,0.500,0.205,0.400,0,0,0,0,0,2,0,0,1,0,0.667,0.333,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,3,0,1,0.00,0,0,0.0,3,0,3,0,0,0,0,0,0,-3.0,0.000,0.333,0.000,0.500,0.000,0.000,1.000,0.000,0.500,0.000,0.000,0.000,0.0,1.0,0.000,0.000,0.000
948300,0042400401,1610612760,Oklahoma City,Thunder,OKC,thunder,1631172,Ousmane,Dieng,O. Dieng,ousmane-dieng,NaN,DNP - Coach's Decision,NaN,NaN,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.00,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0,0,0,0,0,0,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0,0,0,0.00,0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000
948301,0042400401,1610612760,Oklahoma City,Thunder,OKC,thunder,1641794,Dillon,Jones,D. Jones,dillon-jones,NaN,DNP - Coach's Decision,NaN,NaN,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.00,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0,0,0,0,0,0,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0,0,0,0.00,0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000
948302,0042400401,1610612760,Oklahoma City,Thunder,OKC,thunder,1631119,Jaylin,Williams,J. Williams,jaylin-williams,NaN,DNP - Coach's Decision,NaN,NaN,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.00,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0,0,0,0,0,0,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0,0,0,0.00,0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000

In [6]:
df_games

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS,SEASON
0,22010,1610612756,PHX,Phoenix Suns,0021000002,2010-10-26,PHX @ POR,L,239,92,36,74,0.486,9,19,0.474,11,16,0.688,7,23,30,15,3,4,19,19,-14.0,2010-11
1,22010,1610612747,LAL,Los Angeles Lakers,0021000003,2010-10-26,LAL vs. HOU,W,240,112,40,96,0.417,9,21,0.429,23,28,0.821,14,30,44,21,11,4,12,24,2.0,2010-11
2,22010,1610612748,MIA,Miami Heat,0021000001,2010-10-26,MIA @ BOS,L,242,80,27,74,0.365,8,20,0.400,18,25,0.720,11,28,39,15,10,6,17,21,-8.0,2010-11
3,22010,1610612745,HOU,Houston Rockets,0021000003,2010-10-26,HOU @ LAL,L,240,110,38,91,0.418,8,20,0.400,26,28,0.929,16,37,53,25,6,7,20,25,-2.0,2010-11
4,22010,1610612738,BOS,Boston Celtics,0021000001,2010-10-26,BOS vs. MIA,W,239,88,32,69,0.464,8,16,0.500,16,25,0.640,8,34,42,25,6,4,18,19,8.0,2010-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48501,42024,1610612752,NYK,New York Knicks,0042400305,2025-05-29,NYK vs. IND,W,241,111,44,89,0.494,8,29,0.276,15,22,0.682,11,34,45,22,11,3,15,22,17.0,2024-25
48502,42024,1610612754,IND,Indiana Pacers,0042400306,2025-05-31,IND vs. NYK,W,241,125,46,85,0.541,17,33,0.515,16,19,0.842,6,30,36,30,10,9,12,23,17.0,2024-25
48503,42024,1610612752,NYK,New York Knicks,0042400306,2025-05-31,NYK @ IND,L,240,108,41,86,0.477,9,32,0.281,17,26,0.654,13,28,41,23,10,6,17,16,-17.0,2024-25
48504,42024,1610612754,IND,Indiana Pacers,0042400401,2025-06-05,IND @ OKC,W,240,111,39,82,0.476,18,39,0.462,15,21,0.714,13,43,56,24,1,7,24,22,1.0,2024-25
48505,42024,1610612760,OKC,Oklahoma City Thunder,0042400401,2025-06-05,OKC vs. IND,L,239,110,39,98,0.398,11,30,0.367,21,24,0.875,10,29,39,13,14,6,6,19,-1.0,2024-25

# 🧼 Nettoyage des minutes jouées

In [7]:
def convert_minutes(val):
    if pd.isna(val) or val in ['DNP', '']:
        return 0.0
    try:
        parts = str(val).split(':')
        return int(parts[0]) + int(parts[1]) / 60 if len(parts) == 2 else float(val)
    except:
        return 0.0

df_boxscores['MINUTES_PLAYED'] = df_boxscores['minutes'].apply(convert_minutes)

# Rename gameId and teamId in boxscores

In [8]:
rename_columns = {
    'gameId': 'GAME_ID',
    'teamId': 'TEAM_ID',
}

df_boxscores.rename(columns=rename_columns, inplace=True)

# 🔄 Cast dynamique des colonnes numériques

In [9]:
numeric_cols = df_boxscores.select_dtypes(include=[np.number]).columns.tolist()
for col in numeric_cols:
    df_boxscores[col] = pd.to_numeric(df_boxscores[col], errors='coerce').fillna(0)

In [10]:
df_boxscores

,GAME_ID,TEAM_ID,teamCity,teamName,teamTricode,teamSlug,personId,firstName,familyName,nameI,playerSlug,position,comment,jerseyNum,minutes,offensiveRating_advanced,defensiveRating_advanced,estimatedNetRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,oppPointsOffTurnovers_misc,oppPointsSecondChance_misc,oppPointsFastBreak_misc,oppPointsPaint_misc,blocksAgainst_misc,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,threePointersPercentage_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,freeThrowsPercentage_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,points_traditional,plusMinusPoints_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage,MINUTES_PLAYED
0,0021000002,1610612756,Phoenix,Suns,PHX,suns,255,Grant,Hill,G. Hill,grant-hill,F,NaN,0.0,26:05,106.3,122.9,-8.9,-16.7,0.056,0.33,12.5,0.050,0.000,0.021,37.5,0.500,0.450,0.130,89.40,88.33,48.0,-0.011,0.605,0.237,0.234,0.529,0.098,0.199,0.591,0,0,0,4,12,13,10,24,0,3,0.750,0.250,1.000,0.000,0.000,0.000,0.000,0.000,1.000,0.000,1.000,0.000,0.000,0.000,1.000,2,4,0,1,0.00,0,1,0.0,1,0,1,1,0,1,3,1,4,-8.0,0.100,0.105,0.000,0.091,0.000,0.111,0.167,0.000,0.067,0.143,0.273,0.000,1.0,0.0,0.111,0.273,0.078,26.083333
1,0021000002,1610612756,Phoenix,Suns,PHX,suns,2045,Hedo,Turkoglu,H. Turkoglu,hedo-turkoglu,F,NaN,0.0,27:13,114.9,124.5,-11.6,-9.6,0.100,2.00,20.0,0.000,0.111,0.060,10.0,0.429,0.429,0.145,86.77,84.65,47.0,0.010,0.556,0.133,0.164,0.548,0.077,0.161,0.522,0,0,0,0,6,15,0,22,0,1,0.429,0.571,0.000,0.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,0.500,0.500,0.500,0.500,2,7,2,4,0.50,0,0,0.0,0,3,3,2,1,0,1,5,6,-7.0,0.091,0.156,0.333,0.267,0.000,0.000,0.000,0.273,0.167,0.286,0.125,0.333,0.0,0.0,0.556,0.125,0.111,27.216667
2,0021000002,1610612756,Phoenix,Suns,PHX,suns,201577,Robin,Lopez,R. Lopez,robin-lopez,C,NaN,0.0,24:50,120.0,122.7,6.2,-2.7,0.000,0.00,0.0,0.158,0.111,0.130,16.7,0.500,0.512,0.118,91.52,86.00,45.0,0.071,0.641,0.179,0.195,0.490,0.122,0.226,0.667,1,4,0,4,10,18,10,24,0,2,1.000,0.000,0.800,0.000,0.000,0.000,0.200,0.200,0.800,0.000,1.000,0.000,0.000,0.000,1.000,2,4,0,0,0.00,1,2,0.5,3,3,6,0,0,1,1,0,5,0.0,0.091,0.103,0.000,0.000,0.250,0.286,0.600,0.429,0.500,0.000,0.111,0.000,0.5,0.0,0.000,0.182,0.093,24.833333
3,0021000002,1610612756,Phoenix,Suns,PHX,suns,2202,Jason,Richardson,J. Richardson,jason-richardson,G,NaN,0.0,35:05,106.0,116.4,-8.3,-10.4,0.053,1.00,6.3,0.080,0.100,0.092,6.3,0.808,0.793,0.205,93.50,91.67,67.0,0.184,0.630,0.260,0.266,0.500,0.127,0.145,0.457,9,5,6,10,18,13,10,32,0,2,0.692,0.308,0.545,0.091,0.409,0.273,0.045,0.409,0.455,0.667,0.333,0.667,0.333,0.667,0.333,9,13,3,4,0.75,1,2,0.5,2,4,6,1,1,0,1,0,22,-7.0,0.321,0.260,0.429,0.333,0.125,0.154,0.333,0.211,0.240,0.091,0.056,0.333,0.0,0.0,0.000,0.143,0.310,35.083333
4,0021000002,1610612756,Phoenix,Suns,PHX,suns,959,Steve,Nash,S. Nash,steve-nash,G,NaN,0.0,35:25,104.4,114.7,-12.4,-10.3,0.333,0.67,17.1,0.000,0.077,0.046,25.7,0.579,0.613,0.392,92.23,92.15,68.0,0.127,0.618,0.255,0.262,0.507,0.143,0.134,0.457,0,0,0,12,18,13,10,32,1,4,0.789,0.211,0.615,0.154,0.231,0.000,0.154,0.000,0.462,0.000,1.000,0.500,0.500,0.100,0.900,10,19,2,4,0.50,4,5,0.8,0,3,3,6,1,0,9,1,26,-7.0,0.357,0.373,0.286,0.333,0.500,0.385,0.000,0.158,0.120,0.545,0.500,0.333,0.0,1.0,0.083,0.286,0.366,35.416667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
948298,0042400401,1610612760,Oklahoma City,Thunder,OKC,thunder,1629026,Kenrich,Williams,K. Williams,kenrich-williams,NaN,NaN,0.0,0:39,50.0,150.0,-96.8,-100.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,142.90,147.31,2.0,0.000,0.000,2.000,0.000,1.500,0.000,0.500,0.000,0,0,0,0,0,0,0,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0,0,0,0.00,0,0,0.0,0,0,0,0,0,0,0,0,0,-2.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.650000
948299,0042400401,1610612760,Oklahoma City,Thunder,OKC,thunder,1642349,Ajay,Mitchell,A. Mitchell,ajay-mitchell,NaN,NaN,0.0,4:10,100.0,130.0,-17.5,-30.0,0.000,0.00,0.0,0.429,0.000,0.250,0.0,0.000,0.000,0.231,105.98,115.20,10.0,-0.083,0.222,0.667,0.000,0.563,0.500,0.205,0.400,0,0,0,0,0,2,0,0,1,0,0.667,0.333,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,3,0,1,0.00,0,0,0.0,3,0,3,0,0,0,0,0,0,-3.0,0.000,0.333,0.000,0.500,0.000,0.000,1.000,0.000,0.500,0.000,0.000,0.000,0.0,1.0,0.000,0.000,0.000,4.166667
948300,0042400401,1610612760,Oklahoma City,Thunder,OKC,thunder,1631172,Ousmane,Dieng,O. Dieng,ousmane-dieng,NaN,DNP - Coach's Decision,0.0,NaN,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.00,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0,0,0,0,0,0,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0,0,0,0.00,0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000000
948301,0042400401,1610612760,Oklahoma City,Thunder,OKC,thunder,1641794,Dillon,Jones,D. Jones,dillon-jones,NaN,DNP - Coach's Decision,0.0,NaN,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.00,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0,0,0,0,0,0,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0,0,0,0.00,0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000000
948302,0042400401,1610612760,Oklahoma City,Thunder,OKC,thunder,1631119,Jaylin,Williams,J. Williams,jaylin-williams,NaN,DNP - Coach's Decision,0.0,NaN,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.00,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0,0,0,0,0,0,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0,0,0,0.00,0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000000

# Clean duplicates boxscores

In [11]:
# remove duplicate rows based on 'GAME_ID' and 'TEAM_ID' and "playerSlug"
df_boxscores = df_boxscores.drop_duplicates(subset=['GAME_ID', 'TEAM_ID', 'playerSlug'])

# Build player features

In [12]:
player_features_df = build_player_status_features(df_boxscores)

today = datetime.now().strftime('%Y-%m-%d_%H-%M-%S')


os.makedirs(DATA_PLAYERS_DIR, exist_ok=True)
player_features_output = os.path.join(DATA_PLAYERS_DIR, f'player_features_{today}.csv')

# to csv
#player_features_df.to_csv(player_features_output, index=False)

In [13]:
player_features_df

,GAME_ID,TEAM_ID,personId,is_present,is_absent,is_injured,is_resting,is_suspended,is_personal,player_perf_score,player_defense_score,player_offense_score,player_impact_score,comment
0,0021000002,1610612756,255,1,0,0,0,0,0,4.7,0.5,3.3,-0.011,
1,0021000002,1610612756,2045,1,0,0,0,0,0,12.6,-3.5,9.2,0.010,
2,0021000002,1610612756,201577,1,0,0,0,0,0,12.2,1.5,5.0,0.071,
3,0021000002,1610612756,2202,1,0,0,0,0,0,30.7,1.5,26.9,0.184,
4,0021000002,1610612756,959,1,0,0,0,0,0,30.6,0.5,31.2,0.127,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
948269,0042400401,1610612760,1629026,1,0,0,0,0,0,0.0,0.0,0.0,0.000,
948270,0042400401,1610612760,1642349,1,0,0,0,0,0,3.6,0.0,0.0,-0.083,
948271,0042400401,1610612760,1631172,0,1,0,0,0,0,0.0,0.0,0.0,0.000,dnp - coach's decision
948272,0042400401,1610612760,1641794,0,1,0,0,0,0,0.0,0.0,0.0,0.000,dnp - coach's decision
948273,0042400401,1610612760,1631119,0,1,0,0,0,0,0.0,0.0,0.0,0.000,dnp - coach's decision

In [14]:
#player_features_df[player_features_df['is_absent'] == 1].sort_values(by='GAME_ID').head(50)

#same but filter with comment "DNP - Coach's Decision"

filtered = player_features_df[
    (player_features_df['is_absent'] == 1) &
    (~player_features_df['comment'].str.contains("coach's decision", na=False))
]
display(filtered.sort_values(by=['GAME_ID', 'TEAM_ID']).tail(50))

filtered = player_features_df[
    (player_features_df['is_personal'] == 1) &
    (~player_features_df['comment'].str.contains("personal", na=False)) &
    (~player_features_df['comment'].str.contains("not with team", na=False)) 
]
display(filtered.sort_values(by=['GAME_ID', 'TEAM_ID']).tail(50))




# display(player_features_df[
#     player_features_df['is_personal'] == 1 &
#     (~player_features_df['comment'].str.contains("nwt", na=False))
#     ].head(50))

,GAME_ID,TEAM_ID,personId,is_present,is_absent,is_injured,is_resting,is_suspended,is_personal,player_perf_score,player_defense_score,player_offense_score,player_impact_score,comment
514612,0021801052,1610612743,1629020,0,1,0,0,0,0,0.0,0.0,0.0,0.0,
517602,0021801174,1610612756,2037,0,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd_coach
517826,0021801187,1610612742,1628961,0,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd_coach
563883,0021900398,1610612742,1626246,0,1,0,0,0,0,0.0,0.0,0.0,0.0,
565484,0021900464,1610612758,1629713,0,1,0,0,0,0,-1.0,0.0,-1.0,1.0,
573084,0021900770,1610612742,1626246,0,1,0,0,0,0,0.0,0.0,0.0,0.0,
579425,0021901281,1610612743,1629626,0,1,0,0,0,0,0.0,0.0,0.0,0.0,
579413,0021901281,1610612762,1629730,0,1,0,0,0,0,0.0,0.0,0.0,0.0,
617776,0022000485,1610612738,1629605,0,1,0,0,0,0,0.0,0.0,0.0,0.0,
623462,0022000678,1610612748,202340,0,1,0,0,0,0,0.0,0.0,0.0,0.0,nwt - trade pending
623465,0022000678,1610612748,203090,0,1,0,0,0,0,0.0,0.0,0.0,0.0,nwt - trade pending
623466,0022000678,1610612748,203482,0,1,0,0,0,0,0.0,0.0,0.0,0.0,nwt - trade pending
623467,0022000678,1610612748,1629735,0,1,0,0,0,0,0.0,0.0,0.0,0.0,nwt - trade pending
623685,0022000686,1610612748,202357,0,1,0,0,0,0,0.0,0.0,0.0,0.0,nwt - trade pending
623687,0022000686,1610612748,203506,0,1,0,0,0,0,0.0,0.0,0.0,0.0,nwt - trade pending
694990,0022100074,1610612740,1626195,0,1,0,0,0,0,0.0,0.0,0.0,0.0,
705821,0022100151,1610612743,1629626,0,1,0,0,0,0,0.0,0.0,0.0,1.0,
694416,0022100954,1610612742,1626246,0,1,0,0,0,0,0.0,0.0,0.0,0.0,
698525,0022101086,1610612758,1629674,0,1,0,0,0,0,0.0,0.0,0.0,0.0,
757853,0022200793,1610612764,201959,0,1,0,0,0,0,0.0,0.0,0.0,0.0,
758066,0022200798,1610612740,1626195,0,1,0,0,0,0,0.0,0.0,0.0,0.0,
758790,0022200830,1610612757,1628404,0,1,0,0,0,0,0.0,0.0,0.0,0.0,nwt - trade pending
811571,0022300007,1610612763,202687,0,1,0,0,0,0,0.0,0.0,0.0,0.0,
811039,0022300126,1610612744,1631218,0,1,0,0,0,0,0.0,0.0,0.0,0.0,
812349,0022300162,1610612756,1629626,0,1,0,0,0,0,0.0,0.0,0.0,0.0,
815060,0022300226,1610612743,203200,0,1,0,0,0,0,0.0,0.0,0.0,0.0,
815347,0022300238,1610612742,203552,0,1,0,0,0,0,0.0,0.0,0.0,0.0,
821082,0022300410,1610612740,203469,0,1,0,0,0,0,0.0,0.0,0.0,0.0,
829790,0022300745,1610612766,1630544,0,1,0,0,0,0,0.0,0.0,0.0,0.0,nwt - trade pending
835084,0022300948,1610612754,1630543,0,1,0,0,0,0,0.0,0.0,0.0,0.0,
839790,0022301133,1610612754,1630543,0,1,0,0,0,0,0.0,0.0,0.0,0.0,
898352,0022400721,1610612755,1629656,0,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd - trade pending
898412,0022400725,1610612744,203937,0,1,0,0,0,0,0.0,0.0,0.0,0.0,dnp_trade
898414,0022400725,1610612744,203471,0,1,0,0,0,0,0.0,0.0,0.0,0.0,dnp_trade
898415,0022400725,1610612744,1630322,0,1,0,0,0,0,0.0,0.0,0.0,0.0,dnp_trade
898416,0022400725,1610612744,203952,0,1,0,0,0,0,0.0,0.0,0.0,0.0,dnp_trade
901456,0022400831,1610612745,203500,0,1,0,0,0,0,0.0,0.0,0.0,0.0,
904312,0022400942,1610612754,1628396,0,1,0,0,0,0,1.2,0.0,0.0,1.0,
908530,0022401102,1610612750,1630568,0,1,0,0,0,0,0.0,0.0,0.0,0.0,
888535,0022401211,1610612751,1630570,0,1,0,0,0,0,0.0,0.0,0.0,0.0,
29716,0041000162,1610612757,202356,0,1,0,0,0,0,1.2,0.0,0.0,1.0,
182811,0041300152,1610612763,201585,0,1,0,0,0,0,0.0,0.0,0.0,0.0,
182582,0041300161,1610612744,203136,0,1,0,0,0,0,0.0,0.0,0.0,0.0,
251134,0041400222,1610612763,201979,0,1,0,0,0,0,0.0,0.0,0.0,0.0,
251719,0041400301,1610612737,1882,0,1,0,0,0,0,1.0,-1.0,1.2,1.0,
317960,0041500234,1610612759,1889,0,1,0,0,0,0,0.0,0.0,0.0,0.0,
520484,0041800214,1610612755,1626246,0,1,0,0,0,0,0.0,0.0,0.0,0.0,
581233,0041900175,1610612745,2199,0,1,0,0,0,0,0.0,0.0,0.0,1.0,
582062,0041900301,1610612738,202683,0,1,0,0,0,0,0.0,0.0,0.0,0.0,
843520,0042300225,1610612742,203939,0,1,0,0,0,0,0.0,0.0,0.0,0.0,

,GAME_ID,TEAM_ID,personId,is_present,is_absent,is_injured,is_resting,is_suspended,is_personal,player_perf_score,player_defense_score,player_offense_score,player_impact_score,comment
16303,0021000686,1610612765,1112,0,0,0,0,0,1,0.0,0.0,0.0,0.0,nwt - family matter
16830,0021000705,1610612765,1112,0,0,0,0,0,1,0.0,0.0,0.0,0.0,nwt - family matter
20912,0021000874,1610612765,1112,0,0,0,0,0,1,0.0,0.0,0.0,0.0,nwt - family matter
21593,0021000906,1610612750,2545,0,0,0,0,0,1,0.0,0.0,0.0,0.0,nwt - family matter
26648,0021001107,1610612765,101198,0,0,0,0,0,1,0.0,0.0,0.0,0.0,nwt - family matter
53094,0021100099,1610612765,2732,0,0,0,0,0,1,0.0,0.0,0.0,0.0,nwt - family matters
57762,0021100181,1610612765,2863,0,0,0,0,0,1,0.0,0.0,0.0,0.0,nwt - family matter
33188,0021100260,1610612765,2419,0,0,0,0,0,1,0.0,0.0,0.0,0.0,dnd - family matter
33266,0021100274,1610612765,2419,0,0,0,0,0,1,0.0,0.0,0.0,0.0,nwt - family matter
46386,0021100741,1610612757,101109,0,0,0,0,0,1,0.0,0.0,0.0,0.0,nwt - family
47142,0021100771,1610612737,711,0,0,0,0,0,1,0.0,0.0,0.0,0.0,nwt - family emergency
47500,0021100784,1610612744,202148,0,0,0,0,0,1,0.0,0.0,0.0,0.0,nwt - family matters
47808,0021100796,1610612744,202148,0,0,0,0,0,1,0.0,0.0,0.0,0.0,nwt - family matters
51808,0021100947,1610612757,101109,0,0,0,0,0,1,0.0,0.0,0.0,0.0,nwt - family matter
117806,0021200144,1610612738,2545,0,0,0,0,0,1,0.0,0.0,0.0,0.0,nwt - family reasons
97416,0021200607,1610612745,202962,0,0,0,0,0,1,0.0,0.0,0.0,0.0,nwt - family reasons
113129,0021201169,1610612756,201563,0,0,0,0,0,1,0.0,0.0,0.0,0.0,nwt - family reasons
113398,0021201182,1610612739,203079,0,0,0,0,0,1,0.0,0.0,0.0,0.0,nwt - family matters
227243,0021400441,1610612757,2549,0,0,0,0,0,1,0.0,0.0,0.0,0.0,nwt - family
239435,0021400871,1610612737,201143,0,0,0,0,0,1,0.0,0.0,0.0,0.0,nwt - family reasons

In [15]:

# Analyse des statuts des joueurs
total_rows = len(player_features_df)

# Comptage des cas
n_present = player_features_df['is_present'].sum()
n_absent = player_features_df['is_absent'].sum()
n_injured = player_features_df['is_injured'].sum()

# is_resting
# is_suspended
# is_personal

n_resting = player_features_df['is_resting'].sum()
n_suspended = player_features_df['is_suspended'].sum()
n_personal = player_features_df['is_personal'].sum()

# Lignes incohérentes : aucune des colonnes n'est True

mask_no_status = (
    (player_features_df['is_present'] == 0) &
    (player_features_df['is_absent'] == 0) &
    (player_features_df['is_injured'] == 0) &
    (player_features_df['is_resting'] == 0) &
    (player_features_df['is_suspended'] == 0) &
    (player_features_df['is_personal'] == 0)
)


n_inconsistent = mask_no_status.sum()

# Lignes avec plusieurs statuts à la fois (logiquement impossible)
mask_multiple_status = (
    player_features_df[['is_present', 'is_absent', 'is_injured']].sum(axis=1) > 1
)
n_multiple = mask_multiple_status.sum()

print(f"✅ Analyse des statuts des joueurs sur {total_rows} lignes")
print(f" - Joueurs présents : {n_present}")
print(f" - Joueurs absents : {n_absent}")
print(f" - Joueurs blessés : {n_injured}")
print(f" - Joueurs en repos : {n_resting}")
print(f" - Joueurs suspendus : {n_suspended}")
print(f" - Joueurs pour raisons personnelles : {n_personal}")
print(f"❌ Lignes sans statut défini : {n_inconsistent}")
print(f"⚠️ Lignes avec plusieurs statuts actifs : {n_multiple}")

display(player_features_df[mask_no_status].head(10))

✅ Analyse des statuts des joueurs sur 489857 lignes
 - Joueurs présents : 403786
 - Joueurs absents : 72372
 - Joueurs blessés : 12267
 - Joueurs en repos : 379
 - Joueurs suspendus : 482
 - Joueurs pour raisons personnelles : 571
❌ Lignes sans statut défini : 0
⚠️ Lignes avec plusieurs statuts actifs : 0

Empty DataFrame
Columns: [GAME_ID, TEAM_ID, personId, is_present, is_absent, is_injured, is_resting, is_suspended, is_personal, player_perf_score, player_defense_score, player_offense_score, player_impact_score, comment]
Index: []

# ⚙️ Aggrégation des data Player par équipe et match

In [16]:
# df_team_players = aggregate_team_player_features(player_features_df, top_n=10)

# display(df_team_players.head(10))
# display(df_team_players.tail(10))

# #display some lines with absent players
# absent_players = df_team_players[df_team_players['num_injured'] >= 1]
# absent_players 

# Identification des top joueurs sur l'ensemble du dataset
df_top_players = identify_historical_top_players(player_features_df)
print(f"✅ {df_top_players['tag_top_player'].sum()} top joueurs identifiés sur {len(df_top_players)} joueurs.")


df_agg_actual = aggregate_actual_team_features(player_features_df)
print(f"✅ {df_agg_actual.shape[0]} lignes générées dans l'aggregation actuelle par équipe.")

df_agg_top_abs = flag_top_players_absences(player_features_df, df_top_players)
print(f"✅ {df_agg_top_abs['top_player_absence_count'].sum()} absences de top joueurs détectées.")


df_team_features_final = df_agg_actual.merge(df_agg_top_abs, on=["GAME_ID", "TEAM_ID"], how="left")
df_team_features_final.fillna(0, inplace=True)
print(f"✅ Fusion réussie. Shape finale : {df_team_features_final.shape}")

KeyError: "['GAME_DATE'] not in index"

In [ ]:
display(df_team_features_final.head(10))
display(df_team_features_final.tail(10))

display(df_team_features_final[df_team_features_final['top_player_absence_count'] > 0].head(20))

,GAME_ID,TEAM_ID,team_perf_score_sum,team_defense_score_sum,team_offense_score_sum,team_impact_score_sum,team_num_players_present,team_num_players_absent,team_num_injured,team_num_resting,team_num_suspended,team_num_personal,team_presence_rate,top_player_absence_count,top_injured,top_resting,top_suspended,top_personal
0,0021000001,1610612738,167.9,-4.0,125.1,0.860,9,2,0,0,1,0,0.818182,2.0,0.0,0.0,0.0,0.0
1,0021000001,1610612748,148.3,3.0,101.5,0.806,9,3,0,0,0,0,0.750000,3.0,0.0,0.0,0.0,0.0
2,0021000002,1610612756,138.5,-8.5,113.9,0.645,10,2,0,0,0,0,0.833333,2.0,0.0,0.0,0.0,0.0
3,0021000002,1610612757,211.1,-2.5,161.7,-4.608,10,2,0,0,0,0,0.833333,2.0,0.0,0.0,0.0,0.0
4,0021000003,1610612745,204.1,-5.5,149.5,0.831,10,2,0,0,0,0,0.833333,2.0,0.0,0.0,0.0,0.0
5,0021000003,1610612747,199.3,-1.5,153.9,0.547,10,2,0,0,0,0,0.833333,2.0,0.0,0.0,0.0,0.0
6,0021000004,1610612738,158.6,-10.5,121.4,-0.574,10,1,0,0,1,0,0.909091,1.0,0.0,0.0,0.0,0.0
7,0021000004,1610612739,170.4,-6.5,136.0,0.922,9,3,0,0,0,0,0.750000,3.0,0.0,0.0,0.0,0.0
8,0021000005,1610612751,176.3,-11.0,135.7,0.479,12,0,0,0,0,0,1.000000,0.0,0.0,0.0,0.0,0.0
9,0021000005,1610612765,177.9,-4.0,143.1,0.936,10,2,0,0,0,0,0.833333,2.0,0.0,0.0,0.0,0.0

,GAME_ID,TEAM_ID,team_perf_score_sum,team_defense_score_sum,team_offense_score_sum,team_impact_score_sum,team_num_players_present,team_num_players_absent,team_num_injured,team_num_resting,team_num_suspended,team_num_personal,team_presence_rate,top_player_absence_count,top_injured,top_resting,top_suspended,top_personal
38296,0052400111,1610612741,154.1,2.5,113.5,0.814,11,1,0,0,0,0,0.916667,1.0,0.0,0.0,0.0,0.0
38297,0052400111,1610612748,210.0,9.5,160.8,0.059,11,2,2,0,0,0,0.846154,2.0,0.0,0.0,0.0,0.0
38298,0052400121,1610612744,217.3,1.0,178.7,0.831,10,5,0,0,0,0,0.666667,5.0,0.0,0.0,0.0,0.0
38299,0052400121,1610612763,195.0,-18.5,153.2,0.573,9,4,0,0,0,0,0.692308,4.0,0.0,0.0,0.0,0.0
38300,0052400131,1610612742,220.7,10.5,178.5,0.545,13,0,0,0,0,0,1.000000,0.0,0.0,0.0,0.0,0.0
38301,0052400131,1610612758,185.3,-4.0,143.7,1.746,12,1,0,0,0,0,0.923077,1.0,0.0,0.0,0.0,0.0
38302,0052400201,1610612737,217.8,4.5,172.8,0.645,9,2,1,0,0,0,0.818182,2.0,0.0,0.0,0.0,0.0
38303,0052400201,1610612748,235.3,3.0,183.1,0.926,9,5,0,0,0,1,0.642857,5.0,0.0,0.0,0.0,0.0
38304,0052400211,1610612742,187.7,8.5,148.7,0.529,11,2,0,0,0,0,0.846154,2.0,0.0,0.0,0.0,0.0
38305,0052400211,1610612763,227.0,1.0,179.0,0.848,12,1,0,0,0,0,0.923077,1.0,0.0,0.0,0.0,0.0

,GAME_ID,TEAM_ID,team_perf_score_sum,team_defense_score_sum,team_offense_score_sum,team_impact_score_sum,team_num_players_present,team_num_players_absent,team_num_injured,team_num_resting,team_num_suspended,team_num_personal,team_presence_rate,top_player_absence_count,top_injured,top_resting,top_suspended,top_personal
0,0021000001,1610612738,167.9,-4.0,125.1,0.860,9,2,0,0,1,0,0.818182,2.0,0.0,0.0,0.0,0.0
1,0021000001,1610612748,148.3,3.0,101.5,0.806,9,3,0,0,0,0,0.750000,3.0,0.0,0.0,0.0,0.0
2,0021000002,1610612756,138.5,-8.5,113.9,0.645,10,2,0,0,0,0,0.833333,2.0,0.0,0.0,0.0,0.0
3,0021000002,1610612757,211.1,-2.5,161.7,-4.608,10,2,0,0,0,0,0.833333,2.0,0.0,0.0,0.0,0.0
4,0021000003,1610612745,204.1,-5.5,149.5,0.831,10,2,0,0,0,0,0.833333,2.0,0.0,0.0,0.0,0.0
5,0021000003,1610612747,199.3,-1.5,153.9,0.547,10,2,0,0,0,0,0.833333,2.0,0.0,0.0,0.0,0.0
6,0021000004,1610612738,158.6,-10.5,121.4,-0.574,10,1,0,0,1,0,0.909091,1.0,0.0,0.0,0.0,0.0
7,0021000004,1610612739,170.4,-6.5,136.0,0.922,9,3,0,0,0,0,0.750000,3.0,0.0,0.0,0.0,0.0
9,0021000005,1610612765,177.9,-4.0,143.1,0.936,10,2,0,0,0,0,0.833333,2.0,0.0,0.0,0.0,0.0
10,0021000006,1610612748,161.9,3.0,122.9,0.804,11,1,0,0,0,0,0.916667,1.0,0.0,0.0,0.0,0.0
11,0021000006,1610612755,166.6,-1.0,124.4,-0.668,11,1,0,0,0,0,0.916667,1.0,0.0,0.0,0.0,0.0
12,0021000007,1610612752,173.8,-2.0,120.6,0.621,10,2,0,0,0,0,0.833333,1.0,0.0,0.0,0.0,0.0
13,0021000007,1610612761,177.0,-3.5,130.6,0.913,10,1,0,0,1,0,0.909091,1.0,0.0,0.0,0.0,0.0
14,0021000008,1610612737,202.8,4.0,157.8,1.191,11,1,0,0,0,0,0.916667,1.0,0.0,0.0,0.0,0.0
16,0021000009,1610612750,204.2,-12.5,159.2,1.076,11,1,0,0,0,0,0.916667,1.0,0.0,0.0,0.0,0.0
20,0021000011,1610612741,185.7,-10.0,131.5,0.602,11,1,0,0,0,0,0.916667,1.0,0.0,0.0,0.0,0.0
21,0021000011,1610612760,193.3,16.5,140.7,1.169,9,3,0,0,0,0,0.750000,3.0,0.0,0.0,0.0,0.0
22,0021000012,1610612742,194.7,7.5,148.7,-0.841,11,1,0,0,0,0,0.916667,1.0,0.0,0.0,0.0,0.0
23,0021000012,1610612766,153.2,1.5,116.2,0.638,10,2,0,0,0,0,0.833333,1.0,0.0,0.0,0.0,0.0
24,0021000013,1610612754,174.2,-3.5,137.8,0.564,9,2,0,0,1,0,0.818182,2.0,0.0,0.0,0.0,0.0

# ⚙️ Aggrégation des data Boxscore purs par équipe et match

## Définir les colonnes à sommer et à moyenner pondérées

In [ ]:

cols_to_sum = [
    'fieldGoalsMade_traditional', 'fieldGoalsAttempted_traditional',
    'threePointersMade_traditional', 'threePointersAttempted_traditional',
    'freeThrowsMade_traditional', 'freeThrowsAttempted_traditional',
    'reboundsOffensive_traditional', 'reboundsDefensive_traditional',
    'reboundsTotal_traditional', 'assists_traditional', 'steals_traditional',
    'blocks_traditional', 'turnovers_traditional', 'foulsPersonal_traditional',
    'points_traditional', 'MINUTES_PLAYED',
    'pointsOffTurnovers_misc', 'pointsSecondChance_misc', 'pointsFastBreak_misc',
    'pointsPaint_misc', 'blocksAgainst_misc'
]

cols_to_weighted_avg = [
    'offensiveRating_advanced', 'defensiveRating_advanced', 'netRating_advanced',
    'assistPercentage_advanced', 'assistToTurnover_advanced', 'assistRatio_advanced',
    'offensiveReboundPercentage_advanced', 'defensiveReboundPercentage_advanced',
    'reboundPercentage_advanced', 'turnoverRatio_advanced', 'effectiveFieldGoalPercentage_advanced',
    'trueShootingPercentage_advanced', 'usagePercentage_advanced', 'estimatedPace_advanced',
    'pace_advanced', 'possessions_advanced', 'PIE_advanced',
    'effectiveFieldGoalPercentage_fourfactors', 'freeThrowAttemptRate_fourfactors',
    'teamTurnoverPercentage_fourfactors', 'oppEffectiveFieldGoalPercentage_fourfactors',
    'oppFreeThrowAttemptRate_fourfactors', 'oppTeamTurnoverPercentage_fourfactors',
    'oppOffensiveReboundPercentage_fourfactors', 'foulsDrawn_misc',
    'percentageFieldGoalsAttempted2pt_scoring', 'percentageFieldGoalsAttempted3pt_scoring',
    'percentagePoints2pt_scoring', 'percentagePointsMidrange2pt_scoring',
    'percentagePoints3pt_scoring', 'percentagePointsFastBreak_scoring',
    'percentagePointsFreeThrow_scoring', 'percentagePointsOffTurnovers_scoring',
    'percentagePointsPaint_scoring', 'percentageAssisted2pt_scoring',
    'percentageUnassisted2pt_scoring', 'percentageAssisted3pt_scoring',
    'percentageUnassisted3pt_scoring', 'percentageAssistedFGM_scoring',
    'percentageUnassistedFGM_scoring', 'threePointersPercentage_traditional',
    'freeThrowsPercentage_traditional', 'percentageFieldGoalsMade_usage',
    'percentageFieldGoalsAttempted_usage', 'percentageThreePointersMade_usage',
    'percentageThreePointersAttempted_usage', 'percentageFreeThrowsMade_usage',
    'percentageFreeThrowsAttempted_usage', 'percentageReboundsOffensive_usage',
    'percentageReboundsDefensive_usage', 'percentageReboundsTotal_usage',
    'percentageAssists_usage', 'percentageTurnovers_usage', 'percentageSteals_usage',
    'percentageBlocks_usage', 'percentageBlocksAllowed_usage', 'percentagePersonalFouls_usage',
    'percentagePersonalFoulsDrawn_usage', 'percentagePoints_usage','plusMinusPoints_traditional'
]

## 📊 Agrégation des données par équipe et match

In [ ]:

# 1. Agrégation par somme
group_keys = ['GAME_ID', 'TEAM_ID']
sum_agg = df_boxscores[group_keys + cols_to_sum].copy()
sum_agg = sum_agg.groupby(group_keys).sum().reset_index()

# 2. Agrégation pondérée par les minutes jouées
weighted_agg = compute_weighted_mean_features(df_boxscores, group_keys, cols_to_weighted_avg, weight_col='MINUTES_PLAYED')

# 3. Fusion des deux agrégats
team_match_stats = pd.merge(sum_agg, weighted_agg, on=group_keys, how='left')

# 4. Identifier l'équipe adverse
teams_in_game = df_boxscores.groupby('GAME_ID')['TEAM_ID'].unique().to_dict()
team_match_stats['OPP_TEAM_ID'] = team_match_stats.apply(
    lambda row: [tid for tid in teams_in_game[row['GAME_ID']] if tid != row['TEAM_ID']][0], axis=1
)

# Ajout GAME_DATE

In [ ]:
df_games['GAME_DATE'] = pd.to_datetime(df_games['GAME_DATE'])
team_match_stats = team_match_stats.merge(
    df_games[['GAME_ID', 'TEAM_ID', 'GAME_DATE']],
    on=['GAME_ID', 'TEAM_ID'],
    how='left'
)

In [ ]:

team_match_stats

,GAME_ID,TEAM_ID,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,points_traditional,MINUTES_PLAYED,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,blocksAgainst_misc,offensiveRating_advanced,defensiveRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,threePointersPercentage_traditional,freeThrowsPercentage_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage,plusMinusPoints_traditional,OPP_TEAM_ID,GAME_DATE
0,0021000001,1610612738,32,69,8,16,16,25,8,34,42,25,6,4,18,19,88,240.000000,17,11,11,38,6,95.258826,86.767938,8.458819,0.179324,1.418765,16.786944,0.040284,0.143548,0.097696,13.576424,0.536647,0.565526,0.192004,91.500720,92.499906,61.978819,0.121102,0.524833,0.364811,0.217790,0.420576,0.341330,0.187027,0.244226,2.633472,0.773753,0.226247,0.600667,0.136254,0.202795,0.091713,0.196539,0.204380,0.464413,0.525706,0.421030,0.332569,0.000000,0.710834,0.235902,0.228976,0.522179,0.200810,0.200914,0.180178,0.199018,0.197938,0.195703,0.190636,0.204025,0.202745,0.190902,0.178942,0.176299,0.151945,0.196471,0.197720,0.199016,0.200868,4.585556,1610612748,2010-10-26
1,0021000001,1610612748,27,74,8,20,18,25,11,28,39,15,10,6,17,21,80,240.000000,22,5,11,24,4,86.585597,94.558222,-7.960403,0.158097,0.533849,13.530931,0.049858,0.138836,0.087374,10.813681,0.426550,0.495102,0.197047,91.499007,92.600174,59.272778,0.090339,0.418351,0.344338,0.188392,0.524045,0.364850,0.217761,0.223355,2.708681,0.712399,0.243379,0.496113,0.140206,0.278267,0.123794,0.225773,0.204365,0.355907,0.308280,0.538734,0.396736,0.152847,0.520927,0.434698,0.226023,0.579196,0.205427,0.199612,0.187020,0.186814,0.196853,0.187300,0.218039,0.202114,0.198359,0.228813,0.200531,0.173722,0.193393,0.147483,0.203271,0.192911,0.203349,-6.306528,1610612738,2010-10-26
2,0021000002,1610612756,36,74,9,19,11,16,7,23,30,15,3,4,19,19,92,240.000000,17,11,6,44,2,101.425007,116.062382,-14.648243,0.113202,0.765569,12.112500,0.037518,0.088750,0.065437,15.816979,0.525870,0.535510,0.195844,94.820024,91.299769,49.458125,0.072061,0.551087,0.219725,0.204248,0.516365,0.162388,0.155634,0.433928,2.182639,0.755892,0.244108,0.571466,0.086887,0.339328,0.039907,0.089060,0.246915,0.484873,0.259333,0.521430,0.333822,0.231595,0.436625,0.563375,0.372170,0.355924,0.197446,0.201281,0.204137,0.193324,0.178646,0.176324,0.205161,0.195726,0.197705,0.204080,0.182448,0.135582,0.266250,0.217986,0.189598,0.189302,0.196874,-7.175972,1610612757,2010-10-26
3,0021000002,1610612757,43,93,10,20,10,15,18,30,48,31,11,2,12,22,106,240.000000,21,21,13,42,4,116.705951,101.868819,14.847993,0.179627,1.619028,21.211271,0.071370,0.149384,0.105635,7.830722,0.500923,0.520792,0.191743,94.821719,91.100492,55.840069,0.059822,0.516180,0.167638,0.156635,0.550046,0.216926,0.204611,0.194777,2.417917,0.803757,0.196243,0.626211,0.218095,0.243037,0.126697,0.118044,0.228035,0.408116,0.552484,0.343836,0.495069,0.000000,0.696103,0.291188,0.261279,0.596760,0.198572,0.201131,0.215227,0.194294,0.199463,0.211358,0.207308,0.211804,0.199374,0.199567,0.145885,0.190182,0.204896,0.180178,0.195436,0.204637,0.199758,9.013194,1610612756,2010-10-26
4,0021000003,1610612745,38,91,8,20,26,28,16,37,53,25,6,7,20,25,110,239.983333,10,16,17,42,4,106.091812,106.928071,-0.849344,0.163359,1.393743,22.918397,0.061861,0.126248,0.095825,12.957421,0.402580,0.475858,0.198410,107.319701,104.201138,61.522328,0.102728,0.462191,0.307097,0.193372,0.466376,0.295486,0.112989,0.279195,3.016946,0.693632,0.244628,0.453675,0.138961,0.260127,0.120814,0.204803,0.083422,0.314576,0.444436,0.343327,0.383863,0.043388,0.668162,0.250444,0.220759,0.663562,0.195155,0.200732,0.158192,0.197478,0.179789,0.185280,0.236348,0.191520,0.197204,0.203254,0.194367,0.177269,0.216853,0.199693,0.193461,0.186709,0.195638,1.938676,1610612747,2010-10-26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48447,0052400201,1610612748,96,192,32,84,22,36,26,82,108,66,8,16,28,30,246,530.000000,36,34,28,96,6,114.115346,109.194151,4.941660,0.175512,1.914025,21.394906,0.052826,0.136744,0.098506,8.743547,0.602740,0.610614,0.188164,96.091468,96.271151,74.389497,0.108900,0.582882,0.188123,0.140615,0.511179,0.117131,0.094058,0.210104,2.789245,0.569122,0.430878,0.531708,0.131616,0.389409,0.104841,0.078883,0.158831,0.400093,0.679972,0.320028,0.594560,0.156132,0.689231,0.310769,0.317894,0.399580,0.200367,0.200068,0.199439,0.200160,0.203244,0.198173,0.193693,0.197318,0.198007,0.203462,0.175619,0.211259,0.195655,0.227722,0.201947,0.191826,0.199943,7.759057,1610612737,2025-04-18
48448,0052400211,1610612742,82,174,24,76,24,32,14,58,72,50,18,16,32,34,212,479.966667,28,30,30,88,8,103.971838,117.104361,-13.146712,0.159645,1.043291,21.438058,0.028121,0.109295,0.071448,14.196291,0.505059,0.518344,0.194360,102.820733,102.200355,55.776790,0.083048,0.540618,0.184078,0.155320,0.534614,0.150467,0.117294,0.351484,1.775957,0.589597,0.410403,0.375406,0.089519,0.288293,0.120119,0.077834,0.102521,0.286029,0.431148,0.256678,0.465397,0.199927,0.498200,0.243395,0.324056,0.404056,0.199455,0.198674,0.234511,0.197563,0.188766,0.193288,0.179929,0.199788,0.199410,0.199269,0.194797,0.201698,0.189836,0.148746,0.180069,0.178183,0.199691,-8.414820,1610612763,2025-04-18
48449,0052400211,1610612742,82,174,24,76,24,32,14,58,72,50,18,16,32,34,212,479.966667,28,30,30,88,8,103.971838,117.104361,-13.146712,0.159645,1.043291,21.438058,0.028121,0.109295,0.071448,14.196291,0.505059,0.518344,0.194360,102.820733,102.200355,55.776790,0.083048,0.540618,0.184078,0.155320,0.534614,0.150467,0.117294,0.351484,1.775957,0.589597,0.410403,0.375406,0.089519,0.288293,0.120119,0.077834,0.102521,0.286029,0.431148,0.256678,0.465397,0.199927,0.498200,0.243395,0.324056,0.404056,0.199455,0.198674,0.234511,0.197563,0.188766,0.193288,0.179929,0.199788,0.199410,0.199269,0.194797,0.201698,0.189836,0.148746,0.180069,0.178183,0.199691,-8.414820,1610612763,2025-04-18
48450,0052400211,1610612763,94,200,26,62,26,30,32,68,100,60,16,8,20,34,240,480.000000,48,30,38,120,16,118.571125,105.071556,13.509528,0.154672,0.823437,19.079396,0.059757,0.149789,0.100197,4.889924,0.566430,0.582027,0.191697,102.820601,101.299056,62.138194,0.109814,0.532094,0.153846,0.116233,0.542366,0.187143,0.155200,0.164587,2.136944,0.650762,0.334099,0.569661,0.056488,0.328575,0.226652,0.078919,0.205619,0.513310,0.620063,0.349659,0.682240,0.087343,0.648875,0.320847,0.348328,0.327988,0.197052,0.199753,0.185188,0.203577,0.155673,0.161807,0.197832,0.203155,0.201390,0.197460,0.149565,0.187630,0.217161,0.174559,0.196685,0.173665,0.201920,11.408611,1610612742,2025-04-18
48451,0052400211,1610612763,94,200,26,62,26,30,32,68,100,60,16,8,20,34,240,480.000000,48,30,38,120,16,118.571125,105.071556,13.509528,0.154672,0.823437,19.079396,0.059757,0.149789,0.100197,4.889924,0.566430,0.582027,0.191697,102.820601,101.299056,62.138194,0.109814,0.532094,0.153846,0.116233,0.542366,0.187143,0.155200,0.164587,2.136944,0.650762,0.334099,0.569661,0.056488,0.328575,0.226652,0.078919,0.205619,0.513310,0.620063,0.349659,0.682240,0.087343,0.648875,0.320847,0.348328,0.327988,0.197052,0.199753,0.185188,0.203577,0.155673,0.161807,0.197832,0.203155,0.201390,0.197460,0.149565,0.187630,0.217161,0.174559,0.196685,0.173665,0.201920,11.408611,1610612742,2025-04-18

# 🔁 Merge avec l’adversaire

In [ ]:
team_cols = [col for col in team_match_stats.columns if col not in ['GAME_ID', 'TEAM_ID', 'OPP_TEAM_ID']]
opp_cols = [f"OPP_{col}" for col in team_cols]
df_opp = team_match_stats.rename(columns={col: f"OPP_{col}" for col in team_cols}).rename(
    columns={'TEAM_ID': 'OPP_TEAM_ID', 'OPP_TEAM_ID': 'TEAM_ID'})
match_dataset = pd.merge(
    team_match_stats,
    df_opp[['GAME_ID', 'TEAM_ID'] + opp_cols],
    on=['GAME_ID', 'TEAM_ID'],
    how='left'
)

In [ ]:
match_dataset.columns

Index(['GAME_ID', 'TEAM_ID', 'fieldGoalsMade_traditional',
       'fieldGoalsAttempted_traditional', 'threePointersMade_traditional',
       'threePointersAttempted_traditional', 'freeThrowsMade_traditional',
       'freeThrowsAttempted_traditional', 'reboundsOffensive_traditional',
       'reboundsDefensive_traditional',
       ...
       'OPP_percentageAssists_usage', 'OPP_percentageTurnovers_usage',
       'OPP_percentageSteals_usage', 'OPP_percentageBlocks_usage',
       'OPP_percentageBlocksAllowed_usage',
       'OPP_percentagePersonalFouls_usage',
       'OPP_percentagePersonalFoulsDrawn_usage', 'OPP_percentagePoints_usage',
       'OPP_plusMinusPoints_traditional', 'OPP_GAME_DATE'],
      dtype='object', length=167)

In [ ]:
match_dataset

,GAME_ID,TEAM_ID,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,points_traditional,MINUTES_PLAYED,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,blocksAgainst_misc,offensiveRating_advanced,defensiveRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,threePointersPercentage_traditional,freeThrowsPercentage_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage,plusMinusPoints_traditional,OPP_TEAM_ID,GAME_DATE,OPP_fieldGoalsMade_traditional,OPP_fieldGoalsAttempted_traditional,OPP_threePointersMade_traditional,OPP_threePointersAttempted_traditional,OPP_freeThrowsMade_traditional,OPP_freeThrowsAttempted_traditional,OPP_reboundsOffensive_traditional,OPP_reboundsDefensive_traditional,OPP_reboundsTotal_traditional,OPP_assists_traditional,OPP_steals_traditional,OPP_blocks_traditional,OPP_turnovers_traditional,OPP_foulsPersonal_traditional,OPP_points_traditional,OPP_MINUTES_PLAYED,OPP_pointsOffTurnovers_misc,OPP_pointsSecondChance_misc,OPP_pointsFastBreak_misc,OPP_pointsPaint_misc,OPP_blocksAgainst_misc,OPP_offensiveRating_advanced,OPP_defensiveRating_advanced,OPP_netRating_advanced,OPP_assistPercentage_advanced,OPP_assistToTurnover_advanced,OPP_assistRatio_advanced,OPP_offensiveReboundPercentage_advanced,OPP_defensiveReboundPercentage_advanced,OPP_reboundPercentage_advanced,OPP_turnoverRatio_advanced,OPP_effectiveFieldGoalPercentage_advanced,OPP_trueShootingPercentage_advanced,OPP_usagePercentage_advanced,OPP_estimatedPace_advanced,OPP_pace_advanced,OPP_possessions_advanced,OPP_PIE_advanced,OPP_effectiveFieldGoalPercentage_fourfactors,OPP_freeThrowAttemptRate_fourfactors,OPP_teamTurnoverPercentage_fourfactors,OPP_oppEffectiveFieldGoalPercentage_fourfactors,OPP_oppFreeThrowAttemptRate_fourfactors,OPP_oppTeamTurnoverPercentage_fourfactors,OPP_oppOffensiveReboundPercentage_fourfactors,OPP_foulsDrawn_misc,OPP_percentageFieldGoalsAttempted2pt_scoring,OPP_percentageFieldGoalsAttempted3pt_scoring,OPP_percentagePoints2pt_scoring,OPP_percentagePointsMidrange2pt_scoring,OPP_percentagePoints3pt_scoring,OPP_percentagePointsFastBreak_scoring,OPP_percentagePointsFreeThrow_scoring,OPP_percentagePointsOffTurnovers_scoring,OPP_percentagePointsPaint_scoring,OPP_percentageAssisted2pt_scoring,OPP_percentageUnassisted2pt_scoring,OPP_percentageAssisted3pt_scoring,OPP_percentageUnassisted3pt_scoring,OPP_percentageAssistedFGM_scoring,OPP_percentageUnassistedFGM_scoring,OPP_threePointersPercentage_traditional,OPP_freeThrowsPercentage_traditional,OPP_percentageFieldGoalsMade_usage,OPP_percentageFieldGoalsAttempted_usage,OPP_percentageThreePointersMade_usage,OPP_percentageThreePointersAttempted_usage,OPP_percentageFreeThrowsMade_usage,OPP_percentageFreeThrowsAttempted_usage,OPP_percentageReboundsOffensive_usage,OPP_percentageReboundsDefensive_usage,OPP_percentageReboundsTotal_usage,OPP_percentageAssists_usage,OPP_percentageTurnovers_usage,OPP_percentageSteals_usage,OPP_percentageBlocks_usage,OPP_percentageBlocksAllowed_usage,OPP_percentagePersonalFouls_usage,OPP_percentagePersonalFoulsDrawn_usage,OPP_percentagePoints_usage,OPP_plusMinusPoints_traditional,OPP_GAME_DATE
0,0021000001,1610612738,32,69,8,16,16,25,8,34,42,25,6,4,18,19,88,240.000000,17,11,11,38,6,95.258826,86.767938,8.458819,0.179324,1.418765,16.786944,0.040284,0.143548,0.097696,13.576424,0.536647,0.565526,0.192004,91.500720,92.499906,61.978819,0.121102,0.524833,0.364811,0.217790,0.420576,0.341330,0.187027,0.244226,2.633472,0.773753,0.226247,0.600667,0.136254,0.202795,0.091713,0.196539,0.204380,0.464413,0.525706,0.421030,0.332569,0.000000,0.710834,0.235902,0.228976,0.522179,0.200810,0.200914,0.180178,0.199018,0.197938,0.195703,0.190636,0.204025,0.202745,0.190902,0.178942,0.176299,0.151945,0.196471,0.197720,0.199016,0.200868,4.585556,1610612748,2010-10-26,27,74,8,20,18,25,11,28,39,15,10,6,17,21,80,240.000000,22,5,11,24,4,86.585597,94.558222,-7.960403,0.158097,0.533849,13.530931,0.049858,0.138836,0.087374,10.813681,0.426550,0.495102,0.197047,91.499007,92.600174,59.272778,0.090339,0.418351,0.344338,0.188392,0.524045,0.364850,0.217761,0.223355,2.708681,0.712399,0.243379,0.496113,0.140206,0.278267,0.123794,0.225773,0.204365,0.355907,0.308280,0.538734,0.396736,0.152847,0.520927,0.434698,0.226023,0.579196,0.205427,0.199612,0.187020,0.186814,0.196853,0.187300,0.218039,0.202114,0.198359,0.228813,0.200531,0.173722,0.193393,0.147483,0.203271,0.192911,0.203349,-6.306528,2010-10-26
1,0021000001,1610612748,27,74,8,20,18,25,11,28,39,15,10,6,17,21,80,240.000000,22,5,11,24,4,86.585597,94.558222,-7.960403,0.158097,0.533849,13.530931,0.049858,0.138836,0.087374,10.813681,0.426550,0.495102,0.197047,91.499007,92.600174,59.272778,0.090339,0.418351,0.344338,0.188392,0.524045,0.364850,0.217761,0.223355,2.708681,0.712399,0.243379,0.496113,0.140206,0.278267,0.123794,0.225773,0.204365,0.355907,0.308280,0.538734,0.396736,0.152847,0.520927,0.434698,0.226023,0.579196,0.205427,0.199612,0.187020,0.186814,0.196853,0.187300,0.218039,0.202114,0.198359,0.228813,0.200531,0.173722,0.193393,0.147483,0.203271,0.192911,0.203349,-6.306528,1610612738,2010-10-26,32,69,8,16,16,25,8,34,42,25,6,4,18,19,88,240.000000,17,11,11,38,6,95.258826,86.767938,8.458819,0.179324,1.418765,16.786944,0.040284,0.143548,0.097696,13.576424,0.536647,0.565526,0.192004,91.500720,92.499906,61.978819,0.121102,0.524833,0.364811,0.217790,0.420576,0.341330,0.187027,0.244226,2.633472,0.773753,0.226247,0.600667,0.136254,0.202795,0.091713,0.196539,0.204380,0.464413,0.525706,0.421030,0.332569,0.000000,0.710834,0.235902,0.228976,0.522179,0.200810,0.200914,0.180178,0.199018,0.197938,0.195703,0.190636,0.204025,0.202745,0.190902,0.178942,0.176299,0.151945,0.196471,0.197720,0.199016,0.200868,4.585556,2010-10-26
2,0021000002,1610612756,36,74,9,19,11,16,7,23,30,15,3,4,19,19,92,240.000000,17,11,6,44,2,101.425007,116.062382,-14.648243,0.113202,0.765569,12.112500,0.037518,0.088750,0.065437,15.816979,0.525870,0.535510,0.195844,94.820024,91.299769,49.458125,0.072061,0.551087,0.219725,0.204248,0.516365,0.162388,0.155634,0.433928,2.182639,0.755892,0.244108,0.571466,0.086887,0.339328,0.039907,0.089060,0.246915,0.484873,0.259333,0.521430,0.333822,0.231595,0.436625,0.563375,0.372170,0.355924,0.197446,0.201281,0.204137,0.193324,0.178646,0.176324,0.205161,0.195726,0.197705,0.204080,0.182448,0.135582,0.266250,0.217986,0.189598,0.189302,0.196874,-7.175972,1610612757,2010-10-26,43,93,10,20,10,15,18,30,48,31,11,2,12,22,106,240.000000,21,21,13,42,4,116.705951,101.868819,14.847993,0.179627,1.619028,21.211271,0.071370,0.149384,0.105635,7.830722,0.500923,0.520792,0.191743,94.821719,91.100492,55.840069,0.059822,0.516180,0.167638,0.156635,0.550046,0.216926,0.204611,0.194777,2.417917,0.803757,0.196243,0.626211,0.218095,0.243037,0.126697,0.118044,0.228035,0.408116,0.552484,0.343836,0.495069,0.000000,0.696103,0.291188,0.261279,0.596760,0.198572,0.201131,0.215227,0.194294,0.199463,0.211358,0.207308,0.211804,0.199374,0.199567,0.145885,0.190182,0.204896,0.180178,0.195436,0.204637,0.199758,9.013194,2010-10-26
3,0021000002,1610612757,43,93,10,20,10,15,18,30,48,31,11,2,12,22,106,240.000000,21,21,13,42,4,116.705951,101.868819,14.847993,0.179627,1.619028,21.211271,0.071370,0.149384,0.105635,7.830722,0.500923,0.520792,0.191743,94.821719,91.100492,55.840069,0.059822,0.516180,0.167638,0.156635,0.550046,0.216926,0.204611,0.194777,2.417917,0.803757,0.196243,0.626211,0.218095,0.243037,0.126697,0.118044,0.228035,0.408116,0.552484,0.343836,0.495069,0.000000,0.696103,0.291188,0.261279,0.596760,0.198572,0.201131,0.215227,0.194294,0.199463,0.211358,0.207308,0.211804,0.199374,0.199567,0.145885,0.190182,0.204896,0.180178,0.195436,0.204637,0.199758,9.013194,1610612756,2010-10-26,36,74,9,19,11,16,7,23,30,15,3,4,19,19,92,240.000000,17,11,6,44,2,101.425007,116.062382,-14.648243,0.113202,0.765569,12.112500,0.037518,0.088750,0.065437,15.816979,0.525870,0.535510,0.195844,94.820024,91.299769,49.458125,0.072061,0.551087,0.219725,0.204248,0.516365,0.162388,0.155634,0.433928,2.182639,0.755892,0.244108,0.571466,0.086887,0.339328,0.039907,0.089060,0.246915,0.484873,0.259333,0.521430,0.333822,0.231595,0.436625,0.563375,0.372170,0.355924,0.197446,0.201281,0.204137,0.193324,0.178646,0.176324,0.205161,0.195726,0.197705,0.204080,0.182448,0.135582,0.266250,0.217986,0.189598,0.189302,0.196874,-7.175972,2010-10-26
4,0021000003,1610612745,38,91,8,20,26,28,16,37,53,25,6,7,20,25,110,239.983333,10,16,17,42,4,106.091812,106.928071,-0.849344,0.163359,1.393743,22.918397,0.061861,0.126248,0.095825,12.957421,0.402580,0.475858,0.198410,107.319701,104.201138,61.522328,0.102728,0.462191,0.307097,0.193372,0.466376,0.295486,0.112989,0.279195,3.016946,0.693632,0.244628,0.453675,0.138961,0.260127,0.120814,0.204803,0.083422,0.314576,0.444436,0.343327,0.383863,0.043388,0.668162,0.250444,0.220759,0.663562,0.195155,0.200732,0.158192,0.197478,0.179789,0.185280,0.236348,0.191520,0.197204,0.203254,0.194367,0.177269,0.216853,0.199693,0.193461,0.186709,0.195638,1.938676,1610612747,2010-10-26,40,96,9,21,23,28,14,30,44,21,11,4,12,24,112,240.000000,20,23,12,46,7,107.380507,106.350694,1.029812,0.131055,1.647756,16.353167,0.047063,0.113064,0.079990,8.603597,0.459826,0.499774,0.198762,107.319970,103.900553,62.920486,0.095947,0.469353,0.301715,0.112949,0.462946,0.308913,0.193897,0.342518,3.282014,0.763126,0.236874,0.525493,0.091175,0.238875,0.084063,0.155979,0.220723,0.434164,0.409895,0.420730,0.239410,0.061146,0.488379,0.431968,0.178848,0.382295,0.197003,0.201767,0.150194,0.192673,0.191074,0.183087,0.181331,0.198692,0.201060,0.205763,0.192513,0.190966,0.181838,0.153690,0.207920,0.200452,0.194698,1.128750,2010-10-26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68739,0052400211,1610612742,82,174,24,76,24,32,14,58,72,50,18,16,32,34,212,479.966667,28,30,30,88,8,103.971838,117.104361,-13.146712,0.159645,1.043291,21.438058,0.028121,0.109295,0.071448,14.196291,0.505059,0.518344,0.194360,102.820733,102.200355,55.776790,0.083048,0.540618,0.184078,0.155320,0.534614,0.150467,0.117294,0.351484,1.775957,0.589597,0.410403,0.375406,0.089519,0.288293,0.120119,0.077834,0.102521,0.286029,0.431148,0.256678,0.465397,0.199927,0.498200,0.243395,0.324056,0.404056,0.199455,0.198674,0.234511,0.197563,0.188766,0.193288,0.179929,0.199788,0.199410,0.199269,0.194797,0.201698,0.189836,0.148746,0.180069,0.178183,0.199691,-8.414820,1610612763,2025-04-18,94,200,26,62,26,30,32,68,100,60,16,8,20,34,240,480.000000,48,30,38,120,16,118.571125,105.071556,13.509528,0.154672,0.823437,19.079396,0.059757,0.149789,0.100197,4.889924,0.566430,0.582027,0.191697,102.820601,101.299056,62.138194,0.109814,0.532094,0.153846,0.116233,0.542366,0.187143,0.155200,0.164587,2.136944,0.650762,0.334099,0.569661,0.056488,0.328575,0.226652,0.078919,0.205619,0.513310,0.620063,0.349659,0.682240,0.087343,0.648875,0.320847,0.348328,0.327988,0.197052,0.199753,0.185188,0.203577,0.155673,0.161807,0.197832,0.203155,0.201390,0.197460,0.149565,0.187630,0.217161,0.174559,0.196685,0.173665,0.201920,11.408611,2025-04-18
68740,0052400211,1610612763,94,200,26,62,26,30,32,68,100,60,16,8,20,34,240,480.000000,48,30,38,120,16,118.571125,105.071556,13.509528,0.154672,0.823437,19.079396,0.059757,0.149789,0.100197,4.889924,0.566430,0.582027,0.191697,102.820601,101.299056,62.138194,0.109814,0.532094,0.153846,0.116233,0.542366,0.187143,0.155200,0.164587,2.136944,0.650762,0.334099,0.569661,0.056488,0.328575,0.226652,0.078919,0.205619,0.513310,0.620063,0.349659,0.682240,0.087343,0.648875,0.320847,0.348328,0.327988,0.197052,0.199753,0.185188,0.203577,0.155673,0.161807,0.197832,0.203155,0.201390,0.197460,0.149565,0.187630,0.217161,0.174559,0.196685,0.173665,0.201920,11.408611,1610612742,2025-04-18,82,174,24,76,24,32,14,58,72,50,18,16,32,34,212,479.966667,28,30,30,88,8,103.971838,117.104361,-13.146712,0.159645,1.043291,21.438058,0.028121,0.109295,0.071448,14.196291,0.505059,0.518344,0.194360,102.820733,102.200355,55.776790,0.083048,0.540618,0.184078,0.155320,0.534614,0.150467,0.117294,0.351484,1.775957,0.589597,0.410403,0.375406,0.089519,0.288293,0.120119,0.077834,0.102521,0.286029,0.431148,0.256678,0.465397,0.199927,0.498200,0.243395,0.324056,0.404056,0.199455,0.198674,0.234511,0.197563,0.188766,0.193288,0.179929,0.199788,0.199410,0.199269,0.194797,0.201698,0.189836,0.148746,0.180069,0.178183,0.199691,-8.414820,2025-04-18
68741,0052400211,1610612763,94,200,26,62,26,30,32,68,100,60,16,8,20,34,240,480.000000,48,30,38,120,16,118.571125,105.071556,13.509528,0.154672,0.823437,19.079396,0.059757,0.149789,0.100197,4.889924,0.566430,0.582027,0.191697,102.820601,101.299056,62.138194,0.109814,0.532094,0.153846,0.116233,0.542366,0.187143,0.155200,0.164587,2.136944,0.650762,0.334099,0.569661,0.056488,0.328575,0.226652,0.078919,0.205619,0.513310,0.620063,0.349659,0.682240,0.087343,0.648875,0.320847,0.348328,0.327988,0.197052,0.199753,0.185188,0.203577,0.155673,0.161807,0.197832,0.203155,0.201390,0.197460,0.149565,0.187630,0.217161,0.174559,0.196685,0.173665,0.201920,11.408611,1610612742,2025-04-18,82,174,24,76,24,32,14,58,72,50,18,16,32,34,212,479.966667,28,30,30,88,8,103.971838,117.104361,-13.146712,0.159645,1.043291,21.438058,0.028121,0.109295,0.071448,14.196291,0.505059,0.518344,0.194360,102.820733,102.200355,55.776790,0.083048,0.540618,0.184078,0.155320,0.534614,0.150467,0.117294,0.351484,1.775957,0.589597,0.410403,0.375406,0.089519,0.288293,0.120119,0.077834,0.102521,0.286029,0.431148,0.256678,0.465397,0.199927,0.498200,0.243395,0.324056,0.404056,0.199455,0.198674,0.234511,0.197563,0.188766,0.193288,0.179929,0.199788,0.199410,0.199269,0.194797,0.201698,0.189836,0.148746,0.180069,0.178183,0.199691,-8.414820,2025-04-18
68742,0052400211,1610612763,94,200,26,62,26,30,32,68,100,60,16,8,20,34,240,480.000000,48,30,38,120,16,118.571125,105.071556,13.509528,0.154672,0.823437,19.079396,0.059757,0.149789,0.100197,4.889924,0.566430,0.582027,0.191697,102.820601,101.299056,62.138194,0.109814,0.532094,0.153846,0.116233,0.542366,0.187143,0.155200,0.164587,2.136944,0.650762,0.334099,0.569661,0.056488,0.328575,0.226652,0.078919,0.205619,0.513310,0.620063,0.349659,0.682240,0.087343,0.648875,0.320847,0.348328,0.327988,0.197052,0.199753,0.185188,0.203577,0.155673,0.161807,0.197832,0.203155,0.201390,0.197460,0.149565,0.187630,0.217161,0.174559,0.196685,0.173665,0.201920,11.408611,1610612742,2025-04-18,82,174,24,76,24,32,14,58,72,50,18,16,32,34,212,479.966667,28,30,30,88,8,103.971838,117.104361,-13.146712,0.159645,1.043291,21.438058,0.028121,0.109295,0.071448,14.196291,0.505059,0.518344,0.194360,102.820733,102.200355,55.776790,0.083048,0.540618,0.184078,0.155320,0.534614,0.150467,0.117294,0.351484,1.775957,0.589597,0.410403,0.375406,0.089519,0.288293,0.120119,0.077834,0.102521,0.286029,0.431148,0.256678,0.465397,0.199927,0.498200,0.243395,0.324056,0.404056,0.199455,0.198674,0.234511,0.197563,0.188766,0.193288,0.179929,0.199788,0.199410,0.199269,0.194797,0.201698,0.189836,0.148746,0.180069,0.178183,0.199691,-8.414820,2025-04-18
68743,0052400211,1610612763,94,200,26,62,26,30,32,68,100,60,16,8,20,34,240,480.000000,48,30,38,120,16,118.571125,105.071556,13.509528,0.154672,0.823437,19.079396,0.059757,0.149789,0.100197,4.889924,0.566430,0.582027,0.191697,102.820601,101.299056,62.138194,0.109814,0.532094,0.153846,0.116233,0.542366,0.187143,0.155200,0.164587,2.136944,0.650762,0.334099,0.569661,0.056488,0.328575,0.226652,0.078919,0.205619,0.513310,0.620063,0.349659,0.682240,0.087343,0.648875,0.320847,0.348328,0.327988,0.197052,0.199753,0.185188,0.203577,0.155673,0.161807,0.197832,0.203155,0.201390,0.197460,0.149565,0.187630,0.217161,0.174559,0.196685,0.173665,0.201920,11.408611,1610612742,2025-04-18,82,174,24,76,24,32,14,58,72,50,18,16,32,34,212,479.966667,28,30,30,88,8,103.971838,117.104361,-13.146712,0.159645,1.043291,21.438058,0.028121,0.109295,0.071448,14.196291,0.505059,0.518344,0.194360,102.820733,102.200355,55.776790,0.083048,0.540618,0.184078,0.155320,0.534614,0.150467,0.117294,0.351484,1.775957,0.589597,0.410403,0.375406,0.089519,0.288293,0.120119,0.077834,0.102521,0.286029,0.431148,0.256678,0.465397,0.199927,0.498200,0.243395,0.324056,0.404056,0.199455,0.198674,0.234511,0.197563,0.188766,0.193288,0.179929,0.199788,0.199410,0.199269,0.194797,0.201698,0.189836,0.148746,0.180069,0.178183,0.199691,-8.414820,2025-04-18

# 🏠 Ajout IS_HOME et IS_WIN

In [ ]:
# Assurer le format datetime pour GAME_DATE
df_games['GAME_DATE'] = pd.to_datetime(df_games['GAME_DATE'])

# Merge avec les infos de match (MATCHUP, SEASON)
match_dataset = match_dataset.merge(
    df_games[['GAME_ID', 'TEAM_ID', 'MATCHUP', 'SEASON']],
    on=['GAME_ID', 'TEAM_ID'],
    how='left'
)

print("match_dataset after merge")
display(match_dataset)


#display lines with nan values on matchup
print("Lines with NaN in MATCHUP:")
display(match_dataset[match_dataset['MATCHUP'].isna()])

# Définir si l'équipe joue à domicile
match_dataset['IS_HOME'] = match_dataset['MATCHUP'].str.contains('vs').astype(int)

# Calcul du résultat (win) et écart de points
match_dataset['IS_WIN'] = (match_dataset['points_traditional'] > match_dataset['OPP_points_traditional']).astype(int)
match_dataset['POINT_DIFF'] = match_dataset['points_traditional'] - match_dataset['OPP_points_traditional']

# Conversion GAME_DATE et tri
match_dataset['GAME_DATE'] = pd.to_datetime(match_dataset['GAME_DATE'])
match_dataset = match_dataset.sort_values(['GAME_DATE', 'GAME_ID']).reset_index(drop=True)

match_dataset after merge

,GAME_ID,TEAM_ID,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,points_traditional,MINUTES_PLAYED,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,blocksAgainst_misc,offensiveRating_advanced,defensiveRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,threePointersPercentage_traditional,freeThrowsPercentage_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage,plusMinusPoints_traditional,OPP_TEAM_ID,GAME_DATE,OPP_fieldGoalsMade_traditional,OPP_fieldGoalsAttempted_traditional,OPP_threePointersMade_traditional,OPP_threePointersAttempted_traditional,OPP_freeThrowsMade_traditional,OPP_freeThrowsAttempted_traditional,OPP_reboundsOffensive_traditional,OPP_reboundsDefensive_traditional,OPP_reboundsTotal_traditional,OPP_assists_traditional,OPP_steals_traditional,OPP_blocks_traditional,OPP_turnovers_traditional,OPP_foulsPersonal_traditional,OPP_points_traditional,OPP_MINUTES_PLAYED,OPP_pointsOffTurnovers_misc,OPP_pointsSecondChance_misc,OPP_pointsFastBreak_misc,OPP_pointsPaint_misc,OPP_blocksAgainst_misc,OPP_offensiveRating_advanced,OPP_defensiveRating_advanced,OPP_netRating_advanced,OPP_assistPercentage_advanced,OPP_assistToTurnover_advanced,OPP_assistRatio_advanced,OPP_offensiveReboundPercentage_advanced,OPP_defensiveReboundPercentage_advanced,OPP_reboundPercentage_advanced,OPP_turnoverRatio_advanced,OPP_effectiveFieldGoalPercentage_advanced,OPP_trueShootingPercentage_advanced,OPP_usagePercentage_advanced,OPP_estimatedPace_advanced,OPP_pace_advanced,OPP_possessions_advanced,OPP_PIE_advanced,OPP_effectiveFieldGoalPercentage_fourfactors,OPP_freeThrowAttemptRate_fourfactors,OPP_teamTurnoverPercentage_fourfactors,OPP_oppEffectiveFieldGoalPercentage_fourfactors,OPP_oppFreeThrowAttemptRate_fourfactors,OPP_oppTeamTurnoverPercentage_fourfactors,OPP_oppOffensiveReboundPercentage_fourfactors,OPP_foulsDrawn_misc,OPP_percentageFieldGoalsAttempted2pt_scoring,OPP_percentageFieldGoalsAttempted3pt_scoring,OPP_percentagePoints2pt_scoring,OPP_percentagePointsMidrange2pt_scoring,OPP_percentagePoints3pt_scoring,OPP_percentagePointsFastBreak_scoring,OPP_percentagePointsFreeThrow_scoring,OPP_percentagePointsOffTurnovers_scoring,OPP_percentagePointsPaint_scoring,OPP_percentageAssisted2pt_scoring,OPP_percentageUnassisted2pt_scoring,OPP_percentageAssisted3pt_scoring,OPP_percentageUnassisted3pt_scoring,OPP_percentageAssistedFGM_scoring,OPP_percentageUnassistedFGM_scoring,OPP_threePointersPercentage_traditional,OPP_freeThrowsPercentage_traditional,OPP_percentageFieldGoalsMade_usage,OPP_percentageFieldGoalsAttempted_usage,OPP_percentageThreePointersMade_usage,OPP_percentageThreePointersAttempted_usage,OPP_percentageFreeThrowsMade_usage,OPP_percentageFreeThrowsAttempted_usage,OPP_percentageReboundsOffensive_usage,OPP_percentageReboundsDefensive_usage,OPP_percentageReboundsTotal_usage,OPP_percentageAssists_usage,OPP_percentageTurnovers_usage,OPP_percentageSteals_usage,OPP_percentageBlocks_usage,OPP_percentageBlocksAllowed_usage,OPP_percentagePersonalFouls_usage,OPP_percentagePersonalFoulsDrawn_usage,OPP_percentagePoints_usage,OPP_plusMinusPoints_traditional,OPP_GAME_DATE,MATCHUP,SEASON
0,0021000001,1610612738,32,69,8,16,16,25,8,34,42,25,6,4,18,19,88,240.000000,17,11,11,38,6,95.258826,86.767938,8.458819,0.179324,1.418765,16.786944,0.040284,0.143548,0.097696,13.576424,0.536647,0.565526,0.192004,91.500720,92.499906,61.978819,0.121102,0.524833,0.364811,0.217790,0.420576,0.341330,0.187027,0.244226,2.633472,0.773753,0.226247,0.600667,0.136254,0.202795,0.091713,0.196539,0.204380,0.464413,0.525706,0.421030,0.332569,0.000000,0.710834,0.235902,0.228976,0.522179,0.200810,0.200914,0.180178,0.199018,0.197938,0.195703,0.190636,0.204025,0.202745,0.190902,0.178942,0.176299,0.151945,0.196471,0.197720,0.199016,0.200868,4.585556,1610612748,2010-10-26,27,74,8,20,18,25,11,28,39,15,10,6,17,21,80,240.000000,22,5,11,24,4,86.585597,94.558222,-7.960403,0.158097,0.533849,13.530931,0.049858,0.138836,0.087374,10.813681,0.426550,0.495102,0.197047,91.499007,92.600174,59.272778,0.090339,0.418351,0.344338,0.188392,0.524045,0.364850,0.217761,0.223355,2.708681,0.712399,0.243379,0.496113,0.140206,0.278267,0.123794,0.225773,0.204365,0.355907,0.308280,0.538734,0.396736,0.152847,0.520927,0.434698,0.226023,0.579196,0.205427,0.199612,0.187020,0.186814,0.196853,0.187300,0.218039,0.202114,0.198359,0.228813,0.200531,0.173722,0.193393,0.147483,0.203271,0.192911,0.203349,-6.306528,2010-10-26,BOS vs. MIA,2010-11
1,0021000001,1610612748,27,74,8,20,18,25,11,28,39,15,10,6,17,21,80,240.000000,22,5,11,24,4,86.585597,94.558222,-7.960403,0.158097,0.533849,13.530931,0.049858,0.138836,0.087374,10.813681,0.426550,0.495102,0.197047,91.499007,92.600174,59.272778,0.090339,0.418351,0.344338,0.188392,0.524045,0.364850,0.217761,0.223355,2.708681,0.712399,0.243379,0.496113,0.140206,0.278267,0.123794,0.225773,0.204365,0.355907,0.308280,0.538734,0.396736,0.152847,0.520927,0.434698,0.226023,0.579196,0.205427,0.199612,0.187020,0.186814,0.196853,0.187300,0.218039,0.202114,0.198359,0.228813,0.200531,0.173722,0.193393,0.147483,0.203271,0.192911,0.203349,-6.306528,1610612738,2010-10-26,32,69,8,16,16,25,8,34,42,25,6,4,18,19,88,240.000000,17,11,11,38,6,95.258826,86.767938,8.458819,0.179324,1.418765,16.786944,0.040284,0.143548,0.097696,13.576424,0.536647,0.565526,0.192004,91.500720,92.499906,61.978819,0.121102,0.524833,0.364811,0.217790,0.420576,0.341330,0.187027,0.244226,2.633472,0.773753,0.226247,0.600667,0.136254,0.202795,0.091713,0.196539,0.204380,0.464413,0.525706,0.421030,0.332569,0.000000,0.710834,0.235902,0.228976,0.522179,0.200810,0.200914,0.180178,0.199018,0.197938,0.195703,0.190636,0.204025,0.202745,0.190902,0.178942,0.176299,0.151945,0.196471,0.197720,0.199016,0.200868,4.585556,2010-10-26,MIA @ BOS,2010-11
2,0021000002,1610612756,36,74,9,19,11,16,7,23,30,15,3,4,19,19,92,240.000000,17,11,6,44,2,101.425007,116.062382,-14.648243,0.113202,0.765569,12.112500,0.037518,0.088750,0.065437,15.816979,0.525870,0.535510,0.195844,94.820024,91.299769,49.458125,0.072061,0.551087,0.219725,0.204248,0.516365,0.162388,0.155634,0.433928,2.182639,0.755892,0.244108,0.571466,0.086887,0.339328,0.039907,0.089060,0.246915,0.484873,0.259333,0.521430,0.333822,0.231595,0.436625,0.563375,0.372170,0.355924,0.197446,0.201281,0.204137,0.193324,0.178646,0.176324,0.205161,0.195726,0.197705,0.204080,0.182448,0.135582,0.266250,0.217986,0.189598,0.189302,0.196874,-7.175972,1610612757,2010-10-26,43,93,10,20,10,15,18,30,48,31,11,2,12,22,106,240.000000,21,21,13,42,4,116.705951,101.868819,14.847993,0.179627,1.619028,21.211271,0.071370,0.149384,0.105635,7.830722,0.500923,0.520792,0.191743,94.821719,91.100492,55.840069,0.059822,0.516180,0.167638,0.156635,0.550046,0.216926,0.204611,0.194777,2.417917,0.803757,0.196243,0.626211,0.218095,0.243037,0.126697,0.118044,0.228035,0.408116,0.552484,0.343836,0.495069,0.000000,0.696103,0.291188,0.261279,0.596760,0.198572,0.201131,0.215227,0.194294,0.199463,0.211358,0.207308,0.211804,0.199374,0.199567,0.145885,0.190182,0.204896,0.180178,0.195436,0.204637,0.199758,9.013194,2010-10-26,PHX @ POR,2010-11
3,0021000002,1610612757,43,93,10,20,10,15,18,30,48,31,11,2,12,22,106,240.000000,21,21,13,42,4,116.705951,101.868819,14.847993,0.179627,1.619028,21.211271,0.071370,0.149384,0.105635,7.830722,0.500923,0.520792,0.191743,94.821719,91.100492,55.840069,0.059822,0.516180,0.167638,0.156635,0.550046,0.216926,0.204611,0.194777,2.417917,0.803757,0.196243,0.626211,0.218095,0.243037,0.126697,0.118044,0.228035,0.408116,0.552484,0.343836,0.495069,0.000000,0.696103,0.291188,0.261279,0.596760,0.198572,0.201131,0.215227,0.194294,0.199463,0.211358,0.207308,0.211804,0.199374,0.199567,0.145885,0.190182,0.204896,0.180178,0.195436,0.204637,0.199758,9.013194,1610612756,2010-10-26,36,74,9,19,11,16,7,23,30,15,3,4,19,19,92,240.000000,17,11,6,44,2,101.425007,116.062382,-14.648243,0.113202,0.765569,12.112500,0.037518,0.088750,0.065437,15.816979,0.525870,0.535510,0.195844,94.820024,91.299769,49.458125,0.072061,0.551087,0.219725,0.204248,0.516365,0.162388,0.155634,0.433928,2.182639,0.755892,0.244108,0.571466,0.086887,0.339328,0.039907,0.089060,0.246915,0.484873,0.259333,0.521430,0.333822,0.231595,0.436625,0.563375,0.372170,0.355924,0.197446,0.201281,0.204137,0.193324,0.178646,0.176324,0.205161,0.195726,0.197705,0.204080,0.182448,0.135582,0.266250,0.217986,0.189598,0.189302,0.196874,-7.175972,2010-10-26,POR vs. PHX,2010-11
4,0021000003,1610612745,38,91,8,20,26,28,16,37,53,25,6,7,20,25,110,239.983333,10,16,17,42,4,106.091812,106.928071,-0.849344,0.163359,1.393743,22.918397,0.061861,0.126248,0.095825,12.957421,0.402580,0.475858,0.198410,107.319701,104.201138,61.522328,0.102728,0.462191,0.307097,0.193372,0.466376,0.295486,0.112989,0.279195,3.016946,0.693632,0.244628,0.453675,0.138961,0.260127,0.120814,0.204803,0.083422,0.314576,0.444436,0.343327,0.383863,0.043388,0.668162,0.250444,0.220759,0.663562,0.195155,0.200732,0.158192,0.197478,0.179789,0.185280,0.236348,0.191520,0.197204,0.203254,0.194367,0.177269,0.216853,0.199693,0.193461,0.186709,0.195638,1.938676,1610612747,2010-10-26,40,96,9,21,23,28,14,30,44,21,11,4,12,24,112,240.000000,20,23,12,46,7,107.380507,106.350694,1.029812,0.131055,1.647756,16.353167,0.047063,0.113064,0.079990,8.603597,0.459826,0.499774,0.198762,107.319970,103.900553,62.920486,0.095947,0.469353,0.301715,0.112949,0.462946,0.308913,0.193897,0.342518,3.282014,0.763126,0.236874,0.525493,0.091175,0.238875,0.084063,0.155979,0.220723,0.434164,0.409895,0.420730,0.239410,0.061146,0.488379,0.431968,0.178848,0.382295,0.197003,0.201767,0.150194,0.192673,0.191074,0.183087,0.181331,0.198692,0.201060,0.205763,0.192513,0.190966,0.181838,0.153690,0.207920,0.200452,0.194698,1.128750,2010-10-26,HOU @ LAL,2010-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109323,0052400211,1610612763,94,200,26,62,26,30,32,68,100,60,16,8,20,34,240,480.000000,48,30,38,120,16,118.571125,105.071556,13.509528,0.154672,0.823437,19.079396,0.059757,0.149789,0.100197,4.889924,0.566430,0.582027,0.191697,102.820601,101.299056,62.138194,0.109814,0.532094,0.153846,0.116233,0.542366,0.187143,0.155200,0.164587,2.136944,0.650762,0.334099,0.569661,0.056488,0.328575,0.226652,0.078919,0.205619,0.513310,0.620063,0.349659,0.682240,0.087343,0.648875,0.320847,0.348328,0.327988,0.197052,0.199753,0.185188,0.203577,0.155673,0.161807,0.197832,0.203155,0.201390,0.197460,0.149565,0.187630,0.217161,0.174559,0.196685,0.173665,0.201920,11.408611,1610612742,2025-04-18,82,174,24,76,24,32,14,58,72,50,18,16,32,34,212,479.966667,28,30,30,88,8,103.971838,117.104361,-13.146712,0.159645,1.043291,21.438058,0.028121,0.109295,0.071448,14.196291,0.505059,0.518344,0.194360,102.820733,102.200355,55.776790,0.083048,0.540618,0.184078,0.155320,0.534614,0.150467,0.117294,0.351484,1.775957,0.589597,0.410403,0.375406,0.089519,0.288293,0.120119,0.077834,0.102521,0.286029,0.431148,0.256678,0.465397,0.199927,0.498200,0.243395,0.324056,0.404056,0.199455,0.198674,0.234511,0.197563,0.188766,0.193288,0.179929,0.199788,0.199410,0.199269,0.194797,0.201698,0.189836,0.148746,0.180069,0.178183,0.199691,-8.414820,2025-04-18,MEM vs. DAL,2024-25
109324,0052400211,1610612763,94,200,26,62,26,30,32,68,100,60,16,8,20,34,240,480.000000,48,30,38,120,16,118.571125,105.071556,13.509528,0.154672,0.823437,19.079396,0.059757,0.149789,0.100197,4.889924,0.566430,0.582027,0.191697,102.820601,101.299056,62.138194,0.109814,0.532094,0.153846,0.116233,0.542366,0.187143,0.155200,0.164587,2.136944,0.650762,0.334099,0.569661,0.056488,0.328575,0.226652,0.078919,0.205619,0.513310,0.620063,0.349659,0.682240,0.087343,0.648875,0.320847,0.348328,0.327988,0.197052,0.199753,0.185188,0.203577,0.155673,0.161807,0.197832,0.203155,0.201390,0.197460,0.149565,0.187630,0.217161,0.174559,0.196685,0.173665,0.201920,11.408611,1610612742,2025-04-18,82,174,24,76,24,32,14,58,72,50,18,16,32,34,212,479.966667,28,30,30,88,8,103.971838,117.104361,-13.146712,0.159645,1.043291,21.438058,0.028121,0.109295,0.071448,14.196291,0.505059,0.518344,0.194360,102.820733,102.200355,55.776790,0.083048,0.540618,0.184078,0.155320,0.534614,0.150467,0.117294,0.351484,1.775957,0.589597,0.410403,0.375406,0.089519,0.288293,0.120119,0.077834,0.102521,0.286029,0.431148,0.256678,0.465397,0.199927,0.498200,0.243395,0.324056,0.404056,0.199455,0.198674,0.234511,0.197563,0.188766,0.193288,0.179929,0.199788,0.199410,0.199269,0.194797,0.201698,0.189836,0.148746,0.180069,0.178183,0.199691,-8.414820,2025-04-18,MEM vs. DAL,2024-25
109325,0052400211,1610612763,94,200,26,62,26,30,32,68,100,60,16,8,20,34,240,480.000000,48,30,38,120,16,118.571125,105.071556,13.509528,0.154672,0.823437,19.079396,0.059757,0.149789,0.100197,4.889924,0.566430,0.582027,0.191697,102.820601,101.299056,62.138194,0.109814,0.532094,0.153846,0.116233,0.542366,0.187143,0.155200,0.164587,2.136944,0.650762,0.334099,0.569661,0.056488,0.328575,0.226652,0.078919,0.205619,0.513310,0.620063,0.349659,0.682240,0.087343,0.648875,0.320847,0.348328,0.327988,0.197052,0.199753,0.185188,0.203577,0.155673,0.161807,0.197832,0.203155,0.201390,0.197460,0.149565,0.187630,0.217161,0.174559,0.196685,0.173665,0.201920,11.408611,1610612742,2025-04-18,82,174,24,76,24,32,14,58,72,50,18,16,32,34,212,479.966667,28,30,30,88,8,103.971838,117.104361,-13.146712,0.159645,1.043291,21.438058,0.028121,0.109295,0.071448,14.196291,0.505059,0.518344,0.194360,102.820733,102.200355,55.776790,0.083048,0.540618,0.184078,0.155320,0.534614,0.150467,0.117294,0.351484,1.775957,0.589597,0.410403,0.375406,0.089519,0.288293,0.120119,0.077834,0.102521,0.286029,0.431148,0.256678,0.465397,0.199927,0.498200,0.243395,0.324056,0.404056,0.199455,0.198674,0.234511,0.197563,0.188766,0.193288,0.179929,0.199788,0.199410,0.199269,0.194797,0.201698,0.189836,0.148746,0.180069,0.178183,0.199691,-8.414820,2025-04-18,MEM vs. DAL,2024-25
109326,0052400211,1610612763,94,200,26,62,26,30,32,68,100,60,16,8,20,34,240,480.000000,48,30,38,120,16,118.571125,105.071556,13.509528,0.154672,0.823437,19.079396,0.059757,0.149789,0.100197,4.889924,0.566430,0.582027,0.191697,102.820601,101.299056,62.138194,0.109814,0.532094,0.153846,0.116233,0.542366,0.187143,0.155200,0.164587,2.136944,0.650762,0.334099,0.569661,0.056488,0.328575,0.226652,0.078919,0.205619,0.513310,0.620063,0.349659,0.682240,0.087343,0.648875,0.320847,0.348328,0.327988,0.197052,0.199753,0.185188,0.203577,0.155673,0.161807,0.197832,0.203155,0.201390,0.197460,0.149565,0.187630,0.217161,0.174559,0.196685,0.173665,0.201920,11.408611,1610612742,2025-04-18,82,174,24,76,24,32,14,58,72,50,18,16,32,34,212,479.966667,28,30,30,88,8,103.971838,117.104361,-13.146712,0.159645,1.043291,21.438058,0.028121,0.109295,0.071448,14.196291,0.505059,0.518344,0.194360,102.820733,102.200355,55.776790,0.083048,0.540618,0.184078,0.155320,0.534614,0.150467,0.117294,0.351484,1.775957,0.589597,0.410403,0.375406,0.089519,0.288293,0.120119,0.077834,0.102521,0.286029,0.431148,0.256678,0.465397,0.199927,0.498200,0.243395,0.324056,0.404056,0.199455,0.198674,0.234511,0.197563,0.188766,0.193288,0.179929,0.199788,0.199410,0.199269,0.194797,0.201698,0.189836,0.148746,0.180069,0.178183,0.199691,-8.414820,2025-04-18,MEM vs. DAL,2024-25
109327,0052400211,1610612763,94,200,26,62,26,30,32,68,100,60,16,8,20,34,240,480.000000,48,30,38,120,16,118.571125,105.071556,13.509528,0.154672,0.823437,19.079396,0.059757,0.149789,0.100197,4.889924,0.566430,0.582027,0.191697,102.820601,101.299056,62.138194,0.109814,0.532094,0.153846,0.116233,0.542366,0.187143,0.155200,0.164587,2.136944,0.650762,0.334099,0.569661,0.056488,0.328575,0.226652,0.078919,0.205619,0.513310,0.620063,0.349659,0.682240,0.087343,0.648875,0.320847,0.348328,0.327988,0.197052,0.199753,0.185188,0.203577,0.155673,0.161807,0.197832,0.203155,0.201390,0.197460,0.149565,0.187630,0.217161,0.174559,0.196685,0.173665,0.201920,11.408611,1610612742,2025-04-18,82,174,24,76,24,32,14,58,72,50,18,16,32,34,212,479.966667,28,30,30,88,8,103.971838,117.104361,-13.146712,0.159645,1.043291,21.438058,0.028121,0.109295,0.071448,14.196291,0.505059,0.518344,0.194360,102.820733,102.200355,55.776790,0.083048,0.540618,0.184078,0.155320,0.534614,0.150467,0.117294,0.351484,1.775957,0.589597,0.410403,0.375406,0.089519,0.288293,0.120119,0.077834,0.102521,0.286029,0.431148,0.256678,0.465397,0.199927,0.498200,0.243395,0.324056,0.404056,0.199455,0.198674,0.234511,0.197563,0.188766,0.193288,0.179929,0.199788,0.199410,0.199269,0.194797,0.201698,0.189836,0.148746,0.180069,0.178183,0.199691,-8.414820,2025-04-18,MEM vs. DAL,2024-25

Lines with NaN in MATCHUP:

Empty DataFrame
Columns: [GAME_ID, TEAM_ID, fieldGoalsMade_traditional, fieldGoalsAttempted_traditional, threePointersMade_traditional, threePointersAttempted_traditional, freeThrowsMade_traditional, freeThrowsAttempted_traditional, reboundsOffensive_traditional, reboundsDefensive_traditional, reboundsTotal_traditional, assists_traditional, steals_traditional, blocks_traditional, turnovers_traditional, foulsPersonal_traditional, points_traditional, MINUTES_PLAYED, pointsOffTurnovers_misc, pointsSecondChance_misc, pointsFastBreak_misc, pointsPaint_misc, blocksAgainst_misc, offensiveRating_advanced, defensiveRating_advanced, netRating_advanced, assistPercentage_advanced, assistToTurnover_advanced, assistRatio_advanced, offensiveReboundPercentage_advanced, defensiveReboundPercentage_advanced, reboundPercentage_advanced, turnoverRatio_advanced, effectiveFieldGoalPercentage_advanced, trueShootingPercentage_advanced, usagePercentage_advanced, estimatedPace_advanced, pace_advanced, possessions_advanced, PIE_advanced, effectiveFieldGoalPercentage_fourfactors, freeThrowAttemptRate_fourfactors, teamTurnoverPercentage_fourfactors, oppEffectiveFieldGoalPercentage_fourfactors, oppFreeThrowAttemptRate_fourfactors, oppTeamTurnoverPercentage_fourfactors, oppOffensiveReboundPercentage_fourfactors, foulsDrawn_misc, percentageFieldGoalsAttempted2pt_scoring, percentageFieldGoalsAttempted3pt_scoring, percentagePoints2pt_scoring, percentagePointsMidrange2pt_scoring, percentagePoints3pt_scoring, percentagePointsFastBreak_scoring, percentagePointsFreeThrow_scoring, percentagePointsOffTurnovers_scoring, percentagePointsPaint_scoring, percentageAssisted2pt_scoring, percentageUnassisted2pt_scoring, percentageAssisted3pt_scoring, percentageUnassisted3pt_scoring, percentageAssistedFGM_scoring, percentageUnassistedFGM_scoring, threePointersPercentage_traditional, freeThrowsPercentage_traditional, percentageFieldGoalsMade_usage, percentageFieldGoalsAttempted_usage, percentageThreePointersMade_usage, percentageThreePointersAttempted_usage, percentageFreeThrowsMade_usage, percentageFreeThrowsAttempted_usage, percentageReboundsOffensive_usage, percentageReboundsDefensive_usage, percentageReboundsTotal_usage, percentageAssists_usage, percentageTurnovers_usage, percentageSteals_usage, percentageBlocks_usage, percentageBlocksAllowed_usage, percentagePersonalFouls_usage, percentagePersonalFoulsDrawn_usage, percentagePoints_usage, plusMinusPoints_traditional, OPP_TEAM_ID, GAME_DATE, OPP_fieldGoalsMade_traditional, OPP_fieldGoalsAttempted_traditional, OPP_threePointersMade_traditional, OPP_threePointersAttempted_traditional, OPP_freeThrowsMade_traditional, OPP_freeThrowsAttempted_traditional, OPP_reboundsOffensive_traditional, OPP_reboundsDefensive_traditional, OPP_reboundsTotal_traditional, OPP_assists_traditional, OPP_steals_traditional, OPP_blocks_traditional, OPP_turnovers_traditional, OPP_foulsPersonal_traditional, OPP_points_traditional, ...]
Index: []

In [ ]:
match_dataset

,GAME_ID,TEAM_ID,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,points_traditional,MINUTES_PLAYED,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,blocksAgainst_misc,offensiveRating_advanced,defensiveRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,threePointersPercentage_traditional,freeThrowsPercentage_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage,plusMinusPoints_traditional,OPP_TEAM_ID,GAME_DATE,OPP_fieldGoalsMade_traditional,OPP_fieldGoalsAttempted_traditional,OPP_threePointersMade_traditional,OPP_threePointersAttempted_traditional,OPP_freeThrowsMade_traditional,OPP_freeThrowsAttempted_traditional,OPP_reboundsOffensive_traditional,OPP_reboundsDefensive_traditional,OPP_reboundsTotal_traditional,OPP_assists_traditional,OPP_steals_traditional,OPP_blocks_traditional,OPP_turnovers_traditional,OPP_foulsPersonal_traditional,OPP_points_traditional,OPP_MINUTES_PLAYED,OPP_pointsOffTurnovers_misc,OPP_pointsSecondChance_misc,OPP_pointsFastBreak_misc,OPP_pointsPaint_misc,OPP_blocksAgainst_misc,OPP_offensiveRating_advanced,OPP_defensiveRating_advanced,OPP_netRating_advanced,OPP_assistPercentage_advanced,OPP_assistToTurnover_advanced,OPP_assistRatio_advanced,OPP_offensiveReboundPercentage_advanced,OPP_defensiveReboundPercentage_advanced,OPP_reboundPercentage_advanced,OPP_turnoverRatio_advanced,OPP_effectiveFieldGoalPercentage_advanced,OPP_trueShootingPercentage_advanced,OPP_usagePercentage_advanced,OPP_estimatedPace_advanced,OPP_pace_advanced,OPP_possessions_advanced,OPP_PIE_advanced,OPP_effectiveFieldGoalPercentage_fourfactors,OPP_freeThrowAttemptRate_fourfactors,OPP_teamTurnoverPercentage_fourfactors,OPP_oppEffectiveFieldGoalPercentage_fourfactors,OPP_oppFreeThrowAttemptRate_fourfactors,OPP_oppTeamTurnoverPercentage_fourfactors,OPP_oppOffensiveReboundPercentage_fourfactors,OPP_foulsDrawn_misc,OPP_percentageFieldGoalsAttempted2pt_scoring,OPP_percentageFieldGoalsAttempted3pt_scoring,OPP_percentagePoints2pt_scoring,OPP_percentagePointsMidrange2pt_scoring,OPP_percentagePoints3pt_scoring,OPP_percentagePointsFastBreak_scoring,OPP_percentagePointsFreeThrow_scoring,OPP_percentagePointsOffTurnovers_scoring,OPP_percentagePointsPaint_scoring,OPP_percentageAssisted2pt_scoring,OPP_percentageUnassisted2pt_scoring,OPP_percentageAssisted3pt_scoring,OPP_percentageUnassisted3pt_scoring,OPP_percentageAssistedFGM_scoring,OPP_percentageUnassistedFGM_scoring,OPP_threePointersPercentage_traditional,OPP_freeThrowsPercentage_traditional,OPP_percentageFieldGoalsMade_usage,OPP_percentageFieldGoalsAttempted_usage,OPP_percentageThreePointersMade_usage,OPP_percentageThreePointersAttempted_usage,OPP_percentageFreeThrowsMade_usage,OPP_percentageFreeThrowsAttempted_usage,OPP_percentageReboundsOffensive_usage,OPP_percentageReboundsDefensive_usage,OPP_percentageReboundsTotal_usage,OPP_percentageAssists_usage,OPP_percentageTurnovers_usage,OPP_percentageSteals_usage,OPP_percentageBlocks_usage,OPP_percentageBlocksAllowed_usage,OPP_percentagePersonalFouls_usage,OPP_percentagePersonalFoulsDrawn_usage,OPP_percentagePoints_usage,OPP_plusMinusPoints_traditional,OPP_GAME_DATE,MATCHUP,SEASON,IS_HOME,IS_WIN,POINT_DIFF
0,0021000001,1610612738,32,69,8,16,16,25,8,34,42,25,6,4,18,19,88,240.000000,17,11,11,38,6,95.258826,86.767938,8.458819,0.179324,1.418765,16.786944,0.040284,0.143548,0.097696,13.576424,0.536647,0.565526,0.192004,91.500720,92.499906,61.978819,0.121102,0.524833,0.364811,0.217790,0.420576,0.341330,0.187027,0.244226,2.633472,0.773753,0.226247,0.600667,0.136254,0.202795,0.091713,0.196539,0.204380,0.464413,0.525706,0.421030,0.332569,0.000000,0.710834,0.235902,0.228976,0.522179,0.200810,0.200914,0.180178,0.199018,0.197938,0.195703,0.190636,0.204025,0.202745,0.190902,0.178942,0.176299,0.151945,0.196471,0.197720,0.199016,0.200868,4.585556,1610612748,2010-10-26,27,74,8,20,18,25,11,28,39,15,10,6,17,21,80,240.000000,22,5,11,24,4,86.585597,94.558222,-7.960403,0.158097,0.533849,13.530931,0.049858,0.138836,0.087374,10.813681,0.426550,0.495102,0.197047,91.499007,92.600174,59.272778,0.090339,0.418351,0.344338,0.188392,0.524045,0.364850,0.217761,0.223355,2.708681,0.712399,0.243379,0.496113,0.140206,0.278267,0.123794,0.225773,0.204365,0.355907,0.308280,0.538734,0.396736,0.152847,0.520927,0.434698,0.226023,0.579196,0.205427,0.199612,0.187020,0.186814,0.196853,0.187300,0.218039,0.202114,0.198359,0.228813,0.200531,0.173722,0.193393,0.147483,0.203271,0.192911,0.203349,-6.306528,2010-10-26,BOS vs. MIA,2010-11,1,1,8
1,0021000001,1610612748,27,74,8,20,18,25,11,28,39,15,10,6,17,21,80,240.000000,22,5,11,24,4,86.585597,94.558222,-7.960403,0.158097,0.533849,13.530931,0.049858,0.138836,0.087374,10.813681,0.426550,0.495102,0.197047,91.499007,92.600174,59.272778,0.090339,0.418351,0.344338,0.188392,0.524045,0.364850,0.217761,0.223355,2.708681,0.712399,0.243379,0.496113,0.140206,0.278267,0.123794,0.225773,0.204365,0.355907,0.308280,0.538734,0.396736,0.152847,0.520927,0.434698,0.226023,0.579196,0.205427,0.199612,0.187020,0.186814,0.196853,0.187300,0.218039,0.202114,0.198359,0.228813,0.200531,0.173722,0.193393,0.147483,0.203271,0.192911,0.203349,-6.306528,1610612738,2010-10-26,32,69,8,16,16,25,8,34,42,25,6,4,18,19,88,240.000000,17,11,11,38,6,95.258826,86.767938,8.458819,0.179324,1.418765,16.786944,0.040284,0.143548,0.097696,13.576424,0.536647,0.565526,0.192004,91.500720,92.499906,61.978819,0.121102,0.524833,0.364811,0.217790,0.420576,0.341330,0.187027,0.244226,2.633472,0.773753,0.226247,0.600667,0.136254,0.202795,0.091713,0.196539,0.204380,0.464413,0.525706,0.421030,0.332569,0.000000,0.710834,0.235902,0.228976,0.522179,0.200810,0.200914,0.180178,0.199018,0.197938,0.195703,0.190636,0.204025,0.202745,0.190902,0.178942,0.176299,0.151945,0.196471,0.197720,0.199016,0.200868,4.585556,2010-10-26,MIA @ BOS,2010-11,0,0,-8
2,0021000002,1610612756,36,74,9,19,11,16,7,23,30,15,3,4,19,19,92,240.000000,17,11,6,44,2,101.425007,116.062382,-14.648243,0.113202,0.765569,12.112500,0.037518,0.088750,0.065437,15.816979,0.525870,0.535510,0.195844,94.820024,91.299769,49.458125,0.072061,0.551087,0.219725,0.204248,0.516365,0.162388,0.155634,0.433928,2.182639,0.755892,0.244108,0.571466,0.086887,0.339328,0.039907,0.089060,0.246915,0.484873,0.259333,0.521430,0.333822,0.231595,0.436625,0.563375,0.372170,0.355924,0.197446,0.201281,0.204137,0.193324,0.178646,0.176324,0.205161,0.195726,0.197705,0.204080,0.182448,0.135582,0.266250,0.217986,0.189598,0.189302,0.196874,-7.175972,1610612757,2010-10-26,43,93,10,20,10,15,18,30,48,31,11,2,12,22,106,240.000000,21,21,13,42,4,116.705951,101.868819,14.847993,0.179627,1.619028,21.211271,0.071370,0.149384,0.105635,7.830722,0.500923,0.520792,0.191743,94.821719,91.100492,55.840069,0.059822,0.516180,0.167638,0.156635,0.550046,0.216926,0.204611,0.194777,2.417917,0.803757,0.196243,0.626211,0.218095,0.243037,0.126697,0.118044,0.228035,0.408116,0.552484,0.343836,0.495069,0.000000,0.696103,0.291188,0.261279,0.596760,0.198572,0.201131,0.215227,0.194294,0.199463,0.211358,0.207308,0.211804,0.199374,0.199567,0.145885,0.190182,0.204896,0.180178,0.195436,0.204637,0.199758,9.013194,2010-10-26,PHX @ POR,2010-11,0,0,-14
3,0021000002,1610612757,43,93,10,20,10,15,18,30,48,31,11,2,12,22,106,240.000000,21,21,13,42,4,116.705951,101.868819,14.847993,0.179627,1.619028,21.211271,0.071370,0.149384,0.105635,7.830722,0.500923,0.520792,0.191743,94.821719,91.100492,55.840069,0.059822,0.516180,0.167638,0.156635,0.550046,0.216926,0.204611,0.194777,2.417917,0.803757,0.196243,0.626211,0.218095,0.243037,0.126697,0.118044,0.228035,0.408116,0.552484,0.343836,0.495069,0.000000,0.696103,0.291188,0.261279,0.596760,0.198572,0.201131,0.215227,0.194294,0.199463,0.211358,0.207308,0.211804,0.199374,0.199567,0.145885,0.190182,0.204896,0.180178,0.195436,0.204637,0.199758,9.013194,1610612756,2010-10-26,36,74,9,19,11,16,7,23,30,15,3,4,19,19,92,240.000000,17,11,6,44,2,101.425007,116.062382,-14.648243,0.113202,0.765569,12.112500,0.037518,0.088750,0.065437,15.816979,0.525870,0.535510,0.195844,94.820024,91.299769,49.458125,0.072061,0.551087,0.219725,0.204248,0.516365,0.162388,0.155634,0.433928,2.182639,0.755892,0.244108,0.571466,0.086887,0.339328,0.039907,0.089060,0.246915,0.484873,0.259333,0.521430,0.333822,0.231595,0.436625,0.563375,0.372170,0.355924,0.197446,0.201281,0.204137,0.193324,0.178646,0.176324,0.205161,0.195726,0.197705,0.204080,0.182448,0.135582,0.266250,0.217986,0.189598,0.189302,0.196874,-7.175972,2010-10-26,POR vs. PHX,2010-11,1,1,14
4,0021000003,1610612745,38,91,8,20,26,28,16,37,53,25,6,7,20,25,110,239.983333,10,16,17,42,4,106.091812,106.928071,-0.849344,0.163359,1.393743,22.918397,0.061861,0.126248,0.095825,12.957421,0.402580,0.475858,0.198410,107.319701,104.201138,61.522328,0.102728,0.462191,0.307097,0.193372,0.466376,0.295486,0.112989,0.279195,3.016946,0.693632,0.244628,0.453675,0.138961,0.260127,0.120814,0.204803,0.083422,0.314576,0.444436,0.343327,0.383863,0.043388,0.668162,0.250444,0.220759,0.663562,0.195155,0.200732,0.158192,0.197478,0.179789,0.185280,0.236348,0.191520,0.197204,0.203254,0.194367,0.177269,0.216853,0.199693,0.193461,0.186709,0.195638,1.938676,1610612747,2010-10-26,40,96,9,21,23,28,14,30,44,21,11,4,12,24,112,240.000000,20,23,12,46,7,107.380507,106.350694,1.029812,0.131055,1.647756,16.353167,0.047063,0.113064,0.079990,8.603597,0.459826,0.499774,0.198762,107.319970,103.900553,62.920486,0.095947,0.469353,0.301715,0.112949,0.462946,0.308913,0.193897,0.342518,3.282014,0.763126,0.236874,0.525493,0.091175,0.238875,0.084063,0.155979,0.220723,0.434164,0.409895,0.420730,0.239410,0.061146,0.488379,0.431968,0.178848,0.382295,0.197003,0.201767,0.150194,0.192673,0.191074,0.183087,0.181331,0.198692,0.201060,0.205763,0.192513,0.190966,0.181838,0.153690,0.207920,0.200452,0.194698,1.128750,2010-10-26,HOU @ LAL,2010-11,0,0,-2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109323,0042400306,1610612754,92,170,34,66,32,38,12,60,72,60,20,18,24,46,250,480.033333,68,24,50,100,12,127.352996,105.015909,22.340053,0.153711,2.025884,22.049573,0.031637,0.114636,0.078322,7.995493,0.594024,0.616071,0.192961,101.399425,100.497996,54.449066,0.114831,0.633074,0.227772,0.126563,0.531103,0.304584,0.174045,0.304667,2.036595,0.562603,0.430870,0.428352,0.068864,0.387280,0.189745,0.093415,0.301309,0.359492,0.451172,0.346064,0.634262,0.209499,0.559565,0.349330,0.434339,0.543444,0.203022,0.197637,0.193534,0.192665,0.192244,0.191655,0.167582,0.200059,0.202670,0.197309,0.199876,0.164402,0.206905,0.175693,0.203954,0.201069,0.201598,13.039650,1610612752,2025-05-31,82,172,18,64,34,52,26,56,82,46,20,12,34,32,216,480.000000,26,30,20,108,18,108.452111,126.791896,-18.338972,0.137946,1.068833,13.428708,0.050020,0.136825,0.086799,13.136583,0.501459,0.559112,0.190430,101.400812,99.101217,59.888889,0.085635,0.531050,0.308973,0.174502,0.648678,0.225373,0.131917,0.166467,2.875208,0.620439,0.348450,0.568563,0.073972,0.177266,0.102219,0.223204,0.122027,0.494456,0.382728,0.424147,0.355764,0.143333,0.470684,0.402580,0.190597,0.561911,0.195777,0.195994,0.214569,0.203844,0.172815,0.187488,0.206232,0.194752,0.195968,0.195585,0.162782,0.198096,0.156052,0.187617,0.192666,0.197732,0.202965,-12.926389,2025-05-31,IND vs. NYK,2024-25,1,1,34
109324,0042400306,1610612754,92,170,34,66,32,38,12,60,72,60,20,18,24,46,250,480.033333,68,24,50,100,12,127.352996,105.015909,22.340053,0.153711,2.025884,22.049573,0.031637,0.114636,0.078322,7.995493,0.594024,0.616071,0.192961,101.399425,100.497996,54.449066,0.114831,0.633074,0.227772,0.126563,0.531103,0.304584,0.174045,0.304667,2.036595,0.562603,0.430870,0.428352,0.068864,0.387280,0.189745,0.093415,0.301309,0.359492,0.451172,0.346064,0.634262,0.209499,0.559565,0.349330,0.434339,0.543444,0.203022,0.197637,0.193534,0.192665,0.192244,0.191655,0.167582,0.200059,0.202670,0.197309,0.199876,0.164402,0.206905,0.175693,0.203954,0.201069,0.201598,13.039650,1610612752,2025-05-31,82,172,18,64,34,52,26,56,82,46,20,12,34,32,216,480.000000,26,30,20,108,18,108.452111,126.791896,-18.338972,0.137946,1.068833,13.428708,0.050020,0.136825,0.086799,13.136583,0.501459,0.559112,0.190430,101.400812,99.101217,59.888889,0.085635,0.531050,0.308973,0.174502,0.648678,0.225373,0.131917,0.166467,2.875208,0.620439,0.348450,0.568563,0.073972,0.177266,0.102219,0.223204,0.122027,0.494456,0.382728,0.424147,0.355764,0.143333,0.470684,0.402580,0.190597,0.561911,0.195777,0.195994,0.214569,0.203844,0.172815,0.187488,0.206232,0.194752,0.195968,0.195585,0.162782,0.198096,0.156052,0.187617,0.192666,0.197732,0.202965,-12.926389,2025-05-31,IND vs. NYK,2024-25,1,1,34
109325,0042400306,1610612754,92,170,34,66,32,38,12,60,72,60,20,18,24,46,250,480.033333,68,24,50,100,12,127.352996,105.015909,22.340053,0.153711,2.025884,22.049573,0.031637,0.114636,0.078322,7.995493,0.594024,0.616071,0.192961,101.399425,100.497996,54.449066,0.114831,0.633074,0.227772,0.126563,0.531103,0.304584,0.174045,0.304667,2.036595,0.562603,0.430870,0.428352,0.068864,0.387280,0.189745,0.093415,0.301309,0.359492,0.451172,0.346064,0.634262,0.209499,0.559565,0.349330,0.434339,0.543444,0.203022,0.197637,0.193534,0.192665,0.192244,0.191655,0.167582,0.200059,0.202670,0.197309,0.199876,0.164402,0.206905,0.175693,0.203954,0.201069,0.201598,13.039650,1610612752,2025-05-31,82,172,18,64,34,52,26,56,82,46,20,12,34,32,216,480.000000,26,30,20,108,18,108.452111,126.791896,-18.338972,0.137946,1.068833,13.428708,0.050020,0.136825,0.086799,13.136583,0.501459,0.559112,0.190430,101.400812,99.101217,59.888889,0.085635,0.531050,0.308973,0.174502,0.648678,0.225373,0.131917,0.166467,2.875208,0.620439,0.348450,0.568563,0.073972,0.177266,0.102219,0.223204,0.122027,0.494456,0.382728,0.424147,0.355764,0.143333,0.470684,0.402580,0.190597,0.561911,0.195777,0.195994,0.214569,0.203844,0.172815,0.187488,0.206232,0.194752,0.195968,0.195585,0.162782,0.198096,0.156052,0.187617,0.192666,0.197732,0.202965,-12.926389,2025-05-31,IND vs. NYK,2024-25,1,1,34
109326,0042400401,1610612754,78,164,36,78,30,42,26,86,112,48,2,14,48,44,222,480.033333,8,24,20,68,12,107.199743,106.020887,1.185473,0.152824,1.487171,16.042157,0.054027,0.135550,0.102712,16.549691,0.590604,0.622814,0.194014,104.398840,103.499456,61.453580,0.105077,0.587677,0.257399,0.241239,0.456693,0.248252,0.066348,0.198115,2.300604,0.501280,0.498720,0.367759,0.077094,0.487458,0.102077,0.145064,0.030612,0.290827,0.311811,0.520492,0.785258,0.148566,0.577500,0.422500,0.453506,0.406064,0.201986,0.200134,0.195214,0.196461,0.208137,0.204329,0.181644,0.190189,0.193941,0.198113,0.190323,0.068954,0.205017,0.172056,0.188080,0.209822,0.200037,3.767655,1610612760,2025-06-05,78,196,22,60,42,48,20,58,78,26,28,12,12,38,220,480.033333,22,22,22,92,14,104.859211,107.238254,-2.401319,0.089877,0.484480,9.231408,0.032102,0.126582,0.073159,4.215554,0.471415,0.518615,0.190986,104.398813,104.097747,65.037497,0.097399,0.455725,0.253861,0.066125,0.585600,0.256203,0.242994,0.305840,2.829040,0.638792,0.358499,0.523928,0.053338,0.277455,0.101775,0.178516,0.108151,0.470590,0.280170,0.548314,0.341042,0.292109,0.451021,0.528911,0.280632,0.579554,0.197089,0.199259,0.183445,0.203555,0.203944,0.205643,0.158191,0.195664,0.189841,0.191115,0.166873,0.207506,0.252223,0.156445,0.205720,0.204903,0.201040,-1.280814,2025-06-05,IND @ OKC,2024-25,0,1,2
109327,0042400401,1610612760,78,196,22,60,42,48,20,58,78,26,28,12,12,38,220,480.033333,22,22,22,92,14,104.859211,107.238254,-2.401319,0.089877,0.484480,9.231408,0.032102,0.126582,0.073159,4.215554,0.471415,0.518615,0.190986,104.398813,104.097747,65.037497,0.097399,0.455725,0.253861,0.066125,0.585600,0.256203,0.242994,0.305840,2.829040,0.638792,0.358499,0.523928,0.053338,0.277455,0.101775,0.178516,0.108151,0.470590,0.280170,0.548314,0.341042,0.292109,0.451021,0.528911,0.280632,0.579554,0.197089,0.199259,0.183445,0.203555,0.203944,0.205643,0.158191,0.195664,0.189841,0.191115,0.166873,0.207506,0.252223,0.156445,0.205720,0.204903,0.201040,-1.280814,1610612754,2025-06-05,78,164,36,78,30,42,26,86,112,48,2,14,48,44,222,480.033333,8,24,20,68,12,107.199743,106.020887,1.185473,0.152824,1.487171,16.042157,0.054027,0.135550,0.102712,16.549691,0.590604,0.622814,0.194014,104.398840,103.499456,61.453580,0.105077,0.587677,0.257399,0.241239,0.456693,0.248252,0.066348,0.198115,2.300604,0.501280,0.498720,0.367759,0.077094,0.487458,0.102077,0.145064,0.030612,0.290827,0.311811,0.520492,0.785258,0.148566,0.577500,0.422500,0.453506,0.406064,0.201986,0.200134,0.195214,0.196461,0.208137,0.204329,0.181644,0.190189,0.193941,0.198113,0.190323,0.068954,0.205017,0.172056,0.188080,0.209822,0.200037,3.767655,2025-06-05,OKC vs. IND,2024-25,1,0,-2

# SPECIAL FOR ODDS : Keep only season past 2010-11

In [ ]:
# # get first line with season 2010-11 and cut all lines before
# first_season = match_dataset[match_dataset['SEASON'] == '2010-11'].index[0]
# match_dataset = match_dataset.iloc[first_season:].reset_index(drop=True)
# match_dataset

# Merge Odds with dataset

In [ ]:
all_odds_df = merge_odds_csv_files(DATA_ODDS_HISTORY_DIR)

match_dataset = match_odds_with_dataset(all_odds_df, match_dataset)

------------------ Nombre de lignes supprimées pour cotes manquantes: 38 ------------------

In [ ]:
match_dataset

,GAME_ID,TEAM_ID,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,points_traditional,MINUTES_PLAYED,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,blocksAgainst_misc,offensiveRating_advanced,defensiveRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,threePointersPercentage_traditional,freeThrowsPercentage_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage,plusMinusPoints_traditional,OPP_TEAM_ID,GAME_DATE,OPP_fieldGoalsMade_traditional,OPP_fieldGoalsAttempted_traditional,OPP_threePointersMade_traditional,OPP_threePointersAttempted_traditional,OPP_freeThrowsMade_traditional,OPP_freeThrowsAttempted_traditional,OPP_reboundsOffensive_traditional,OPP_reboundsDefensive_traditional,OPP_reboundsTotal_traditional,OPP_assists_traditional,OPP_steals_traditional,OPP_blocks_traditional,OPP_turnovers_traditional,OPP_foulsPersonal_traditional,OPP_points_traditional,OPP_MINUTES_PLAYED,OPP_pointsOffTurnovers_misc,OPP_pointsSecondChance_misc,OPP_pointsFastBreak_misc,OPP_pointsPaint_misc,OPP_blocksAgainst_misc,OPP_offensiveRating_advanced,OPP_defensiveRating_advanced,OPP_netRating_advanced,OPP_assistPercentage_advanced,OPP_assistToTurnover_advanced,OPP_assistRatio_advanced,OPP_offensiveReboundPercentage_advanced,OPP_defensiveReboundPercentage_advanced,OPP_reboundPercentage_advanced,OPP_turnoverRatio_advanced,OPP_effectiveFieldGoalPercentage_advanced,OPP_trueShootingPercentage_advanced,OPP_usagePercentage_advanced,OPP_estimatedPace_advanced,OPP_pace_advanced,OPP_possessions_advanced,OPP_PIE_advanced,OPP_effectiveFieldGoalPercentage_fourfactors,OPP_freeThrowAttemptRate_fourfactors,OPP_teamTurnoverPercentage_fourfactors,OPP_oppEffectiveFieldGoalPercentage_fourfactors,OPP_oppFreeThrowAttemptRate_fourfactors,OPP_oppTeamTurnoverPercentage_fourfactors,OPP_oppOffensiveReboundPercentage_fourfactors,OPP_foulsDrawn_misc,OPP_percentageFieldGoalsAttempted2pt_scoring,OPP_percentageFieldGoalsAttempted3pt_scoring,OPP_percentagePoints2pt_scoring,OPP_percentagePointsMidrange2pt_scoring,OPP_percentagePoints3pt_scoring,OPP_percentagePointsFastBreak_scoring,OPP_percentagePointsFreeThrow_scoring,OPP_percentagePointsOffTurnovers_scoring,OPP_percentagePointsPaint_scoring,OPP_percentageAssisted2pt_scoring,OPP_percentageUnassisted2pt_scoring,OPP_percentageAssisted3pt_scoring,OPP_percentageUnassisted3pt_scoring,OPP_percentageAssistedFGM_scoring,OPP_percentageUnassistedFGM_scoring,OPP_threePointersPercentage_traditional,OPP_freeThrowsPercentage_traditional,OPP_percentageFieldGoalsMade_usage,OPP_percentageFieldGoalsAttempted_usage,OPP_percentageThreePointersMade_usage,OPP_percentageThreePointersAttempted_usage,OPP_percentageFreeThrowsMade_usage,OPP_percentageFreeThrowsAttempted_usage,OPP_percentageReboundsOffensive_usage,OPP_percentageReboundsDefensive_usage,OPP_percentageReboundsTotal_usage,OPP_percentageAssists_usage,OPP_percentageTurnovers_usage,OPP_percentageSteals_usage,OPP_percentageBlocks_usage,OPP_percentageBlocksAllowed_usage,OPP_percentagePersonalFouls_usage,OPP_percentagePersonalFoulsDrawn_usage,OPP_percentagePoints_usage,OPP_plusMinusPoints_traditional,OPP_GAME_DATE,MATCHUP,SEASON,IS_HOME,IS_WIN,POINT_DIFF,TEAM_NAME,OPPONENT_NAME,ODDS,OPP_ODDS
0,0041000405,1610612742,39.0,69.0,13.0,19.0,21.0,27.0,4.0,22.0,26.0,23.0,8.0,3.0,11.0,20.0,112.0,240.000000,21.0,7.0,14.0,34.0,4.0,124.483000,115.769097,8.688201,0.156017,1.707951,17.436076,0.023313,0.119843,0.074096,9.238958,0.721924,0.717079,0.192045,89.160360,89.400925,60.698056,0.112384,0.662704,0.404485,0.124605,0.583640,0.370735,0.199594,0.292299,3.331250,0.652529,0.347471,0.490485,0.129948,0.335592,0.154415,0.173923,0.205318,0.360644,0.445141,0.456595,0.471740,0.191593,0.662219,0.337781,0.495611,0.722107,0.201647,0.198718,0.200506,0.198868,0.198774,0.195838,0.142726,0.209231,0.212778,0.218416,0.208787,0.205196,0.216426,0.218662,0.193322,0.194688,0.200734,9.178333,1610612748,2011-06-09,37.0,70.0,8.0,20.0,21.0,26.0,9.0,27.0,36.0,25.0,5.0,4.0,16.0,26.0,103.0,240.000000,15.0,11.0,11.0,46.0,3.0,115.847194,123.534965,-7.678000,0.181847,1.192205,17.331146,0.049004,0.164362,0.104834,12.073757,0.634362,0.671524,0.194274,89.161361,90.000096,58.286111,0.087416,0.584849,0.377992,0.199160,0.661934,0.408766,0.123801,0.118958,2.993056,0.700720,0.299280,0.638474,0.146638,0.193494,0.088319,0.153588,0.102425,0.491671,0.463771,0.327410,0.194375,0.143542,0.648529,0.337027,0.209442,0.440016,0.198049,0.202923,0.175064,0.183521,0.178636,0.175533,0.202980,0.199053,0.198641,0.202974,0.174229,0.167085,0.182146,0.156903,0.199387,0.189628,0.198622,-7.056458,2011-06-09,DAL vs. MIA,2010-11,1.0,1.0,9.0,dallas mavericks,miami heat,1.64,1.76
1,0041000405,1610612748,37.0,70.0,8.0,20.0,21.0,26.0,9.0,27.0,36.0,25.0,5.0,4.0,16.0,26.0,103.0,240.000000,15.0,11.0,11.0,46.0,3.0,115.847194,123.534965,-7.678000,0.181847,1.192205,17.331146,0.049004,0.164362,0.104834,12.073757,0.634362,0.671524,0.194274,89.161361,90.000096,58.286111,0.087416,0.584849,0.377992,0.199160,0.661934,0.408766,0.123801,0.118958,2.993056,0.700720,0.299280,0.638474,0.146638,0.193494,0.088319,0.153588,0.102425,0.491671,0.463771,0.327410,0.194375,0.143542,0.648529,0.337027,0.209442,0.440016,0.198049,0.202923,0.175064,0.183521,0.178636,0.175533,0.202980,0.199053,0.198641,0.202974,0.174229,0.167085,0.182146,0.156903,0.199387,0.189628,0.198622,-7.056458,1610612742,2011-06-09,39.0,69.0,13.0,19.0,21.0,27.0,4.0,22.0,26.0,23.0,8.0,3.0,11.0,20.0,112.0,240.000000,21.0,7.0,14.0,34.0,4.0,124.483000,115.769097,8.688201,0.156017,1.707951,17.436076,0.023313,0.119843,0.074096,9.238958,0.721924,0.717079,0.192045,89.160360,89.400925,60.698056,0.112384,0.662704,0.404485,0.124605,0.583640,0.370735,0.199594,0.292299,3.331250,0.652529,0.347471,0.490485,0.129948,0.335592,0.154415,0.173923,0.205318,0.360644,0.445141,0.456595,0.471740,0.191593,0.662219,0.337781,0.495611,0.722107,0.201647,0.198718,0.200506,0.198868,0.198774,0.195838,0.142726,0.209231,0.212778,0.218416,0.208787,0.205196,0.216426,0.218662,0.193322,0.194688,0.200734,9.178333,2011-06-09,MIA @ DAL,2010-11,0.0,0.0,-9.0,miami heat,dallas mavericks,1.76,1.64
2,0041000404,1610612742,29.0,73.0,4.0,19.0,24.0,30.0,12.0,29.0,41.0,13.0,7.0,2.0,11.0,18.0,86.0,240.000000,18.0,15.0,6.0,38.0,5.0,100.873868,96.398639,4.442590,0.113874,0.536158,12.644361,0.056293,0.118563,0.086590,11.815931,0.378804,0.432576,0.195710,85.370765,85.688906,58.694167,0.099991,0.424794,0.406251,0.130057,0.441711,0.319575,0.175969,0.327472,3.498472,0.610423,0.376591,0.451375,0.096813,0.113327,0.048074,0.228900,0.154725,0.354562,0.249309,0.437635,0.254306,0.000000,0.375732,0.418017,0.082695,0.661237,0.197312,0.199356,0.143681,0.182896,0.205958,0.209901,0.204594,0.195762,0.199805,0.201086,0.201356,0.168984,0.134826,0.228042,0.195406,0.206492,0.198223,4.126111,1610612748,2011-06-07,32.0,75.0,2.0,14.0,17.0,24.0,15.0,29.0,44.0,19.0,8.0,5.0,13.0,23.0,83.0,240.000000,12.0,15.0,11.0,40.0,2.0,95.933215,101.875465,-5.924340,0.141166,0.970573,18.303035,0.058802,0.120893,0.092651,9.220799,0.364425,0.409425,0.191351,85.377647,85.899028,59.846458,0.098935,0.444339,0.320926,0.173622,0.423996,0.412444,0.129097,0.305750,3.006319,0.741355,0.247534,0.664792,0.230533,0.060694,0.108858,0.196067,0.228346,0.434259,0.431126,0.429568,0.060694,0.000000,0.491821,0.429568,0.024278,0.459279,0.197191,0.200027,0.060694,0.187825,0.225926,0.209875,0.179078,0.194578,0.198288,0.199801,0.178217,0.199264,0.189727,0.169931,0.199084,0.208150,0.201120,-2.981667,2011-06-07,DAL vs. MIA,2010-11,1.0,1.0,3.0,dallas mavericks,miami heat,1.52,1.95
3,0041000404,1610612748,32.0,75.0,2.0,14.0,17.0,24.0,15.0,29.0,44.0,19.0,8.0,5.0,13.0,23.0,83.0,240.000000,12.0,15.0,11.0,40.0,2.0,95.933215,101.875465,-5.924340,0.141166,0.970573,18.303035,0.058802,0.120893,0.092651,9.220799,0.364425,0.409425,0.191351,85.377647,85.899028,59.846458,0.098935,0.444339,0.320926,0.173622,0.423996,0.412444,0.129097,0.305750,3.006319,0.741355,0.247534,0.664792,0.230533,0.060694,0.108858,0.196067,0.228346,0.434259,0.431126,0.429568,0.060694,0.000000,0.491821,0.429568,0.024278,0.459279,0.197191,0.200027,0.060694,0.187825,0.225926,0.209875,0.179078,0.194578,0.198288,0.199801,0.178217,0.199264,0.189727,0.169931,0.199084,0.208150,0.201120,-2.981667,1610612742,2011-06-07,29.0,73.0,4.0,19.0,24.0,30.0,12.0,29.0,41.0,13.0,7.0,2.0,11.0,18.0,86.0,240.000000,18.0,15.0,6.0,38.0,5.0,100.873868,96.398639,4.442590,0.113874,0.536158,12.644361,0.056293,0.118563,0.086590,11.815931,0.378804,0.432576,0.195710,85.370765,85.688906,58.694167,0.099991,0.424794,0.406251,0.130057,0.441711,0.319575,0.175969,0.327472,3.498472,0.610423,0.376591,0.451375,0.096813,0.113327,0.048074,0.228900,0.154725,0.354562,0.249309,0.437635,0.254306,0.000000,0.375732,0.418017,0.082695,0.661237,0.197312,0.199356,0.143681,0.182896,0.205958,0.209901,0.204594,0.195762,0.199805,0.201086,0.201356,0.168984,0.134826,0.228042,0.195406,0.206492,0.198223,4.126111,2011-06-07,MIA @ DAL,2010-11,0.0,0.0,-3.0,miami heat,dallas mavericks,1.95,1.52
4,0041000403,1610612742,28.0,70.0,8.0,21.0,22.0,27.0,12.0,30.0,42.0,18.0,3.0,8.0,14.0,14.0,86.0,240.016667,15.0,10.0,16.0,22.0,5.0,99.437171,100.956579,-1.501437,0.159033,0.716335,15.023873,0.055469,0.131777,0.093695,9.475342,0.462078,0.546024,0.194047,86.240661,87.203469,60.724464,0.107783,0.459188,0.386461,0.165660,0.487271,0.205206,0.148102,0.226107,3.787306,0.698464,0.301050,0.448428,0.178193,0.270369,0.196699,0.280892,0.112813,0.270060,0.440091,0.466929,0.594542,0.000000,0.581981,0.384202,0.283477,0.715446,0.203179,0.199818,0.197541,0.218848,0.191637,0.191682,0.201641,0.196560,0.198357,0.195042,0.182928,0.158187,0.193325,0.183023,0.180651,0.202986,0.200672,1.866676,1610612748,2011-06-05,34.0,78.0,8.0,19.0,12.0,15.0,9.0,27.0,36.0,20.0,8.0,5.0,10.0,27.0,88.0,240.000000,19.0,6.0,14.0,40.0,8.0,101.587653,97.731354,3.851229,0.149351,0.993837,17.983674,0.037043,0.122203,0.079955,9.223090,0.437792,0.478918,0.190763,86.238558,87.500490,57.617431,0.097241,0.490690,0.203339,0.146303,0.462031,0.388643,0.167176,0.306525,1.977222,0.684235,0.289028,0.560525,0.137528,0.266296,0.196057,0.122296,0.194572,0.422997,0.458541,0.264237,0.388333,0.160972,0.671875,0.250695,0.227667,0.447583,0.200026,0.197254,0.225424,0.211465,0.256346,0.267137,0.188497,0.199093,0.195778,0.198939,0.158231,0.182757,0.180563,0.195386,0.198620,0.231920,0.204162,0.124236,2011-06-05,DAL vs. MIA,2010-11,1.0,0.0,-2.0,dallas mavericks,miami heat,1.55,1.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38076,0022400087,1610612746,80.0,164.0,24.0,66.0,34.0,42.0,22.0,66.0,88.0,60.0,8.0,10.0,32.0,48.0,218.0,480.000000,24.0,26.0,18.0,104.0,8.0,113.362125,106.258118,7.124118,0.176159,0.721969,23.426660,0.047712,0.124879,0.090236,9.414285,0.445455,0.526659,0.199489,97.398442,97.201100,56.666111,0.080197,0.563024,0.254146,0.174821,0.487391,0.278288,0.102450,0.230944,2.985000,0.509191,0.385670,0.406454,0.021151,0.199629,0.090298,0.192666,0.078131,0.385304,0.443182,0.265984,0.413165,0.071557,0.496141,0.213026,0.193859,0.390767,0.192688,0.201909,0.190237,0.200174,0.189189,0.203901,0.197160,0.202369,0.202316,0.199148,0.183938,0.200451,0.194223,0.230847,0.212717,0.209447,0.196583,1.675764,1610612743,2024-10-26,70.0,174.0,28.0,70.0,40.0,48.0,20.0,54.0,74.0,40.0,26.0,8.0,20.0,44.0,208.0,480.000000,46.0,26.0,18.0,68.0,10.0,106.772104,112.970514,-6.198410,0.151218,1.326062,15.111083,0.038915,0.127791,0.079419,6.563722,0.458367,0.510433,0.192078,97.401411,97.299438,63.261667,0.071764,0.485370,0.277949,0.102535,0.561151,0.256051,0.174513,0.279869,3.273889,0.633511,0.366489,0.403140,0.070555,0.275650,0.084249,0.274251,0.334755,0.332739,0.343786,0.480728,0.542070,0.124319,0.459480,0.365033,0.413705,0.785538,0.183716,0.200075,0.180334,0.200766,0.200539,0.197205,0.205557,0.206304,0.204789,0.192580,0.203496,0.194035,0.233618,0.195868,0.185764,0.189378,0.187967,0.159167,2024-10-26,LAC @ DEN,2024-25,0.0,1.0,10.0,los angeles clippers,denver nuggets,3.31,1.25
38077,0041600144,1610612744,92.0,172.0,34.0,58.0,38.0,54.0,12.0,78.0,90.0,54.0,14.0,18.0,20.0,30.0,256.0,480.066667,28.0,8.0,28.0,76.0,6.0,124.959651,101.338634,23.627788,0.159116,0.671833,19.085578,0.021503,0.144437,0.091251,6.107187,0.574273,0.591628,0.197779,101.820948,101.899357,49.736912,0.125485,0.638266,0.309432,0.098037,0.467547,0.339688,0.108453,0.152001,2.018609,0.696467,0.303533,0.483538,0.161477,0.283940,0.072509,0.151561,0.089193,0.322061,0.475786,0.443392,0.361629,0.112888,0.527949,0.391229,0.326586,0.555776,0.197415,0.201708,0.149023,0.178059,0.220644,0.203437,0.120788,0.203820,0.199202,0.192156,0.155522,0.188083,0.159018,0.167407,0.190030,0.201668,0.194639,15.950840,1610612757,2017-04-24,66.0,170.0,26.0,78.0,48.0,58.0,14.0,64.0,78.0,28.0,14.0,6.0,22.0,40.0,206.0,480.000000,10.0,24.0,8.0,56.0,18.0,101.844146,125.220750,-23.395333,0.127247,0.459810,7.659931,0.026963,0.149890,0.079387,7.898889,0.445574,0.497418,0.197088,101.821058,101.799083,58.903472,0.072797,0.464278,0.342151,0.107807,0.638345,0.314603,0.097185,0.141563,2.000625,0.569321,0.430679,0.416382,0.113276,0.266090,0.021082,0.265775,0.045946,0.303253,0.232639,0.629861,0.465324,0.134190,0.356060,0.529634,0.246725,0.660928,0.196420,0.199501,0.202839,0.198949,0.188219,0.189613,0.218232,0.200356,0.196915,0.202024,0.185506,0.179140,0.179408,0.188289,0.199278,0.189102,0.195214,-15.393889,2017-04-24,GSW @ POR,2016-17,0.0,1.0,50.0,golden state warriors,portland trail blazers,1.39,2.53
38078,0041600144,1610612757,66.0,170.0,26.0,78.0,48.0,58.0,14.0,64.0,78.0,28.0,14.0,6.0,22.0,40.0,206.0,480.000000,10.0,24.0,8.0,56.0,18.0,101.844146,125.220750,-23.395333,0.127247,0.459810,7.659931,0.026963,0.149890,0.079387,7.898889,0.445574,0.497418,0.197088,101.821058,101.799083,58.903472,0.072797,0.464278,0.342151,0.107807,0.638345,0.314603,0.097185,0.141563,2.000625,0.569321,0.430679,0.416382,0.113276,0.266090,0.021082,0.265775,0.045946,0.303253,0.232639,0.629861,0.465324,0.134190,0.356060,0.529634,0.246725,0.660928,0.196420,0.199501,0.202839,0.198949,0.188219,0.189613,0.218232,0.200356,0.196915,0.202024,0.185506,0.179140,0.179408,0.188289,0.199278,0.189102,0.195214,-15.393889,1610612744,2017-04-24,92.0,172.0,34.0,58.0,38.0,54.0,12.0,78.0,90.0,54.0,14.0,18.0,20.0,30.0,256.0,480.066667,28.0,8.0,28.0,76.0,6.0,124.959651,101.338634,23.627788,0.159116,0.671833,19.085578,0.021503,0.144437,0.091251,6.107187,0.574273,0.591628,0.197779,101.820948,101.899357,49.736912,0.125485,0.638266,0.309432,0.098037,0.467547,0.339688,0.108453,0.152001,2.018609,0.696467,0.303533,0.483538,0.161477,0.283940,0.072509,0.151561,0.089193,0.322061,0.475786,0.443392,0.361629,0.112888,0.527949,0.391229,0.326586,0.555776,0.197415,0.201708,0.149023,0.178059,0.220644,0.203437,0.120788,0.203820,0.199202,0.192156,0.155522,0.188083,0.159018,0.167407,0.190030,0.201668,0.194639,15.950840,2017-04-24,POR vs. GSW,2016-17,1.0,0.0,-50.0,portland trail blazers,golden state warriors,2.53,1.39
38079,0041600174,1610612746,66.0,150.0,22.0,64.0,42.0,58.0,12.0,50.0,62.0,34.0,16.0,0.0,18.0,36.0,196.0,480.000000,8.0,18.0,2.0,72.0,6.0,105.526958,114.612326,-9.062743,0.158487,1.224792,9.869785,0.027667,0.136051,0.075938,7.550153,0.470915,0.523953,0.196106,90.000755,92.499403,61.731944,0.079637,0.515302,0.389761,0.099057,0.611337,0.299591,0.144572,0.216650,2.398264,0.545538,0.438420,0.411841,0.112741,0.283564,0.016042,0.254109,0.033678,0.299100,0.523208,0.410264,0.613097,0.026208,0.657032,0.276440,0.276600,0.678282,0.195867,0.199402,0.179647,0.197842,0.197776,0.196380,0.161846,0.189472,0.188428,0.187360,0.217585,0.167650,0.000000,0.219571,0.201685,0.204162,0.196494,-5.767708,1610612762,2017-04-23,80.0,148.0,20.0,44.0,30.0,42.0,14.0,70.0,84.0,48.0,14.0,6.0,24.0,34.0,210.0,480.033333,34.0,26.0,14.0,116.0,0.0,114.779251,105.963287,8.798521,0.146641,1.804977,21.007916,0.038889,0.152663,0.101374,10.618881,0.616318,0.632372,0.192232,90.000485,92.499108,56.007083,0.121128,0.610731,0.285767,0.144788,0.512997,0.387243,0.098771,0.149382,2.278314,0.606645,0.342811,0.432184,0.010235,0.349148,0.080264,0.124603,0.194886,0.421949,0.357923,0.460700,0.584751,0.121033,0.571900,0.334009,0.381367,0.514805,0.202307,0.197492,0.217908,0.192665,0.212821,0.209094,0.197643,0.195777,0.198899,0.191070,0.175250,0.172667,0.224207,0.000000,0.192367,0.195124,0.202119,5.759461,2017-04-23,LAC @ UTA,2016-17,0.0,0.0,-14.0,los angeles clippers,utah jazz,1.70,1.93

# Reorder columns for visualisation

In [ ]:
cols_first = ['GAME_ID', 'GAME_DATE', 'TEAM_ID', 'OPP_TEAM_ID', 'IS_HOME', 'IS_WIN','POINT_DIFF', 'points_traditional','ODDS','OPP_ODDS']
other_cols = [col for col in match_dataset.columns if col not in cols_first]
match_dataset = match_dataset[cols_first + other_cols]
match_dataset

,GAME_ID,GAME_DATE,TEAM_ID,OPP_TEAM_ID,IS_HOME,IS_WIN,POINT_DIFF,points_traditional,ODDS,OPP_ODDS,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,MINUTES_PLAYED,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,blocksAgainst_misc,offensiveRating_advanced,defensiveRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,threePointersPercentage_traditional,freeThrowsPercentage_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage,plusMinusPoints_traditional,OPP_fieldGoalsMade_traditional,OPP_fieldGoalsAttempted_traditional,OPP_threePointersMade_traditional,OPP_threePointersAttempted_traditional,OPP_freeThrowsMade_traditional,OPP_freeThrowsAttempted_traditional,OPP_reboundsOffensive_traditional,OPP_reboundsDefensive_traditional,OPP_reboundsTotal_traditional,OPP_assists_traditional,OPP_steals_traditional,OPP_blocks_traditional,OPP_turnovers_traditional,OPP_foulsPersonal_traditional,OPP_points_traditional,OPP_MINUTES_PLAYED,OPP_pointsOffTurnovers_misc,OPP_pointsSecondChance_misc,OPP_pointsFastBreak_misc,OPP_pointsPaint_misc,OPP_blocksAgainst_misc,OPP_offensiveRating_advanced,OPP_defensiveRating_advanced,OPP_netRating_advanced,OPP_assistPercentage_advanced,OPP_assistToTurnover_advanced,OPP_assistRatio_advanced,OPP_offensiveReboundPercentage_advanced,OPP_defensiveReboundPercentage_advanced,OPP_reboundPercentage_advanced,OPP_turnoverRatio_advanced,OPP_effectiveFieldGoalPercentage_advanced,OPP_trueShootingPercentage_advanced,OPP_usagePercentage_advanced,OPP_estimatedPace_advanced,OPP_pace_advanced,OPP_possessions_advanced,OPP_PIE_advanced,OPP_effectiveFieldGoalPercentage_fourfactors,OPP_freeThrowAttemptRate_fourfactors,OPP_teamTurnoverPercentage_fourfactors,OPP_oppEffectiveFieldGoalPercentage_fourfactors,OPP_oppFreeThrowAttemptRate_fourfactors,OPP_oppTeamTurnoverPercentage_fourfactors,OPP_oppOffensiveReboundPercentage_fourfactors,OPP_foulsDrawn_misc,OPP_percentageFieldGoalsAttempted2pt_scoring,OPP_percentageFieldGoalsAttempted3pt_scoring,OPP_percentagePoints2pt_scoring,OPP_percentagePointsMidrange2pt_scoring,OPP_percentagePoints3pt_scoring,OPP_percentagePointsFastBreak_scoring,OPP_percentagePointsFreeThrow_scoring,OPP_percentagePointsOffTurnovers_scoring,OPP_percentagePointsPaint_scoring,OPP_percentageAssisted2pt_scoring,OPP_percentageUnassisted2pt_scoring,OPP_percentageAssisted3pt_scoring,OPP_percentageUnassisted3pt_scoring,OPP_percentageAssistedFGM_scoring,OPP_percentageUnassistedFGM_scoring,OPP_threePointersPercentage_traditional,OPP_freeThrowsPercentage_traditional,OPP_percentageFieldGoalsMade_usage,OPP_percentageFieldGoalsAttempted_usage,OPP_percentageThreePointersMade_usage,OPP_percentageThreePointersAttempted_usage,OPP_percentageFreeThrowsMade_usage,OPP_percentageFreeThrowsAttempted_usage,OPP_percentageReboundsOffensive_usage,OPP_percentageReboundsDefensive_usage,OPP_percentageReboundsTotal_usage,OPP_percentageAssists_usage,OPP_percentageTurnovers_usage,OPP_percentageSteals_usage,OPP_percentageBlocks_usage,OPP_percentageBlocksAllowed_usage,OPP_percentagePersonalFouls_usage,OPP_percentagePersonalFoulsDrawn_usage,OPP_percentagePoints_usage,OPP_plusMinusPoints_traditional,OPP_GAME_DATE,MATCHUP,SEASON,TEAM_NAME,OPPONENT_NAME
0,0041000405,2011-06-09,1610612742,1610612748,1.0,1.0,9.0,112.0,1.64,1.76,39.0,69.0,13.0,19.0,21.0,27.0,4.0,22.0,26.0,23.0,8.0,3.0,11.0,20.0,240.000000,21.0,7.0,14.0,34.0,4.0,124.483000,115.769097,8.688201,0.156017,1.707951,17.436076,0.023313,0.119843,0.074096,9.238958,0.721924,0.717079,0.192045,89.160360,89.400925,60.698056,0.112384,0.662704,0.404485,0.124605,0.583640,0.370735,0.199594,0.292299,3.331250,0.652529,0.347471,0.490485,0.129948,0.335592,0.154415,0.173923,0.205318,0.360644,0.445141,0.456595,0.471740,0.191593,0.662219,0.337781,0.495611,0.722107,0.201647,0.198718,0.200506,0.198868,0.198774,0.195838,0.142726,0.209231,0.212778,0.218416,0.208787,0.205196,0.216426,0.218662,0.193322,0.194688,0.200734,9.178333,37.0,70.0,8.0,20.0,21.0,26.0,9.0,27.0,36.0,25.0,5.0,4.0,16.0,26.0,103.0,240.000000,15.0,11.0,11.0,46.0,3.0,115.847194,123.534965,-7.678000,0.181847,1.192205,17.331146,0.049004,0.164362,0.104834,12.073757,0.634362,0.671524,0.194274,89.161361,90.000096,58.286111,0.087416,0.584849,0.377992,0.199160,0.661934,0.408766,0.123801,0.118958,2.993056,0.700720,0.299280,0.638474,0.146638,0.193494,0.088319,0.153588,0.102425,0.491671,0.463771,0.327410,0.194375,0.143542,0.648529,0.337027,0.209442,0.440016,0.198049,0.202923,0.175064,0.183521,0.178636,0.175533,0.202980,0.199053,0.198641,0.202974,0.174229,0.167085,0.182146,0.156903,0.199387,0.189628,0.198622,-7.056458,2011-06-09,DAL vs. MIA,2010-11,dallas mavericks,miami heat
1,0041000405,2011-06-09,1610612748,1610612742,0.0,0.0,-9.0,103.0,1.76,1.64,37.0,70.0,8.0,20.0,21.0,26.0,9.0,27.0,36.0,25.0,5.0,4.0,16.0,26.0,240.000000,15.0,11.0,11.0,46.0,3.0,115.847194,123.534965,-7.678000,0.181847,1.192205,17.331146,0.049004,0.164362,0.104834,12.073757,0.634362,0.671524,0.194274,89.161361,90.000096,58.286111,0.087416,0.584849,0.377992,0.199160,0.661934,0.408766,0.123801,0.118958,2.993056,0.700720,0.299280,0.638474,0.146638,0.193494,0.088319,0.153588,0.102425,0.491671,0.463771,0.327410,0.194375,0.143542,0.648529,0.337027,0.209442,0.440016,0.198049,0.202923,0.175064,0.183521,0.178636,0.175533,0.202980,0.199053,0.198641,0.202974,0.174229,0.167085,0.182146,0.156903,0.199387,0.189628,0.198622,-7.056458,39.0,69.0,13.0,19.0,21.0,27.0,4.0,22.0,26.0,23.0,8.0,3.0,11.0,20.0,112.0,240.000000,21.0,7.0,14.0,34.0,4.0,124.483000,115.769097,8.688201,0.156017,1.707951,17.436076,0.023313,0.119843,0.074096,9.238958,0.721924,0.717079,0.192045,89.160360,89.400925,60.698056,0.112384,0.662704,0.404485,0.124605,0.583640,0.370735,0.199594,0.292299,3.331250,0.652529,0.347471,0.490485,0.129948,0.335592,0.154415,0.173923,0.205318,0.360644,0.445141,0.456595,0.471740,0.191593,0.662219,0.337781,0.495611,0.722107,0.201647,0.198718,0.200506,0.198868,0.198774,0.195838,0.142726,0.209231,0.212778,0.218416,0.208787,0.205196,0.216426,0.218662,0.193322,0.194688,0.200734,9.178333,2011-06-09,MIA @ DAL,2010-11,miami heat,dallas mavericks
2,0041000404,2011-06-07,1610612742,1610612748,1.0,1.0,3.0,86.0,1.52,1.95,29.0,73.0,4.0,19.0,24.0,30.0,12.0,29.0,41.0,13.0,7.0,2.0,11.0,18.0,240.000000,18.0,15.0,6.0,38.0,5.0,100.873868,96.398639,4.442590,0.113874,0.536158,12.644361,0.056293,0.118563,0.086590,11.815931,0.378804,0.432576,0.195710,85.370765,85.688906,58.694167,0.099991,0.424794,0.406251,0.130057,0.441711,0.319575,0.175969,0.327472,3.498472,0.610423,0.376591,0.451375,0.096813,0.113327,0.048074,0.228900,0.154725,0.354562,0.249309,0.437635,0.254306,0.000000,0.375732,0.418017,0.082695,0.661237,0.197312,0.199356,0.143681,0.182896,0.205958,0.209901,0.204594,0.195762,0.199805,0.201086,0.201356,0.168984,0.134826,0.228042,0.195406,0.206492,0.198223,4.126111,32.0,75.0,2.0,14.0,17.0,24.0,15.0,29.0,44.0,19.0,8.0,5.0,13.0,23.0,83.0,240.000000,12.0,15.0,11.0,40.0,2.0,95.933215,101.875465,-5.924340,0.141166,0.970573,18.303035,0.058802,0.120893,0.092651,9.220799,0.364425,0.409425,0.191351,85.377647,85.899028,59.846458,0.098935,0.444339,0.320926,0.173622,0.423996,0.412444,0.129097,0.305750,3.006319,0.741355,0.247534,0.664792,0.230533,0.060694,0.108858,0.196067,0.228346,0.434259,0.431126,0.429568,0.060694,0.000000,0.491821,0.429568,0.024278,0.459279,0.197191,0.200027,0.060694,0.187825,0.225926,0.209875,0.179078,0.194578,0.198288,0.199801,0.178217,0.199264,0.189727,0.169931,0.199084,0.208150,0.201120,-2.981667,2011-06-07,DAL vs. MIA,2010-11,dallas mavericks,miami heat
3,0041000404,2011-06-07,1610612748,1610612742,0.0,0.0,-3.0,83.0,1.95,1.52,32.0,75.0,2.0,14.0,17.0,24.0,15.0,29.0,44.0,19.0,8.0,5.0,13.0,23.0,240.000000,12.0,15.0,11.0,40.0,2.0,95.933215,101.875465,-5.924340,0.141166,0.970573,18.303035,0.058802,0.120893,0.092651,9.220799,0.364425,0.409425,0.191351,85.377647,85.899028,59.846458,0.098935,0.444339,0.320926,0.173622,0.423996,0.412444,0.129097,0.305750,3.006319,0.741355,0.247534,0.664792,0.230533,0.060694,0.108858,0.196067,0.228346,0.434259,0.431126,0.429568,0.060694,0.000000,0.491821,0.429568,0.024278,0.459279,0.197191,0.200027,0.060694,0.187825,0.225926,0.209875,0.179078,0.194578,0.198288,0.199801,0.178217,0.199264,0.189727,0.169931,0.199084,0.208150,0.201120,-2.981667,29.0,73.0,4.0,19.0,24.0,30.0,12.0,29.0,41.0,13.0,7.0,2.0,11.0,18.0,86.0,240.000000,18.0,15.0,6.0,38.0,5.0,100.873868,96.398639,4.442590,0.113874,0.536158,12.644361,0.056293,0.118563,0.086590,11.815931,0.378804,0.432576,0.195710,85.370765,85.688906,58.694167,0.099991,0.424794,0.406251,0.130057,0.441711,0.319575,0.175969,0.327472,3.498472,0.610423,0.376591,0.451375,0.096813,0.113327,0.048074,0.228900,0.154725,0.354562,0.249309,0.437635,0.254306,0.000000,0.375732,0.418017,0.082695,0.661237,0.197312,0.199356,0.143681,0.182896,0.205958,0.209901,0.204594,0.195762,0.199805,0.201086,0.201356,0.168984,0.134826,0.228042,0.195406,0.206492,0.198223,4.126111,2011-06-07,MIA @ DAL,2010-11,miami heat,dallas mavericks
4,0041000403,2011-06-05,1610612742,1610612748,1.0,0.0,-2.0,86.0,1.55,1.90,28.0,70.0,8.0,21.0,22.0,27.0,12.0,30.0,42.0,18.0,3.0,8.0,14.0,14.0,240.016667,15.0,10.0,16.0,22.0,5.0,99.437171,100.956579,-1.501437,0.159033,0.716335,15.023873,0.055469,0.131777,0.093695,9.475342,0.462078,0.546024,0.194047,86.240661,87.203469,60.724464,0.107783,0.459188,0.386461,0.165660,0.487271,0.205206,0.148102,0.226107,3.787306,0.698464,0.301050,0.448428,0.178193,0.270369,0.196699,0.280892,0.112813,0.270060,0.440091,0.466929,0.594542,0.000000,0.581981,0.384202,0.283477,0.715446,0.203179,0.199818,0.197541,0.218848,0.191637,0.191682,0.201641,0.196560,0.198357,0.195042,0.182928,0.158187,0.193325,0.183023,0.180651,0.202986,0.200672,1.866676,34.0,78.0,8.0,19.0,12.0,15.0,9.0,27.0,36.0,20.0,8.0,5.0,10.0,27.0,88.0,240.000000,19.0,6.0,14.0,40.0,8.0,101.587653,97.731354,3.851229,0.149351,0.993837,17.983674,0.037043,0.122203,0.079955,9.223090,0.437792,0.478918,0.190763,86.238558,87.500490,57.617431,0.097241,0.490690,0.203339,0.146303,0.462031,0.388643,0.167176,0.306525,1.977222,0.684235,0.289028,0.560525,0.137528,0.266296,0.196057,0.122296,0.194572,0.422997,0.458541,0.264237,0.388333,0.160972,0.671875,0.250695,0.227667,0.447583,0.200026,0.197254,0.225424,0.211465,0.256346,0.267137,0.188497,0.199093,0.195778,0.198939,0.158231,0.182757,0.180563,0.195386,0.198620,0.231920,0.204162,0.124236,2011-06-05,DAL vs. MIA,2010-11,dallas mavericks,miami heat
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38076,0022400087,2024-10-26,1610612746,1610612743,0.0,1.0,10.0,218.0,3.31,1.25,80.0,164.0,24.0,66.0,34.0,42.0,22.0,66.0,88.0,60.0,8.0,10.0,32.0,48.0,480.000000,24.0,26.0,18.0,104.0,8.0,113.362125,106.258118,7.124118,0.176159,0.721969,23.426660,0.047712,0.124879,0.090236,9.414285,0.445455,0.526659,0.199489,97.398442,97.201100,56.666111,0.080197,0.563024,0.254146,0.174821,0.487391,0.278288,0.102450,0.230944,2.985000,0.509191,0.385670,0.406454,0.021151,0.199629,0.090298,0.192666,0.078131,0.385304,0.443182,0.265984,0.413165,0.071557,0.496141,0.213026,0.193859,0.390767,0.192688,0.201909,0.190237,0.200174,0.189189,0.203901,0.197160,0.202369,0.202316,0.199148,0.183938,0.200451,0.194223,0.230847,0.212717,0.209447,0.196583,1.675764,70.0,174.0,28.0,70.0,40.0,48.0,20.0,54.0,74.0,40.0,26.0,8.0,20.0,44.0,208.0,480.000000,46.0,26.0,18.0,68.0,10.0,106.772104,112.970514,-6.198410,0.151218,1.326062,15.111083,0.038915,0.127791,0.079419,6.563722,0.458367,0.510433,0.192078,97.401411,97.299438,63.261667,0.071764,0.485370,0.277949,0.102535,0.561151,0.256051,0.174513,0.279869,3.273889,0.633511,0.366489,0.403140,0.070555,0.275650,0.084249,0.274251,0.334755,0.332739,0.343786,0.480728,0.542070,0.124319,0.459480,0.365033,0.413705,0.785538,0.183716,0.200075,0.180334,0.200766,0.200539,0.197205,0.205557,0.206304,0.204789,0.192580,0.203496,0.194035,0.233618,0.195868,0.185764,0.189378,0.187967,0.159167,2024-10-26,LAC @ DEN,2024-25,los angeles clippers,denver nuggets
38077,0041600144,2017-04-24,1610612744,1610612757,0.0,1.0,50.0,256.0,1.39,2.53,92.0,172.0,34.0,58.0,38.0,54.0,12.0,78.0,90.0,54.0,14.0,18.0,20.0,30.0,480.066667,28.0,8.0,28.0,76.0,6.0,124.959651,101.338634,23.627788,0.159116,0.671833,19.085578,0.021503,0.144437,0.091251,6.107187,0.574273,0.591628,0.197779,101.820948,101.899357,49.736912,0.125485,0.638266,0.309432,0.098037,0.467547,0.339688,0.108453,0.152001,2.018609,0.696467,0.303533,0.483538,0.161477,0.283940,0.072509,0.151561,0.089193,0.322061,0.475786,0.443392,0.361629,0.112888,0.527949,0.391229,0.326586,0.555776,0.197415,0.201708,0.149023,0.178059,0.220644,0.203437,0.120788,0.203820,0.199202,0.192156,0.155522,0.188083,0.159018,0.167407,0.190030,0.201668,0.194639,15.950840,66.0,170.0,26.0,78.0,48.0,58.0,14.0,64.0,78.0,28.0,14.0,6.0,22.0,40.0,206.0,480.000000,10.0,24.0,8.0,56.0,18.0,101.844146,125.220750,-23.395333,0.127247,0.459810,7.659931,0.026963,0.149890,0.079387,7.898889,0.445574,0.497418,0.197088,101.821058,101.799083,58.903472,0.072797,0.464278,0.342151,0.107807,0.638345,0.314603,0.097185,0.141563,2.000625,0.569321,0.430679,0.416382,0.113276,0.266090,0.021082,0.265775,0.045946,0.303253,0.232639,0.629861,0.465324,0.134190,0.356060,0.529634,0.246725,0.660928,0.196420,0.199501,0.202839,0.198949,0.188219,0.189613,0.218232,0.200356,0.196915,0.202024,0.185506,0.179140,0.179408,0.188289,0.199278,0.189102,0.195214,-15.393889,2017-04-24,GSW @ POR,2016-17,golden state warriors,portland trail blazers
38078,0041600144,2017-04-24,1610612757,1610612744,1.0,0.0,-50.0,206.0,2.53,1.39,66.0,170.0,26.0,78.0,48.0,58.0,14.0,64.0,78.0,28.0,14.0,6.0,22.0,40.0,480.000000,10.0,24.0,8.0,56.0,18.0,101.844146,125.220750,-23.395333,0.127247,0.459810,7.659931,0.026963,0.149890,0.079387,7.898889,0.445574,0.497418,0.197088,101.821058,101.799083,58.903472,0.072797,0.464278,0.342151,0.107807,0.638345,0.314603,0.097185,0.141563,2.000625,0.569321,0.430679,0.416382,0.113276,0.266090,0.021082,0.265775,0.045946,0.303253,0.232639,0.629861,0.465324,0.134190,0.356060,0.529634,0.246725,0.660928,0.196420,0.199501,0.202839,0.198949,0.188219,0.189613,0.218232,0.200356,0.196915,0.202024,0.185506,0.179140,0.179408,0.188289,0.199278,0.189102,0.195214,-15.393889,92.0,172.0,34.0,58.0,38.0,54.0,12.0,78.0,90.0,54.0,14.0,18.0,20.0,30.0,256.0,480.066667,28.0,8.0,28.0,76.0,6.0,124.959651,101.338634,23.627788,0.159116,0.671833,19.085578,0.021503,0.144437,0.091251,6.107187,0.574273,0.591628,0.197779,101.820948,101.899357,49.736912,0.125485,0.638266,0.309432,0.098037,0.467547,0.339688,0.108453,0.152001,2.018609,0.696467,0.303533,0.483538,0.161477,0.283940,0.072509,0.151561,0.089193,0.322061,0.475786,0.443392,0.361629,0.112888,0.527949,0.391229,0.326586,0.555776,0.197415,0.201708,0.149023,0.178059,0.220644,0.203437,0.120788,0.203820,0.199202,0.192156,0.155522,0.188083,0.159018,0.167407,0.190030,0.201668,0.194639,15.950840,2017-04-24,POR vs. GSW,2016-17,portland trail blazers,golden state warriors
38079,0041600174,2017-04-23,1610612746,1610612762,0.0,0.0,-14.0,196.0,1.70,1.93,66.0,150.0,22.0,64.0,42.0,58.0,12.0,50.0,62.0,34.0,16.0,0.0,18.0,36.0,480.000000,8.0,18.0,2.0,72.0,6.0,105.526958,114.612326,-9.062743,0.158487,1.224792,9.869785,0.027667,0.136051,0.075938,7.550153,0.470915,0.523953,0.196106,90.000755,92.499403,61.731944,0.079637,0.515302,0.389761,0.099057,0.611337,0.299591,0.144572,0.216650,2.398264,0.545538,0.438420,0.411841,0.112741,0.283564,0.016042,0.254109,0.033678,0.299100,0.523208,0.410264,0.613097,0.026208,0.657032,0.276440,0.276600,0.678282,0.195867,0.199402,0.179647,0.197842,0.197776,0.196380,0.161846,0.189472,0.188428,0.187360,0.217585,0.167650,0.000000,0.219571,0.201685,0.204162,0.196494,-5.767708,80.0,148.0,20.0,44.0,30.0,42.0,14.0,70.0,84.0,48.0,14.0,6.0,24.0,34.0,210.0,480.033333,34.0,26.0,14.0,116.0,0.0,114.779251,105.963287,8.798521,0.146641,1.804977,21.007916,0.038889,0.152663,0.101374,10.618881,0.616318,0.632372,0.192232,90.000485,92.499108,56.007083,0.121128,0.610731,0.285767,0.144788,0.512997,0.387243,0.098771,0.149382,2.278314,0.606645,0.342811,0.432184,0.010235,0.349148,0.080264,0.124603,0.194886,0.421949,0.357923,0.460700,0.584751,0.121033,0.571900,0.334009,0.381367,0.514805,0.202307,0.197492,0.217908,0.192665,0.212821,0.209094,0.197643,0.195777,0.198899,0.191070,0.175250,0.172667,0.224207,0.000000,0.192367,0.195124,0.202119,5.759461,2017-04-23,LAC @ UTA,2016-17,los angeles clippers,utah jazz

# 🚀 Features avancées

In [ ]:

# Ajouter les features avancées aux stats de match
#match_dataset = add_advanced_boxscore_features(match_dataset)

# MOVED TO CONFIG
# features_to_roll = cols_to_sum + cols_to_weighted_avg
# features_to_roll += [f"OPP_{col}" for col in cols_to_sum + cols_to_weighted_avg]

# Calcul des features glissantes shiftées
match_dataset = compute_rolling_features(match_dataset, "TEAM_ID", ["TEAM_ID", "GAME_DATE"], features_to_roll, N_LIST, method="ewm")


match_dataset = compute_winrates(match_dataset, "TEAM_ID", "IS_WIN", "IS_HOME", N_LIST)
match_dataset = compute_win_ratio(match_dataset, "TEAM_ID", "IS_WIN", N_LIST)

match_dataset["IS_WIN_SHIFTED"] = match_dataset.groupby("TEAM_ID")["IS_WIN"].shift(1).fillna(0).astype(int)
match_dataset["WIN_STREAK"] = match_dataset.groupby("TEAM_ID").apply(
    lambda x: compute_win_streak(x, "TEAM_ID", "IS_WIN_SHIFTED")).reset_index(level=0, drop=True)
match_dataset = compute_side_win_streak(match_dataset, win_shifted_col="IS_WIN_SHIFTED")


# Calcul des jours de repos pour l'équipe et l'adversaire
match_dataset["DAYS_SINCE_LAST_GAME"] = compute_rest_days(match_dataset, "GAME_DATE", "TEAM_ID")
match_dataset["OPP_DAYS_SINCE_LAST_GAME"] = compute_rest_days(match_dataset, "GAME_DATE", "OPP_TEAM_ID")

# Avantage de repos
match_dataset["REST_ADVANTAGE"] = (
    match_dataset["DAYS_SINCE_LAST_GAME"] - match_dataset["OPP_DAYS_SINCE_LAST_GAME"]
)


match_dataset = compute_rolling_rest_advantage(
    match_dataset, "TEAM_ID", "IS_HOME", "REST_ADVANTAGE", N_LIST
)

match_dataset = compute_home_away_pts(
    match_dataset, "TEAM_ID", "IS_HOME", "points_traditional", "OPP_points_traditional", N_LIST
)

# match_dataset = rename_pts_against_columns(match_dataset)

match_dataset = compute_h2h(match_dataset, N_LIST)
# match_dataset = compute_h2h_pts_margin(match_dataset, N_LIST)
match_dataset = compute_h2h_season(match_dataset)
match_dataset = compute_h2h_streak(match_dataset)

match_dataset = compute_elo(match_dataset)
match_dataset = compute_elo_season(match_dataset)

e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (
e:\Documents_\Dev\NBA_Predictor\src\feature_builder.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"ROLL_{col}_{window}"] = (

In [ ]:
pd.options.display.max_columns = None
display(match_dataset)

          GAME_ID  GAME_DATE     TEAM_ID OPP_TEAM_ID  IS_HOME  IS_WIN  \
0      0021000001 2010-10-26  1610612738  1610612748      1.0     1.0
1      0021000001 2010-10-26  1610612748  1610612738      0.0     0.0
2      0021000002 2010-10-26  1610612756  1610612757      0.0     0.0
3      0021000002 2010-10-26  1610612757  1610612756      1.0     1.0
4      0021000003 2010-10-26  1610612745  1610612747      0.0     0.0
...           ...        ...         ...         ...      ...     ...
38076  0042400315 2025-05-28  1610612760  1610612750      1.0     1.0
38077  0042400305 2025-05-29  1610612752  1610612754      1.0     1.0
38078  0042400305 2025-05-29  1610612754  1610612752      0.0     0.0
38079  0042400306 2025-05-31  1610612752  1610612754      0.0     0.0
38080  0042400306 2025-05-31  1610612754  1610612752      1.0     1.0

       POINT_DIFF  points_traditional  ODDS  OPP_ODDS  \
0             8.0                88.0  1.88      1.70
1            -8.0                80.0  1.70      1.88
2           -14.0                92.0  3.30      1.22
3            14.0               106.0  1.22      3.30
4            -2.0               110.0  3.50      1.20
...           ...                 ...   ...       ...
38076        60.0               248.0  1.25      3.91
38077        34.0               222.0  1.54      2.46
38078       -34.0               188.0  2.46      1.54
38079       -34.0               216.0  2.38      1.58
38080        34.0               250.0  1.58      2.38

       fieldGoalsMade_traditional  fieldGoalsAttempted_traditional  \
0                            32.0                             69.0
1                            27.0                             74.0
2                            36.0                             74.0
3                            43.0                             93.0
4                            38.0                             91.0
...                           ...                              ...
38076                        92.0                            176.0
38077                        88.0                            178.0
38078                        60.0                            148.0
38079                        82.0                            172.0
38080                        92.0                            170.0

       threePointersMade_traditional  threePointersAttempted_traditional  \
0                                8.0                                16.0
1                                8.0                                20.0
2                                9.0                                19.0
3                               10.0                                20.0
4                                8.0                                20.0
...                              ...                                 ...
38076                           28.0                                70.0
38077                           16.0                                58.0
38078                           20.0                                60.0
38079                           18.0                                64.0
38080                           34.0                                66.0

       freeThrowsMade_traditional  freeThrowsAttempted_traditional  \
0                            16.0                             25.0
1                            18.0                             25.0
2                            11.0                             16.0
3                            10.0                             15.0
4                            26.0                             28.0
...                           ...                              ...
38076                        36.0                             42.0
38077                        30.0                             44.0
38078                        48.0                             58.0
38079                        34.0                             52.0
38080                        32.0                             38.0

       reboundsOffensive_traditional  reboundsDefensive_traditional  \
0                                8.0                           34.0
1                               11.0                           28.0
2                                7.0                           23.0
3                               18.0                           30.0
4                               16.0                           37.0
...                              ...                            ...
38076                           14.0                           78.0
38077                           22.0                           68.0
38078                           16.0                           64.0
38079                           26.0                           56.0
38080                           12.0                           60.0

       reboundsTotal_traditional  assists_traditional  steals_traditional  \
0                           42.0                 25.0                 6.0
1                           39.0                 15.0                10.0
2                           30.0                 15.0                 3.0
3                           48.0                 31.0                11.0
4                           53.0                 25.0                 6.0
...                          ...                  ...                 ...
38076                       92.0                 52.0                28.0
38077                       90.0                 44.0                22.0
38078                       80.0                 40.0                20.0
38079                       82.0                 46.0                20.0
38080                       72.0                 60.0                20.0

       blocks_traditional  turnovers_traditional  foulsPersonal_traditional  \
0                     4.0                   18.0                       19.0
1                     6.0                   17.0                       21.0
2                     4.0                   19.0                       19.0
3                     2.0                   12.0                       22.0
4                     7.0                   20.0                       25.0
...                   ...                    ...                        ...
38076                16.0                   28.0                       40.0
38077                 6.0                   30.0                       44.0
38078                14.0                   40.0                       44.0
38079                12.0                   34.0                       32.0
38080                18.0                   24.0                       46.0

       MINUTES_PLAYED  pointsOffTurnovers_misc  pointsSecondChance_misc  \
0          240.000000                     17.0                     11.0
1          240.000000                     22.0                      5.0
2          240.000000                     17.0                     11.0
3          240.000000                     21.0                     21.0
4          239.983333                     10.0                     16.0
...               ...                      ...                      ...
38076      479.966667                     36.0                     18.0
38077      480.033333                     30.0                     26.0
38078      480.000000                     40.0                     14.0
38079      480.000000                     26.0                     30.0
38080      480.033333                     68.0                     24.0

       pointsFastBreak_misc  pointsPaint_misc  blocksAgainst_misc  \
0                      11.0              38.0                 6.0
1                      11.0              24.0                 4.0
2                       6.0              44.0                 2.0
3                      13.0              42.0                 4.0
4                      17.0              42.0                 4.0
...                     ...               ...                 ...
38076                  38.0             108.0                12.0
38077                  30.0             120.0                14.0
38078                  32.0              68.0                 6.0
38079                  20.0             108.0                18.0
38080                  50.0             100.0                12.0

       offensiveRating_advanced  defensiveRating_advanced  netRating_advanced  \
0                     95.258826                 86.767938            8.458819
1                     86.585597                 94.558222           -7.960403
2                    101.425007                116.062382          -14.648243
3                    116.705951                101.868819           14.847993
4                    106.091812                106.928071           -0.849344
...                         ...                       ...                 ...
38076                116.271158                 86.683714           29.598472
38077                111.626672                 96.476189           15.129859
38078                 94.468389                110.979389          -16.503681
38079                108.452111                126.791896          -18.338972
38080                127.352996                105.015909           22.340053

       assistPercentage_advanced  assistToTurnover_advanced  \
0                       0.179324                   1.418765
1                       0.158097                   0.533849
2                       0.113202                   0.765569
3                       0.179627                   1.619028
4                       0.163359                   1.393743
...                          ...                        ...
38076                   0.153179                   1.150288
38077                   0.125950                   1.390534
38078                   0.163760                   0.659449
38079                   0.137946                   1.068833
38080                   0.153711                   2.025884

       assistRatio_advanced  offensiveReboundPercentage_advanced  \
0                 16.786944                             0.040284
1                 13.530931                             0.049858
2                 12.112500                             0.037518
3                 21.211271                             0.071370
4                 22.918397                             0.061861
...                     ...                                  ...
38076             17.148017                             0.028388
38077             15.440879                             0.043370
38078             15.763840                             0.033514
38079             13.428708                             0.050020
38080             22.049573                             0.031637

       defensiveReboundPercentage_advanced  reboundPercentage_advanced  \
0                                 0.143548                    0.097696
1                                 0.138836                    0.087374
2                                 0.088750                    0.065437
3                                 0.149384                    0.105635
4                                 0.126248                    0.095825
...                                    ...                         ...
38076                             0.149998                    0.096439
38077                             0.141279                    0.092679
38078                             0.127963                    0.081709
38079                             0.136825                    0.086799
38080                             0.114636                    0.078322

       turnoverRatio_advanced  effectiveFieldGoalPercentage_advanced  \
0                   13.576424                               0.536647
1                   10.813681                               0.426550
2                   15.816979                               0.525870
3                    7.830722                               0.500923
4                   12.957421                               0.402580
...                       ...                                    ...
38076               10.277860                               0.516245
38077               12.034067                               0.558147
38078               16.695181                               0.522219
38079               13.136583                               0.501459
38080                7.995493                               0.594024

       trueShootingPercentage_advanced  usagePercentage_advanced  \
0                             0.565526                  0.192004
1                             0.495102                  0.197047
2                             0.535510                  0.195844
3                             0.520792                  0.191743
4                             0.475858                  0.198410
...                                ...                       ...
38076                         0.561993                  0.192570
38077                         0.567221                  0.193626
38078                         0.580079                  0.196780
38079                         0.559112                  0.190430
38080                         0.616071                  0.192961

       estimatedPace_advanced  pace_advanced  possessions_advanced  \
0                   91.500720      92.499906             61.978819
1                   91.499007      92.600174             59.272778
2                   94.820024      91.299769             49.458125
3                   94.821719      91.100492             55.840069
4                  107.319701     104.201138             61.522328
...                       ...            ...                   ...
38076              105.418048     106.997439             56.169803
38077              100.719560      98.500117             59.565447
38078              100.719401      99.700689             48.830486
38079              101.400812      99.101217             59.888889
38080              101.399425     100.497996             54.449066

       PIE_advanced  effectiveFieldGoalPercentage_fourfactors  \
0          0.121102                                  0.524833
1          0.090339                                  0.418351
2          0.072061                                  0.551087
3          0.059822                                  0.516180
4          0.102728                                  0.462191
...             ...                                       ...
38076      0.148150                                  0.611803
38077      0.119602                                  0.540469
38078      0.078752                                  0.474772
38079      0.085635                                  0.531050
38080      0.114831                                  0.633074

       freeThrowAttemptRate_fourfactors  teamTurnoverPercentage_fourfactors  \
0                              0.364811                            0.217790
1                              0.344338                            0.188392
2                              0.219725                            0.204248
3                              0.167638                            0.156635
4                              0.307097                            0.193372
...                                 ...                                 ...
38076                          0.236456                            0.146934
38077                          0.246219                            0.145814
38078                          0.405602                            0.202463
38079                          0.308973                            0.174502
38080                          0.227772                            0.126563

       oppEffectiveFieldGoalPercentage_fourfactors  \
0                                         0.420576
1                                         0.524045
2                                         0.516365
3                                         0.550046
4                                         0.466376
...                                            ...
38076                                     0.474105
38077                                     0.472053
38078                                     0.541328
38079                                     0.648678
38080                                     0.531103

       oppFreeThrowAttemptRate_fourfactors  \
0                                 0.341330
1                                 0.364850
2                                 0.162388
3                                 0.216926
4                                 0.295486
...                                    ...
38076                             0.174840
38077                             0.393109
38078                             0.248815
38079                             0.225373
38080                             0.304584

       oppTeamTurnoverPercentage_fourfactors  \
0                                   0.187027
1                                   0.217761
2                                   0.155634
3                                   0.204611
4                                   0.112989
...                                      ...
38076                               0.200146
38077                               0.202483
38078                               0.145482
38079                               0.131917
38080                               0.174045

       oppOffensiveReboundPercentage_fourfactors  foulsDrawn_misc  \
0                                       0.244226         2.633472
1                                       0.223355         2.708681
2                                       0.433928         2.182639
3                                       0.194777         2.417917
4                                       0.279195         3.016946
...                                          ...              ...
38076                                   0.167282         2.263421
38077                                   0.192982         2.828206
38078                                   0.266363         2.224722
38079                                   0.166467         2.875208
38080                                   0.304667         2.036595

       percentageFieldGoalsAttempted2pt_scoring  \
0                                      0.773753
1                                      0.712399
2                                      0.755892
3                                      0.803757
4                                      0.693632
...                                         ...
38076                                  0.505107
38077                                  0.683842
38078                                  0.574555
38079                                  0.620439
38080                                  0.562603

       percentageFieldGoalsAttempted3pt_scoring  percentagePoints2pt_scoring  \
0                                      0.226247                     0.600667
1                                      0.243379                     0.496113
2                                      0.244108                     0.571466
3                                      0.196243                     0.626211
4                                      0.244628                     0.453675
...                                         ...                          ...
38076                                  0.447042                     0.415513
38077                                  0.316158                     0.631731
38078                                  0.419334                     0.426940
38079                                  0.348450                     0.568563
38080                                  0.430870                     0.428352

       percentagePointsMidrange2pt_scoring  percentagePoints3pt_scoring  \
0                                 0.136254                     0.202795
1                                 0.140206                     0.278267
2                                 0.086887                     0.339328

# 🧽 Nettoyage et sauvegarde

In [ ]:


final_date = datetime.now().strftime('%Y-%m-%d_%H-%M-%S')
raw_save_path = os.path.join(DATA_FINAL_DATASET_DIR, f'nba_features_final_{final_date}.csv')
clean_save_path = os.path.join(DATA_FINAL_CLEANED_DATASET_DIR, f'nba_features_cleaned_final_{final_date}.csv')

os.makedirs(DATA_FINAL_DATASET_DIR, exist_ok=True)
os.makedirs(DATA_FINAL_CLEANED_DATASET_DIR, exist_ok=True)

match_dataset.to_csv(raw_save_path, index=False)

final_cleaned = match_dataset.drop(columns=features_to_roll+COLS_MATCH_REAL, errors='ignore')
final_cleaned.to_csv(clean_save_path, index=False)

print(f"✅ Fichier brut : {raw_save_path}")
print(f"✅ Fichier clean : {clean_save_path}")

final_cleaned

✅ Fichier brut : data\final_dataset\nba_features_final_2025-06-06_19-50-30.csv
✅ Fichier clean : data\final_cleaned_dataset\nba_features_cleaned_final_2025-06-06_19-50-30.csv

,GAME_ID,GAME_DATE,TEAM_ID,OPP_TEAM_ID,IS_HOME,IS_WIN,POINT_DIFF,ODDS,OPP_ODDS,SEASON,ROLL_fieldGoalsMade_traditional_3,ROLL_fieldGoalsMade_traditional_5,ROLL_fieldGoalsMade_traditional_10,ROLL_fieldGoalsMade_traditional_25,ROLL_fieldGoalsMade_traditional_50,ROLL_fieldGoalsMade_traditional_100,ROLL_fieldGoalsMade_traditional_200,ROLL_fieldGoalsAttempted_traditional_3,ROLL_fieldGoalsAttempted_traditional_5,ROLL_fieldGoalsAttempted_traditional_10,ROLL_fieldGoalsAttempted_traditional_25,ROLL_fieldGoalsAttempted_traditional_50,ROLL_fieldGoalsAttempted_traditional_100,ROLL_fieldGoalsAttempted_traditional_200,ROLL_threePointersMade_traditional_3,ROLL_threePointersMade_traditional_5,ROLL_threePointersMade_traditional_10,ROLL_threePointersMade_traditional_25,ROLL_threePointersMade_traditional_50,ROLL_threePointersMade_traditional_100,ROLL_threePointersMade_traditional_200,ROLL_threePointersAttempted_traditional_3,ROLL_threePointersAttempted_traditional_5,ROLL_threePointersAttempted_traditional_10,ROLL_threePointersAttempted_traditional_25,ROLL_threePointersAttempted_traditional_50,ROLL_threePointersAttempted_traditional_100,ROLL_threePointersAttempted_traditional_200,ROLL_freeThrowsMade_traditional_3,ROLL_freeThrowsMade_traditional_5,ROLL_freeThrowsMade_traditional_10,ROLL_freeThrowsMade_traditional_25,ROLL_freeThrowsMade_traditional_50,ROLL_freeThrowsMade_traditional_100,ROLL_freeThrowsMade_traditional_200,ROLL_freeThrowsAttempted_traditional_3,ROLL_freeThrowsAttempted_traditional_5,ROLL_freeThrowsAttempted_traditional_10,ROLL_freeThrowsAttempted_traditional_25,ROLL_freeThrowsAttempted_traditional_50,ROLL_freeThrowsAttempted_traditional_100,ROLL_freeThrowsAttempted_traditional_200,ROLL_reboundsOffensive_traditional_3,ROLL_reboundsOffensive_traditional_5,ROLL_reboundsOffensive_traditional_10,ROLL_reboundsOffensive_traditional_25,ROLL_reboundsOffensive_traditional_50,ROLL_reboundsOffensive_traditional_100,ROLL_reboundsOffensive_traditional_200,ROLL_reboundsDefensive_traditional_3,ROLL_reboundsDefensive_traditional_5,ROLL_reboundsDefensive_traditional_10,ROLL_reboundsDefensive_traditional_25,ROLL_reboundsDefensive_traditional_50,ROLL_reboundsDefensive_traditional_100,ROLL_reboundsDefensive_traditional_200,ROLL_reboundsTotal_traditional_3,ROLL_reboundsTotal_traditional_5,ROLL_reboundsTotal_traditional_10,ROLL_reboundsTotal_traditional_25,ROLL_reboundsTotal_traditional_50,ROLL_reboundsTotal_traditional_100,ROLL_reboundsTotal_traditional_200,ROLL_assists_traditional_3,ROLL_assists_traditional_5,ROLL_assists_traditional_10,ROLL_assists_traditional_25,ROLL_assists_traditional_50,ROLL_assists_traditional_100,ROLL_assists_traditional_200,ROLL_steals_traditional_3,ROLL_steals_traditional_5,ROLL_steals_traditional_10,ROLL_steals_traditional_25,ROLL_steals_traditional_50,ROLL_steals_traditional_100,ROLL_steals_traditional_200,ROLL_blocks_traditional_3,ROLL_blocks_traditional_5,ROLL_blocks_traditional_10,ROLL_blocks_traditional_25,ROLL_blocks_traditional_50,ROLL_blocks_traditional_100,ROLL_blocks_traditional_200,ROLL_turnovers_traditional_3,ROLL_turnovers_traditional_5,ROLL_turnovers_traditional_10,ROLL_turnovers_traditional_25,ROLL_turnovers_traditional_50,ROLL_turnovers_traditional_100,ROLL_turnovers_traditional_200,ROLL_foulsPersonal_traditional_3,ROLL_foulsPersonal_traditional_5,ROLL_foulsPersonal_traditional_10,ROLL_foulsPersonal_traditional_25,ROLL_foulsPersonal_traditional_50,ROLL_foulsPersonal_traditional_100,ROLL_foulsPersonal_traditional_200,ROLL_points_traditional_3,ROLL_points_traditional_5,ROLL_points_traditional_10,ROLL_points_traditional_25,ROLL_points_traditional_50,ROLL_points_traditional_100,ROLL_points_traditional_200,ROLL_MINUTES_PLAYED_3,ROLL_MINUTES_PLAYED_5,ROLL_MINUTES_PLAYED_10,ROLL_MINUTES_PLAYED_25,ROLL_MINUTES_PLAYED_50,ROLL_MINUTES_PLAYED_100,ROLL_MINUTES_PLAYED_200,ROLL_pointsOffTurnovers_misc_3,ROLL_pointsOffTurnovers_misc_5,ROLL_pointsOffTurnovers_misc_10,ROLL_pointsOffTurnovers_misc_25,ROLL_pointsOffTurnovers_misc_50,ROLL_pointsOffTurnovers_misc_100,ROLL_pointsOffTurnovers_misc_200,ROLL_pointsSecondChance_misc_3,ROLL_pointsSecondChance_misc_5,ROLL_pointsSecondChance_misc_10,ROLL_pointsSecondChance_misc_25,ROLL_pointsSecondChance_misc_50,ROLL_pointsSecondChance_misc_100,ROLL_pointsSecondChance_misc_200,ROLL_pointsFastBreak_misc_3,ROLL_pointsFastBreak_misc_5,ROLL_pointsFastBreak_misc_10,ROLL_pointsFastBreak_misc_25,ROLL_pointsFastBreak_misc_50,ROLL_pointsFastBreak_misc_100,ROLL_pointsFastBreak_misc_200,ROLL_pointsPaint_misc_3,ROLL_pointsPaint_misc_5,ROLL_pointsPaint_misc_10,ROLL_pointsPaint_misc_25,ROLL_pointsPaint_misc_50,ROLL_pointsPaint_misc_100,ROLL_pointsPaint_misc_200,ROLL_blocksAgainst_misc_3,ROLL_blocksAgainst_misc_5,ROLL_blocksAgainst_misc_10,ROLL_blocksAgainst_misc_25,ROLL_blocksAgainst_misc_50,ROLL_blocksAgainst_misc_100,ROLL_blocksAgainst_misc_200,ROLL_offensiveRating_advanced_3,ROLL_offensiveRating_advanced_5,ROLL_offensiveRating_advanced_10,ROLL_offensiveRating_advanced_25,ROLL_offensiveRating_advanced_50,ROLL_offensiveRating_advanced_100,ROLL_offensiveRating_advanced_200,ROLL_defensiveRating_advanced_3,ROLL_defensiveRating_advanced_5,ROLL_defensiveRating_advanced_10,ROLL_defensiveRating_advanced_25,ROLL_defensiveRating_advanced_50,ROLL_defensiveRating_advanced_100,ROLL_defensiveRating_advanced_200,ROLL_netRating_advanced_3,ROLL_netRating_advanced_5,ROLL_netRating_advanced_10,ROLL_netRating_advanced_25,ROLL_netRating_advanced_50,ROLL_netRating_advanced_100,ROLL_netRating_advanced_200,ROLL_assistPercentage_advanced_3,ROLL_assistPercentage_advanced_5,ROLL_assistPercentage_advanced_10,ROLL_assistPercentage_advanced_25,ROLL_assistPercentage_advanced_50,ROLL_assistPercentage_advanced_100,ROLL_assistPercentage_advanced_200,ROLL_assistToTurnover_advanced_3,ROLL_assistToTurnover_advanced_5,ROLL_assistToTurnover_advanced_10,ROLL_assistToTurnover_advanced_25,ROLL_assistToTurnover_advanced_50,ROLL_assistToTurnover_advanced_100,ROLL_assistToTurnover_advanced_200,ROLL_assistRatio_advanced_3,ROLL_assistRatio_advanced_5,ROLL_assistRatio_advanced_10,ROLL_assistRatio_advanced_25,ROLL_assistRatio_advanced_50,ROLL_assistRatio_advanced_100,ROLL_assistRatio_advanced_200,ROLL_offensiveReboundPercentage_advanced_3,ROLL_offensiveReboundPercentage_advanced_5,ROLL_offensiveReboundPercentage_advanced_10,ROLL_offensiveReboundPercentage_advanced_25,ROLL_offensiveReboundPercentage_advanced_50,ROLL_offensiveReboundPercentage_advanced_100,ROLL_offensiveReboundPercentage_advanced_200,ROLL_defensiveReboundPercentage_advanced_3,ROLL_defensiveReboundPercentage_advanced_5,ROLL_defensiveReboundPercentage_advanced_10,ROLL_defensiveReboundPercentage_advanced_25,ROLL_defensiveReboundPercentage_advanced_50,ROLL_defensiveReboundPercentage_advanced_100,ROLL_defensiveReboundPercentage_advanced_200,ROLL_reboundPercentage_advanced_3,ROLL_reboundPercentage_advanced_5,ROLL_reboundPercentage_advanced_10,ROLL_reboundPercentage_advanced_25,ROLL_reboundPercentage_advanced_50,ROLL_reboundPercentage_advanced_100,ROLL_reboundPercentage_advanced_200,ROLL_turnoverRatio_advanced_3,ROLL_turnoverRatio_advanced_5,ROLL_turnoverRatio_advanced_10,ROLL_turnoverRatio_advanced_25,ROLL_turnoverRatio_advanced_50,ROLL_turnoverRatio_advanced_100,ROLL_turnoverRatio_advanced_200,ROLL_effectiveFieldGoalPercentage_advanced_3,ROLL_effectiveFieldGoalPercentage_advanced_5,ROLL_effectiveFieldGoalPercentage_advanced_10,ROLL_effectiveFieldGoalPercentage_advanced_25,ROLL_effectiveFieldGoalPercentage_advanced_50,ROLL_effectiveFieldGoalPercentage_advanced_100,ROLL_effectiveFieldGoalPercentage_advanced_200,ROLL_trueShootingPercentage_advanced_3,ROLL_trueShootingPercentage_advanced_5,ROLL_trueShootingPercentage_advanced_10,ROLL_trueShootingPercentage_advanced_25,ROLL_trueShootingPercentage_advanced_50,ROLL_trueShootingPercentage_advanced_100,ROLL_trueShootingPercentage_advanced_200,ROLL_usagePercentage_advanced_3,ROLL_usagePercentage_advanced_5,ROLL_usagePercentage_advanced_10,ROLL_usagePercentage_advanced_25,ROLL_usagePercentage_advanced_50,ROLL_usagePercentage_advanced_100,ROLL_usagePercentage_advanced_200,ROLL_estimatedPace_advanced_3,ROLL_estimatedPace_advanced_5,ROLL_estimatedPace_advanced_10,ROLL_estimatedPace_advanced_25,ROLL_estimatedPace_advanced_50,ROLL_estimatedPace_advanced_100,ROLL_estimatedPace_advanced_200,ROLL_pace_advanced_3,ROLL_pace_advanced_5,ROLL_pace_advanced_10,ROLL_pace_advanced_25,ROLL_pace_advanced_50,ROLL_pace_advanced_100,ROLL_pace_advanced_200,ROLL_possessions_advanced_3,ROLL_possessions_advanced_5,ROLL_possessions_advanced_10,ROLL_possessions_advanced_25,ROLL_possessions_advanced_50,ROLL_possessions_advanced_100,ROLL_possessions_advanced_200,ROLL_PIE_advanced_3,ROLL_PIE_advanced_5,ROLL_PIE_advanced_10,ROLL_PIE_advanced_25,ROLL_PIE_advanced_50,ROLL_PIE_advanced_100,ROLL_PIE_advanced_200,ROLL_effectiveFieldGoalPercentage_fourfactors_3,ROLL_effectiveFieldGoalPercentage_fourfactors_5,ROLL_effectiveFieldGoalPercentage_fourfactors_10,ROLL_effectiveFieldGoalPercentage_fourfactors_25,ROLL_effectiveFieldGoalPercentage_fourfactors_50,ROLL_effectiveFieldGoalPercentage_fourfactors_100,ROLL_effectiveFieldGoalPercentage_fourfactors_200,ROLL_freeThrowAttemptRate_fourfactors_3,ROLL_freeThrowAttemptRate_fourfactors_5,ROLL_freeThrowAttemptRate_fourfactors_10,ROLL_freeThrowAttemptRate_fourfactors_25,ROLL_freeThrowAttemptRate_fourfactors_50,ROLL_freeThrowAttemptRate_fourfactors_100,ROLL_freeThrowAttemptRate_fourfactors_200,ROLL_teamTurnoverPercentage_fourfactors_3,ROLL_teamTurnoverPercentage_fourfactors_5,ROLL_teamTurnoverPercentage_fourfactors_10,ROLL_teamTurnoverPercentage_fourfactors_25,ROLL_teamTurnoverPercentage_fourfactors_50,ROLL_teamTurnoverPercentage_fourfactors_100,ROLL_teamTurnoverPercentage_fourfactors_200,ROLL_oppEffectiveFieldGoalPercentage_fourfactors_3,ROLL_oppEffectiveFieldGoalPercentage_fourfactors_5,ROLL_oppEffectiveFieldGoalPercentage_fourfactors_10,ROLL_oppEffectiveFieldGoalPercentage_fourfactors_25,ROLL_oppEffectiveFieldGoalPercentage_fourfactors_50,ROLL_oppEffectiveFieldGoalPercentage_fourfactors_100,ROLL_oppEffectiveFieldGoalPercentage_fourfactors_200,ROLL_oppFreeThrowAttemptRate_fourfactors_3,ROLL_oppFreeThrowAttemptRate_fourfactors_5,ROLL_oppFreeThrowAttemptRate_fourfactors_10,ROLL_oppFreeThrowAttemptRate_fourfactors_25,ROLL_oppFreeThrowAttemptRate_fourfactors_50,ROLL_oppFreeThrowAttemptRate_fourfactors_100,ROLL_oppFreeThrowAttemptRate_fourfactors_200,ROLL_oppTeamTurnoverPercentage_fourfactors_3,ROLL_oppTeamTurnoverPercentage_fourfactors_5,ROLL_oppTeamTurnoverPercentage_fourfactors_10,ROLL_oppTeamTurnoverPercentage_fourfactors_25,ROLL_oppTeamTurnoverPercentage_fourfactors_50,ROLL_oppTeamTurnoverPercentage_fourfactors_100,ROLL_oppTeamTurnoverPercentage_fourfactors_200,ROLL_oppOffensiveReboundPercentage_fourfactors_3,ROLL_oppOffensiveReboundPercentage_fourfactors_5,ROLL_oppOffensiveReboundPercentage_fourfactors_10,ROLL_oppOffensiveReboundPercentage_fourfactors_25,ROLL_oppOffensiveReboundPercentage_fourfactors_50,ROLL_oppOffensiveReboundPercentage_fourfactors_100,ROLL_oppOffensiveReboundPercentage_fourfactors_200,ROLL_foulsDrawn_misc_3,ROLL_foulsDrawn_misc_5,ROLL_foulsDrawn_misc_10,ROLL_foulsDrawn_misc_25,ROLL_foulsDrawn_misc_50,ROLL_foulsDrawn_misc_100,ROLL_foulsDrawn_misc_200,ROLL_percentageFieldGoalsAttempted2pt_scoring_3,ROLL_percentageFieldGoalsAttempted2pt_scoring_5,ROLL_percentageFieldGoalsAttempted2pt_scoring_10,ROLL_percentageFieldGoalsAttempted2pt_scoring_25,ROLL_percentageFieldGoalsAttempted2pt_scoring_50,ROLL_percentageFieldGoalsAttempted2pt_scoring_100,ROLL_percentageFieldGoalsAttempted2pt_scoring_200,ROLL_percentageFieldGoalsAttempted3pt_scoring_3,ROLL_percentageFieldGoalsAttempted3pt_scoring_5,ROLL_percentageFieldGoalsAttempted3pt_scoring_10,ROLL_percentageFieldGoalsAttempted3pt_scoring_25,ROLL_percentageFieldGoalsAttempted3pt_scoring_50,ROLL_percentageFieldGoalsAttempted3pt_scoring_100,ROLL_percentageFieldGoalsAttempted3pt_scoring_200,ROLL_percentagePoints2pt_scoring_3,ROLL_percentagePoints2pt_scoring_5,ROLL_percentagePoints2pt_scoring_10,ROLL_percentagePoints2pt_scoring_25,ROLL_percentagePoints2pt_scoring_50,ROLL_percentagePoints2pt_scoring_100,ROLL_percentagePoints2pt_scoring_200,ROLL_percentagePointsMidrange2pt_scoring_3,ROLL_percentagePointsMidrange2pt_scoring_5,ROLL_percentagePointsMidrange2pt_scoring_10,ROLL_percentagePointsMidrange2pt_scoring_25,ROLL_percentagePointsMidrange2pt_scoring_50,ROLL_percentagePointsMidrange2pt_scoring_100,ROLL_percentagePointsMidrange2pt_scoring_200,ROLL_percentagePoints3pt_scoring_3,ROLL_percentagePoints3pt_scoring_5,ROLL_percentagePoints3pt_scoring_10,ROLL_percentagePoints3pt_scoring_25,ROLL_percentagePoints3pt_scoring_50,ROLL_percentagePoints3pt_scoring_100,ROLL_percentagePoints3pt_scoring_200,ROLL_percentagePointsFastBreak_scoring_3,ROLL_percentagePointsFastBreak_scoring_5,ROLL_percentagePointsFastBreak_scoring_10,ROLL_percentagePointsFastBreak_scoring_25,ROLL_percentagePointsFastBreak_scoring_50,ROLL_percentagePointsFastBreak_scoring_100,ROLL_percentagePointsFastBreak_scoring_200,ROLL_percentagePointsFreeThrow_scoring_3,ROLL_percentagePointsFreeThrow_scoring_5,ROLL_percentagePointsFreeThrow_scoring_10,ROLL_percentagePointsFreeThrow_scoring_25,ROLL_percentagePointsFreeThrow_scoring_50,ROLL_percentagePointsFreeThrow_scoring_100,ROLL_percentagePointsFreeThrow_scoring_200,ROLL_percentagePointsOffTurnovers_scoring_3,ROLL_percentagePointsOffTurnovers_scoring_5,ROLL_percentagePointsOffTurnovers_scoring_10,ROLL_percentagePointsOffTurnovers_scoring_25,ROLL_percentagePointsOffTurnovers_scoring_50,ROLL_percentagePointsOffTurnovers_scoring_100,ROLL_percentagePointsOffTurnovers_scoring_200,ROLL_percentagePointsPaint_scoring_3,ROLL_percentagePointsPaint_scoring_5,ROLL_percentagePointsPaint_scoring_10,ROLL_percentagePointsPaint_scoring_25,ROLL_percentagePointsPaint_scoring_50,ROLL_percentagePointsPaint_scoring_100,ROLL_percentagePointsPaint_scoring_200,ROLL_percentageAssisted2pt_scoring_3,ROLL_percentageAssisted2pt_scoring_5,ROLL_percentageAssisted2pt_scoring_10,ROLL_percentageAssisted2pt_scoring_25,ROLL_percentageAssisted2pt_scoring_50,ROLL_percentageAssisted2pt_scoring_100,ROLL_percentageAssisted2pt_scoring_200,ROLL_percentageUnassisted2pt_scoring_3,ROLL_percentageUnassisted2pt_scoring_5,ROLL_percentageUnassisted2pt_scoring_10,ROLL_percentageUnassisted2pt_scoring_25,ROLL_percentageUnassisted2pt_scoring_50,ROLL_percentageUnassisted2pt_scoring_100,ROLL_percentageUnassisted2pt_scoring_200,ROLL_percentageAssisted3pt_scoring_3,ROLL_percentageAssisted3pt_scoring_5,ROLL_percentageAssisted3pt_scoring_10,ROLL_percentageAssisted3pt_scoring_25,ROLL_percentageAssisted3pt_scoring_50,ROLL_percentageAssisted3pt_scoring_100,ROLL_percentageAssisted3pt_scoring_200,ROLL_percentageUnassisted3pt_scoring_3,ROLL_percentageUnassisted3pt_scoring_5,ROLL_percentageUnassisted3pt_scoring_10,ROLL_percentageUnassisted3pt_scoring_25,ROLL_percentageUnassisted3pt_scoring_50,ROLL_percentageUnassisted3pt_scoring_100,ROLL_percentageUnassisted3pt_scoring_200,ROLL_percentageAssistedFGM_scoring_3,ROLL_percentageAssistedFGM_scoring_5,ROLL_percentageAssistedFGM_scoring_10,ROLL_percentageAssistedFGM_scoring_25,ROLL_percentageAssistedFGM_scoring_50,ROLL_percentageAssistedFGM_scoring_100,ROLL_percentageAssistedFGM_scoring_200,ROLL_percentageUnassistedFGM_scoring_3,ROLL_percentageUnassistedFGM_scoring_5,ROLL_percentageUnassistedFGM_scoring_10,ROLL_percentageUnassistedFGM_scoring_25,ROLL_percentageUnassistedFGM_scoring_50,ROLL_percentageUnassistedFGM_scoring_100,ROLL_percentageUnassistedFGM_scoring_200,ROLL_threePointersPercentage_traditional_3,ROLL_threePointersPercentage_traditional_5,ROLL_threePointersPercentage_traditional_10,ROLL_threePointersPercentage_traditional_25,ROLL_threePointersPercentage_traditional_50,ROLL_threePointersPercentage_traditional_100,ROLL_threePointersPercentage_traditional_200,ROLL_freeThrowsPercentage_traditional_3,ROLL_freeThrowsPercentage_traditional_5,ROLL_freeThrowsPercentage_traditional_10,ROLL_freeThrowsPercentage_traditional_25,ROLL_freeThrowsPercentage_traditional_50,ROLL_freeThrowsPercentage_traditional_100,ROLL_freeThrowsPercentage_traditional_200,ROLL_percentageFieldGoalsMade_usage_3,ROLL_percentageFieldGoalsMade_usage_5,ROLL_percentageFieldGoalsMade_usage_10,ROLL_percentageFieldGoalsMade_usage_25,ROLL_percentageFieldGoalsMade_usage_50,ROLL_percentageFieldGoalsMade_usage_100,ROLL_percentageFieldGoalsMade_usage_200,ROLL_percentageFieldGoalsAttempted_usage_3,ROLL_percentageFieldGoalsAttempted_usage_5,ROLL_percentageFieldGoalsAttempted_usage_10,ROLL_percentageFieldGoalsAttempted_usage_25,ROLL_percentageFieldGoalsAttempted_usage_50,ROLL_percentageFieldGoalsAttempted_usage_100,ROLL_percentageFieldGoalsAttempted_usage_200,ROLL_percentageThreePointersMade_usage_3,ROLL_percentageThreePointersMade_usage_5,ROLL_percentageThreePointersMade_usage_10,ROLL_percentageThreePointersMade_usage_25,ROLL_percentageThreePointersMade_usage_50,ROLL_percentageThreePointersMade_usage_100,ROLL_percentageThreePointersMade_usage_200,ROLL_percentageThreePointersAttempted_usage_3,ROLL_percentageThreePointersAttempted_usage_5,ROLL_percentageThreePointersAttempted_usage_10,ROLL_percentageThreePointersAttempted_usage_25,ROLL_percentageThreePointersAttempted_usage_50,ROLL_percentageThreePointersAttempted_usage_100,ROLL_percentageThreePointersAttempted_usage_200,ROLL_percentageFreeThrowsMade_usage_3,ROLL_percentageFreeThrowsMade_usage_5,ROLL_percentageFreeThrowsMade_usage_10,ROLL_percentageFreeThrowsMade_usage_25,ROLL_percentageFreeThrowsMade_usage_50,ROLL_percentageFreeThrowsMade_usage_100,ROLL_percentageFreeThrowsMade_usage_200,ROLL_percentageFreeThrowsAttempted_usage_3,ROLL_percentageFreeThrowsAttempted_usage_5,ROLL_percentageFreeThrowsAttempted_usage_10,ROLL_percentageFreeThrowsAttempted_usage_25,ROLL_percentageFreeThrowsAttempted_usage_50,ROLL_percentageFreeThrowsAttempted_usage_100,ROLL_percentageFreeThrowsAttempted_usage_200,ROLL_percentageReboundsOffensive_usage_3,ROLL_percentageReboundsOffensive_usage_5,ROLL_percentageReboundsOffensive_usage_10,ROLL_percentageReboundsOffensive_usage_25,ROLL_percentageReboundsOffensive_usage_50,ROLL_percentageReboundsOffensive_usage_100,ROLL_percentageReboundsOffensive_usage_200,ROLL_percentageReboundsDefensive_usage_3,ROLL_percentageReboundsDefensive_usage_5,ROLL_percentageReboundsDefensive_usage_10,ROLL_percentageReboundsDefensive_usage_25,ROLL_percentageReboundsDefensive_usage_50,ROLL_percentageReboundsDefensive_usage_100,ROLL_percentageReboundsDefensive_usage_200,ROLL_percentageReboundsTotal_usage_3,ROLL_percentageReboundsTotal_usage_5,ROLL_percentageReboundsTotal_usage_10,ROLL_percentageReboundsTotal_usage_25,ROLL_percentageReboundsTotal_usage_50,ROLL_percentageReboundsTotal_usage_100,ROLL_percentageReboundsTotal_usage_200,ROLL_percentageAssists_usage_3,ROLL_percentageAssists_usage_5,ROLL_percentageAssists_usage_10,ROLL_percentageAssists_usage_25,ROLL_percentageAssists_usage_50,ROLL_percentageAssists_usage_100,ROLL_percentageAssists_usage_200,ROLL_percentageTurnovers_usage_3,ROLL_percentageTurnovers_usage_5,ROLL_percentageTurnovers_usage_10,ROLL_percentageTurnovers_usage_25,ROLL_percentageTurnovers_usage_50,ROLL_percentageTurnovers_usage_100,ROLL_percentageTurnovers_usage_200,ROLL_percentageSteals_usage_3,ROLL_percentageSteals_usage_5,ROLL_percentageSteals_usage_10,ROLL_percentageSteals_usage_25,ROLL_percentageSteals_usage_50,ROLL_percentageSteals_usage_100,ROLL_percentageSteals_usage_200,ROLL_percentageBlocks_usage_3,ROLL_percentageBlocks_usage_5,ROLL_percentageBlocks_usage_10,ROLL_percentageBlocks_usage_25,ROLL_percentageBlocks_usage_50,ROLL_percentageBlocks_usage_100,ROLL_percentageBlocks_usage_200,ROLL_percentageBlocksAllowed_usage_3,ROLL_percentageBlocksAllowed_usage_5,ROLL_percentageBlocksAllowed_usage_10,ROLL_percentageBlocksAllowed_usage_25,ROLL_percentageBlocksAllowed_usage_50,ROLL_percentageBlocksAllowed_usage_100,ROLL_percentageBlocksAllowed_usage_200,ROLL_percentagePersonalFouls_usage

In [ ]:
final_cleaned.columns

Index(['GAME_ID', 'GAME_DATE', 'TEAM_ID', 'OPP_TEAM_ID', 'IS_HOME', 'IS_WIN',
       'POINT_DIFF', 'ODDS', 'OPP_ODDS', 'SEASON',
       ...
       'H2H_LAST_200_WINRATE', 'H2H_LAST_200_COUNT', 'H2H_SEASON_WINS',
       'H2H_SEASON_MATCHES', 'H2H_SEASON_WINRATE', 'H2H_WIN_STREAK', 'ELO_PRE',
       'OPP_ELO_PRE', 'ELO_PRE_SEASON', 'OPP_ELO_PRE_SEASON'],
      dtype='object', length=1242)

In [ ]:
#store end time of notebook
end_time = datetime.now()
print("End time: ", end_time)
print("Total time: ", end_time - start_time)

End time:  2025-06-06 19:52:56.379113
Total time:  0:04:54.229970