In [ ]:
import pandas as pd
from datetime import datetime
from src.config import *
from src.utils import *
from src.predictions import build_prediction_rows

pd.set_option("display.max_columns", None)

# ⏱️ Start
start_time = datetime.now()
print("Start time:", start_time)

# 🔁 Charger le dataset complet avec toutes les colonnes nécessaires
dataset_path = get_latest_file(DATA_FINAL_DATASET_DIR)
full_df = pd.read_csv(dataset_path)
full_df["GAME_DATE"] = pd.to_datetime(full_df["GAME_DATE"])
print("Loaded dataset:", dataset_path)


# 🧪 Extraction des deux dernières lignes (réelles)
real_last_rows = full_df.sort_values("GAME_DATE").tail(2).copy()
real_match_date = real_last_rows["GAME_DATE"].iloc[0]

home_id = real_last_rows.loc[real_last_rows["IS_HOME"] == 1, "TEAM_ID"].values[0]
away_id = real_last_rows.loc[real_last_rows["IS_HOME"] == 0, "TEAM_ID"].values[0]
home_odds = real_last_rows.loc[real_last_rows["IS_HOME"] == 1, "ODDS"].values[0]
away_odds = real_last_rows.loc[real_last_rows["IS_HOME"] == 0, "ODDS"].values[0]


print(f"Match: HOME={home_id}, AWAY={away_id}, Date={real_match_date.date()}")

# 🧼 Dataset sans ces lignes
cut_df = full_df[full_df["GAME_DATE"] < real_match_date].copy()

display(cut_df.tail(10))

# 🔁 Reconstruction des lignes à prédire
predicted_rows = build_prediction_rows(home_team_id=home_id, away_team_id=away_id, home_odds=home_odds, <<away_odds=away_odds, dataset=cut_df, match_date=real_match_date)

# 🧹 Préparation des lignes pour comparaison
drop_cols = ['TEAM_ID','OPP_TEAM_ID','SEASON','GAME_DATE','IS_WIN']


real_clean = real_last_rows.drop(columns=drop_cols, errors='ignore').drop(columns=COLS_MATCH_REAL, errors='ignore').reset_index(drop=True)
pred_clean = predicted_rows.drop(columns=drop_cols, errors='ignore').drop(columns=COLS_MATCH_REAL, errors='ignore').reset_index(drop=True)

# 📏 Alignement des colonnes
common_cols = [col for col in real_clean.columns if col in pred_clean.columns]
real_clean = real_clean[common_cols]
pred_clean = pred_clean[common_cols]

# 🔍 Comparaison
diff = (real_clean != pred_clean).sum()
diff_summary = diff[diff > 0]
print(f"\nNombre de colonnes différentes : {len(diff_summary)}")
print("Colonnes divergentes :", diff_summary.index.tolist())

print("\nLigne prédite:")
display(pred_clean)
print("\nLigne réelle:")
display(real_clean)

# 🕒 Fin
end_time = datetime.now()
print("End time:", end_time)
print("Duration:", end_time - start_time)

Start time: 2025-05-30 01:20:51.669574
Loaded dataset: data/final_dataset/nba_features_final_2025-05-30_00-04-22.csv
Match: HOME=1610612752, AWAY=1610612754, Date=2025-05-23

,GAME_ID,TEAM_ID,GAME_DATE,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS,MINUTES_PLAYED,OPP_TEAM_ID,OPP_GAME_DATE,OPP_FGM,OPP_FGA,OPP_FG_PCT,OPP_FG3M,OPP_FG3A,OPP_FG3_PCT,OPP_FTM,OPP_FTA,OPP_FT_PCT,OPP_OREB,OPP_DREB,OPP_REB,OPP_AST,OPP_STL,OPP_BLK,OPP_TO,OPP_PF,OPP_PTS,OPP_PLUS_MINUS,OPP_MINUTES_PLAYED,MATCHUP,SEASON,IS_HOME,IS_WIN,POINT_DIFF,TEAM_NAME,OPPONENT_NAME,ODDS,OPP_ODDS,TS_PCT,EFG_PCT,AST_TO_RATIO,REB_RATE,POSSESSIONS,OPP_POSSESSIONS,OFF_RATING,DEF_RATING,ROLL_PTS_3,ROLL_PTS_5,ROLL_PTS_10,ROLL_PTS_25,ROLL_PTS_50,ROLL_PTS_100,ROLL_PTS_200,ROLL_REB_3,ROLL_REB_5,ROLL_REB_10,ROLL_REB_25,ROLL_REB_50,ROLL_REB_100,ROLL_REB_200,ROLL_AST_3,ROLL_AST_5,ROLL_AST_10,ROLL_AST_25,ROLL_AST_50,ROLL_AST_100,ROLL_AST_200,ROLL_FGM_3,ROLL_FGM_5,ROLL_FGM_10,ROLL_FGM_25,ROLL_FGM_50,ROLL_FGM_100,ROLL_FGM_200,ROLL_FGA_3,ROLL_FGA_5,ROLL_FGA_10,ROLL_FGA_25,ROLL_FGA_50,ROLL_FGA_100,ROLL_FGA_200,ROLL_FG_PCT_3,ROLL_FG_PCT_5,ROLL_FG_PCT_10,ROLL_FG_PCT_25,ROLL_FG_PCT_50,ROLL_FG_PCT_100,ROLL_FG_PCT_200,ROLL_PLUS_MINUS_3,ROLL_PLUS_MINUS_5,ROLL_PLUS_MINUS_10,ROLL_PLUS_MINUS_25,ROLL_PLUS_MINUS_50,ROLL_PLUS_MINUS_100,ROLL_PLUS_MINUS_200,ROLL_TS_PCT_3,ROLL_TS_PCT_5,ROLL_TS_PCT_10,ROLL_TS_PCT_25,ROLL_TS_PCT_50,ROLL_TS_PCT_100,ROLL_TS_PCT_200,ROLL_EFG_PCT_3,ROLL_EFG_PCT_5,ROLL_EFG_PCT_10,ROLL_EFG_PCT_25,ROLL_EFG_PCT_50,ROLL_EFG_PCT_100,ROLL_EFG_PCT_200,ROLL_AST_TO_RATIO_3,ROLL_AST_TO_RATIO_5,ROLL_AST_TO_RATIO_10,ROLL_AST_TO_RATIO_25,ROLL_AST_TO_RATIO_50,ROLL_AST_TO_RATIO_100,ROLL_AST_TO_RATIO_200,ROLL_REB_RATE_3,ROLL_REB_RATE_5,ROLL_REB_RATE_10,ROLL_REB_RATE_25,ROLL_REB_RATE_50,ROLL_REB_RATE_100,ROLL_REB_RATE_200,ROLL_POSSESSIONS_3,ROLL_POSSESSIONS_5,ROLL_POSSESSIONS_10,ROLL_POSSESSIONS_25,ROLL_POSSESSIONS_50,ROLL_POSSESSIONS_100,ROLL_POSSESSIONS_200,ROLL_OPP_POSSESSIONS_3,ROLL_OPP_POSSESSIONS_5,ROLL_OPP_POSSESSIONS_10,ROLL_OPP_POSSESSIONS_25,ROLL_OPP_POSSESSIONS_50,ROLL_OPP_POSSESSIONS_100,ROLL_OPP_POSSESSIONS_200,ROLL_OFF_RATING_3,ROLL_OFF_RATING_5,ROLL_OFF_RATING_10,ROLL_OFF_RATING_25,ROLL_OFF_RATING_50,ROLL_OFF_RATING_100,ROLL_OFF_RATING_200,ROLL_DEF_RATING_3,ROLL_DEF_RATING_5,ROLL_DEF_RATING_10,ROLL_DEF_RATING_25,ROLL_DEF_RATING_50,ROLL_DEF_RATING_100,ROLL_DEF_RATING_200,ROLL_HOME_WINRATE_3,ROLL_AWAY_WINRATE_3,ROLL_HOME_WINRATE_5,ROLL_AWAY_WINRATE_5,ROLL_HOME_WINRATE_10,ROLL_AWAY_WINRATE_10,ROLL_HOME_WINRATE_25,ROLL_AWAY_WINRATE_25,ROLL_HOME_WINRATE_50,ROLL_AWAY_WINRATE_50,ROLL_HOME_WINRATE_100,ROLL_AWAY_WINRATE_100,ROLL_HOME_WINRATE_200,ROLL_AWAY_WINRATE_200,ROLL_WIN_RATIO_3,ROLL_WIN_RATIO_5,ROLL_WIN_RATIO_10,ROLL_WIN_RATIO_25,ROLL_WIN_RATIO_50,ROLL_WIN_RATIO_100,ROLL_WIN_RATIO_200,WIN_STREAK,HOME_WIN_STREAK,AWAY_WIN_STREAK,DAYS_SINCE_LAST_GAME,OPP_DAYS_SINCE_LAST_GAME,REST_ADVANTAGE,ROLL_HOME_REST_ADV_3,ROLL_AWAY_REST_ADV_3,ROLL_HOME_REST_ADV_5,ROLL_AWAY_REST_ADV_5,ROLL_HOME_REST_ADV_10,ROLL_AWAY_REST_ADV_10,ROLL_HOME_REST_ADV_25,ROLL_AWAY_REST_ADV_25,ROLL_HOME_REST_ADV_50,ROLL_AWAY_REST_ADV_50,ROLL_HOME_REST_ADV_100,ROLL_AWAY_REST_ADV_100,ROLL_HOME_REST_ADV_200,ROLL_AWAY_REST_ADV_200,ROLL_HOME_PTS_FOR_3,ROLL_HOME_OPP_PTS_AGAINST_3,ROLL_AWAY_PTS_FOR_3,ROLL_AWAY_OPP_PTS_AGAINST_3,ROLL_HOME_PTS_FOR_5,ROLL_HOME_OPP_PTS_AGAINST_5,ROLL_AWAY_PTS_FOR_5,ROLL_AWAY_OPP_PTS_AGAINST_5,ROLL_HOME_PTS_FOR_10,ROLL_HOME_OPP_PTS_AGAINST_10,ROLL_AWAY_PTS_FOR_10,ROLL_AWAY_OPP_PTS_AGAINST_10,ROLL_HOME_PTS_FOR_25,ROLL_HOME_OPP_PTS_AGAINST_25,ROLL_AWAY_PTS_FOR_25,ROLL_AWAY_OPP_PTS_AGAINST_25,ROLL_HOME_PTS_FOR_50,ROLL_HOME_OPP_PTS_AGAINST_50,ROLL_AWAY_PTS_FOR_50,ROLL_AWAY_OPP_PTS_AGAINST_50,ROLL_HOME_PTS_FOR_100,ROLL_HOME_OPP_PTS_AGAINST_100,ROLL_AWAY_PTS_FOR_100,ROLL_AWAY_OPP_PTS_AGAINST_100,ROLL_HOME_PTS_FOR_200,ROLL_HOME_OPP_PTS_AGAINST_200,ROLL_AWAY_PTS_FOR_200,ROLL_AWAY_OPP_PTS_AGAINST_200,H2H_LAST_3_DIFF,H2H_LAST_3_WINRATE,H2H_LAST_3_COUNT,H2H_LAST_5_DIFF,H2H_LAST_5_WINRATE,H2H_LAST_5_COUNT,H2H_LAST_10_DIFF,H2H_LAST_10_WINRATE,H2H_LAST_10_COUNT,H2H_LAST_25_DIFF,H2H_LAST_25_WINRATE,H2H_LAST_25_COUNT,H2H_LAST_50_DIFF,H2H_LAST_50_WINRATE,H2H_LAST_50_COUNT,H2H_LAST_100_DIFF,H2H_LAST_100_WINRATE,H2H_LAST_100_COUNT,H2H_LAST_200_DIFF,H2H_LAST_200_WINRATE,H2H_LAST_200_COUNT,H2H_SEASON_WINS,H2H_SEASON_MATCHES,H2H_SEASON_WINRATE,H2H_WIN_STREAK,ELO_PRE,OPP_ELO_PRE,ELO_PRE_SEASON,OPP_ELO_PRE_SEASON
38003,42400216,1610612738,2025-05-16,62.0,172.0,9.404,24.0,80.0,6.732,14.0,20.0,9.000,18.0,54.0,72.0,38.0,8.0,6.0,30.0,44.0,162.0,-380.0,0.0,1610612752,2025-05-16,84.0,182.0,8.478,32.0,90.0,6.500,38.0,42.0,10.500,30.0,80.0,110.0,50.0,14.0,12.0,28.0,46.0,238.0,380.0,0.0,BOS @ NYK,2024-25,0.0,0.0,-76.0,boston celtics,new york knicks,2.15,1.69,0.448009,0.430233,1.266667,0.395604,192.80,198.48,84.024896,119.911326,237.029109,229.253204,222.689927,222.817129,225.701301,230.617332,236.780709,82.622616,84.477089,87.247239,89.498260,90.028163,90.845742,92.591676,44.976724,43.137285,43.165949,46.600949,48.994188,50.852507,52.457336,81.793624,79.259326,77.540530,78.790405,80.468372,82.610869,85.085801,166.875171,167.713787,168.641566,171.605812,174.338569,177.682819,181.537875,9.780087,9.116592,8.677831,8.647338,8.712540,8.876660,9.149938,136.707221,113.931124,98.204328,91.866008,89.560939,90.827979,91.069342,0.631117,0.611144,0.593444,0.588412,0.589735,0.592261,0.594535,0.608785,0.582535,0.559383,0.554423,0.557378,0.560749,0.562716,2.535510,2.289587,2.136675,2.247493,2.406441,2.538467,2.558670,0.493828,0.495286,0.503545,0.513161,0.513781,0.512663,0.512195,185.592313,186.908206,187.986064,189.197893,191.166135,195.005858,200.613806,191.169462,190.488003,189.813748,190.161219,191.964717,195.662809,201.152967,128.191117,123.280823,119.025304,118.146521,118.381578,118.567320,118.348586,109.629738,108.311919,106.921279,107.541115,108.315604,108.688871,108.804160,1.0,0.5,0.333333,0.500000,0.666667,0.500000,0.636364,0.785714,0.666667,0.807692,0.705882,0.775510,0.757282,0.742268,0.666667,0.4,0.6,0.72,0.74,0.74,0.750,1,0,2,2.0,2.0,0.0,0.0,0.0,-7.000000,0.000000,-3.5,0.000000,-19.909091,-64.214286,-66.583333,-77.692308,-102.843137,-95.183673,-96.417476,-108.742268,254.0,204.0,228.0,214.0,214.666667,200.666667,228.000000,214.000000,218.0,192.0,214.000000,203.500000,221.818182,201.272727,224.857143,207.142857,228.833333,210.583333,226.769231,208.769231,231.960784,213.333333,227.632653,212.040816,252.504854,227.631068,250.391753,234.536082,1,0.666667,3,-1,0.4,5,2,0.6,10,3,0.56,25,14,0.64,50,19,0.630137,73,19,0.630137,73,6,9,0.666667,1,1689.717618,1626.246375,1665.309275,1619.417530
38004,42400216,1610612752,2025-05-16,84.0,182.0,8.478,32.0,90.0,6.500,38.0,42.0,10.500,30.0,80.0,110.0,50.0,14.0,12.0,28.0,46.0,238.0,380.0,0.0,1610612738,2025-05-16,62.0,172.0,9.404,24.0,80.0,6.732,14.0,20.0,9.000,18.0,54.0,72.0,38.0,8.0,6.0,30.0,44.0,162.0,-380.0,0.0,NYK vs. BOS,2024-25,1.0,1.0,76.0,new york knicks,boston celtics,1.69,2.15,0.593575,0.549451,1.785714,0.604396,198.48,192.80,119.911326,84.024896,210.720708,210.169854,211.688765,217.243751,222.496817,227.645635,231.566123,83.771631,85.256111,85.626469,85.031514,85.119771,86.614084,89.635839,38.238407,38.656743,40.540042,45.863847,49.327478,51.095454,51.058659,71.407864,73.634839,76.197264,80.111432,82.768243,84.633949,85.530410,168.665527,170.171081,172.060564,174.942452,176.983900,179.007494,181.522089,7.473171,7.399288,7.303618,7.702966,8.058678,8.307026,8.575651,-130.609991,-93.610975,-49.249054,-8.869192,9.342289,23.511519,29.748184,0.540460,0.540311,0.544752,0.557403,0.567355,0.574908,0.576026,0.484621,0.492825,0.504342,0.521812,0.533239,0.541231,0.542051,1.726076,1.687872,1.739269,1.975117,2.157329,2.266886,2.257202,0.506464,0.505624,0.501316,0.498728,0.499841,0.504886,0.511226,191.586058,192.059417,193.616193,196.057559,197.756041,199.521787,202.241640,186.125704,188.899096,192.528364,195.646072,197.166332,198.750586,201.515252,109.935174,109.360268,109.252754,110.714347,112.417864,114.045288,114.514973,127.785615,121.937594,115.773610,112.365849,112.170170,112.382400,112.161813,0.5,0.0,0.500000,0.666667,0.250000,0.833333,0.615385,0.583333,0.615385,0.625000,0.653061,0.588235,0.670000,0.570000,0.333333,0.6,0.6,0.60,0.62,0.62,0.620,0,0,3,2.0,2.0,0.0,0.0,0.0,0.000000,-7.666667,0.0,-3.833333,-41.307692,-31.500000,-91.730769,-74.083333,-97.816327,-106.588235,-93.470000,-117.570000,214.0,228.0,204.0,254.0,214.000000,228.000000,200.666667,214.666667,205.5,217.0,209.666667,214.666667,224.153846,212.923077,211.333333,218.666667,232.000000,225.153846,219.333333,223.000000,234.204082,222.163265,224.000000,224.313725,243.500000,230.060000,239.980000,237.020000,-1,0.333333,3,1,0.6,5,-2,0.4,10,-3,0.44,25,-14,0.36,50,-19,0.369863,73,-19,0.369863,73,3,9,0.333333,0,1626.246375,1689.717618,1619.417530,1665.309275
38005,42400227,1610612743,2025-05-18,66.0,168.0,8.318,20.0,88.0,5.016,34.0,44.0,6.136,30.0,64.0,94.0,40.0,12.0,4.0,44.0,38.0,186.0,-320.0,0.0,1610612760,2025-05-18,94.0,192.0,11.902,24.0,78.0,8.200,38.0,48.0,8.778,30.0,58.0,88.0,56.0,32.0,6.0,18.0,38.0,250.0,320.0,0.0,DEN @ OKC,2024-25,0.0,0.0,-64.0,denver nuggets,oklahoma city thunder,3.55,1.31,0.496371,0.452381,0.909091,0.516484,201.36,201.12,92.371871,124.303898,221.373019,218.505729,219.006147,224.872010,230.612752,234.969371,238.256805,100.566029,98.720186,95.896939,93.046617,92.075655,91.995806,92.498320,46.837011,45.241047,45.966814,50.931100,55.016696,57.878347,59.364344,75.912920,75.307914,77.094347,81.676808,85.267143,87.875803,89.590357,176.257543,175.901745,175.041274,175.179916,176.542728,178.751338,181.458736,6.397299,6.654179,7.191203,7.901620,8.463993,8.984756,9.443161,30.162500,3.118198,-13.780128,-11.431148,3.883496,19.689574,29.638588,0.553168,0.548527,0.555072,0.572936,0.585839,0.592184,0.593475,0.500912,0.498833,0.511008,0.536103,0.552428,0.560563,0.562594,1.649994,1.603956,1.692015,1.982336,2.226277,2.404686,2.482576,0.536575,0.526768,0.521447,0.519249,0.519280,0.518572,0.517343,204.320067,203.738768,202.220504,201.452943,201.894139,203.271647,205.695125,202.805723,202.487375,201.240405,200.770566,201.612838,203.349600,205.856775,108.210997,107.145823,108.272799,111.597741,114.198736,115.612175,115.927606,106.193847,107.602522,110.260037,113.244651,114.109096,113.739890,112.989161,0.5,0.0,0.666667,0.000000,0.800000,0.400000,0.538462,0.416667,0.653846,0.458333,0.607843,0.551020,0.712871,0.575758,0.333333,0.4,0.6,0.48,0.56,0.58,0.645,1,0,1,3.0,3.0,0.0,0.0,0.0,0.000000,0.000000,0.0,-10.800000,-30.692308,-25.583333,-33.307692,-96.583333,-88.764706,-116.265306,-90.782178,-111.575758,206.0,199.0,210.0,224.0,212.666667,202.000000,211.000000,261.000000,228.0,207.6,215.200000,236.000000,234.461538,223.230769,216.000000,234.166667,242.923077,230.000000,226.333333,237.666667,238.470588,228.666667,231.265306,232.326531,252.871287,237.366337,244.323232,244.282828,-1,0.333333,3,-1,0.4,5,0,0.5,10,3,0.56,25,2,0.52,50,-4,0.470588,68,-4,0.470588,68,5,10,0.500000,1,1627.824002,1756.460648,1611.656178,1736.362225
38006,42400227,1610612760,2025-05-18,94.0,192.0,11.902,24.0,78.0,8.200,38.0,48.0,8.778,30.0,58.0,88.0,56.0,32.0,6.0,18.0,38.0,250.0,320.0,0.0,1610612743,2025-05-18,66.0,168.0,8.318,20.0,88.0,5.016,34.0,44.0,6.136,30.0,64.0,94.0,40.0,12.0,4.0,44.0,38.0,186.0,-320.0,0.0,OKC vs. DEN,2024-25,1.0,1.0,64.0,oklahoma city thunder,denver nuggets,1.31,3.55,0.586524,0.552083,3.111111,0.483516,201.12,201.36,124.303898,92.371871,215.708562,219.876176,227.882662,237.324961,240.647633,242.037448,242.937763,87.347986,89.736446,90.528449,90.454688,90.319797,90.044280,90.387734,48.012340,48.266691,49.464358,51.810529,53.061438,53.695945,53.624302,81.995905,81.787678,83.525629,86.764071,88.289578,89.185059,89.637011,179.356971,181.084695,183.875231,185.394823,185.473226,185.962649,187.370038,9.252091,9.281073,9.401456,9.547168,9.653745,9.843920,10.007456,-27.417045,11.275339,56.624013,96.806684,111.396470,109.730413,87.596878,0.548183,0.549023,0.557594,0.577095,0.587109,0.590341,0.587511,0.521336,0.517036,0.522400,0.542114,0.552902,0.556498,0.553336,2.057573,2.140893,2.335265,2.553454,2.633599,2.617541,2.498843,0.463432,0.474383,0.485119,0.497975,0.502210,0.499531,0.494619,203.026866,203.802183,205.134347,205.697282,205.253292,206.174981,209.198823,204.529590,204.953782,205.680551,205.582381,205.086758,206.287723,209.528615,106.247244,107.815703,110.968193,115.280084,117.176571,117.340322,116.060267,108.005489,106.051686,105.246449,106.105153,106.598041,106.811010,107.684316,1.0,0.5,1.000000,0.333333,0.800000,0.600000,0.846154,0.750000,0.814815,0.739130,0.826923,0.750000,0.806122,0.647059,0.666667,0.6,0.7,0.80,0.78,0.79,0.725,0,0,1,3.0,3.0,0.0,0.0,0.0,0.000000,0.000000,-12.0,0.000000,-46.846154,-61.083333,-70.592593,-57.043478,-110.096154,-97.083333,-122.581633,-97.480392,224.0,210.0,199.0,206.0,261.000000,211.000000,202.000000,212.666667,251.6,204.4,213.600000,216.800000,255.230769,215.076923,224.333333,218.166667,254.222222,218.592593,233.652174,223.652174,244.000000,212.115385,230.333333,214.166667,264.755102,236.346939,244.392157,235.078431,1,0.666667,3,1,0.6,5,0,0.5,10,-3,0.44,25,-2,0.48,50,4,0.529412,68,4,0.529412,68,5,10,0.500000,0,1756.460648,1627.824002,1736.362225,1611.656178
38007,42400311,1610612750,2025-05-20,116.0,332.0,15.352,60.0,204.0,8.852,60.0,84.0,16.188,48.0,120.0,168.0,72.0,20.0,28.0,68.0,88.0,352.0,-520.0,0.0,1610612760,2025-05-20,164.0,328.0,26.368,44.0,84.0,22.664,84.0,104.0,13.144,36.0,148.0,184.0,108.0,52.0,12.0,48.0,88.0,456.0,520.0,0.0,MIN @ OKC,2024-25,0.0,0.0,-104.0,minnesota timberwolves,oklahoma city thunder,3.26,1.36,0.477016,0.439759,1.058824,0.477273,388.96,385.76,90.497738,118.208212,231.836830,226.104550,222.583256,226.168018,228.089130,229.178464,232.511389,79.493750,81.353749,84.005660,86.599492,87.613996,88.341124,89.358580,60.738770,57.112483,53.752295,53.046769,52.981323,52.966222,53.473508,87.472015,83.954045,81.812230,82.498226,82.662051,82.825798,84.119119,159.795170,163.148352,167.811834,173.029252,174.834691,175.709535,177.969923,8.858201,8.437678,8.226026,8.615574,8.812881,9.001936,9.324966,92.153900,83.735528,74.964946,72.590697,66.208153,57.480454,47.799976,0.658507,0.627497,0.599144,0.589693,0.588619,0.587908,0.587338,0.634881,0.598649,0.566877,0.556536,0.554907,0.553927,0.553239,1.663742,1.732893,1.877601,2.098796,2.174071,2.162733,2.123459,0.502011,0.505648,0.511186,0.513906,0.512001,0.509720,0.506322,198.579713,197.463340,196.205965,197.155370,198.100368,199.877220,204.226863,198.602084,194.867248,191.956476,193.575674,195.779521,198.640473,203.723299,116.751027,114.473910,113.409153,114.728240,115.223188,114.787433,113.984829,107.426698,107.440768,108.158054,109.301778,109.733328,109.666352,109.608295,1.0,1.0,0.666667,1.000000,0.800000,0.800000,0.769231,0.750000,0.653846,0.666667,0.560000,0.600000,0.636364,0.603960,1.000000,0.8,0.8,0.76,0.66,0.58,0.620,4,1,5,6.0,85.0,-79.0,0.0,0.0,-35.000000,0.000000,-21.0,-8.000000,-61.307692,-58.666667,-91.307692,-59.625000,-107.320000,-95.660000,-105.000000,-104.841584,242.0,220.0,219.0,207.0,217.333333,201.333333,219.000000,207.000000,223.2,207.6,209.600000,196.800000,241.692308,217.384615,218.333333,209.666667,237.461538,218.153846,226.500000,218.166667,227.960000,216.840000,220.880000,214.880000,244.525253,229.151515,239.920792,233.009901,1,0.666667,3,1,0.6,5,2,0.6,10,3,0.56,25,-4,0.46,50,-10,0.413793,58,-10,0.413793,58,2,4,0.500000,1,1663.936260,1763.977960,1650.071781,1743.993270
38008,42400311,1610612760,2025-05-20,164.0,328.0,26.368,44.0,84.0,22.664,84.0,104.0,13.144,36.0,148.0,184.0,108.0,52.0,12.0,48.0,88.0,456.0,520.0,0.0,1610612750,2025-05-20,116.0,332.0,15.352,60.0,204.0,8.852,60.0,84.0,16.188,48.0,120.0,168.0,72.0,20.0,28.0,68.0,88.0,352.0,-520.0,0.0,OKC vs. MIN,2024-25,1.0,1.0,104.0,oklahoma city thunder,minnesota timberwolves,1.36,3.26,0.610017,0.567073,2.250000,0.522727,385.76,388.96,118.208212,90.497738,232.854281,229.917451,231.903996,238.299964,241.014393,242.195122,243.008034,87.673993,89.157631,90.068731,90.265866,90.228825,90.003800,90.363976,52.006170,50.844461,50.652657,52.132796,53.176675,53.741570,53.647941,87.997952,85.858452,85.430060,87.320681,88.513516,89.280404,89.680424,185.678486,184.723130,185.352462,185.902914,185.729178,186.082201,187.416107,10.577045,10.154715,9.856100,9.728309,9.741911,9.884675,10.026307,146.291477,114.183559,104.510556,113.975401,119.577000,113.894167,89.909351,0.567353,0.561523,0.562854,0.577820,0.587086,0.590265,0.587501,0.536710,0.528719,0.527797,0.542881,0.552870,0.556410,0.553323,2.584342,2.464299,2.476328,2.596351,2.652325,2.627315,2.504935,0.473474,0.477427,0.484828,0.496863,0.501477,0.499214,0.494509,202.073433,202.908122,204.404466,205.345183,205.091202,206.074882,209.118437,202.944795,203.755855,204.894996,205.257582,204.940611,206.190144,209.447335,115.275571,113.311768,113.392867,115.974223,117.456074,117.478215,116.142293,100.188680,101.491747,102.905616,105.048747,106.040152,106.525086,107.531953,1.0,0.0,1.000000,0.333333,0.800000,0.600000,0.857143,0.727273,0.821429,0.772727,0.826923,0.750000,0.806122,0.647059,0.666667,0.6,0.7,0.80,0.80,0.79,0.725,1,1,1,2.0,85.0,-83.0,0.0,0.0,0.000000,0.000000,-9.4,0.000000,-43.500000,-60.818182,-68.071429,-56.909091,-109.769231,-97.083333,-122.306122,-97.480392,237.0,198.0,214.0,238.0,237.000000,198.000000,202.000000,212.666667,249.2,209.6,213.600000,216.800000,254.857143,213.000000,223.272727,217.636364,254.071429,217.428571,235.363636,224.181818,244.000000,211.576923,230.333333,214.166667,264.510204,235.632653,244.392157,235.078431,-1,0.333333,3,-1,0.4,5,-2,0.4,10,-3,0.44,25,4,0.54,50,10,0.586207,58,10,0.586207,58,2,4,0.500000,0,1763.977960,1663.936260,1743.993270,1650.071781
38009,42400301,1610612752,2025-05-21,192.0,376.0,16.876,44.0,136.0,7.932,112.0,160.0,13.900,52.0,132.0,184.0,96.0,28.0,32.0,60.0,92.0,540.0,-60.0,0.0,1610612754,2025-05-21,204.0,400.0,17.672,60.0,148.0,8.556,84.0,112.0,23.400,44.0,112.0,156.0,104.0,24.0,12.0,28.0,96.0,552.0,60.0,0.0,NYK vs. IND,2024-25,1.0,0.0,-12.0,new york knicks,indiana pacers,1.53,2.51,0.604839,0.569149,1.600000,0.541176,454.40,433.28,118.838028,127.400295,224.360354,219.446569,216.472626,218.840386,223.104785,227.850672,231.630142,96.885816,93.504074,90.058020,86.952167,86.095467,87.077171,89.838468,44.119203,42.437828,42.260034,46.182012,49.353851,51.073762,51.048125,77.703932,77.089893,77.615943,80.410553,82.816548,84.621396,85.515182,175.332764,174.114054,173.867734,175.485341,177.180610,179.066751,181.526845,7.975586,7.758858,7.517142,7.762584,8.075122,8.310411,8.574680,124.695004,64.259350,28.796229,21.043823,23.877886,30.570697,33.233291,0.567017,0.558066,0.553629,0.560186,0.568383,0.575278,0.576201,0.517036,0.511700,0.512543,0.523938,0.533875,0.541394,0.542124,1.755895,1.720486,1.747713,1.960547,2.142756,2.257358,2.252510,0.555430,0.538548,0.520058,0.506856,0.503941,0.506857,0.512153,195.033029,194.199611,194.500522,196.243900,197.784432,199.501157,202.204211,189.462852,190.199397,192.577753,195.427144,196.995103,198.632752,201.428532,114.923250,112.877287,111.190676,111.421807,112.711725,114.161447,114.568669,105.905256,109.300028,110.001117,110.185775,111.066434,111.820865,111.881843,1.0,0.0,0.666667,0.500000,0.500000,0.833333,0.642857,0.636364,0.653846,0.625000,0.660000,0.600000,0.670000,0.570000,0.666667,0.6,0.7,0.64,0.64,0.63,0.620,1,1,3,5.0,99.0,-94.0,0.0,0.0,0.000000,0.000000,0.0,-3.833333,-38.357143,-33.636364,-90.346154,-74.083333,-95.860000,-108.720000,-93.420000,-117.570000,240.0,194.0,204.0,254.0,222.000000,206.000000,193.000000,217.000000,218.0,207.5,209.666667,214.666667,225.142857,209.285714,213.454545,220.909091,232.000000,221.846154,219.333333,223.000000,234.280000,220.960000,223.920000,223.800000,243.860000,229.840000,239.980000,237.020000,1,0.666667,3,-1,0.4,5,0,0.5,10,1,0.52,25,-10,0.40,50,-11,0.415385,65,-11,0.415385,65,2,3,0.666667,1,1639.937904,1669.492929,1632.530472,1665.843449

Nombre de colonnes différentes : 121
Colonnes divergentes : ['GAME_ID', 'ROLL_PTS_3', 'ROLL_PTS_5', 'ROLL_PTS_10', 'ROLL_PTS_25', 'ROLL_PTS_50', 'ROLL_PTS_100', 'ROLL_PTS_200', 'ROLL_REB_3', 'ROLL_REB_5', 'ROLL_REB_10', 'ROLL_REB_25', 'ROLL_REB_50', 'ROLL_REB_100', 'ROLL_REB_200', 'ROLL_AST_3', 'ROLL_AST_5', 'ROLL_AST_10', 'ROLL_AST_25', 'ROLL_AST_50', 'ROLL_AST_100', 'ROLL_AST_200', 'ROLL_FGM_3', 'ROLL_FGM_5', 'ROLL_FGM_10', 'ROLL_FGM_25', 'ROLL_FGM_50', 'ROLL_FGM_100', 'ROLL_FGM_200', 'ROLL_FGA_3', 'ROLL_FGA_5', 'ROLL_FGA_10', 'ROLL_FGA_25', 'ROLL_FGA_50', 'ROLL_FGA_100', 'ROLL_FGA_200', 'ROLL_FG_PCT_3', 'ROLL_FG_PCT_5', 'ROLL_FG_PCT_10', 'ROLL_FG_PCT_25', 'ROLL_FG_PCT_50', 'ROLL_FG_PCT_100', 'ROLL_FG_PCT_200', 'ROLL_PLUS_MINUS_3', 'ROLL_PLUS_MINUS_5', 'ROLL_PLUS_MINUS_10', 'ROLL_PLUS_MINUS_25', 'ROLL_PLUS_MINUS_50', 'ROLL_PLUS_MINUS_100', 'ROLL_PLUS_MINUS_200', 'ROLL_TS_PCT_3', 'ROLL_TS_PCT_5', 'ROLL_TS_PCT_10', 'ROLL_TS_PCT_25', 'ROLL_TS_PCT_50', 'ROLL_TS_PCT_100', 'ROLL_TS_PCT_200', 'ROLL_EFG_PCT_3', 'ROLL_EFG_PCT_5', 'ROLL_EFG_PCT_10', 'ROLL_EFG_PCT_25', 'ROLL_EFG_PCT_50', 'ROLL_EFG_PCT_100', 'ROLL_EFG_PCT_200', 'ROLL_AST_TO_RATIO_3', 'ROLL_AST_TO_RATIO_5', 'ROLL_AST_TO_RATIO_10', 'ROLL_AST_TO_RATIO_25', 'ROLL_AST_TO_RATIO_50', 'ROLL_AST_TO_RATIO_100', 'ROLL_AST_TO_RATIO_200', 'ROLL_REB_RATE_3', 'ROLL_REB_RATE_5', 'ROLL_REB_RATE_10', 'ROLL_REB_RATE_25', 'ROLL_REB_RATE_50', 'ROLL_REB_RATE_100', 'ROLL_REB_RATE_200', 'ROLL_POSSESSIONS_3', 'ROLL_POSSESSIONS_5', 'ROLL_POSSESSIONS_10', 'ROLL_POSSESSIONS_25', 'ROLL_POSSESSIONS_50', 'ROLL_POSSESSIONS_100', 'ROLL_POSSESSIONS_200', 'ROLL_OPP_POSSESSIONS_3', 'ROLL_OPP_POSSESSIONS_5', 'ROLL_OPP_POSSESSIONS_10', 'ROLL_OPP_POSSESSIONS_25', 'ROLL_OPP_POSSESSIONS_50', 'ROLL_OPP_POSSESSIONS_100', 'ROLL_OPP_POSSESSIONS_200', 'ROLL_OFF_RATING_3', 'ROLL_OFF_RATING_5', 'ROLL_OFF_RATING_10', 'ROLL_OFF_RATING_25', 'ROLL_OFF_RATING_50', 'ROLL_OFF_RATING_100', 'ROLL_OFF_RATING_200', 'ROLL_DEF_RATING_3', 'ROLL_DEF_RATING_5', 'ROLL_DEF_RATING_10', 'ROLL_DEF_RATING_25', 'ROLL_DEF_RATING_50', 'ROLL_DEF_RATING_100', 'ROLL_DEF_RATING_200', 'ROLL_AWAY_WINRATE_200', 'ROLL_AWAY_REST_ADV_5', 'ROLL_AWAY_REST_ADV_10', 'ROLL_AWAY_REST_ADV_50', 'ROLL_HOME_REST_ADV_100', 'ROLL_HOME_REST_ADV_200', 'ROLL_HOME_PTS_FOR_25', 'ROLL_HOME_OPP_PTS_AGAINST_25', 'ROLL_HOME_PTS_FOR_50', 'ROLL_AWAY_PTS_FOR_50', 'ROLL_HOME_PTS_FOR_100', 'ROLL_AWAY_PTS_FOR_100', 'ROLL_HOME_PTS_FOR_200', 'ROLL_HOME_OPP_PTS_AGAINST_200', 'ROLL_AWAY_PTS_FOR_200']

Ligne prédite:

,GAME_ID,IS_HOME,ODDS,OPP_ODDS,ROLL_PTS_3,ROLL_PTS_5,ROLL_PTS_10,ROLL_PTS_25,ROLL_PTS_50,ROLL_PTS_100,ROLL_PTS_200,ROLL_REB_3,ROLL_REB_5,ROLL_REB_10,ROLL_REB_25,ROLL_REB_50,ROLL_REB_100,ROLL_REB_200,ROLL_AST_3,ROLL_AST_5,ROLL_AST_10,ROLL_AST_25,ROLL_AST_50,ROLL_AST_100,ROLL_AST_200,ROLL_FGM_3,ROLL_FGM_5,ROLL_FGM_10,ROLL_FGM_25,ROLL_FGM_50,ROLL_FGM_100,ROLL_FGM_200,ROLL_FGA_3,ROLL_FGA_5,ROLL_FGA_10,ROLL_FGA_25,ROLL_FGA_50,ROLL_FGA_100,ROLL_FGA_200,ROLL_FG_PCT_3,ROLL_FG_PCT_5,ROLL_FG_PCT_10,ROLL_FG_PCT_25,ROLL_FG_PCT_50,ROLL_FG_PCT_100,ROLL_FG_PCT_200,ROLL_PLUS_MINUS_3,ROLL_PLUS_MINUS_5,ROLL_PLUS_MINUS_10,ROLL_PLUS_MINUS_25,ROLL_PLUS_MINUS_50,ROLL_PLUS_MINUS_100,ROLL_PLUS_MINUS_200,ROLL_TS_PCT_3,ROLL_TS_PCT_5,ROLL_TS_PCT_10,ROLL_TS_PCT_25,ROLL_TS_PCT_50,ROLL_TS_PCT_100,ROLL_TS_PCT_200,ROLL_EFG_PCT_3,ROLL_EFG_PCT_5,ROLL_EFG_PCT_10,ROLL_EFG_PCT_25,ROLL_EFG_PCT_50,ROLL_EFG_PCT_100,ROLL_EFG_PCT_200,ROLL_AST_TO_RATIO_3,ROLL_AST_TO_RATIO_5,ROLL_AST_TO_RATIO_10,ROLL_AST_TO_RATIO_25,ROLL_AST_TO_RATIO_50,ROLL_AST_TO_RATIO_100,ROLL_AST_TO_RATIO_200,ROLL_REB_RATE_3,ROLL_REB_RATE_5,ROLL_REB_RATE_10,ROLL_REB_RATE_25,ROLL_REB_RATE_50,ROLL_REB_RATE_100,ROLL_REB_RATE_200,ROLL_POSSESSIONS_3,ROLL_POSSESSIONS_5,ROLL_POSSESSIONS_10,ROLL_POSSESSIONS_25,ROLL_POSSESSIONS_50,ROLL_POSSESSIONS_100,ROLL_POSSESSIONS_200,ROLL_OPP_POSSESSIONS_3,ROLL_OPP_POSSESSIONS_5,ROLL_OPP_POSSESSIONS_10,ROLL_OPP_POSSESSIONS_25,ROLL_OPP_POSSESSIONS_50,ROLL_OPP_POSSESSIONS_100,ROLL_OPP_POSSESSIONS_200,ROLL_OFF_RATING_3,ROLL_OFF_RATING_5,ROLL_OFF_RATING_10,ROLL_OFF_RATING_25,ROLL_OFF_RATING_50,ROLL_OFF_RATING_100,ROLL_OFF_RATING_200,ROLL_DEF_RATING_3,ROLL_DEF_RATING_5,ROLL_DEF_RATING_10,ROLL_DEF_RATING_25,ROLL_DEF_RATING_50,ROLL_DEF_RATING_100,ROLL_DEF_RATING_200,ROLL_HOME_WINRATE_3,ROLL_AWAY_WINRATE_3,ROLL_HOME_WINRATE_5,ROLL_AWAY_WINRATE_5,ROLL_HOME_WINRATE_10,ROLL_AWAY_WINRATE_10,ROLL_HOME_WINRATE_25,ROLL_AWAY_WINRATE_25,ROLL_HOME_WINRATE_50,ROLL_AWAY_WINRATE_50,ROLL_HOME_WINRATE_100,ROLL_AWAY_WINRATE_100,ROLL_HOME_WINRATE_200,ROLL_AWAY_WINRATE_200,ROLL_WIN_RATIO_3,ROLL_WIN_RATIO_5,ROLL_WIN_RATIO_10,ROLL_WIN_RATIO_25,ROLL_WIN_RATIO_50,ROLL_WIN_RATIO_100,ROLL_WIN_RATIO_200,WIN_STREAK,HOME_WIN_STREAK,AWAY_WIN_STREAK,DAYS_SINCE_LAST_GAME,OPP_DAYS_SINCE_LAST_GAME,REST_ADVANTAGE,ROLL_HOME_REST_ADV_3,ROLL_AWAY_REST_ADV_3,ROLL_HOME_REST_ADV_5,ROLL_AWAY_REST_ADV_5,ROLL_HOME_REST_ADV_10,ROLL_AWAY_REST_ADV_10,ROLL_HOME_REST_ADV_25,ROLL_AWAY_REST_ADV_25,ROLL_HOME_REST_ADV_50,ROLL_AWAY_REST_ADV_50,ROLL_HOME_REST_ADV_100,ROLL_AWAY_REST_ADV_100,ROLL_HOME_REST_ADV_200,ROLL_AWAY_REST_ADV_200,ROLL_HOME_PTS_FOR_3,ROLL_HOME_OPP_PTS_AGAINST_3,ROLL_AWAY_PTS_FOR_3,ROLL_AWAY_OPP_PTS_AGAINST_3,ROLL_HOME_PTS_FOR_5,ROLL_HOME_OPP_PTS_AGAINST_5,ROLL_AWAY_PTS_FOR_5,ROLL_AWAY_OPP_PTS_AGAINST_5,ROLL_HOME_PTS_FOR_10,ROLL_HOME_OPP_PTS_AGAINST_10,ROLL_AWAY_PTS_FOR_10,ROLL_AWAY_OPP_PTS_AGAINST_10,ROLL_HOME_PTS_FOR_25,ROLL_HOME_OPP_PTS_AGAINST_25,ROLL_AWAY_PTS_FOR_25,ROLL_AWAY_OPP_PTS_AGAINST_25,ROLL_HOME_PTS_FOR_50,ROLL_HOME_OPP_PTS_AGAINST_50,ROLL_AWAY_PTS_FOR_50,ROLL_AWAY_OPP_PTS_AGAINST_50,ROLL_HOME_PTS_FOR_100,ROLL_HOME_OPP_PTS_AGAINST_100,ROLL_AWAY_PTS_FOR_100,ROLL_AWAY_OPP_PTS_AGAINST_100,ROLL_HOME_PTS_FOR_200,ROLL_HOME_OPP_PTS_AGAINST_200,ROLL_AWAY_PTS_FOR_200,ROLL_AWAY_OPP_PTS_AGAINST_200,H2H_LAST_3_DIFF,H2H_LAST_3_WINRATE,H2H_LAST_3_COUNT,H2H_LAST_5_DIFF,H2H_LAST_5_WINRATE,H2H_LAST_5_COUNT,H2H_LAST_10_DIFF,H2H_LAST_10_WINRATE,H2H_LAST_10_COUNT,H2H_LAST_25_DIFF,H2H_LAST_25_WINRATE,H2H_LAST_25_COUNT,H2H_LAST_50_DIFF,H2H_LAST_50_WINRATE,H2H_LAST_50_COUNT,H2H_LAST_100_DIFF,H2H_LAST_100_WINRATE,H2H_LAST_100_COUNT,H2H_LAST_200_DIFF,H2H_LAST_200_WINRATE,H2H_LAST_200_COUNT,H2H_SEASON_WINS,H2H_SEASON_MATCHES,H2H_SEASON_WINRATE,H2H_WIN_STREAK,ELO_PRE,OPP_ELO_PRE,ELO_PRE_SEASON,OPP_ELO_PRE_SEASON
0,NaN,1.0,1.40,2.94,327.333333,282.0,243.4,232.32,231.72,232.56,243.32,124.666667,109.2,99.6,89.20,86.96,86.38,95.03,60.000000,52.4,45.0,50.88,52.72,52.78,53.27,111.333333,99.6,87.4,85.84,86.84,86.42,89.55,240.0,212.8,194.4,183.12,184.12,179.48,190.48,10.725333,10.0276,7.9334,8.27248,8.46376,8.4282,8.92574,23.333333,-14.0,-2.0,17.2,15.2,32.5,41.45,0.571885,0.564999,0.543018,0.566841,0.568056,0.584975,0.577230,0.516899,0.518129,0.507045,0.532414,0.534737,0.551261,0.543180,1.695238,1.724719,1.596013,2.130905,2.271841,2.366300,2.272639,0.540588,0.541745,0.511528,0.504696,0.496949,0.506617,0.517424,282.026667,243.488,220.752,205.9616,205.1184,200.8168,211.5424,269.653333,234.560,218.056,205.0496,203.3824,199.8704,210.1896,114.779805,114.808275,109.035630,112.412853,112.674018,115.747949,115.114531,116.771360,120.338360,110.428569,111.169515,112.295159,113.092697,112.019918,0.5,0.0,0.5,0.0,0.40,0.800000,0.571429,0.636364,0.629630,0.608696,0.647059,0.591837,0.663366,0.565657,0.333333,0.4,0.6,0.6,0.62,0.62,0.615,0,0,3,2.0,2.0,0.0,-47.0,0.0,-23.5,0.000000,-18.8,-4.600000,-44.142857,-33.636364,-90.481481,-74.608696,-95.823529,-110.938776,-93.425743,-118.111111,389.0,357.0,204.0,254.0,301.5,292.5,204.0,254.000000,282.4,276.4,204.4,211.200000,247.142857,235.142857,213.454545,220.909091,243.407407,234.074074,218.000000,222.347826,240.274510,227.450980,224.530612,224.612245,246.792079,233.029703,239.777778,237.070707,-1,0.333333,3,-1,0.4,5,-2,0.4,10,1,0.52,25,-12,0.38,50,-12,0.409091,66,-12,0.409091,66,2,4,0.5,0,1628.956243,1680.099161,1621.677548,1676.326177
1,NaN,0.0,2.94,1.40,346.000000,297.2,267.2,243.44,240.12,235.06,257.45,108.000000,97.2,90.0,85.92,82.76,82.98,88.42,76.666667,67.6,64.2,59.36,60.24,58.64,63.93,128.000000,108.4,98.2,88.64,88.32,87.76,96.88,250.0,216.0,195.8,177.68,178.68,177.22,193.59,13.010667,11.8580,10.6116,10.10912,9.80268,9.8750,10.88140,116.666667,28.0,42.0,72.0,53.2,28.3,22.10,0.623213,0.606197,0.615100,0.614477,0.606592,0.600937,0.603343,0.594663,0.572019,0.582573,0.579433,0.572807,0.569573,0.573657,3.138095,2.612269,2.624479,3.043710,2.964510,2.720584,2.711153,0.479520,0.468431,0.477907,0.490264,0.477675,0.483588,0.487099,280.080000,251.136,226.312,203.7568,203.4432,202.1152,219.4940,286.053333,258.304,229.128,207.1168,206.1456,203.5808,219.6092,122.014574,116.346741,117.262012,119.317175,117.979954,116.363258,117.216372,110.311715,111.427854,112.214304,110.202594,111.224902,112.704891,114.968778,1.0,1.0,0.5,1.0,0.75,0.833333,0.800000,0.800000,0.777778,0.608696,0.714286,0.509804,0.653061,0.490196,1.000000,0.8,0.8,0.8,0.70,0.61,0.570,3,0,5,2.0,2.0,0.0,0.0,-45.5,0.0,-30.333333,0.0,-18.333333,-42.800000,-65.500000,-68.666667,-101.260870,-73.775510,-128.294118,-95.948980,-117.343137,258.0,218.0,390.0,375.0,233.0,235.0,340.0,329.333333,237.5,234.0,287.0,275.333333,220.266667,206.133333,278.200000,263.400000,229.925926,216.074074,252.086957,245.217391,231.306122,219.632653,238.666667,238.784314,266.122449,254.122449,249.117647,252.000000,1,0.666667,3,1,0.6,5,2,0.6,10,-1,0.48,25,12,0.62,50,12,0.590909,66,12,0.590909,66,2,4,0.5,1,1680.099161,1628.956243,1676.326177,1621.677548

Ligne réelle:

,GAME_ID,IS_HOME,ODDS,OPP_ODDS,ROLL_PTS_3,ROLL_PTS_5,ROLL_PTS_10,ROLL_PTS_25,ROLL_PTS_50,ROLL_PTS_100,ROLL_PTS_200,ROLL_REB_3,ROLL_REB_5,ROLL_REB_10,ROLL_REB_25,ROLL_REB_50,ROLL_REB_100,ROLL_REB_200,ROLL_AST_3,ROLL_AST_5,ROLL_AST_10,ROLL_AST_25,ROLL_AST_50,ROLL_AST_100,ROLL_AST_200,ROLL_FGM_3,ROLL_FGM_5,ROLL_FGM_10,ROLL_FGM_25,ROLL_FGM_50,ROLL_FGM_100,ROLL_FGM_200,ROLL_FGA_3,ROLL_FGA_5,ROLL_FGA_10,ROLL_FGA_25,ROLL_FGA_50,ROLL_FGA_100,ROLL_FGA_200,ROLL_FG_PCT_3,ROLL_FG_PCT_5,ROLL_FG_PCT_10,ROLL_FG_PCT_25,ROLL_FG_PCT_50,ROLL_FG_PCT_100,ROLL_FG_PCT_200,ROLL_PLUS_MINUS_3,ROLL_PLUS_MINUS_5,ROLL_PLUS_MINUS_10,ROLL_PLUS_MINUS_25,ROLL_PLUS_MINUS_50,ROLL_PLUS_MINUS_100,ROLL_PLUS_MINUS_200,ROLL_TS_PCT_3,ROLL_TS_PCT_5,ROLL_TS_PCT_10,ROLL_TS_PCT_25,ROLL_TS_PCT_50,ROLL_TS_PCT_100,ROLL_TS_PCT_200,ROLL_EFG_PCT_3,ROLL_EFG_PCT_5,ROLL_EFG_PCT_10,ROLL_EFG_PCT_25,ROLL_EFG_PCT_50,ROLL_EFG_PCT_100,ROLL_EFG_PCT_200,ROLL_AST_TO_RATIO_3,ROLL_AST_TO_RATIO_5,ROLL_AST_TO_RATIO_10,ROLL_AST_TO_RATIO_25,ROLL_AST_TO_RATIO_50,ROLL_AST_TO_RATIO_100,ROLL_AST_TO_RATIO_200,ROLL_REB_RATE_3,ROLL_REB_RATE_5,ROLL_REB_RATE_10,ROLL_REB_RATE_25,ROLL_REB_RATE_50,ROLL_REB_RATE_100,ROLL_REB_RATE_200,ROLL_POSSESSIONS_3,ROLL_POSSESSIONS_5,ROLL_POSSESSIONS_10,ROLL_POSSESSIONS_25,ROLL_POSSESSIONS_50,ROLL_POSSESSIONS_100,ROLL_POSSESSIONS_200,ROLL_OPP_POSSESSIONS_3,ROLL_OPP_POSSESSIONS_5,ROLL_OPP_POSSESSIONS_10,ROLL_OPP_POSSESSIONS_25,ROLL_OPP_POSSESSIONS_50,ROLL_OPP_POSSESSIONS_100,ROLL_OPP_POSSESSIONS_200,ROLL_OFF_RATING_3,ROLL_OFF_RATING_5,ROLL_OFF_RATING_10,ROLL_OFF_RATING_25,ROLL_OFF_RATING_50,ROLL_OFF_RATING_100,ROLL_OFF_RATING_200,ROLL_DEF_RATING_3,ROLL_DEF_RATING_5,ROLL_DEF_RATING_10,ROLL_DEF_RATING_25,ROLL_DEF_RATING_50,ROLL_DEF_RATING_100,ROLL_DEF_RATING_200,ROLL_HOME_WINRATE_3,ROLL_AWAY_WINRATE_3,ROLL_HOME_WINRATE_5,ROLL_AWAY_WINRATE_5,ROLL_HOME_WINRATE_10,ROLL_AWAY_WINRATE_10,ROLL_HOME_WINRATE_25,ROLL_AWAY_WINRATE_25,ROLL_HOME_WINRATE_50,ROLL_AWAY_WINRATE_50,ROLL_HOME_WINRATE_100,ROLL_AWAY_WINRATE_100,ROLL_HOME_WINRATE_200,ROLL_AWAY_WINRATE_200,ROLL_WIN_RATIO_3,ROLL_WIN_RATIO_5,ROLL_WIN_RATIO_10,ROLL_WIN_RATIO_25,ROLL_WIN_RATIO_50,ROLL_WIN_RATIO_100,ROLL_WIN_RATIO_200,WIN_STREAK,HOME_WIN_STREAK,AWAY_WIN_STREAK,DAYS_SINCE_LAST_GAME,OPP_DAYS_SINCE_LAST_GAME,REST_ADVANTAGE,ROLL_HOME_REST_ADV_3,ROLL_AWAY_REST_ADV_3,ROLL_HOME_REST_ADV_5,ROLL_AWAY_REST_ADV_5,ROLL_HOME_REST_ADV_10,ROLL_AWAY_REST_ADV_10,ROLL_HOME_REST_ADV_25,ROLL_AWAY_REST_ADV_25,ROLL_HOME_REST_ADV_50,ROLL_AWAY_REST_ADV_50,ROLL_HOME_REST_ADV_100,ROLL_AWAY_REST_ADV_100,ROLL_HOME_REST_ADV_200,ROLL_AWAY_REST_ADV_200,ROLL_HOME_PTS_FOR_3,ROLL_HOME_OPP_PTS_AGAINST_3,ROLL_AWAY_PTS_FOR_3,ROLL_AWAY_OPP_PTS_AGAINST_3,ROLL_HOME_PTS_FOR_5,ROLL_HOME_OPP_PTS_AGAINST_5,ROLL_AWAY_PTS_FOR_5,ROLL_AWAY_OPP_PTS_AGAINST_5,ROLL_HOME_PTS_FOR_10,ROLL_HOME_OPP_PTS_AGAINST_10,ROLL_AWAY_PTS_FOR_10,ROLL_AWAY_OPP_PTS_AGAINST_10,ROLL_HOME_PTS_FOR_25,ROLL_HOME_OPP_PTS_AGAINST_25,ROLL_AWAY_PTS_FOR_25,ROLL_AWAY_OPP_PTS_AGAINST_25,ROLL_HOME_PTS_FOR_50,ROLL_HOME_OPP_PTS_AGAINST_50,ROLL_AWAY_PTS_FOR_50,ROLL_AWAY_OPP_PTS_AGAINST_50,ROLL_HOME_PTS_FOR_100,ROLL_HOME_OPP_PTS_AGAINST_100,ROLL_AWAY_PTS_FOR_100,ROLL_AWAY_OPP_PTS_AGAINST_100,ROLL_HOME_PTS_FOR_200,ROLL_HOME_OPP_PTS_AGAINST_200,ROLL_AWAY_PTS_FOR_200,ROLL_AWAY_OPP_PTS_AGAINST_200,H2H_LAST_3_DIFF,H2H_LAST_3_WINRATE,H2H_LAST_3_COUNT,H2H_LAST_5_DIFF,H2H_LAST_5_WINRATE,H2H_LAST_5_COUNT,H2H_LAST_10_DIFF,H2H_LAST_10_WINRATE,H2H_LAST_10_COUNT,H2H_LAST_25_DIFF,H2H_LAST_25_WINRATE,H2H_LAST_25_COUNT,H2H_LAST_50_DIFF,H2H_LAST_50_WINRATE,H2H_LAST_50_COUNT,H2H_LAST_100_DIFF,H2H_LAST_100_WINRATE,H2H_LAST_100_COUNT,H2H_LAST_200_DIFF,H2H_LAST_200_WINRATE,H2H_LAST_200_COUNT,H2H_SEASON_WINS,H2H_SEASON_MATCHES,H2H_SEASON_WINRATE,H2H_WIN_STREAK,ELO_PRE,OPP_ELO_PRE,ELO_PRE_SEASON,OPP_ELO_PRE_SEASON
0,42400302,1.0,1.40,2.94,382.180177,326.297713,275.295785,243.544971,235.532048,234.031847,234.698511,140.442908,123.669382,107.138380,94.417385,89.934860,88.996435,90.775403,70.059602,60.291886,52.030937,50.014165,51.183112,51.963390,51.495409,134.851966,115.393262,98.413044,88.994356,87.098252,86.747705,86.574737,275.666382,241.409369,210.619055,190.909545,184.977449,182.966420,183.461909,12.425793,10.797906,9.218752,8.463616,8.420255,8.480027,8.657280,32.347502,22.839566,12.651460,14.809683,20.588557,28.777218,32.305593,0.585928,0.573657,0.562940,0.563621,0.569813,0.575863,0.576486,0.543092,0.530850,0.522835,0.527416,0.535258,0.541944,0.542393,1.677948,1.680324,1.720856,1.932813,2.121471,2.244341,2.246018,0.548303,0.539424,0.523897,0.509496,0.505402,0.507536,0.512442,324.716514,280.933074,241.754972,216.102062,207.847788,204.548659,204.713631,311.371426,271.226265,236.341798,213.723517,206.261178,203.279233,203.735521,116.880639,114.864201,112.581104,111.992285,112.951972,114.254052,114.611150,116.652776,115.333450,113.164604,111.509969,111.706977,112.129369,112.036256,0.5,0.0,0.5,0.0,0.40,0.800000,0.571429,0.636364,0.629630,0.608696,0.647059,0.591837,0.663366,0.565657,0.333333,0.4,0.6,0.6,0.62,0.62,0.615,0,0,3,2.0,2.0,0.0,-47.0,0.0,-23.5,0.000000,-18.8,-4.600000,-44.142857,-33.636364,-90.481481,-74.608696,-95.823529,-110.938776,-93.425743,-118.111111,389.0,357.0,204.0,254.0,301.5,292.5,204.0,254.000000,282.4,276.4,204.4,211.200000,247.142857,235.142857,213.454545,220.909091,243.407407,234.074074,218.000000,222.347826,240.274510,227.450980,224.530612,224.612245,246.792079,233.029703,239.777778,237.070707,-1,0.333333,3,-1,0.4,5,-2,0.4,10,1,0.52,25,-12,0.38,50,-12,0.409091,66,-12,0.409091,66,2,4,0.5,0,1628.956243,1680.099161,1621.677548,1676.326177
1,42400302,0.0,2.94,1.40,393.203893,339.798495,288.712767,254.152723,243.869086,241.396263,243.245671,120.787175,107.856812,95.446917,87.093464,84.710641,84.354656,85.338084,81.068100,73.577712,66.162318,61.383566,60.186736,60.016477,60.058459,144.611345,124.691846,105.751906,93.162445,89.845326,89.693529,90.832928,284.908272,246.530754,210.326604,186.904695,181.082095,180.911948,183.940023,14.058119,12.746207,11.301342,10.294742,10.022773,10.040069,10.149976,66.442406,58.332798,55.231839,58.078790,52.794086,41.085556,25.684855,0.615234,0.614421,0.613446,0.610759,0.607149,0.603565,0.599014,0.584440,0.582552,0.580594,0.577362,0.574166,0.571711,0.567781,3.066421,2.878475,2.862596,2.986777,2.961887,2.864360,2.711272,0.471114,0.472817,0.476818,0.480988,0.481997,0.483511,0.485055,318.157986,279.380050,240.774443,213.629162,206.362563,205.641757,208.966627,330.042062,288.028751,246.292251,217.049462,208.927222,207.308068,209.597282,121.433240,119.505921,118.486533,118.412929,117.949360,117.306250,116.345729,112.832139,111.902505,111.325504,111.063493,111.366221,112.336898,113.476110,1.0,1.0,0.5,1.0,0.75,0.833333,0.800000,0.800000,0.777778,0.608696,0.714286,0.509804,0.653061,0.490196,1.000000,0.8,0.8,0.8,0.70,0.61,0.570,3,0,5,2.0,2.0,0.0,0.0,-45.5,0.0,-30.333333,0.0,-18.333333,-42.800000,-65.500000,-68.666667,-101.260870,-73.775510,-128.294118,-95.948980,-117.343137,258.0,218.0,390.0,375.0,233.0,235.0,340.0,329.333333,237.5,234.0,287.0,275.333333,220.266667,206.133333,278.200000,263.400000,229.925926,216.074074,252.086957,245.217391,231.306122,219.632653,238.666667,238.784314,266.122449,254.122449,249.117647,252.000000,1,0.666667,3,1,0.6,5,2,0.6,10,-1,0.48,25,12,0.62,50,12,0.590909,66,12,0.590909,66,2,4,0.5,1,1680.099161,1628.956243,1676.326177,1621.677548

End time: 2025-05-30 01:21:37.647785
Duration: 0:00:45.978211