In [1]:
%pip install lightgbm xgboost catboost

Requirement already satisfied: lightgbm in /opt/conda/lib/python3.10/site-packages (4.6.0)
Requirement already satisfied: xgboost in /opt/conda/lib/python3.10/site-packages (3.0.2)
Requirement already satisfied: catboost in /opt/conda/lib/python3.10/site-packages (1.2.8)
Requirement already satisfied: numpy>=1.17.0 in /opt/conda/lib/python3.10/site-packages (from lightgbm) (1.23.4)
Requirement already satisfied: scipy in /opt/conda/lib/python3.10/site-packages (from lightgbm) (1.9.3)
Requirement already satisfied: nvidia-nccl-cu12 in /opt/conda/lib/python3.10/site-packages (from xgboost) (2.26.5)
Requirement already satisfied: graphviz in /opt/conda/lib/python3.10/site-packages (from catboost) (0.20.3)
Requirement already satisfied: pandas>=0.24 in /opt/conda/lib/python3.10/site-packages (from catboost) (1.5.1)
Requirement already satisfied: matplotlib in /opt/conda/lib/python3.10/site-packages (from catboost) (3.6.2)
Requirement already satisfied: plotly in /opt/conda/lib/python3.10/site-packages (from catboost) (6.1.1)
Requirement already satisfied: six in /opt/conda/lib/python3.10/site-packages (from catboost) (1.16.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /opt/conda/lib/python3.10/site-packages (from pandas>=0.24->catboost) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.10/site-packages (from pandas>=0.24->catboost) (2022.6)
Requirement already satisfied: kiwisolver>=1.0.1 in /opt/conda/lib/python3.10/site-packages (from matplotlib->catboost) (1.4.4)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.10/site-packages (from matplotlib->catboost) (4.38.0)
Requirement already satisfied: pillow>=6.2.0 in /opt/conda/lib/python3.10/site-packages (from matplotlib->catboost) (9.2.0)
Requirement already satisfied: pyparsing>=2.2.1 in /opt/conda/lib/python3.10/site-packages (from matplotlib->catboost) (3.0.9)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.10/site-packages (from matplotlib->catboost) (0.11.0)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.10/site-packages (from matplotlib->catboost) (21.3)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.10/site-packages (from matplotlib->catboost) (1.0.6)
Requirement already satisfied: narwhals>=1.15.1 in /opt/conda/lib/python3.10/site-packages (from plotly->catboost) (1.41.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import os
import pandas as pd
import joblib


from sklearn.ensemble import RandomForestClassifier, StackingClassifier
from sklearn.linear_model import LogisticRegression
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from sklearn.ensemble import ExtraTreesClassifier, HistGradientBoostingClassifier
from sklearn.neural_network import MLPClassifier

from src.simulator_betting import *
from src.config import *
from src.utils import get_latest_file
pd.set_option("display.max_columns", None)

# --- 1. Charger le modèle

In [3]:

model_path = get_latest_file(DATA_MODELS_DIR)
model = joblib.load(model_path)
print("Modèle chargé:", model_path)

Modèle chargé: data/models/stacking_model_2025-05-26.joblib

# --- 2. Charger les données NBA

In [4]:

dataset_path = get_latest_file(DATA_FINAL_CLEANED_DATASET_DIR)
nba_df = pd.read_csv(dataset_path, dtype={"GAME_ID": str, "GAME_DATE": str, "SEASON": str})

nba_df = nba_df[nba_df['SEASON'] == '2023-24']


print("Dataset NBA chargé:", dataset_path)

nba_df

Dataset NBA chargé: data/final_cleaned_dataset/nba_features_cleaned_final_2025-05-26_17-54-31.csv

,GAME_ID,TEAM_ID,GAME_DATE,OPP_TEAM_ID,SEASON,IS_HOME,IS_WIN,ROLL_HOME_WINRATE_3,ROLL_AWAY_WINRATE_3,ROLL_HOME_WINRATE_5,ROLL_AWAY_WINRATE_5,ROLL_HOME_WINRATE_10,ROLL_AWAY_WINRATE_10,ROLL_HOME_WINRATE_25,ROLL_AWAY_WINRATE_25,ROLL_HOME_WINRATE_50,ROLL_AWAY_WINRATE_50,ROLL_HOME_WINRATE_100,ROLL_AWAY_WINRATE_100,ROLL_HOME_WINRATE_200,ROLL_AWAY_WINRATE_200,ROLL_WIN_RATIO_3,ROLL_WIN_RATIO_5,ROLL_WIN_RATIO_10,ROLL_WIN_RATIO_25,ROLL_WIN_RATIO_50,ROLL_WIN_RATIO_100,ROLL_WIN_RATIO_200,WIN_STREAK,HOME_WIN_STREAK,AWAY_WIN_STREAK,DAYS_SINCE_LAST_GAME,OPP_DAYS_SINCE_LAST_GAME,REST_ADVANTAGE,ROLL_HOME_REST_ADV_3,ROLL_AWAY_REST_ADV_3,ROLL_HOME_REST_ADV_5,ROLL_AWAY_REST_ADV_5,ROLL_HOME_REST_ADV_10,ROLL_AWAY_REST_ADV_10,ROLL_HOME_REST_ADV_25,ROLL_AWAY_REST_ADV_25,ROLL_HOME_REST_ADV_50,ROLL_AWAY_REST_ADV_50,ROLL_HOME_REST_ADV_100,ROLL_AWAY_REST_ADV_100,ROLL_HOME_REST_ADV_200,ROLL_AWAY_REST_ADV_200,H2H_LAST_3_DIFF,H2H_LAST_3_WINRATE,H2H_LAST_3_COUNT,H2H_LAST_5_DIFF,H2H_LAST_5_WINRATE,H2H_LAST_5_COUNT,H2H_LAST_10_DIFF,H2H_LAST_10_WINRATE,H2H_LAST_10_COUNT,H2H_LAST_25_DIFF,H2H_LAST_25_WINRATE,H2H_LAST_25_COUNT,H2H_LAST_50_DIFF,H2H_LAST_50_WINRATE,H2H_LAST_50_COUNT,H2H_LAST_100_DIFF,H2H_LAST_100_WINRATE,H2H_LAST_100_COUNT,H2H_LAST_200_DIFF,H2H_LAST_200_WINRATE,H2H_LAST_200_COUNT,H2H_SEASON_WINS,H2H_SEASON_MATCHES,H2H_SEASON_WINRATE,H2H_WIN_STREAK,ELO_PRE,OPP_ELO_PRE,ELO_PRE_SEASON,OPP_ELO_PRE_SEASON
58976,0022300061,1610612743,2023-10-24,1610612747,2023-24,1,1,1.0,1.000000,0.666667,1.000000,0.8,1.000000,0.923077,0.500000,0.833333,0.500000,0.846154,0.500000,0.700000,0.520000,1.000000,0.8,0.9,0.72,0.66,0.68,0.610,3,6,1,134.0,155.0,-21.0,0.0,0.0,-32.666667,0.0,-44.0,0.0,-35.230769,-12.833333,-69.500000,-39.269231,-109.211538,-96.875000,-105.390000,-91.850000,3,1.000000,3,5,1.0,5,4,0.7,10,1,0.52,25,10,0.60,50,-4,0.480000,100,-8,0.463636,110,0,0,0.000000,5,1688.099683,1571.552579,1500.000000,1500.000000
58977,0022300061,1610612747,2023-10-24,1610612743,2023-24,0,0,0.0,0.000000,0.333333,0.000000,0.6,0.200000,0.750000,0.461538,0.680000,0.480000,0.600000,0.460000,0.564356,0.383838,0.000000,0.2,0.4,0.60,0.58,0.53,0.475,0,0,0,155.0,155.0,0.0,0.0,0.0,0.000000,-61.5,0.0,-35.4,-40.500000,-36.153846,-53.640000,-56.800000,-113.280000,-93.200000,-109.237624,-89.313131,-3,0.000000,3,-5,0.0,5,-4,0.3,10,-1,0.48,25,-10,0.40,50,4,0.520000,100,8,0.536364,110,0,0,0.000000,0,1571.552579,1688.099683,1500.000000,1500.000000
58978,0022300062,1610612744,2023-10-24,1610612756,2023-24,1,0,1.0,0.000000,1.000000,0.000000,0.6,0.400000,0.727273,0.428571,0.800000,0.320000,0.795918,0.294118,0.782178,0.404040,0.333333,0.4,0.5,0.56,0.56,0.54,0.595,0,0,1,165.0,225.0,-60.0,0.0,0.0,0.000000,0.0,-11.2,0.0,-27.363636,-27.500000,-39.600000,-47.400000,-98.795918,-99.000000,-98.118812,-93.666667,-1,0.333333,3,-3,0.2,5,-2,0.4,10,5,0.60,25,14,0.64,50,2,0.511111,90,2,0.511111,90,0,0,0.000000,1,1558.179623,1580.917377,1500.000000,1500.000000
58979,0022300062,1610612756,2023-10-24,1610612744,2023-24,0,1,0.5,0.000000,0.666667,0.000000,0.8,0.400000,0.714286,0.363636,0.692308,0.500000,0.686275,0.387755,0.722772,0.555556,0.333333,0.4,0.6,0.56,0.60,0.54,0.640,0,0,0,166.0,225.0,-59.0,0.0,0.0,0.000000,0.0,0.0,-3.8,-38.785714,-24.909091,-98.807692,-47.875000,-110.274510,-87.591837,-104.643564,-84.313131,1,0.666667,3,3,0.8,5,2,0.6,10,-5,0.40,25,-14,0.36,50,-2,0.488889,90,-2,0.488889,90,0,0,0.000000,0,1580.917377,1558.179623,1500.000000,1500.000000
58980,0022300063,1610612737,2023-10-25,1610612766,2023-24,0,0,0.0,1.000000,0.333333,0.500000,0.4,0.400000,0.538462,0.416667,0.560000,0.480000,0.583333,0.403846,0.620000,0.420000,0.333333,0.4,0.4,0.48,0.52,0.49,0.520,0,2,0,181.0,254.0,-73.0,0.0,0.0,0.000000,0.0,-30.6,-12.6,-85.538462,-17.500000,-88.040000,-79.640000,-118.833333,-89.115385,-100.510000,-94.680000,-1,0.333333,3,-1,0.4,5,0,0.5,10,-7,0.36,25,4,0.54,50,-4,0.475610,82,-4,0.475610,82,0,0,0.000000,0,1518.053186,1413.275295,1500.000000,1500.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61607,0042300403,1610612742,2024-06-12,1610612738,2023-24,1,0,0.5,0.333333,0.500000,0.333333,0.5,0.666667,0.636364,0.642857,0.727273,0.642857,0.612245,0.607843,0.608247,0.485437,0.333333,0.4,0.6,0.64,0.68,0.61,0.545,0,0,0,3.0,3.0,0.0,NaN,-30.0,0.000000,-30.0,0.0,-33.0,-3.545455,-39.214286,-42.772727,-67.285714,-110.408163,-110.686275,-114.484536,-93.320388,-3,0.000000,3,-5,0.0,5,-2,0.4,10,-1,0.48,25,10,0.60,50,10,0.600000,50,10,0.600000,50,0,4,0.000000,0,1670.584328,1774.586274,1670.929911,1760.520679
61608,0042300404,1610612738,2024-06-14,1610612742,2023-24,0,0,1.0,1.000000,1.000000,1.000000,1.0,1.000000,0.812500,0.888889,0.884615,0.791667,0.865385,0.708333,0.794118,0.663265,1.000000,1.0,1.0,0.84,0.84,0.79,0.730,10,11,5,2.0,2.0,0.0,-43.5,0.0,-43.500000,0.0,-38.6,0.0,-38.375000,-16.555556,-46.230769,-63.666667,-91.769231,-122.520833,-93.401961,-113.765306,3,1.000000,3,5,1.0,5,4,0.7,10,3,0.56,25,-8,0.42,50,-9,0.411765,51,-9,0.411765,51,5,5,1.000000,7,1783.097754,1662.340023,1769.493132,1662.245687
61609,0042300404,1610612742,2024-06-14,1610612738,2023-24,1,1,0.0,0.000000,0.000000,0.333333,0.5,0.666667,0.545455,0.642857,0.695652,0.629630,0.591837,0.607843,0.597938,0.485437,0.000000,0.2,0.6,0.60,0.66,0.60,0.540,0,0,0,2.0,2.0,0.0,0.0,-45.0,0.000000,-30.0,0.0,-33.0,-3.363636,-39.214286,-40.913043,-68.814815,-103.224490,-110.686275,-114.484536,-93.320388,-3,0.000000,3,-5,0.0,5,-4,0.3,10,-3,0.44,25,8,0.58,50,9,0.588235,51,9,0.588235,51,0,5,0.000000,0,1662.340023,1783.097754,1662.245687,1769.493132
61610,0042300405,1610612738,2024-06-17,1610612742,2023-24,1,1,1.0,0.500000,1.000000,0.666667,1.0,0.800000,0.812500,0.777778,0.880000,0.760000,0.882353,0.693878,0.794118,0.653061,0.666667,0.8,0.9,0.80,0.82,0.79,0.725,0,0,5,3.0,3.0,0.0,0.0,0.0,-43.500000,0.0,-38.6,0.0,-38.375000,-2.000000,-45.120000,-61.120000,-93.568627,-120.020408,-93.401961,-112.316327,1,0.666667,3,3,0.8,5,4,0.7,10,3,0.56,25,-8,0.42,50,-10,0.403846,52,-10,0.403846,52,5,6,0.833333,0,1767.087143,1677.852091,1753.902270,1677.339943
61611,0042300405,1610612742,2024-06-17,1610612738,2023-24,0,0,0.5,0.000000,0.500000,0.333333,0.6,0.600000,0.545455,0.642857,0.695652,0.629630,0.600000,0.600000,0.602041,0.480392,0.333333,0.4,0.6,0.60,0.66,0.60,0.540,1,0,1,3.0,3.0,0.0,0.0,0.0,0.000000,-30.0,0.0,-39.6,-2.909091,-39.214286,-37.956522,-68.814815,-101.160000,-108.480000,-113.316327,-94.235294,-1,0.333333,3,-3,0.2,5,-4,0.3,10,-3,0.44,25,8,0.58,50,10,0.596154,52,10,0.596154,52,1,6,0.166667,1,1677.852091,1767.087143,1677.339943,1753.902270


# --- 3. Charger la table des équipes

In [5]:

teams_path = get_latest_file(DATA_TEAMS_DIR)
teams_df = pd.read_csv(teams_path)
team_id_map = dict(zip(teams_df["id"], teams_df["full_name"]))

In [6]:
team_id_map

{1610612737: 'Atlanta Hawks',
 1610612738: 'Boston Celtics',
 1610612739: 'Cleveland Cavaliers',
 1610612740: 'New Orleans Pelicans',
 1610612741: 'Chicago Bulls',
 1610612742: 'Dallas Mavericks',
 1610612743: 'Denver Nuggets',
 1610612744: 'Golden State Warriors',
 1610612745: 'Houston Rockets',
 1610612746: 'Los Angeles Clippers',
 1610612747: 'Los Angeles Lakers',
 1610612748: 'Miami Heat',
 1610612749: 'Milwaukee Bucks',
 1610612750: 'Minnesota Timberwolves',
 1610612751: 'Brooklyn Nets',
 1610612752: 'New York Knicks',
 1610612753: 'Orlando Magic',
 1610612754: 'Indiana Pacers',
 1610612755: 'Philadelphia 76ers',
 1610612756: 'Phoenix Suns',
 1610612757: 'Portland Trail Blazers',
 1610612758: 'Sacramento Kings',
 1610612759: 'San Antonio Spurs',
 1610612760: 'Oklahoma City Thunder',
 1610612761: 'Toronto Raptors',
 1610612762: 'Utah Jazz',
 1610612763: 'Memphis Grizzlies',
 1610612764: 'Washington Wizards',
 1610612765: 'Detroit Pistons',
 1610612766: 'Charlotte Hornets'}

# --- 4. Simuler une saison (exemple 2023-2024)

In [7]:

odds_path = os.path.join(DATA_ODDS_HISTORY_DIR, "nba_2023_2024.csv")
odds_df = pd.read_csv(odds_path)

# Fusion des données
merged = match_odds_with_dataset(odds_df, nba_df, team_id_map)
cleaned_merged = clean_merged_matches(merged)

cleaned_merged

Exemples de clés de match dans odds_df (tolérance date):
0    (2024-06-17, boston celtics, dallas mavericks)
1    (2024-06-14, dallas mavericks, boston celtics)
2    (2024-06-12, dallas mavericks, boston celtics)
3    (2024-06-09, boston celtics, dallas mavericks)
4    (2024-06-06, boston celtics, dallas mavericks)
Name: match_key, dtype: object

Exemples de clés de match dans nba_df:
58976     (2023-10-24, denver nuggets, los angeles lakers)
58978    (2023-10-24, golden state warriors, phoenix suns)
58980       (2023-10-25, charlotte hornets, atlanta hawks)
58982     (2023-10-25, indiana pacers, washington wizards)
58984        (2023-10-25, new york knicks, boston celtics)
Name: match_key, dtype: object

Nombre de lignes fusionnées: 5182
Nombre de correspondances réussies: 2624
Nombre de correspondances échouées: 2558

IDs manquants TEAM_ID: []
IDs manquants OPP_TEAM_ID: []

,date,match_key,GAME_ID,TEAM_ID,GAME_DATE,OPP_TEAM_ID,SEASON,IS_HOME,IS_WIN,ROLL_HOME_WINRATE_3,ROLL_AWAY_WINRATE_3,ROLL_HOME_WINRATE_5,ROLL_AWAY_WINRATE_5,ROLL_HOME_WINRATE_10,ROLL_AWAY_WINRATE_10,ROLL_HOME_WINRATE_25,ROLL_AWAY_WINRATE_25,ROLL_HOME_WINRATE_50,ROLL_AWAY_WINRATE_50,ROLL_HOME_WINRATE_100,ROLL_AWAY_WINRATE_100,ROLL_HOME_WINRATE_200,ROLL_AWAY_WINRATE_200,ROLL_WIN_RATIO_3,ROLL_WIN_RATIO_5,ROLL_WIN_RATIO_10,ROLL_WIN_RATIO_25,ROLL_WIN_RATIO_50,ROLL_WIN_RATIO_100,ROLL_WIN_RATIO_200,WIN_STREAK,HOME_WIN_STREAK,AWAY_WIN_STREAK,DAYS_SINCE_LAST_GAME,OPP_DAYS_SINCE_LAST_GAME,REST_ADVANTAGE,ROLL_HOME_REST_ADV_3,ROLL_AWAY_REST_ADV_3,ROLL_HOME_REST_ADV_5,ROLL_AWAY_REST_ADV_5,ROLL_HOME_REST_ADV_10,ROLL_AWAY_REST_ADV_10,ROLL_HOME_REST_ADV_25,ROLL_AWAY_REST_ADV_25,ROLL_HOME_REST_ADV_50,ROLL_AWAY_REST_ADV_50,ROLL_HOME_REST_ADV_100,ROLL_AWAY_REST_ADV_100,ROLL_HOME_REST_ADV_200,ROLL_AWAY_REST_ADV_200,H2H_LAST_3_DIFF,H2H_LAST_3_WINRATE,H2H_LAST_3_COUNT,H2H_LAST_5_DIFF,H2H_LAST_5_WINRATE,H2H_LAST_5_COUNT,H2H_LAST_10_DIFF,H2H_LAST_10_WINRATE,H2H_LAST_10_COUNT,H2H_LAST_25_DIFF,H2H_LAST_25_WINRATE,H2H_LAST_25_COUNT,H2H_LAST_50_DIFF,H2H_LAST_50_WINRATE,H2H_LAST_50_COUNT,H2H_LAST_100_DIFF,H2H_LAST_100_WINRATE,H2H_LAST_100_COUNT,H2H_LAST_200_DIFF,H2H_LAST_200_WINRATE,H2H_LAST_200_COUNT,H2H_SEASON_WINS,H2H_SEASON_MATCHES,H2H_SEASON_WINRATE,H2H_WIN_STREAK,ELO_PRE,OPP_ELO_PRE,ELO_PRE_SEASON,OPP_ELO_PRE_SEASON,TEAM_NAME,OPPONENT_NAME,ODDS,OPP_ODDS
0,2024-06-18,"(2024-06-17, boston celtics, dallas mavericks)",0042300405,1610612738,2024-06-17,1610612742,2023-24,1.0,1.0,1.000000,0.500000,1.000000,0.666667,1.000000,0.800000,0.812500,0.777778,0.880000,0.760000,0.882353,0.693878,0.794118,0.653061,0.666667,0.8,0.9,0.80,0.82,0.79,0.725,0.0,0.0,5.0,3.0,3.0,0.0,0.0,0.000000,-43.5,0.000000,-38.600000,0.000000,-38.375000,-2.000000,-45.120000,-61.120000,-93.568627,-120.020408,-93.401961,-112.316327,1.0,0.666667,3.0,3.0,0.8,5.0,4.0,0.7,10.0,3.0,0.56,25.0,-8.0,0.420000,50.0,-10.0,0.403846,52.0,-10.0,0.403846,52.0,5.0,6.0,0.833333,0.0,1767.087143,1677.852091,1753.902270,1677.339943,boston celtics,dallas mavericks,1.32,2.93
1,2024-06-18,"(2024-06-17, boston celtics, dallas mavericks)",0042300405,1610612742,2024-06-17,1610612738,2023-24,0.0,0.0,0.500000,0.000000,0.500000,0.333333,0.600000,0.600000,0.545455,0.642857,0.695652,0.629630,0.600000,0.600000,0.602041,0.480392,0.333333,0.4,0.6,0.60,0.66,0.60,0.540,1.0,0.0,1.0,3.0,3.0,0.0,0.0,0.000000,0.0,-30.000000,0.000000,-39.600000,-2.909091,-39.214286,-37.956522,-68.814815,-101.160000,-108.480000,-113.316327,-94.235294,-1.0,0.333333,3.0,-3.0,0.2,5.0,-4.0,0.3,10.0,-3.0,0.44,25.0,8.0,0.580000,50.0,10.0,0.596154,52.0,10.0,0.596154,52.0,1.0,6.0,0.166667,1.0,1677.852091,1767.087143,1677.339943,1753.902270,dallas mavericks,boston celtics,2.93,1.32
2,2024-06-15,"(2024-06-14, dallas mavericks, boston celtics)",0042300404,1610612738,2024-06-14,1610612742,2023-24,0.0,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.812500,0.888889,0.884615,0.791667,0.865385,0.708333,0.794118,0.663265,1.000000,1.0,1.0,0.84,0.84,0.79,0.730,10.0,11.0,5.0,2.0,2.0,0.0,-43.5,0.000000,-43.5,0.000000,-38.600000,0.000000,-38.375000,-16.555556,-46.230769,-63.666667,-91.769231,-122.520833,-93.401961,-113.765306,3.0,1.000000,3.0,5.0,1.0,5.0,4.0,0.7,10.0,3.0,0.56,25.0,-8.0,0.420000,50.0,-9.0,0.411765,51.0,-9.0,0.411765,51.0,5.0,5.0,1.000000,7.0,1783.097754,1662.340023,1769.493132,1662.245687,boston celtics,dallas mavericks,1.76,1.87
3,2024-06-15,"(2024-06-14, dallas mavericks, boston celtics)",0042300404,1610612742,2024-06-14,1610612738,2023-24,1.0,1.0,0.000000,0.000000,0.000000,0.333333,0.500000,0.666667,0.545455,0.642857,0.695652,0.629630,0.591837,0.607843,0.597938,0.485437,0.000000,0.2,0.6,0.60,0.66,0.60,0.540,0.0,0.0,0.0,2.0,2.0,0.0,0.0,-45.000000,0.0,-30.000000,0.000000,-33.000000,-3.363636,-39.214286,-40.913043,-68.814815,-103.224490,-110.686275,-114.484536,-93.320388,-3.0,0.000000,3.0,-5.0,0.0,5.0,-4.0,0.3,10.0,-3.0,0.44,25.0,8.0,0.580000,50.0,9.0,0.588235,51.0,9.0,0.588235,51.0,0.0,5.0,0.000000,0.0,1662.340023,1783.097754,1662.245687,1769.493132,dallas mavericks,boston celtics,1.87,1.76
4,2024-06-13,"(2024-06-12, dallas mavericks, boston celtics)",0042300403,1610612738,2024-06-12,1610612742,2023-24,0.0,1.0,1.000000,1.000000,1.000000,1.000000,0.833333,1.000000,0.812500,0.888889,0.851852,0.782609,0.865385,0.708333,0.796117,0.659794,1.000000,1.0,0.9,0.84,0.82,0.79,0.730,9.0,11.0,4.0,3.0,3.0,0.0,-43.5,0.000000,-29.0,0.000000,-32.166667,0.000000,-38.375000,-23.111111,-45.851852,-66.434783,-91.769231,-122.520833,-93.669903,-114.938144,3.0,1.000000,3.0,5.0,1.0,5.0,2.0,0.6,10.0,1.0,0.52,25.0,-10.0,0.400000,50.0,-10.0,0.400000,50.0,-10.0,0.400000,50.0,4.0,4.0,1.000000,6.0,1774.586274,1670.584328,1760.520679,1670.929911,boston celtics,dallas mavericks,2.09,1.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2619,2023-11-05,"(2023-11-05, detroit pistons, phoenix suns)",0022300140,1610612765,2023-11-05,1610612756,2023-24,1.0,0.0,0.000000,0.000000,0.500000,0.333333,0.250000,0.333333,0.166667,0.153846,0.200000,0.200000,0.240000,0.220000,0.287129,0.212121,0.000000,0.4,0.3,0.16,0.20,0.23,0.250,0.0,0.0,0.0,3.0,274.0,-271.0,-238.0,-252.500000,-219.5,-245.000000,-130.250000,-133.333333,-94.333333,-90.230769,-80.800000,-101.880000,-95.420000,-143.780000,-97.564356,-142.424242,-3.0,0.000000,3.0,-5.0,0.0,5.0,0.0,0.5,10.0,3.0,0.56,25.0,5.0,0.555556,45.0,5.0,0.555556,45.0,5.0,0.555556,45.0,0.0,0.0,0.000000,0.0,1261.138470,1540.133357,1478.417216,1476.192935,detroit pistons,phoenix suns,2.12,1.58
2620,2023-11-04,"(2023-11-04, philadelphia 76ers, phoenix suns)",0022300132,1610612755,2023-11-04,1610612756,2023-24,1.0,1.0,1.000000,1.000000,1.000000,0.333333,0.600000,0.400000,0.727273,0.500000,0.695652,0.629630,0.700000,0.600000,0.640000,0.610000,1.000000,0.6,0.5,0.60,0.66,0.65,0.625,3.0,4.0,0.0,2.0,224.0,-222.0,-116.5,-209.000000,-116.5,-83.666667,-46.600000,-50.200000,-38.909091,-54.928571,-66.217391,-66.111111,-105.860000,-111.700000,-100.210000,-97.360000,-1.0,0.333333,3.0,-3.0,0.2,5.0,-4.0,0.3,10.0,-3.0,0.44,25.0,-9.0,0.400000,45.0,-9.0,0.400000,45.0,-9.0,0.400000,45.0,0.0,0.0,0.000000,0.0,1658.197344,1548.197635,1523.152184,1486.568427,philadelphia 76ers,phoenix suns,1.33,2.69
2621,2023-11-04,"(2023-11-04, philadelphia 76ers, phoenix suns)",0022300132,1610612756,2023-11-04,1610612755,2023-24,0.0,0.0,0.333333,0.500000,0.333333,0.500000,0.500000,0.250000,0.666667,0.500000,0.615385,0.541667,0.647059,0.408163,0.712871,0.555556,0.333333,0.4,0.4,0.60,0.58,0.53,0.635,0.0,0.0,0.0,2.0,224.0,-222.0,-140.0,NaN,-140.0,-129.500000,-70.000000,-64.750000,-55.000000,-42.400000,-87.423077,-55.333333,-116.588235,-92.877551,-108.346535,-86.929293,1.0,0.666667,3.0,3.0,0.8,5.0,4.0,0.7,10.0,3.0,0.56,25.0,9.0,0.600000,45.0,9.0,0.600000,45.0,9.0,0.600000,45.0,0.0,0.0,0.000000,1.0,1548.197635,1658.197344,1486.568427,1523.152184,phoenix suns,philadelphia 76ers,2.69,1.33
2622,2023-10-29,"(2023-10-29, oklahoma city thunder, denver nug...",0022300095,1610612743,2023-10-29,1610612760,2023-24,0.0,1.0,1.000000,1.000000,1.000000,1.000000,0.800000,1.000000,0.923077,0.583333,0.833333,0.538462,0.846154,0.520833,0.710000,0.530000,1.000000,1.0,0.9,0.76,0.68,0.69,0.620,5.0,6.0,3.0,2.0,280.0,-278.0,-10.5,-235.000000,-10.5,-78.333333,-23.800000,-47.000000,-32.461538,-29.666667,-67.791667,-47.653846,-105.596154,-96.833333,-105.600000,-93.970000,1.0,0.666667,3.0,3.0,0.8,5.0,4.0,0.7,10.0,11.0,0.72,25.0,0.0,0.500000,50.0,8.0,0.542553,94.0,8.0,0.542553,94.0,0.0,0.0,0.000000,0.0,1703.394033,1514.233320,1523.186628,1523.185198,denver nuggets,oklahoma city thunder,1.54,2.15
2623,2023-10-29,"(2023-10-29, oklahoma city thunder, denver nug...",0022300095,1610612760,2023-10-29,1610612743,2023-24,1.0,0.0,0.500000,0.666667,1.000000,0.750000,0.666667,0.571429,0.700000,0.533333,0.636364,0.500000,0.574468,0.377358,0.387755,0.333333,0.666667,0.8,0.6,0.60,0.56,0.47,0.360,2.0,2.0,1.0,2.0,280.0,-278.0,NaN,-159.666667,-110.0,-127.000000,-87.666667,-90.571429,-46.800000,-71.466667,-66.090909,-108.142857,-85.893617,-143.698113,-120.010204,-119.333333,-1.0,0.333333,3.0,-3.0,0.2,5.0,-4.0,0.3,10.0,-11.0,0.28,25.0,0.0,0.500000,50.0,-8.0,0.457447,94.0,-8.0,0.457447,94.0,0.0,0.0,0.000000,1.0,1514.233320,1703.394033,1523.185198,1523.186628,oklahoma city thunder,denver nuggets,2.15,1.54

In [8]:
# Simulation
bets = simulate_bets(
    merged_df=merged,
    model_pipeline=model,
    min_ev=0.05,
    bankroll=1000,
    max_risk=0.05
)

KeyError: "['ROLL_HOME_REST_ADV_3'] not in index"

In [ ]:

# Évaluation
results = evaluate_simulation(bets)
print("\nRésultats de la simulation 2023-2024:")
for k, v in results.items():
    print(f"{k}: {v}")

# Aperçu des paris
bets.head()