In [1]:
import pandas as pd
from datetime import datetime
from src.config import *
from src.utils import *
from src.predictions import build_prediction_rows

pd.set_option("display.max_columns", None)

# ⏱️ Start
start_time = datetime.now()
print("Start time:", start_time)

# 🔁 Charger le dataset complet avec toutes les colonnes nécessaires
dataset_path = get_latest_file(DATA_FINAL_DATASET_DIR)
full_df = pd.read_csv(dataset_path)
full_df["GAME_DATE"] = pd.to_datetime(full_df["GAME_DATE"])
print("Loaded dataset:", dataset_path)


# 🧪 Extraction des deux dernières lignes (réelles)
real_last_rows = full_df.sort_values("GAME_DATE").tail(2).copy()
real_match_date = real_last_rows["GAME_DATE"].iloc[0]

home_id = real_last_rows.loc[real_last_rows["IS_HOME"] == 1, "TEAM_ID"].values[0]
away_id = real_last_rows.loc[real_last_rows["IS_HOME"] == 0, "TEAM_ID"].values[0]
home_odds = real_last_rows.loc[real_last_rows["IS_HOME"] == 1, "ODDS"].values[0]
away_odds = real_last_rows.loc[real_last_rows["IS_HOME"] == 0, "ODDS"].values[0]


print(f"Match: HOME={home_id}, AWAY={away_id}, Date={real_match_date.date()}")

# 🧼 Dataset sans ces lignes
#cut_df = full_df[full_df["GAME_DATE"] < real_match_date].copy()

#remove 2 last rows
cut_df = full_df.iloc[:-2].copy()
 
# display(cut_df.tail(6))
# display(full_df.tail(6))

# 🔁 Reconstruction des lignes à prédire
predicted_rows = build_prediction_rows(home_team_id=home_id, away_team_id=away_id, home_odds=home_odds,away_odds=away_odds, dataset=cut_df, match_date=real_match_date)

# 🧹 Préparation des lignes pour comparaison
#drop_cols = features_to_roll + COLS_MATCH_REAL + COLS_TO_DROP_TARGET_IS_WIN


real_clean = real_last_rows #.drop(columns=drop_cols, errors='ignore').reset_index(drop=True)
pred_clean = predicted_rows #.drop(columns=drop_cols, errors='ignore').reset_index(drop=True)

# 📏 Alignement des colonnes
common_cols = [col for col in real_clean.columns if col in pred_clean.columns]
real_clean = real_clean[common_cols]
pred_clean = pred_clean[common_cols]

# 🔍 Comparaison for floats and ints
diff = (pred_clean - real_clean).abs().sum()
diff_summary = diff[diff > 0.001].sort_values(ascending=False)
print(f"\nNombre de colonnes différentes : {len(diff_summary)}")
print("Colonnes divergentes :", diff_summary.index.tolist())

display(diff_summary)

print("\nLigne prédite:")
display(pred_clean)
print("\nLigne réelle:")
display(real_clean)

# 🕒 Fin
end_time = datetime.now()
print("End time:", end_time)
print("Duration:", end_time - start_time)

Start time: 2025-06-06 20:54:52.279881
Loaded dataset: data\final_dataset\nba_features_final_2025-06-06_19-50-30.csv
Match: HOME=1610612754, AWAY=1610612752, Date=2025-05-31

Nombre de colonnes différentes : 0
Colonnes divergentes : []

Series([], dtype: float64)

Ligne prédite:

,IS_HOME,ROLL_fieldGoalsMade_traditional_3,ROLL_fieldGoalsMade_traditional_5,ROLL_fieldGoalsMade_traditional_10,ROLL_fieldGoalsMade_traditional_25,ROLL_fieldGoalsMade_traditional_50,ROLL_fieldGoalsMade_traditional_100,ROLL_fieldGoalsMade_traditional_200,ROLL_fieldGoalsAttempted_traditional_3,ROLL_fieldGoalsAttempted_traditional_5,ROLL_fieldGoalsAttempted_traditional_10,ROLL_fieldGoalsAttempted_traditional_25,ROLL_fieldGoalsAttempted_traditional_50,ROLL_fieldGoalsAttempted_traditional_100,ROLL_fieldGoalsAttempted_traditional_200,ROLL_threePointersMade_traditional_3,ROLL_threePointersMade_traditional_5,ROLL_threePointersMade_traditional_10,ROLL_threePointersMade_traditional_25,ROLL_threePointersMade_traditional_50,ROLL_threePointersMade_traditional_100,ROLL_threePointersMade_traditional_200,ROLL_threePointersAttempted_traditional_3,ROLL_threePointersAttempted_traditional_5,ROLL_threePointersAttempted_traditional_10,ROLL_threePointersAttempted_traditional_25,ROLL_threePointersAttempted_traditional_50,ROLL_threePointersAttempted_traditional_100,ROLL_threePointersAttempted_traditional_200,ROLL_freeThrowsMade_traditional_3,ROLL_freeThrowsMade_traditional_5,ROLL_freeThrowsMade_traditional_10,ROLL_freeThrowsMade_traditional_25,ROLL_freeThrowsMade_traditional_50,ROLL_freeThrowsMade_traditional_100,ROLL_freeThrowsMade_traditional_200,ROLL_freeThrowsAttempted_traditional_3,ROLL_freeThrowsAttempted_traditional_5,ROLL_freeThrowsAttempted_traditional_10,ROLL_freeThrowsAttempted_traditional_25,ROLL_freeThrowsAttempted_traditional_50,ROLL_freeThrowsAttempted_traditional_100,ROLL_freeThrowsAttempted_traditional_200,ROLL_reboundsOffensive_traditional_3,ROLL_reboundsOffensive_traditional_5,ROLL_reboundsOffensive_traditional_10,ROLL_reboundsOffensive_traditional_25,ROLL_reboundsOffensive_traditional_50,ROLL_reboundsOffensive_traditional_100,ROLL_reboundsOffensive_traditional_200,ROLL_reboundsDefensive_traditional_3,ROLL_reboundsDefensive_traditional_5,ROLL_reboundsDefensive_traditional_10,ROLL_reboundsDefensive_traditional_25,ROLL_reboundsDefensive_traditional_50,ROLL_reboundsDefensive_traditional_100,ROLL_reboundsDefensive_traditional_200,ROLL_reboundsTotal_traditional_3,ROLL_reboundsTotal_traditional_5,ROLL_reboundsTotal_traditional_10,ROLL_reboundsTotal_traditional_25,ROLL_reboundsTotal_traditional_50,ROLL_reboundsTotal_traditional_100,ROLL_reboundsTotal_traditional_200,ROLL_assists_traditional_3,ROLL_assists_traditional_5,ROLL_assists_traditional_10,ROLL_assists_traditional_25,ROLL_assists_traditional_50,ROLL_assists_traditional_100,ROLL_assists_traditional_200,ROLL_steals_traditional_3,ROLL_steals_traditional_5,ROLL_steals_traditional_10,ROLL_steals_traditional_25,ROLL_steals_traditional_50,ROLL_steals_traditional_100,ROLL_steals_traditional_200,ROLL_blocks_traditional_3,ROLL_blocks_traditional_5,ROLL_blocks_traditional_10,ROLL_blocks_traditional_25,ROLL_blocks_traditional_50,ROLL_blocks_traditional_100,ROLL_blocks_traditional_200,ROLL_turnovers_traditional_3,ROLL_turnovers_traditional_5,ROLL_turnovers_traditional_10,ROLL_turnovers_traditional_25,ROLL_turnovers_traditional_50,ROLL_turnovers_traditional_100,ROLL_turnovers_traditional_200,ROLL_foulsPersonal_traditional_3,ROLL_foulsPersonal_traditional_5,ROLL_foulsPersonal_traditional_10,ROLL_foulsPersonal_traditional_25,ROLL_foulsPersonal_traditional_50,ROLL_foulsPersonal_traditional_100,ROLL_foulsPersonal_traditional_200,ROLL_points_traditional_3,ROLL_points_traditional_5,ROLL_points_traditional_10,ROLL_points_traditional_25,ROLL_points_traditional_50,ROLL_points_traditional_100,ROLL_points_traditional_200,ROLL_MINUTES_PLAYED_3,ROLL_MINUTES_PLAYED_5,ROLL_MINUTES_PLAYED_10,ROLL_MINUTES_PLAYED_25,ROLL_MINUTES_PLAYED_50,ROLL_MINUTES_PLAYED_100,ROLL_MINUTES_PLAYED_200,ROLL_pointsOffTurnovers_misc_3,ROLL_pointsOffTurnovers_misc_5,ROLL_pointsOffTurnovers_misc_10,ROLL_pointsOffTurnovers_misc_25,ROLL_pointsOffTurnovers_misc_50,ROLL_pointsOffTurnovers_misc_100,ROLL_pointsOffTurnovers_misc_200,ROLL_pointsSecondChance_misc_3,ROLL_pointsSecondChance_misc_5,ROLL_pointsSecondChance_misc_10,ROLL_pointsSecondChance_misc_25,ROLL_pointsSecondChance_misc_50,ROLL_pointsSecondChance_misc_100,ROLL_pointsSecondChance_misc_200,ROLL_pointsFastBreak_misc_3,ROLL_pointsFastBreak_misc_5,ROLL_pointsFastBreak_misc_10,ROLL_pointsFastBreak_misc_25,ROLL_pointsFastBreak_misc_50,ROLL_pointsFastBreak_misc_100,ROLL_pointsFastBreak_misc_200,ROLL_pointsPaint_misc_3,ROLL_pointsPaint_misc_5,ROLL_pointsPaint_misc_10,ROLL_pointsPaint_misc_25,ROLL_pointsPaint_misc_50,ROLL_pointsPaint_misc_100,ROLL_pointsPaint_misc_200,ROLL_blocksAgainst_misc_3,ROLL_blocksAgainst_misc_5,ROLL_blocksAgainst_misc_10,ROLL_blocksAgainst_misc_25,ROLL_blocksAgainst_misc_50,ROLL_blocksAgainst_misc_100,ROLL_blocksAgainst_misc_200,ROLL_offensiveRating_advanced_3,ROLL_offensiveRating_advanced_5,ROLL_offensiveRating_advanced_10,ROLL_offensiveRating_advanced_25,ROLL_offensiveRating_advanced_50,ROLL_offensiveRating_advanced_100,ROLL_offensiveRating_advanced_200,ROLL_defensiveRating_advanced_3,ROLL_defensiveRating_advanced_5,ROLL_defensiveRating_advanced_10,ROLL_defensiveRating_advanced_25,ROLL_defensiveRating_advanced_50,ROLL_defensiveRating_advanced_100,ROLL_defensiveRating_advanced_200,ROLL_netRating_advanced_3,ROLL_netRating_advanced_5,ROLL_netRating_advanced_10,ROLL_netRating_advanced_25,ROLL_netRating_advanced_50,ROLL_netRating_advanced_100,ROLL_netRating_advanced_200,ROLL_assistPercentage_advanced_3,ROLL_assistPercentage_advanced_5,ROLL_assistPercentage_advanced_10,ROLL_assistPercentage_advanced_25,ROLL_assistPercentage_advanced_50,ROLL_assistPercentage_advanced_100,ROLL_assistPercentage_advanced_200,ROLL_assistToTurnover_advanced_3,ROLL_assistToTurnover_advanced_5,ROLL_assistToTurnover_advanced_10,ROLL_assistToTurnover_advanced_25,ROLL_assistToTurnover_advanced_50,ROLL_assistToTurnover_advanced_100,ROLL_assistToTurnover_advanced_200,ROLL_assistRatio_advanced_3,ROLL_assistRatio_advanced_5,ROLL_assistRatio_advanced_10,ROLL_assistRatio_advanced_25,ROLL_assistRatio_advanced_50,ROLL_assistRatio_advanced_100,ROLL_assistRatio_advanced_200,ROLL_offensiveReboundPercentage_advanced_3,ROLL_offensiveReboundPercentage_advanced_5,ROLL_offensiveReboundPercentage_advanced_10,ROLL_offensiveReboundPercentage_advanced_25,ROLL_offensiveReboundPercentage_advanced_50,ROLL_offensiveReboundPercentage_advanced_100,ROLL_offensiveReboundPercentage_advanced_200,ROLL_defensiveReboundPercentage_advanced_3,ROLL_defensiveReboundPercentage_advanced_5,ROLL_defensiveReboundPercentage_advanced_10,ROLL_defensiveReboundPercentage_advanced_25,ROLL_defensiveReboundPercentage_advanced_50,ROLL_defensiveReboundPercentage_advanced_100,ROLL_defensiveReboundPercentage_advanced_200,ROLL_reboundPercentage_advanced_3,ROLL_reboundPercentage_advanced_5,ROLL_reboundPercentage_advanced_10,ROLL_reboundPercentage_advanced_25,ROLL_reboundPercentage_advanced_50,ROLL_reboundPercentage_advanced_100,ROLL_reboundPercentage_advanced_200,ROLL_turnoverRatio_advanced_3,ROLL_turnoverRatio_advanced_5,ROLL_turnoverRatio_advanced_10,ROLL_turnoverRatio_advanced_25,ROLL_turnoverRatio_advanced_50,ROLL_turnoverRatio_advanced_100,ROLL_turnoverRatio_advanced_200,ROLL_effectiveFieldGoalPercentage_advanced_3,ROLL_effectiveFieldGoalPercentage_advanced_5,ROLL_effectiveFieldGoalPercentage_advanced_10,ROLL_effectiveFieldGoalPercentage_advanced_25,ROLL_effectiveFieldGoalPercentage_advanced_50,ROLL_effectiveFieldGoalPercentage_advanced_100,ROLL_effectiveFieldGoalPercentage_advanced_200,ROLL_trueShootingPercentage_advanced_3,ROLL_trueShootingPercentage_advanced_5,ROLL_trueShootingPercentage_advanced_10,ROLL_trueShootingPercentage_advanced_25,ROLL_trueShootingPercentage_advanced_50,ROLL_trueShootingPercentage_advanced_100,ROLL_trueShootingPercentage_advanced_200,ROLL_usagePercentage_advanced_3,ROLL_usagePercentage_advanced_5,ROLL_usagePercentage_advanced_10,ROLL_usagePercentage_advanced_25,ROLL_usagePercentage_advanced_50,ROLL_usagePercentage_advanced_100,ROLL_usagePercentage_advanced_200,ROLL_estimatedPace_advanced_3,ROLL_estimatedPace_advanced_5,ROLL_estimatedPace_advanced_10,ROLL_estimatedPace_advanced_25,ROLL_estimatedPace_advanced_50,ROLL_estimatedPace_advanced_100,ROLL_estimatedPace_advanced_200,ROLL_pace_advanced_3,ROLL_pace_advanced_5,ROLL_pace_advanced_10,ROLL_pace_advanced_25,ROLL_pace_advanced_50,ROLL_pace_advanced_100,ROLL_pace_advanced_200,ROLL_possessions_advanced_3,ROLL_possessions_advanced_5,ROLL_possessions_advanced_10,ROLL_possessions_advanced_25,ROLL_possessions_advanced_50,ROLL_possessions_advanced_100,ROLL_possessions_advanced_200,ROLL_PIE_advanced_3,ROLL_PIE_advanced_5,ROLL_PIE_advanced_10,ROLL_PIE_advanced_25,ROLL_PIE_advanced_50,ROLL_PIE_advanced_100,ROLL_PIE_advanced_200,ROLL_effectiveFieldGoalPercentage_fourfactors_3,ROLL_effectiveFieldGoalPercentage_fourfactors_5,ROLL_effectiveFieldGoalPercentage_fourfactors_10,ROLL_effectiveFieldGoalPercentage_fourfactors_25,ROLL_effectiveFieldGoalPercentage_fourfactors_50,ROLL_effectiveFieldGoalPercentage_fourfactors_100,ROLL_effectiveFieldGoalPercentage_fourfactors_200,ROLL_freeThrowAttemptRate_fourfactors_3,ROLL_freeThrowAttemptRate_fourfactors_5,ROLL_freeThrowAttemptRate_fourfactors_10,ROLL_freeThrowAttemptRate_fourfactors_25,ROLL_freeThrowAttemptRate_fourfactors_50,ROLL_freeThrowAttemptRate_fourfactors_100,ROLL_freeThrowAttemptRate_fourfactors_200,ROLL_teamTurnoverPercentage_fourfactors_3,ROLL_teamTurnoverPercentage_fourfactors_5,ROLL_teamTurnoverPercentage_fourfactors_10,ROLL_teamTurnoverPercentage_fourfactors_25,ROLL_teamTurnoverPercentage_fourfactors_50,ROLL_teamTurnoverPercentage_fourfactors_100,ROLL_teamTurnoverPercentage_fourfactors_200,ROLL_oppEffectiveFieldGoalPercentage_fourfactors_3,ROLL_oppEffectiveFieldGoalPercentage_fourfactors_5,ROLL_oppEffectiveFieldGoalPercentage_fourfactors_10,ROLL_oppEffectiveFieldGoalPercentage_fourfactors_25,ROLL_oppEffectiveFieldGoalPercentage_fourfactors_50,ROLL_oppEffectiveFieldGoalPercentage_fourfactors_100,ROLL_oppEffectiveFieldGoalPercentage_fourfactors_200,ROLL_oppFreeThrowAttemptRate_fourfactors_3,ROLL_oppFreeThrowAttemptRate_fourfactors_5,ROLL_oppFreeThrowAttemptRate_fourfactors_10,ROLL_oppFreeThrowAttemptRate_fourfactors_25,ROLL_oppFreeThrowAttemptRate_fourfactors_50,ROLL_oppFreeThrowAttemptRate_fourfactors_100,ROLL_oppFreeThrowAttemptRate_fourfactors_200,ROLL_oppTeamTurnoverPercentage_fourfactors_3,ROLL_oppTeamTurnoverPercentage_fourfactors_5,ROLL_oppTeamTurnoverPercentage_fourfactors_10,ROLL_oppTeamTurnoverPercentage_fourfactors_25,ROLL_oppTeamTurnoverPercentage_fourfactors_50,ROLL_oppTeamTurnoverPercentage_fourfactors_100,ROLL_oppTeamTurnoverPercentage_fourfactors_200,ROLL_oppOffensiveReboundPercentage_fourfactors_3,ROLL_oppOffensiveReboundPercentage_fourfactors_5,ROLL_oppOffensiveReboundPercentage_fourfactors_10,ROLL_oppOffensiveReboundPercentage_fourfactors_25,ROLL_oppOffensiveReboundPercentage_fourfactors_50,ROLL_oppOffensiveReboundPercentage_fourfactors_100,ROLL_oppOffensiveReboundPercentage_fourfactors_200,ROLL_foulsDrawn_misc_3,ROLL_foulsDrawn_misc_5,ROLL_foulsDrawn_misc_10,ROLL_foulsDrawn_misc_25,ROLL_foulsDrawn_misc_50,ROLL_foulsDrawn_misc_100,ROLL_foulsDrawn_misc_200,ROLL_percentageFieldGoalsAttempted2pt_scoring_3,ROLL_percentageFieldGoalsAttempted2pt_scoring_5,ROLL_percentageFieldGoalsAttempted2pt_scoring_10,ROLL_percentageFieldGoalsAttempted2pt_scoring_25,ROLL_percentageFieldGoalsAttempted2pt_scoring_50,ROLL_percentageFieldGoalsAttempted2pt_scoring_100,ROLL_percentageFieldGoalsAttempted2pt_scoring_200,ROLL_percentageFieldGoalsAttempted3pt_scoring_3,ROLL_percentageFieldGoalsAttempted3pt_scoring_5,ROLL_percentageFieldGoalsAttempted3pt_scoring_10,ROLL_percentageFieldGoalsAttempted3pt_scoring_25,ROLL_percentageFieldGoalsAttempted3pt_scoring_50,ROLL_percentageFieldGoalsAttempted3pt_scoring_100,ROLL_percentageFieldGoalsAttempted3pt_scoring_200,ROLL_percentagePoints2pt_scoring_3,ROLL_percentagePoints2pt_scoring_5,ROLL_percentagePoints2pt_scoring_10,ROLL_percentagePoints2pt_scoring_25,ROLL_percentagePoints2pt_scoring_50,ROLL_percentagePoints2pt_scoring_100,ROLL_percentagePoints2pt_scoring_200,ROLL_percentagePointsMidrange2pt_scoring_3,ROLL_percentagePointsMidrange2pt_scoring_5,ROLL_percentagePointsMidrange2pt_scoring_10,ROLL_percentagePointsMidrange2pt_scoring_25,ROLL_percentagePointsMidrange2pt_scoring_50,ROLL_percentagePointsMidrange2pt_scoring_100,ROLL_percentagePointsMidrange2pt_scoring_200,ROLL_percentagePoints3pt_scoring_3,ROLL_percentagePoints3pt_scoring_5,ROLL_percentagePoints3pt_scoring_10,ROLL_percentagePoints3pt_scoring_25,ROLL_percentagePoints3pt_scoring_50,ROLL_percentagePoints3pt_scoring_100,ROLL_percentagePoints3pt_scoring_200,ROLL_percentagePointsFastBreak_scoring_3,ROLL_percentagePointsFastBreak_scoring_5,ROLL_percentagePointsFastBreak_scoring_10,ROLL_percentagePointsFastBreak_scoring_25,ROLL_percentagePointsFastBreak_scoring_50,ROLL_percentagePointsFastBreak_scoring_100,ROLL_percentagePointsFastBreak_scoring_200,ROLL_percentagePointsFreeThrow_scoring_3,ROLL_percentagePointsFreeThrow_scoring_5,ROLL_percentagePointsFreeThrow_scoring_10,ROLL_percentagePointsFreeThrow_scoring_25,ROLL_percentagePointsFreeThrow_scoring_50,ROLL_percentagePointsFreeThrow_scoring_100,ROLL_percentagePointsFreeThrow_scoring_200,ROLL_percentagePointsOffTurnovers_scoring_3,ROLL_percentagePointsOffTurnovers_scoring_5,ROLL_percentagePointsOffTurnovers_scoring_10,ROLL_percentagePointsOffTurnovers_scoring_25,ROLL_percentagePointsOffTurnovers_scoring_50,ROLL_percentagePointsOffTurnovers_scoring_100,ROLL_percentagePointsOffTurnovers_scoring_200,ROLL_percentagePointsPaint_scoring_3,ROLL_percentagePointsPaint_scoring_5,ROLL_percentagePointsPaint_scoring_10,ROLL_percentagePointsPaint_scoring_25,ROLL_percentagePointsPaint_scoring_50,ROLL_percentagePointsPaint_scoring_100,ROLL_percentagePointsPaint_scoring_200,ROLL_percentageAssisted2pt_scoring_3,ROLL_percentageAssisted2pt_scoring_5,ROLL_percentageAssisted2pt_scoring_10,ROLL_percentageAssisted2pt_scoring_25,ROLL_percentageAssisted2pt_scoring_50,ROLL_percentageAssisted2pt_scoring_100,ROLL_percentageAssisted2pt_scoring_200,ROLL_percentageUnassisted2pt_scoring_3,ROLL_percentageUnassisted2pt_scoring_5,ROLL_percentageUnassisted2pt_scoring_10,ROLL_percentageUnassisted2pt_scoring_25,ROLL_percentageUnassisted2pt_scoring_50,ROLL_percentageUnassisted2pt_scoring_100,ROLL_percentageUnassisted2pt_scoring_200,ROLL_percentageAssisted3pt_scoring_3,ROLL_percentageAssisted3pt_scoring_5,ROLL_percentageAssisted3pt_scoring_10,ROLL_percentageAssisted3pt_scoring_25,ROLL_percentageAssisted3pt_scoring_50,ROLL_percentageAssisted3pt_scoring_100,ROLL_percentageAssisted3pt_scoring_200,ROLL_percentageUnassisted3pt_scoring_3,ROLL_percentageUnassisted3pt_scoring_5,ROLL_percentageUnassisted3pt_scoring_10,ROLL_percentageUnassisted3pt_scoring_25,ROLL_percentageUnassisted3pt_scoring_50,ROLL_percentageUnassisted3pt_scoring_100,ROLL_percentageUnassisted3pt_scoring_200,ROLL_percentageAssistedFGM_scoring_3,ROLL_percentageAssistedFGM_scoring_5,ROLL_percentageAssistedFGM_scoring_10,ROLL_percentageAssistedFGM_scoring_25,ROLL_percentageAssistedFGM_scoring_50,ROLL_percentageAssistedFGM_scoring_100,ROLL_percentageAssistedFGM_scoring_200,ROLL_percentageUnassistedFGM_scoring_3,ROLL_percentageUnassistedFGM_scoring_5,ROLL_percentageUnassistedFGM_scoring_10,ROLL_percentageUnassistedFGM_scoring_25,ROLL_percentageUnassistedFGM_scoring_50,ROLL_percentageUnassistedFGM_scoring_100,ROLL_percentageUnassistedFGM_scoring_200,ROLL_threePointersPercentage_traditional_3,ROLL_threePointersPercentage_traditional_5,ROLL_threePointersPercentage_traditional_10,ROLL_threePointersPercentage_traditional_25,ROLL_threePointersPercentage_traditional_50,ROLL_threePointersPercentage_traditional_100,ROLL_threePointersPercentage_traditional_200,ROLL_freeThrowsPercentage_traditional_3,ROLL_freeThrowsPercentage_traditional_5,ROLL_freeThrowsPercentage_traditional_10,ROLL_freeThrowsPercentage_traditional_25,ROLL_freeThrowsPercentage_traditional_50,ROLL_freeThrowsPercentage_traditional_100,ROLL_freeThrowsPercentage_traditional_200,ROLL_percentageFieldGoalsMade_usage_3,ROLL_percentageFieldGoalsMade_usage_5,ROLL_percentageFieldGoalsMade_usage_10,ROLL_percentageFieldGoalsMade_usage_25,ROLL_percentageFieldGoalsMade_usage_50,ROLL_percentageFieldGoalsMade_usage_100,ROLL_percentageFieldGoalsMade_usage_200,ROLL_percentageFieldGoalsAttempted_usage_3,ROLL_percentageFieldGoalsAttempted_usage_5,ROLL_percentageFieldGoalsAttempted_usage_10,ROLL_percentageFieldGoalsAttempted_usage_25,ROLL_percentageFieldGoalsAttempted_usage_50,ROLL_percentageFieldGoalsAttempted_usage_100,ROLL_percentageFieldGoalsAttempted_usage_200,ROLL_percentageThreePointersMade_usage_3,ROLL_percentageThreePointersMade_usage_5,ROLL_percentageThreePointersMade_usage_10,ROLL_percentageThreePointersMade_usage_25,ROLL_percentageThreePointersMade_usage_50,ROLL_percentageThreePointersMade_usage_100,ROLL_percentageThreePointersMade_usage_200,ROLL_percentageThreePointersAttempted_usage_3,ROLL_percentageThreePointersAttempted_usage_5,ROLL_percentageThreePointersAttempted_usage_10,ROLL_percentageThreePointersAttempted_usage_25,ROLL_percentageThreePointersAttempted_usage_50,ROLL_percentageThreePointersAttempted_usage_100,ROLL_percentageThreePointersAttempted_usage_200,ROLL_percentageFreeThrowsMade_usage_3,ROLL_percentageFreeThrowsMade_usage_5,ROLL_percentageFreeThrowsMade_usage_10,ROLL_percentageFreeThrowsMade_usage_25,ROLL_percentageFreeThrowsMade_usage_50,ROLL_percentageFreeThrowsMade_usage_100,ROLL_percentageFreeThrowsMade_usage_200,ROLL_percentageFreeThrowsAttempted_usage_3,ROLL_percentageFreeThrowsAttempted_usage_5,ROLL_percentageFreeThrowsAttempted_usage_10,ROLL_percentageFreeThrowsAttempted_usage_25,ROLL_percentageFreeThrowsAttempted_usage_50,ROLL_percentageFreeThrowsAttempted_usage_100,ROLL_percentageFreeThrowsAttempted_usage_200,ROLL_percentageReboundsOffensive_usage_3,ROLL_percentageReboundsOffensive_usage_5,ROLL_percentageReboundsOffensive_usage_10,ROLL_percentageReboundsOffensive_usage_25,ROLL_percentageReboundsOffensive_usage_50,ROLL_percentageReboundsOffensive_usage_100,ROLL_percentageReboundsOffensive_usage_200,ROLL_percentageReboundsDefensive_usage_3,ROLL_percentageReboundsDefensive_usage_5,ROLL_percentageReboundsDefensive_usage_10,ROLL_percentageReboundsDefensive_usage_25,ROLL_percentageReboundsDefensive_usage_50,ROLL_percentageReboundsDefensive_usage_100,ROLL_percentageReboundsDefensive_usage_200,ROLL_percentageReboundsTotal_usage_3,ROLL_percentageReboundsTotal_usage_5,ROLL_percentageReboundsTotal_usage_10,ROLL_percentageReboundsTotal_usage_25,ROLL_percentageReboundsTotal_usage_50,ROLL_percentageReboundsTotal_usage_100,ROLL_percentageReboundsTotal_usage_200,ROLL_percentageAssists_usage_3,ROLL_percentageAssists_usage_5,ROLL_percentageAssists_usage_10,ROLL_percentageAssists_usage_25,ROLL_percentageAssists_usage_50,ROLL_percentageAssists_usage_100,ROLL_percentageAssists_usage_200,ROLL_percentageTurnovers_usage_3,ROLL_percentageTurnovers_usage_5,ROLL_percentageTurnovers_usage_10,ROLL_percentageTurnovers_usage_25,ROLL_percentageTurnovers_usage_50,ROLL_percentageTurnovers_usage_100,ROLL_percentageTurnovers_usage_200,ROLL_percentageSteals_usage_3,ROLL_percentageSteals_usage_5,ROLL_percentageSteals_usage_10,ROLL_percentageSteals_usage_25,ROLL_percentageSteals_usage_50,ROLL_percentageSteals_usage_100,ROLL_percentageSteals_usage_200,ROLL_percentageBlocks_usage_3,ROLL_percentageBlocks_usage_5,ROLL_percentageBlocks_usage_10,ROLL_percentageBlocks_usage_25,ROLL_percentageBlocks_usage_50,ROLL_percentageBlocks_usage_100,ROLL_percentageBlocks_usage_200,ROLL_percentageBlocksAllowed_usage_3,ROLL_percentageBlocksAllowed_usage_5,ROLL_percentageBlocksAllowed_usage_10,ROLL_percentageBlocksAllowed_usage_25,ROLL_percentageBlocksAllowed_usage_50,ROLL_percentageBlocksAllowed_usage_100,ROLL_percentageBlocksAllowed_usage_200,ROLL_percentagePersonalFouls_usage_3,ROLL_percentagePersonalFouls_usage_5,ROLL_percentagePersonalFouls_usage_10

Ligne réelle:

,IS_HOME,ROLL_fieldGoalsMade_traditional_3,ROLL_fieldGoalsMade_traditional_5,ROLL_fieldGoalsMade_traditional_10,ROLL_fieldGoalsMade_traditional_25,ROLL_fieldGoalsMade_traditional_50,ROLL_fieldGoalsMade_traditional_100,ROLL_fieldGoalsMade_traditional_200,ROLL_fieldGoalsAttempted_traditional_3,ROLL_fieldGoalsAttempted_traditional_5,ROLL_fieldGoalsAttempted_traditional_10,ROLL_fieldGoalsAttempted_traditional_25,ROLL_fieldGoalsAttempted_traditional_50,ROLL_fieldGoalsAttempted_traditional_100,ROLL_fieldGoalsAttempted_traditional_200,ROLL_threePointersMade_traditional_3,ROLL_threePointersMade_traditional_5,ROLL_threePointersMade_traditional_10,ROLL_threePointersMade_traditional_25,ROLL_threePointersMade_traditional_50,ROLL_threePointersMade_traditional_100,ROLL_threePointersMade_traditional_200,ROLL_threePointersAttempted_traditional_3,ROLL_threePointersAttempted_traditional_5,ROLL_threePointersAttempted_traditional_10,ROLL_threePointersAttempted_traditional_25,ROLL_threePointersAttempted_traditional_50,ROLL_threePointersAttempted_traditional_100,ROLL_threePointersAttempted_traditional_200,ROLL_freeThrowsMade_traditional_3,ROLL_freeThrowsMade_traditional_5,ROLL_freeThrowsMade_traditional_10,ROLL_freeThrowsMade_traditional_25,ROLL_freeThrowsMade_traditional_50,ROLL_freeThrowsMade_traditional_100,ROLL_freeThrowsMade_traditional_200,ROLL_freeThrowsAttempted_traditional_3,ROLL_freeThrowsAttempted_traditional_5,ROLL_freeThrowsAttempted_traditional_10,ROLL_freeThrowsAttempted_traditional_25,ROLL_freeThrowsAttempted_traditional_50,ROLL_freeThrowsAttempted_traditional_100,ROLL_freeThrowsAttempted_traditional_200,ROLL_reboundsOffensive_traditional_3,ROLL_reboundsOffensive_traditional_5,ROLL_reboundsOffensive_traditional_10,ROLL_reboundsOffensive_traditional_25,ROLL_reboundsOffensive_traditional_50,ROLL_reboundsOffensive_traditional_100,ROLL_reboundsOffensive_traditional_200,ROLL_reboundsDefensive_traditional_3,ROLL_reboundsDefensive_traditional_5,ROLL_reboundsDefensive_traditional_10,ROLL_reboundsDefensive_traditional_25,ROLL_reboundsDefensive_traditional_50,ROLL_reboundsDefensive_traditional_100,ROLL_reboundsDefensive_traditional_200,ROLL_reboundsTotal_traditional_3,ROLL_reboundsTotal_traditional_5,ROLL_reboundsTotal_traditional_10,ROLL_reboundsTotal_traditional_25,ROLL_reboundsTotal_traditional_50,ROLL_reboundsTotal_traditional_100,ROLL_reboundsTotal_traditional_200,ROLL_assists_traditional_3,ROLL_assists_traditional_5,ROLL_assists_traditional_10,ROLL_assists_traditional_25,ROLL_assists_traditional_50,ROLL_assists_traditional_100,ROLL_assists_traditional_200,ROLL_steals_traditional_3,ROLL_steals_traditional_5,ROLL_steals_traditional_10,ROLL_steals_traditional_25,ROLL_steals_traditional_50,ROLL_steals_traditional_100,ROLL_steals_traditional_200,ROLL_blocks_traditional_3,ROLL_blocks_traditional_5,ROLL_blocks_traditional_10,ROLL_blocks_traditional_25,ROLL_blocks_traditional_50,ROLL_blocks_traditional_100,ROLL_blocks_traditional_200,ROLL_turnovers_traditional_3,ROLL_turnovers_traditional_5,ROLL_turnovers_traditional_10,ROLL_turnovers_traditional_25,ROLL_turnovers_traditional_50,ROLL_turnovers_traditional_100,ROLL_turnovers_traditional_200,ROLL_foulsPersonal_traditional_3,ROLL_foulsPersonal_traditional_5,ROLL_foulsPersonal_traditional_10,ROLL_foulsPersonal_traditional_25,ROLL_foulsPersonal_traditional_50,ROLL_foulsPersonal_traditional_100,ROLL_foulsPersonal_traditional_200,ROLL_points_traditional_3,ROLL_points_traditional_5,ROLL_points_traditional_10,ROLL_points_traditional_25,ROLL_points_traditional_50,ROLL_points_traditional_100,ROLL_points_traditional_200,ROLL_MINUTES_PLAYED_3,ROLL_MINUTES_PLAYED_5,ROLL_MINUTES_PLAYED_10,ROLL_MINUTES_PLAYED_25,ROLL_MINUTES_PLAYED_50,ROLL_MINUTES_PLAYED_100,ROLL_MINUTES_PLAYED_200,ROLL_pointsOffTurnovers_misc_3,ROLL_pointsOffTurnovers_misc_5,ROLL_pointsOffTurnovers_misc_10,ROLL_pointsOffTurnovers_misc_25,ROLL_pointsOffTurnovers_misc_50,ROLL_pointsOffTurnovers_misc_100,ROLL_pointsOffTurnovers_misc_200,ROLL_pointsSecondChance_misc_3,ROLL_pointsSecondChance_misc_5,ROLL_pointsSecondChance_misc_10,ROLL_pointsSecondChance_misc_25,ROLL_pointsSecondChance_misc_50,ROLL_pointsSecondChance_misc_100,ROLL_pointsSecondChance_misc_200,ROLL_pointsFastBreak_misc_3,ROLL_pointsFastBreak_misc_5,ROLL_pointsFastBreak_misc_10,ROLL_pointsFastBreak_misc_25,ROLL_pointsFastBreak_misc_50,ROLL_pointsFastBreak_misc_100,ROLL_pointsFastBreak_misc_200,ROLL_pointsPaint_misc_3,ROLL_pointsPaint_misc_5,ROLL_pointsPaint_misc_10,ROLL_pointsPaint_misc_25,ROLL_pointsPaint_misc_50,ROLL_pointsPaint_misc_100,ROLL_pointsPaint_misc_200,ROLL_blocksAgainst_misc_3,ROLL_blocksAgainst_misc_5,ROLL_blocksAgainst_misc_10,ROLL_blocksAgainst_misc_25,ROLL_blocksAgainst_misc_50,ROLL_blocksAgainst_misc_100,ROLL_blocksAgainst_misc_200,ROLL_offensiveRating_advanced_3,ROLL_offensiveRating_advanced_5,ROLL_offensiveRating_advanced_10,ROLL_offensiveRating_advanced_25,ROLL_offensiveRating_advanced_50,ROLL_offensiveRating_advanced_100,ROLL_offensiveRating_advanced_200,ROLL_defensiveRating_advanced_3,ROLL_defensiveRating_advanced_5,ROLL_defensiveRating_advanced_10,ROLL_defensiveRating_advanced_25,ROLL_defensiveRating_advanced_50,ROLL_defensiveRating_advanced_100,ROLL_defensiveRating_advanced_200,ROLL_netRating_advanced_3,ROLL_netRating_advanced_5,ROLL_netRating_advanced_10,ROLL_netRating_advanced_25,ROLL_netRating_advanced_50,ROLL_netRating_advanced_100,ROLL_netRating_advanced_200,ROLL_assistPercentage_advanced_3,ROLL_assistPercentage_advanced_5,ROLL_assistPercentage_advanced_10,ROLL_assistPercentage_advanced_25,ROLL_assistPercentage_advanced_50,ROLL_assistPercentage_advanced_100,ROLL_assistPercentage_advanced_200,ROLL_assistToTurnover_advanced_3,ROLL_assistToTurnover_advanced_5,ROLL_assistToTurnover_advanced_10,ROLL_assistToTurnover_advanced_25,ROLL_assistToTurnover_advanced_50,ROLL_assistToTurnover_advanced_100,ROLL_assistToTurnover_advanced_200,ROLL_assistRatio_advanced_3,ROLL_assistRatio_advanced_5,ROLL_assistRatio_advanced_10,ROLL_assistRatio_advanced_25,ROLL_assistRatio_advanced_50,ROLL_assistRatio_advanced_100,ROLL_assistRatio_advanced_200,ROLL_offensiveReboundPercentage_advanced_3,ROLL_offensiveReboundPercentage_advanced_5,ROLL_offensiveReboundPercentage_advanced_10,ROLL_offensiveReboundPercentage_advanced_25,ROLL_offensiveReboundPercentage_advanced_50,ROLL_offensiveReboundPercentage_advanced_100,ROLL_offensiveReboundPercentage_advanced_200,ROLL_defensiveReboundPercentage_advanced_3,ROLL_defensiveReboundPercentage_advanced_5,ROLL_defensiveReboundPercentage_advanced_10,ROLL_defensiveReboundPercentage_advanced_25,ROLL_defensiveReboundPercentage_advanced_50,ROLL_defensiveReboundPercentage_advanced_100,ROLL_defensiveReboundPercentage_advanced_200,ROLL_reboundPercentage_advanced_3,ROLL_reboundPercentage_advanced_5,ROLL_reboundPercentage_advanced_10,ROLL_reboundPercentage_advanced_25,ROLL_reboundPercentage_advanced_50,ROLL_reboundPercentage_advanced_100,ROLL_reboundPercentage_advanced_200,ROLL_turnoverRatio_advanced_3,ROLL_turnoverRatio_advanced_5,ROLL_turnoverRatio_advanced_10,ROLL_turnoverRatio_advanced_25,ROLL_turnoverRatio_advanced_50,ROLL_turnoverRatio_advanced_100,ROLL_turnoverRatio_advanced_200,ROLL_effectiveFieldGoalPercentage_advanced_3,ROLL_effectiveFieldGoalPercentage_advanced_5,ROLL_effectiveFieldGoalPercentage_advanced_10,ROLL_effectiveFieldGoalPercentage_advanced_25,ROLL_effectiveFieldGoalPercentage_advanced_50,ROLL_effectiveFieldGoalPercentage_advanced_100,ROLL_effectiveFieldGoalPercentage_advanced_200,ROLL_trueShootingPercentage_advanced_3,ROLL_trueShootingPercentage_advanced_5,ROLL_trueShootingPercentage_advanced_10,ROLL_trueShootingPercentage_advanced_25,ROLL_trueShootingPercentage_advanced_50,ROLL_trueShootingPercentage_advanced_100,ROLL_trueShootingPercentage_advanced_200,ROLL_usagePercentage_advanced_3,ROLL_usagePercentage_advanced_5,ROLL_usagePercentage_advanced_10,ROLL_usagePercentage_advanced_25,ROLL_usagePercentage_advanced_50,ROLL_usagePercentage_advanced_100,ROLL_usagePercentage_advanced_200,ROLL_estimatedPace_advanced_3,ROLL_estimatedPace_advanced_5,ROLL_estimatedPace_advanced_10,ROLL_estimatedPace_advanced_25,ROLL_estimatedPace_advanced_50,ROLL_estimatedPace_advanced_100,ROLL_estimatedPace_advanced_200,ROLL_pace_advanced_3,ROLL_pace_advanced_5,ROLL_pace_advanced_10,ROLL_pace_advanced_25,ROLL_pace_advanced_50,ROLL_pace_advanced_100,ROLL_pace_advanced_200,ROLL_possessions_advanced_3,ROLL_possessions_advanced_5,ROLL_possessions_advanced_10,ROLL_possessions_advanced_25,ROLL_possessions_advanced_50,ROLL_possessions_advanced_100,ROLL_possessions_advanced_200,ROLL_PIE_advanced_3,ROLL_PIE_advanced_5,ROLL_PIE_advanced_10,ROLL_PIE_advanced_25,ROLL_PIE_advanced_50,ROLL_PIE_advanced_100,ROLL_PIE_advanced_200,ROLL_effectiveFieldGoalPercentage_fourfactors_3,ROLL_effectiveFieldGoalPercentage_fourfactors_5,ROLL_effectiveFieldGoalPercentage_fourfactors_10,ROLL_effectiveFieldGoalPercentage_fourfactors_25,ROLL_effectiveFieldGoalPercentage_fourfactors_50,ROLL_effectiveFieldGoalPercentage_fourfactors_100,ROLL_effectiveFieldGoalPercentage_fourfactors_200,ROLL_freeThrowAttemptRate_fourfactors_3,ROLL_freeThrowAttemptRate_fourfactors_5,ROLL_freeThrowAttemptRate_fourfactors_10,ROLL_freeThrowAttemptRate_fourfactors_25,ROLL_freeThrowAttemptRate_fourfactors_50,ROLL_freeThrowAttemptRate_fourfactors_100,ROLL_freeThrowAttemptRate_fourfactors_200,ROLL_teamTurnoverPercentage_fourfactors_3,ROLL_teamTurnoverPercentage_fourfactors_5,ROLL_teamTurnoverPercentage_fourfactors_10,ROLL_teamTurnoverPercentage_fourfactors_25,ROLL_teamTurnoverPercentage_fourfactors_50,ROLL_teamTurnoverPercentage_fourfactors_100,ROLL_teamTurnoverPercentage_fourfactors_200,ROLL_oppEffectiveFieldGoalPercentage_fourfactors_3,ROLL_oppEffectiveFieldGoalPercentage_fourfactors_5,ROLL_oppEffectiveFieldGoalPercentage_fourfactors_10,ROLL_oppEffectiveFieldGoalPercentage_fourfactors_25,ROLL_oppEffectiveFieldGoalPercentage_fourfactors_50,ROLL_oppEffectiveFieldGoalPercentage_fourfactors_100,ROLL_oppEffectiveFieldGoalPercentage_fourfactors_200,ROLL_oppFreeThrowAttemptRate_fourfactors_3,ROLL_oppFreeThrowAttemptRate_fourfactors_5,ROLL_oppFreeThrowAttemptRate_fourfactors_10,ROLL_oppFreeThrowAttemptRate_fourfactors_25,ROLL_oppFreeThrowAttemptRate_fourfactors_50,ROLL_oppFreeThrowAttemptRate_fourfactors_100,ROLL_oppFreeThrowAttemptRate_fourfactors_200,ROLL_oppTeamTurnoverPercentage_fourfactors_3,ROLL_oppTeamTurnoverPercentage_fourfactors_5,ROLL_oppTeamTurnoverPercentage_fourfactors_10,ROLL_oppTeamTurnoverPercentage_fourfactors_25,ROLL_oppTeamTurnoverPercentage_fourfactors_50,ROLL_oppTeamTurnoverPercentage_fourfactors_100,ROLL_oppTeamTurnoverPercentage_fourfactors_200,ROLL_oppOffensiveReboundPercentage_fourfactors_3,ROLL_oppOffensiveReboundPercentage_fourfactors_5,ROLL_oppOffensiveReboundPercentage_fourfactors_10,ROLL_oppOffensiveReboundPercentage_fourfactors_25,ROLL_oppOffensiveReboundPercentage_fourfactors_50,ROLL_oppOffensiveReboundPercentage_fourfactors_100,ROLL_oppOffensiveReboundPercentage_fourfactors_200,ROLL_foulsDrawn_misc_3,ROLL_foulsDrawn_misc_5,ROLL_foulsDrawn_misc_10,ROLL_foulsDrawn_misc_25,ROLL_foulsDrawn_misc_50,ROLL_foulsDrawn_misc_100,ROLL_foulsDrawn_misc_200,ROLL_percentageFieldGoalsAttempted2pt_scoring_3,ROLL_percentageFieldGoalsAttempted2pt_scoring_5,ROLL_percentageFieldGoalsAttempted2pt_scoring_10,ROLL_percentageFieldGoalsAttempted2pt_scoring_25,ROLL_percentageFieldGoalsAttempted2pt_scoring_50,ROLL_percentageFieldGoalsAttempted2pt_scoring_100,ROLL_percentageFieldGoalsAttempted2pt_scoring_200,ROLL_percentageFieldGoalsAttempted3pt_scoring_3,ROLL_percentageFieldGoalsAttempted3pt_scoring_5,ROLL_percentageFieldGoalsAttempted3pt_scoring_10,ROLL_percentageFieldGoalsAttempted3pt_scoring_25,ROLL_percentageFieldGoalsAttempted3pt_scoring_50,ROLL_percentageFieldGoalsAttempted3pt_scoring_100,ROLL_percentageFieldGoalsAttempted3pt_scoring_200,ROLL_percentagePoints2pt_scoring_3,ROLL_percentagePoints2pt_scoring_5,ROLL_percentagePoints2pt_scoring_10,ROLL_percentagePoints2pt_scoring_25,ROLL_percentagePoints2pt_scoring_50,ROLL_percentagePoints2pt_scoring_100,ROLL_percentagePoints2pt_scoring_200,ROLL_percentagePointsMidrange2pt_scoring_3,ROLL_percentagePointsMidrange2pt_scoring_5,ROLL_percentagePointsMidrange2pt_scoring_10,ROLL_percentagePointsMidrange2pt_scoring_25,ROLL_percentagePointsMidrange2pt_scoring_50,ROLL_percentagePointsMidrange2pt_scoring_100,ROLL_percentagePointsMidrange2pt_scoring_200,ROLL_percentagePoints3pt_scoring_3,ROLL_percentagePoints3pt_scoring_5,ROLL_percentagePoints3pt_scoring_10,ROLL_percentagePoints3pt_scoring_25,ROLL_percentagePoints3pt_scoring_50,ROLL_percentagePoints3pt_scoring_100,ROLL_percentagePoints3pt_scoring_200,ROLL_percentagePointsFastBreak_scoring_3,ROLL_percentagePointsFastBreak_scoring_5,ROLL_percentagePointsFastBreak_scoring_10,ROLL_percentagePointsFastBreak_scoring_25,ROLL_percentagePointsFastBreak_scoring_50,ROLL_percentagePointsFastBreak_scoring_100,ROLL_percentagePointsFastBreak_scoring_200,ROLL_percentagePointsFreeThrow_scoring_3,ROLL_percentagePointsFreeThrow_scoring_5,ROLL_percentagePointsFreeThrow_scoring_10,ROLL_percentagePointsFreeThrow_scoring_25,ROLL_percentagePointsFreeThrow_scoring_50,ROLL_percentagePointsFreeThrow_scoring_100,ROLL_percentagePointsFreeThrow_scoring_200,ROLL_percentagePointsOffTurnovers_scoring_3,ROLL_percentagePointsOffTurnovers_scoring_5,ROLL_percentagePointsOffTurnovers_scoring_10,ROLL_percentagePointsOffTurnovers_scoring_25,ROLL_percentagePointsOffTurnovers_scoring_50,ROLL_percentagePointsOffTurnovers_scoring_100,ROLL_percentagePointsOffTurnovers_scoring_200,ROLL_percentagePointsPaint_scoring_3,ROLL_percentagePointsPaint_scoring_5,ROLL_percentagePointsPaint_scoring_10,ROLL_percentagePointsPaint_scoring_25,ROLL_percentagePointsPaint_scoring_50,ROLL_percentagePointsPaint_scoring_100,ROLL_percentagePointsPaint_scoring_200,ROLL_percentageAssisted2pt_scoring_3,ROLL_percentageAssisted2pt_scoring_5,ROLL_percentageAssisted2pt_scoring_10,ROLL_percentageAssisted2pt_scoring_25,ROLL_percentageAssisted2pt_scoring_50,ROLL_percentageAssisted2pt_scoring_100,ROLL_percentageAssisted2pt_scoring_200,ROLL_percentageUnassisted2pt_scoring_3,ROLL_percentageUnassisted2pt_scoring_5,ROLL_percentageUnassisted2pt_scoring_10,ROLL_percentageUnassisted2pt_scoring_25,ROLL_percentageUnassisted2pt_scoring_50,ROLL_percentageUnassisted2pt_scoring_100,ROLL_percentageUnassisted2pt_scoring_200,ROLL_percentageAssisted3pt_scoring_3,ROLL_percentageAssisted3pt_scoring_5,ROLL_percentageAssisted3pt_scoring_10,ROLL_percentageAssisted3pt_scoring_25,ROLL_percentageAssisted3pt_scoring_50,ROLL_percentageAssisted3pt_scoring_100,ROLL_percentageAssisted3pt_scoring_200,ROLL_percentageUnassisted3pt_scoring_3,ROLL_percentageUnassisted3pt_scoring_5,ROLL_percentageUnassisted3pt_scoring_10,ROLL_percentageUnassisted3pt_scoring_25,ROLL_percentageUnassisted3pt_scoring_50,ROLL_percentageUnassisted3pt_scoring_100,ROLL_percentageUnassisted3pt_scoring_200,ROLL_percentageAssistedFGM_scoring_3,ROLL_percentageAssistedFGM_scoring_5,ROLL_percentageAssistedFGM_scoring_10,ROLL_percentageAssistedFGM_scoring_25,ROLL_percentageAssistedFGM_scoring_50,ROLL_percentageAssistedFGM_scoring_100,ROLL_percentageAssistedFGM_scoring_200,ROLL_percentageUnassistedFGM_scoring_3,ROLL_percentageUnassistedFGM_scoring_5,ROLL_percentageUnassistedFGM_scoring_10,ROLL_percentageUnassistedFGM_scoring_25,ROLL_percentageUnassistedFGM_scoring_50,ROLL_percentageUnassistedFGM_scoring_100,ROLL_percentageUnassistedFGM_scoring_200,ROLL_threePointersPercentage_traditional_3,ROLL_threePointersPercentage_traditional_5,ROLL_threePointersPercentage_traditional_10,ROLL_threePointersPercentage_traditional_25,ROLL_threePointersPercentage_traditional_50,ROLL_threePointersPercentage_traditional_100,ROLL_threePointersPercentage_traditional_200,ROLL_freeThrowsPercentage_traditional_3,ROLL_freeThrowsPercentage_traditional_5,ROLL_freeThrowsPercentage_traditional_10,ROLL_freeThrowsPercentage_traditional_25,ROLL_freeThrowsPercentage_traditional_50,ROLL_freeThrowsPercentage_traditional_100,ROLL_freeThrowsPercentage_traditional_200,ROLL_percentageFieldGoalsMade_usage_3,ROLL_percentageFieldGoalsMade_usage_5,ROLL_percentageFieldGoalsMade_usage_10,ROLL_percentageFieldGoalsMade_usage_25,ROLL_percentageFieldGoalsMade_usage_50,ROLL_percentageFieldGoalsMade_usage_100,ROLL_percentageFieldGoalsMade_usage_200,ROLL_percentageFieldGoalsAttempted_usage_3,ROLL_percentageFieldGoalsAttempted_usage_5,ROLL_percentageFieldGoalsAttempted_usage_10,ROLL_percentageFieldGoalsAttempted_usage_25,ROLL_percentageFieldGoalsAttempted_usage_50,ROLL_percentageFieldGoalsAttempted_usage_100,ROLL_percentageFieldGoalsAttempted_usage_200,ROLL_percentageThreePointersMade_usage_3,ROLL_percentageThreePointersMade_usage_5,ROLL_percentageThreePointersMade_usage_10,ROLL_percentageThreePointersMade_usage_25,ROLL_percentageThreePointersMade_usage_50,ROLL_percentageThreePointersMade_usage_100,ROLL_percentageThreePointersMade_usage_200,ROLL_percentageThreePointersAttempted_usage_3,ROLL_percentageThreePointersAttempted_usage_5,ROLL_percentageThreePointersAttempted_usage_10,ROLL_percentageThreePointersAttempted_usage_25,ROLL_percentageThreePointersAttempted_usage_50,ROLL_percentageThreePointersAttempted_usage_100,ROLL_percentageThreePointersAttempted_usage_200,ROLL_percentageFreeThrowsMade_usage_3,ROLL_percentageFreeThrowsMade_usage_5,ROLL_percentageFreeThrowsMade_usage_10,ROLL_percentageFreeThrowsMade_usage_25,ROLL_percentageFreeThrowsMade_usage_50,ROLL_percentageFreeThrowsMade_usage_100,ROLL_percentageFreeThrowsMade_usage_200,ROLL_percentageFreeThrowsAttempted_usage_3,ROLL_percentageFreeThrowsAttempted_usage_5,ROLL_percentageFreeThrowsAttempted_usage_10,ROLL_percentageFreeThrowsAttempted_usage_25,ROLL_percentageFreeThrowsAttempted_usage_50,ROLL_percentageFreeThrowsAttempted_usage_100,ROLL_percentageFreeThrowsAttempted_usage_200,ROLL_percentageReboundsOffensive_usage_3,ROLL_percentageReboundsOffensive_usage_5,ROLL_percentageReboundsOffensive_usage_10,ROLL_percentageReboundsOffensive_usage_25,ROLL_percentageReboundsOffensive_usage_50,ROLL_percentageReboundsOffensive_usage_100,ROLL_percentageReboundsOffensive_usage_200,ROLL_percentageReboundsDefensive_usage_3,ROLL_percentageReboundsDefensive_usage_5,ROLL_percentageReboundsDefensive_usage_10,ROLL_percentageReboundsDefensive_usage_25,ROLL_percentageReboundsDefensive_usage_50,ROLL_percentageReboundsDefensive_usage_100,ROLL_percentageReboundsDefensive_usage_200,ROLL_percentageReboundsTotal_usage_3,ROLL_percentageReboundsTotal_usage_5,ROLL_percentageReboundsTotal_usage_10,ROLL_percentageReboundsTotal_usage_25,ROLL_percentageReboundsTotal_usage_50,ROLL_percentageReboundsTotal_usage_100,ROLL_percentageReboundsTotal_usage_200,ROLL_percentageAssists_usage_3,ROLL_percentageAssists_usage_5,ROLL_percentageAssists_usage_10,ROLL_percentageAssists_usage_25,ROLL_percentageAssists_usage_50,ROLL_percentageAssists_usage_100,ROLL_percentageAssists_usage_200,ROLL_percentageTurnovers_usage_3,ROLL_percentageTurnovers_usage_5,ROLL_percentageTurnovers_usage_10,ROLL_percentageTurnovers_usage_25,ROLL_percentageTurnovers_usage_50,ROLL_percentageTurnovers_usage_100,ROLL_percentageTurnovers_usage_200,ROLL_percentageSteals_usage_3,ROLL_percentageSteals_usage_5,ROLL_percentageSteals_usage_10,ROLL_percentageSteals_usage_25,ROLL_percentageSteals_usage_50,ROLL_percentageSteals_usage_100,ROLL_percentageSteals_usage_200,ROLL_percentageBlocks_usage_3,ROLL_percentageBlocks_usage_5,ROLL_percentageBlocks_usage_10,ROLL_percentageBlocks_usage_25,ROLL_percentageBlocks_usage_50,ROLL_percentageBlocks_usage_100,ROLL_percentageBlocks_usage_200,ROLL_percentageBlocksAllowed_usage_3,ROLL_percentageBlocksAllowed_usage_5,ROLL_percentageBlocksAllowed_usage_10,ROLL_percentageBlocksAllowed_usage_25,ROLL_percentageBlocksAllowed_usage_50,ROLL_percentageBlocksAllowed_usage_100,ROLL_percentageBlocksAllowed_usage_200,ROLL_percentagePersonalFouls_usage_3,ROLL_percentagePersonalFouls_usage_5,ROLL_percentagePersonalFouls_usage_10

End time: 2025-06-06 20:58:38.933644
Duration: 0:03:46.653763