# Nettoyage & enrichissement des boxscores (minutes, DNP, totaux, ratios)

In [1]:
import pandas as pd
import numpy as np
import os
from datetime import datetime
from nba_api.stats.static import players

from src.config import *
from src.utils import *
from src.feature_builder import *
from src.feature_aggregation import *

#display full columns
pd.set_option('display.max_column', None)
# pd.set_option('display.max_rows', None)
# pd.set_option('display.max_seq_items', None)
# pd.set_option('display.max_colwidth', 500)
# pd.set_option('expand_frame_repr', True)

In [2]:
#store start time of notebook
start_time = datetime.now()
print("Start time: ", start_time)

Start time:  2025-11-01 14:09:27.803456

# 🔁 Chargement des fichiers

In [3]:
boxscores_file = get_latest_file(DATA_LAST_BOXSCORES_BATCHES_MERGED_DIR)
games_file = get_latest_file(DATA_LAST_GAMES_MERGED_DIR)
df_boxscores = pd.read_csv(boxscores_file, dtype={'gameId': str})
df_games = pd.read_csv(games_file, dtype={'GAME_ID': str, 'TEAM_ID': str})

In [4]:
games_file

'data/raw_last/games_merged/games_merged_all_seasons_2025-11-01_03-03-49.csv'

In [5]:
df_boxscores

,gameId,teamId,teamCity,teamName,teamTricode,teamSlug,personId,firstName,familyName,nameI,playerSlug,position,comment,jerseyNum,minutes,offensiveRating_advanced,defensiveRating_advanced,estimatedNetRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,oppPointsOffTurnovers_misc,oppPointsSecondChance_misc,oppPointsFastBreak_misc,oppPointsPaint_misc,blocksAgainst_misc,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,threePointersPercentage_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,freeThrowsPercentage_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,points_traditional,plusMinusPoints_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage
0,0020000279,1610612741,Chicago,Bulls,CHI,bulls,1897,Metta,World Peace,M. World Peace,metta-world-peace,F,NaN,NaN,29:20,83.3,112.3,-28.9,-28.9,0.077,1.00,6.7,0.038,0.031,0.034,6.7,0.583,0.582,0.203,95.73,95.73,60.0,0.156,0.467,0.267,0.249,0.475,0.186,0.100,0.370,2,2,4,10,17,14,13,36,2,0,0.917,0.083,0.933,0.267,0.000,0.267,0.067,0.133,0.667,0.429,0.571,0.0,0.0,0.429,0.571,7,12,0,1,0.000,1,2,0.50,1,1,2,1,3,2,1,2,15,-14.0,0.350,0.267,0.00,0.200,0.125,0.167,0.125,0.059,0.080,0.125,0.071,0.75,0.667,0.400,0.143,0.000,0.300
1,0020000279,1610612741,Chicago,Bulls,CHI,bulls,2033,Marcus,Fizer,M. Fizer,marcus-fizer,F,NaN,NaN,37:09,90.3,101.4,-11.1,-11.1,0.087,0.50,11.8,0.111,0.128,0.120,23.5,0.300,0.368,0.181,92.38,92.38,72.0,0.043,0.475,0.217,0.223,0.477,0.297,0.156,0.361,2,4,2,6,19,14,10,42,3,0,1.000,0.000,0.750,0.000,0.000,0.250,0.250,0.250,0.750,0.333,0.667,0.0,0.0,0.333,0.667,3,10,0,0,0.000,2,2,1.00,4,5,9,2,0,0,4,2,8,-7.0,0.115,0.167,0.00,0.000,0.250,0.154,0.400,0.217,0.273,0.167,0.250,0.00,0.000,0.600,0.095,0.000,0.123
2,0020000279,1610612741,Chicago,Bulls,CHI,bulls,1434,Dragan,Tarlac,D. Tarlac,dragan-tarlac,C,NaN,NaN,22:49,85.1,122.4,-37.3,-37.3,0.000,0.00,0.0,0.150,0.154,0.152,75.0,1.000,1.064,0.151,100.98,100.98,47.0,-0.007,0.486,0.286,0.259,0.500,0.260,0.095,0.364,0,4,0,2,16,10,19,34,0,0,1.000,0.000,0.500,0.000,0.000,0.000,0.500,0.000,0.500,0.000,1.000,0.0,0.0,0.000,1.000,1,1,0,0,0.000,2,2,1.00,3,4,7,0,1,0,6,5,4,-20.0,0.063,0.029,0.00,0.000,0.333,0.200,0.600,0.286,0.368,0.000,0.500,0.25,0.000,0.000,0.357,0.000,0.100
3,0020000279,1610612741,Chicago,Bulls,CHI,bulls,2064,Khalid,El-Amin,K. El-Amin,khalid-el-amin,G,NaN,NaN,27:47,100.0,107.1,-7.1,-7.1,0.286,4.00,21.1,0.042,0.107,0.077,5.3,0.643,0.643,0.242,95.88,95.88,55.0,0.188,0.545,0.250,0.237,0.538,0.154,0.144,0.348,2,0,6,6,14,10,8,40,0,0,0.786,0.214,0.667,0.333,0.333,0.333,0.000,0.111,0.333,0.167,0.833,1.0,0.0,0.375,0.625,8,14,2,3,0.667,0,0,0.00,1,3,4,4,0,1,1,2,18,-5.0,0.364,0.318,0.50,0.375,0.000,0.000,0.143,0.200,0.182,0.444,0.077,0.00,0.167,0.000,0.200,0.000,0.327
4,0020000279,1610612741,Chicago,Bulls,CHI,bulls,1500,Ron,Mercer,R. Mercer,ron-mercer,G,NaN,NaN,41:20,86.4,113.6,-27.2,-27.2,0.045,0.33,4.2,0.000,0.095,0.050,12.5,0.361,0.405,0.250,94.06,94.06,81.0,0.037,0.469,0.200,0.238,0.500,0.256,0.142,0.378,0,0,2,4,21,18,21,54,1,0,0.889,0.111,0.625,0.375,0.188,0.125,0.188,0.000,0.250,0.600,0.400,1.0,0.0,0.667,0.333,6,18,1,2,0.500,3,4,0.75,0,4,4,1,0,1,3,1,16,-22.0,0.214,0.277,0.20,0.200,0.333,0.308,0.000,0.174,0.121,0.071,0.158,0.00,0.167,0.143,0.043,0.000,0.229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
754141,0022500092,1610612761,Toronto,Raptors,TOR,raptors,1642347,Jamal,Shead,J. Shead,jamal-shead,NaN,NaN,NaN,11:30,92.6,108.0,-15.4,-15.4,0.500,0.00,36.4,0.000,0.000,0.000,0.0,0.167,0.291,0.212,108.52,108.52,27.0,0.099,0.396,0.292,0.185,0.605,0.421,0.245,0.400,0,0,0,2,3,7,6,14,2,1,0.667,0.333,0.500,0.000,0.000,0.000,0.500,0.000,0.500,0.000,1.000,0.0,0.0,0.000,1.000,1,6,0,2,0.000,2,2,1.00,0,0,0,4,1,0,0,0,4,-2.0,0.111,0.250,0.00,0.286,0.333,0.286,0.000,0.000,0.000,0.800,0.000,0.25,0.000,1.000,0.000,0.167,0.160
754142,0022500092,1610612761,Toronto,Raptors,TOR,raptors,1642367,Jonathan,Mogbo,J. Mogbo,jonathan-mogbo,NaN,NaN,NaN,3:58,80.0,88.9,-8.9,-8.9,0.000,0.00,0.0,0.200,0.250,0.222,100.0,0.000,0.000,0.083,114.96,114.96,10.0,0.071,0.286,0.571,0.228,0.571,0.000,0.444,0.500,0,0,0,0,0,3,0,2,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0,0,0,0,0.000,0,0,0.00,1,1,2,0,0,1,1,0,0,0.0,0.000,0.000,0.00,0.000,0.000,0.000,0.500,0.500,0.500,0.000,0.500,0.00,0.500,0.000,0.000,0.000,0.000
754143,0022500092,1610612761,Toronto,Raptors,TOR,raptors,1642419,Jamison,Battle,J. Battle,jamison-battle,NaN,NaN,NaN,10:33,152.2,109.1,43.1,43.1,0.000,0.00,0.0,0.000,0.133,0.087,25.0,1.500,1.500,0.160,102.37,102.37,23.0,0.182,0.800,0.350,0.120,0.479,0.083,0.131,0.385,0,0,3,0,6,7,0,12,0,0,0.000,1.000,0.000,0.000,1.000,0.333,0.000,0.000,0.000,0.000,0.000,1.0,0.0,1.000,0.000,3,3,3,3,1.000,0,0,0.00,0,2,2,0,1,0,1,1,9,11.0,0.214,0.150,0.75,0.500,0.000,0.000,0.000,0.250,0.222,0.000,0.333,0.50,0.000,0.000,0.333,0.000,0.257
754144,0022500092,1610612761,Toronto,Raptors,TOR,raptors,202066,Garrett,Temple,G. Temple,garrett-temple,NaN,DNP - Coach's Decision,NaN,NaN,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.00,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0,0,0,0,0,0,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0,0,0,0,0.000,0,0,0.00,0,0,0,0,0,0,0,0,0,0.0,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000
754145,0022500092,1610612761,Toronto,Raptors,TOR,raptors,1642266,Ja'Kobe,Walter,J. Walter,jakobe-walter,NaN,DNP - Coach's Decision,NaN,NaN,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.00,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0,0,0,0,0,0,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0,0,0,0,0.000,0,0,0.00,0,0,0,0,0,0,0,0,0,0.0,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000

In [6]:
df_games

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS,SEASON
0,22010,1610612738.0,BOS,Boston Celtics,0021000001,2010-10-26,BOS vs. MIA,W,239,88,32,69,0.464,8,16,0.500,16,25,0.640,8,34,42,25,6,4,18,19,8.0,2010-11
1,22010,1610612756.0,PHX,Phoenix Suns,0021000002,2010-10-26,PHX @ POR,L,239,92,36,74,0.486,9,19,0.474,11,16,0.688,7,23,30,15,3,4,19,19,-14.0,2010-11
2,22010,1610612745.0,HOU,Houston Rockets,0021000003,2010-10-26,HOU @ LAL,L,240,110,38,91,0.418,8,20,0.400,26,28,0.929,16,37,53,25,6,7,20,25,-2.0,2010-11
3,22010,1610612757.0,POR,Portland Trail Blazers,0021000002,2010-10-26,POR vs. PHX,W,240,106,43,93,0.462,10,20,0.500,10,15,0.667,18,30,48,31,11,2,12,22,14.0,2010-11
4,22010,1610612748.0,MIA,Miami Heat,0021000001,2010-10-26,MIA @ BOS,L,242,80,27,74,0.365,8,20,0.400,18,25,0.720,11,28,39,15,10,6,17,21,-8.0,2010-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66921,22025,1610612737.0,ATL,Atlanta Hawks,0022500020,2025-10-31,ATL @ IND,W,239,128,51,94,0.543,10,30,0.333,16,20,0.800,12,43,55,30,10,5,10,23,20.0,2025-26
66922,22025,1610612763.0,MEM,Memphis Grizzlies,0022500024,2025-10-31,MEM vs. LAL,NaN,0,8,3,3,1.000,1,1,1.000,1,2,0.500,0,2,2,3,1,0,1,0,4.0,2025-26
66923,22025,1610612747.0,LAL,Los Angeles Lakers,0022500024,2025-10-31,LAL @ MEM,NaN,0,4,2,4,0.500,0,2,0.000,0,0,NaN,0,0,0,1,1,0,2,2,-4.0,2025-26
66924,22025,1610612739.0,CLE,Cleveland Cavaliers,0022500022,2025-10-31,CLE vs. TOR,NaN,241,93,33,80,0.413,13,42,0.310,14,22,0.636,12,25,37,22,9,10,12,14,-6.4,2025-26
66925,22025,1610612761.0,TOR,Toronto Raptors,0022500022,2025-10-31,TOR @ CLE,NaN,240,98,35,75,0.467,11,28,0.393,17,22,0.773,10,35,45,24,8,3,15,17,10.6,2025-26

# 🧼 Nettoyage des minutes jouées

In [7]:
def convert_minutes(val):
    if pd.isna(val) or val in ['DNP', '']:
        return 0.0
    try:
        parts = str(val).split(':')
        return int(parts[0]) + int(parts[1]) / 60 if len(parts) == 2 else float(val)
    except:
        return 0.0

df_boxscores['MINUTES_PLAYED'] = df_boxscores['minutes'].apply(convert_minutes)

# Rename gameId and teamId in boxscores

In [8]:
rename_columns = {
    'gameId': 'GAME_ID',
    'teamId': 'TEAM_ID',
}

df_boxscores.rename(columns=rename_columns, inplace=True)

In [9]:
# Normaliser GAME_ID et TEAM_ID pour garantir des jointures cohérentes
for df in (df_games, df_boxscores):
    for col in ['GAME_ID', 'TEAM_ID']:
        df[col] = pd.to_numeric(df[col], errors='coerce').astype('Int64')
        df[col] = df[col].astype(str).replace('<NA>', None)

In [10]:
print(df_games.dtypes)

SEASON_ID              int64
TEAM_ID               object
TEAM_ABBREVIATION     object
TEAM_NAME             object
GAME_ID               object
GAME_DATE             object
MATCHUP               object
WL                    object
MIN                    int64
PTS                    int64
FGM                    int64
FGA                    int64
FG_PCT               float64
FG3M                   int64
FG3A                   int64
FG3_PCT              float64
FTM                    int64
FTA                    int64
FT_PCT               float64
OREB                   int64
DREB                   int64
REB                    int64
AST                    int64
STL                    int64
BLK                    int64
TOV                    int64
PF                     int64
PLUS_MINUS           float64
SEASON                object
dtype: object

In [11]:
print(df_boxscores.dtypes)

GAME_ID                                object
TEAM_ID                                object
teamCity                               object
teamName                               object
teamTricode                            object
                                       ...
percentageBlocksAllowed_usage         float64
percentagePersonalFouls_usage         float64
percentagePersonalFoulsDrawn_usage    float64
percentagePoints_usage                float64
MINUTES_PLAYED                        float64
Length: 101, dtype: object

# Merge GAME_DATE dans les boxscores et remove les duplicates créés

In [12]:
df_games['GAME_DATE'] = pd.to_datetime(df_games['GAME_DATE'])
df_boxscores = df_boxscores.merge(
    df_games[['GAME_ID', 'TEAM_ID', 'GAME_DATE']],
    on=['GAME_ID', 'TEAM_ID'],
    how='left'
)

df_boxscores = df_boxscores.drop_duplicates(subset=['GAME_ID', 'TEAM_ID', 'playerSlug'])

In [13]:
# display nat GAME_DATE in df_boxscores
# check for NaT values in GAME_DATE
nat_dates = df_boxscores[df_boxscores['GAME_DATE'].isna()]
nat_dates

Empty DataFrame
Columns: [GAME_ID, TEAM_ID, teamCity, teamName, teamTricode, teamSlug, personId, firstName, familyName, nameI, playerSlug, position, comment, jerseyNum, minutes, offensiveRating_advanced, defensiveRating_advanced, estimatedNetRating_advanced, netRating_advanced, assistPercentage_advanced, assistToTurnover_advanced, assistRatio_advanced, offensiveReboundPercentage_advanced, defensiveReboundPercentage_advanced, reboundPercentage_advanced, turnoverRatio_advanced, effectiveFieldGoalPercentage_advanced, trueShootingPercentage_advanced, usagePercentage_advanced, estimatedPace_advanced, pace_advanced, possessions_advanced, PIE_advanced, effectiveFieldGoalPercentage_fourfactors, freeThrowAttemptRate_fourfactors, teamTurnoverPercentage_fourfactors, oppEffectiveFieldGoalPercentage_fourfactors, oppFreeThrowAttemptRate_fourfactors, oppTeamTurnoverPercentage_fourfactors, oppOffensiveReboundPercentage_fourfactors, pointsOffTurnovers_misc, pointsSecondChance_misc, pointsFastBreak_misc, pointsPaint_misc, oppPointsOffTurnovers_misc, oppPointsSecondChance_misc, oppPointsFastBreak_misc, oppPointsPaint_misc, blocksAgainst_misc, foulsDrawn_misc, percentageFieldGoalsAttempted2pt_scoring, percentageFieldGoalsAttempted3pt_scoring, percentagePoints2pt_scoring, percentagePointsMidrange2pt_scoring, percentagePoints3pt_scoring, percentagePointsFastBreak_scoring, percentagePointsFreeThrow_scoring, percentagePointsOffTurnovers_scoring, percentagePointsPaint_scoring, percentageAssisted2pt_scoring, percentageUnassisted2pt_scoring, percentageAssisted3pt_scoring, percentageUnassisted3pt_scoring, percentageAssistedFGM_scoring, percentageUnassistedFGM_scoring, fieldGoalsMade_traditional, fieldGoalsAttempted_traditional, threePointersMade_traditional, threePointersAttempted_traditional, threePointersPercentage_traditional, freeThrowsMade_traditional, freeThrowsAttempted_traditional, freeThrowsPercentage_traditional, reboundsOffensive_traditional, reboundsDefensive_traditional, reboundsTotal_traditional, assists_traditional, steals_traditional, blocks_traditional, turnovers_traditional, foulsPersonal_traditional, points_traditional, plusMinusPoints_traditional, percentageFieldGoalsMade_usage, percentageFieldGoalsAttempted_usage, percentageThreePointersMade_usage, percentageThreePointersAttempted_usage, percentageFreeThrowsMade_usage, percentageFreeThrowsAttempted_usage, percentageReboundsOffensive_usage, percentageReboundsDefensive_usage, percentageReboundsTotal_usage, percentageAssists_usage, percentageTurnovers_usage, percentageSteals_usage, percentageBlocks_usage, percentageBlocksAllowed_usage, percentagePersonalFouls_usage, percentagePersonalFoulsDrawn_usage, percentagePoints_usage, ...]
Index: []

In [14]:
missing = df_boxscores[df_boxscores['GAME_DATE'].isna()][['GAME_ID', 'TEAM_ID']].drop_duplicates()

print(f"Exemples de lignes avec GAME_DATE NaT:")
print(missing.head(10))

# On regarde s’ils existent dans df_games
merged_check = missing.merge(df_games[['GAME_ID', 'TEAM_ID']], on=['GAME_ID', 'TEAM_ID'], how='left', indicator=True)
print(merged_check['_merge'].value_counts())

Exemples de lignes avec GAME_DATE NaT:
Empty DataFrame
Columns: [GAME_ID, TEAM_ID]
Index: []
_merge
left_only     0
right_only    0
both          0
Name: count, dtype: int64

In [15]:
print("Exemples d’ID manquants dans df_games")
print(missing[~missing.set_index(['GAME_ID', 'TEAM_ID']).index.isin(df_games.set_index(['GAME_ID', 'TEAM_ID']).index)])

Exemples d’ID manquants dans df_games
Empty DataFrame
Columns: [GAME_ID, TEAM_ID]
Index: []

# 🔄 Cast dynamique des colonnes numériques

In [16]:
numeric_cols = df_boxscores.select_dtypes(include=[np.number]).columns.tolist()
for col in numeric_cols:
    df_boxscores[col] = pd.to_numeric(df_boxscores[col], errors='coerce').fillna(0)

In [17]:
df_boxscores

,GAME_ID,TEAM_ID,teamCity,teamName,teamTricode,teamSlug,personId,firstName,familyName,nameI,playerSlug,position,comment,jerseyNum,minutes,offensiveRating_advanced,defensiveRating_advanced,estimatedNetRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,oppPointsOffTurnovers_misc,oppPointsSecondChance_misc,oppPointsFastBreak_misc,oppPointsPaint_misc,blocksAgainst_misc,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,threePointersPercentage_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,freeThrowsPercentage_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,points_traditional,plusMinusPoints_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage,MINUTES_PLAYED,GAME_DATE
0,20000279,1610612741,Chicago,Bulls,CHI,bulls,1897,Metta,World Peace,M. World Peace,metta-world-peace,F,NaN,0.0,29:20,83.3,112.3,-28.9,-28.9,0.077,1.00,6.7,0.038,0.031,0.034,6.7,0.583,0.582,0.203,95.73,95.73,60.0,0.156,0.467,0.267,0.249,0.475,0.186,0.100,0.370,2,2,4,10,17,14,13,36,2,0,0.917,0.083,0.933,0.267,0.000,0.267,0.067,0.133,0.667,0.429,0.571,0.0,0.0,0.429,0.571,7,12,0,1,0.000,1,2,0.50,1,1,2,1,3,2,1,2,15,-14.0,0.350,0.267,0.00,0.200,0.125,0.167,0.125,0.059,0.080,0.125,0.071,0.75,0.667,0.400,0.143,0.000,0.300,29.333333,2000-12-08
1,20000279,1610612741,Chicago,Bulls,CHI,bulls,2033,Marcus,Fizer,M. Fizer,marcus-fizer,F,NaN,0.0,37:09,90.3,101.4,-11.1,-11.1,0.087,0.50,11.8,0.111,0.128,0.120,23.5,0.300,0.368,0.181,92.38,92.38,72.0,0.043,0.475,0.217,0.223,0.477,0.297,0.156,0.361,2,4,2,6,19,14,10,42,3,0,1.000,0.000,0.750,0.000,0.000,0.250,0.250,0.250,0.750,0.333,0.667,0.0,0.0,0.333,0.667,3,10,0,0,0.000,2,2,1.00,4,5,9,2,0,0,4,2,8,-7.0,0.115,0.167,0.00,0.000,0.250,0.154,0.400,0.217,0.273,0.167,0.250,0.00,0.000,0.600,0.095,0.000,0.123,37.150000,2000-12-08
2,20000279,1610612741,Chicago,Bulls,CHI,bulls,1434,Dragan,Tarlac,D. Tarlac,dragan-tarlac,C,NaN,0.0,22:49,85.1,122.4,-37.3,-37.3,0.000,0.00,0.0,0.150,0.154,0.152,75.0,1.000,1.064,0.151,100.98,100.98,47.0,-0.007,0.486,0.286,0.259,0.500,0.260,0.095,0.364,0,4,0,2,16,10,19,34,0,0,1.000,0.000,0.500,0.000,0.000,0.000,0.500,0.000,0.500,0.000,1.000,0.0,0.0,0.000,1.000,1,1,0,0,0.000,2,2,1.00,3,4,7,0,1,0,6,5,4,-20.0,0.063,0.029,0.00,0.000,0.333,0.200,0.600,0.286,0.368,0.000,0.500,0.25,0.000,0.000,0.357,0.000,0.100,22.816667,2000-12-08
3,20000279,1610612741,Chicago,Bulls,CHI,bulls,2064,Khalid,El-Amin,K. El-Amin,khalid-el-amin,G,NaN,0.0,27:47,100.0,107.1,-7.1,-7.1,0.286,4.00,21.1,0.042,0.107,0.077,5.3,0.643,0.643,0.242,95.88,95.88,55.0,0.188,0.545,0.250,0.237,0.538,0.154,0.144,0.348,2,0,6,6,14,10,8,40,0,0,0.786,0.214,0.667,0.333,0.333,0.333,0.000,0.111,0.333,0.167,0.833,1.0,0.0,0.375,0.625,8,14,2,3,0.667,0,0,0.00,1,3,4,4,0,1,1,2,18,-5.0,0.364,0.318,0.50,0.375,0.000,0.000,0.143,0.200,0.182,0.444,0.077,0.00,0.167,0.000,0.200,0.000,0.327,27.783333,2000-12-08
4,20000279,1610612741,Chicago,Bulls,CHI,bulls,1500,Ron,Mercer,R. Mercer,ron-mercer,G,NaN,0.0,41:20,86.4,113.6,-27.2,-27.2,0.045,0.33,4.2,0.000,0.095,0.050,12.5,0.361,0.405,0.250,94.06,94.06,81.0,0.037,0.469,0.200,0.238,0.500,0.256,0.142,0.378,0,0,2,4,21,18,21,54,1,0,0.889,0.111,0.625,0.375,0.188,0.125,0.188,0.000,0.250,0.600,0.400,1.0,0.0,0.667,0.333,6,18,1,2,0.500,3,4,0.75,0,4,4,1,0,1,3,1,16,-22.0,0.214,0.277,0.20,0.200,0.333,0.308,0.000,0.174,0.121,0.071,0.158,0.00,0.167,0.143,0.043,0.000,0.229,41.333333,2000-12-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
784245,22500092,1610612761,Toronto,Raptors,TOR,raptors,1642347,Jamal,Shead,J. Shead,jamal-shead,NaN,NaN,0.0,11:30,92.6,108.0,-15.4,-15.4,0.500,0.00,36.4,0.000,0.000,0.000,0.0,0.167,0.291,0.212,108.52,108.52,27.0,0.099,0.396,0.292,0.185,0.605,0.421,0.245,0.400,0,0,0,2,3,7,6,14,2,1,0.667,0.333,0.500,0.000,0.000,0.000,0.500,0.000,0.500,0.000,1.000,0.0,0.0,0.000,1.000,1,6,0,2,0.000,2,2,1.00,0,0,0,4,1,0,0,0,4,-2.0,0.111,0.250,0.00,0.286,0.333,0.286,0.000,0.000,0.000,0.800,0.000,0.25,0.000,1.000,0.000,0.167,0.160,11.500000,2025-10-24
784246,22500092,1610612761,Toronto,Raptors,TOR,raptors,1642367,Jonathan,Mogbo,J. Mogbo,jonathan-mogbo,NaN,NaN,0.0,3:58,80.0,88.9,-8.9,-8.9,0.000,0.00,0.0,0.200,0.250,0.222,100.0,0.000,0.000,0.083,114.96,114.96,10.0,0.071,0.286,0.571,0.228,0.571,0.000,0.444,0.500,0,0,0,0,0,3,0,2,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0,0,0,0,0.000,0,0,0.00,1,1,2,0,0,1,1,0,0,0.0,0.000,0.000,0.00,0.000,0.000,0.000,0.500,0.500,0.500,0.000,0.500,0.00,0.500,0.000,0.000,0.000,0.000,3.966667,2025-10-24
784247,22500092,1610612761,Toronto,Raptors,TOR,raptors,1642419,Jamison,Battle,J. Battle,jamison-battle,NaN,NaN,0.0,10:33,152.2,109.1,43.1,43.1,0.000,0.00,0.0,0.000,0.133,0.087,25.0,1.500,1.500,0.160,102.37,102.37,23.0,0.182,0.800,0.350,0.120,0.479,0.083,0.131,0.385,0,0,3,0,6,7,0,12,0,0,0.000,1.000,0.000,0.000,1.000,0.333,0.000,0.000,0.000,0.000,0.000,1.0,0.0,1.000,0.000,3,3,3,3,1.000,0,0,0.00,0,2,2,0,1,0,1,1,9,11.0,0.214,0.150,0.75,0.500,0.000,0.000,0.000,0.250,0.222,0.000,0.333,0.50,0.000,0.000,0.333,0.000,0.257,10.550000,2025-10-24
784248,22500092,1610612761,Toronto,Raptors,TOR,raptors,202066,Garrett,Temple,G. Temple,garrett-temple,NaN,DNP - Coach's Decision,0.0,NaN,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.00,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0,0,0,0,0,0,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0,0,0,0,0.000,0,0,0.00,0,0,0,0,0,0,0,0,0,0.0,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000,0.000000,2025-10-24
784249,22500092,1610612761,Toronto,Raptors,TOR,raptors,1642266,Ja'Kobe,Walter,J. Walter,jakobe-walter,NaN,DNP - Coach's Decision,0.0,NaN,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.00,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0,0,0,0,0,0,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0,0,0,0,0.000,0,0,0.00,0,0,0,0,0,0,0,0,0,0.0,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000,0.000000,2025-10-24

# Build player features (players and top players absence for each game)

In [18]:
player_features_df = build_player_status_features(df_boxscores)

today = datetime.now().strftime('%Y-%m-%d_%H-%M-%S')


os.makedirs(DATA_PLAYERS_DIR, exist_ok=True)
player_features_output = os.path.join(DATA_PLAYERS_DIR, f'player_features_{today}.csv')

# to csv
#player_features_df.to_csv(player_features_output, index=False)

In [19]:
player_features_df

,GAME_ID,TEAM_ID,GAME_DATE,personId,is_present,is_absent,is_injured,is_resting,is_suspended,is_personal,is_absent_other,player_perf_score,player_defense_score,player_offense_score,player_impact_score,comment
0,20000279,1610612741,2000-12-08,1897,1,0,0,0,0,0,0,22.9,5.5,18.5,0.156,
1,20000279,1610612741,2000-12-08,2033,1,0,0,0,0,0,0,17.8,-2.0,8.6,0.043,
2,20000279,1610612741,2000-12-08,1434,1,0,0,0,0,0,0,7.4,-3.5,-1.2,-0.007,
3,20000279,1610612741,2000-12-08,2064,1,0,0,0,0,0,0,28.8,-0.5,26.6,0.188,
4,20000279,1610612741,2000-12-08,1500,1,0,0,0,0,0,0,20.3,0.5,17.7,0.037,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
784245,22500092,1610612761,2025-10-24,1642347,1,0,0,0,0,0,0,11.0,1.5,10.8,0.099,
784246,22500092,1610612761,2025-10-24,1642367,1,0,0,0,0,0,0,2.4,1.5,-1.0,0.071,
784247,22500092,1610612761,2025-10-24,1642419,1,0,0,0,0,0,0,11.4,0.5,9.8,0.182,
784248,22500092,1610612761,2025-10-24,202066,0,1,0,0,0,0,1,0.0,0.0,0.0,0.000,dnp - coach's decision
784249,22500092,1610612761,2025-10-24,1642266,0,1,0,0,0,0,1,0.0,0.0,0.0,0.000,dnp - coach's decision

In [20]:
#print duplicates on 'GAME_ID' and 'TEAM_ID', personId
duplicates = player_features_df[player_features_df.duplicated(subset=['GAME_ID', 'TEAM_ID', 'personId'], keep=False)]
if not duplicates.empty:
    print("Duplicates found:")
    display(duplicates)

In [21]:
#player_features_df[player_features_df['is_absent'] == 1].sort_values(by='GAME_ID').head(50)

#same but filter with comment "DNP - Coach's Decision"

filtered = player_features_df[
    (player_features_df['is_absent'] == 1) &
    (~player_features_df['comment'].str.contains("coach's decision", na=False))
]
display(filtered.sort_values(by=['GAME_ID', 'TEAM_ID']).tail(10))

filtered = player_features_df[
    (player_features_df['is_personal'] == 1) &
    (~player_features_df['comment'].str.contains("personal", na=False)) &
    (~player_features_df['comment'].str.contains("not with team", na=False)) 
]
display(filtered.sort_values(by=['GAME_ID', 'TEAM_ID']).tail(10))




# display(player_features_df[
#     player_features_df['is_personal'] == 1 &
#     (~player_features_df['comment'].str.contains("nwt", na=False))
#     ].head(50))

,GAME_ID,TEAM_ID,GAME_DATE,personId,is_present,is_absent,is_injured,is_resting,is_suspended,is_personal,is_absent_other,player_perf_score,player_defense_score,player_offense_score,player_impact_score,comment
714168,52300201,1610612741,2024-04-19,1641763,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd - injury/illness
714169,52300201,1610612741,2024-04-19,1630172,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd - injury/illness
714182,52300201,1610612748,2024-04-19,202710,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd - injury/illness
714183,52300201,1610612748,2024-04-19,1626196,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd - injury/illness
714184,52300201,1610612748,2024-04-19,1626179,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd - injury/illness
748643,52400101,1610612737,2025-04-15,1630552,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnp - injury/illness
748697,52400111,1610612748,2025-04-16,1631107,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd - injury/illness
748699,52400111,1610612748,2025-04-16,201567,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd-return to competition reconditioning
748764,52400201,1610612737,2025-04-18,1630552,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd - injury/illness
748752,52400201,1610612748,2025-04-18,201567,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - personal

,GAME_ID,TEAM_ID,GAME_DATE,personId,is_present,is_absent,is_injured,is_resting,is_suspended,is_personal,is_absent_other,player_perf_score,player_defense_score,player_offense_score,player_impact_score,comment
354289,21200144,1610612738,2012-11-18,2545,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family reasons
355943,21200607,1610612745,2013-01-21,202962,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family reasons
381385,21201169,1610612756,2013-04-10,201563,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family reasons
365720,21201182,1610612739,2013-04-12,203079,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family matters
442619,21400441,1610612757,2014-12-26,2549,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family
432403,21400871,1610612737,2015-02-28,201143,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family reasons
81018,40100154,1610612759,2002-05-01,1495,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - death in family
133330,40400311,1610612759,2005-05-22,299,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family business
133344,40400312,1610612759,2005-05-24,299,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family business
133381,40400313,1610612759,2005-05-28,299,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family business

In [22]:

# Analyse des statuts des joueurs
total_rows = len(player_features_df)

# Comptage des cas
n_present = player_features_df['is_present'].sum()
n_absent = player_features_df['is_absent'].sum()
n_injured = player_features_df['is_injured'].sum()

# is_resting
# is_suspended
# is_personal

n_resting = player_features_df['is_resting'].sum()
n_suspended = player_features_df['is_suspended'].sum()
n_personal = player_features_df['is_personal'].sum()

# Lignes incohérentes : aucune des colonnes n'est True

mask_no_status = (
    (player_features_df['is_present'] == 0) &
    (player_features_df['is_absent'] == 0) &
    (player_features_df['is_injured'] == 0) &
    (player_features_df['is_resting'] == 0) &
    (player_features_df['is_suspended'] == 0) &
    (player_features_df['is_personal'] == 0)
)


n_inconsistent = mask_no_status.sum()

# Lignes avec plusieurs statuts à la fois (logiquement impossible)
mask_multiple_status = (
    player_features_df[['is_present', 'is_absent', 'is_injured']].sum(axis=1) > 1
)
n_multiple = mask_multiple_status.sum()

print(f"✅ Analyse des statuts des joueurs sur {total_rows} lignes")
print(f" - Joueurs présents : {n_present}")
print(f" - Joueurs absents : {n_absent}")
print(f" - Joueurs blessés : {n_injured}")
print(f" - Joueurs en repos : {n_resting}")
print(f" - Joueurs suspendus : {n_suspended}")
print(f" - Joueurs pour raisons personnelles : {n_personal}")
print(f"❌ Lignes sans statut défini : {n_inconsistent}")
print(f"⚠️ Lignes avec plusieurs statuts actifs : {n_multiple}")

display(player_features_df[mask_no_status].head(10))

✅ Analyse des statuts des joueurs sur 754146 lignes
 - Joueurs présents : 618911
 - Joueurs absents : 135235
 - Joueurs blessés : 21327
 - Joueurs en repos : 392
 - Joueurs suspendus : 1037
 - Joueurs pour raisons personnelles : 1005
❌ Lignes sans statut défini : 0
⚠️ Lignes avec plusieurs statuts actifs : 21327

Empty DataFrame
Columns: [GAME_ID, TEAM_ID, GAME_DATE, personId, is_present, is_absent, is_injured, is_resting, is_suspended, is_personal, is_absent_other, player_perf_score, player_defense_score, player_offense_score, player_impact_score, comment]
Index: []

# ⚙️ Aggrégation des data Player par équipe et match

In [23]:
# df_team_players = aggregate_team_player_features(player_features_df, top_n=10)

# display(df_team_players.head(10))
# display(df_team_players.tail(10))

# #display some lines with absent players
# absent_players = df_team_players[df_team_players['num_injured'] >= 1]
# absent_players 

# Identification des top joueurs sur l'ensemble du dataset
df_top_players = identify_historical_top_players(player_features_df)
print(f"✅ {df_top_players['is_historical_top'].sum()} top joueurs identifiés sur {len(df_top_players)} joueurs.")


df_agg_actual = aggregate_actual_team_features(player_features_df)
print(f"✅ {df_agg_actual.shape[0]} lignes générées dans l'aggregation actuelle par équipe.")

df_agg_top_abs = flag_top_players_absences(player_features_df, df_top_players)
print(f"✅ {df_agg_top_abs['top_player_absent'].sum()} absences de top joueurs détectées.")

df_team_features_final = df_agg_actual.merge(df_agg_top_abs, on=["GAME_ID", "TEAM_ID"], how="left")
df_team_features_final.fillna(0, inplace=True)

#add flags has_top_absent flag to use it as input and not roll it to see in analyse how much it helps to scrap this data before match
df_team_features_final['has_top_absent'] = df_team_features_final['top_player_absent'].apply(lambda x: 1 if x > 0 else 0)
df_team_features_final['has_absent'] = df_team_features_final['num_absent'].apply(lambda x: 1 if x > 0 else 0)


#sort by GAME_ID, TEAM_ID and GAME_DATE
df_team_features_final.sort_values(by=['GAME_ID', 'TEAM_ID', 'GAME_DATE'], inplace=True)


print(f"✅ Fusion réussie. Shape finale : {df_team_features_final.shape}")

/home/ju/Documents/Dev/NBA_Predictor/src/feature_aggregation.py:92: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  tops = roll.groupby(['GAME_ID', 'TEAM_ID']).apply(pick_top).reset_index()

✅ 308062 top joueurs identifiés sur 308062 joueurs.
✅ 63875 lignes générées dans l'aggregation actuelle par équipe.
✅ 19309 absences de top joueurs détectées.
✅ Fusion réussie. Shape finale : (63875, 27)

In [24]:
# display(df_team_features_final.head(10))
# display(df_team_features_final.tail(10))

# top_player_absence_rate
# top_player_injury_rate
# top_player_resting_rate
# top_player_suspension_rate
# top_player_personal_rate

# display(df_team_features_final[df_team_features_final['top_player_absent_rate'] > 0])
# display(df_team_features_final[df_team_features_final['top_player_injury_rate'] > 0])
# display(df_team_features_final[df_team_features_final['top_player_resting_rate'] > 0])
# display(df_team_features_final[df_team_features_final['top_player_suspension_rate'] > 0])
# display(df_team_features_final[df_team_features_final['top_player_personal_rate'] > 0])
display(df_team_features_final)

,GAME_ID,TEAM_ID,GAME_DATE,player_perf_score_mean,player_perf_score_sum,num_present,num_absent,num_injured,num_suspended,num_resting,num_personal,num_absent_other,top_player_count,top_player_absent,top_player_injured,top_player_resting,top_player_suspended,top_player_personal,top_player_absent_other,top_player_absent_rate,top_player_injury_rate,top_player_resting_rate,top_player_suspension_rate,top_player_personal_rate,top_player_absent_other_rate,has_top_absent,has_absent
0,20000001,1610612752,2000-10-31,10.450000,125.4,12,0,0,0,0,0,0,5,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
1,20000001,1610612755,2000-10-31,15.658333,187.9,12,0,0,0,0,0,0,5,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
2,20000002,1610612739,2000-10-31,13.866667,166.4,11,1,0,0,0,0,1,5,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1
3,20000002,1610612751,2000-10-31,14.950000,179.4,10,2,0,0,0,0,2,5,1,0,0,0,0,1,0.2,0.0,0.0,0.0,0.0,0.2,1,1
4,20000003,1610612753,2000-10-31,14.616667,175.4,10,2,0,0,0,0,2,5,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63870,52400131,1610612758,2025-04-16,14.253846,185.3,12,1,0,0,0,0,1,5,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1
63871,52400201,1610612737,2025-04-18,18.150000,217.8,9,3,1,0,0,0,2,5,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1
63872,52400201,1610612748,2025-04-18,15.686667,235.3,9,6,0,0,0,1,5,5,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1
63873,52400211,1610612742,2025-04-18,14.438462,187.7,11,2,0,0,0,0,2,5,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1
63874,52400211,1610612763,2025-04-18,17.461538,227.0,12,1,0,0,0,0,1,5,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1

# ⚙️ Aggrégation des data Boxscore purs par équipe et match

## 📊 Agrégation des données par équipe et match

In [25]:

# 1. Agrégation par somme
group_keys = ['GAME_ID', 'TEAM_ID']
sum_agg = df_boxscores[group_keys + cols_to_sum].copy()
sum_agg = sum_agg.groupby(group_keys).sum().reset_index()

# 2. Agrégation pondérée par les minutes jouées
weighted_agg = compute_weighted_mean_features(df_boxscores, group_keys, cols_to_weighted_avg, weight_col='MINUTES_PLAYED')

# 3. Fusion des deux agrégats
team_match_stats = pd.merge(sum_agg, weighted_agg, on=group_keys, how='left')

# 4. Identifier l'équipe adverse
teams_in_game = df_boxscores.groupby('GAME_ID')['TEAM_ID'].unique().to_dict()
def get_opponent(row):
    teams = teams_in_game.get(row['GAME_ID'], [])
    opps = [tid for tid in teams if tid != row['TEAM_ID']]
    return opps[0] if opps else None

team_match_stats['OPP_TEAM_ID'] = team_match_stats.apply(get_opponent, axis=1)

In [26]:
count = 0

for game_id, teams in teams_in_game.items():
    if len(teams) < 2:
        #print(f"Attention : GAME_ID {game_id} a moins de 2 équipes : {teams}")
        count += 1
        
print(f"Nombre de GAME_ID avec moins de 2 équipes : {count}")

Nombre de GAME_ID avec moins de 2 équipes : 393

# 🔁 Ajout des colonnes OPP_ avec les data de l'adversaire

In [27]:
team_cols = [col for col in team_match_stats.columns if col not in ['GAME_ID', 'TEAM_ID', 'OPP_TEAM_ID']]
opp_cols = [f"OPP_{col}" for col in team_cols]
df_opp = team_match_stats.rename(columns={col: f"OPP_{col}" for col in team_cols}).rename(
    columns={'TEAM_ID': 'OPP_TEAM_ID', 'OPP_TEAM_ID': 'TEAM_ID'})
match_dataset = pd.merge(
    team_match_stats,
    df_opp[['GAME_ID', 'TEAM_ID'] + opp_cols],
    on=['GAME_ID', 'TEAM_ID'],
    how='left'
)

In [28]:
match_dataset.columns

Index(['GAME_ID', 'TEAM_ID', 'fieldGoalsMade_traditional',
       'fieldGoalsAttempted_traditional', 'threePointersMade_traditional',
       'threePointersAttempted_traditional', 'freeThrowsMade_traditional',
       'freeThrowsAttempted_traditional', 'reboundsOffensive_traditional',
       'reboundsDefensive_traditional',
       ...
       'OPP_percentageReboundsTotal_usage', 'OPP_percentageAssists_usage',
       'OPP_percentageTurnovers_usage', 'OPP_percentageSteals_usage',
       'OPP_percentageBlocks_usage', 'OPP_percentageBlocksAllowed_usage',
       'OPP_percentagePersonalFouls_usage',
       'OPP_percentagePersonalFoulsDrawn_usage', 'OPP_percentagePoints_usage',
       'OPP_plusMinusPoints_traditional'],
      dtype='object', length=165)

# 🏠 Ajout IS_HOME et IS_WIN

In [29]:
df_games

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS,SEASON
0,22010,1610612738,BOS,Boston Celtics,21000001,2010-10-26,BOS vs. MIA,W,239,88,32,69,0.464,8,16,0.500,16,25,0.640,8,34,42,25,6,4,18,19,8.0,2010-11
1,22010,1610612756,PHX,Phoenix Suns,21000002,2010-10-26,PHX @ POR,L,239,92,36,74,0.486,9,19,0.474,11,16,0.688,7,23,30,15,3,4,19,19,-14.0,2010-11
2,22010,1610612745,HOU,Houston Rockets,21000003,2010-10-26,HOU @ LAL,L,240,110,38,91,0.418,8,20,0.400,26,28,0.929,16,37,53,25,6,7,20,25,-2.0,2010-11
3,22010,1610612757,POR,Portland Trail Blazers,21000002,2010-10-26,POR vs. PHX,W,240,106,43,93,0.462,10,20,0.500,10,15,0.667,18,30,48,31,11,2,12,22,14.0,2010-11
4,22010,1610612748,MIA,Miami Heat,21000001,2010-10-26,MIA @ BOS,L,242,80,27,74,0.365,8,20,0.400,18,25,0.720,11,28,39,15,10,6,17,21,-8.0,2010-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66921,22025,1610612737,ATL,Atlanta Hawks,22500020,2025-10-31,ATL @ IND,W,239,128,51,94,0.543,10,30,0.333,16,20,0.800,12,43,55,30,10,5,10,23,20.0,2025-26
66922,22025,1610612763,MEM,Memphis Grizzlies,22500024,2025-10-31,MEM vs. LAL,NaN,0,8,3,3,1.000,1,1,1.000,1,2,0.500,0,2,2,3,1,0,1,0,4.0,2025-26
66923,22025,1610612747,LAL,Los Angeles Lakers,22500024,2025-10-31,LAL @ MEM,NaN,0,4,2,4,0.500,0,2,0.000,0,0,NaN,0,0,0,1,1,0,2,2,-4.0,2025-26
66924,22025,1610612739,CLE,Cleveland Cavaliers,22500022,2025-10-31,CLE vs. TOR,NaN,241,93,33,80,0.413,13,42,0.310,14,22,0.636,12,25,37,22,9,10,12,14,-6.4,2025-26
66925,22025,1610612761,TOR,Toronto Raptors,22500022,2025-10-31,TOR @ CLE,NaN,240,98,35,75,0.467,11,28,0.393,17,22,0.773,10,35,45,24,8,3,15,17,10.6,2025-26

In [30]:
match_dataset

,GAME_ID,TEAM_ID,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,points_traditional,MINUTES_PLAYED,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,blocksAgainst_misc,offensiveRating_advanced,defensiveRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,threePointersPercentage_traditional,freeThrowsPercentage_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage,plusMinusPoints_traditional,OPP_TEAM_ID,OPP_fieldGoalsMade_traditional,OPP_fieldGoalsAttempted_traditional,OPP_threePointersMade_traditional,OPP_threePointersAttempted_traditional,OPP_freeThrowsMade_traditional,OPP_freeThrowsAttempted_traditional,OPP_reboundsOffensive_traditional,OPP_reboundsDefensive_traditional,OPP_reboundsTotal_traditional,OPP_assists_traditional,OPP_steals_traditional,OPP_blocks_traditional,OPP_turnovers_traditional,OPP_foulsPersonal_traditional,OPP_points_traditional,OPP_MINUTES_PLAYED,OPP_pointsOffTurnovers_misc,OPP_pointsSecondChance_misc,OPP_pointsFastBreak_misc,OPP_pointsPaint_misc,OPP_blocksAgainst_misc,OPP_offensiveRating_advanced,OPP_defensiveRating_advanced,OPP_netRating_advanced,OPP_assistPercentage_advanced,OPP_assistToTurnover_advanced,OPP_assistRatio_advanced,OPP_offensiveReboundPercentage_advanced,OPP_defensiveReboundPercentage_advanced,OPP_reboundPercentage_advanced,OPP_turnoverRatio_advanced,OPP_effectiveFieldGoalPercentage_advanced,OPP_trueShootingPercentage_advanced,OPP_usagePercentage_advanced,OPP_estimatedPace_advanced,OPP_pace_advanced,OPP_possessions_advanced,OPP_PIE_advanced,OPP_effectiveFieldGoalPercentage_fourfactors,OPP_freeThrowAttemptRate_fourfactors,OPP_teamTurnoverPercentage_fourfactors,OPP_oppEffectiveFieldGoalPercentage_fourfactors,OPP_oppFreeThrowAttemptRate_fourfactors,OPP_oppTeamTurnoverPercentage_fourfactors,OPP_oppOffensiveReboundPercentage_fourfactors,OPP_foulsDrawn_misc,OPP_percentageFieldGoalsAttempted2pt_scoring,OPP_percentageFieldGoalsAttempted3pt_scoring,OPP_percentagePoints2pt_scoring,OPP_percentagePointsMidrange2pt_scoring,OPP_percentagePoints3pt_scoring,OPP_percentagePointsFastBreak_scoring,OPP_percentagePointsFreeThrow_scoring,OPP_percentagePointsOffTurnovers_scoring,OPP_percentagePointsPaint_scoring,OPP_percentageAssisted2pt_scoring,OPP_percentageUnassisted2pt_scoring,OPP_percentageAssisted3pt_scoring,OPP_percentageUnassisted3pt_scoring,OPP_percentageAssistedFGM_scoring,OPP_percentageUnassistedFGM_scoring,OPP_threePointersPercentage_traditional,OPP_freeThrowsPercentage_traditional,OPP_percentageFieldGoalsMade_usage,OPP_percentageFieldGoalsAttempted_usage,OPP_percentageThreePointersMade_usage,OPP_percentageThreePointersAttempted_usage,OPP_percentageFreeThrowsMade_usage,OPP_percentageFreeThrowsAttempted_usage,OPP_percentageReboundsOffensive_usage,OPP_percentageReboundsDefensive_usage,OPP_percentageReboundsTotal_usage,OPP_percentageAssists_usage,OPP_percentageTurnovers_usage,OPP_percentageSteals_usage,OPP_percentageBlocks_usage,OPP_percentageBlocksAllowed_usage,OPP_percentagePersonalFouls_usage,OPP_percentagePersonalFoulsDrawn_usage,OPP_percentagePoints_usage,OPP_plusMinusPoints_traditional
0,20000001,1610612752,25,70,3,11,19,24,14,23,37,14,6,4,22,30,72,240.000000,12,15,4,22,5,80.922299,114.464688,-33.537868,0.163246,0.523610,11.026556,0.056220,0.147483,0.091563,19.763500,0.372955,0.436562,0.193970,88.699676,88.699676,43.962361,0.039403,0.377483,0.365924,0.247518,0.598126,0.458272,0.160368,0.266661,0.000000,0.857836,0.142164,0.650577,0.241035,0.057733,0.039143,0.257106,0.165235,0.409507,0.518244,0.447172,0.197778,0.000000,0.559933,0.405484,0.108844,0.466333,0.213520,0.203724,0.197778,0.193515,0.199331,0.190465,0.232461,0.204200,0.204153,0.200857,0.197202,0.196856,0.199583,0.160243,0.192422,0.000000,0.201207,-14.930903,1610612755,38.0,66.0,3.0,8.0,22.0,30.0,8.0,29.0,37.0,27.0,10.0,5.0,13.0,24.0,101.0,240.000000,26.0,9.0,10.0,36.0,4.0,113.678208,80.924167,32.729556,0.182441,1.177822,20.832340,0.049657,0.117050,0.092804,12.917368,0.562437,0.596134,0.194474,88.899378,88.899378,50.502014,0.160855,0.601599,0.469504,0.161353,0.382886,0.361238,0.246772,0.319077,0.000000,0.839428,0.116266,0.644489,0.293966,0.049281,0.125861,0.169078,0.233654,0.350402,0.615402,0.247446,0.168090,0.078368,0.629851,0.232997,0.168090,0.508698,0.203276,0.200388,0.194265,0.173397,0.203479,0.208561,0.163576,0.192186,0.195743,0.196602,0.176540,0.217619,0.134035,0.178715,0.194042,0.000000,0.208010,18.242986
1,20000001,1610612755,38,66,3,8,22,30,8,29,37,27,10,5,13,24,101,240.000000,26,9,10,36,4,113.678208,80.924167,32.729556,0.182441,1.177822,20.832340,0.049657,0.117050,0.092804,12.917368,0.562437,0.596134,0.194474,88.899378,88.899378,50.502014,0.160855,0.601599,0.469504,0.161353,0.382886,0.361238,0.246772,0.319077,0.000000,0.839428,0.116266,0.644489,0.293966,0.049281,0.125861,0.169078,0.233654,0.350402,0.615402,0.247446,0.168090,0.078368,0.629851,0.232997,0.168090,0.508698,0.203276,0.200388,0.194265,0.173397,0.203479,0.208561,0.163576,0.192186,0.195743,0.196602,0.176540,0.217619,0.134035,0.178715,0.194042,0.000000,0.208010,18.242986,1610612752,25.0,70.0,3.0,11.0,19.0,24.0,14.0,23.0,37.0,14.0,6.0,4.0,22.0,30.0,72.0,240.000000,12.0,15.0,4.0,22.0,5.0,80.922299,114.464688,-33.537868,0.163246,0.523610,11.026556,0.056220,0.147483,0.091563,19.763500,0.372955,0.436562,0.193970,88.699676,88.699676,43.962361,0.039403,0.377483,0.365924,0.247518,0.598126,0.458272,0.160368,0.266661,0.000000,0.857836,0.142164,0.650577,0.241035,0.057733,0.039143,0.257106,0.165235,0.409507,0.518244,0.447172,0.197778,0.000000,0.559933,0.405484,0.108844,0.466333,0.213520,0.203724,0.197778,0.193515,0.199331,0.190465,0.232461,0.204200,0.204153,0.200857,0.197202,0.196856,0.199583,0.160243,0.192422,0.000000,0.201207,-14.930903
2,20000002,1610612739,32,78,2,7,20,32,11,41,52,16,5,8,19,27,86,240.000000,12,12,14,36,8,87.118465,82.284514,4.836236,0.135260,0.953071,12.727431,0.043157,0.154742,0.099091,13.891264,0.403829,0.477510,0.197340,99.597600,99.597600,55.404514,0.027378,0.423046,0.418163,0.189245,0.385467,0.306368,0.150790,0.226623,0.000000,0.905348,0.071110,0.619452,0.225391,0.042091,0.151227,0.250680,0.134511,0.394061,0.380781,0.531441,0.226319,0.000000,0.404284,0.507939,0.179271,0.558568,0.200988,0.201629,0.113160,0.180712,0.189883,0.188048,0.223730,0.215432,0.215471,0.206409,0.202678,0.200235,0.161342,0.223420,0.197098,0.000000,0.194632,4.139722,1610612751,31.0,85.0,3.0,10.0,17.0,26.0,12.0,35.0,47.0,24.0,9.0,8.0,12.0,31.0,82.0,240.000000,21.0,13.0,9.0,42.0,8.0,83.457417,86.645424,-3.170028,0.186321,1.655972,19.164549,0.044377,0.128634,0.084390,9.645229,0.334428,0.403052,0.190604,98.798017,98.798017,59.042292,0.112319,0.383964,0.309240,0.149999,0.421320,0.418921,0.191348,0.243931,0.000000,0.892640,0.107360,0.589287,0.177226,0.068950,0.074612,0.329879,0.171267,0.412061,0.623859,0.250308,0.227153,0.000000,0.623859,0.250308,0.129859,0.680444,0.195359,0.199699,0.140674,0.162797,0.207021,0.210566,0.241208,0.196126,0.197293,0.200915,0.151191,0.198521,0.187091,0.206165,0.210120,0.000000,0.192918,-2.137222
3,20000002,1610612751,31,85,3,10,17,26,12,35,47,24,9,8,12,31,82,240.000000,21,13,9,42,8,83.457417,86.645424,-3.170028,0.186321,1.655972,19.164549,0.044377,0.128634,0.084390,9.645229,0.334428,0.403052,0.190604,98.798017,98.798017,59.042292,0.112319,0.383964,0.309240,0.149999,0.421320,0.418921,0.191348,0.243931,0.000000,0.892640,0.107360,0.589287,0.177226,0.068950,0.074612,0.329879,0.171267,0.412061,0.623859,0.250308,0.227153,0.000000,0.623859,0.250308,0.129859,0.680444,0.195359,0.199699,0.140674,0.162797,0.207021,0.210566,0.241208,0.196126,0.197293,0.200915,0.151191,0.198521,0.187091,0.206165,0.210120,0.000000,0.192918,-2.137222,1610612739,32.0,78.0,2.0,7.0,20.0,32.0,11.0,41.0,52.0,16.0,5.0,8.0,19.0,27.0,86.0,240.000000,12.0,12.0,14.0,36.0,8.0,87.118465,82.284514,4.836236,0.135260,0.953071,12.727431,0.043157,0.154742,0.099091,13.891264,0.403829,0.477510,0.197340,99.597600,99.597600,55.404514,0.027378,0.423046,0.418163,0.189245,0.385467,0.306368,0.150790,0.226623,0.000000,0.905348,0.071110,0.619452,0.225391,0.042091,0.151227,0.250680,0.134511,0.394061,0.380781,0.531441,0.226319,0.000000,0.404284,0.507939,0.179271,0.558568,0.200988,0.201629,0.113160,0.180712,0.189883,0.188048,0.223730,0.215432,0.215471,0.206409,0.202678,0.200235,0.161342,0.223420,0.197098,0.000000,0.194632,4.139722
4,20000003,1610612753,34,79,6,16,23,33,8,29,37,20,10,9,15,24,97,240.000000,28,9,19,32,1,98.736875,86.636882,12.099993,0.142503,0.857986,12.904542,0.031709,0.133742,0.081268,11.997660,0.475912,0.520254,0.200260,98.899090,98.899090,61.198889,0.118825,0.472056,0.423020,0.148499,0.486995,0.336534,0.267238,0.238280,0.000000,0.799790,0.200210,0.571690,0.237194,0.199434,0.245441,0.229067,0.346846,0.334358,0.459721,0.398473,0.403889,0.000000,0.606531,0.371316,0.186988,0.685047,0.200331,0.201844,0.229832,0.189043,0.227233,0.227924,0.167742,0.196079,0.201831,0.197763,0.182205,0.192654,0.169992,0.065000,0.193451,0.000000,0.204198,7.283056,1610612764,33.0,72.0,4.0,7.0,16.0,24.0,9.0,35.0,44.0,20.0,6.0,1.0,26.0,28.0,86.0,240.000000,15.0,12.0,14.0,42.0,9.0,87.675576,98.295687,-10.619472,0.149045,0.627285,14.817028,0.042904,0.148099,0.098173,19.670639,0.520195,0.553401,0.194765,98.401342,98.401342,53.393403,0.101201,0.485589,0.342879,0.267129,0.470513,0.418830,0.148780,0.185661,0.000000,0.916404,0.083596,0.632414,0.206632,0.148603,0.156626,0.189113,0.165165,0.425926,0.502342,0.467588,0.432986,0.000000,0.600256,0.369674,0.276597,0.604405,0.194938,0.201348,0.157969,0.160486,0.177851,0.170195,0.210115,0.209455,0.210824,0.194940,0.196138,0.138369,0.109583,0.186508,0.215050,0.000000,0.198386,-6.894514
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63870,52400131,1610612758,41,89,13,33,11,15,15,29,44,23,6,4,18,19,106,240.000000,15,13,15,40,8,110.123410,123.832694,-13.692986,0.144001,0.915579,16.246007,0.061248,0.139456,0.094800,13.410542,0.553654,0.568678,0.196805,96.900852,96.900852,64.197361,0.078930,0.533497,0.168455,0.181755,0.589886,0.321300,0.106123,0.242713,1.925417,0.579009,0.412449,0.498701,0.103705,0.374451,0.147024,0.093555,0.120819,0.394996,0.601385,0.356601,0.625625,0.137917,0.614244,0.352284,0.337209,0.444622,0.198443,0.199547,0.199186,0.197010,0.199987,0.198947,0.220836,0.204731,0.202397,0.198671,0.194704,0.193650,0.140420,0.176580,0.204741,0.201187,0.198282,-14.351250,1610612742,41.0,83.0,14.0,28.0,24.0,26.0,10.0,31.0,41.0,29.0,9.0,8.0,9.0,15.0,120.0,240.000000,18.0,4.0,14.0,40.0,4.0,123.867549,110.768076,13.093542,0.179320,1.234705,23.328986,0.043102,0.126057,0.088669,7.650514,0.614891,0.653447,0.190092,96.700401,96.700401,52.394028,0.120096,0.586034,0.319399,0.106316,0.531757,0.167544,0.181331,0.320657,2.229653,0.660342,0.331116,0.484243,0.140879,0.266205,0.119458,0.173500,0.127531,0.343317,0.539994,0.384173,0.710417,0.000000,0.693429,0.230738,0.371341,0.690868,0.189465,0.197248,0.188922,0.192500,0.200256,0.200080,0.177569,0.202057,0.201182,0.211608,0.180998,0.195077,0.211063,0.166207,0.202276,0.192422,0.188871,13.047708
63871,52400201,1610612737,44,102,16,47,10,12,11,33,44,30,12,3,9,18,114,265.016667,21,14,22,56,8,108.972216,113.769398,-4.786328,0.170940,1.701450,19.786856,0.038220,0.132929,0.082033,6.828665,0.533646,0.548288,0.194796,96.542768,96.542768,70.793032,0.094415,0.515043,0.115509,0.094355,0.582867,0.189826,0.139047,0.283225,2.338658,0.528556,0.471444,0.478198,0.000000,0.421953,0.212341,0.069536,0.130952,0.478198,0.664189,0.249212,0.692064,0.218571,0.717321,0.252367,0.401740,0.302049,0.201907,0.198260,0.191661,0.199505,0.163951,0.180012,0.223868,0.200502,0.200689,0.193867,0.160034,0.206388,0.145900,0.193684,0.193772,0.193633,0.199234,-6.091126,1610612748,48.0,96.0,16.0,42.0,11.0,18.0,13.0,41.0,54.0,33.0,4.0,8.0,14.0,15.0,123.0,265.000000,18.0,17.0,14.0,48.0,3.0,114.115346,109.194151,4.941660,0.175512,1.914025,21.394906,0.052826,0.136744,0.098506,8.743547,0.602740,0.610614,0.188164,96.271151,96.271151,74.389497,0.108900,0.582882,0.188123,0.140615,0.511179,0.117131,0.094058,0.210104,2.789245,0.569122,0.430878,0.531708,0.131616,0.389409,0.104841,0.078883,0.158831,0.400093,0.679972,0.320028,0.594560,0.156132,0.689231,0.310769,0.317894,0.399580,0.200367,0.200068,0.199439,0.200160,0.203244,0.198173,0.193693,0.197318,0.198007,0.203462,0.175619,0.211259,0.195655,0.227722,0.201947,0.191826,0.199943,7.759057
63872,52400201,1610612748,48,96,16,42,11,18,13,41,54,33,4,8,14,15,123,265.000000,18,17,14,48,3,114.115346,109.194151,4.941660,0.175512,1.914025,21.394906,0.052826,0.136744,0.098506,8.743547,0.602740,0.610614,0.188164,96.271151,96.271151,74.389497,0.108900,0.582882,0.188123,0.140615,0.511179,0.117131,0.094058,0.210104,2.789245,0.569122,0.430878,0.531708,0.131616,0.389409,0.104841,0.078883,0.158831,0.400093,0.679972,0.320028,0.594560,0.156132,0.689231,0.310769,0.317894,0.399580,0.200367,0.200068,0.199439,0.200160,0.203244,0.198173,0.193693,0.197318,0.198007,0.203462,0.175619,0.211259,0.195655,0.227722,0.201947,0.191826,0.199943,7.759057,1610612737,44.0,102.0,16.0,47.0,10.0,12.0,11.0,33.0,44.0,30.0,12.0,3.0,9.0,18.0,114.0,265.016667,21.0,14.0,22.0,56.0,8.0,108.972216,113.769398,-4.786328,0.170940,1.701450,19.786856,0.038220,0.132929,0.082033,6.828665,0.533646,0.548288,0.194796,96.542768,96.542768,70.793032,0.094415,0.515043,0.115509,0.094355,0.582867,0.189826,0.139047,0.283225,2.338658,0.528556,0.471444,0.478198,0.000000,0.421953,0.212341,0.069536,0.130952,0.478198,0.664189,0.249212,0.692064,0.218571,0.717321,0.252367,0.401740,0.302049,0.201907,0.198260,0.191661,0.199505,0.163951,0.180012,0.223868,0.200502,0.200689,0.193867,0.160034,0.206388,0.145900,0.193684,0.193772,0.193633,0.199234,-6.091126
63873,52400211,1610612742,41,87,12,38,12,16,7,29,36,25,9,8,16,17,106,239.983333,14,15,15,44,4,103.971838,117.104361,-13.146712,0.159645,1.043291,21.438058,0.028121,0.109295,0.071448,14.196291,0.505059,0.518344,0.194360,102.200355,102.200355,55.776790,0.083048,0.540618,0.184078,0.155320,0.534614,0.150467,0.117294,0.351484,1.775957,0.589597,0.410403,0.375406,0.089519,0.288293,0.120119,0.077834,0.102521,0.286029,0.431148,0.256678,0.465397,0.199927,0.498200,0.243395,0.324056,0.404056,0.199455,0.198674,0.234511,0.197563,0.188766,0.193288,0.179929,0.199788,0.199410,0.199269,0.194797,0.201698,0.189836,0.148746,0.180069,0.178183,0.199691,-8.414820,1610612763,47.0,100.0,13.0,31.0,13.0,15.0,16.0,34.0,50.0,30.0,8.0,4.0,10.0,17.0,120.0,240.000000,24.0,15.0,19.0,60.0,8.0,118.571125,105.071556,13.509528,0.154672,0.823437,19.079396,0.059757,0.149789,0.100197,4.889924,0.566430,0.582027,0.191697,101.299056,101.299056,62.138194,0.109814,0.532094,0.153846,0.116233,0.542366,0.187143,0.155200,0.164587,2.136944,0.650762,0.334099,0.569661,0.056488,0.328575,0.226652,0.078919,0.205619,0.513310,0.620063,0.349659,0.682240,0.087343,0.648875,0.320847,0.348328,0.327988,0.197052,0.199753,0.185188,0.203577,0.155673,0.161807,0.197832,0.203155,0.201390,0.197460,0.149565,0.187630,0.217161,0.174559,0.196685,0.173665,0.201920,11.408611
63874,52400211,1610612763,47,100,13,31,13,15,16,34,50,30,8,4,10,17,120,240.000000,24,15,19,60,8,118.571125,105.071556,13.509528,0.154672,0.823437,19.079396,0.059757,0.149789,0.100197,4.889924,0.566430,0.582027,0.191697,101.299056,101.299056,62.138194,0.109814,0.532094,0.153846,0.116233,0.542366,0.187143,0.155200,0.164587,2.136944,0.650762,0.334099,0.569661,0.056488,0.328575,0.226652,0.078919,0.205619,0.513310,0.620063,0.349659,0.682240,0.087343,0.648875,0.320847,0.348328,0.327988,0.197052,0.199753,0.185188,0.203577,0.155673,0.161807,0.197832,0.203155,0.201390,0.197460,0.149565,0.187630,0.217161,0.174559,0.196685,0.173665,0.201920,11.408611,1610612742,41.0,87.0,12.0,38.0,12.0,16.0,7.0,29.0,36.0,25.0,9.0,8.0,16.0,17.0,106.0,239.983333,14.0,15.0,15.0,44.0,4.0,103.971838,117.104361,-13.146712,0.159645,1.043291,21.438058,0.028121,0.109295,0.071448,14.196291,0.505059,0.518344,0.194360,102.200355,102.200355,55.776790,0.083048,0.540618,0.184078,0.155320,0.534614,0.150467,0.117294,0.351484,1.775957,0.589597,0.410403,0.375406,0.089519,0.288293,0.120119,0.077834,0.102521,0.286029,0.431148,0.256678,0.465397,0.199927,0.498200,0.243395,0.324056,0.404056,0.199455,0.198674,0.234511,0.197563,0.188766,0.193288,0.179929,0.199788,0.199410,0.199269,0.194797,0.201698,0.189836,0.148746,0.180069,0.178183,0.199691,-8.414820

In [31]:
# Assurer le format datetime pour GAME_DATE
df_games['GAME_DATE'] = pd.to_datetime(df_games['GAME_DATE'])



# Merge avec les infos de match (MATCHUP, SEASON)
match_dataset = match_dataset.merge(
    df_games[['GAME_ID', 'TEAM_ID', 'MATCHUP', 'SEASON','GAME_DATE']],
    on=['GAME_ID', 'TEAM_ID'],
    how='left'
)

In [32]:

print("match_dataset after merge")
display(match_dataset)

match_dataset after merge

,GAME_ID,TEAM_ID,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,points_traditional,MINUTES_PLAYED,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,blocksAgainst_misc,offensiveRating_advanced,defensiveRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,threePointersPercentage_traditional,freeThrowsPercentage_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage,plusMinusPoints_traditional,OPP_TEAM_ID,OPP_fieldGoalsMade_traditional,OPP_fieldGoalsAttempted_traditional,OPP_threePointersMade_traditional,OPP_threePointersAttempted_traditional,OPP_freeThrowsMade_traditional,OPP_freeThrowsAttempted_traditional,OPP_reboundsOffensive_traditional,OPP_reboundsDefensive_traditional,OPP_reboundsTotal_traditional,OPP_assists_traditional,OPP_steals_traditional,OPP_blocks_traditional,OPP_turnovers_traditional,OPP_foulsPersonal_traditional,OPP_points_traditional,OPP_MINUTES_PLAYED,OPP_pointsOffTurnovers_misc,OPP_pointsSecondChance_misc,OPP_pointsFastBreak_misc,OPP_pointsPaint_misc,OPP_blocksAgainst_misc,OPP_offensiveRating_advanced,OPP_defensiveRating_advanced,OPP_netRating_advanced,OPP_assistPercentage_advanced,OPP_assistToTurnover_advanced,OPP_assistRatio_advanced,OPP_offensiveReboundPercentage_advanced,OPP_defensiveReboundPercentage_advanced,OPP_reboundPercentage_advanced,OPP_turnoverRatio_advanced,OPP_effectiveFieldGoalPercentage_advanced,OPP_trueShootingPercentage_advanced,OPP_usagePercentage_advanced,OPP_estimatedPace_advanced,OPP_pace_advanced,OPP_possessions_advanced,OPP_PIE_advanced,OPP_effectiveFieldGoalPercentage_fourfactors,OPP_freeThrowAttemptRate_fourfactors,OPP_teamTurnoverPercentage_fourfactors,OPP_oppEffectiveFieldGoalPercentage_fourfactors,OPP_oppFreeThrowAttemptRate_fourfactors,OPP_oppTeamTurnoverPercentage_fourfactors,OPP_oppOffensiveReboundPercentage_fourfactors,OPP_foulsDrawn_misc,OPP_percentageFieldGoalsAttempted2pt_scoring,OPP_percentageFieldGoalsAttempted3pt_scoring,OPP_percentagePoints2pt_scoring,OPP_percentagePointsMidrange2pt_scoring,OPP_percentagePoints3pt_scoring,OPP_percentagePointsFastBreak_scoring,OPP_percentagePointsFreeThrow_scoring,OPP_percentagePointsOffTurnovers_scoring,OPP_percentagePointsPaint_scoring,OPP_percentageAssisted2pt_scoring,OPP_percentageUnassisted2pt_scoring,OPP_percentageAssisted3pt_scoring,OPP_percentageUnassisted3pt_scoring,OPP_percentageAssistedFGM_scoring,OPP_percentageUnassistedFGM_scoring,OPP_threePointersPercentage_traditional,OPP_freeThrowsPercentage_traditional,OPP_percentageFieldGoalsMade_usage,OPP_percentageFieldGoalsAttempted_usage,OPP_percentageThreePointersMade_usage,OPP_percentageThreePointersAttempted_usage,OPP_percentageFreeThrowsMade_usage,OPP_percentageFreeThrowsAttempted_usage,OPP_percentageReboundsOffensive_usage,OPP_percentageReboundsDefensive_usage,OPP_percentageReboundsTotal_usage,OPP_percentageAssists_usage,OPP_percentageTurnovers_usage,OPP_percentageSteals_usage,OPP_percentageBlocks_usage,OPP_percentageBlocksAllowed_usage,OPP_percentagePersonalFouls_usage,OPP_percentagePersonalFoulsDrawn_usage,OPP_percentagePoints_usage,OPP_plusMinusPoints_traditional,MATCHUP,SEASON,GAME_DATE
0,20000001,1610612752,25,70,3,11,19,24,14,23,37,14,6,4,22,30,72,240.000000,12,15,4,22,5,80.922299,114.464688,-33.537868,0.163246,0.523610,11.026556,0.056220,0.147483,0.091563,19.763500,0.372955,0.436562,0.193970,88.699676,88.699676,43.962361,0.039403,0.377483,0.365924,0.247518,0.598126,0.458272,0.160368,0.266661,0.000000,0.857836,0.142164,0.650577,0.241035,0.057733,0.039143,0.257106,0.165235,0.409507,0.518244,0.447172,0.197778,0.000000,0.559933,0.405484,0.108844,0.466333,0.213520,0.203724,0.197778,0.193515,0.199331,0.190465,0.232461,0.204200,0.204153,0.200857,0.197202,0.196856,0.199583,0.160243,0.192422,0.000000,0.201207,-14.930903,1610612755,38.0,66.0,3.0,8.0,22.0,30.0,8.0,29.0,37.0,27.0,10.0,5.0,13.0,24.0,101.0,240.000000,26.0,9.0,10.0,36.0,4.0,113.678208,80.924167,32.729556,0.182441,1.177822,20.832340,0.049657,0.117050,0.092804,12.917368,0.562437,0.596134,0.194474,88.899378,88.899378,50.502014,0.160855,0.601599,0.469504,0.161353,0.382886,0.361238,0.246772,0.319077,0.000000,0.839428,0.116266,0.644489,0.293966,0.049281,0.125861,0.169078,0.233654,0.350402,0.615402,0.247446,0.168090,0.078368,0.629851,0.232997,0.168090,0.508698,0.203276,0.200388,0.194265,0.173397,0.203479,0.208561,0.163576,0.192186,0.195743,0.196602,0.176540,0.217619,0.134035,0.178715,0.194042,0.000000,0.208010,18.242986,NYK vs. PHI,2000-01,2000-10-31
1,20000001,1610612755,38,66,3,8,22,30,8,29,37,27,10,5,13,24,101,240.000000,26,9,10,36,4,113.678208,80.924167,32.729556,0.182441,1.177822,20.832340,0.049657,0.117050,0.092804,12.917368,0.562437,0.596134,0.194474,88.899378,88.899378,50.502014,0.160855,0.601599,0.469504,0.161353,0.382886,0.361238,0.246772,0.319077,0.000000,0.839428,0.116266,0.644489,0.293966,0.049281,0.125861,0.169078,0.233654,0.350402,0.615402,0.247446,0.168090,0.078368,0.629851,0.232997,0.168090,0.508698,0.203276,0.200388,0.194265,0.173397,0.203479,0.208561,0.163576,0.192186,0.195743,0.196602,0.176540,0.217619,0.134035,0.178715,0.194042,0.000000,0.208010,18.242986,1610612752,25.0,70.0,3.0,11.0,19.0,24.0,14.0,23.0,37.0,14.0,6.0,4.0,22.0,30.0,72.0,240.000000,12.0,15.0,4.0,22.0,5.0,80.922299,114.464688,-33.537868,0.163246,0.523610,11.026556,0.056220,0.147483,0.091563,19.763500,0.372955,0.436562,0.193970,88.699676,88.699676,43.962361,0.039403,0.377483,0.365924,0.247518,0.598126,0.458272,0.160368,0.266661,0.000000,0.857836,0.142164,0.650577,0.241035,0.057733,0.039143,0.257106,0.165235,0.409507,0.518244,0.447172,0.197778,0.000000,0.559933,0.405484,0.108844,0.466333,0.213520,0.203724,0.197778,0.193515,0.199331,0.190465,0.232461,0.204200,0.204153,0.200857,0.197202,0.196856,0.199583,0.160243,0.192422,0.000000,0.201207,-14.930903,PHI @ NYK,2000-01,2000-10-31
2,20000002,1610612739,32,78,2,7,20,32,11,41,52,16,5,8,19,27,86,240.000000,12,12,14,36,8,87.118465,82.284514,4.836236,0.135260,0.953071,12.727431,0.043157,0.154742,0.099091,13.891264,0.403829,0.477510,0.197340,99.597600,99.597600,55.404514,0.027378,0.423046,0.418163,0.189245,0.385467,0.306368,0.150790,0.226623,0.000000,0.905348,0.071110,0.619452,0.225391,0.042091,0.151227,0.250680,0.134511,0.394061,0.380781,0.531441,0.226319,0.000000,0.404284,0.507939,0.179271,0.558568,0.200988,0.201629,0.113160,0.180712,0.189883,0.188048,0.223730,0.215432,0.215471,0.206409,0.202678,0.200235,0.161342,0.223420,0.197098,0.000000,0.194632,4.139722,1610612751,31.0,85.0,3.0,10.0,17.0,26.0,12.0,35.0,47.0,24.0,9.0,8.0,12.0,31.0,82.0,240.000000,21.0,13.0,9.0,42.0,8.0,83.457417,86.645424,-3.170028,0.186321,1.655972,19.164549,0.044377,0.128634,0.084390,9.645229,0.334428,0.403052,0.190604,98.798017,98.798017,59.042292,0.112319,0.383964,0.309240,0.149999,0.421320,0.418921,0.191348,0.243931,0.000000,0.892640,0.107360,0.589287,0.177226,0.068950,0.074612,0.329879,0.171267,0.412061,0.623859,0.250308,0.227153,0.000000,0.623859,0.250308,0.129859,0.680444,0.195359,0.199699,0.140674,0.162797,0.207021,0.210566,0.241208,0.196126,0.197293,0.200915,0.151191,0.198521,0.187091,0.206165,0.210120,0.000000,0.192918,-2.137222,CLE @ NJN,2000-01,2000-10-31
3,20000002,1610612751,31,85,3,10,17,26,12,35,47,24,9,8,12,31,82,240.000000,21,13,9,42,8,83.457417,86.645424,-3.170028,0.186321,1.655972,19.164549,0.044377,0.128634,0.084390,9.645229,0.334428,0.403052,0.190604,98.798017,98.798017,59.042292,0.112319,0.383964,0.309240,0.149999,0.421320,0.418921,0.191348,0.243931,0.000000,0.892640,0.107360,0.589287,0.177226,0.068950,0.074612,0.329879,0.171267,0.412061,0.623859,0.250308,0.227153,0.000000,0.623859,0.250308,0.129859,0.680444,0.195359,0.199699,0.140674,0.162797,0.207021,0.210566,0.241208,0.196126,0.197293,0.200915,0.151191,0.198521,0.187091,0.206165,0.210120,0.000000,0.192918,-2.137222,1610612739,32.0,78.0,2.0,7.0,20.0,32.0,11.0,41.0,52.0,16.0,5.0,8.0,19.0,27.0,86.0,240.000000,12.0,12.0,14.0,36.0,8.0,87.118465,82.284514,4.836236,0.135260,0.953071,12.727431,0.043157,0.154742,0.099091,13.891264,0.403829,0.477510,0.197340,99.597600,99.597600,55.404514,0.027378,0.423046,0.418163,0.189245,0.385467,0.306368,0.150790,0.226623,0.000000,0.905348,0.071110,0.619452,0.225391,0.042091,0.151227,0.250680,0.134511,0.394061,0.380781,0.531441,0.226319,0.000000,0.404284,0.507939,0.179271,0.558568,0.200988,0.201629,0.113160,0.180712,0.189883,0.188048,0.223730,0.215432,0.215471,0.206409,0.202678,0.200235,0.161342,0.223420,0.197098,0.000000,0.194632,4.139722,NJN vs. CLE,2000-01,2000-10-31
4,20000003,1610612753,34,79,6,16,23,33,8,29,37,20,10,9,15,24,97,240.000000,28,9,19,32,1,98.736875,86.636882,12.099993,0.142503,0.857986,12.904542,0.031709,0.133742,0.081268,11.997660,0.475912,0.520254,0.200260,98.899090,98.899090,61.198889,0.118825,0.472056,0.423020,0.148499,0.486995,0.336534,0.267238,0.238280,0.000000,0.799790,0.200210,0.571690,0.237194,0.199434,0.245441,0.229067,0.346846,0.334358,0.459721,0.398473,0.403889,0.000000,0.606531,0.371316,0.186988,0.685047,0.200331,0.201844,0.229832,0.189043,0.227233,0.227924,0.167742,0.196079,0.201831,0.197763,0.182205,0.192654,0.169992,0.065000,0.193451,0.000000,0.204198,7.283056,1610612764,33.0,72.0,4.0,7.0,16.0,24.0,9.0,35.0,44.0,20.0,6.0,1.0,26.0,28.0,86.0,240.000000,15.0,12.0,14.0,42.0,9.0,87.675576,98.295687,-10.619472,0.149045,0.627285,14.817028,0.042904,0.148099,0.098173,19.670639,0.520195,0.553401,0.194765,98.401342,98.401342,53.393403,0.101201,0.485589,0.342879,0.267129,0.470513,0.418830,0.148780,0.185661,0.000000,0.916404,0.083596,0.632414,0.206632,0.148603,0.156626,0.189113,0.165165,0.425926,0.502342,0.467588,0.432986,0.000000,0.600256,0.369674,0.276597,0.604405,0.194938,0.201348,0.157969,0.160486,0.177851,0.170195,0.210115,0.209455,0.210824,0.194940,0.196138,0.138369,0.109583,0.186508,0.215050,0.000000,0.198386,-6.894514,ORL vs. WAS,2000-01,2000-10-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66390,52400131,1610612758,41,89,13,33,11,15,15,29,44,23,6,4,18,19,106,240.000000,15,13,15,40,8,110.123410,123.832694,-13.692986,0.144001,0.915579,16.246007,0.061248,0.139456,0.094800,13.410542,0.553654,0.568678,0.196805,96.900852,96.900852,64.197361,0.078930,0.533497,0.168455,0.181755,0.589886,0.321300,0.106123,0.242713,1.925417,0.579009,0.412449,0.498701,0.103705,0.374451,0.147024,0.093555,0.120819,0.394996,0.601385,0.356601,0.625625,0.137917,0.614244,0.352284,0.337209,0.444622,0.198443,0.199547,0.199186,0.197010,0.199987,0.198947,0.220836,0.204731,0.202397,0.198671,0.194704,0.193650,0.140420,0.176580,0.204741,0.201187,0.198282,-14.351250,1610612742,41.0,83.0,14.0,28.0,24.0,26.0,10.0,31.0,41.0,29.0,9.0,8.0,9.0,15.0,120.0,240.000000,18.0,4.0,14.0,40.0,4.0,123.867549,110.768076,13.093542,0.179320,1.234705,23.328986,0.043102,0.126057,0.088669,7.650514,0.614891,0.653447,0.190092,96.700401,96.700401,52.394028,0.120096,0.586034,0.319399,0.106316,0.531757,0.167544,0.181331,0.320657,2.229653,0.660342,0.331116,0.484243,0.140879,0.266205,0.119458,0.173500,0.127531,0.343317,0.539994,0.384173,0.710417,0.000000,0.693429,0.230738,0.371341,0.690868,0.189465,0.197248,0.188922,0.192500,0.200256,0.200080,0.177569,0.202057,0.201182,0.211608,0.180998,0.195077,0.211063,0.166207,0.202276,0.192422,0.188871,13.047708,SAC vs. DAL,2024-25,2025-04-16
66391,52400201,1610612737,44,102,16,47,10,12,11,33,44,30,12,3,9,18,114,265.016667,21,14,22,56,8,108.972216,113.769398,-4.786328,0.170940,1.701450,19.786856,0.038220,0.132929,0.082033,6.828665,0.533646,0.548288,0.194796,96.542768,96.542768,70.793032,0.094415,0.515043,0.115509,0.094355,0.582867,0.189826,0.139047,0.283225,2.338658,0.528556,0.471444,0.478198,0.000000,0.421953,0.212341,0.069536,0.130952,0.478198,0.664189,0.249212,0.692064,0.218571,0.717321,0.252367,0.401740,0.302049,0.201907,0.198260,0.191661,0.199505,0.163951,0.180012,0.223868,0.200502,0.200689,0.193867,0.160034,0.206388,0.145900,0.193684,0.193772,0.193633,0.199234,-6.091126,1610612748,48.0,96.0,16.0,42.0,11.0,18.0,13.0,41.0,54.0,33.0,4.0,8.0,14.0,15.0,123.0,265.000000,18.0,17.0,14.0,48.0,3.0,114.115346,109.194151,4.941660,0.175512,1.914025,21.394906,0.052826,0.136744,0.098506,8.743547,0.602740,0.610614,0.188164,96.271151,96.271151,74.389497,0.108900,0.582882,0.188123,0.140615,0.511179,0.117131,0.094058,0.210104,2.789245,0.569122,0.430878,0.531708,0.131616,0.389409,0.104841,0.078883,0.158831,0.400093,0.679972,0.320028,0.594560,0.156132,0.689231,0.310769,0.317894,0.399580,0.200367,0.200068,0.199439,0.200160,0.203244,0.198173,0.193693,0.197318,0.198007,0.203462,0.175619,0.211259,0.195655,0.227722,0.201947,0.191826,0.199943,7.759057,ATL vs. MIA,2024-25,2025-04-18
66392,52400201,1610612748,48,96,16,42,11,18,13,41,54,33,4,8,14,15,123,265.000000,18,17,14,48,3,114.115346,109.194151,4.941660,0.175512,1.914025,21.394906,0.052826,0.136744,0.098506,8.743547,0.602740,0.610614,0.188164,96.271151,96.271151,74.389497,0.108900,0.582882,0.188123,0.140615,0.511179,0.117131,0.094058,0.210104,2.789245,0.569122,0.430878,0.531708,0.131616,0.389409,0.104841,0.078883,0.158831,0.400093,0.679972,0.320028,0.594560,0.156132,0.689231,0.310769,0.317894,0.399580,0.200367,0.200068,0.199439,0.200160,0.203244,0.198173,0.193693,0.197318,0.198007,0.203462,0.175619,0.211259,0.195655,0.227722,0.201947,0.191826,0.199943,7.759057,1610612737,44.0,102.0,16.0,47.0,10.0,12.0,11.0,33.0,44.0,30.0,12.0,3.0,9.0,18.0,114.0,265.016667,21.0,14.0,22.0,56.0,8.0,108.972216,113.769398,-4.786328,0.170940,1.701450,19.786856,0.038220,0.132929,0.082033,6.828665,0.533646,0.548288,0.194796,96.542768,96.542768,70.793032,0.094415,0.515043,0.115509,0.094355,0.582867,0.189826,0.139047,0.283225,2.338658,0.528556,0.471444,0.478198,0.000000,0.421953,0.212341,0.069536,0.130952,0.478198,0.664189,0.249212,0.692064,0.218571,0.717321,0.252367,0.401740,0.302049,0.201907,0.198260,0.191661,0.199505,0.163951,0.180012,0.223868,0.200502,0.200689,0.193867,0.160034,0.206388,0.145900,0.193684,0.193772,0.193633,0.199234,-6.091126,MIA @ ATL,2024-25,2025-04-18
66393,52400211,1610612742,41,87,12,38,12,16,7,29,36,25,9,8,16,17,106,239.983333,14,15,15,44,4,103.971838,117.104361,-13.146712,0.159645,1.043291,21.438058,0.028121,0.109295,0.071448,14.196291,0.505059,0.518344,0.194360,102.200355,102.200355,55.776790,0.083048,0.540618,0.184078,0.155320,0.534614,0.150467,0.117294,0.351484,1.775957,0.589597,0.410403,0.375406,0.089519,0.288293,0.120119,0.077834,0.102521,0.286029,0.431148,0.256678,0.465397,0.199927,0.498200,0.243395,0.324056,0.404056,0.199455,0.198674,0.234511,0.197563,0.188766,0.193288,0.179929,0.199788,0.199410,0.199269,0.194797,0.201698,0.189836,0.148746,0.180069,0.178183,0.199691,-8.414820,1610612763,47.0,100.0,13.0,31.0,13.0,15.0,16.0,34.0,50.0,30.0,8.0,4.0,10.0,17.0,120.0,240.000000,24.0,15.0,19.0,60.0,8.0,118.571125,105.071556,13.509528,0.154672,0.823437,19.079396,0.059757,0.149789,0.100197,4.889924,0.566430,0.582027,0.191697,101.299056,101.299056,62.138194,0.109814,0.532094,0.153846,0.116233,0.542366,0.187143,0.155200,0.164587,2.136944,0.650762,0.334099,0.569661,0.056488,0.328575,0.226652,0.078919,0.205619,0.513310,0.620063,0.349659,0.682240,0.087343,0.648875,0.320847,0.348328,0.327988,0.197052,0.199753,0.185188,0.203577,0.155673,0.161807,0.197832,0.203155,0.201390,0.197460,0.149565,0.187630,0.217161,0.174559,0.196685,0.173665,0.201920,11.408611,DAL @ MEM,2024-25,2025-04-18
66394,52400211,1610612763,47,100,13,31,13,15,16,34,50,30,8,4,10,17,120,240.000000,24,15,19,60,8,118.571125,105.071556,13.509528,0.154672,0.823437,19.079396,0.059757,0.149789,0.100197,4.889924,0.566430,0.582027,0.191697,101.299056,101.299056,62.138194,0.109814,0.532094,0.153846,0.116233,0.542366,0.187143,0.155200,0.164587,2.136944,0.650762,0.334099,0.569661,0.056488,0.328575,0.226652,0.078919,0.205619,0.513310,0.620063,0.349659,0.682240,0.087343,0.648875,0.320847,0.348328,0.327988,0.197052,0.199753,0.185188,0.203577,0.155673,0.161807,0.197832,0.203155,0.201390,0.197460,0.149565,0.187630,0.217161,0.174559,0.196685,0.173665,0.201920,11.408611,1610612742,41.0,87.0,12.0,38.0,12.0,16.0,7.0,29.0,36.0,25.0,9.0,8.0,16.0,17.0,106.0,239.983333,14.0,15.0,15.0,44.0,4.0,103.971838,117.104361,-13.146712,0.159645,1.043291,21.438058,0.028121,0.109295,0.071448,14.196291,0.505059,0.518344,0.194360,102.200355,102.200355,55.776790,0.083048,0.540618,0.184078,0.155320,0.534614,0.150467,0.117294,0.351484,1.775957,0.589597,0.410403,0.375406,0.089519,0.288293,0.120119,0.077834,0.102521,0.286029,0.431148,0.256678,0.465397,0.199927,0.498200,0.243395,0.324056,0.404056,0.199455,0.198674,0.234511,0.197563,0.188766,0.193288,0.179929,0.199788,0.199410,0.199269,0.194797,0.201698,0.189836,0.148746,0.180069,0.178183,0.199691,-8.414820,MEM vs. DAL,2024-25,2025-04-18

In [33]:

#display lines with nan values on matchup
print("Lines with NaN in MATCHUP:")
display(match_dataset[match_dataset['MATCHUP'].isna()])

Lines with NaN in MATCHUP:

Empty DataFrame
Columns: [GAME_ID, TEAM_ID, fieldGoalsMade_traditional, fieldGoalsAttempted_traditional, threePointersMade_traditional, threePointersAttempted_traditional, freeThrowsMade_traditional, freeThrowsAttempted_traditional, reboundsOffensive_traditional, reboundsDefensive_traditional, reboundsTotal_traditional, assists_traditional, steals_traditional, blocks_traditional, turnovers_traditional, foulsPersonal_traditional, points_traditional, MINUTES_PLAYED, pointsOffTurnovers_misc, pointsSecondChance_misc, pointsFastBreak_misc, pointsPaint_misc, blocksAgainst_misc, offensiveRating_advanced, defensiveRating_advanced, netRating_advanced, assistPercentage_advanced, assistToTurnover_advanced, assistRatio_advanced, offensiveReboundPercentage_advanced, defensiveReboundPercentage_advanced, reboundPercentage_advanced, turnoverRatio_advanced, effectiveFieldGoalPercentage_advanced, trueShootingPercentage_advanced, usagePercentage_advanced, estimatedPace_advanced, pace_advanced, possessions_advanced, PIE_advanced, effectiveFieldGoalPercentage_fourfactors, freeThrowAttemptRate_fourfactors, teamTurnoverPercentage_fourfactors, oppEffectiveFieldGoalPercentage_fourfactors, oppFreeThrowAttemptRate_fourfactors, oppTeamTurnoverPercentage_fourfactors, oppOffensiveReboundPercentage_fourfactors, foulsDrawn_misc, percentageFieldGoalsAttempted2pt_scoring, percentageFieldGoalsAttempted3pt_scoring, percentagePoints2pt_scoring, percentagePointsMidrange2pt_scoring, percentagePoints3pt_scoring, percentagePointsFastBreak_scoring, percentagePointsFreeThrow_scoring, percentagePointsOffTurnovers_scoring, percentagePointsPaint_scoring, percentageAssisted2pt_scoring, percentageUnassisted2pt_scoring, percentageAssisted3pt_scoring, percentageUnassisted3pt_scoring, percentageAssistedFGM_scoring, percentageUnassistedFGM_scoring, threePointersPercentage_traditional, freeThrowsPercentage_traditional, percentageFieldGoalsMade_usage, percentageFieldGoalsAttempted_usage, percentageThreePointersMade_usage, percentageThreePointersAttempted_usage, percentageFreeThrowsMade_usage, percentageFreeThrowsAttempted_usage, percentageReboundsOffensive_usage, percentageReboundsDefensive_usage, percentageReboundsTotal_usage, percentageAssists_usage, percentageTurnovers_usage, percentageSteals_usage, percentageBlocks_usage, percentageBlocksAllowed_usage, percentagePersonalFouls_usage, percentagePersonalFoulsDrawn_usage, percentagePoints_usage, plusMinusPoints_traditional, OPP_TEAM_ID, OPP_fieldGoalsMade_traditional, OPP_fieldGoalsAttempted_traditional, OPP_threePointersMade_traditional, OPP_threePointersAttempted_traditional, OPP_freeThrowsMade_traditional, OPP_freeThrowsAttempted_traditional, OPP_reboundsOffensive_traditional, OPP_reboundsDefensive_traditional, OPP_reboundsTotal_traditional, OPP_assists_traditional, OPP_steals_traditional, OPP_blocks_traditional, OPP_turnovers_traditional, OPP_foulsPersonal_traditional, OPP_points_traditional, OPP_MINUTES_PLAYED, ...]
Index: []

In [34]:
# Définir si l'équipe joue à domicile
match_dataset['IS_HOME'] = match_dataset['MATCHUP'].str.contains('vs', na=False).astype(int)

# Calcul du résultat (win) et écart de points
match_dataset['IS_WIN'] = (match_dataset['points_traditional'] > match_dataset['OPP_points_traditional']).astype(int)
match_dataset['POINT_DIFF'] = match_dataset['points_traditional'] - match_dataset['OPP_points_traditional']

#

In [35]:
match_dataset

,GAME_ID,TEAM_ID,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,points_traditional,MINUTES_PLAYED,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,blocksAgainst_misc,offensiveRating_advanced,defensiveRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,threePointersPercentage_traditional,freeThrowsPercentage_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage,plusMinusPoints_traditional,OPP_TEAM_ID,OPP_fieldGoalsMade_traditional,OPP_fieldGoalsAttempted_traditional,OPP_threePointersMade_traditional,OPP_threePointersAttempted_traditional,OPP_freeThrowsMade_traditional,OPP_freeThrowsAttempted_traditional,OPP_reboundsOffensive_traditional,OPP_reboundsDefensive_traditional,OPP_reboundsTotal_traditional,OPP_assists_traditional,OPP_steals_traditional,OPP_blocks_traditional,OPP_turnovers_traditional,OPP_foulsPersonal_traditional,OPP_points_traditional,OPP_MINUTES_PLAYED,OPP_pointsOffTurnovers_misc,OPP_pointsSecondChance_misc,OPP_pointsFastBreak_misc,OPP_pointsPaint_misc,OPP_blocksAgainst_misc,OPP_offensiveRating_advanced,OPP_defensiveRating_advanced,OPP_netRating_advanced,OPP_assistPercentage_advanced,OPP_assistToTurnover_advanced,OPP_assistRatio_advanced,OPP_offensiveReboundPercentage_advanced,OPP_defensiveReboundPercentage_advanced,OPP_reboundPercentage_advanced,OPP_turnoverRatio_advanced,OPP_effectiveFieldGoalPercentage_advanced,OPP_trueShootingPercentage_advanced,OPP_usagePercentage_advanced,OPP_estimatedPace_advanced,OPP_pace_advanced,OPP_possessions_advanced,OPP_PIE_advanced,OPP_effectiveFieldGoalPercentage_fourfactors,OPP_freeThrowAttemptRate_fourfactors,OPP_teamTurnoverPercentage_fourfactors,OPP_oppEffectiveFieldGoalPercentage_fourfactors,OPP_oppFreeThrowAttemptRate_fourfactors,OPP_oppTeamTurnoverPercentage_fourfactors,OPP_oppOffensiveReboundPercentage_fourfactors,OPP_foulsDrawn_misc,OPP_percentageFieldGoalsAttempted2pt_scoring,OPP_percentageFieldGoalsAttempted3pt_scoring,OPP_percentagePoints2pt_scoring,OPP_percentagePointsMidrange2pt_scoring,OPP_percentagePoints3pt_scoring,OPP_percentagePointsFastBreak_scoring,OPP_percentagePointsFreeThrow_scoring,OPP_percentagePointsOffTurnovers_scoring,OPP_percentagePointsPaint_scoring,OPP_percentageAssisted2pt_scoring,OPP_percentageUnassisted2pt_scoring,OPP_percentageAssisted3pt_scoring,OPP_percentageUnassisted3pt_scoring,OPP_percentageAssistedFGM_scoring,OPP_percentageUnassistedFGM_scoring,OPP_threePointersPercentage_traditional,OPP_freeThrowsPercentage_traditional,OPP_percentageFieldGoalsMade_usage,OPP_percentageFieldGoalsAttempted_usage,OPP_percentageThreePointersMade_usage,OPP_percentageThreePointersAttempted_usage,OPP_percentageFreeThrowsMade_usage,OPP_percentageFreeThrowsAttempted_usage,OPP_percentageReboundsOffensive_usage,OPP_percentageReboundsDefensive_usage,OPP_percentageReboundsTotal_usage,OPP_percentageAssists_usage,OPP_percentageTurnovers_usage,OPP_percentageSteals_usage,OPP_percentageBlocks_usage,OPP_percentageBlocksAllowed_usage,OPP_percentagePersonalFouls_usage,OPP_percentagePersonalFoulsDrawn_usage,OPP_percentagePoints_usage,OPP_plusMinusPoints_traditional,MATCHUP,SEASON,GAME_DATE,IS_HOME,IS_WIN,POINT_DIFF
0,20000001,1610612752,25,70,3,11,19,24,14,23,37,14,6,4,22,30,72,240.000000,12,15,4,22,5,80.922299,114.464688,-33.537868,0.163246,0.523610,11.026556,0.056220,0.147483,0.091563,19.763500,0.372955,0.436562,0.193970,88.699676,88.699676,43.962361,0.039403,0.377483,0.365924,0.247518,0.598126,0.458272,0.160368,0.266661,0.000000,0.857836,0.142164,0.650577,0.241035,0.057733,0.039143,0.257106,0.165235,0.409507,0.518244,0.447172,0.197778,0.000000,0.559933,0.405484,0.108844,0.466333,0.213520,0.203724,0.197778,0.193515,0.199331,0.190465,0.232461,0.204200,0.204153,0.200857,0.197202,0.196856,0.199583,0.160243,0.192422,0.000000,0.201207,-14.930903,1610612755,38.0,66.0,3.0,8.0,22.0,30.0,8.0,29.0,37.0,27.0,10.0,5.0,13.0,24.0,101.0,240.000000,26.0,9.0,10.0,36.0,4.0,113.678208,80.924167,32.729556,0.182441,1.177822,20.832340,0.049657,0.117050,0.092804,12.917368,0.562437,0.596134,0.194474,88.899378,88.899378,50.502014,0.160855,0.601599,0.469504,0.161353,0.382886,0.361238,0.246772,0.319077,0.000000,0.839428,0.116266,0.644489,0.293966,0.049281,0.125861,0.169078,0.233654,0.350402,0.615402,0.247446,0.168090,0.078368,0.629851,0.232997,0.168090,0.508698,0.203276,0.200388,0.194265,0.173397,0.203479,0.208561,0.163576,0.192186,0.195743,0.196602,0.176540,0.217619,0.134035,0.178715,0.194042,0.000000,0.208010,18.242986,NYK vs. PHI,2000-01,2000-10-31,1,0,-29.0
1,20000001,1610612755,38,66,3,8,22,30,8,29,37,27,10,5,13,24,101,240.000000,26,9,10,36,4,113.678208,80.924167,32.729556,0.182441,1.177822,20.832340,0.049657,0.117050,0.092804,12.917368,0.562437,0.596134,0.194474,88.899378,88.899378,50.502014,0.160855,0.601599,0.469504,0.161353,0.382886,0.361238,0.246772,0.319077,0.000000,0.839428,0.116266,0.644489,0.293966,0.049281,0.125861,0.169078,0.233654,0.350402,0.615402,0.247446,0.168090,0.078368,0.629851,0.232997,0.168090,0.508698,0.203276,0.200388,0.194265,0.173397,0.203479,0.208561,0.163576,0.192186,0.195743,0.196602,0.176540,0.217619,0.134035,0.178715,0.194042,0.000000,0.208010,18.242986,1610612752,25.0,70.0,3.0,11.0,19.0,24.0,14.0,23.0,37.0,14.0,6.0,4.0,22.0,30.0,72.0,240.000000,12.0,15.0,4.0,22.0,5.0,80.922299,114.464688,-33.537868,0.163246,0.523610,11.026556,0.056220,0.147483,0.091563,19.763500,0.372955,0.436562,0.193970,88.699676,88.699676,43.962361,0.039403,0.377483,0.365924,0.247518,0.598126,0.458272,0.160368,0.266661,0.000000,0.857836,0.142164,0.650577,0.241035,0.057733,0.039143,0.257106,0.165235,0.409507,0.518244,0.447172,0.197778,0.000000,0.559933,0.405484,0.108844,0.466333,0.213520,0.203724,0.197778,0.193515,0.199331,0.190465,0.232461,0.204200,0.204153,0.200857,0.197202,0.196856,0.199583,0.160243,0.192422,0.000000,0.201207,-14.930903,PHI @ NYK,2000-01,2000-10-31,0,1,29.0
2,20000002,1610612739,32,78,2,7,20,32,11,41,52,16,5,8,19,27,86,240.000000,12,12,14,36,8,87.118465,82.284514,4.836236,0.135260,0.953071,12.727431,0.043157,0.154742,0.099091,13.891264,0.403829,0.477510,0.197340,99.597600,99.597600,55.404514,0.027378,0.423046,0.418163,0.189245,0.385467,0.306368,0.150790,0.226623,0.000000,0.905348,0.071110,0.619452,0.225391,0.042091,0.151227,0.250680,0.134511,0.394061,0.380781,0.531441,0.226319,0.000000,0.404284,0.507939,0.179271,0.558568,0.200988,0.201629,0.113160,0.180712,0.189883,0.188048,0.223730,0.215432,0.215471,0.206409,0.202678,0.200235,0.161342,0.223420,0.197098,0.000000,0.194632,4.139722,1610612751,31.0,85.0,3.0,10.0,17.0,26.0,12.0,35.0,47.0,24.0,9.0,8.0,12.0,31.0,82.0,240.000000,21.0,13.0,9.0,42.0,8.0,83.457417,86.645424,-3.170028,0.186321,1.655972,19.164549,0.044377,0.128634,0.084390,9.645229,0.334428,0.403052,0.190604,98.798017,98.798017,59.042292,0.112319,0.383964,0.309240,0.149999,0.421320,0.418921,0.191348,0.243931,0.000000,0.892640,0.107360,0.589287,0.177226,0.068950,0.074612,0.329879,0.171267,0.412061,0.623859,0.250308,0.227153,0.000000,0.623859,0.250308,0.129859,0.680444,0.195359,0.199699,0.140674,0.162797,0.207021,0.210566,0.241208,0.196126,0.197293,0.200915,0.151191,0.198521,0.187091,0.206165,0.210120,0.000000,0.192918,-2.137222,CLE @ NJN,2000-01,2000-10-31,0,1,4.0
3,20000002,1610612751,31,85,3,10,17,26,12,35,47,24,9,8,12,31,82,240.000000,21,13,9,42,8,83.457417,86.645424,-3.170028,0.186321,1.655972,19.164549,0.044377,0.128634,0.084390,9.645229,0.334428,0.403052,0.190604,98.798017,98.798017,59.042292,0.112319,0.383964,0.309240,0.149999,0.421320,0.418921,0.191348,0.243931,0.000000,0.892640,0.107360,0.589287,0.177226,0.068950,0.074612,0.329879,0.171267,0.412061,0.623859,0.250308,0.227153,0.000000,0.623859,0.250308,0.129859,0.680444,0.195359,0.199699,0.140674,0.162797,0.207021,0.210566,0.241208,0.196126,0.197293,0.200915,0.151191,0.198521,0.187091,0.206165,0.210120,0.000000,0.192918,-2.137222,1610612739,32.0,78.0,2.0,7.0,20.0,32.0,11.0,41.0,52.0,16.0,5.0,8.0,19.0,27.0,86.0,240.000000,12.0,12.0,14.0,36.0,8.0,87.118465,82.284514,4.836236,0.135260,0.953071,12.727431,0.043157,0.154742,0.099091,13.891264,0.403829,0.477510,0.197340,99.597600,99.597600,55.404514,0.027378,0.423046,0.418163,0.189245,0.385467,0.306368,0.150790,0.226623,0.000000,0.905348,0.071110,0.619452,0.225391,0.042091,0.151227,0.250680,0.134511,0.394061,0.380781,0.531441,0.226319,0.000000,0.404284,0.507939,0.179271,0.558568,0.200988,0.201629,0.113160,0.180712,0.189883,0.188048,0.223730,0.215432,0.215471,0.206409,0.202678,0.200235,0.161342,0.223420,0.197098,0.000000,0.194632,4.139722,NJN vs. CLE,2000-01,2000-10-31,1,0,-4.0
4,20000003,1610612753,34,79,6,16,23,33,8,29,37,20,10,9,15,24,97,240.000000,28,9,19,32,1,98.736875,86.636882,12.099993,0.142503,0.857986,12.904542,0.031709,0.133742,0.081268,11.997660,0.475912,0.520254,0.200260,98.899090,98.899090,61.198889,0.118825,0.472056,0.423020,0.148499,0.486995,0.336534,0.267238,0.238280,0.000000,0.799790,0.200210,0.571690,0.237194,0.199434,0.245441,0.229067,0.346846,0.334358,0.459721,0.398473,0.403889,0.000000,0.606531,0.371316,0.186988,0.685047,0.200331,0.201844,0.229832,0.189043,0.227233,0.227924,0.167742,0.196079,0.201831,0.197763,0.182205,0.192654,0.169992,0.065000,0.193451,0.000000,0.204198,7.283056,1610612764,33.0,72.0,4.0,7.0,16.0,24.0,9.0,35.0,44.0,20.0,6.0,1.0,26.0,28.0,86.0,240.000000,15.0,12.0,14.0,42.0,9.0,87.675576,98.295687,-10.619472,0.149045,0.627285,14.817028,0.042904,0.148099,0.098173,19.670639,0.520195,0.553401,0.194765,98.401342,98.401342,53.393403,0.101201,0.485589,0.342879,0.267129,0.470513,0.418830,0.148780,0.185661,0.000000,0.916404,0.083596,0.632414,0.206632,0.148603,0.156626,0.189113,0.165165,0.425926,0.502342,0.467588,0.432986,0.000000,0.600256,0.369674,0.276597,0.604405,0.194938,0.201348,0.157969,0.160486,0.177851,0.170195,0.210115,0.209455,0.210824,0.194940,0.196138,0.138369,0.109583,0.186508,0.215050,0.000000,0.198386,-6.894514,ORL vs. WAS,2000-01,2000-10-31,1,1,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66390,52400131,1610612758,41,89,13,33,11,15,15,29,44,23,6,4,18,19,106,240.000000,15,13,15,40,8,110.123410,123.832694,-13.692986,0.144001,0.915579,16.246007,0.061248,0.139456,0.094800,13.410542,0.553654,0.568678,0.196805,96.900852,96.900852,64.197361,0.078930,0.533497,0.168455,0.181755,0.589886,0.321300,0.106123,0.242713,1.925417,0.579009,0.412449,0.498701,0.103705,0.374451,0.147024,0.093555,0.120819,0.394996,0.601385,0.356601,0.625625,0.137917,0.614244,0.352284,0.337209,0.444622,0.198443,0.199547,0.199186,0.197010,0.199987,0.198947,0.220836,0.204731,0.202397,0.198671,0.194704,0.193650,0.140420,0.176580,0.204741,0.201187,0.198282,-14.351250,1610612742,41.0,83.0,14.0,28.0,24.0,26.0,10.0,31.0,41.0,29.0,9.0,8.0,9.0,15.0,120.0,240.000000,18.0,4.0,14.0,40.0,4.0,123.867549,110.768076,13.093542,0.179320,1.234705,23.328986,0.043102,0.126057,0.088669,7.650514,0.614891,0.653447,0.190092,96.700401,96.700401,52.394028,0.120096,0.586034,0.319399,0.106316,0.531757,0.167544,0.181331,0.320657,2.229653,0.660342,0.331116,0.484243,0.140879,0.266205,0.119458,0.173500,0.127531,0.343317,0.539994,0.384173,0.710417,0.000000,0.693429,0.230738,0.371341,0.690868,0.189465,0.197248,0.188922,0.192500,0.200256,0.200080,0.177569,0.202057,0.201182,0.211608,0.180998,0.195077,0.211063,0.166207,0.202276,0.192422,0.188871,13.047708,SAC vs. DAL,2024-25,2025-04-16,1,0,-14.0
66391,52400201,1610612737,44,102,16,47,10,12,11,33,44,30,12,3,9,18,114,265.016667,21,14,22,56,8,108.972216,113.769398,-4.786328,0.170940,1.701450,19.786856,0.038220,0.132929,0.082033,6.828665,0.533646,0.548288,0.194796,96.542768,96.542768,70.793032,0.094415,0.515043,0.115509,0.094355,0.582867,0.189826,0.139047,0.283225,2.338658,0.528556,0.471444,0.478198,0.000000,0.421953,0.212341,0.069536,0.130952,0.478198,0.664189,0.249212,0.692064,0.218571,0.717321,0.252367,0.401740,0.302049,0.201907,0.198260,0.191661,0.199505,0.163951,0.180012,0.223868,0.200502,0.200689,0.193867,0.160034,0.206388,0.145900,0.193684,0.193772,0.193633,0.199234,-6.091126,1610612748,48.0,96.0,16.0,42.0,11.0,18.0,13.0,41.0,54.0,33.0,4.0,8.0,14.0,15.0,123.0,265.000000,18.0,17.0,14.0,48.0,3.0,114.115346,109.194151,4.941660,0.175512,1.914025,21.394906,0.052826,0.136744,0.098506,8.743547,0.602740,0.610614,0.188164,96.271151,96.271151,74.389497,0.108900,0.582882,0.188123,0.140615,0.511179,0.117131,0.094058,0.210104,2.789245,0.569122,0.430878,0.531708,0.131616,0.389409,0.104841,0.078883,0.158831,0.400093,0.679972,0.320028,0.594560,0.156132,0.689231,0.310769,0.317894,0.399580,0.200367,0.200068,0.199439,0.200160,0.203244,0.198173,0.193693,0.197318,0.198007,0.203462,0.175619,0.211259,0.195655,0.227722,0.201947,0.191826,0.199943,7.759057,ATL vs. MIA,2024-25,2025-04-18,1,0,-9.0
66392,52400201,1610612748,48,96,16,42,11,18,13,41,54,33,4,8,14,15,123,265.000000,18,17,14,48,3,114.115346,109.194151,4.941660,0.175512,1.914025,21.394906,0.052826,0.136744,0.098506,8.743547,0.602740,0.610614,0.188164,96.271151,96.271151,74.389497,0.108900,0.582882,0.188123,0.140615,0.511179,0.117131,0.094058,0.210104,2.789245,0.569122,0.430878,0.531708,0.131616,0.389409,0.104841,0.078883,0.158831,0.400093,0.679972,0.320028,0.594560,0.156132,0.689231,0.310769,0.317894,0.399580,0.200367,0.200068,0.199439,0.200160,0.203244,0.198173,0.193693,0.197318,0.198007,0.203462,0.175619,0.211259,0.195655,0.227722,0.201947,0.191826,0.199943,7.759057,1610612737,44.0,102.0,16.0,47.0,10.0,12.0,11.0,33.0,44.0,30.0,12.0,3.0,9.0,18.0,114.0,265.016667,21.0,14.0,22.0,56.0,8.0,108.972216,113.769398,-4.786328,0.170940,1.701450,19.786856,0.038220,0.132929,0.082033,6.828665,0.533646,0.548288,0.194796,96.542768,96.542768,70.793032,0.094415,0.515043,0.115509,0.094355,0.582867,0.189826,0.139047,0.283225,2.338658,0.528556,0.471444,0.478198,0.000000,0.421953,0.212341,0.069536,0.130952,0.478198,0.664189,0.249212,0.692064,0.218571,0.717321,0.252367,0.401740,0.302049,0.201907,0.198260,0.191661,0.199505,0.163951,0.180012,0.223868,0.200502,0.200689,0.193867,0.160034,0.206388,0.145900,0.193684,0.193772,0.193633,0.199234,-6.091126,MIA @ ATL,2024-25,2025-04-18,0,1,9.0
66393,52400211,1610612742,41,87,12,38,12,16,7,29,36,25,9,8,16,17,106,239.983333,14,15,15,44,4,103.971838,117.104361,-13.146712,0.159645,1.043291,21.438058,0.028121,0.109295,0.071448,14.196291,0.505059,0.518344,0.194360,102.200355,102.200355,55.776790,0.083048,0.540618,0.184078,0.155320,0.534614,0.150467,0.117294,0.351484,1.775957,0.589597,0.410403,0.375406,0.089519,0.288293,0.120119,0.077834,0.102521,0.286029,0.431148,0.256678,0.465397,0.199927,0.498200,0.243395,0.324056,0.404056,0.199455,0.198674,0.234511,0.197563,0.188766,0.193288,0.179929,0.199788,0.199410,0.199269,0.194797,0.201698,0.189836,0.148746,0.180069,0.178183,0.199691,-8.414820,1610612763,47.0,100.0,13.0,31.0,13.0,15.0,16.0,34.0,50.0,30.0,8.0,4.0,10.0,17.0,120.0,240.000000,24.0,15.0,19.0,60.0,8.0,118.571125,105.071556,13.509528,0.154672,0.823437,19.079396,0.059757,0.149789,0.100197,4.889924,0.566430,0.582027,0.191697,101.299056,101.299056,62.138194,0.109814,0.532094,0.153846,0.116233,0.542366,0.187143,0.155200,0.164587,2.136944,0.650762,0.334099,0.569661,0.056488,0.328575,0.226652,0.078919,0.205619,0.513310,0.620063,0.349659,0.682240,0.087343,0.648875,0.320847,0.348328,0.327988,0.197052,0.199753,0.185188,0.203577,0.155673,0.161807,0.197832,0.203155,0.201390,0.197460,0.149565,0.187630,0.217161,0.174559,0.196685,0.173665,0.201920,11.408611,DAL @ MEM,2024-25,2025-04-18,0,0,-14.0
66394,52400211,1610612763,47,100,13,31,13,15,16,34,50,30,8,4,10,17,120,240.000000,24,15,19,60,8,118.571125,105.071556,13.509528,0.154672,0.823437,19.079396,0.059757,0.149789,0.100197,4.889924,0.566430,0.582027,0.191697,101.299056,101.299056,62.138194,0.109814,0.532094,0.153846,0.116233,0.542366,0.187143,0.155200,0.164587,2.136944,0.650762,0.334099,0.569661,0.056488,0.328575,0.226652,0.078919,0.205619,0.513310,0.620063,0.349659,0.682240,0.087343,0.648875,0.320847,0.348328,0.327988,0.197052,0.199753,0.185188,0.203577,0.155673,0.161807,0.197832,0.203155,0.201390,0.197460,0.149565,0.187630,0.217161,0.174559,0.196685,0.173665,0.201920,11.408611,1610612742,41.0,87.0,12.0,38.0,12.0,16.0,7.0,29.0,36.0,25.0,9.0,8.0,16.0,17.0,106.0,239.983333,14.0,15.0,15.0,44.0,4.0,103.971838,117.104361,-13.146712,0.159645,1.043291,21.438058,0.028121,0.109295,0.071448,14.196291,0.505059,0.518344,0.194360,102.200355,102.200355,55.776790,0.083048,0.540618,0.184078,0.155320,0.534614,0.150467,0.117294,0.351484,1.775957,0.589597,0.410403,0.375406,0.089519,0.288293,0.120119,0.077834,0.102521,0.286029,0.431148,0.256678,0.465397,0.199927,0.498200,0.243395,0.324056,0.404056,0.199455,0.198674,0.234511,0.197563,0.188766,0.193288,0.179929,0.199788,0.199410,0.199269,0.194797,0.201698,0.189836,0.148746,0.180069,0.178183,0.199691,-8.414820,MEM vs. DAL,2024-25,2025-04-18,1,1,14.0

# SPECIAL FOR ODDS : Keep only season past 2010-11

In [36]:
# # get first line with season 2010-11 and cut all lines before
# first_season = match_dataset[match_dataset['SEASON'] == '2010-11'].index[0]
# match_dataset = match_dataset.iloc[first_season:].reset_index(drop=True)
# match_dataset

# Merge Odds with dataset

In [37]:
all_odds_df = merge_odds_csv_files(DATA_ODDS_HISTORY_DIR)

match_dataset = match_odds_with_dataset_test(all_odds_df, match_dataset)

------------------ Nombre de lignes sans cotes (home/away): 25772 ------------------

In [38]:
match_dataset

,GAME_ID,TEAM_ID,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,points_traditional,MINUTES_PLAYED,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,blocksAgainst_misc,offensiveRating_advanced,defensiveRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,threePointersPercentage_traditional,freeThrowsPercentage_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage,plusMinusPoints_traditional,OPP_TEAM_ID,OPP_fieldGoalsMade_traditional,OPP_fieldGoalsAttempted_traditional,OPP_threePointersMade_traditional,OPP_threePointersAttempted_traditional,OPP_freeThrowsMade_traditional,OPP_freeThrowsAttempted_traditional,OPP_reboundsOffensive_traditional,OPP_reboundsDefensive_traditional,OPP_reboundsTotal_traditional,OPP_assists_traditional,OPP_steals_traditional,OPP_blocks_traditional,OPP_turnovers_traditional,OPP_foulsPersonal_traditional,OPP_points_traditional,OPP_MINUTES_PLAYED,OPP_pointsOffTurnovers_misc,OPP_pointsSecondChance_misc,OPP_pointsFastBreak_misc,OPP_pointsPaint_misc,OPP_blocksAgainst_misc,OPP_offensiveRating_advanced,OPP_defensiveRating_advanced,OPP_netRating_advanced,OPP_assistPercentage_advanced,OPP_assistToTurnover_advanced,OPP_assistRatio_advanced,OPP_offensiveReboundPercentage_advanced,OPP_defensiveReboundPercentage_advanced,OPP_reboundPercentage_advanced,OPP_turnoverRatio_advanced,OPP_effectiveFieldGoalPercentage_advanced,OPP_trueShootingPercentage_advanced,OPP_usagePercentage_advanced,OPP_estimatedPace_advanced,OPP_pace_advanced,OPP_possessions_advanced,OPP_PIE_advanced,OPP_effectiveFieldGoalPercentage_fourfactors,OPP_freeThrowAttemptRate_fourfactors,OPP_teamTurnoverPercentage_fourfactors,OPP_oppEffectiveFieldGoalPercentage_fourfactors,OPP_oppFreeThrowAttemptRate_fourfactors,OPP_oppTeamTurnoverPercentage_fourfactors,OPP_oppOffensiveReboundPercentage_fourfactors,OPP_foulsDrawn_misc,OPP_percentageFieldGoalsAttempted2pt_scoring,OPP_percentageFieldGoalsAttempted3pt_scoring,OPP_percentagePoints2pt_scoring,OPP_percentagePointsMidrange2pt_scoring,OPP_percentagePoints3pt_scoring,OPP_percentagePointsFastBreak_scoring,OPP_percentagePointsFreeThrow_scoring,OPP_percentagePointsOffTurnovers_scoring,OPP_percentagePointsPaint_scoring,OPP_percentageAssisted2pt_scoring,OPP_percentageUnassisted2pt_scoring,OPP_percentageAssisted3pt_scoring,OPP_percentageUnassisted3pt_scoring,OPP_percentageAssistedFGM_scoring,OPP_percentageUnassistedFGM_scoring,OPP_threePointersPercentage_traditional,OPP_freeThrowsPercentage_traditional,OPP_percentageFieldGoalsMade_usage,OPP_percentageFieldGoalsAttempted_usage,OPP_percentageThreePointersMade_usage,OPP_percentageThreePointersAttempted_usage,OPP_percentageFreeThrowsMade_usage,OPP_percentageFreeThrowsAttempted_usage,OPP_percentageReboundsOffensive_usage,OPP_percentageReboundsDefensive_usage,OPP_percentageReboundsTotal_usage,OPP_percentageAssists_usage,OPP_percentageTurnovers_usage,OPP_percentageSteals_usage,OPP_percentageBlocks_usage,OPP_percentageBlocksAllowed_usage,OPP_percentagePersonalFouls_usage,OPP_percentagePersonalFoulsDrawn_usage,OPP_percentagePoints_usage,OPP_plusMinusPoints_traditional,MATCHUP,SEASON,GAME_DATE,IS_HOME,IS_WIN,POINT_DIFF,TEAM_NAME,OPPONENT_NAME,ODDS,OPP_ODDS
0,20000001,1610612752,25,70,3,11,19,24,14,23,37,14,6,4,22,30,72,240.000000,12,15,4,22,5,80.922299,114.464688,-33.537868,0.163246,0.523610,11.026556,0.056220,0.147483,0.091563,19.763500,0.372955,0.436562,0.193970,88.699676,88.699676,43.962361,0.039403,0.377483,0.365924,0.247518,0.598126,0.458272,0.160368,0.266661,0.000000,0.857836,0.142164,0.650577,0.241035,0.057733,0.039143,0.257106,0.165235,0.409507,0.518244,0.447172,0.197778,0.000000,0.559933,0.405484,0.108844,0.466333,0.213520,0.203724,0.197778,0.193515,0.199331,0.190465,0.232461,0.204200,0.204153,0.200857,0.197202,0.196856,0.199583,0.160243,0.192422,0.000000,0.201207,-14.930903,1610612755,38.0,66.0,3.0,8.0,22.0,30.0,8.0,29.0,37.0,27.0,10.0,5.0,13.0,24.0,101.0,240.000000,26.0,9.0,10.0,36.0,4.0,113.678208,80.924167,32.729556,0.182441,1.177822,20.832340,0.049657,0.117050,0.092804,12.917368,0.562437,0.596134,0.194474,88.899378,88.899378,50.502014,0.160855,0.601599,0.469504,0.161353,0.382886,0.361238,0.246772,0.319077,0.000000,0.839428,0.116266,0.644489,0.293966,0.049281,0.125861,0.169078,0.233654,0.350402,0.615402,0.247446,0.168090,0.078368,0.629851,0.232997,0.168090,0.508698,0.203276,0.200388,0.194265,0.173397,0.203479,0.208561,0.163576,0.192186,0.195743,0.196602,0.176540,0.217619,0.134035,0.178715,0.194042,0.000000,0.208010,18.242986,NYK vs. PHI,2000-01,2000-10-31,1,0,-29.0,new york knicks,philadelphia 76ers,NaN,NaN
1,20000001,1610612755,38,66,3,8,22,30,8,29,37,27,10,5,13,24,101,240.000000,26,9,10,36,4,113.678208,80.924167,32.729556,0.182441,1.177822,20.832340,0.049657,0.117050,0.092804,12.917368,0.562437,0.596134,0.194474,88.899378,88.899378,50.502014,0.160855,0.601599,0.469504,0.161353,0.382886,0.361238,0.246772,0.319077,0.000000,0.839428,0.116266,0.644489,0.293966,0.049281,0.125861,0.169078,0.233654,0.350402,0.615402,0.247446,0.168090,0.078368,0.629851,0.232997,0.168090,0.508698,0.203276,0.200388,0.194265,0.173397,0.203479,0.208561,0.163576,0.192186,0.195743,0.196602,0.176540,0.217619,0.134035,0.178715,0.194042,0.000000,0.208010,18.242986,1610612752,25.0,70.0,3.0,11.0,19.0,24.0,14.0,23.0,37.0,14.0,6.0,4.0,22.0,30.0,72.0,240.000000,12.0,15.0,4.0,22.0,5.0,80.922299,114.464688,-33.537868,0.163246,0.523610,11.026556,0.056220,0.147483,0.091563,19.763500,0.372955,0.436562,0.193970,88.699676,88.699676,43.962361,0.039403,0.377483,0.365924,0.247518,0.598126,0.458272,0.160368,0.266661,0.000000,0.857836,0.142164,0.650577,0.241035,0.057733,0.039143,0.257106,0.165235,0.409507,0.518244,0.447172,0.197778,0.000000,0.559933,0.405484,0.108844,0.466333,0.213520,0.203724,0.197778,0.193515,0.199331,0.190465,0.232461,0.204200,0.204153,0.200857,0.197202,0.196856,0.199583,0.160243,0.192422,0.000000,0.201207,-14.930903,PHI @ NYK,2000-01,2000-10-31,0,1,29.0,philadelphia 76ers,new york knicks,NaN,NaN
2,20000002,1610612739,32,78,2,7,20,32,11,41,52,16,5,8,19,27,86,240.000000,12,12,14,36,8,87.118465,82.284514,4.836236,0.135260,0.953071,12.727431,0.043157,0.154742,0.099091,13.891264,0.403829,0.477510,0.197340,99.597600,99.597600,55.404514,0.027378,0.423046,0.418163,0.189245,0.385467,0.306368,0.150790,0.226623,0.000000,0.905348,0.071110,0.619452,0.225391,0.042091,0.151227,0.250680,0.134511,0.394061,0.380781,0.531441,0.226319,0.000000,0.404284,0.507939,0.179271,0.558568,0.200988,0.201629,0.113160,0.180712,0.189883,0.188048,0.223730,0.215432,0.215471,0.206409,0.202678,0.200235,0.161342,0.223420,0.197098,0.000000,0.194632,4.139722,1610612751,31.0,85.0,3.0,10.0,17.0,26.0,12.0,35.0,47.0,24.0,9.0,8.0,12.0,31.0,82.0,240.000000,21.0,13.0,9.0,42.0,8.0,83.457417,86.645424,-3.170028,0.186321,1.655972,19.164549,0.044377,0.128634,0.084390,9.645229,0.334428,0.403052,0.190604,98.798017,98.798017,59.042292,0.112319,0.383964,0.309240,0.149999,0.421320,0.418921,0.191348,0.243931,0.000000,0.892640,0.107360,0.589287,0.177226,0.068950,0.074612,0.329879,0.171267,0.412061,0.623859,0.250308,0.227153,0.000000,0.623859,0.250308,0.129859,0.680444,0.195359,0.199699,0.140674,0.162797,0.207021,0.210566,0.241208,0.196126,0.197293,0.200915,0.151191,0.198521,0.187091,0.206165,0.210120,0.000000,0.192918,-2.137222,CLE @ NJN,2000-01,2000-10-31,0,1,4.0,cleveland cavaliers,brooklyn nets,NaN,NaN
3,20000002,1610612751,31,85,3,10,17,26,12,35,47,24,9,8,12,31,82,240.000000,21,13,9,42,8,83.457417,86.645424,-3.170028,0.186321,1.655972,19.164549,0.044377,0.128634,0.084390,9.645229,0.334428,0.403052,0.190604,98.798017,98.798017,59.042292,0.112319,0.383964,0.309240,0.149999,0.421320,0.418921,0.191348,0.243931,0.000000,0.892640,0.107360,0.589287,0.177226,0.068950,0.074612,0.329879,0.171267,0.412061,0.623859,0.250308,0.227153,0.000000,0.623859,0.250308,0.129859,0.680444,0.195359,0.199699,0.140674,0.162797,0.207021,0.210566,0.241208,0.196126,0.197293,0.200915,0.151191,0.198521,0.187091,0.206165,0.210120,0.000000,0.192918,-2.137222,1610612739,32.0,78.0,2.0,7.0,20.0,32.0,11.0,41.0,52.0,16.0,5.0,8.0,19.0,27.0,86.0,240.000000,12.0,12.0,14.0,36.0,8.0,87.118465,82.284514,4.836236,0.135260,0.953071,12.727431,0.043157,0.154742,0.099091,13.891264,0.403829,0.477510,0.197340,99.597600,99.597600,55.404514,0.027378,0.423046,0.418163,0.189245,0.385467,0.306368,0.150790,0.226623,0.000000,0.905348,0.071110,0.619452,0.225391,0.042091,0.151227,0.250680,0.134511,0.394061,0.380781,0.531441,0.226319,0.000000,0.404284,0.507939,0.179271,0.558568,0.200988,0.201629,0.113160,0.180712,0.189883,0.188048,0.223730,0.215432,0.215471,0.206409,0.202678,0.200235,0.161342,0.223420,0.197098,0.000000,0.194632,4.139722,NJN vs. CLE,2000-01,2000-10-31,1,0,-4.0,brooklyn nets,cleveland cavaliers,NaN,NaN
4,20000003,1610612753,34,79,6,16,23,33,8,29,37,20,10,9,15,24,97,240.000000,28,9,19,32,1,98.736875,86.636882,12.099993,0.142503,0.857986,12.904542,0.031709,0.133742,0.081268,11.997660,0.475912,0.520254,0.200260,98.899090,98.899090,61.198889,0.118825,0.472056,0.423020,0.148499,0.486995,0.336534,0.267238,0.238280,0.000000,0.799790,0.200210,0.571690,0.237194,0.199434,0.245441,0.229067,0.346846,0.334358,0.459721,0.398473,0.403889,0.000000,0.606531,0.371316,0.186988,0.685047,0.200331,0.201844,0.229832,0.189043,0.227233,0.227924,0.167742,0.196079,0.201831,0.197763,0.182205,0.192654,0.169992,0.065000,0.193451,0.000000,0.204198,7.283056,1610612764,33.0,72.0,4.0,7.0,16.0,24.0,9.0,35.0,44.0,20.0,6.0,1.0,26.0,28.0,86.0,240.000000,15.0,12.0,14.0,42.0,9.0,87.675576,98.295687,-10.619472,0.149045,0.627285,14.817028,0.042904,0.148099,0.098173,19.670639,0.520195,0.553401,0.194765,98.401342,98.401342,53.393403,0.101201,0.485589,0.342879,0.267129,0.470513,0.418830,0.148780,0.185661,0.000000,0.916404,0.083596,0.632414,0.206632,0.148603,0.156626,0.189113,0.165165,0.425926,0.502342,0.467588,0.432986,0.000000,0.600256,0.369674,0.276597,0.604405,0.194938,0.201348,0.157969,0.160486,0.177851,0.170195,0.210115,0.209455,0.210824,0.194940,0.196138,0.138369,0.109583,0.186508,0.215050,0.000000,0.198386,-6.894514,ORL vs. WAS,2000-01,2000-10-31,1,1,11.0,orlando magic,washington wizards,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63870,52400131,1610612758,41,89,13,33,11,15,15,29,44,23,6,4,18,19,106,240.000000,15,13,15,40,8,110.123410,123.832694,-13.692986,0.144001,0.915579,16.246007,0.061248,0.139456,0.094800,13.410542,0.553654,0.568678,0.196805,96.900852,96.900852,64.197361,0.078930,0.533497,0.168455,0.181755,0.589886,0.321300,0.106123,0.242713,1.925417,0.579009,0.412449,0.498701,0.103705,0.374451,0.147024,0.093555,0.120819,0.394996,0.601385,0.356601,0.625625,0.137917,0.614244,0.352284,0.337209,0.444622,0.198443,0.199547,0.199186,0.197010,0.199987,0.198947,0.220836,0.204731,0.202397,0.198671,0.194704,0.193650,0.140420,0.176580,0.204741,0.201187,0.198282,-14.351250,1610612742,41.0,83.0,14.0,28.0,24.0,26.0,10.0,31.0,41.0,29.0,9.0,8.0,9.0,15.0,120.0,240.000000,18.0,4.0,14.0,40.0,4.0,123.867549,110.768076,13.093542,0.179320,1.234705,23.328986,0.043102,0.126057,0.088669,7.650514,0.614891,0.653447,0.190092,96.700401,96.700401,52.394028,0.120096,0.586034,0.319399,0.106316,0.531757,0.167544,0.181331,0.320657,2.229653,0.660342,0.331116,0.484243,0.140879,0.266205,0.119458,0.173500,0.127531,0.343317,0.539994,0.384173,0.710417,0.000000,0.693429,0.230738,0.371341,0.690868,0.189465,0.197248,0.188922,0.192500,0.200256,0.200080,0.177569,0.202057,0.201182,0.211608,0.180998,0.195077,0.211063,0.166207,0.202276,0.192422,0.188871,13.047708,SAC vs. DAL,2024-25,2025-04-16,1,0,-14.0,sacramento kings,dallas mavericks,1.41,2.85
63871,52400201,1610612737,44,102,16,47,10,12,11,33,44,30,12,3,9,18,114,265.016667,21,14,22,56,8,108.972216,113.769398,-4.786328,0.170940,1.701450,19.786856,0.038220,0.132929,0.082033,6.828665,0.533646,0.548288,0.194796,96.542768,96.542768,70.793032,0.094415,0.515043,0.115509,0.094355,0.582867,0.189826,0.139047,0.283225,2.338658,0.528556,0.471444,0.478198,0.000000,0.421953,0.212341,0.069536,0.130952,0.478198,0.664189,0.249212,0.692064,0.218571,0.717321,0.252367,0.401740,0.302049,0.201907,0.198260,0.191661,0.199505,0.163951,0.180012,0.223868,0.200502,0.200689,0.193867,0.160034,0.206388,0.145900,0.193684,0.193772,0.193633,0.199234,-6.091126,1610612748,48.0,96.0,16.0,42.0,11.0,18.0,13.0,41.0,54.0,33.0,4.0,8.0,14.0,15.0,123.0,265.000000,18.0,17.0,14.0,48.0,3.0,114.115346,109.194151,4.941660,0.175512,1.914025,21.394906,0.052826,0.136744,0.098506,8.743547,0.602740,0.610614,0.188164,96.271151,96.271151,74.389497,0.108900,0.582882,0.188123,0.140615,0.511179,0.117131,0.094058,0.210104,2.789245,0.569122,0.430878,0.531708,0.131616,0.389409,0.104841,0.078883,0.158831,0.400093,0.679972,0.320028,0.594560,0.156132,0.689231,0.310769,0.317894,0.399580,0.200367,0.200068,0.199439,0.200160,0.203244,0.198173,0.193693,0.197318,0.198007,0.203462,0.175619,0.211259,0.195655,0.227722,0.201947,0.191826,0.199943,7.759057,ATL vs. MIA,2024-25,2025-04-18,1,0,-9.0,atlanta hawks,miami heat,2.05,1.74
63872,52400201,1610612748,48,96,16,42,11,18,13,41,54,33,4,8,14,15,123,265.000000,18,17,14,48,3,114.115346,109.194151,4.941660,0.175512,1.914025,21.394906,0.052826,0.136744,0.098506,8.743547,0.602740,0.610614,0.188164,96.271151,96.271151,74.389497,0.108900,0.582882,0.188123,0.140615,0.511179,0.117131,0.094058,0.210104,2.789245,0.569122,0.430878,0.531708,0.131616,0.389409,0.104841,0.078883,0.158831,0.400093,0.679972,0.320028,0.594560,0.156132,0.689231,0.310769,0.317894,0.399580,0.200367,0.200068,0.199439,0.200160,0.203244,0.198173,0.193693,0.197318,0.198007,0.203462,0.175619,0.211259,0.195655,0.227722,0.201947,0.191826,0.199943,7.759057,1610612737,44.0,102.0,16.0,47.0,10.0,12.0,11.0,33.0,44.0,30.0,12.0,3.0,9.0,18.0,114.0,265.016667,21.0,14.0,22.0,56.0,8.0,108.972216,113.769398,-4.786328,0.170940,1.701450,19.786856,0.038220,0.132929,0.082033,6.828665,0.533646,0.548288,0.194796,96.542768,96.542768,70.793032,0.094415,0.515043,0.115509,0.094355,0.582867,0.189826,0.139047,0.283225,2.338658,0.528556,0.471444,0.478198,0.000000,0.421953,0.212341,0.069536,0.130952,0.478198,0.664189,0.249212,0.692064,0.218571,0.717321,0.252367,0.401740,0.302049,0.201907,0.198260,0.191661,0.199505,0.163951,0.180012,0.223868,0.200502,0.200689,0.193867,0.160034,0.206388,0.145900,0.193684,0.193772,0.193633,0.199234,-6.091126,MIA @ ATL,2024-25,2025-04-18,0,1,9.0,miami heat,atlanta hawks,1.74,2.05
63873,52400211,1610612742,41,87,12,38,12,16,7,29,36,25,9,8,16,17,106,239.983333,14,15,15,44,4,103.971838,117.104361,-13.146712,0.159645,1.043291,21.438058,0.028121,0.109295,0.071448,14.196291,0.505059,0.518344,0.194360,102.200355,102.200355,55.776790,0.083048,0.540618,0.184078,0.155320,0.534614,0.150467,0.117294,0.351484,1.775957,0.589597,0.410403,0.375406,0.089519,0.288293,0.120119,0.077834,0.102521,0.286029,0.431148,0.256678,0.465397,0.199927,0.498200,0.243395,0.324056,0.404056,0.199455,0.198674,0.234511,0.197563,0.188766,0.193288,0.179929,0.199788,0.199410,0.199269,0.194797,0.201698,0.189836,0.148746,0.180069,0.178183,0.199691,-8.414820,1610612763,47.0,100.0,13.0,31.0,13.0,15.0,16.0,34.0,50.0,30.0,8.0,4.0,10.0,17.0,120.0,240.000000,24.0,15.0,19.0,60.0,8.0,118.571125,105.071556,13.509528,0.154672,0.823437,19.079396,0.059757,0.149789,0.100197,4.889924,0.566430,0.582027,0.191697,101.299056,101.299056,62.138194,0.109814,0.532094,0.153846,0.116233,0.542366,0.187143,0.155200,0.164587,2.136944,0.650762,0.334099,0.569661,0.056488,0.328575,0.226652,0.078919,0.205619,0.513310,0.620063,0.349659,0.682240,0.087343,0.648875,0.320847,0.348328,0.327988,0.197052,0.199753,0.185188,0.203577,0.155673,0.161807,0.197832,0.203155,0.201390,0.197460,0.149565,0.187630,0.217161,0.174559,0.196685,0.173665,0.201920,11.408611,DAL @ MEM,2024-25,2025-04-18,0,0,-14.0,dallas mavericks,memphis grizzlies,2.82,1.42
63874,52400211,1610612763,47,100,13,31,13,15,16,34,50,30,8,4,10,17,120,240.000000,24,15,19,60,8,118.571125,105.071556,13.509528,0.154672,0.823437,19.079396,0.059757,0.149789,0.100197,4.889924,0.566430,0.582027,0.191697,101.299056,101.299056,62.138194,0.109814,0.532094,0.153846,0.116233,0.542366,0.187143,0.155200,0.164587,2.136944,0.650762,0.334099,0.569661,0.056488,0.328575,0.226652,0.078919,0.205619,0.513310,0.620063,0.349659,0.682240,0.087343,0.648875,0.320847,0.348328,0.327988,0.197052,0.199753,0.185188,0.203577,0.155673,0.161807,0.197832,0.203155,0.201390,0.197460,0.149565,0.187630,0.217161,0.174559,0.196685,0.173665,0.201920,11.408611,1610612742,41.0,87.0,12.0,38.0,12.0,16.0,7.0,29.0,36.0,25.0,9.0,8.0,16.0,17.0,106.0,239.983333,14.0,15.0,15.0,44.0,4.0,103.971838,117.104361,-13.146712,0.159645,1.043291,21.438058,0.028121,0.109295,0.071448,14.196291,0.505059,0.518344,0.194360,102.200355,102.200355,55.776790,0.083048,0.540618,0.184078,0.155320,0.534614,0.150467,0.117294,0.351484,1.775957,0.589597,0.410403,0.375406,0.089519,0.288293,0.120119,0.077834,0.102521,0.286029,0.431148,0.256678,0.465397,0.199927,0.498200,0.243395,0.324056,0.404056,0.199455,0.198674,0.234511,0.197563,0.188766,0.193288,0.179929,0.199788,0.199410,0.199269,0.194797,0.201698,0.189836,0.148746,0.180069,0.178183,0.199691,-8.414820,MEM vs. DAL,2024-25,2025-04-18,1,1,14.0,memphis grizzlies,dallas mavericks,1.42,2.82

# Merge match_dataset with df_team_features_final on TEAM and GAME

In [39]:

#team id as str
match_dataset['TEAM_ID'] = match_dataset['TEAM_ID'].astype(str)
match_dataset['GAME_ID'] = match_dataset['GAME_ID'].astype(str)

#date as datetime
match_dataset['GAME_DATE'] = pd.to_datetime(match_dataset['GAME_DATE'])

df_team_features_final['TEAM_ID'] = df_team_features_final['TEAM_ID'].astype(str)
df_team_features_final['GAME_ID'] = df_team_features_final['GAME_ID'].astype(str)
df_team_features_final['GAME_DATE'] = pd.to_datetime(df_team_features_final['GAME_DATE'])



# Merge match_dataset with df_team_features_final on TEAM and GAME, keep GAME_DATE
match_dataset = match_dataset.merge(
    df_team_features_final[['GAME_ID', 'TEAM_ID', 'GAME_DATE'] + df_team_features_final.columns.difference(['GAME_ID', 'TEAM_ID', 'GAME_DATE']).tolist()],
    on=['GAME_ID', 'TEAM_ID'],
    how='left'
)



# match_dataset_ = match_dataset.merge(
#     df_team_features_final,
#     on=['GAME_ID', 'TEAM_ID'],
#     how='left'
# )
#remove duplicates
match_dataset = match_dataset.drop_duplicates(subset=['GAME_ID', 'TEAM_ID'])

In [40]:
#sort by GAME_DATE and GAME_ID
#match_dataset = match_dataset.sort_values(['GAME_DATE', 'GAME_ID']).reset_index(drop=True)



#print GAME_DATE_x and GAME_DATE_y to check if they are the same
print("GAME_DATE_x and GAME_DATE_y are the same:", (match_dataset['GAME_DATE_x'] == match_dataset['GAME_DATE_y']).all())

#drop GAME_DATE_x and GAME_DATE_y to GAME_DATE
match_dataset['GAME_DATE'] = match_dataset['GAME_DATE_x']
match_dataset = match_dataset.drop(columns=['GAME_DATE_x', 'GAME_DATE_y'])



#display cols in common match_dataset and df_team_features_final
common_cols = set(match_dataset.columns).intersection(set(df_team_features_final.columns))
print("Common columns between match_dataset and df_team_features_final:")
display(common_cols)

GAME_DATE_x and GAME_DATE_y are the same: True
Common columns between match_dataset and df_team_features_final:

{'GAME_DATE',
 'GAME_ID',
 'TEAM_ID',
 'has_absent',
 'has_top_absent',
 'num_absent',
 'num_absent_other',
 'num_injured',
 'num_personal',
 'num_present',
 'num_resting',
 'num_suspended',
 'player_perf_score_mean',
 'player_perf_score_sum',
 'top_player_absent',
 'top_player_absent_other',
 'top_player_absent_other_rate',
 'top_player_absent_rate',
 'top_player_count',
 'top_player_injured',
 'top_player_injury_rate',
 'top_player_personal',
 'top_player_personal_rate',
 'top_player_resting',
 'top_player_resting_rate',
 'top_player_suspended',
 'top_player_suspension_rate'}

# Reorder columns for visualisation

In [41]:
cols_first = ['GAME_ID', 'GAME_DATE', 'TEAM_ID', 'OPP_TEAM_ID', 'IS_HOME', 'IS_WIN','POINT_DIFF','has_absent','has_top_absent','num_absent','top_player_absent', 'points_traditional','ODDS','OPP_ODDS']
other_cols = [col for col in match_dataset.columns if col not in cols_first]
match_dataset = match_dataset[cols_first + other_cols]
match_dataset

,GAME_ID,GAME_DATE,TEAM_ID,OPP_TEAM_ID,IS_HOME,IS_WIN,POINT_DIFF,has_absent,has_top_absent,num_absent,top_player_absent,points_traditional,ODDS,OPP_ODDS,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,MINUTES_PLAYED,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,blocksAgainst_misc,offensiveRating_advanced,defensiveRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,threePointersPercentage_traditional,freeThrowsPercentage_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage,plusMinusPoints_traditional,OPP_fieldGoalsMade_traditional,OPP_fieldGoalsAttempted_traditional,OPP_threePointersMade_traditional,OPP_threePointersAttempted_traditional,OPP_freeThrowsMade_traditional,OPP_freeThrowsAttempted_traditional,OPP_reboundsOffensive_traditional,OPP_reboundsDefensive_traditional,OPP_reboundsTotal_traditional,OPP_assists_traditional,OPP_steals_traditional,OPP_blocks_traditional,OPP_turnovers_traditional,OPP_foulsPersonal_traditional,OPP_points_traditional,OPP_MINUTES_PLAYED,OPP_pointsOffTurnovers_misc,OPP_pointsSecondChance_misc,OPP_pointsFastBreak_misc,OPP_pointsPaint_misc,OPP_blocksAgainst_misc,OPP_offensiveRating_advanced,OPP_defensiveRating_advanced,OPP_netRating_advanced,OPP_assistPercentage_advanced,OPP_assistToTurnover_advanced,OPP_assistRatio_advanced,OPP_offensiveReboundPercentage_advanced,OPP_defensiveReboundPercentage_advanced,OPP_reboundPercentage_advanced,OPP_turnoverRatio_advanced,OPP_effectiveFieldGoalPercentage_advanced,OPP_trueShootingPercentage_advanced,OPP_usagePercentage_advanced,OPP_estimatedPace_advanced,OPP_pace_advanced,OPP_possessions_advanced,OPP_PIE_advanced,OPP_effectiveFieldGoalPercentage_fourfactors,OPP_freeThrowAttemptRate_fourfactors,OPP_teamTurnoverPercentage_fourfactors,OPP_oppEffectiveFieldGoalPercentage_fourfactors,OPP_oppFreeThrowAttemptRate_fourfactors,OPP_oppTeamTurnoverPercentage_fourfactors,OPP_oppOffensiveReboundPercentage_fourfactors,OPP_foulsDrawn_misc,OPP_percentageFieldGoalsAttempted2pt_scoring,OPP_percentageFieldGoalsAttempted3pt_scoring,OPP_percentagePoints2pt_scoring,OPP_percentagePointsMidrange2pt_scoring,OPP_percentagePoints3pt_scoring,OPP_percentagePointsFastBreak_scoring,OPP_percentagePointsFreeThrow_scoring,OPP_percentagePointsOffTurnovers_scoring,OPP_percentagePointsPaint_scoring,OPP_percentageAssisted2pt_scoring,OPP_percentageUnassisted2pt_scoring,OPP_percentageAssisted3pt_scoring,OPP_percentageUnassisted3pt_scoring,OPP_percentageAssistedFGM_scoring,OPP_percentageUnassistedFGM_scoring,OPP_threePointersPercentage_traditional,OPP_freeThrowsPercentage_traditional,OPP_percentageFieldGoalsMade_usage,OPP_percentageFieldGoalsAttempted_usage,OPP_percentageThreePointersMade_usage,OPP_percentageThreePointersAttempted_usage,OPP_percentageFreeThrowsMade_usage,OPP_percentageFreeThrowsAttempted_usage,OPP_percentageReboundsOffensive_usage,OPP_percentageReboundsDefensive_usage,OPP_percentageReboundsTotal_usage,OPP_percentageAssists_usage,OPP_percentageTurnovers_usage,OPP_percentageSteals_usage,OPP_percentageBlocks_usage,OPP_percentageBlocksAllowed_usage,OPP_percentagePersonalFouls_usage,OPP_percentagePersonalFoulsDrawn_usage,OPP_percentagePoints_usage,OPP_plusMinusPoints_traditional,MATCHUP,SEASON,TEAM_NAME,OPPONENT_NAME,num_absent_other,num_injured,num_personal,num_present,num_resting,num_suspended,player_perf_score_mean,player_perf_score_sum,top_player_absent_other,top_player_absent_other_rate,top_player_absent_rate,top_player_count,top_player_injured,top_player_injury_rate,top_player_personal,top_player_personal_rate,top_player_resting,top_player_resting_rate,top_player_suspended,top_player_suspension_rate
0,20000001,2000-10-31,1610612752,1610612755,1,0,-29.0,0,0,0,0,72,NaN,NaN,25,70,3,11,19,24,14,23,37,14,6,4,22,30,240.000000,12,15,4,22,5,80.922299,114.464688,-33.537868,0.163246,0.523610,11.026556,0.056220,0.147483,0.091563,19.763500,0.372955,0.436562,0.193970,88.699676,88.699676,43.962361,0.039403,0.377483,0.365924,0.247518,0.598126,0.458272,0.160368,0.266661,0.000000,0.857836,0.142164,0.650577,0.241035,0.057733,0.039143,0.257106,0.165235,0.409507,0.518244,0.447172,0.197778,0.000000,0.559933,0.405484,0.108844,0.466333,0.213520,0.203724,0.197778,0.193515,0.199331,0.190465,0.232461,0.204200,0.204153,0.200857,0.197202,0.196856,0.199583,0.160243,0.192422,0.000000,0.201207,-14.930903,38.0,66.0,3.0,8.0,22.0,30.0,8.0,29.0,37.0,27.0,10.0,5.0,13.0,24.0,101.0,240.000000,26.0,9.0,10.0,36.0,4.0,113.678208,80.924167,32.729556,0.182441,1.177822,20.832340,0.049657,0.117050,0.092804,12.917368,0.562437,0.596134,0.194474,88.899378,88.899378,50.502014,0.160855,0.601599,0.469504,0.161353,0.382886,0.361238,0.246772,0.319077,0.000000,0.839428,0.116266,0.644489,0.293966,0.049281,0.125861,0.169078,0.233654,0.350402,0.615402,0.247446,0.168090,0.078368,0.629851,0.232997,0.168090,0.508698,0.203276,0.200388,0.194265,0.173397,0.203479,0.208561,0.163576,0.192186,0.195743,0.196602,0.176540,0.217619,0.134035,0.178715,0.194042,0.000000,0.208010,18.242986,NYK vs. PHI,2000-01,new york knicks,philadelphia 76ers,0,0,0,12,0,0,10.450000,125.4,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0
1,20000001,2000-10-31,1610612755,1610612752,0,1,29.0,0,0,0,0,101,NaN,NaN,38,66,3,8,22,30,8,29,37,27,10,5,13,24,240.000000,26,9,10,36,4,113.678208,80.924167,32.729556,0.182441,1.177822,20.832340,0.049657,0.117050,0.092804,12.917368,0.562437,0.596134,0.194474,88.899378,88.899378,50.502014,0.160855,0.601599,0.469504,0.161353,0.382886,0.361238,0.246772,0.319077,0.000000,0.839428,0.116266,0.644489,0.293966,0.049281,0.125861,0.169078,0.233654,0.350402,0.615402,0.247446,0.168090,0.078368,0.629851,0.232997,0.168090,0.508698,0.203276,0.200388,0.194265,0.173397,0.203479,0.208561,0.163576,0.192186,0.195743,0.196602,0.176540,0.217619,0.134035,0.178715,0.194042,0.000000,0.208010,18.242986,25.0,70.0,3.0,11.0,19.0,24.0,14.0,23.0,37.0,14.0,6.0,4.0,22.0,30.0,72.0,240.000000,12.0,15.0,4.0,22.0,5.0,80.922299,114.464688,-33.537868,0.163246,0.523610,11.026556,0.056220,0.147483,0.091563,19.763500,0.372955,0.436562,0.193970,88.699676,88.699676,43.962361,0.039403,0.377483,0.365924,0.247518,0.598126,0.458272,0.160368,0.266661,0.000000,0.857836,0.142164,0.650577,0.241035,0.057733,0.039143,0.257106,0.165235,0.409507,0.518244,0.447172,0.197778,0.000000,0.559933,0.405484,0.108844,0.466333,0.213520,0.203724,0.197778,0.193515,0.199331,0.190465,0.232461,0.204200,0.204153,0.200857,0.197202,0.196856,0.199583,0.160243,0.192422,0.000000,0.201207,-14.930903,PHI @ NYK,2000-01,philadelphia 76ers,new york knicks,0,0,0,12,0,0,15.658333,187.9,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0
2,20000002,2000-10-31,1610612739,1610612751,0,1,4.0,1,0,1,0,86,NaN,NaN,32,78,2,7,20,32,11,41,52,16,5,8,19,27,240.000000,12,12,14,36,8,87.118465,82.284514,4.836236,0.135260,0.953071,12.727431,0.043157,0.154742,0.099091,13.891264,0.403829,0.477510,0.197340,99.597600,99.597600,55.404514,0.027378,0.423046,0.418163,0.189245,0.385467,0.306368,0.150790,0.226623,0.000000,0.905348,0.071110,0.619452,0.225391,0.042091,0.151227,0.250680,0.134511,0.394061,0.380781,0.531441,0.226319,0.000000,0.404284,0.507939,0.179271,0.558568,0.200988,0.201629,0.113160,0.180712,0.189883,0.188048,0.223730,0.215432,0.215471,0.206409,0.202678,0.200235,0.161342,0.223420,0.197098,0.000000,0.194632,4.139722,31.0,85.0,3.0,10.0,17.0,26.0,12.0,35.0,47.0,24.0,9.0,8.0,12.0,31.0,82.0,240.000000,21.0,13.0,9.0,42.0,8.0,83.457417,86.645424,-3.170028,0.186321,1.655972,19.164549,0.044377,0.128634,0.084390,9.645229,0.334428,0.403052,0.190604,98.798017,98.798017,59.042292,0.112319,0.383964,0.309240,0.149999,0.421320,0.418921,0.191348,0.243931,0.000000,0.892640,0.107360,0.589287,0.177226,0.068950,0.074612,0.329879,0.171267,0.412061,0.623859,0.250308,0.227153,0.000000,0.623859,0.250308,0.129859,0.680444,0.195359,0.199699,0.140674,0.162797,0.207021,0.210566,0.241208,0.196126,0.197293,0.200915,0.151191,0.198521,0.187091,0.206165,0.210120,0.000000,0.192918,-2.137222,CLE @ NJN,2000-01,cleveland cavaliers,brooklyn nets,1,0,0,11,0,0,13.866667,166.4,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0
3,20000002,2000-10-31,1610612751,1610612739,1,0,-4.0,1,1,2,1,82,NaN,NaN,31,85,3,10,17,26,12,35,47,24,9,8,12,31,240.000000,21,13,9,42,8,83.457417,86.645424,-3.170028,0.186321,1.655972,19.164549,0.044377,0.128634,0.084390,9.645229,0.334428,0.403052,0.190604,98.798017,98.798017,59.042292,0.112319,0.383964,0.309240,0.149999,0.421320,0.418921,0.191348,0.243931,0.000000,0.892640,0.107360,0.589287,0.177226,0.068950,0.074612,0.329879,0.171267,0.412061,0.623859,0.250308,0.227153,0.000000,0.623859,0.250308,0.129859,0.680444,0.195359,0.199699,0.140674,0.162797,0.207021,0.210566,0.241208,0.196126,0.197293,0.200915,0.151191,0.198521,0.187091,0.206165,0.210120,0.000000,0.192918,-2.137222,32.0,78.0,2.0,7.0,20.0,32.0,11.0,41.0,52.0,16.0,5.0,8.0,19.0,27.0,86.0,240.000000,12.0,12.0,14.0,36.0,8.0,87.118465,82.284514,4.836236,0.135260,0.953071,12.727431,0.043157,0.154742,0.099091,13.891264,0.403829,0.477510,0.197340,99.597600,99.597600,55.404514,0.027378,0.423046,0.418163,0.189245,0.385467,0.306368,0.150790,0.226623,0.000000,0.905348,0.071110,0.619452,0.225391,0.042091,0.151227,0.250680,0.134511,0.394061,0.380781,0.531441,0.226319,0.000000,0.404284,0.507939,0.179271,0.558568,0.200988,0.201629,0.113160,0.180712,0.189883,0.188048,0.223730,0.215432,0.215471,0.206409,0.202678,0.200235,0.161342,0.223420,0.197098,0.000000,0.194632,4.139722,NJN vs. CLE,2000-01,brooklyn nets,cleveland cavaliers,2,0,0,10,0,0,14.950000,179.4,1,0.2,0.2,5,0,0.0,0,0.0,0,0.0,0,0.0
4,20000003,2000-10-31,1610612753,1610612764,1,1,11.0,1,0,2,0,97,NaN,NaN,34,79,6,16,23,33,8,29,37,20,10,9,15,24,240.000000,28,9,19,32,1,98.736875,86.636882,12.099993,0.142503,0.857986,12.904542,0.031709,0.133742,0.081268,11.997660,0.475912,0.520254,0.200260,98.899090,98.899090,61.198889,0.118825,0.472056,0.423020,0.148499,0.486995,0.336534,0.267238,0.238280,0.000000,0.799790,0.200210,0.571690,0.237194,0.199434,0.245441,0.229067,0.346846,0.334358,0.459721,0.398473,0.403889,0.000000,0.606531,0.371316,0.186988,0.685047,0.200331,0.201844,0.229832,0.189043,0.227233,0.227924,0.167742,0.196079,0.201831,0.197763,0.182205,0.192654,0.169992,0.065000,0.193451,0.000000,0.204198,7.283056,33.0,72.0,4.0,7.0,16.0,24.0,9.0,35.0,44.0,20.0,6.0,1.0,26.0,28.0,86.0,240.000000,15.0,12.0,14.0,42.0,9.0,87.675576,98.295687,-10.619472,0.149045,0.627285,14.817028,0.042904,0.148099,0.098173,19.670639,0.520195,0.553401,0.194765,98.401342,98.401342,53.393403,0.101201,0.485589,0.342879,0.267129,0.470513,0.418830,0.148780,0.185661,0.000000,0.916404,0.083596,0.632414,0.206632,0.148603,0.156626,0.189113,0.165165,0.425926,0.502342,0.467588,0.432986,0.000000,0.600256,0.369674,0.276597,0.604405,0.194938,0.201348,0.157969,0.160486,0.177851,0.170195,0.210115,0.209455,0.210824,0.194940,0.196138,0.138369,0.109583,0.186508,0.215050,0.000000,0.198386,-6.894514,ORL vs. WAS,2000-01,orlando magic,washington wizards,2,0,0,10,0,0,14.616667,175.4,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63870,52400131,2025-04-16,1610612758,1610612742,1,0,-14.0,1,0,1,0,106,1.41,2.85,41,89,13,33,11,15,15,29,44,23,6,4,18,19,240.000000,15,13,15,40,8,110.123410,123.832694,-13.692986,0.144001,0.915579,16.246007,0.061248,0.139456,0.094800,13.410542,0.553654,0.568678,0.196805,96.900852,96.900852,64.197361,0.078930,0.533497,0.168455,0.181755,0.589886,0.321300,0.106123,0.242713,1.925417,0.579009,0.412449,0.498701,0.103705,0.374451,0.147024,0.093555,0.120819,0.394996,0.601385,0.356601,0.625625,0.137917,0.614244,0.352284,0.337209,0.444622,0.198443,0.199547,0.199186,0.197010,0.199987,0.198947,0.220836,0.204731,0.202397,0.198671,0.194704,0.193650,0.140420,0.176580,0.204741,0.201187,0.198282,-14.351250,41.0,83.0,14.0,28.0,24.0,26.0,10.0,31.0,41.0,29.0,9.0,8.0,9.0,15.0,120.0,240.000000,18.0,4.0,14.0,40.0,4.0,123.867549,110.768076,13.093542,0.179320,1.234705,23.328986,0.043102,0.126057,0.088669,7.650514,0.614891,0.653447,0.190092,96.700401,96.700401,52.394028,0.120096,0.586034,0.319399,0.106316,0.531757,0.167544,0.181331,0.320657,2.229653,0.660342,0.331116,0.484243,0.140879,0.266205,0.119458,0.173500,0.127531,0.343317,0.539994,0.384173,0.710417,0.000000,0.693429,0.230738,0.371341,0.690868,0.189465,0.197248,0.188922,0.192500,0.200256,0.200080,0.177569,0.202057,0.201182,0.211608,0.180998,0.195077,0.211063,0.166207,0.202276,0.192422,0.188871,13.047708,SAC vs. DAL,2024-25,sacramento kings,dallas mavericks,1,0,0,12,0,0,14.253846,185.3,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0
63871,52400201,2025-04-18,1610612737,1610612748,1,0,-9.0,1,0,3,0,114,2.05,1.74,44,102,16,47,10,12,11,33,44,30,12,3,9,18,265.016667,21,14,22,56,8,108.972216,113.769398,-4.786328,0.170940,1.701450,19.786856,0.038220,0.132929,0.082033,6.828665,0.533646,0.548288,0.194796,96.542768,96.542768,70.793032,0.094415,0.515043,0.115509,0.094355,0.582867,0.189826,0.139047,0.283225,2.338658,0.528556,0.471444,0.478198,0.000000,0.421953,0.212341,0.069536,0.130952,0.478198,0.664189,0.249212,0.692064,0.218571,0.717321,0.252367,0.401740,0.302049,0.201907,0.198260,0.191661,0.199505,0.163951,0.180012,0.223868,0.200502,0.200689,0.193867,0.160034,0.206388,0.145900,0.193684,0.193772,0.193633,0.199234,-6.091126,48.0,96.0,16.0,42.0,11.0,18.0,13.0,41.0,54.0,33.0,4.0,8.0,14.0,15.0,123.0,265.000000,18.0,17.0,14.0,48.0,3.0,114.115346,109.194151,4.941660,0.175512,1.914025,21.394906,0.052826,0.136744,0.098506,8.743547,0.602740,0.610614,0.188164,96.271151,96.271151,74.389497,0.108900,0.582882,0.188123,0.140615,0.511179,0.117131,0.094058,0.210104,2.789245,0.569122,0.430878,0.531708,0.131616,0.389409,0.104841,0.078883,0.158831,0.400093,0.679972,0.320028,0.594560,0.156132,0.689231,0.310769,0.317894,0.399580,0.200367,0.200068,0.199439,0.200160,0.203244,0.198173,0.193693,0.197318,0.198007,0.203462,0.175619,0.211259,0.195655,0.227722,0.201947,0.191826,0.199943,7.759057,ATL vs. MIA,2024-25,atlanta hawks,miami heat,2,1,0,9,0,0,18.150000,217.8,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0
63872,52400201,2025-04-18,1610612748,1610612737,0,1,9.0,1,0,6,0,123,1.74,2.05,48,96,16,42,11,18,13,41,54,33,4,8,14,15,265.000000,18,17,14,48,3,114.115346,109.194151,4.941660,0.175512,1.914025,21.394906,0.052826,0.136744,0.098506,8.743547,0.602740,0.610614,0.188164,96.271151,96.271151,74.389497,0.108900,0.582882,0.188123,0.140615,0.511179,0.117131,0.094058,0.210104,2.789245,0.569122,0.430878,0.531708,0.131616,0.389409,0.104841,0.078883,0.158831,0.400093,0.679972,0.320028,0.594560,0.156132,0.689231,0.310769,0.317894,0.399580,0.200367,0.200068,0.199439,0.200160,0.203244,0.198173,0.193693,0.197318,0.198007,0.203462,0.175619,0.211259,0.195655,0.227722,0.201947,0.191826,0.199943,7.759057,44.0,102.0,16.0,47.0,10.0,12.0,11.0,33.0,44.0,30.0,12.0,3.0,9.0,18.0,114.0,265.016667,21.0,14.0,22.0,56.0,8.0,108.972216,113.769398,-4.786328,0.170940,1.701450,19.786856,0.038220,0.132929,0.082033,6.828665,0.533646,0.548288,0.194796,96.542768,96.542768,70.793032,0.094415,0.515043,0.115509,0.094355,0.582867,0.189826,0.139047,0.283225,2.338658,0.528556,0.471444,0.478198,0.000000,0.421953,0.212341,0.069536,0.130952,0.478198,0.664189,0.249212,0.692064,0.218571,0.717321,0.252367,0.401740,0.302049,0.201907,0.198260,0.191661,0.199505,0.163951,0.180012,0.223868,0.200502,0.200689,0.193867,0.160034,0.206388,0.145900,0.193684,0.193772,0.193633,0.199234,-6.091126,MIA @ ATL,2024-25,miami heat,atlanta hawks,5,0,1,9,0,0,15.686667,235.3,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0
63873,52400211,2025-04-18,1610612742,1610612763,0,0,-14.0,1,0,2,0,106,2.82,1.42,41,87,12,38,12,16,7,29,36,25,9,8,16,17,239.983333,14,15,15,44,4,103.971838,117.104361,-13.146712,0.159645,1.043291,21.438058,0.028121,0.109295,0.071448,14.196291,0.505059,0.518344,0.194360,102.200355,102.200355,55.776790,0.083048,0.540618,0.184078,0.155320,0.534614,0.150467,0.117294,0.351484,1.775957,0.589597,0.410403,0.375406,0.089519,0.288293,0.120119,0.077834,0.102521,0.286029,0.431148,0.256678,0.465397,0.199927,0.498200,0.243395,0.324056,0.404056,0.199455,0.198674,0.234511,0.197563,0.188766,0.193288,0.179929,0.199788,0.199410,0.199269,0.194797,0.201698,0.189836,0.148746,0.180069,0.178183,0.199691,-8.414820,47.0,100.0,13.0,31.0,13.0,15.0,16.0,34.0,50.0,30.0,8.0,4.0,10.0,17.0,120.0,240.000000,24.0,15.0,19.0,60.0,8.0,118.571125,105.071556,13.509528,0.154672,0.823437,19.079396,0.059757,0.149789,0.100197,4.889924,0.566430,0.582027,0.191697,101.299056,101.299056,62.138194,0.109814,0.532094,0.153846,0.116233,0.542366,0.187143,0.155200,0.164587,2.136944,0.650762,0.334099,0.569661,0.056488,0.328575,0.226652,0.078919,0.205619,0.513310,0.620063,0.349659,0.682240,0.087343,0.648875,0.320847,0.348328,0.327988,0.197052,0.199753,0.185188,0.203577,0.155673,0.161807,0.197832,0.203155,0.201390,0.197460,0.149565,0.187630,0.217161,0.174559,0.196685,0.173665,0.201920,11.408611,DAL @ MEM,2024-25,dallas mavericks,memphis grizzlies,2,0,0,11,0,0,14.438462,187.7,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0

# Add OPP cols for player stats

In [42]:
opp_cols = [f"OPP_{col}" for col in cols_player_stats]
df_opp = match_dataset.rename(columns={col: f"OPP_{col}" for col in cols_player_stats})

match_dataset = pd.merge(
    match_dataset,
    df_opp[['GAME_ID', 'TEAM_ID'] + opp_cols],
    on=['GAME_ID', 'TEAM_ID'],
    how='left'
)

In [43]:
match_dataset

,GAME_ID,GAME_DATE,TEAM_ID,OPP_TEAM_ID,IS_HOME,IS_WIN,POINT_DIFF,has_absent,has_top_absent,num_absent,top_player_absent,points_traditional,ODDS,OPP_ODDS,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,MINUTES_PLAYED,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,blocksAgainst_misc,offensiveRating_advanced,defensiveRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,threePointersPercentage_traditional,freeThrowsPercentage_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage,plusMinusPoints_traditional,OPP_fieldGoalsMade_traditional,OPP_fieldGoalsAttempted_traditional,OPP_threePointersMade_traditional,OPP_threePointersAttempted_traditional,OPP_freeThrowsMade_traditional,OPP_freeThrowsAttempted_traditional,OPP_reboundsOffensive_traditional,OPP_reboundsDefensive_traditional,OPP_reboundsTotal_traditional,OPP_assists_traditional,OPP_steals_traditional,OPP_blocks_traditional,OPP_turnovers_traditional,OPP_foulsPersonal_traditional,OPP_points_traditional,OPP_MINUTES_PLAYED,OPP_pointsOffTurnovers_misc,OPP_pointsSecondChance_misc,OPP_pointsFastBreak_misc,OPP_pointsPaint_misc,OPP_blocksAgainst_misc,OPP_offensiveRating_advanced,OPP_defensiveRating_advanced,OPP_netRating_advanced,OPP_assistPercentage_advanced,OPP_assistToTurnover_advanced,OPP_assistRatio_advanced,OPP_offensiveReboundPercentage_advanced,OPP_defensiveReboundPercentage_advanced,OPP_reboundPercentage_advanced,OPP_turnoverRatio_advanced,OPP_effectiveFieldGoalPercentage_advanced,OPP_trueShootingPercentage_advanced,OPP_usagePercentage_advanced,OPP_estimatedPace_advanced,OPP_pace_advanced,OPP_possessions_advanced,OPP_PIE_advanced,OPP_effectiveFieldGoalPercentage_fourfactors,OPP_freeThrowAttemptRate_fourfactors,OPP_teamTurnoverPercentage_fourfactors,OPP_oppEffectiveFieldGoalPercentage_fourfactors,OPP_oppFreeThrowAttemptRate_fourfactors,OPP_oppTeamTurnoverPercentage_fourfactors,OPP_oppOffensiveReboundPercentage_fourfactors,OPP_foulsDrawn_misc,OPP_percentageFieldGoalsAttempted2pt_scoring,OPP_percentageFieldGoalsAttempted3pt_scoring,OPP_percentagePoints2pt_scoring,OPP_percentagePointsMidrange2pt_scoring,OPP_percentagePoints3pt_scoring,OPP_percentagePointsFastBreak_scoring,OPP_percentagePointsFreeThrow_scoring,OPP_percentagePointsOffTurnovers_scoring,OPP_percentagePointsPaint_scoring,OPP_percentageAssisted2pt_scoring,OPP_percentageUnassisted2pt_scoring,OPP_percentageAssisted3pt_scoring,OPP_percentageUnassisted3pt_scoring,OPP_percentageAssistedFGM_scoring,OPP_percentageUnassistedFGM_scoring,OPP_threePointersPercentage_traditional,OPP_freeThrowsPercentage_traditional,OPP_percentageFieldGoalsMade_usage,OPP_percentageFieldGoalsAttempted_usage,OPP_percentageThreePointersMade_usage,OPP_percentageThreePointersAttempted_usage,OPP_percentageFreeThrowsMade_usage,OPP_percentageFreeThrowsAttempted_usage,OPP_percentageReboundsOffensive_usage,OPP_percentageReboundsDefensive_usage,OPP_percentageReboundsTotal_usage,OPP_percentageAssists_usage,OPP_percentageTurnovers_usage,OPP_percentageSteals_usage,OPP_percentageBlocks_usage,OPP_percentageBlocksAllowed_usage,OPP_percentagePersonalFouls_usage,OPP_percentagePersonalFoulsDrawn_usage,OPP_percentagePoints_usage,OPP_plusMinusPoints_traditional,MATCHUP,SEASON,TEAM_NAME,OPPONENT_NAME,num_absent_other,num_injured,num_personal,num_present,num_resting,num_suspended,player_perf_score_mean,player_perf_score_sum,top_player_absent_other,top_player_absent_other_rate,top_player_absent_rate,top_player_count,top_player_injured,top_player_injury_rate,top_player_personal,top_player_personal_rate,top_player_resting,top_player_resting_rate,top_player_suspended,top_player_suspension_rate,OPP_num_absent,OPP_num_injured,OPP_num_personal,OPP_num_present,OPP_num_resting,OPP_num_suspended,OPP_num_absent_other,OPP_player_perf_score_mean,OPP_player_perf_score_sum,OPP_top_player_absent,OPP_top_player_absent_rate,OPP_top_player_count,OPP_top_player_injured,OPP_top_player_injury_rate,OPP_top_player_personal,OPP_top_player_personal_rate,OPP_top_player_resting,OPP_top_player_resting_rate,OPP_top_player_suspended,OPP_top_player_suspension_rate,OPP_top_player_absent_other,OPP_top_player_absent_other_rate
0,20000001,2000-10-31,1610612752,1610612755,1,0,-29.0,0,0,0,0,72,NaN,NaN,25,70,3,11,19,24,14,23,37,14,6,4,22,30,240.000000,12,15,4,22,5,80.922299,114.464688,-33.537868,0.163246,0.523610,11.026556,0.056220,0.147483,0.091563,19.763500,0.372955,0.436562,0.193970,88.699676,88.699676,43.962361,0.039403,0.377483,0.365924,0.247518,0.598126,0.458272,0.160368,0.266661,0.000000,0.857836,0.142164,0.650577,0.241035,0.057733,0.039143,0.257106,0.165235,0.409507,0.518244,0.447172,0.197778,0.000000,0.559933,0.405484,0.108844,0.466333,0.213520,0.203724,0.197778,0.193515,0.199331,0.190465,0.232461,0.204200,0.204153,0.200857,0.197202,0.196856,0.199583,0.160243,0.192422,0.000000,0.201207,-14.930903,38.0,66.0,3.0,8.0,22.0,30.0,8.0,29.0,37.0,27.0,10.0,5.0,13.0,24.0,101.0,240.000000,26.0,9.0,10.0,36.0,4.0,113.678208,80.924167,32.729556,0.182441,1.177822,20.832340,0.049657,0.117050,0.092804,12.917368,0.562437,0.596134,0.194474,88.899378,88.899378,50.502014,0.160855,0.601599,0.469504,0.161353,0.382886,0.361238,0.246772,0.319077,0.000000,0.839428,0.116266,0.644489,0.293966,0.049281,0.125861,0.169078,0.233654,0.350402,0.615402,0.247446,0.168090,0.078368,0.629851,0.232997,0.168090,0.508698,0.203276,0.200388,0.194265,0.173397,0.203479,0.208561,0.163576,0.192186,0.195743,0.196602,0.176540,0.217619,0.134035,0.178715,0.194042,0.000000,0.208010,18.242986,NYK vs. PHI,2000-01,new york knicks,philadelphia 76ers,0,0,0,12,0,0,10.450000,125.4,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0,0,0,0,12,0,0,0,10.450000,125.4,0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
1,20000001,2000-10-31,1610612755,1610612752,0,1,29.0,0,0,0,0,101,NaN,NaN,38,66,3,8,22,30,8,29,37,27,10,5,13,24,240.000000,26,9,10,36,4,113.678208,80.924167,32.729556,0.182441,1.177822,20.832340,0.049657,0.117050,0.092804,12.917368,0.562437,0.596134,0.194474,88.899378,88.899378,50.502014,0.160855,0.601599,0.469504,0.161353,0.382886,0.361238,0.246772,0.319077,0.000000,0.839428,0.116266,0.644489,0.293966,0.049281,0.125861,0.169078,0.233654,0.350402,0.615402,0.247446,0.168090,0.078368,0.629851,0.232997,0.168090,0.508698,0.203276,0.200388,0.194265,0.173397,0.203479,0.208561,0.163576,0.192186,0.195743,0.196602,0.176540,0.217619,0.134035,0.178715,0.194042,0.000000,0.208010,18.242986,25.0,70.0,3.0,11.0,19.0,24.0,14.0,23.0,37.0,14.0,6.0,4.0,22.0,30.0,72.0,240.000000,12.0,15.0,4.0,22.0,5.0,80.922299,114.464688,-33.537868,0.163246,0.523610,11.026556,0.056220,0.147483,0.091563,19.763500,0.372955,0.436562,0.193970,88.699676,88.699676,43.962361,0.039403,0.377483,0.365924,0.247518,0.598126,0.458272,0.160368,0.266661,0.000000,0.857836,0.142164,0.650577,0.241035,0.057733,0.039143,0.257106,0.165235,0.409507,0.518244,0.447172,0.197778,0.000000,0.559933,0.405484,0.108844,0.466333,0.213520,0.203724,0.197778,0.193515,0.199331,0.190465,0.232461,0.204200,0.204153,0.200857,0.197202,0.196856,0.199583,0.160243,0.192422,0.000000,0.201207,-14.930903,PHI @ NYK,2000-01,philadelphia 76ers,new york knicks,0,0,0,12,0,0,15.658333,187.9,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0,0,0,0,12,0,0,0,15.658333,187.9,0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
2,20000002,2000-10-31,1610612739,1610612751,0,1,4.0,1,0,1,0,86,NaN,NaN,32,78,2,7,20,32,11,41,52,16,5,8,19,27,240.000000,12,12,14,36,8,87.118465,82.284514,4.836236,0.135260,0.953071,12.727431,0.043157,0.154742,0.099091,13.891264,0.403829,0.477510,0.197340,99.597600,99.597600,55.404514,0.027378,0.423046,0.418163,0.189245,0.385467,0.306368,0.150790,0.226623,0.000000,0.905348,0.071110,0.619452,0.225391,0.042091,0.151227,0.250680,0.134511,0.394061,0.380781,0.531441,0.226319,0.000000,0.404284,0.507939,0.179271,0.558568,0.200988,0.201629,0.113160,0.180712,0.189883,0.188048,0.223730,0.215432,0.215471,0.206409,0.202678,0.200235,0.161342,0.223420,0.197098,0.000000,0.194632,4.139722,31.0,85.0,3.0,10.0,17.0,26.0,12.0,35.0,47.0,24.0,9.0,8.0,12.0,31.0,82.0,240.000000,21.0,13.0,9.0,42.0,8.0,83.457417,86.645424,-3.170028,0.186321,1.655972,19.164549,0.044377,0.128634,0.084390,9.645229,0.334428,0.403052,0.190604,98.798017,98.798017,59.042292,0.112319,0.383964,0.309240,0.149999,0.421320,0.418921,0.191348,0.243931,0.000000,0.892640,0.107360,0.589287,0.177226,0.068950,0.074612,0.329879,0.171267,0.412061,0.623859,0.250308,0.227153,0.000000,0.623859,0.250308,0.129859,0.680444,0.195359,0.199699,0.140674,0.162797,0.207021,0.210566,0.241208,0.196126,0.197293,0.200915,0.151191,0.198521,0.187091,0.206165,0.210120,0.000000,0.192918,-2.137222,CLE @ NJN,2000-01,cleveland cavaliers,brooklyn nets,1,0,0,11,0,0,13.866667,166.4,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0,1,0,0,11,0,0,1,13.866667,166.4,0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
3,20000002,2000-10-31,1610612751,1610612739,1,0,-4.0,1,1,2,1,82,NaN,NaN,31,85,3,10,17,26,12,35,47,24,9,8,12,31,240.000000,21,13,9,42,8,83.457417,86.645424,-3.170028,0.186321,1.655972,19.164549,0.044377,0.128634,0.084390,9.645229,0.334428,0.403052,0.190604,98.798017,98.798017,59.042292,0.112319,0.383964,0.309240,0.149999,0.421320,0.418921,0.191348,0.243931,0.000000,0.892640,0.107360,0.589287,0.177226,0.068950,0.074612,0.329879,0.171267,0.412061,0.623859,0.250308,0.227153,0.000000,0.623859,0.250308,0.129859,0.680444,0.195359,0.199699,0.140674,0.162797,0.207021,0.210566,0.241208,0.196126,0.197293,0.200915,0.151191,0.198521,0.187091,0.206165,0.210120,0.000000,0.192918,-2.137222,32.0,78.0,2.0,7.0,20.0,32.0,11.0,41.0,52.0,16.0,5.0,8.0,19.0,27.0,86.0,240.000000,12.0,12.0,14.0,36.0,8.0,87.118465,82.284514,4.836236,0.135260,0.953071,12.727431,0.043157,0.154742,0.099091,13.891264,0.403829,0.477510,0.197340,99.597600,99.597600,55.404514,0.027378,0.423046,0.418163,0.189245,0.385467,0.306368,0.150790,0.226623,0.000000,0.905348,0.071110,0.619452,0.225391,0.042091,0.151227,0.250680,0.134511,0.394061,0.380781,0.531441,0.226319,0.000000,0.404284,0.507939,0.179271,0.558568,0.200988,0.201629,0.113160,0.180712,0.189883,0.188048,0.223730,0.215432,0.215471,0.206409,0.202678,0.200235,0.161342,0.223420,0.197098,0.000000,0.194632,4.139722,NJN vs. CLE,2000-01,brooklyn nets,cleveland cavaliers,2,0,0,10,0,0,14.950000,179.4,1,0.2,0.2,5,0,0.0,0,0.0,0,0.0,0,0.0,2,0,0,10,0,0,2,14.950000,179.4,1,0.2,5,0,0.0,0,0.0,0,0.0,0,0.0,1,0.2
4,20000003,2000-10-31,1610612753,1610612764,1,1,11.0,1,0,2,0,97,NaN,NaN,34,79,6,16,23,33,8,29,37,20,10,9,15,24,240.000000,28,9,19,32,1,98.736875,86.636882,12.099993,0.142503,0.857986,12.904542,0.031709,0.133742,0.081268,11.997660,0.475912,0.520254,0.200260,98.899090,98.899090,61.198889,0.118825,0.472056,0.423020,0.148499,0.486995,0.336534,0.267238,0.238280,0.000000,0.799790,0.200210,0.571690,0.237194,0.199434,0.245441,0.229067,0.346846,0.334358,0.459721,0.398473,0.403889,0.000000,0.606531,0.371316,0.186988,0.685047,0.200331,0.201844,0.229832,0.189043,0.227233,0.227924,0.167742,0.196079,0.201831,0.197763,0.182205,0.192654,0.169992,0.065000,0.193451,0.000000,0.204198,7.283056,33.0,72.0,4.0,7.0,16.0,24.0,9.0,35.0,44.0,20.0,6.0,1.0,26.0,28.0,86.0,240.000000,15.0,12.0,14.0,42.0,9.0,87.675576,98.295687,-10.619472,0.149045,0.627285,14.817028,0.042904,0.148099,0.098173,19.670639,0.520195,0.553401,0.194765,98.401342,98.401342,53.393403,0.101201,0.485589,0.342879,0.267129,0.470513,0.418830,0.148780,0.185661,0.000000,0.916404,0.083596,0.632414,0.206632,0.148603,0.156626,0.189113,0.165165,0.425926,0.502342,0.467588,0.432986,0.000000,0.600256,0.369674,0.276597,0.604405,0.194938,0.201348,0.157969,0.160486,0.177851,0.170195,0.210115,0.209455,0.210824,0.194940,0.196138,0.138369,0.109583,0.186508,0.215050,0.000000,0.198386,-6.894514,ORL vs. WAS,2000-01,orlando magic,washington wizards,2,0,0,10,0,0,14.616667,175.4,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0,2,0,0,10,0,0,2,14.616667,175.4,0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63870,52400131,2025-04-16,1610612758,1610612742,1,0,-14.0,1,0,1,0,106,1.41,2.85,41,89,13,33,11,15,15,29,44,23,6,4,18,19,240.000000,15,13,15,40,8,110.123410,123.832694,-13.692986,0.144001,0.915579,16.246007,0.061248,0.139456,0.094800,13.410542,0.553654,0.568678,0.196805,96.900852,96.900852,64.197361,0.078930,0.533497,0.168455,0.181755,0.589886,0.321300,0.106123,0.242713,1.925417,0.579009,0.412449,0.498701,0.103705,0.374451,0.147024,0.093555,0.120819,0.394996,0.601385,0.356601,0.625625,0.137917,0.614244,0.352284,0.337209,0.444622,0.198443,0.199547,0.199186,0.197010,0.199987,0.198947,0.220836,0.204731,0.202397,0.198671,0.194704,0.193650,0.140420,0.176580,0.204741,0.201187,0.198282,-14.351250,41.0,83.0,14.0,28.0,24.0,26.0,10.0,31.0,41.0,29.0,9.0,8.0,9.0,15.0,120.0,240.000000,18.0,4.0,14.0,40.0,4.0,123.867549,110.768076,13.093542,0.179320,1.234705,23.328986,0.043102,0.126057,0.088669,7.650514,0.614891,0.653447,0.190092,96.700401,96.700401,52.394028,0.120096,0.586034,0.319399,0.106316,0.531757,0.167544,0.181331,0.320657,2.229653,0.660342,0.331116,0.484243,0.140879,0.266205,0.119458,0.173500,0.127531,0.343317,0.539994,0.384173,0.710417,0.000000,0.693429,0.230738,0.371341,0.690868,0.189465,0.197248,0.188922,0.192500,0.200256,0.200080,0.177569,0.202057,0.201182,0.211608,0.180998,0.195077,0.211063,0.166207,0.202276,0.192422,0.188871,13.047708,SAC vs. DAL,2024-25,sacramento kings,dallas mavericks,1,0,0,12,0,0,14.253846,185.3,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0,1,0,0,12,0,0,1,14.253846,185.3,0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
63871,52400201,2025-04-18,1610612737,1610612748,1,0,-9.0,1,0,3,0,114,2.05,1.74,44,102,16,47,10,12,11,33,44,30,12,3,9,18,265.016667,21,14,22,56,8,108.972216,113.769398,-4.786328,0.170940,1.701450,19.786856,0.038220,0.132929,0.082033,6.828665,0.533646,0.548288,0.194796,96.542768,96.542768,70.793032,0.094415,0.515043,0.115509,0.094355,0.582867,0.189826,0.139047,0.283225,2.338658,0.528556,0.471444,0.478198,0.000000,0.421953,0.212341,0.069536,0.130952,0.478198,0.664189,0.249212,0.692064,0.218571,0.717321,0.252367,0.401740,0.302049,0.201907,0.198260,0.191661,0.199505,0.163951,0.180012,0.223868,0.200502,0.200689,0.193867,0.160034,0.206388,0.145900,0.193684,0.193772,0.193633,0.199234,-6.091126,48.0,96.0,16.0,42.0,11.0,18.0,13.0,41.0,54.0,33.0,4.0,8.0,14.0,15.0,123.0,265.000000,18.0,17.0,14.0,48.0,3.0,114.115346,109.194151,4.941660,0.175512,1.914025,21.394906,0.052826,0.136744,0.098506,8.743547,0.602740,0.610614,0.188164,96.271151,96.271151,74.389497,0.108900,0.582882,0.188123,0.140615,0.511179,0.117131,0.094058,0.210104,2.789245,0.569122,0.430878,0.531708,0.131616,0.389409,0.104841,0.078883,0.158831,0.400093,0.679972,0.320028,0.594560,0.156132,0.689231,0.310769,0.317894,0.399580,0.200367,0.200068,0.199439,0.200160,0.203244,0.198173,0.193693,0.197318,0.198007,0.203462,0.175619,0.211259,0.195655,0.227722,0.201947,0.191826,0.199943,7.759057,ATL vs. MIA,2024-25,atlanta hawks,miami heat,2,1,0,9,0,0,18.150000,217.8,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0,3,1,0,9,0,0,2,18.150000,217.8,0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
63872,52400201,2025-04-18,1610612748,1610612737,0,1,9.0,1,0,6,0,123,1.74,2.05,48,96,16,42,11,18,13,41,54,33,4,8,14,15,265.000000,18,17,14,48,3,114.115346,109.194151,4.941660,0.175512,1.914025,21.394906,0.052826,0.136744,0.098506,8.743547,0.602740,0.610614,0.188164,96.271151,96.271151,74.389497,0.108900,0.582882,0.188123,0.140615,0.511179,0.117131,0.094058,0.210104,2.789245,0.569122,0.430878,0.531708,0.131616,0.389409,0.104841,0.078883,0.158831,0.400093,0.679972,0.320028,0.594560,0.156132,0.689231,0.310769,0.317894,0.399580,0.200367,0.200068,0.199439,0.200160,0.203244,0.198173,0.193693,0.197318,0.198007,0.203462,0.175619,0.211259,0.195655,0.227722,0.201947,0.191826,0.199943,7.759057,44.0,102.0,16.0,47.0,10.0,12.0,11.0,33.0,44.0,30.0,12.0,3.0,9.0,18.0,114.0,265.016667,21.0,14.0,22.0,56.0,8.0,108.972216,113.769398,-4.786328,0.170940,1.701450,19.786856,0.038220,0.132929,0.082033,6.828665,0.533646,0.548288,0.194796,96.542768,96.542768,70.793032,0.094415,0.515043,0.115509,0.094355,0.582867,0.189826,0.139047,0.283225,2.338658,0.528556,0.471444,0.478198,0.000000,0.421953,0.212341,0.069536,0.130952,0.478198,0.664189,0.249212,0.692064,0.218571,0.717321,0.252367,0.401740,0.302049,0.201907,0.198260,0.191661,0.199505,0.163951,0.180012,0.223868,0.200502,0.200689,0.193867,0.160034,0.206388,0.145900,0.193684,0.193772,0.193633,0.199234,-6.091126,MIA @ ATL,2024-25,miami heat,atlanta hawks,5,0,1,9,0,0,15.686667,235.3,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0,6,0,1,9,0,0,5,15.686667,235.3,0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0

# 🚀 Features avancées

In [44]:

# Ajouter les features avancées aux stats de match
#match_dataset = add_advanced_boxscore_features(match_dataset)

# MOVED TO CONFIG
# features_to_roll = cols_to_sum + cols_to_weighted_avg
# features_to_roll += [f"OPP_{col}" for col in cols_to_sum + cols_to_weighted_avg]

# Calcul des features glissantes shiftées
match_dataset = compute_rolling_features(match_dataset, "TEAM_ID", ["TEAM_ID", "GAME_DATE"], features_to_roll, N_LIST, method="ewm")

match_dataset = compute_rolling_features(match_dataset, "TEAM_ID", ["TEAM_ID", "GAME_DATE"], top_player_features_to_roll, N_LIST_TOP, method="ewm", apply_log=True)


match_dataset = compute_winrates(match_dataset, "TEAM_ID", "IS_WIN", "IS_HOME", N_LIST)
match_dataset = compute_win_ratio(match_dataset, "TEAM_ID", "IS_WIN", N_LIST)

match_dataset["IS_WIN_SHIFTED"] = match_dataset.groupby("TEAM_ID")["IS_WIN"].shift(1).fillna(0).astype(int)
match_dataset["WIN_STREAK"] = match_dataset.groupby("TEAM_ID").apply(
    lambda x: compute_win_streak(x, "TEAM_ID", "IS_WIN_SHIFTED")).reset_index(level=0, drop=True)
match_dataset = compute_side_win_streak(match_dataset, win_shifted_col="IS_WIN_SHIFTED")


# Calcul des jours de repos pour l'équipe et l'adversaire
match_dataset["DAYS_SINCE_LAST_GAME"] = compute_rest_days(match_dataset, "GAME_DATE", "TEAM_ID")
match_dataset["OPP_DAYS_SINCE_LAST_GAME"] = compute_rest_days(match_dataset, "GAME_DATE", "OPP_TEAM_ID")

# Avantage de repos
match_dataset["REST_ADVANTAGE"] = (
    match_dataset["DAYS_SINCE_LAST_GAME"] - match_dataset["OPP_DAYS_SINCE_LAST_GAME"]
)


match_dataset = compute_rolling_rest_advantage(
    match_dataset, "TEAM_ID", "IS_HOME", "REST_ADVANTAGE", N_LIST
)

match_dataset = compute_home_away_pts(
    match_dataset, "TEAM_ID", "IS_HOME", "points_traditional", "OPP_points_traditional", N_LIST
)

# match_dataset = rename_pts_against_columns(match_dataset)

match_dataset = compute_h2h(match_dataset, N_LIST)
# match_dataset = compute_h2h_pts_margin(match_dataset, N_LIST)
match_dataset = compute_h2h_season(match_dataset)
match_dataset = compute_h2h_streak(match_dataset)

match_dataset = compute_elo(match_dataset)
match_dataset = compute_elo_season(match_dataset)

match_dataset = convert_elos_to_elo_diff(match_dataset)

/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (

In [45]:
pd.options.display.max_columns = None
display(match_dataset)

        GAME_ID  GAME_DATE     TEAM_ID OPP_TEAM_ID  IS_HOME  IS_WIN  \
0      20000001 2000-10-31  1610612752  1610612755        1       0
1      20000001 2000-10-31  1610612755  1610612752        0       1
2      20000002 2000-10-31  1610612739  1610612751        0       1
3      20000002 2000-10-31  1610612751  1610612739        1       0
4      20000003 2000-10-31  1610612753  1610612764        1       1
...         ...        ...         ...         ...      ...     ...
63870  22500022 2025-10-31  1610612761  1610612739        0       1
63871  22500023 2025-10-31  1610612741  1610612752        1       0
63872  22500023 2025-10-31  1610612752  1610612741        0       0
63873  22500024 2025-10-31  1610612747  1610612763        0       0
63874  22500024 2025-10-31  1610612763  1610612747        1       0

       POINT_DIFF  has_absent  has_top_absent  num_absent  top_player_absent  \
0           -29.0           0               0           0                  0
1            29.0           0               0           0                  0
2             4.0           1               0           1                  0
3            -4.0           1               1           2                  1
4            11.0           1               0           2                  0
...           ...         ...             ...         ...                ...
63870        11.0           1               1           2                  1
63871         0.0           1               1          13                  5
63872         0.0           1               1          14                  5
63873         0.0           1               1          11                  5
63874         0.0           1               1          14                  5

       points_traditional  ODDS  OPP_ODDS  fieldGoalsMade_traditional  \
0                      72   NaN       NaN                          25
1                     101   NaN       NaN                          38
2                      86   NaN       NaN                          32
3                      82   NaN       NaN                          31
4                      97   NaN       NaN                          34
...                   ...   ...       ...                         ...
63870                 112   NaN       NaN                          40
63871                   0   NaN       NaN                           0
63872                   0   NaN       NaN                           0
63873                   0   NaN       NaN                           0
63874                   0   NaN       NaN                           0

       fieldGoalsAttempted_traditional  threePointersMade_traditional  \
0                                   70                              3
1                                   66                              3
2                                   78                              2
3                                   85                              3
4                                   79                              6
...                                ...                            ...
63870                               82                             13
63871                                0                              0
63872                                0                              0
63873                                0                              0
63874                                0                              0

       threePointersAttempted_traditional  freeThrowsMade_traditional  \
0                                      11                          19
1                                       8                          22
2                                       7                          20
3                                      10                          17
4                                      16                          23
...                                   ...                         ...
63870                                  30                          19
63871                                   0                           0
63872                                   0                           0
63873                                   0                           0
63874                                   0                           0

       freeThrowsAttempted_traditional  reboundsOffensive_traditional  \
0                                   24                             14
1                                   30                              8
2                                   32                             11
3                                   26                             12
4                                   33                              8
...                                ...                            ...
63870                               24                             10
63871                                0                              0
63872                                0                              0
63873                                0                              0
63874                                0                              0

       reboundsDefensive_traditional  reboundsTotal_traditional  \
0                                 23                         37
1                                 29                         37
2                                 41                         52
3                                 35                         47
4                                 29                         37
...                              ...                        ...
63870                             38                         48
63871                              0                          0
63872                              0                          0
63873                              0                          0
63874                              0                          0

       assists_traditional  steals_traditional  blocks_traditional  \
0                       14                   6                   4
1                       27                  10                   5
2                       16                   5                   8
3                       24                   9                   8
4                       20                  10                   9
...                    ...                 ...                 ...
63870                   27                   9                   4
63871                    0                   0                   0
63872                    0                   0                   0
63873                    0                   0                   0
63874                    0                   0                   0

       turnovers_traditional  foulsPersonal_traditional  MINUTES_PLAYED  \
0                         22                         30      240.000000
1                         13                         24      240.000000
2                         19                         27      240.000000
3                         12                         31      240.000000
4                         15                         24      240.000000
...                      ...                        ...             ...
63870                     16                         18      240.016667
63871                      0                          0        0.000000
63872                      0                          0        0.000000
63873                      0                          0        0.000000
63874                      0                          0        0.000000

       pointsOffTurnovers_misc  pointsSecondChance_misc  pointsFastBreak_misc  \
0                           12                       15                     4
1                           26                        9                    10
2                           12                       12                    14
3                           21                       13                     9
4                           28                        9                    19
...                        ...                      ...                   ...
63870                       12                       18                    12
63871                        0                        0                     0
63872                        0                        0                     0
63873                        0                        0                     0
63874                        0                        0                     0

       pointsPaint_misc  blocksAgainst_misc  offensiveRating_advanced  \
0                    22                   5                 80.922299
1                    36                   4                113.678208
2                    36                   8                 87.118465
3                    42                   8                 83.457417
4                    32                   1                 98.736875
...                 ...                 ...                       ...
63870                44                  10                112.208985
63871                 0                   0                       NaN
63872                 0                   0                       NaN
63873                 0                   0                       NaN
63874                 0                   0                       NaN

       defensiveRating_advanced  netRating_advanced  \
0                    114.464688          -33.537868
1                     80.924167           32.729556
2                     82.284514            4.836236
3                     86.645424           -3.170028
4                     86.636882           12.099993
...                         ...                 ...
63870                102.557593            9.651392
63871                       NaN                 NaN
63872                       NaN                 NaN
63873                       NaN                 NaN
63874                       NaN                 NaN

       assistPercentage_advanced  assistToTurnover_advanced  \
0                       0.163246                   0.523610
1                       0.182441                   1.177822
2                       0.135260                   0.953071
3                       0.186321                   1.655972
4                       0.142503                   0.857986
...                          ...                        ...
63870                   0.163420                   1.663421
63871                        NaN                        NaN
63872                        NaN                        NaN
63873                        NaN                        NaN
63874                        NaN                        NaN

       assistRatio_advanced  offensiveReboundPercentage_advanced  \
0                 11.026556                             0.056220
1                 20.832340                             0.049657
2                 12.727431                             0.043157
3                 19.164549                             0.044377
4                 12.904542                             0.031709
...                     ...                                  ...
63870             18.893792                             0.043179
63871                   NaN                                  NaN
63872                   NaN                                  NaN
63873                   NaN                                  NaN
63874                   NaN                                  NaN

       defensiveReboundPercentage_advanced  reboundPercentage_advanced  \
0                                 0.147483                    0.091563
1                                 0.117050                    0.092804
2                                 0.154742                    0.099091
3                                 0.128634                    0.084390
4                                 0.133742                    0.081268
...                                    ...                         ...
63870                             0.128836                    0.093612
63871                                  NaN                         NaN
63872                                  NaN                         NaN
63873                                  NaN                         NaN
63874                                  NaN                         NaN

       turnoverRatio_advanced  effectiveFieldGoalPercentage_advanced  \
0                   19.763500                               0.372955
1                   12.917368                               0.562437
2                   13.891264                               0.403829
3                    9.645229                               0.334428
4                   11.997660                               0.475912
...                       ...                                    ...
63870               11.228227                               0.554876
63871                     NaN                                    NaN
63872                     NaN                                    NaN
63873                     NaN                                    NaN
63874                     NaN                                    NaN

       trueShootingPercentage_advanced  usagePercentage_advanced  \
0                             0.436562                  0.193970
1                             0.596134                  0.194474
2                             0.477510                  0.197340
3                             0.403052                  0.190604
4                             0.520254                  0.200260
...                                ...                       ...
63870                         0.599684                  0.191658
63871                              NaN                       NaN
63872                              NaN                       NaN
63873                              NaN                       NaN
63874                              NaN                       NaN

       estimatedPace_advanced  pace_advanced  possessions_advanced  \
0                   88.699676      88.699676             43.962361
1                   88.899378      88.899378             50.502014
2                   99.597600      99.597600             55.404514
3                   98.798017      98.798017             59.042292
4                   98.899090      98.899090             61.198889
...                       ...            ...                   ...
63870               98.898722      98.898722             53.906118
63871                     NaN            NaN                   NaN
63872                     NaN            NaN                   NaN
63873                     NaN            NaN                   NaN
63874                     NaN            NaN                   NaN

       PIE_advanced  effectiveFieldGoalPercentage_fourfactors  \
0          0.039403                                  0.377483
1          0.160855                                  0.601599
2          0.027378                                  0.423046
3          0.112319                                  0.383964
4          0.118825                                  0.472056
...             ...                                       ...
63870      0.112253                                  0.571873
63871           NaN                                       NaN
63872           NaN                                       NaN
63873           NaN                                       NaN
63874           NaN                                       NaN

       freeThrowAttemptRate_fourfactors  teamTurnoverPercentage_fourfactors  \
0                              0.365924                            0.247518
1                              0.469504                            0.161353
2                              0.418163                            0.189245
3                              0.309240                            0.149999
4                              0.423020                            0.148499
...                                 ...                                 ...
63870                          0.296170                            0.179065
63871                               NaN                                 NaN
63872                               NaN                                 NaN
63873                               NaN                                 NaN
63874                               NaN                                 NaN

       oppEffectiveFieldGoalPercentage_fourfactors  \
0                                         0.598126
1                                         0.382886
2                                         0.385467
3                                         0.421320
4                                         0.486995
...                                            ...
63870                                     0.477146
63871                                          NaN
63872                                          NaN
63873                                          NaN
63874                                          NaN

       oppFreeThrowAttemptRate_fourfactors  \
0                                 0.458272
1                                 0.361238
2                                 0.306368
3                                 0.418921
4                                 0.336534
...                                    ...
63870                             0.257602
63871                                  NaN
63872                                  NaN
63873                                  NaN
63874                                  NaN

       oppTeamTurnoverPercentage_fourfactors  \
0                                   0.160368
1                                   0.246772
2                                   0.150790
3                                   0.191348
4                                   0.267238
...                                      ...
63870                               0.140061
63871                                    NaN
63872                                    NaN
63873                                    NaN
63874                                    NaN

       oppOffensiveReboundPercentage_fourfactors  foulsDrawn_misc  \
0                                       0.266661         0.000000
1                                       0.319077         0.000000
2                                       0.226623         0.000000
3                                       0.243931         0.000000
4                                       0.238280         0.000000
...                                          ...              ...
63870                                   0.284341         1.731408
63871                                        NaN              NaN
63872                                        NaN              NaN
63873                                        NaN              NaN
63874                                        NaN              NaN

       percentageFieldGoalsAttempted2pt_scoring  \
0                                      0.857836
1                                      0.839428
2                                      0.905348
3                                      0.892640
4                                      0.799790
...                                         ...
63870                                  0.641683
63871                                       NaN
63872                                       NaN
63873                                       NaN
63874                                       NaN

       percentageFieldGoalsAttempted3pt_scoring  percentagePoints2pt_scoring  \
0                                      0.142164                     0.650577
1                                      0.116266                     0.644489
2                                      0.071110                     0.619452
3                                      0.107360                     0.589287
4                                      0.200210                     0.571690

# 🧽 Nettoyage et sauvegarde

In [46]:

#TODO : see why not found in config.py after reboot
player_absent_input_cols = [
    'has_top_absent',
    'has_absent',
    'top_player_absent',
    'num_absent',
]

final_date = datetime.now().strftime('%Y-%m-%d_%H-%M-%S')
raw_save_path = os.path.join(DATA_FINAL_DATASET_DIR, f'nba_features_final_{final_date}.csv')
clean_save_path = os.path.join(DATA_FINAL_CLEANED_DATASET_DIR, f'nba_features_cleaned_final_{final_date}.csv')

os.makedirs(DATA_FINAL_DATASET_DIR, exist_ok=True)
os.makedirs(DATA_FINAL_CLEANED_DATASET_DIR, exist_ok=True)

match_dataset.to_csv(raw_save_path, index=False)

cols_to_drop = features_to_roll+top_player_features_to_roll+COLS_MATCH_REAL
#remove num_absent and top_player_absent from cols_to_drop to see if we can use them has input
cols_to_drop = [col for col in cols_to_drop if col not in player_absent_input_cols]


final_cleaned = match_dataset.drop(columns=cols_to_drop, errors='ignore')
final_cleaned.to_csv(clean_save_path, index=False)

print(f"✅ Fichier brut : {raw_save_path}")
print(f"✅ Fichier clean : {clean_save_path}")

final_cleaned

✅ Fichier brut : data/final_dataset/nba_features_final_2025-11-01_14-16-47.csv
✅ Fichier clean : data/final_cleaned_dataset/nba_features_cleaned_final_2025-11-01_14-16-47.csv

        GAME_ID  GAME_DATE     TEAM_ID OPP_TEAM_ID  IS_HOME  IS_WIN  \
0      20000001 2000-10-31  1610612752  1610612755        1       0
1      20000001 2000-10-31  1610612755  1610612752        0       1
2      20000002 2000-10-31  1610612739  1610612751        0       1
3      20000002 2000-10-31  1610612751  1610612739        1       0
4      20000003 2000-10-31  1610612753  1610612764        1       1
...         ...        ...         ...         ...      ...     ...
63870  22500022 2025-10-31  1610612761  1610612739        0       1
63871  22500023 2025-10-31  1610612741  1610612752        1       0
63872  22500023 2025-10-31  1610612752  1610612741        0       0
63873  22500024 2025-10-31  1610612747  1610612763        0       0
63874  22500024 2025-10-31  1610612763  1610612747        1       0

       POINT_DIFF  has_absent  has_top_absent  num_absent  top_player_absent  \
0           -29.0           0               0           0                  0
1            29.0           0               0           0                  0
2             4.0           1               0           1                  0
3            -4.0           1               1           2                  1
4            11.0           1               0           2                  0
...           ...         ...             ...         ...                ...
63870        11.0           1               1           2                  1
63871         0.0           1               1          13                  5
63872         0.0           1               1          14                  5
63873         0.0           1               1          11                  5
63874         0.0           1               1          14                  5

       ODDS  OPP_ODDS   SEASON  ROLL_fieldGoalsMade_traditional_3  \
0       NaN       NaN  2000-01                                NaN
1       NaN       NaN  2000-01                                NaN
2       NaN       NaN  2000-01                                NaN
3       NaN       NaN  2000-01                                NaN
4       NaN       NaN  2000-01                                NaN
...     ...       ...      ...                                ...
63870   NaN       NaN  2025-26                          42.582343
63871   NaN       NaN  2025-26                          46.261745
63872   NaN       NaN  2025-26                          37.998877
63873   NaN       NaN  2025-26                          42.578127
63874   NaN       NaN  2025-26                          42.319896

       ROLL_fieldGoalsMade_traditional_5  ROLL_fieldGoalsMade_traditional_10  \
0                                    NaN                                 NaN
1                                    NaN                                 NaN
2                                    NaN                                 NaN
3                                    NaN                                 NaN
4                                    NaN                                 NaN
...                                  ...                                 ...
63870                          43.365185                           43.887769
63871                          44.727231                           43.815233
63872                          37.998301                           38.392047
63873                          41.527665                           40.310418
63874                          41.558244                           41.064642

       ROLL_fieldGoalsMade_traditional_25  ROLL_fieldGoalsMade_traditional_50  \
0                                     NaN                                 NaN
1                                     NaN                                 NaN
2                                     NaN                                 NaN
3                                     NaN                                 NaN
4                                     NaN                                 NaN
...                                   ...                                 ...
63870                           43.086326                           42.319950
63871                           43.704611                           43.487194
63872                           39.259391                           40.339954
63873                           39.913025                           40.237170
63874                           41.747859                           42.622155

       ROLL_fieldGoalsMade_traditional_100  \
0                                      NaN
1                                      NaN
2                                      NaN
3                                      NaN
4                                      NaN
...                                    ...
63870                            41.980493
63871                            43.190106
63872                            41.092812
63873                            40.834041
63874                            42.794795

       ROLL_fieldGoalsMade_traditional_200  \
0                                      NaN
1                                      NaN
2                                      NaN
3                                      NaN
4                                      NaN
...                                    ...
63870                            41.825807
63871                            42.784834
63872                            41.109852
63873                            41.421604
63874                            42.465072

       ROLL_fieldGoalsAttempted_traditional_3  \
0                                         NaN
1                                         NaN
2                                         NaN
3                                         NaN
4                                         NaN
...                                       ...
63870                               86.101765
63871                               89.928888
63872                               91.989908
63873                               82.613496
63874                               91.685248

       ROLL_fieldGoalsAttempted_traditional_5  \
0                                         NaN
1                                         NaN
2                                         NaN
3                                         NaN
4                                         NaN
...                                       ...
63870                               88.263932
63871                               89.539580
63872                               90.586802
63873                               81.641760
63874                               90.966785

       ROLL_fieldGoalsAttempted_traditional_10  \
0                                          NaN
1                                          NaN
2                                          NaN
3                                          NaN
4                                          NaN
...                                        ...
63870                                91.215906
63871                                89.641278
63872                                88.790269
63873                                81.074165
63874                                90.475554

       ROLL_fieldGoalsAttempted_traditional_25  \
0                                          NaN
1                                          NaN
2                                          NaN
3                                          NaN
4                                          NaN
...                                        ...
63870                                92.782692
63871                                90.513201
63872                                87.881803
63873                                82.221553
63874                                91.133762

       ROLL_fieldGoalsAttempted_traditional_50  \
0                                          NaN
1                                          NaN
2                                          NaN
3                                          NaN
4                                          NaN
...                                        ...
63870                                92.123775
63871                                91.127263
63872                                88.160997
63873                                83.443574
63874                                91.905880

       ROLL_fieldGoalsAttempted_traditional_100  \
0                                           NaN
1                                           NaN
2                                           NaN
3                                           NaN
4                                           NaN
...                                         ...
63870                                 91.239948
63871                                 91.100736
63872                                 88.116492
63873                                 84.546178
63874                                 91.981943

       ROLL_fieldGoalsAttempted_traditional_200  \
0                                           NaN
1                                           NaN
2                                           NaN
3                                           NaN
4                                           NaN
...                                         ...
63870                                 90.720629
63871                                 90.342708
63872                                 87.716813
63873                                 85.641288
63874                                 91.668692

       ROLL_threePointersMade_traditional_3  \
0                                       NaN
1                                       NaN
2                                       NaN
3                                       NaN
4                                       NaN
...                                     ...
63870                             16.429328
63871                             13.666501
63872                             13.838403
63873                              9.675858
63874                             13.904858

       ROLL_threePointersMade_traditional_5  \
0                                       NaN
1                                       NaN
2                                       NaN
3                                       NaN
4                                       NaN
...                                     ...
63870                             14.899637
63871                             13.242079
63872                             13.534072
63873                              9.947224
63874                             13.464385

       ROLL_threePointersMade_traditional_10  \
0                                        NaN
1                                        NaN
2                                        NaN
3                                        NaN
4                                        NaN
...                                      ...
63870                              13.792224
63871                              13.209471
63872                              12.813958
63873                              11.115760
63874                              13.090921

       ROLL_threePointersMade_traditional_25  \
0                                        NaN
1                                        NaN
2                                        NaN
3                                        NaN
4                                        NaN
...                                      ...
63870                              13.003638
63871                              13.779243
63872                              12.196120
63873                              12.914361
63874                              13.233973

       ROLL_threePointersMade_traditional_50  \
0                                        NaN
1                                        NaN
2                                        NaN
3                                        NaN
4                                        NaN
...                                      ...
63870                              12.478501
63871                              14.219456
63872                              12.049953
63873                              13.423670
63874                              13.416360

       ROLL_threePointersMade_traditional_100  \
0                                         NaN
1                                         NaN
2                                         NaN
3                                         NaN
4                                         NaN
...                                       ...
63870                               12.033643
63871                               14.112656
63872                               12.122100
63873                               13.158924
63874                               13.445589

       ROLL_threePointersMade_traditional_200  \
0                                         NaN
1                                         NaN
2                                         NaN
3                                         NaN
4                                         NaN
...                                       ...
63870                               11.785389
63871                               13.340682
63872                               12.243555
63873                               12.567995
63874                               13.182859

       ROLL_threePointersAttempted_traditional_3  \
0                                            NaN
1                                            NaN
2                                            NaN
3                                            NaN
4                                            NaN
...                                          ...
63870                                  35.854379
63871                                  34.397494
63872                                  43.554512
63873                                  29.417820
63874                                  38.656710

       ROLL_threePointersAttempted_traditional_5  \
0                                            NaN
1                                            NaN
2                                            NaN
3                                            NaN
4                                            NaN
...                                          ...
63870                                  34.962935
63871                                  34.784321
63872                                  42.100981
63873                                  30.129589
63874                                  38.522381

       ROLL_threePointersAttempted_traditional_10  \
0                                             NaN
1                                             NaN
2                                             NaN
3                                             NaN
4                                             NaN
...                                           ...
63870                                   35.250392
63871                                   35.743368
63872                                   38.983982
63873                                   32.331729
63874                                   37.969715

       ROLL_threePointersAttempted_traditional_25  \
0                                             NaN
1                                             NaN
2                                             NaN
3                                             NaN
4                                             NaN
...                                           ...
63870                                   35.556797
63871                                   37.644749
63872                                   35.736439
63873                                   35.518170
63874                                   37.750928

       ROLL_threePointersAttempted_traditional_50  \
0                                             NaN
1                                             NaN
2                                             NaN
3                                             NaN
4                                             NaN
...                                           ...
63870                                   34.962660
63871                                   39.018714
63872                                   34.457984
63873                                   36.510096
63874                                   37.669341

       ROLL_threePointersAttempted_traditional_100  \
0                                              NaN
1                                              NaN
2                                              NaN
3                                              NaN
4                                              NaN
...                                            ...
63870                                    34.202339
63871                                    38.789505
63872                                    33.970123
63873                                    35.837515
63874                                    37.503453

       ROLL_threePointersAttempted_traditional_200  \
0                                              NaN
1                                              NaN
2                                              NaN
3                                              NaN
4                                              NaN
...                                            ...
63870                                    33.759662
63871                                    36.766681
63872                                    33.945831
63873                                    34.483850
63874                                    36.916359

       ROLL_freeThrowsMade_traditional_3  ROLL_freeThrowsMade_traditional_5  \
0                                    NaN                                NaN
1                                    NaN                                NaN
2                                    NaN                                NaN
3                                    NaN                                NaN
4                                    NaN                                NaN
...                                  ...                                ...
63870                          15.921154                          16.274646
63871                          16.329683                          17.238005
63872                          19.899369                          20.638614
63873                          20.616788                          21.808923
63874                          18.498122                          20.585585

       ROLL_freeThrowsMade_traditional_10  ROLL_freeThrowsMade_traditional_25  \
0                                     NaN                                 NaN
1                                     NaN                                 NaN
2                                     NaN                                 NaN
3                                     NaN                                 NaN
4                                     NaN                                 NaN
...                                   ...                                 ...
63870                           15.773975                           15.543184
63871                           17.845247                           17.769355
63872                           21.192443                           20.059299
63873                           21.321289                           19.844258
63874                           20.856307                           19.331344

       ROLL_freeThrowsMade_traditional_50  \
0                                     NaN
1                                     NaN
2                                     NaN
3                                     NaN
4                                     NaN
...                                   ...
63870                           15.731647
63871                           17.162682
63872                           18.731210
63873                           19.047616
63874                           18.632994

       ROLL_freeThrowsMade_traditional_100  \
0                                      NaN
1                                      NaN

In [47]:
final_cleaned.columns

Index(['GAME_ID', 'GAME_DATE', 'TEAM_ID', 'OPP_TEAM_ID', 'IS_HOME', 'IS_WIN',
       'POINT_DIFF', 'has_absent', 'has_top_absent', 'num_absent',
       ...
       'H2H_LAST_100_COUNT', 'H2H_LAST_200_DIFF', 'H2H_LAST_200_WINRATE',
       'H2H_LAST_200_COUNT', 'H2H_SEASON_WINS', 'H2H_SEASON_MATCHES',
       'H2H_SEASON_WINRATE', 'H2H_WIN_STREAK', 'ELO_DIFF', 'ELO_DIFF_SEASON'],
      dtype='object', length=1464)

In [48]:
#store end time of notebook
end_time = datetime.now()
print("End time: ", end_time)
print("Total time: ", end_time - start_time)

End time:  2025-11-01 14:20:01.630715
Total time:  0:10:33.827259